Add Toodledo [Other]
2factorauth/twofactorauth pull request #1959
Opened 2016-08-03 22:09 UTC by offsky

2016-08-04 04:40 UTC, Jawshy commented on _data/other.yml
> +      url: http://www.toodledo.com
Their site is available through HTTPS which 2factorauth prefers.

2016-08-15 17:18 UTC, stephengroat commented on _data/other.yml
> +      doc: https://www.toodledo.com/otp.php
for the `doc`, what about https://www.toodledo.com/info/help.php#168? It's not behind a sign-in page

2016-09-14 22:32 UTC, Carlgo11 commented
Merge conflict :disappointed:

2016-09-15 02:26 UTC, stephengroat requested changes
Because of additions to the `other.yml` file, the name is now out of alphabetical order. could you merge and reorder it?

2016-09-15 17:02 UTC, offsky commented
@stephengroat I have merged and reordered it so its alphabetically again.

2016-09-15 17:34 UTC, stephengroat approved these changes

2016-09-29 10:24 UTC, merged

2016-09-29 10:25 UTC, Carlgo11 commented
Sorry for the delay @offsky. Your pull request is now merged and will show up on our site soon.