Add ec council
2factorauth/twofactorauth pull request #2036
Opened 2016-09-15 18:52 UTC by stephengroat

2016-09-15 18:57 UTC, stephengroat commented
I really want to add CompTIA too, but there website login vs cert login is confusing.

I'll try to find someone who has Security+ to test

2016-10-16 00:23 UTC, fpigerre approved these changes

2016-10-16 13:57 UTC, Jawshy commented on _data/education.yml
> +      doc: https://aspen.eccouncil.org/aspen/Help/2FactorAuthentication-User_Manual.pdf
Is the documentation available outside of a PDF file? I have been under the assumption that links to PDF files are to be avoided if at all possible.

2016-10-17 01:23 UTC, stephengroat commented on _data/education.yml
> +      doc: https://aspen.eccouncil.org/aspen/Help/2FactorAuthentication-User_Manual.pdf
couldn't find anything else

2016-10-17 04:50 UTC, Jawshy requested changes
`email` TFA.

2016-10-17 04:50 UTC, Jawshy commented on _data/education.yml
> +      doc: https://aspen.eccouncil.org/aspen/Help/2FactorAuthentication-User_Manual.pdf
The documentation also specifies sending the verification code via email. See page 2 and 3. 

> 1. ...
> 2. ...
> 3. Select one of the options presented on the screen. Select My mobile number to receive
the verification code on your mobile number, My registered email to receive the ... verification code on your registered email, or No, I want to use a backup code if you have
a backup verification code, and click Use this method. 

Could you please add the following? 

```ruby
      email: Yes
```

2016-10-17 05:29 UTC, Jawshy approved these changes

2016-10-17 08:52 UTC, merged