Add comptia certs
2factorauth/twofactorauth pull request #2056
Opened 2016-09-24 00:00 UTC by thegeekkid

Shame on them!  They even made such a big deal out of 2fa on the Security+!  ;)

2016-09-24 06:47 UTC, Jawshy commented
@thegeekkid, would you like to use one of these icons instead? 

1. Their logo: 
![comptia](https://cloud.githubusercontent.com/assets/10876578/18806651/5ff4ac0a-8276-11e6-8154-103ecb526751.png) 

2. Their site's favicon: 
![comptia-2](https://cloud.githubusercontent.com/assets/10876578/18806652/656c51ec-8276-11e6-9af8-36b50a18c443.png) 

Closes https://github.com/2factorauth/twofactorauth/issues/2038

2016-09-26 02:16 UTC, Jawshy commented on _data/other.yml
> +
@thegeekkid, could you remove those blank spaces?

2016-09-26 13:18 UTC, thegeekkid commented on _data/other.yml
> +
Ahh.  Sorry about that.  Stupid Notepad++.  Should have used vim.  ;)

Pushing that and the updated icon (I'll use the favicon).  Thanks for those!

2016-09-26 15:35 UTC, stephengroat approved these changes

2016-09-29 10:38 UTC, Carlgo11 commented on _data/other.yml
> +
@thegeekkid if you use notepad++ you can install the editorconfig plugin. That way your edits will automatically comply with our mark-up guidelines. :wink: 
https://github.com/editorconfig/editorconfig-notepad-plus-plus#install-from-the-plugin-manager

2016-09-29 10:40 UTC, Carlgo11 commented
I think Comptia is better suited for the education category.

2016-09-29 13:17 UTC, stephengroat requested changes
move to `education` catagory

2016-09-29 13:23 UTC, thegeekkid commented on _data/other.yml
> +
Hmm.  Good to know.  ;)

2016-09-29 13:24 UTC, thegeekkid commented
Ya... I was debating which to put it under when I was adding it.  I'll change it over.  :)

2016-09-29 13:30 UTC, thegeekkid commented
Ok, moved it over.

2016-09-29 13:31 UTC, stephengroat approved these changes

2016-09-29 13:51 UTC, merged