Update banking with facebooks
2factorauth/twofactorauth pull request #2071
Opened 2016-09-29 16:57 UTC by stephengroat

diff looks bad, but I didn't chance that much

2016-10-15 23:45 UTC, psgs commented
@stephengroat It looks like this branch has merge conflicts. Do you think you would be able to fix them before merging?

2016-10-19 03:33 UTC, Jawshy reviewed
Facebook links `looks-good`. `url` fields could be updated and `lang` fields added for certain sites.

2016-10-19 03:33 UTC, Jawshy commented on _data/banking.yml
>        url: http://www.actorsfcu.com/
Redirects to HTTPS. Please update.

2016-10-19 03:33 UTC, Jawshy commented on _data/banking.yml
> +      facebook: BancaMediolanum
~~Should the `lang: it` (Italian) field be added?~~

2016-10-19 03:33 UTC, Jawshy commented on _data/banking.yml
>        url: http://www.cibc.ca
Now supporting HTTPS. Please update.

2016-10-19 03:33 UTC, Jawshy commented on _data/banking.yml
>        url: https://online.citibank.com/US/Welcome.c
Please use `https://online.citi.com/`.

2016-10-19 03:33 UTC, Jawshy commented on _data/banking.yml
>      - name: comdirect
Could the `lang: de` field be added for `comdirect`?

2016-10-19 03:33 UTC, Jawshy commented on _data/banking.yml
>        url: http://www.halifax.co.uk
HTTPS is available. Please update.

2016-10-19 03:33 UTC, Jawshy commented on _data/banking.yml
>        url: http://www.lloydsbank.com/
HTTPS works. Please update.

2016-10-19 03:33 UTC, Jawshy commented on _data/banking.yml
>        url: http://www.mbna.ca
Redirects to `https://www.mbna.ca/`. Please update.

2016-10-19 03:33 UTC, Jawshy commented on _data/banking.yml
>      - name: Postbank
Perhaps change the `url` to `https://www.postbank.de/` and add `lang: de` for Postbank?

2016-10-19 03:33 UTC, Jawshy commented on _data/banking.yml
>        url: http://www.tangerine.ca/
Now supports HTTPS. Please update.

2016-10-19 03:33 UTC, Jawshy commented on _data/banking.yml
>        url: http://zenbanx.ca/
Redirects to HTTPS. Please update.

2016-10-19 05:07 UTC, stephengroat commented
@Jawshy you know you can update these too, right?

2016-10-19 06:28 UTC, Jawshy commented
Updated.

2016-10-27 05:46 UTC, jamcat22 requested changes
Multiple lines are misspelled as `faceook:` instead of `facebook:`.

2016-10-27 05:46 UTC, jamcat22 commented on _data/banking.yml
> +      faceook: CIBC
Line should be changed to `facebook: CIBC`.

2016-10-27 05:46 UTC, jamcat22 commented on _data/banking.yml
> +      faceook: HuntingtonBank
Line should be changed to `facebook: HuntingtonBank`.

2016-10-27 05:46 UTC, jamcat22 commented on _data/banking.yml
> +      faceook: LendingClubTeam
Line should be changed to `facebook: LendingClubTeam`.

2016-10-27 05:46 UTC, jamcat22 commented on _data/banking.yml
> +      faceook: lloydsbank
Line should be changed to `facebook: lloydsbank`.

2016-10-27 05:46 UTC, jamcat22 commented on _data/banking.yml
> +      faceook: MandTBank
Line should be changed to `facebook: MandTBank`.

2016-10-27 05:46 UTC, jamcat22 commented on _data/banking.yml
> +      faceook: MeridianCreditUnion
Line should be changed to `facebook: MeridianCreditUnion`.

2016-10-27 05:46 UTC, jamcat22 commented on _data/banking.yml
> +      faceook: NavyFederal
Line should be changed to `facebook: NavyFederal`.

2016-10-27 05:54 UTC, jamcat22 approved these changes

2016-10-27 05:55 UTC, merged