Adding Final to the list of Banking institutions
2factorauth/twofactorauth pull request #2085
Opened 2016-10-07 07:49 UTC by arfrank

2FA stats and logo added

2016-10-07 14:26 UTC, stephengroat requested changes

2016-10-07 14:26 UTC, stephengroat commented on _data/banking.yml
> +      url: https://www.getFinal.com/
since domains are case insensitive and google return a no `www` URL, please correct `url` to `https://getfinal.com`

2016-10-07 14:27 UTC, stephengroat commented on _data/banking.yml
> +      url: https://www.getFinal.com/
Is there a `doc` to publish?

2016-10-07 20:17 UTC, arfrank commented
Not yet unfortunately. Will add when there is and also update when we move to push and totp too. 





On Fri, Oct 7, 2016 at 8:27 AM -0600, "Stephen" <notifications@github.com> wrote:












@stephengroat commented on this pull request.





In _data/banking.yml:
> +      url: https://www.fairwinds.org
+      img: fairwinds.png
+      tfa: Yes
+      sms: Yes
+      email: Yes
+      phone: Yes
+      doc: "https://www.fairwinds.org/inside/privacy/security_we.asp#multifactor-auth"
+
+    - name: Fifth Third Bank
+      url: https://www.53.com/
+      twitter: fifththird
+      img: fifththird.png
+      tfa: No
+
+    - name: Final
+      url: https://www.getFinal.com/



Is there a doc to publish?



—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.

2016-10-07 20:25 UTC, stephengroat commented
OK. just make the `url` change for now and we'll merge

2016-10-08 04:07 UTC, stephengroat commented
Since that security page doesn't mention anything about client facing two factor auth, could you remove it? we can re-add a different page when it's updated with something. thanks!

2016-10-08 04:09 UTC, arfrank commented
Done :)

On Fri, Oct 7, 2016 at 10:07 PM, Stephen <notifications@github.com> wrote:

> Since that security page doesn't mention anything about client facing two
> factor auth, could you remove it? we can re-add a different page when it's
> updated with something. thanks!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/2factorauth/twofactorauth/pull/2085#issuecomment-252401362>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAHzLJEN2dT_VQniHtm_Shg8P6ZO_VKbks5qxxcOgaJpZM4KQwrK>
> .
>

2016-10-08 04:11 UTC, stephengroat approved these changes
thanks for all the work!

2016-10-15 17:47 UTC, stephengroat commented
@arfrank you have a merge conflict. could you resolve it at your convenience?

2016-10-15 19:43 UTC, arfrank commented
@stephengroat Now fixed, not sure why it's seeing whitespace changes, didn't touch anything but our entries, but happy to revert if needed

2016-10-15 23:31 UTC, fpigerre approved these changes

2016-10-16 05:01 UTC, merged