Added Any.do
2factorauth/twofactorauth pull request #2115
Opened 2016-10-13 20:23 UTC by moritzsternemann

Fixed #2114

2016-10-13 20:25 UTC, stephengroat approved these changes

2016-10-13 20:25 UTC, stephengroat commented
thanks for the pr @moritzsternemann!

2016-10-13 20:55 UTC, stephengroat commented
Please revert the `Added ProjectFi` commit. we like to do one site per PR

2016-10-13 20:56 UTC, stephengroat requested changes
Please revert the `Added ProjectFi` commit. we like to do one site per PR

2016-10-13 20:56 UTC, stephengroat commented on _data/utilities.yml
> +    - name: Project Fi
please remove the projectfi

2016-10-13 20:57 UTC, moritzsternemann commented
Yep, sorry - I meant to create another branch :P

2016-10-13 21:08 UTC, stephengroat approved these changes

2016-10-15 17:45 UTC, stephengroat commented
@moritzsternemann you have a merge conflict. could you resolve it?

2016-10-16 16:04 UTC, Jawshy commented on _data/other.yml
> +      facebook: Any.DO
@`Any.do`*

2016-10-16 21:15 UTC, moritzsternemann commented on _data/other.yml
> +      facebook: Any.DO
What do you mean?

2016-10-16 21:24 UTC, Carlgo11 commented on _data/other.yml
> +      facebook: Any.DO
@moritzsternemann he means that you've incorrectly capitalized a couple of characters for the facebook name. It should be `Any.do` and not `Any.DO`

2016-10-17 03:49 UTC, Jawshy commented on _data/other.yml
> +      facebook: Any.DO
Yes. I should have clarified by initial comment. Anyway, thanks for correcting the case. `looks-good`

2016-10-17 04:25 UTC, merged