Add Hexonet [Domains]
2factorauth/twofactorauth pull request #2131
Opened 2016-10-17 15:51 UTC by vgarmash

2016-10-17 16:03 UTC, RichJeanes commented
Please add the ```img``` tag to the entry.

If you need more info, please check out the [Wiki](https://github.com/2factorauth/twofactorauth/wiki) or the [Contributing doc](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md).

2016-10-17 16:12 UTC, Jawshy requested changes
HTTPS and doc.

2016-10-17 16:12 UTC, Jawshy commented on _data/domains.yml
> +      url: http://www.hexonet.net
That URL directs to `https://www.hexonet.net/` (HTTPS). Please use that instead.

2016-10-17 16:12 UTC, Jawshy commented on _data/domains.yml
> +      doc: https://cp.hexonet.net/cp2/downloads/2FA.pdf
Do you know if they have the documentation available on a normal webpage - not a PDF file? If so then please use that instead.

2016-10-17 16:16 UTC, vgarmash commented on _data/domains.yml
> +      url: http://www.hexonet.net
Fixed

2016-10-17 16:18 UTC, vgarmash commented on _data/domains.yml
> +      url: http://www.hexonet.net
This is the only documentation link about it. The link itself is located under the authentication form.
![2016-10-17_12-17-48](https://cloud.githubusercontent.com/assets/1226001/19445788/c71355d6-9463-11e6-8341-c4c65e3c93b2.png)

2016-10-17 16:23 UTC, vgarmash commented on _data/domains.yml
> +      doc: https://cp.hexonet.net/cp2/downloads/2FA.pdf
This is the only documentation I have found. The link to 2FA instructions is located under the authentication form. 
![2016-10-17_12-17-48](https://cloud.githubusercontent.com/assets/1226001/19445949/7d2f4e42-9464-11e6-9ec4-423ed252c699.png)

There is nothing about it at https://wiki.hexonet.net/wiki/Main_Page.

2016-10-17 16:52 UTC, Jawshy approved these changes

2016-10-18 03:48 UTC, Jawshy commented
@vgarmash, would you like to use the following image instead? It just has some minor tweaks. 

![hexonet](https://cloud.githubusercontent.com/assets/10876578/19463660/4ba4c598-9539-11e6-97c3-6b44f01e6f48.png)

2016-11-02 15:01 UTC, vgarmash commented
@Jawshy Your picture is 715 bytes while mine is 315 bytes. The actual X symbol is smaller on yours which should look better after the auto-rounding. Although you have transparent background instead of white. If your website engine will add the white background automatically then it is probably OK to use yours. Otherwise it will look weird as all other icons have white background.

2016-11-02 15:24 UTC, Jawshy commented
For comparison, [10Dollar](https://github.com/2factorauth/twofactorauth/blob/361f47a081a44820c93da8399f5778d2ee61332c/img/domains/10dollar.png) has a white background whilst [123 Reg](https://github.com/2factorauth/twofactorauth/blob/992db3ee802d6a605f7fe7dbe4420bb75c37559b/img/domains/123reg.png) does not. They both appear with a white background on the [website](https://twofactorauth.org/).

2016-11-02 15:28 UTC, vgarmash commented
Ok then. I will put your picture instead of mine.

2016-11-02 15:42 UTC, vgarmash commented
@Jawshy Please check why the build fails now. By the way - the last warning is about file size. Could it be that your image is too big?

2016-11-02 15:46 UTC, stephengroat commented
#2173 fixes the issue

2016-11-02 15:55 UTC, vgarmash commented
Thanks, @stephengroat. In this case I will just wait and watch.

2016-11-07 05:58 UTC, Jawshy approved these changes
`looks-good`

2016-11-18 07:01 UTC, merged

2016-11-18 07:02 UTC, psgs commented
Thanks for the pull request @vgarmash! :+1: