update entry for PythonAnywhere, now has software 2fa
2factorauth/twofactorauth pull request #2147
Opened 2016-10-20 18:45 UTC by hjwp

2016-10-20 18:54 UTC, stephengroat approved these changes
thanks for the pr @hjwp!

2016-10-21 02:44 UTC, Jawshy requested changes
@hjwp, is there any documentation about their support for software 2FA?

2016-10-21 11:16 UTC, hjwp commented
there is not, no.  it's a soft launch.  i'll update the entry once docs are available though.

2016-10-21 13:21 UTC, Jawshy approved these changes

2016-10-21 13:31 UTC, merged