update finance with facebooks
2factorauth/twofactorauth pull request #2165
Opened 2016-10-27 16:46 UTC by stephengroat

2016-10-28 03:02 UTC, Jawshy commented on _data/finance.yml
> +      facebook: shoeboxed
I received this message - including when logged in - when trying to view their Facebook page: 

```
Sorry, this content isn't available at the moment
The link you followed may have expired, or the Page may only be visible to an audience that you aren't in.
Go back to the previous page · Go to News Feed · Visit our Help Centre
```

Is anyone else experiencing this?

2016-10-28 03:05 UTC, Jawshy commented on _data/finance.yml
> +      facebook: transferwiseUS
As with https://github.com/2factorauth/twofactorauth/pull/2164, what about using non-region specific pages instead? ([transferwise](https://www.facebook.com/transferwise/))

2016-10-28 16:38 UTC, stephengroat commented on _data/finance.yml
> +      facebook: shoeboxed
i think this, like the `spotify` etc. stuff, is a result of facebook serving pages based off of some sort of geographic information (IP address, facebook profile, etc)

2016-12-11 13:17 UTC, Jawshy requested changes
Everything looks good except this one teensy-tiny lil' thing.

2016-12-11 13:17 UTC, Jawshy commented on _data/finance.yml
> +      facebook: inex.finance
I'm not sure about this one. I can't find a link to it from their website. I only end up at [fentury](https://www.facebook.com/fentury).

2016-12-11 22:54 UTC, stephengroat commented on _data/finance.yml
> +      facebook: inex.finance
maybe geo-specific
![screenshot 2016-12-11 at 14 53 44](https://cloud.githubusercontent.com/assets/1159138/21084049/b1760376-bfb1-11e6-8b11-9864923bcd7a.png)

2016-12-12 02:40 UTC, Jawshy approved these changes

2016-12-14 01:01 UTC, mxxcon commented on _data/finance.yml
> +      url: http://www.hellowallet.com
Maybe leave it as https in case in the future they won't downgrade? And similar mindset for other similar changes?

2016-12-14 03:35 UTC, Jawshy commented on _data/finance.yml
> +      url: http://www.hellowallet.com
Done - https://github.com/2factorauth/twofactorauth/pull/2165/commits/4764ece46eb1ee8946668475a7af42dbd7c03f38.

2016-12-17 21:30 UTC, merged