update customer.io with sw tfa
2factorauth/twofactorauth pull request #2167
Opened 2016-10-27 19:37 UTC by stephengroat

#2166

2016-10-27 21:33 UTC, jamcat22 requested changes

2016-10-27 21:33 UTC, jamcat22 commented on _data/communication.yml
The doc URL given in the previous issue should be added.
`doc: https://customer.io/docs/two-factor-auth.html`

2016-10-28 03:20 UTC, Jawshy approved these changes

2016-10-29 20:09 UTC, jamcat22 approved these changes

2016-10-29 20:09 UTC, merged