Add InterNetX
2factorauth/twofactorauth pull request #2187
Opened 2016-11-21 13:35 UTC by InterNetX

Add InterNetX Icon and Data

2016-11-21 15:38 UTC, stephengroat requested changes
@InterNetX we tend to only list companies under a single category. what do you think the primary category for InterNetX is, maybe `domains`?

2016-11-21 16:08 UTC, Jawshy requested changes
`doc`

2016-11-21 16:08 UTC, Jawshy commented on _data/domains.yml
> +      doc: https://www.internetx.com/en/domains/autodns/
I cannot see any documentation about SMS or software 2FA on that webpage. Are you sure that is the correct page?

2016-11-21 16:18 UTC, InterNetX commented on _data/domains.yml
> +      doc: https://www.internetx.com/en/domains/autodns/
There it is https://www.internetx.com/en/domains/autodns/domain-safe/ or do you need a full documentation?

2016-11-21 16:33 UTC, Jawshy commented on _data/domains.yml
> +      doc: https://www.internetx.com/en/domains/autodns/
Full documentation would be ideal.

2016-11-22 20:59 UTC, stephengroat approved these changes

2017-01-11 10:17 UTC, Carlgo11 commented
How should we continue with this PR?

2017-01-11 14:18 UTC, Jawshy commented
Full documentation or close.

2017-01-11 23:57 UTC, Carlgo11 commented
And since the last response from the author is on the 21st of November I guess it's the later option.

2017-01-11 23:57 UTC, closed without merging