Add John Hancock (jhpensions.com) to unsupported services list
2factorauth/twofactorauth pull request #2191
Opened 2016-11-24 13:52 UTC by rwinikates

2016-11-24 14:18 UTC, Jawshy requested changes

2016-11-24 14:18 UTC, Jawshy commented on _data/investing.yml
> +      url: https://www.jhpensions.com
I cannot access this domain and neither can [Is It Down Right Now](http://www.isitdownrightnow.com/jhpensions.com.html).

2016-11-25 02:27 UTC, Jawshy commented on _data/investing.yml
> +      url: https://www.jhpensions.com
Did you mean to write `https://www.jhancockpensions.com/`, @rwinikates?

2016-11-28 14:14 UTC, rwinikates commented on _data/investing.yml
> +      url: https://www.jhpensions.com
@Jawshy yep! jhpensions.com 301s me to that full url, apologies for the issues. Will fix.

2016-11-28 14:30 UTC, stephengroat approved these changes

2016-12-11 13:27 UTC, Jawshy requested changes
The Twitter handle and Facebook page both link to `http://www.johnhancock.com/` not `https://www.jhancockpensions.com`. :confused:

2017-01-08 23:45 UTC, Carlgo11 commented
Closing due to inactivity.

2017-01-08 23:45 UTC, closed without merging