Add Migadu
2factorauth/twofactorauth pull request #2195
Opened 2016-11-27 19:18 UTC by AndrewKvalheim

This service has been getting attention [on HN][hn].

  [hn]: https://news.ycombinator.com/item?id=13048334

2016-11-27 21:13 UTC, stephengroat approved these changes
thanks for the pr @AndrewKvalheim!

2017-01-08 23:52 UTC, Carlgo11 requested changes
Sorry for the long delay! 😞 
I'm not 100% sure that the twitter handle you added really is Migadu. Could you please remove that line?
When that's done just ping me and I'll merge this PR right away.

Again, sorry for having to wait so long for a response!
//Carl ⛄️

2017-01-09 15:30 UTC, AndrewKvalheim commented
@Carlgo11 Removed, thanks.

2017-01-09 21:50 UTC, Carlgo11 approved these changes

2017-01-09 21:50 UTC, merged