Add ACCU
2factorauth/twofactorauth pull request #2198
Opened 2016-11-28 18:56 UTC by vgarmash

Add America’s Christian Credit Union which supports MFA

2016-11-28 19:30 UTC, stephengroat requested changes
@vgarmash thanks for the PR. could you add an image?

2016-11-28 19:32 UTC, vgarmash commented
I don't have an image and their logo is not square so I am not sure if I 
can make one properly...


On 11/28/16 2:30 PM, Stephen wrote:
>
> *@stephengroat* requested changes on this pull request.
>
> @vgarmash <https://github.com/vgarmash> thanks for the PR. could you 
> add an image?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/2factorauth/twofactorauth/pull/2198#pullrequestreview-10393946>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe-auth/ABK1EZWF3JJOeHGUEUgIF_c28D21NgtIks5rCyvmgaJpZM4K-IuS>.
>

2016-11-28 19:53 UTC, vgarmash commented
Added logo. Check it out.

2016-11-28 20:33 UTC, stephengroat commented
You'll need to properly alphabetize `_data/banking.yml` accord to [travis](https://travis-ci.org/2factorauth/twofactorauth/builds/179552210)

2016-11-28 20:43 UTC, vgarmash commented
@stephengroat Can you please help me? After what record should I put ACCU?

2016-11-28 20:45 UTC, stephengroat commented
try it before the `America First Credit Union` entry?

2016-11-28 21:13 UTC, vgarmash commented
@stephengroat Please check now.

2016-11-28 21:18 UTC, vgarmash commented
@stephengroat I tried before and after America First Credit Union and I got error both times... Please help.

2016-11-28 21:23 UTC, vgarmash commented
I squashed all commits into 1

2016-11-28 21:28 UTC, stephengroat approved these changes

2016-11-28 21:28 UTC, stephengroat commented
looks good. Thanks for all the work @vgarmash!

2016-11-29 01:49 UTC, Jawshy commented on _data/banking.yml
> +      doc: https://www.americaschristiancu.com/business/services/online-banking-bill-pay.html
For me this link is HTTP, not HTTPS.

2016-11-29 02:01 UTC, Jawshy requested changes
I followed the provided documentation, but I can't see where they specify the categories of two/multi-factor authentication (I.e. SMS, phone, and email). I can only see that there is 2FA/MFA.

2016-11-29 03:38 UTC, vgarmash commented
Yes, in the documentation they do not explain it. Actually MFA is enabled for everyone by default. I registered there today and I got a MFA screen with 3 options and I chosen get code by email and it worked fine. I can give you a screen-shot of it.

2016-11-29 03:39 UTC, vgarmash commented on _data/banking.yml
> +      doc: https://www.americaschristiancu.com/business/services/online-banking-bill-pay.html
Link work any way - it just redirects from https to http...

2016-11-29 04:00 UTC, Jawshy commented
> I can give you a screen-shot of it. 

Please do.

2016-11-29 04:22 UTC, vgarmash commented
This is on mobile.
On Nov 28, 2016 11:00 PM, Jawsh <notifications@github.com> wrote:
I can give you a screen-shot of it.

Please do.

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.

2016-12-01 02:00 UTC, vgarmash commented
@stephengroat @Jawshy Guys, do you have any other questions?

2016-12-01 04:25 UTC, Jawshy commented
That's all from me, @vgarmash. Thanks again.

2016-12-01 04:25 UTC, Jawshy approved these changes

2016-12-01 05:22 UTC, merged