Add LCN.com
2factorauth/twofactorauth pull request #2202
Opened 2016-11-28 21:23 UTC by rubenarakelyan

2016-11-28 21:35 UTC, stephengroat requested changes
could you fix the image size? it should be 32x32

2016-11-28 21:48 UTC, stephengroat requested changes
try using tinypng.com to reduce the image size

2016-11-28 22:01 UTC, stephengroat approved these changes

2017-01-09 00:45 UTC, psgs commented
Thanks for the pull request @rubenarakelyan! 👍

2017-01-09 00:45 UTC, merged