Add FS Data
2factorauth/twofactorauth pull request #2216
Opened 2016-12-05 22:12 UTC by cez81

2016-12-07 18:44 UTC, stephengroat approved these changes

2017-01-08 23:36 UTC, Carlgo11 requested changes

2017-01-08 23:36 UTC, Carlgo11 commented on _data/hosting.yml
> +      facebook: fsdata
Please add their email address info@fsdata.se as well. 
`email_address: info@fsdata.se`

2017-01-09 14:21 UTC, Jawshy approved these changes
:+1:

2017-01-09 21:43 UTC, Carlgo11 approved these changes

2017-01-09 21:43 UTC, merged