Added BasisCode Compliance Software to other.yml
2factorauth/twofactorauth pull request #2223
Opened 2016-12-08 02:46 UTC by baileybasiscode

Added BasisCode Compliance Software because it has 2FA and contains private and secure information

2016-12-08 02:55 UTC, Jawshy requested changes
Thanks for submitting a pull request, @baileybasiscode. Could you please add an image for the site? The image will need to be 32 by 32 pixels, PNG format, and under 2,500 bytes in size. 

[Travis CI Build](https://travis-ci.org/2factorauth/twofactorauth/jobs/182165605)
```
BasisCode Compliance image not found.
```

2016-12-08 02:57 UTC, Jawshy commented on _data/other.yml
> +      img: http://basiscode.com/wp-content/uploads/2016/10/BasisCode-Compliance.png
See [FAQ_New_TFA_SITE](https://github.com/2factorauth/twofactorauth/wiki/FAQ_New_TFA_SITE) for how to correctly add an image.

2016-12-08 02:58 UTC, Jawshy commented on _data/other.yml
> +      phone: Yes
Is there any public documentation for how two-factor authentication is implemented on the site?

2016-12-12 22:43 UTC, baileybasiscode commented
Rich/all,

Thanks for the help and guidance. I believe I've figured it out (new to github). I've uploaded a new file (basiscode.png) to the img/other directory under the same branch (patch-3). 

About the text version of the png. I saw that I could create a new file, but not upload. So, I tried to create a new png file in the directory, then copy the "text" version of the file into the newly created file. Thanks for the comments as I was able to upload into the correct branch and submit.

Joe

2016-12-12 23:08 UTC, Carlgo11 commented
Hello Joe,
I'm afraid the logo you uploaded doesn't fit as it's 32x17 pixels instead of 32x32.
It's also not a very good image as it's [extremely hard to make out what it says](https://raw.githubusercontent.com/baileybasiscode/twofactorauth/262e52db6921ca689146c0ce7d8ea9084fbc0aa9/img/other/basiscode.png) when it's on such a small scale. Maybe you could find another image that better suits smaller sizes and preferably a squared one.

I can help you upload and shrink it if you prefer, however I need to know which image to use.
Just get back to me with a link or upload it using GitHub's drag and drop feature for comments.
![index](https://cloud.githubusercontent.com/assets/3535780/21120547/27b775e4-c0c8-11e6-9bf8-66b578ee9e11.png)

//Carl

2016-12-12 23:18 UTC, baileybasiscode commented
Carl/All,

Thanks for your patience. I played around and figure out how to create the graphic with the correct size. 

Thanks again!
Joe

2016-12-12 23:28 UTC, RichJeanes commented
That's wonderful that you have figured it out (and welcome to GitHub!).

However, Carlgo11's and my comment still stand: That icon is not very well suited to being scaled to such a small size. Perhaps something in the ballpark of the site's favicon would be more appropriate?

2016-12-12 23:48 UTC, baileybasiscode commented
Thanks for the feedback.. I'll work on it this evening and send something tomorrow. Again, thanks!

2016-12-13 03:44 UTC, Jawshy submitted a review, later dismissed
> Is there any public documentation for how two-factor authentication is implemented on the site? 

See [FAQ_New_TFA_SITE](https://github.com/2factorauth/twofactorauth/wiki/FAQ_New_TFA_SITE).

2016-12-13 03:53 UTC, Carlgo11 submitted a review, later dismissed
Needs a new logo as requested in [266583020](https://github.com/2factorauth/twofactorauth/pull/2223#issuecomment-266583020) and [266587168](https://github.com/2factorauth/twofactorauth/pull/2223#issuecomment-266587168).

2016-12-19 22:23 UTC, baileybasiscode commented
Ok, I just submitted 2 pull requests on changeset 3 which includes a new graphic and a url to the 2FA documentation. Feel free to let me know if there are any issues. Thanks again. Joe

2016-12-20 02:27 UTC, Jawshy requested changes
> Ok, I just submitted 2 pull requests on changeset 3 which includes a new graphic and a url to the 2FA documentation. Feel free to let me know if there are any issues. Thanks again. Joe 

[Travis CI is having an issue](https://travis-ci.org/2factorauth/twofactorauth/jobs/185297262) with the [image that was used](https://github.com/baileybasiscode/twofactorauth/blob/9d5fab73bdb25294a6c846c20543704c517022c8/img/other/basiscode.png). Could you please replace it with the below image, @baileybasiscode? 

![basiscode-resaved](https://cloud.githubusercontent.com/assets/10876578/21336166/4cd1b456-c6af-11e6-8d95-604411f4bb5f.png)

2016-12-22 17:18 UTC, baileybasiscode commented
Just pushed the latest update which includes the graphic. Thanks again for all of the help.
Joe

2017-01-05 04:25 UTC, Jawshy approved these changes

2017-01-05 04:27 UTC, merged

2017-01-05 13:40 UTC, baileybasiscode commented
**You guys are the best! Thanks for all of your help! Joe**