Add Vantiv to Payments section
2factorauth/twofactorauth pull request #2228
Opened 2016-12-08 23:14 UTC by oliver-donorschoose

Vantiv is one of the biggest payment processors on the planet. Every year, they process >20B billion transactions and $726B in volume. Unfortunately, their merchant-facing console/portal does not offer 2FA.

2016-12-09 02:09 UTC, Jawshy requested changes
Thanks for submitting a pull request, @oliver-donorschoose. 

Could you please add their Facebook page? 
```ruby
      facebook: Vantiv
```

[Travis CI](https://travis-ci.org/2factorauth/twofactorauth/jobs/182438994): 
```
1. img/payments/vantiv.png is not 32x32 pixels.
2. img/payments/vantiv.png should not be larger than 2500 bytes. It is currently 24786 bytes.
```

Would you also be able to edit the image so that it is both 32 by 32 pixels and under 2,500 bytes? You can use tinypng.com to compress the image once it has been resized.

2016-12-09 02:09 UTC, Jawshy commented on _data/payments.yml
> +
Please remove these blank spaces.

2016-12-09 17:26 UTC, oliver-donorschoose commented
@Jawshy Thanks for the feedback, we should be good to go now! Can you approve?

2016-12-09 17:37 UTC, stephengroat approved these changes

2016-12-10 07:03 UTC, Jawshy commented
That looks better. Thanks again, @oliver-donorschoose. I have decided to also update the icon to the same one that their website uses as a favicon.

2016-12-10 07:03 UTC, Jawshy approved these changes

2016-12-10 17:09 UTC, oliver-donorschoose commented
Thanks @Jawshy! Although I don't see the addition at https://twofactorauth.org/ > Payments... Let me know if there's a final step I need to take.

2016-12-11 03:12 UTC, mxxcon approved these changes

2016-12-11 03:13 UTC, merged

2016-12-11 03:38 UTC, Jawshy commented
@oliver-donorschoose, there are two steps to go after approval. They are merging into the `master` branch (done just a few minutes ago) and then merging into the `gh-pages` branch at which point the changes will go live. See [FAQ_Merge](https://github.com/2factorauth/twofactorauth/wiki/FAQ_Merge) for more details on the process.