1Password supports 2FA for Teams accounts using Duo Security
2factorauth/twofactorauth pull request #2248
Opened 2016-12-14 18:32 UTC by gingerbeardman

See https://twitter.com/1Password/status/809091553381777409

2016-12-14 18:40 UTC, mxxcon requested changes
please don't include amazon change with this PR. please make it a separate PR.

2016-12-14 18:42 UTC, gingerbeardman commented
Apologies, GitHub Desktop didn't warn me.

2016-12-14 19:33 UTC, mxxcon approved these changes

2016-12-14 19:34 UTC, mxxcon commented
That's a pretty crappy setup of them. :/ Use only 2fa service which requires payment to that service.

2016-12-14 19:36 UTC, RichJeanes requested changes

2016-12-14 19:36 UTC, RichJeanes commented on _data/retail.yml
> -
Please do not remove new lines at the end of files. They should be there in all of our `.yml` files. See our `.editorconfig` for our formatting rules. If you use an editor that supports plugins, you can look for and install the Editor Config plug-in.

2016-12-14 19:46 UTC, gingerbeardman commented
ok, thanks for the info.

changed

2016-12-14 21:37 UTC, Carlgo11 commented
I think that maybe we should wait for them to roll it out everywhere. From past experience they could very well disable 2FA again or never activate it for individuals.

2016-12-14 21:53 UTC, mxxcon commented
@Carlgo11 but that's why there's exception text?

2016-12-14 21:54 UTC, Carlgo11 commented
@mxxcon yeah but then `tfa` is set to true.

2016-12-15 04:03 UTC, RichJeanes approved these changes

2016-12-15 07:33 UTC, Carlgo11 requested changes
Only partially added. Don't think `tfa` should be set to `Yes` then.

2016-12-15 08:25 UTC, jamcat22 approved these changes
I say we should add it with the exception. We've taken this approach on other sites we've added, including Square, Dyn, Coinify, and arguably PayPal and Apple, whose 2FA systems don't protect their entire userbase and various sign in systems.

2016-12-15 12:25 UTC, gingerbeardman commented
FWIW I search for other entries that rely on Duo and copied the way their entry was set up. Specifically, University of Michigan.

2016-12-15 21:19 UTC, Carlgo11 commented
@jamcat22 what if we put it as a `status` link then? To still put pressure on them.

2017-01-09 00:19 UTC, psgs commented
A `status` link sounds like a good compromise, given that payment is required in order to use 2FA for 1Password.

2017-01-09 09:56 UTC, gingerbeardman commented
redone as status link

2017-01-09 21:53 UTC, Carlgo11 approved these changes

2017-01-11 09:44 UTC, merged