Amazon UK supports 2FA via Amazon.com
2factorauth/twofactorauth pull request #2249
Opened 2016-12-14 18:47 UTC by gingerbeardman

2016-12-14 19:38 UTC, RichJeanes requested changes

2016-12-14 19:38 UTC, RichJeanes commented on _data/retail.yml
> -
Please do not remove new lines at the end of files. They should be there in all of our `.yml` files. See our `.editorconfig` for our formatting rules. If you use an editor that supports plugins, you can look for and install the Editor Config plug-in.

2016-12-14 19:39 UTC, mxxcon commented on _data/retail.yml
> -
[.editorconfig](https://github.com/2factorauth/twofactorauth/blob/master/.editorconfig) is like a style guide for files. how many spaces to use, what kind of linebreaks, etc etc. see http://editorconfig.org/

2016-12-14 19:45 UTC, gingerbeardman commented
understood, thanks for the info.

2016-12-14 19:50 UTC, mxxcon commented
I'm a little bit worried by this. If this is a glitch/bug in Amazon's login system, once Amazon fixes this might bite people in the butt and lock them out of their accounts.
It would be nice to contact Amazon UK support and confirm with them that this is safe to use. 🤔

2016-12-15 04:04 UTC, RichJeanes approved these changes

2016-12-15 05:55 UTC, Carlgo11 commented
Does it make sense to have multiple Amazon sites listed here? As far as I can tell 2FA works on all of them the same way.

> On 15 Dec 2016, at 05:04, Rich Jeanes <notifications@github.com> wrote:
> 
> @RichJeanes approved this pull request.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

2016-12-15 05:57 UTC, gingerbeardman commented
@Carlogo11 I think you're right, maybe just stick with .com URL, make sure Amazon name doesn't include any domain suffix, and make a note in the exception text?

2016-12-17 21:29 UTC, Carlgo11 approved these changes
Looks good to me! 👍

2016-12-28 18:10 UTC, merged