Add labanquepostale.fr
2factorauth/twofactorauth pull request #2300
Opened 2017-01-11 20:58 UTC by divayprakash

2017-01-12 01:03 UTC, Jawshy requested changes

2017-01-12 01:03 UTC, Jawshy commented on _data/banking.yml
> +      twitter: labanquepostale
Please use the same case that their Twitter handle uses: [`LaBanquePostale`](https://twitter.com/labanquepostale).

2017-01-12 01:35 UTC, fpigerre requested changes

2017-01-12 01:35 UTC, psgs commented on _data/banking.yml
> +
Hello @divayprakash,
Would you also be able to add the following line: `lang: fr` please?

2017-01-12 07:01 UTC, divayprakash commented on _data/banking.yml
> +
@psgs Added in d368469

2017-01-12 07:02 UTC, divayprakash commented on _data/banking.yml
> +      twitter: labanquepostale
@Jawshy Updated in d368469

2017-01-12 07:03 UTC, Jawshy commented on _data/banking.yml
> +      twitter: labanquepostale
You changed the `name` instead of the `twitter`.

2017-01-12 10:41 UTC, divayprakash commented on _data/banking.yml
> +      twitter: labanquepostale
Fixed in 5c44a6c

2017-01-12 14:21 UTC, Jawshy approved these changes

2017-01-13 04:16 UTC, fpigerre approved these changes

2017-01-13 04:17 UTC, psgs commented
Thanks for the pull request @divayprakash! 👍

2017-01-13 04:17 UTC, merged