Add orange.fr
2factorauth/twofactorauth pull request #2302
Opened 2017-01-12 12:59 UTC by divayprakash

Closes #2257

2017-01-12 13:42 UTC, Carlgo11 approved these changes

2017-01-12 14:32 UTC, Jawshy requested changes

2017-01-12 14:32 UTC, Jawshy commented on _data/utilities.yml
> +      url: https://orange.fr/
The current `url` redirects to a HTTP page for me. @divayprakash, please use `https://www.orange.fr/portail` instead.

2017-01-12 14:38 UTC, divayprakash commented on _data/utilities.yml
> +      url: https://orange.fr/
Fixed in ca69c48

2017-01-12 14:41 UTC, Jawshy commented on _data/utilities.yml
> +      url: https://orange.fr/
Needs the `www.`.

2017-01-12 15:31 UTC, divayprakash commented on _data/utilities.yml
> +      url: https://orange.fr/
Fixed in 04bfa7c

2017-01-13 00:48 UTC, Jawshy approved these changes

2017-01-13 00:51 UTC, merged