Add mbconnectline.com (#2301)
2factorauth/twofactorauth pull request #2309
Opened 2017-01-16 07:57 UTC by JohannesRegner

2017-01-26 16:17 UTC, stephengroat approved these changes

2017-01-27 09:14 UTC, Carlgo11 commented on _data/remote.yml
> +      doc: http://www.cc-onlinehelp.com/en/#index/administrati/users/authenticati/authenticati.html
I don't see any link between the doc page and the main site.

2017-01-27 09:17 UTC, jamcat22 requested changes

2017-01-27 09:17 UTC, jamcat22 commented on _data/remote.yml
> +    - name: MB connect line
On their website, their name seems to be stylized with each word capitalized. Please change this line to `- name: MB Connect Line`.

2017-01-27 10:03 UTC, JohannesRegner commented
Hi, mbconnectline.com is the main site from our company, we had public portals, https://rsp-vpn.mbconnect24.net/portal/ and sell virtual servers, so there is no general domain.

2017-02-12 22:51 UTC, jamcat22 approved these changes

2017-02-12 22:51 UTC, merged