BitGo has removed SMS 2FA support
2factorauth/twofactorauth pull request #2312
Opened 2017-01-18 16:10 UTC by jlopp

We have removed SMS 2FA due to the rise in phone porting attacks https://blog.bitgo.com/bitgo-phasing-out-sms-based-2-factor-authentication-96db16fdd63a

2017-01-18 17:27 UTC, Carlgo11 requested changes
```<------------ ERROR ------------>

1. BitGo: The YAML tag 'sms' should either have a value set to 'Yes' or not be used at all. (Current value: 'false')
```

2017-01-18 17:47 UTC, jlopp commented
Removed sms tag.

2017-01-18 18:10 UTC, Carlgo11 commented
The doc link still refers to SMS authentication.

https://bitgo.zendesk.com/hc/en-us/articles/205139615-Two-Step-Authentication-via-SMS

2017-01-18 18:17 UTC, mxxcon commented
from their blog:

> Additionally, effective immediately, BitGo has withdrawn SMS as a 2FA method for all new user signups. New users must use client-side 2FA systems such as TOTP with Google Authenticator.
If you’re an existing BitGo user using SMS 2FA, you can continue to use it. However, we strongly recommend that you migrate to alternate methods as soon as possible.

2017-01-18 18:18 UTC, jlopp commented
Yes, we need to update the Zendesk article - I've tasked our Zendesk person with doing that.

2017-01-18 19:09 UTC, jlopp commented
SMS zendesk post has been removed; should be good to go!

2017-01-19 03:25 UTC, Jawshy requested changes
[How to setup Two Factor Authentication?](https://bitgo.zendesk.com/hc/en-us/articles/211880046-How-to-setup-Two-Factor-Authentication-): 
> 4. You can setup Two Factor Authentication using Google authenticator or Yubikey

So there is [hardware](https://github.com/2factorauth/twofactorauth/wiki/FAQ_Categories) support too. @jlopp, would you like to add the following on a new line below `software`? 

```ruby
       hardware: Yes
```

2017-01-19 03:46 UTC, jlopp commented
Good catch; thanks. Added hardware tag.

2017-01-19 03:50 UTC, Jawshy approved these changes

2017-01-19 03:51 UTC, jamcat22 approved these changes

2017-01-19 07:02 UTC, Carlgo11 approved these changes

2017-01-19 07:02 UTC, merged