Add SatoshiTango
2factorauth/twofactorauth pull request #2321
Opened 2017-01-20 03:07 UTC by rainbowintheshell

2017-01-20 03:26 UTC, Jawshy requested changes
@rainbowintheshell, thanks for submitting a pull request. 

Does the site have any documentation about how it has implemented [two-factor authentication](https://github.com/jdavis/twofactorauth/blob/master/CONTRIBUTING.md#a-note-on-definitions)?

2017-01-20 03:28 UTC, rainbowintheshell commented
@Jawshy Hi there,

I searched, but I found none.

2017-01-20 03:42 UTC, Jawshy commented
Okay. Would you be able to screenshot the process for enabling 2FA and then attach the screenshots below? We can then use that as documentation.

2017-01-20 03:58 UTC, rainbowintheshell commented
## Enabling 2-FA in SatoshiTango

Log in, and then go to Settings > Security. Then, click 'Activate'

![](https://i.imgur.com/pIxUvWv.png)

Scan the QR Code with your mobile using Authy (or similar)

![](https://i.imgur.com/nCKvyWO.png)

Enter the code, confirm, and you're done!

2017-01-20 05:25 UTC, Jawshy commented
Thanks, @rainbowintheshell. Those screenshots show enabling software-based authentication. What is the process for enabling hardware-based authentication?

2017-01-20 16:24 UTC, rainbowintheshell commented
@Jawshy My mistake, It's just software-based authentication.

2017-01-21 05:00 UTC, Jawshy approved these changes
:ok_hand: :+1:

2017-01-21 05:14 UTC, jamcat22 requested changes

2017-01-21 05:14 UTC, jamcat22 commented on _data/cryptocurrencies.yml
> +      doc: https://github.com/2factorauth/twofactorauth/pull/2321#issuecomment-273971890
I'm hesitant to add this as the doc link, considering we have a [notes](https://twofactorauth.org/notes/) section on the website already for sites without pre-made docs. Should we make a new note for this site?

2017-01-21 16:08 UTC, rainbowintheshell commented on _data/cryptocurrencies.yml
> +      doc: https://github.com/2factorauth/twofactorauth/pull/2321#issuecomment-273971890
@jamcat22 I've seen sites with similar doc links, but it's up to you guys. But, creating a note will be more cleaner than this, for sure.

2017-01-24 15:46 UTC, jamcat22 commented on _data/cryptocurrencies.yml
> +      doc: https://github.com/2factorauth/twofactorauth/pull/2321#issuecomment-273971890
I'll go ahead and merge this now, and add the PR to our backlog. This way the site appears right away, and there is a doc listed for it, but we can easily return to add a page to the [notes](https://twofactorauth.org/notes/) section later. 😄

2017-01-24 15:46 UTC, jamcat22 approved these changes

2017-01-24 15:46 UTC, merged