Added AAI@EduHr
2factorauth/twofactorauth pull request #2324
Opened 2017-01-21 20:11 UTC by randomeuropean

Added AAI@EduHr (Authentication and Authorisation Infrastructure of science and higher education in Croatia)

2017-01-21 23:15 UTC, Jawshy submitted a review, later dismissed
[Travis CI job log](https://travis-ci.org/2factorauth/twofactorauth/jobs/194074361): 

```
1. img/education/aaieduhr.png is not 32x32 pixels.
2. img/education/aaieduhr.png should not be larger than 2500 bytes. It is currently 14796 bytes.
```

@randomeuropean, please correct the above errors. 

As `tfa` is set as `No` a `twitter`, `facebook`, and/or support `email_address` should also be added in this format: 

```ruby
      twitter: <AAI@EduHr twitter handle>
      facebook: <AAI@EduHr facebook page>
      email_address: <AAI@EduHr support email address>
```

2017-01-21 23:15 UTC, Jawshy commented on _data/education.yml
> +
Please remove the spaces on this line.

2017-01-24 15:43 UTC, Carlgo11 requested changes
Could use a language tag.
Please add `lang: hr` to the end of the submission.

2017-01-25 01:09 UTC, Carlgo11 approved these changes

2017-01-29 21:12 UTC, merged