Added Ello
2factorauth/twofactorauth pull request #2325
Opened 2017-01-21 20:13 UTC by randomeuropean

Added Ello.co website

2017-01-21 23:21 UTC, Jawshy requested changes
[Travis CI job log](https://travis-ci.org/2factorauth/twofactorauth/jobs/194074609): 

```
1. img/social/ello.png is not 32x32 pixels.
```

@randomeuropean, please reduce the size of the image to exactly 32 by 32 pixels.

2017-01-21 23:21 UTC, Jawshy commented on _data/social.yml
> +
Please remove the spaces on this line.

2017-01-21 23:51 UTC, Carlgo11 commented
Please add their email as well. `email_address: suggestions@ello.co`

2017-01-22 13:03 UTC, Jawshy approved these changes
Thanks, @randomeuropean.

2017-01-22 23:57 UTC, Carlgo11 approved these changes

2017-01-22 23:57 UTC, merged