Add Hostiso
2factorauth/twofactorauth pull request #2374
Opened 2017-02-15 08:27 UTC by trance-with-me

[Hostiso uses cPanel](https://hostiso.com/speed-security/) which [has TFA](https://documentation.cpanel.net/display/ALD/cPanel+Two-Factor+Authentication). However they're lacking their own documentation formally stating so.

2017-02-15 21:22 UTC, stephengroat requested changes

2017-02-15 21:22 UTC, stephengroat commented on _data/cloud.yml
> +      doc: https://hostiso.com/speed-security/
@trance-with-me since the `doc` link doesn't mention 2fa and isn't required, could you remove it?

2017-02-16 07:21 UTC, trance-with-me commented on _data/cloud.yml
> +      doc: https://hostiso.com/speed-security/
Sure

2017-02-16 07:43 UTC, stephengroat approved these changes

2017-02-16 07:44 UTC, stephengroat commented
@trance-with-me thanks for the PR!

2017-02-16 08:25 UTC, trance-with-me commented
No prob :+1:

2017-02-25 00:37 UTC, Carlgo11 commented
I'm a bit unsure if we should add it when it uses cPanel. Maybe that falls under the self-host category or third party login category?

@2factorauth/collaborators Any thoughts on this?

2017-02-25 06:39 UTC, jamcat22 commented
@Carlgo11 I think it falls under the same category which other sites like Bluehost, sites hosted with a 2FA WordPress plugin, and sites using WHM. I think it belongs in either the `Hosting/VPS` or `Cloud` categories because it provides shared hosting with 2FA (similar to DreamHost or Bluehost), rather than providing instructions for a host (running cPanel) to enable 2FA. cPanel doesn't have a single-sign-on version of their accounts, and each account on a hosting website is completely separate (again, much like it would be on WordPress or Drupal).

@trance-with-me, does 2FA also protect the [client area](https://my.hostiso.com/clientarea.php), or only the shared hosting cPanel?

2017-02-25 08:20 UTC, trance-with-me commented
@jamcat22 yeah 2FA (software token) protects the client area and a separate 2FA software token protects the shared hosting cPanel.

2017-02-26 04:41 UTC, Carlgo11 approved these changes
Guess it's good to go 👍

2017-02-26 14:51 UTC, jamcat22 requested changes
I think we should add an exception stating that 2FA for the client area and shared hosting panel are separate and each require setup. Maybe something like: `While both the main client area and the shared hosting panel support 2FA, each system is separate and requires its own setup.`

2017-03-03 15:32 UTC, jamcat22 approved these changes

2017-03-03 15:32 UTC, jamcat22 commented
Thanks @trance-with-me for the PR!

2017-03-03 15:32 UTC, merged