Add SignNow
2factorauth/twofactorauth pull request #2402
Opened 2017-02-26 16:18 UTC by Jawshy

Closes https://github.com/2factorauth/twofactorauth/issues/2394. 

#### Changes:
- Added: [SignNow](https://www.signnow.com/) under other. 
  - [Twitter handle](https://twitter.com/signnow). [Facebook page](https://www.facebook.com/signnow). I cannot access their Facebook page even when logged in.

2017-02-26 23:31 UTC, stephengroat approved these changes

2017-02-27 00:55 UTC, jamcat22 requested changes

2017-02-27 00:55 UTC, jamcat22 commented on _data/other.yml
> +      facebook: signnow
It looks like their Facebook page is actually `BarracudaSignNow`. Not sure why it isn't correctly linked on their site...

2017-02-27 02:53 UTC, Jawshy commented on _data/other.yml
> +      facebook: signnow
Thanks for finding that.

2017-02-27 22:11 UTC, jamcat22 commented on _data/other.yml
> +      facebook: signnow
No prob!

2017-02-27 22:11 UTC, jamcat22 approved these changes

2017-02-27 22:11 UTC, merged