Add Firstbank
2factorauth/twofactorauth pull request #2408
Opened 2017-02-27 04:28 UTC by schwartzadev

2017-02-27 05:02 UTC, Jawshy requested changes
Hi, @schwartzadev. Thanks for submitting a pull request. 

They list an email address on their [contact page](https://www.efirstbank.com/customer-service/contact-us.htm). Could you please add the following below line 311? 

```ruby
      email_address: banking@efirstbank.com
```

2017-02-27 05:02 UTC, Jawshy commented on _data/banking.yml
> +    - name: First Bank (Colorado)
Their website uses `FirstBank` without a space. Could you please amend your pull request to reflect that? Also, I am not sure if `(Colorado)` is necessary.

2017-02-27 06:42 UTC, schwartzadev commented on _data/banking.yml
> +    - name: First Bank (Colorado)
Sure thing

2017-02-27 06:46 UTC, schwartzadev commented
Done. I also cross checked the case of FirstBank and it appears to be camel case on their website as well.

2017-02-27 07:01 UTC, Carlgo11 commented
The logo is too big. Here's a compressed version:
![1stbank](https://cloud.githubusercontent.com/assets/3535780/23351696/ea797010-fcc2-11e6-867d-917a3b0489ce.png)

2017-02-27 07:02 UTC, Carlgo11 requested changes
The logo is too big. Here's a compressed version:
![1stbank](https://cloud.githubusercontent.com/assets/3535780/23351696/ea797010-fcc2-11e6-867d-917a3b0489ce.png)

2017-02-27 07:14 UTC, Jawshy approved these changes

2017-02-27 14:09 UTC, stephengroat requested changes

2017-02-27 14:09 UTC, stephengroat commented on _data/banking.yml
> +    - name: FirstBank (Colorado)
I really think that the `(Colorado)` needs to be removed. From their [about page](https://www.efirstbank.com/about-firstbank/about.htm),

> FirstBank now has over $17 billion in assets and over 120 locations in **Colorado, Arizona, and California**

2017-02-27 14:35 UTC, schwartzadev commented on _data/banking.yml
> +    - name: FirstBank (Colorado)
On the contrary, there are multiple other FirstBanks, including [this](https://www.firstbanks.com/), [this](https://www.firstbank.com/), [this](http://www.1firstbank.com/vi/en), and [this](https://www.firstbankofberne.com/) one. I can take care of that as well.

2017-02-27 14:48 UTC, stephengroat commented on _data/banking.yml
> +    - name: FirstBank (Colorado)
i think for how this site tends to be organized, those would be named `First Banks`, `First Bank & Trust Company`, `First Bank of Berne`, etc. those sites can be dealt with when submitted. thanks for the changes!

2017-02-27 14:48 UTC, stephengroat approved these changes

2017-02-27 16:14 UTC, schwartzadev commented on _data/banking.yml
> +    - name: FirstBank (Colorado)
Okay that sounds good, thanks

2017-02-28 06:52 UTC, schwartzadev commented
@Carlgo11 I think I resolved the logo issue in your request so this PR should be ready...

2017-03-01 03:35 UTC, schwartzadev commented
@Carlgo11 I think I did your changes--please approve them for the merge

2017-03-05 18:05 UTC, Carlgo11 approved these changes

2017-03-06 05:26 UTC, jamcat22 approved these changes

2017-03-06 05:27 UTC, merged

2017-03-06 05:27 UTC, jamcat22 commented
Thanks for the PR @schwartzadev! You can learn more about our merging process on our [wiki](https://github.com/2factorauth/twofactorauth/wiki/FAQ_Merge) page.