Cdnjs
2factorauth/twofactorauth pull request #2427
Opened 2017-03-06 05:09 UTC by stephengroat

Include semantic ui from cdn.

still need a tiny bit of help, my font-size override trick works for everything except the `icon` in the `header`

2017-03-06 05:27 UTC, mxxcon commented
Let's implement SRI tags. You can use https://www.srihash.org/ to speed things up.

2017-03-06 05:37 UTC, stephengroat commented
OK. Let's get the sizing down first

On Sun, Mar 5, 2017, 21:27 mxxcon <notifications@github.com> wrote:

> Let's implement SRI tags. You can use https://www.srihash.org/ to speed
> things up.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/2factorauth/twofactorauth/pull/2427#issuecomment-284306245>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABGv4hhdY2HngB-g9t7ldSa8ZJaDMCklks5ri5lIgaJpZM4MTuwG>
> .
>

2017-03-06 13:29 UTC, psgs commented
Awesome stuff @stephengroat! 👍 

At the moment, the Semantic-UI library sets the icon font-size to `2em` through the following classes: 
```.ui.icon.header .circular.icon, .ui.icon.header .square.icon {```
It's quite likely that somewhere, either in our own CSS or in Semantic-UI's CSS, there is a line of code that sets a base font-size lower than 18px specifically for a class which affects the logo icon. I'll have a dig around over the next day or two and see what I can find.
You can also see exactly which classes have what effects on particular elements by right-clicking on an element and selecting "Inspect". From there, specific classes provided for by the CSS appear in the Styles tab. The "Computed" tab is also really useful, as it shows the whole collection of styles applied to that specific element, regardless of how they were applied.

Would you be able to re-factor the `style="font-size:18px"` snippet into the `css/base.scss` file by any chance? This helps keep all the CSS in one place.

Thanks,
psgs 🌴

2017-03-06 13:29 UTC, fpigerre requested changes
* Refactor style tag into `base.scss`
* Fix logo icon sizing
* Implement SRI hashes

2017-03-06 15:01 UTC, stephengroat commented
@psgs thanks for the help, i don't really know what i'm doing with css (learning curve is steep).

i moved the `font-size` to the css and it seems to fix the `icon` issue, could you look the size over and see if you can tell any major differences? i tried it on chrome and firefox and it looks the same (to me)

2017-03-07 13:15 UTC, psgs commented
Awesome work @stephengroat! 👍 

The only difference with the sizing of elements that I can see is a slight difference in the width of table columns. It's probably caused by several elements gradually inheriting a larger font size. Visually, the difference is negligible, however, so I think we can go ahead and merge the pull request.

@Carlgo11, @mxxcon: Should we specify one particular type of hash to use for SRI hashes (eg. `sha-256`), or allow different hash types to be used for each resource?

2017-03-07 13:16 UTC, fpigerre approved these changes

2017-03-07 13:57 UTC, mxxcon commented
>Should we specify one particular type of hash to use for SRI hashes (eg. sha-256), or allow different hash types to be used for each resource?

I think it doesn't really matter as long as they are secure hashes(not sha1). We could stick to one type just for consistency sake.

2017-03-07 14:07 UTC, jamcat22 commented
I think if we decide to stick to one type, we should use sha-384, since that's what https://www.srihash.org uses when generating hashes.

2017-03-07 14:32 UTC, stephengroat commented
The srihash.org generated hashes weren't withing for the Google fonts, so I
switched to 256

On Tue, Mar 7, 2017, 06:07 Jacob <notifications@github.com> wrote:

> I think if we decide to stick to one type, we should use sha-384, since
> that's what https://www.srihash.org uses when generating hashes.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/2factorauth/twofactorauth/pull/2427#issuecomment-284730517>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABGv4oJLDAXRnJ83Zk3UYEVCZ_cyz4_4ks5rjWSmgaJpZM4MTuwG>
> .
>

2017-03-07 16:32 UTC, stephengroat commented
@psgs i'm still seeing a problem for the `backup` entry `pogoplug`

do you see anything?

2017-03-08 12:18 UTC, psgs commented
@stephengroat, I can't seem to see any problems with Pogoplug.

![screen shot 2017-03-08 at 22 17 27](https://cloud.githubusercontent.com/assets/3946887/23703724/1f471c7a-044d-11e7-85ef-fa4be2e2ac89.png)


![screen shot 2017-03-08 at 22 17 09](https://cloud.githubusercontent.com/assets/3946887/23703733/237d5232-044d-11e7-8003-68bc3c8d30a7.png)

2017-03-08 16:23 UTC, stephengroat commented
@psgs you're 100% right. i was comparing against an unmerged changed that still had the `in progress` badge on it and was getting VERY confused!

2017-03-09 22:59 UTC, stephengroat commented
@2factorauth/collaborators can some more people look this over? i think this one needs more than 2 reviews

2017-03-10 06:52 UTC, mxxcon commented on _layouts/default.html
> +  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,700"
I think we should NOT use SRI for Google Fonts. Apparently CSS they serve is intentionally unversioned and it changes depending on which browser requests it.
See https://github.com/google/fonts/issues/473

2017-03-10 19:39 UTC, mxxcon approved these changes

2017-03-13 10:17 UTC, jamcat22 requested changes
Is it possible to change the hashes of our jquery source to be sha384?

2017-03-13 15:46 UTC, jamcat22 approved these changes

2017-03-13 15:46 UTC, merged

2017-03-14 02:24 UTC, psgs commented
👍