Updated the URL for Okta
2factorauth/twofactorauth pull request #2437
Opened 2017-03-09 15:56 UTC by mmahadevan-okta

2017-03-09 16:14 UTC, mxxcon requested changes

2017-03-09 16:14 UTC, mxxcon commented on _data/identity.yml
> +      doc: https://www.okta.com/products/adaptive-multi-factor-authentication/
`doc:` url should be not a marketing product page with what okta is selling, but a link to a documentation how a user can enable 2fa for their okta account.

2017-03-09 19:42 UTC, mmahadevan-okta reviewed
Updated the URL to the support page.

2017-03-09 19:42 UTC, mmahadevan-okta commented
Changed URL to https://help.okta.com/en/prod/Content/Topics/Security/MFA.htm

2017-03-09 19:48 UTC, stephengroat approved these changes

2017-03-09 20:41 UTC, jamcat22 approved these changes
:+1:

2017-03-10 07:02 UTC, mxxcon reviewed
If the current URL is as good as it gets 👍, otherwise a link to the actual _instructions_ would be nice.

2017-03-10 07:02 UTC, mxxcon approved these changes

2017-03-10 14:09 UTC, merged