Update fidelity with real doc
2factorauth/twofactorauth pull request #2450
Opened 2017-03-15 23:05 UTC by stephengroat

2017-03-16 01:35 UTC, fpigerre approved these changes

2017-03-16 23:56 UTC, jamcat22 requested changes
Fidelity's doc does not mention the fact that they support hardware-based 2FA. I'm worried that by linking to their doc, we may confuse users who do not understand that hardware tokens are supported. See #1519.

2017-03-17 00:06 UTC, stephengroat commented
since fidelity no longer recognizes on their website, i've removed it

2017-03-17 00:10 UTC, jamcat22 commented
Technically speaking though, they do support it. Much like how PayPal does not document support for software 2FA anymore, but they do still support it in their account settings.

2017-06-22 18:09 UTC, closed without merging