Add Georgia Institute of Technology
2factorauth/twofactorauth pull request #2472
Opened 2017-03-27 13:07 UTC by kylekoza

2017-03-27 13:47 UTC, mxxcon approved these changes

2017-03-27 16:43 UTC, stephengroat requested changes
thanks for the pr @kylekoza! if you could address the one issue, that'd be great!

2017-03-27 16:43 UTC, stephengroat commented on _data/education.yml
> +      sms: No
if `sms` is not enabled, then please remove the tag

2017-03-27 18:20 UTC, Carlgo11 requested changes
Please use this image instead.
![gatech](https://cloud.githubusercontent.com/assets/3535780/24371332/c2c48cc0-132a-11e7-826a-db16504bd77f.png)

2017-03-27 19:56 UTC, kylekoza commented on _data/education.yml
> +      sms: No
@stephengroat: I have removed the sms tag

2017-03-27 19:56 UTC, kylekoza commented
@Carlgo11: I have changed out the image as suggested

2017-03-27 19:59 UTC, stephengroat approved these changes

2017-03-29 13:42 UTC, Carlgo11 approved these changes

2017-03-29 13:44 UTC, merged