html proofer + fixes
2factorauth/twofactorauth pull request #2478
Opened 2017-03-29 02:15 UTC by stephengroat

fixes bugs in fidelity notes and updates sites (identified using html-proofer)

html proofer now has a cache (it can cache websites that it searches). i'm working on getting that working 100%, but it's not there yet

2017-03-29 05:16 UTC, jamcat22 requested changes

2017-03-29 05:16 UTC, jamcat22 commented on _data/hosting.yml
>        twitter: missgroupcom
This should be changed to `misshostingcom`

2017-03-29 05:16 UTC, jamcat22 commented on _data/payments.yml
> +      doc: https://www.neteller.com/en/support#/path/ACCOUNT/Two-Factor-Authentication/85238429/What-is-two-step-authentication.htm
This link should be changed to `https://support.neteller.com/ACCOUNT/Two-Factor-Authentication/85238429/What-is-two-step-authentication.htm`

2017-03-29 06:05 UTC, stephengroat commented on _data/payments.yml
> +      doc: https://www.neteller.com/en/support#/path/ACCOUNT/Two-Factor-Authentication/85238429/What-is-two-step-authentication.htm
good catch. could you fix it?

2017-03-29 15:52 UTC, jamcat22 submitted a review, later dismissed

2017-03-29 15:52 UTC, jamcat22 commented on _data/security.yml
> -      doc: https://docs.incapsula.com/Content/Management%20Console%20and%20Settings/accountsettings.htm
Why was Incapsula removed? They seem to still provide service, and they have a doc page here: `https://docs.incapsula.com/Content/management-console-and-settings/account-settings.htm`

2017-03-29 15:53 UTC, stephengroat commented on _data/security.yml
> -      doc: https://docs.incapsula.com/Content/Management%20Console%20and%20Settings/accountsettings.htm
double listed

2017-03-29 16:32 UTC, jamcat22 commented on _data/security.yml
> -      doc: https://docs.incapsula.com/Content/Management%20Console%20and%20Settings/accountsettings.htm
Ah I see. I'll push the change to the doc link.

2017-03-29 16:58 UTC, stephengroat commented
anyone know how to fix the extra `div` tag that we have? i'm looking into it, but haven't had any luck

2017-03-29 17:53 UTC, mxxcon commented on _data/remote.yml
> +    - name: O&amp;O Syspectr
I think you forgot to delete the `&` symbol?

2017-03-29 17:55 UTC, stephengroat commented on _data/remote.yml
> +    - name: O&amp;O Syspectr
nope, that's the html for ampersand

2017-03-29 17:56 UTC, mxxcon commented on _data/remote.yml
> +    - name: O&amp;O Syspectr
ah yes, it's `&amp;`
The way diff showed it confused me. 😅

2017-04-04 06:52 UTC, fpigerre approved these changes

2017-04-04 06:53 UTC, psgs commented
This pull request affects issue #1265.

2017-04-04 19:52 UTC, stephengroat commented
in reference to #1265, `html-proofer` now has a cache for it's link checker result, so that it can cache the link check results for a specified time. if you remove the `disable_external: true, \` line or set it to `false`, it will check the external links and cache the result. i currently set the cache to 1 day, but that is modifiable. 

currently, not all links work, so i'm going through them manually to check the results. i might try to enable this eventually on travis cron jobs, but not for specific PRs

2017-04-09 16:20 UTC, Carlgo11 commented
Could you do a rebase?

2017-04-10 15:03 UTC, stephengroat commented
will do

On Sun, Apr 9, 2017 at 9:20 AM Carlgo11 <notifications@github.com> wrote:

> Could you do a rebase?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/2factorauth/twofactorauth/pull/2478#issuecomment-292795712>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABGv4kddZDgt2ywpX43nYtgJi-B_0rs_ks5ruQU3gaJpZM4Msati>
> .
>

2017-04-25 17:47 UTC, stephengroat commented
ready to go. i removed the `verify.rb` changes, just don't have time right now. but these changes are needed and good

2017-04-25 20:53 UTC, stephengroat commented
@2factorauth/collaborators does anyone understand why the `html-proofer` is failing to load in the second build env on the latest builds? I was trying to do 2 things:
1. test using `trusty` (build infra is moving eventually)
2. trying to create a separate build that runs the external link checks. those external link checks are extremely helpful, but random failures will happen. a good place to monitor them (if possible)

2017-04-25 21:05 UTC, stephengroat commented
sorry about that, think i figured it out. was missing `bundler` cmd. take a look at the build under "Allow failures", see if you like the output. It's not 100%, but it's pretty good

2017-04-29 02:12 UTC, psgs commented on _config.yml
> +    - vendor
It looks like this could be a remnant of a very old version of twofactorauth.org, from back when we used the `vendor` directory. Is this intentional?

2017-04-29 02:35 UTC, stephengroat commented
yup, need it for the `html-proofer`

On Fri, Apr 28, 2017 at 7:12 PM Francois <notifications@github.com> wrote:

> *@psgs* commented on this pull request.
> ------------------------------
>
> In _config.yml
> <https://github.com/2factorauth/twofactorauth/pull/2478#discussion_r114043733>
> :
>
> > @@ -19,3 +19,4 @@ exclude:
>      - README.md
>      - Rakefile
>      - verify.rb
> +    - vendor
>
> It looks like this could be a remnant of a very old version of
> twofactorauth.org, from back when we used the vendor directory. Is this
> intentional?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/2factorauth/twofactorauth/pull/2478#pullrequestreview-35487009>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABGv4sB3wNvsJUPg5QXDj6WrOCpsfuCLks5r0pyagaJpZM4Msati>
> .
>
-- 

Stephen Groat
stephen@egroat.com
+1 (703) 798-4551
Sent from mobile

2017-04-29 02:45 UTC, fpigerre approved these changes

2017-04-29 02:46 UTC, psgs commented
It looks like this pull request is ready to merge then 👍 .  @jamcat22 @mxxcon, would you agree?

2017-05-10 04:36 UTC, jamcat22 commented
@stephengroat, is this ready to merge or still a WIP?

2017-05-10 15:50 UTC, stephengroat commented
moved the `proof_external` task to `osx` (doesn't seem to work on `linux`, filed a bug with `html-proofer. seems to be a memory leak`)

ready

2017-05-27 22:02 UTC, Carlgo11 commented on _config.yml
> +    - vendor
ping @stephengroat ^

2017-05-27 22:07 UTC, Carlgo11 commented on _data/remote.yml
> +
Why is this added in the PR?

2017-05-27 22:27 UTC, stephengroat commented on _data/remote.yml
> +
needed from `html-proofer` https://github.com/2factorauth/twofactorauth/pull/2478#issuecomment-298141955

2017-05-27 22:27 UTC, stephengroat commented on _config.yml
> +    - vendor
needed from `html-proofer` https://github.com/2factorauth/twofactorauth/pull/2478#issuecomment-298141955

2017-05-27 22:28 UTC, stephengroat commented on _data/remote.yml
> +
it's the rebrand of screenconnect, which was deleted in this pr

2017-05-27 23:35 UTC, Carlgo11 requested changes

2017-05-27 23:35 UTC, Carlgo11 commented on _data/hosting.yml
> +      facebook: misshostingcom
Looks like they're a Swedish company writing in Swedish. Maybe a sv lang tag would be good?

2017-05-27 23:35 UTC, Carlgo11 commented on _data/domains.yml
>        sms: Yes
They also support email 2FA.

2017-05-27 23:35 UTC, Carlgo11 commented on _data/domains.yml
> +      url: http://dyn.com/
`http://dyn.com/` redirects to `https://dyn.com/` for me.

2017-05-27 23:35 UTC, Carlgo11 commented on _data/developer.yml
> -    - name: Jidoteki
Why was this removed? The site is still works for me.

2017-05-27 23:35 UTC, Carlgo11 commented on _data/cloud.yml
> +      doc: https://help.packet.net/faq/the-portal
According to the doc link they use software 2FA "Google Authenticator" and not SMS.

2017-05-27 23:54 UTC, stephengroat commented on _data/developer.yml
> -    - name: Jidoteki
Jidoteki changed their project, not longer has a login/need for 2fa

2017-05-28 00:02 UTC, stephengroat commented on _data/domains.yml
>        sms: Yes
done

2017-05-28 00:03 UTC, Carlgo11 commented on .travis.yml
> +    - script: bundle exec rake proof_external
Doesn't this mean all the entire bundle exec rake command will is ignored when checking for errors?

2017-05-28 00:03 UTC, Carlgo11 commented on .travis.yml
> +dist: trusty
Do we **need** to specify a distribution?

2017-05-28 00:05 UTC, stephengroat commented on _data/hosting.yml
> +      facebook: misshostingcom
done

2017-05-28 00:09 UTC, stephengroat commented on .travis.yml
> +    - script: bundle exec rake proof_external
it means that only the separate build using the script `rake proof_external` is allowed to fail

2017-05-28 00:09 UTC, stephengroat commented on .travis.yml
> +dist: trusty
`html-proofer` has performance advantages on `trusty`

2017-05-28 00:10 UTC, Carlgo11 approved these changes

2017-05-28 00:10 UTC, merged