Updated SEB with soft token (Mobilt BankID)
2factorauth/twofactorauth pull request #2483
Opened 2017-03-30 09:43 UTC by westlund

Two factor authentication available through hardware token supplied by SEB or by BankID which can reside on a smart card, or a soft cert in your computer os smartphone.

2017-03-30 11:25 UTC, Carlgo11 approved these changes

2017-03-30 11:26 UTC, Carlgo11 requested changes

2017-03-30 11:26 UTC, Carlgo11 commented on _data/banking.yml
> +      software: Yes
Looks like the only software 2FA option is BankID which requires SE citizenship.

2017-03-30 12:03 UTC, westlund commented on _data/banking.yml
> +      software: Yes
SEB have a Digipass option for 2FA. It's a Vasco hardware token that do not require Swedish citizenship or residency.

2017-03-30 12:04 UTC, westlund commented on _data/banking.yml
> +      software: Yes
And to be precise, BankID does not require Swedish citizenship. It requires Swedish permanent resicendy, ie you need to be assigned a personal number by the Swedish tax authority.

2017-04-07 11:56 UTC, Carlgo11 approved these changes

2017-04-19 13:57 UTC, stephengroat approved these changes

2017-04-19 13:58 UTC, merged