Add Private Internet Access
2factorauth/twofactorauth pull request #2493
Opened 2017-04-07 19:41 UTC by leetruitt

2017-04-07 19:45 UTC, stephengroat approved these changes
thanks for the pr @leetruitt!

2017-04-07 20:21 UTC, Carlgo11 requested changes

2017-04-07 20:21 UTC, Carlgo11 commented on _data/security.yml
> +      twitter: buyvpnservice
Please change their twitter handle to `piacsm`

2017-04-07 20:38 UTC, disforw commented on _data/security.yml
> +      twitter: buyvpnservice
The doc is wrong ??

2017-04-07 20:51 UTC, Carlgo11 commented on _data/security.yml
> +      twitter: buyvpnservice
No but the twitter handle is wrong

2017-04-08 00:48 UTC, leetruitt commented on _data/security.yml
> +      twitter: buyvpnservice
Sorry about that. The twitter handle should be correct now.

2017-04-08 00:49 UTC, Carlgo11 approved these changes

2017-04-08 00:50 UTC, merged