Add Ulule
2factorauth/twofactorauth pull request #2496
Opened 2017-04-12 20:09 UTC by TJ619

The EU crowdfunding website (like Kickstarter for US)

2017-04-12 20:21 UTC, stephengroat approved these changes
thanks for the pr @TJ619

2017-04-13 15:48 UTC, Carlgo11 submitted a review, later dismissed

2017-04-13 15:48 UTC, Carlgo11 commented on _data/other.yml
> +      url: https://ulule.com/
Please change the URL to `https://www.ulule.com/`

2017-04-13 19:14 UTC, jamcat22 requested changes

2017-04-13 19:14 UTC, jamcat22 commented on _data/other.yml
> +      facebook: ulule
Their Facebook page redirects to `ululeEN` for me. Does anyone else get a different result after going to [facebook.com/ulule](https://www.facebook.com/ulule)?

2017-04-13 19:58 UTC, stephengroat commented on _data/other.yml
> +      facebook: ulule
it's doing that based on globalization techniques available for facebook pages. it's the best option to link against

2017-04-14 02:16 UTC, Carlgo11 commented on _data/other.yml
> +      facebook: ulule
Well `ulule` seems to be in French so why not use `ululeEn`? Also, it doesn't redirect for me.

2017-04-14 08:21 UTC, TJ619 commented on _data/other.yml
> +      facebook: ulule
For me (in FR) the ulule facebook didn't redirect me to the FR one, seem to be better for all.

2017-04-14 16:14 UTC, stephengroat commented on _data/other.yml
> +      facebook: ulule
i believe that `ulule` is the company's [Facebook root or default page](https://www.facebook.com/business/help/331800410323820)

2017-04-14 17:12 UTC, Carlgo11 commented on _data/other.yml
> +      facebook: ulule
I'm not saying it redirects to another facebook page. Just that `ulule` seems to be a French version.

ulule:
![ulule-screenshot](https://cloud.githubusercontent.com/assets/3535780/25050147/149393ba-2146-11e7-83f8-1a618cf14c6f.png)
ululeEn:
![ululeEn-screenshot](https://cloud.githubusercontent.com/assets/3535780/25050157/21da4ae6-2146-11e7-88ad-1c961d1ba80f.png)

2017-04-14 17:14 UTC, stephengroat commented on _data/other.yml
> +      facebook: ulule
for me, `ulule` redirects to `ulueEn`

2017-04-14 17:15 UTC, Carlgo11 commented on _data/other.yml
> +      facebook: ulule
@stephengroat are you signed in to Facebook?

2017-04-14 17:25 UTC, stephengroat commented
i get redirects when signed in and when not

On Fri, Apr 14, 2017 at 10:16 AM Carlgo11 <notifications@github.com> wrote:

> *@Carlgo11* commented on this pull request.
> ------------------------------
>
> In _data/other.yml
> <https://github.com/2factorauth/twofactorauth/pull/2496#discussion_r111604032>
> :
>
> > @@ -343,6 +343,13 @@ websites:
>        tfa: Yes
>        software: Yes
>
> +    - name: Ulule
> +      url: https://www.ulule.com/
> +      twitter: ulule
> +      facebook: ulule
>
> @stephengroat <https://github.com/stephengroat> are you signed in to
> Facebook?
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/2factorauth/twofactorauth/pull/2496#discussion_r111604032>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABGv4sT8qvOld8wAwEiImRaICQlzTmmZks5rv6mrgaJpZM4M76Mo>
> .
>
-- 

Stephen Groat
stephen@egroat.com
+1 (703) 798-4551
Sent from mobile

2017-04-20 13:01 UTC, TJ619 commented on _data/other.yml
> +      facebook: ulule
Oh yes i just see.
Yes the **ulule** page is the French Page (cause created in France before expand for EU)
So yes, better for here to put **ululeEn** page

2017-04-21 13:46 UTC, TJ619 commented
Yes the ulule page is the French Page (cause created in France before expand for EU)
So yes, better for here to put ululeEn page for all.

2017-04-24 16:51 UTC, jamcat22 commented
I think in the context of how we currently handle things (forcing English websites unless they're a regional service such as a bank) we should probably force their English Facebook page as well. If we later implement options for other languages then we can figure something out.

Cross ref #2510.

2017-05-14 00:23 UTC, jamcat22 approved these changes

2017-05-14 00:23 UTC, merged