Update domains.yml
2factorauth/twofactorauth pull request #2498
Opened 2017-04-13 15:57 UTC by LeeMcCartney

2nd attempt. Hopefully I've got it right this time!

2017-04-13 15:58 UTC, Carlgo11 commented
Looks better but you forgot the spacing. Make sure your addition is aligned with other things.

2017-04-13 17:14 UTC, stephengroat commented
@LeeMcCartney, do you have an `img` to add to the `img/domains` folder? it has to be a `png` with the size `32x32 px`

2017-04-13 19:23 UTC, LeeMcCartney commented
I've uploaded the image to the directory but i'm not sure how to link it to my edit.

2017-04-13 19:57 UTC, stephengroat requested changes

2017-04-13 19:57 UTC, stephengroat commented on _data/domains.yml
> +      img:
could you add the filename `uk2.png` for the `img` tag?

also, rename the img to `uk2.png`? we try to only have the entry `name` in the `img` filename

it should look like this: `img: uk2.png`

2017-04-19 16:44 UTC, stephengroat commented on _data/domains.yml
> +      img:
bump for @LeeMcCartney

2017-04-19 18:25 UTC, LeeMcCartney commented
My head hurts!

I can't work out how to rename the img file and I'm not sure what file i'm editing anymore.

2017-04-20 06:11 UTC, Carlgo11 commented
I'll do it in a couple of hours.

2017-04-20 15:52 UTC, stephengroat approved these changes

2017-04-20 15:53 UTC, stephengroat commented
thanks for all of the work @LeeMcCartney! got the image renamed, corrected, etc.

2017-04-20 22:07 UTC, Carlgo11 requested changes

2017-04-20 22:07 UTC, Carlgo11 commented on _data/domains.yml
> +      facebook: uk2.net
Please rename to `UK2.net`

2017-04-21 18:31 UTC, Carlgo11 approved these changes

2017-04-27 22:15 UTC, merged