Added www.awardwallet.com
2factorauth/twofactorauth pull request #2499
Opened 2017-04-13 20:59 UTC by rj175

Awardwallet allows users to store and track loyalty schemes in one place. Mostly used for air miles but can also deal with store loyalty schemes and hotels. I've included a image and documentation from their FAQ regarding 2FA. Let me know if I have done anything wrong as this is my first time contributing :)

2017-04-13 21:09 UTC, rj175 commented
One more thing...
Last time I did a PR I was asked if it fitted the site criteria. I would say it does for the following reasons:

- **Personal Info**: This site allows users to store their account numbers and passwords so that the information can pulled into one place. If this information was accessed it would be possible for someone to either spend air miles/hotel points or in the case of hotel reservations (which AwardWallet also pulls in) cancel or amend bookings.
- **Money**: You can also add in credit card point schemes e.g. American Express Rewards. This information could be used to access a persons account.

2017-04-13 21:53 UTC, stephengroat commented
previously looked at in #1956

2017-04-15 02:13 UTC, jamcat22 requested changes

2017-04-15 02:13 UTC, jamcat22 commented on _data/other.yml
> +      url: https://www.awardwallet.com
This URL redirects to one without a preceding `www`. Please update the url to `https://awardwallet.com`

2017-04-15 19:06 UTC, rj175 commented
Hello, I've now made the requested changes.

2017-04-16 04:40 UTC, jamcat22 approved these changes

2017-04-16 12:26 UTC, Carlgo11 approved these changes

2017-04-16 12:26 UTC, merged