Added www.scotrail.co.uk
2factorauth/twofactorauth pull request #2502
Opened 2017-04-14 23:06 UTC by rj175

Scotrail is the main rail operator in Scotland, UK. Their site allows you to book tickets for trains within Scotland for pickup at stations or to be loaded onto a smartcard. Their site does not support 2FA.

2017-04-15 02:18 UTC, jamcat22 requested changes

2017-04-15 02:18 UTC, jamcat22 commented on _data/transport.yml
> +    - name: Scotrail
Their name appears to be stylized as "ScotRail" according to their website and social media profiles.
Please update their name to be `ScotRail`.

2017-04-15 02:18 UTC, jamcat22 commented on _data/transport.yml
> +      twitter: Scotrail
Their Twitter username is stylized as `ScotRail`.
Please update this line to reflect that.

2017-04-15 02:18 UTC, jamcat22 commented on _data/transport.yml
> +      facebook: Scotrail
Their Facebook username is stylized as `ScotRail`.
Please update this line to reflect that.

2017-04-15 19:10 UTC, rj175 commented
Hello, I have made the above branding changes as requested.

2017-04-15 19:58 UTC, Carlgo11 commented
So uhm, what's the worst thing that could happen if someone got hold of a ScotRail account? Could they make purchases from that account?

2017-04-15 20:11 UTC, rj175 commented
Yes they could. You can also purchase season tickets and additional smartcards to hold etickets.

2017-04-16 04:39 UTC, jamcat22 approved these changes

2017-04-16 15:44 UTC, stephengroat approved these changes

2017-04-16 15:44 UTC, merged