Add ImmobilienScout24 as a service
2factorauth/twofactorauth pull request #2535
Opened 2017-05-11 13:39 UTC by ruempel

ImmobilienScout24 supports 2FA via authenticator app, but does not provide a public documentation.

2017-05-11 13:45 UTC, stephengroat requested changes
also, do you have any links to documentation that we could add to the `doc` tag?

2017-05-11 13:45 UTC, stephengroat commented on _data/other.yml
> +      lang: de
could you remove the `lang` tag? we don't use it when `tfa: true`

2017-05-11 13:57 UTC, ruempel commented
There is not publicly available documentation on 2FA. However, there are hints available at https://sso.immobilienscout24.de/account/verwaltung when logged in, but this link is useless for public audience.

2017-05-11 14:25 UTC, stephengroat approved these changes

2017-05-11 14:25 UTC, stephengroat commented
@ruempel no problem. thanks for the addition and quick fixes!

2017-05-12 03:35 UTC, fpigerre approved these changes

2017-05-12 03:35 UTC, merged