Fix Dominion Energy
2factorauth/twofactorauth pull request #2540
Opened 2017-05-16 16:07 UTC by stephengroat

2017-05-17 04:57 UTC, jamcat22 requested changes

2017-05-17 04:57 UTC, jamcat22 commented on _data/utilities.yml
>      - name: Dominion
It appears they've [rebranded](https://www.dominionenergy.com/NewBrand) as "Dominion Energy", so I think we should update their name to match that.

2017-05-17 04:57 UTC, jamcat22 commented on _data/utilities.yml
> +      twitter: dominionenergy
It appears that this account is solely used as a corporate news Twitter, and it doesn't look like they reply to tweets. Should we use a different account?

2017-05-17 17:04 UTC, stephengroat commented on _data/utilities.yml
> +      twitter: dominionenergy
there isn't any other official account linked on their website

2017-06-22 18:29 UTC, Carlgo11 approved these changes

2017-06-22 18:30 UTC, Carlgo11 commented on _data/utilities.yml
> +      twitter: dominionenergy
![chrome_2017-06-22_20-30-11](https://user-images.githubusercontent.com/3535780/27449722-a4c1c6f4-5789-11e7-9d35-2c985e177080.png)
There are actually a few replies from the account.

2017-07-07 01:33 UTC, jamcat22 approved these changes

2017-07-07 01:33 UTC, merged