Add Poloniex
2factorauth/twofactorauth pull request #2564
Opened 2017-06-11 00:00 UTC by rajivshah3

2017-06-11 00:30 UTC, mxxcon requested changes

2017-06-11 00:30 UTC, mxxcon commented on _data/cryptocurrencies.yml
> +
Please correct indentations here. In YAML format spacing matters.

2017-06-11 00:34 UTC, rajivshah3 commented on _data/cryptocurrencies.yml
> +
Done

2017-06-11 00:48 UTC, mxxcon commented on _data/cryptocurrencies.yml
> +
I noticed that their docs page states that they also support SMS? If that's the case, perhaps add it.

2017-06-11 00:52 UTC, rajivshah3 commented on _data/cryptocurrencies.yml
> +
My bad, fixed that

2017-06-11 00:54 UTC, mxxcon approved these changes

2017-06-11 00:54 UTC, mxxcon commented
In the future please submit one site per pull request so that they can be reviewed independently of each other.

2017-06-11 00:55 UTC, rajivshah3 commented
I originally intended to, but when I submitted the commit for bitfinex it added on to the existing one for Poloniex

2017-06-11 01:07 UTC, mxxcon commented
To get around such situations, before you make your additions, in your own repo create separate branches for each site and make changes there. Then you can create pull requests from those separate branches.

2017-06-11 10:41 UTC, fpigerre approved these changes

2017-06-11 10:41 UTC, psgs commented
Thanks for the pull request @rajivshah3! 👍

2017-06-11 10:42 UTC, merged

2017-06-13 03:34 UTC, Carlgo11 commented
How did not travis fail here?
Got any ideas @stephengroat?

2017-06-13 03:50 UTC, stephengroat commented
travis implemented a change that silently broke system using implicit matrix expansion https://github.com/travis-ci/travis-ci/issues/4681