Add Readthedocs
2factorauth/twofactorauth pull request #2573
Opened 2017-06-16 17:21 UTC by stephengroat

I understand that the `twitter` is not a support channel, but it does provide public shame

2017-06-17 03:28 UTC, psgs commented
Hi @stephengroat 😄 

How would this site fit into the current [website criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#site-criteria)?

2017-06-17 17:31 UTC, stephengroat commented
I think it has to deal with Data (2) and Control (4). Sites like to auto-push docs to readthedocs.io, don't want those changing, providing mis-information, etc.

2017-06-18 01:58 UTC, Carlgo11 requested changes

2017-06-18 01:58 UTC, Carlgo11 commented on _data/developer.yml
> +      twitter: readthedocs
Doesn't seem like they're monitoring their twitter account. I suggest we only use the email address.

2017-06-18 01:59 UTC, Carlgo11 commented
I think it can pass. Looks like a pretty big service and it shouldn't be very difficult for them to add 2FA.

2017-06-18 02:04 UTC, Carlgo11 commented
@ericholscher and/or @agjohnson would any of you like to comment?

2017-06-18 02:38 UTC, agjohnson commented
2fa is on our list, and something we'd certainly take contributions on. Currently it isn't implemented however, and isn't on our roadmap just yet.

I'm not familiar with the purpose of the above changes, but as to the question around twitter or email: we don't consider either as support channels for our community platform, so both are highly likely to be ignored.

If the point is to encourage us to implement 2fa, we'd just tell anyone looking for this feature that patches are encouraged. Perhaps you need a "contribute a patch" call to action on the site? 🙂

2017-06-18 03:10 UTC, mxxcon commented
Perhaps `exceptions:` is in order then indicating that 2fa is not planned but could be contributed?

2017-06-18 19:34 UTC, ericholscher commented
Opening a ticket on https://github.com/rtfd/readthedocs.org is probably the best course of action. Definitely would love to have 2fa, but needs to not be a large operational overhead. We're Django, with django-allauth as our auth mechanism. I wouldn't be surprised if there are plugins for this.

2018-02-13 19:43 UTC, jamcat22 commented
Referencing rtfd/readthedocs.org#3523 in case we decide to link to it.

2019-01-29 17:27 UTC, Carlgo11 approved these changes

2019-02-04 15:32 UTC, mxxcon approved these changes

2019-02-04 15:34 UTC, merged