Add Vodafone Ireland.
2factorauth/twofactorauth pull request #2593
Opened 2017-06-24 21:05 UTC by Flameeyes

Same logo as Vodafone UK, no 2FA option.

2017-06-28 21:33 UTC, stephengroat approved these changes

2017-07-07 23:11 UTC, Carlgo11 requested changes
Same thing here. Make the twitter capitalized. `VodafoneIreland`

2017-07-08 16:52 UTC, Flameeyes commented
Done.

2017-07-08 20:30 UTC, Carlgo11 approved these changes

2017-07-08 20:36 UTC, merged