Update Pinterest.
2factorauth/twofactorauth pull request #2595
Opened 2017-06-27 16:34 UTC by timonus

Pinterest now supports two factor auth, this PR updates the entry for it.

2017-06-27 16:39 UTC, mxxcon commented on _data/social.yml
> +          text: "Software tokens can only be provided through Authy at this time."
It doesn't sound like they are planning to support other totp clients. it seems like both sms and tokens are generated completely within twillo. Unless i'm misreading their announcement?

2017-06-27 16:41 UTC, 0x0ece commented
@mxxcon correct, we use Authy for everything. Eng blog post here:
https://medium.com/@Pinterest_Engineering/two-factor-authentication-on-pinterest-238aa3dc92d1

2017-06-27 16:47 UTC, 0x0ece commented
Also, the help page: https://help.pinterest.com/en/articles/two-factor-authentication

2017-06-27 16:51 UTC, mxxcon commented
@timonus Please update your `doc` link with the one @0x0ece posted. That one is more useful for people to figure out how to turn on 2fa.
And I'm thinking that perhaps `exception` text is unnecessary since it doesn't seem like you are planning to support other totp clients?

2017-06-27 16:53 UTC, mxxcon requested changes

2017-06-27 16:53 UTC, mxxcon commented on _data/social.yml
>        twitter: Pinterest
twitter info is not necessary for `tfa: yes` sites.

2017-06-27 18:04 UTC, timonus commented
@mxxcon you got it, updated.

2017-06-27 18:09 UTC, stephengroat approved these changes
thanks for the pr @timonus! i just removed the `twitter` tag and pointed the `doc` link to the help page

2017-06-27 18:21 UTC, timonus commented on _data/social.yml
>        twitter: Pinterest
Looks like @stephengroat did this.

2017-06-27 19:09 UTC, mxxcon approved these changes

2017-06-27 19:10 UTC, merged

2017-06-28 16:11 UTC, 0x0ece commented
Out of curiosity, when will it be deployed? (just waiting to do some screenshots to tweet around)

2017-06-28 17:41 UTC, Carlgo11 commented
@0x0ece either when I get back from vacation (in a week) or if @jamcat22 merges. Let’s hope on the second one :wink:

2017-06-28 17:43 UTC, 0x0ece commented
Thanks @Carlgo11, enjoy your vacation!