Add context.io
2factorauth/twofactorauth pull request #2631
Opened 2017-07-12 23:50 UTC by stephengroat

2017-07-13 08:43 UTC, ghost approved these changes

2017-07-14 02:22 UTC, fpigerre approved these changes

2017-07-19 04:06 UTC, jamcat22 requested changes
Should we use `https://context.io/security-faq` as the doc link? They have a short blurb about enabling 2FA as an answer to the last question.

2017-07-19 18:55 UTC, jamcat22 approved these changes

2017-07-19 18:55 UTC, merged