Update Samsung
2factorauth/twofactorauth pull request #2641
Opened 2017-07-17 10:05 UTC by Jawshy

#### Changes: 
- Updated: Samsung under retail. 

  - Samsung supports SMS two factor authentication (referred to as "2-step verification" on the webpage.) I briefly searched for a doc link, but could not find one. 

#### Steps to turn on 2-step verification: 

1. Go to [Samsung account](https://account.samsung.com/). 
2. Click _Sign in_. 
3. Enter login details. 
4. Click _Security_. 
5. Verify password. 
6. On _Enable 2-step verification_ click _Turn On_. 
7. Enter phone number and confirm. 
8. _???_ 
9. Security!

2017-07-17 14:33 UTC, stephengroat approved these changes

2017-07-19 03:41 UTC, jamcat22 requested changes
I think we should use `https://help.content.samsung.com/csweb/faq/searchFaq.do?category1_id=sacb-01-003&serviceCd=saccount` as the doc link unless someone finds a better one.

2017-07-19 04:16 UTC, Jawshy commented
Thanks for finding that, @jamcat22. I've added it to the pull request.

2017-07-19 18:57 UTC, jamcat22 approved these changes

2017-07-19 18:57 UTC, merged