Add ING-DiBa Austria
2factorauth/twofactorauth pull request #2666
Opened 2017-07-27 14:06 UTC by eega

2017-07-27 15:19 UTC, stephengroat approved these changes
thanks for doing the split and the pr @eega!

2017-08-08 14:33 UTC, Carlgo11 requested changes
Here's a more compressed logo. Please use that one instead.
![ingdibaaustria](https://user-images.githubusercontent.com/3535780/29076941-3bd0998e-7c57-11e7-8df7-d69e2f86e9fa.png)

2017-08-09 06:36 UTC, eega commented
Sure, replaced the icon with the compressed version you provided.

2017-08-09 14:21 UTC, Carlgo11 approved these changes

2017-08-09 14:21 UTC, merged