Add vcu
2factorauth/twofactorauth pull request #2668
Opened 2017-07-27 15:26 UTC by stephengroat

the image isn't the best, but it's their logo

closes #2667

2017-08-07 02:10 UTC, Jawshy requested changes
The URL says `https://` but I can only connect to their main webpage over `http://`. 

I suggest using the following image. It's their favicon converted to PNG. ![vcu](https://user-images.githubusercontent.com/10876578/29009745-4799fdc6-7b69-11e7-9aa4-34f44c95817f.png)

2017-08-14 22:13 UTC, Carlgo11 approved these changes

2017-08-15 03:22 UTC, stephengroat commented
@Jawshy the `http` redirects to `https`. i'd rather leave it in the hope that they'll upgrade, but it still connects as is

2017-09-06 04:22 UTC, Jawshy approved these changes

2017-09-06 04:23 UTC, merged