added Federal Student Aid
2factorauth/twofactorauth pull request #2671
Opened 2017-07-28 06:18 UTC by mrbmi513

aka FAFSA, US Government's Federal Student Aid programs

2017-07-28 19:56 UTC, stephengroat approved these changes
thanks for the pr @mrbmi513

2017-07-31 16:24 UTC, Carlgo11 requested changes
I recommend you use this image instead. It's better fitted for small sizes such as 32x32px.
![favicon_32x32](https://studentaid.ed.gov/sa/sites/all/themes/ise/images/favicon-32x32.png)

2017-09-26 21:41 UTC, stephengroat approved these changes

2017-09-26 21:42 UTC, Carlgo11 approved these changes

2017-09-27 13:06 UTC, merged