added Chartbeat
2factorauth/twofactorauth pull request #2683
Opened 2017-08-17 15:52 UTC by paulschreiber

2017-08-18 16:47 UTC, stephengroat approved these changes

2017-12-06 21:53 UTC, jamcat22 requested changes
The last sentence of the [`doc`](https://chartbeat.zendesk.com/hc/en-us/articles/209531888-Two-Factor-Authentication) article states: 

> After that, or if you chose to just use SMS, you’ll need to enter a phone number.

Does this mean that an SMS number is required for software 2FA?

2017-12-08 14:03 UTC, paulschreiber commented
@jamcat22 Yes, that's correct.

2018-02-13 20:05 UTC, jamcat22 approved these changes

2018-02-13 20:06 UTC, merged