Reddit is beta-testing 2FA
2factorauth/twofactorauth pull request #2739
Opened 2017-09-20 00:40 UTC by haykam821

Reddit has started enabling a software-generated token. Because of this, I made this pull request but made the exceptions state it's only for beta testers.

![image](https://user-images.githubusercontent.com/24855774/30621646-4485193a-9d7a-11e7-9d66-005ca98615a1.png)

2017-09-20 02:37 UTC, mxxcon submitted a review, later dismissed

2017-09-20 02:37 UTC, mxxcon commented on _data/social.yml
>        twitter: reddit
Remote `twitter` if `tfa:yes`

2017-09-20 02:41 UTC, jamcat22 commented
Additional info seems to be available here: https://www.reddit.com/r/modnews/comments/6x1uh7/twofactor_authentication_beta_for_moderators/

2017-09-21 13:36 UTC, stephengroat commented
since this is for moderators only and the such a small subset of their users, i'm not sure this one would be ready to post.

2017-09-21 14:04 UTC, mxxcon commented
If you join beta thing on reddit and go to their beta subreddit, you'll see some posts about tfa too..

2017-09-22 13:02 UTC, jamcat22 commented
Maybe we should use a status label?

2017-09-22 15:12 UTC, RichJeanes commented
I think it's fair to add this since it is a pretty big deal for moderators, more so than your every day user. A user gets their account hacked, they might lose some fake internet points. A mod gets their account hacked and a whole community (potentially) gets nuked. But, yes, put an exception text on it that it is beta and mod-only at this time.

2017-09-24 20:03 UTC, Carlgo11 requested changes
As per [331440306](https://github.com/2factorauth/twofactorauth/pull/2739#issuecomment-331440306) and [331475143](https://github.com/2factorauth/twofactorauth/pull/2739#issuecomment-331475143), add a note that it's only applied to moderators or set tfa to no.

2017-10-13 01:15 UTC, Carlgo11 commented
Closing due to inactivity.

2017-10-13 01:15 UTC, closed without merging