Add degoo
2factorauth/twofactorauth pull request #2750
Opened 2017-09-24 17:41 UTC by Nicos18

2017-09-24 17:42 UTC, stephengroat requested changes
@Nicos18 please cleanup the trailing whitespace on lines 45 and 53

2017-09-24 18:02 UTC, stephengroat approved these changes

2017-09-24 18:19 UTC, mxxcon approved these changes

2017-09-24 18:20 UTC, mxxcon requested changes
Actually, shouldn't this go into backup category rather than cloud?

2017-09-25 05:03 UTC, mxxcon approved these changes

2017-09-25 05:04 UTC, merged