Add Askfm
2factorauth/twofactorauth pull request #2753
Opened 2017-09-25 16:06 UTC by Nicos18

2017-09-25 16:35 UTC, stephengroat commented
@Nicos18 we tend to only count `tfa: yes` when the site protects it's login with it, not when oauth/third party provided 2fa is the only protection

2017-09-25 16:37 UTC, Nicos18 commented
@stephengroat I didn't know. I will update the file according to this

2017-09-26 22:05 UTC, Carlgo11 requested changes

2017-09-26 22:05 UTC, Carlgo11 commented on _data/social.yml
> +    - name: Askfm
Change the name to `ASKfm`

2017-09-27 11:46 UTC, Carlgo11 requested changes
Please use this logo instead.
![askfm](https://user-images.githubusercontent.com/3535780/30911766-2bb284ea-a38a-11e7-8f2a-e6a362ed9c18.png)

2017-09-27 11:51 UTC, Carlgo11 approved these changes

2017-09-27 15:52 UTC, mxxcon commented
Why do you think this site qualifies to be listed?

2017-09-27 16:03 UTC, Nicos18 commented
I think that it should be listed because ASKfm is a site used especially by bullies (there are many cases about this site), and requesting a 2FA method, many bullies could be discouraged to do this.

2017-09-27 16:10 UTC, mxxcon commented
If this is that kind of site, I'm not sure it is even worth getting publicity by being listed here. 🤔

2017-09-27 16:14 UTC, Nicos18 commented
This is the Wikipedia's page about ASKfm: https://en.wikipedia.org/wiki/ASKfm

If you think that it shouldn't be listed on the site, close this pull request. No problem!

2017-09-28 00:31 UTC, Carlgo11 commented
@mxxcon ASKfm was popular a couple of years ago with pre-teens and teens (say around 10-13yo).

I’ve never used it myself but I’ve seen some people use it and it’s mostly just anonymous questions to others. ‘Do you think x is cute?’ ‘Did you see what y did today in class?’ and things like that.

By the looks of it most of their accounts seem to be inactive but it was a pretty big social network at that time. That means they still have a lot of data and so it would probably be worth protecting.

As I’ve said earlier, I don’t have any first hand experience with the site but I would assume there would be some bullying happening on such sites. If the target audience is of that age it’s almost impossible not to have that. Especially when people can post anonymously.

As with all social media the negative posts are in a minority but of course that’s the posts that get attention.


> On 27 Sep 2017, at 18:10, mxxcon <notifications@github.com> wrote:
> 
> If this is that kind of site, I'm not sure it is even worth getting publicity by being listed here. 🤔
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
>

2017-09-28 08:35 UTC, Nicos18 commented
@Carlgo11 I saw myself that, especially for profile with more than 10K answers, in many cases there are very sensitive data, such as the school that the user attends, and so on

2018-04-13 16:18 UTC, mxxcon approved these changes

2018-04-13 16:18 UTC, merged