Add Spare5
2factorauth/twofactorauth pull request #2764
Opened 2017-09-26 15:33 UTC by Nicos18

2017-09-26 16:17 UTC, stephengroat commented
replacement image

![favicon](https://user-images.githubusercontent.com/1159138/30871367-8424f68e-a29b-11e7-8e25-69d10f602746.png)

2017-09-26 16:18 UTC, stephengroat approved these changes

2017-09-26 16:19 UTC, stephengroat requested changes
currently not popular enough https://www.domaintally.com/www/spare5.com

2017-09-26 16:22 UTC, Nicos18 commented
@stephengroat on official alexa site, it is 37,497 in the global rank. That websites was updated over 8 months ago

https://www.alexa.com/siteinfo/spare5.com

2017-09-26 16:30 UTC, stephengroat approved these changes

2017-09-27 00:40 UTC, mxxcon approved these changes

2017-09-27 00:40 UTC, merged