Add Kik Messenger
2factorauth/twofactorauth pull request #2773
Opened 2017-09-26 20:43 UTC by Nicos18

2017-09-26 23:14 UTC, Carlgo11 requested changes
Please use this logo instead. It's smaller and transparent.
![kik](https://user-images.githubusercontent.com/3535780/30888501-2087e5a6-a321-11e7-95e6-eb88658a6aa9.png)

2017-09-26 23:14 UTC, Carlgo11 commented on _data/communication.yml
> +    - name: Kik Messenger
Maybe just let the name be `Kik`? Seems like they use that themselves.

2017-09-26 23:14 UTC, Carlgo11 commented on _data/communication.yml
> +
Add `email_address: support@kik.com`

2017-09-26 23:14 UTC, Carlgo11 commented on _data/communication.yml
> +      img: kikmessenger.png
Same here, name could just be kik.

2017-09-26 23:14 UTC, Carlgo11 commented on _data/communication.yml
> +      twitter: kik
Make the first K capital. (aka `twitter: Kik`)

2017-09-27 11:24 UTC, Carlgo11 approved these changes

2017-09-27 15:36 UTC, merged

2017-10-04 11:15 UTC, Jawshy commented on _data/communication.yml
> +
There's an extra line break [here](https://github.com/2factorauth/twofactorauth/blob/7ea0c6a695238945d5d5f24bf3c56d7436eb3618/_data/communication.yml#L101). Could a pull request be skipped and go straight to committing to `master`, @2factorauth/core?