Add CrowdFlower
2factorauth/twofactorauth pull request #2779
Opened 2017-09-26 22:35 UTC by Nicos18

2017-09-26 23:15 UTC, stephengroat approved these changes

2017-09-27 11:27 UTC, Carlgo11 commented
```
_data/other.yml is not alphabetized by name
```
I think it counts a blankspace as before any letter in the alphabet.
Move it below Crowd Supply and I think it should work :wink:

2017-09-27 15:42 UTC, mxxcon requested changes
Lets use their logo https://www.crowdflower.com/wp-content/themes/crowdflower/favicon/favicon-32x32.png

2017-09-27 16:02 UTC, mxxcon approved these changes

2017-09-27 16:02 UTC, merged