add Bitflyer and Bithumb from 'acceptbitcoincash'
2factorauth/twofactorauth pull request #2848
Opened 2017-11-13 04:39 UTC by spazvt

* add 'Bitflyer' and 'Bithumb' crypto currency exchanges from fork
  https://github.com/acceptbitcoincash/acceptbitcoincash

2018-05-13 01:51 UTC, spazvt commented
These two websites have A LOT of traffic. 
[Bithumb Alexa rank is 4930](https://www.alexa.com/siteinfo/bithumb.com) globally and 153 in South Korea.
[Bitflyer Alexa rank is 2932](https://www.alexa.com/siteinfo/bitflyer.jp) globally and 236 in Japan.

Please use google translate to verify the [Google Authenticator and OTP instructions for bithumb](http://bithumb.cafe/archives/7286). (I don't know Korean, but it links directly to their user page to show users how to enable it.)

2018-05-23 00:50 UTC, Carlgo11 requested changes

2018-05-23 00:50 UTC, Carlgo11 commented on _data/cryptocurrencies.yml
> +      doc: http://bithumb.cafe/archives/7286
Seems that they support HTTPS (even though some stuff still load HTTP). Could you change the doc to `https://bithumb.cafe/archives/7286 `?

2018-05-24 02:05 UTC, spazvt commented
URL updated to https.

2018-05-24 02:29 UTC, Carlgo11 requested changes
The bitflyer logo you provided contains text which often makes the logo look weird when shrunken down to 32x32 pixels. Here's one from their site that just is the logo (without any text).
![32x32](https://user-images.githubusercontent.com/3535780/40461283-e01468ea-5f0a-11e8-99f0-851061c81092.png)

2018-05-24 03:00 UTC, spazvt commented
ok I'll avoid text next time.

2018-05-25 01:28 UTC, Carlgo11 approved these changes

2018-06-05 12:29 UTC, brycx approved these changes

2018-06-05 19:26 UTC, merged