Adding TFA info for Direct Mail
2factorauth/twofactorauth pull request #2887
Opened 2017-12-08 18:06 UTC by jhammer

2017-12-10 16:10 UTC, Carlgo11 requested changes
Hello @jhammer,
thanks for the PR! It looks like the logo is a bit too big. Here's a compressed one: 
![directmail](https://user-images.githubusercontent.com/3535780/33806756-032ac2a8-ddcd-11e7-9d16-46aeb56c1af9.png)
I suggest using that one instead. 😉

2017-12-11 18:57 UTC, jhammer commented
Thanks @Carlgo11. I've updated the icon.

2017-12-12 22:23 UTC, Carlgo11 approved these changes

2017-12-14 19:10 UTC, jamcat22 approved these changes

2017-12-14 19:10 UTC, merged