Update Nutmeg entry: 2FA is supported via TOTP app.
2factorauth/twofactorauth pull request #2919
Opened 2017-12-27 15:21 UTC by Flameeyes

2017-12-27 17:50 UTC, stephengroat submitted a review, later dismissed
thanks for the pr @Flameeyes

2017-12-27 17:59 UTC, mxxcon requested changes

2017-12-27 17:59 UTC, mxxcon commented on _data/investing.yml
> +      facebook: TheNutmegTeam
'twitter' should NOT be present when `tfa: true`.
'facebook' should NOT be present when `tfa: true`.

2017-12-27 23:57 UTC, Flameeyes commented
Updated, PTAL.

2018-01-01 15:22 UTC, Flameeyes commented
Ping?

2018-01-01 15:26 UTC, mxxcon approved these changes

2018-01-17 00:49 UTC, Flameeyes commented
Hi folks, any update on this one? :)

2018-01-17 01:02 UTC, Jawshy approved these changes
Looks good. Thanks for the pull request, @Flameeyes. 

For any future pull requests I'd recommend creating a [new branch](https://help.github.com/articles/creating-and-deleting-branches-within-your-repository/) on your fork.

2018-01-17 01:03 UTC, merged