updated ebay 2FA options. Currently ebay now only supports SMS 2FA
2factorauth/twofactorauth pull request #2930
Opened 2018-01-06 04:04 UTC by Sunit-Kulkarni

2018-01-08 03:20 UTC, Carlgo11 approved these changes
Looks good to me. Nice work on keeping the text short yet informative! 👍

2018-01-18 23:01 UTC, jamcat22 requested changes
I think we should remove `hardware` and `software` tags since they're not supported for new users. See #2480 for a similar situation we handled with Patreon.

2018-01-19 01:02 UTC, Jawshy requested changes
I agree with @jamcat22 plus the url can be updated to use HTTPS: `https://www.ebay.com/`.

2018-02-05 15:29 UTC, jamcat22 commented
Duplicate of #2987

2018-02-05 15:29 UTC, closed without merging