Add Bitwarden exception
2factorauth/twofactorauth pull request #2946
Opened 2018-01-13 15:46 UTC by brycx

Bitwarden requires you to have a [premium](https://help.bitwarden.com/article/setup-two-step-login/) account to use hardware 2FA. I think it would be good to have an exception for this.

2018-01-13 16:35 UTC, mxxcon approved these changes

2018-01-14 04:00 UTC, Carlgo11 requested changes
To me it looks like it's not just only for hardware 2FA.
I suggest you rephrase it to `"Premium account required for SMS, Phone call and hardware 2FA"` or something similar.
I'm not a native English speaker so the structuring might need some improvements ¯\_(ツ)_/¯

2018-01-14 04:12 UTC, mxxcon commented
Carl, sms and phone call are properties of Duo's offering.
From what I can see you can't have them w/o Duo.
Perhaps change the wording further that Duo, Yubikey and FIDO U2F require paid plan?

2018-01-14 08:44 UTC, brycx commented
Is this better?

2018-01-15 09:14 UTC, Jawshy approved these changes
👍

2018-01-17 09:57 UTC, Carlgo11 approved these changes

2018-01-17 09:57 UTC, merged