Investing - Vanguard poor use of Yubikey (FIDO) noted
2factorauth/twofactorauth pull request #2962
Opened 2018-01-22 18:28 UTC by PeterTheobald

Updated Vanguard entry to note that use of FIDO device like Yubikey is trivially bypassed by simply checking a box for "I forgot my device please use SMS instead". SMS cannot be disabled, thus the security of Yubikey is not actually enforced. Tested as of Jan 2018.

2018-01-22 22:07 UTC, RichJeanes commented
I don't know that an exception is called for when a site lets you use any of your configured 2FA methods. This exception could apply to a lot of sites, like Google.

2018-01-22 22:28 UTC, jamcat22 commented
This would likely be better rephrased to “SMS required for 2FA.” to line up with the other exceptions on the site.

2018-02-05 15:19 UTC, jamcat22 approved these changes

2018-02-07 17:14 UTC, Carlgo11 requested changes
Try and keep changes to one per PR.
Remove the BOA change from this PR and move it to another PR.
I suggest you use separate branches instead of pushing to your master branch. 😉

2018-02-07 23:00 UTC, PeterTheobald commented
Sorry - git-illiterate here. Tried making the change to a new branch, couldn't issue a pull request to you, only to my own master. Merged w my own master, issued a pull request to you from there. Giving up now *sigh* looks longingly at dusty SVN.

2019-06-15 06:08 UTC, kmpoppe commented
@PeterTheobald unfortunately, your pull request has accumulated quite a bit of merge conflicts, with another exception (worded differently) also being added to Vanguard.
For the sake code cleanliness, I'd like to close this PR and create a new one to incorporate what you said there.
If I don't hear anything from you within 14 days, I'll close this PR.
Thank you for your contribution, which is much valued!
// Kai

2019-06-15 14:10 UTC, PeterTheobald commented
sounds good to me. thanks. 

Sent from my iPhone

> On Jun 15, 2019, at 2:08 AM, Kai Michael Poppe <notifications@github.com> wrote:
> 
> @PeterTheobald unfortunately, your pull request has accumulated quite a bit of merge conflicts, with another exception (worded differently) also being added to Vanguard.
> For the sake code cleanliness, I'd like to close this PR and create a new one to incorporate what you said there.
> If I don't hear anything from you within 14 days, I'll close this PR.
> Thank you for your contribution, which is much valued!
> // Kai
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.

2019-08-11 08:24 UTC, kmpoppe commented
Closing to be replaced by #3963

2019-08-11 08:24 UTC, closed without merging