Added Parsec
2factorauth/twofactorauth pull request #2969
Opened 2018-01-27 15:02 UTC by jamezrin

Parsec is a remote access tool that focus primarily on gaming.

2018-01-29 18:47 UTC, stephengroat submitted a review, later dismissed
[looking relatively popular on alexa](https://www.alexa.com/siteinfo/parsecgaming.com), approving

2018-03-20 22:47 UTC, jamezrin commented
Sorry for asking but is this going to be added?

2018-03-21 00:09 UTC, mxxcon requested changes

2018-03-21 00:09 UTC, mxxcon commented on _data/remote.yml
> +      email_address: founders@parsec.tv
Their website lists founders@parsecgaming.com address

2018-03-21 00:46 UTC, mxxcon approved these changes

2018-03-28 16:47 UTC, jamezrin commented
Anything else for it to get merged?

2018-03-28 16:50 UTC, merged