Add Caisse Epargne bank (FR)
2factorauth/twofactorauth pull request #2977
Opened 2018-02-01 10:03 UTC by chatainsim

Add Caisse Epargne bank (FR)

2018-02-01 12:54 UTC, Jawshy submitted a review, later dismissed
Thanks for the pull request, @chatainsim. Unfortunately, there are a couple of issues that I'm hoping you could resolve. Please resize the image to exactly 32 by 32 pixels and under 2,500 bytes in size. Saving the image at a bit depth of 8 rather than 32 can help reduce the file size.

2018-02-03 00:10 UTC, chatainsim commented
Done

2018-02-11 19:55 UTC, nagromc commented
I think the Twitter account should be [@CaissEpargneSAV](https://twitter.com/CaissEpargneSAV) (I know, an 'e' is missing at character 6) rather than [@Caisse_Epargne](https://twitter.com/Caisse_Epargne). The first one is for asking questions (_Nous répondons à vos questions_). The second one is for marketing purposes (_Découvrez l'actualité de la marque Caisse d'Epargne à travers ses multiples engagements !_).

See my (submitted too quickly) [PR](https://github.com/2factorauth/twofactorauth/pull/2996/files#diff-7227dddb57500925d273116121c64aa5R168).

2018-02-11 20:43 UTC, chatainsim commented
@nagromc yes it's better I think. I didn't know that they have a 'SAV' account. Good to know.

2018-02-12 11:24 UTC, Carlgo11 commented
How about this logo instead?
It doesn't contain that white border.

![logo](https://user-images.githubusercontent.com/3535780/36094690-84bc2a4c-0fef-11e8-9181-bf2a231633ff.png)

Other than that the PR looks good 😄

2018-02-12 13:24 UTC, chatainsim commented
@Carlgo11 thanks, updated

2018-02-13 00:09 UTC, Carlgo11 approved these changes
Looking good! 👍

2018-02-13 00:12 UTC, Carlgo11 commented on _data/banking.yml
> +    - name: Caisse D'Eparnge
On their Facebook and Twitter page they've named themselves Caisse d'Epargne with a lowercase d. I don't speak French so I won't try to request any changes here but if it is a typo here you might want to change that. 😉 
If not then this PR is good to go.

2018-02-13 09:54 UTC, chatainsim commented
Updated :) Thanks

2018-02-15 20:12 UTC, nagromc requested changes
There is a typo: "Epar**gn**e"

2018-02-15 20:19 UTC, chatainsim commented
Fixed

2018-02-15 20:19 UTC, chatainsim commented
Fixed

2018-02-16 22:49 UTC, Carlgo11 commented
Now https://github.com/2factorauth/twofactorauth/pull/2977#discussion_r167727169 is reverted. :/

2018-02-21 23:03 UTC, chatainsim commented
@carlgo11 what does that mean?

2018-02-24 23:13 UTC, stephengroat commented
@chatainsim the `d` has been upper-cased again to `D`

2018-02-27 10:28 UTC, chatainsim commented
I'm not able to find any capital D, sorry.

2018-02-27 10:34 UTC, nagromc commented
> I'm not able to find any capital D, sorry.

I agree. See the [line 166 of modified file](https://github.com/2factorauth/twofactorauth/pull/2977/files#diff-7227dddb57500925d273116121c64aa5R166) in the PR. I don't see the problem @stephengroat @Carlgo11

2018-02-27 10:34 UTC, nagromc approved these changes

2018-02-27 16:34 UTC, stephengroat approved these changes
thanks for the pr @chatainsim

2018-02-27 16:34 UTC, merged

2018-02-28 00:19 UTC, Carlgo11 reviewed
https://github.com/2factorauth/twofactorauth/pull/2977#issuecomment-368823371
Right. And I asked you to change it to uppercase.

**Edit: I fixed it in 14c286878c5919691ea8e2ac7c632208d949a35b**

2018-02-28 00:28 UTC, Carlgo11 commented
I'll merge it when https://github.com/2factorauth/twofactorauth/pull/2977#pullrequestreview-99906355 is solved.

2018-02-28 09:18 UTC, chatainsim commented
Thanks, I was reading too quickly. My bad.

2018-04-05 03:39 UTC, psgs commented
@Carlgo11 According to convention, the capital letter in this sentence is already the "É" in Épargne. Capitalising the "d" is unnecessary.

This is shown on the Caisse d'Épargne Facebook page as well.

![screen shot 2018-04-05 at 13 38 07](https://user-images.githubusercontent.com/3946887/38346160-a44cf0b6-38d6-11e8-887d-876ff7b50935.png)