Added Adobe software 2FA
2factorauth/twofactorauth pull request #3013
Opened 2018-02-15 10:49 UTC by hellyarbm

2018-02-15 13:21 UTC, Jawshy requested changes
Thanks for the pull request, @hellyarbm. 

Could you please add the following under `doc`: 
```ruby
      exceptions:
          text: "To activate 2-Step Verification, you must provide a mobile phone number."
```

2018-02-15 20:04 UTC, hellyarbm commented
Nice catch Jawshy, as I definitely missed that

2018-02-16 10:50 UTC, Jawshy approved these changes

2018-02-21 04:55 UTC, jamcat22 approved these changes

2018-02-21 04:55 UTC, merged