Updated TD Bank US
2factorauth/twofactorauth pull request #3049
Opened 2018-03-08 20:15 UTC by elahd

#3046

2018-03-08 20:19 UTC, mxxcon submitted a review, later dismissed

2018-03-09 17:31 UTC, Carlgo11 requested changes

2018-03-09 17:31 UTC, Carlgo11 commented on _data/banking.yml
> -    - name: Caisse D'Epargne
Looks like you're not up to the with our master branch. I suggest you pull/revert before we merge this PR.

2018-03-09 19:34 UTC, closed without merging

2018-03-18 03:40 UTC, jamcat22 commented
Duplicate of #3052