Add BBVA Compass to list of banking sites
2factorauth/twofactorauth pull request #3074
Opened 2018-03-19 15:00 UTC by jmeridth

- no 2fa
- image included

2018-03-19 15:28 UTC, stephengroat commented
@jmeridth could you [look at the travis logs](https://travis-ci.org/2factorauth/twofactorauth/jobs/355403074#L1010-L1023)? there's a few errors that need to be dealt with before this is g2g, let us know if you need any help!

2018-03-19 15:36 UTC, jmeridth commented
@stephengroat definitely.  Looking.

2018-03-19 15:53 UTC, jmeridth commented
@stephengroat :green_heart:

2018-03-19 16:07 UTC, stephengroat commented
@jmeridth thanks for the work!

as a rule of thumb, we try to avoid having tons of text in the image icons (at 32x32 px, it's basically impossible to read).

i found the bbva compass favicon and scaled it to 32x32 which i think would be better than what's currently in there, do you know of any other logos they have with no text at all?

![bbvacompass](https://user-images.githubusercontent.com/1159138/37607313-ec979630-2b54-11e8-916a-fbfd88cfa860.png)

2018-03-19 16:24 UTC, jmeridth commented
@stephengroat awesome. thank you.

2018-03-23 13:26 UTC, jmeridth commented
@stephengroat done.

2018-03-23 13:33 UTC, stephengroat submitted a review, later dismissed

2018-03-26 13:04 UTC, Carlgo11 requested changes

2018-03-26 13:04 UTC, Carlgo11 commented on _data/banking.yml
> +      twitter: bbvacompass
Please capitalize the twitter tag so that it matches their twitter handle. `BBVACompass`

Thank you!

2018-03-26 16:50 UTC, jmeridth commented
@Carlgo11 done.

2018-03-26 17:07 UTC, Carlgo11 approved these changes

2018-03-26 17:07 UTC, Carlgo11 commented
@jmeridth Great! Thanks :smile:

2018-03-27 00:19 UTC, mxxcon approved these changes

2018-03-27 00:19 UTC, merged