Update semantic-ui
2factorauth/twofactorauth pull request #3167
Opened 2018-04-29 22:24 UTC by stephengroat

2018-04-29 23:47 UTC, mxxcon commented on _layouts/secondary.html
>  <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.13/semantic.min.js"
I think you forgot to update version here

2018-05-01 13:50 UTC, kenman345 requested changes
https://github.com/2factorauth/twofactorauth/pull/3167/files#diff-f96e55fbd5421f2438a0dbfe7df336e2R19

I think since Semantic 2.3.1 changed `bitcoin` icon to have a circle backdrop, that you would like to instead have the icon be `btc` which is the same as what `bitcoin` looked like in 2.2.7

2018-05-01 16:31 UTC, stephengroat commented
@kenman345 great catch!

i actually liked the change to something new, anyone have an opinion on it?

2018-05-01 16:49 UTC, kenman345 commented
I recommend making my suggested change. the `btc` icon is the one meant to indicate a currency, and not a specific implementation of bitcoin. It makes more sense as a crypto based section to be a bit more agnostic and more towards a symbol recognized for the space youre hoping to cover with that category.

2018-05-01 16:57 UTC, stephengroat commented
> the btc icon is the one meant to indicate a currency, and not a specific implementation of bitcoin

are you sure that's right? from googling around, i'm not 100% sure. both seem to stand for bitcoin, it comes down to preference

https://en.bitcoin.it/wiki/Bitcoin_symbol

https://en.wikipedia.org/wiki/Bitcoin

2018-05-01 17:32 UTC, kenman345 commented
among other reasons, the circle around the icon makes it messier for your site.

I obviously have an opinion on this as I help maintain acceptbitcoin.cash....but you're free to do as you wish, both have their merits.

2018-05-02 05:48 UTC, mxxcon commented
I agree with Ken here. 
We'd want to use `btc` icon ₿ as a generic "cryptocurrency" image rather than a specific "bitcoin"-brand icon.

2018-05-02 12:57 UTC, kenman345 commented
Side note: This PR brings up a glaring issue with your Jekyll setup. Why does each and every notes page have to be adjusted? Why is this not templated as a template or inside an `_include`? 

If you'd like I can take a look at that. Its probably not going to result in smaller page sizes but it should bee able to reduce redundant styling across pages so its easier to make the next upgrade to a newer versioon of Semantics UI in the future. 

Such a change would best be done once this is merged in so I have these changes to work off of.

2018-05-02 22:49 UTC, stephengroat commented
agreed, it's a good point, but let's tackle stuff one pr at a time.

2018-05-15 15:19 UTC, kenman345 commented
Would love if this got merged in so I can make a PR to consolidate the layouts. This change has already been made on my fork of the site and working wonderfully. I dont foresee this being an issue to your site at all.

2018-05-22 04:25 UTC, fpigerre approved these changes

2018-06-01 16:58 UTC, kenman345 commented
can we merge this? Its been working just fine for a long time on my project, making the same changes you have here. Its also delaying some changes to the notes layout to make it easier to update in the future.

2018-06-01 17:44 UTC, jamcat22 approved these changes

2018-06-01 17:44 UTC, merged

2018-06-01 17:45 UTC, jamcat22 commented
Sorry @kenman345. Didn’t see that @psgs already reviewed the changes.