Update TD Ameritrade TFA status
2factorauth/twofactorauth pull request #3178
Opened 2018-05-05 15:18 UTC by ItsMattL

Instructions require account login...
https://invest.ameritrade.com/cgi-bin/apps/u/help/security/protectingYourAccountAndPersonalData/twoFactorAuthentication

2018-05-05 15:34 UTC, mxxcon requested changes

2018-05-05 15:34 UTC, mxxcon commented on _data/investing.yml
>        twitter: TDAmeritrade
Please remove twitter line since it's no longer needed.

2018-05-05 15:34 UTC, mxxcon commented on _data/investing.yml
Please add your url or another publicly accessible one as `doc:` line

2018-05-05 15:58 UTC, mxxcon submitted a review, later dismissed

2018-05-05 20:06 UTC, jamcat22 submitted a review, later dismissed
Because the doc link requires logging in, should we add an exception to state this, or create a note to replace it? Could someone with a TD Ameritrade account post a screenshot of the doc link (blurring out any sensitive info)?

2018-05-05 21:52 UTC, ItsMattL commented
Sure, here you go.

![ameritrade help](https://user-images.githubusercontent.com/1213849/39667854-b384212e-5084-11e8-88b1-dad8af05dd2a.png)

2018-05-06 04:08 UTC, mxxcon commented
@jamcat22 i don't think we've done that before...We generally prefer publicly accessible URls, but if not it's ok too..

2018-05-19 14:34 UTC, ItsMattL commented
Anything else I can do here?

2018-06-07 01:19 UTC, Carlgo11 commented
@mxxcon I disagree, I've seen many PRs where we have simply left out the doc page because it's behind a login screen. In fact I think most sites listed here that only list documentation for registered users are without a doc link.

2018-08-06 23:11 UTC, ItsMattL commented
Ping... 

I'm amenable to however the project owners want to manage the documentation, but I think it's unfortunate that in the mean time, the site has been providing outdated information for multiple months now. :\

2018-08-07 09:00 UTC, brycx commented
Hi @ItsMattL 
It is unfortunate, and we all try our best with the amount of time we can put aside for reviewing. That's no excuse of course for PR's to be left behind. I appreciate the ping.

I agree with @Carlgo11, most sites with walled doc-links aren't given the `doc:` attribute. Please remove the doc link.

2018-08-09 17:22 UTC, brycx approved these changes

2019-01-29 05:03 UTC, stephengroat approved these changes

2019-01-29 05:03 UTC, merged