Add SAFE Credit Union
2factorauth/twofactorauth pull request #3190
Opened 2018-05-12 08:31 UTC by brycx

Fixes #2881.

2018-05-13 02:11 UTC, spazvt commented
confirmed [Alexa traffic rank of 108k](https://www.alexa.com/siteinfo/safecu.org) is within required threshold of 200k.

2018-05-13 02:31 UTC, mxxcon requested changes
Consider using their fav icon 
![safe_logo_32sq](https://user-images.githubusercontent.com/847140/39963234-2a1f3166-5634-11e8-9e21-6291eb6698c3.png)

2018-05-13 23:40 UTC, Carlgo11 approved these changes

2018-05-14 00:22 UTC, mxxcon approved these changes

2018-05-14 00:22 UTC, merged