Added Michigan State University Federal Credit Union to Banking
2factorauth/twofactorauth pull request #3199
Opened 2018-05-15 13:10 UTC by mckenn55

2018-06-03 21:44 UTC, brycx requested changes
Thanks for the PR @mckenn55. I have some concerns:
- The docs say that:
> by choosing to receive a verification code sent via text message, email, or automated voice message.

So the `email: Yes` tag is missing.
- The docs need to explain _how to_ setup 2FA(the current link only says it's available). I couldn't find anything on their homepage, so if the how-to is only for registered customers, please provide a screenshot that documents the setup. Redact personal information, if any.

2018-06-26 04:51 UTC, Carlgo11 requested changes
The logo you chose contains lots of text which looks distorted when shrunk down to 32x32 pixels.
I suggest you use this logo instead:
It contains their MSU characters but without the small text.
![msufcu](https://user-images.githubusercontent.com/3535780/41890002-c1cb4fc6-790d-11e8-8e60-8faf33cae3bb.png)

2018-06-26 04:51 UTC, Carlgo11 commented on _data/banking.yml
> +
Could you remove these extra spaces?

2018-06-26 04:51 UTC, Carlgo11 commented on _data/banking.yml
> +    - name: Michigan State University Federal Credit Union
They call themselves MSU Federal Credit Union. Please change the name to that.

2019-02-04 03:01 UTC, Carlgo11 commented
Closing due to inactivity.

2019-02-04 03:01 UTC, closed without merging