Minor changes on docs and yaml order
2factorauth/twofactorauth pull request #3220
Opened 2018-05-25 12:26 UTC by alex-nitrokey

This is rather cosmetic than a change in content (beside two docs). Would make comparison easier on dongleauth.info though.

2018-05-25 12:31 UTC, alex-nitrokey commented
Okay, I have look, what went wrong, one moment please...

2018-05-25 17:39 UTC, mxxcon requested changes

2018-05-25 17:39 UTC, mxxcon commented on _data/developer.yml
> +      doc: https://docs.gitlab.com/ee/security/two_factor_authentication.html
Your doc link is intended for gitlab admins, whereas our previous link was intended more for end-users.

2018-05-28 06:46 UTC, alex-nitrokey commented on _data/developer.yml
> +      doc: https://docs.gitlab.com/ee/security/two_factor_authentication.html
Right. Sorry, changed it.

2018-05-28 14:18 UTC, mxxcon approved these changes

2018-05-31 19:19 UTC, Carlgo11 approved these changes

2018-05-31 19:19 UTC, merged