Google Hangouts and Digidentity added
2factorauth/twofactorauth pull request #3221
Opened 2018-05-25 12:41 UTC by alex-nitrokey

This is included on https://www.dongleauth.info and seems to fit in here as well.

2018-06-03 21:20 UTC, brycx requested changes
Thanks for the PR @alex-nitrokey. There are two points which need to be addressed:
- Google Hangouts also supports phone and sms for 2FA, so `phone: Yes` and `sms: Yes` needs to be added.
- Due to a limit where a new site needs to be within Alexa top 200k, Digidentity can unfortunately [not be added](https://www.alexa.com/siteinfo/digidentity.eu). This needs to be removed.

The rest looks fine to me.

2018-06-04 07:54 UTC, alex-nitrokey commented
> Due to a limit where a new site needs to be within Alexa top 200k, Digidentity can unfortunately not be added. This needs to be removed.

Didn't realized this limitation, good to know.

I adapted accordingly.

2018-06-04 12:06 UTC, brycx approved these changes

2018-06-04 16:08 UTC, RichJeanes approved these changes

2018-06-04 16:09 UTC, merged