Update citibank au per #1811
2factorauth/twofactorauth pull request #3240
Opened 2018-05-31 13:16 UTC by jimsug

As per our working definition for 2fa, Citibank Australia does not satisfy it. (See Issue #1811)

The [document that is provided in support of its addition](https://www.citibank.com.au/otp/) itself states that:

> You'll need to enter this anytime you want to perform select online transactions or query through Citibank Online.

The entry has been updated to include the financial institution's social media information instead.

2018-05-31 18:55 UTC, Carlgo11 approved these changes

2018-05-31 18:56 UTC, Carlgo11 requested changes
Looks like you accidentally changed the permissions for logo.png and placeholder.png from 644 to 755. Could you revert that?

2018-06-01 13:08 UTC, jimsug commented
@Carlgo11 huh, don't remember doing that... fixed now :smile:

2018-06-01 15:14 UTC, mxxcon submitted a review, later dismissed

2018-06-03 19:39 UTC, Carlgo11 approved these changes

2018-06-04 14:35 UTC, mxxcon approved these changes

2018-06-04 14:36 UTC, merged