Fix up Notes Pages
2factorauth/twofactorauth pull request #3242
Opened 2018-06-01 19:29 UTC by kenman345

Closes #3173 

Found a few issues with Notes pages during these efforts.
1. the new Semantics UI version broke some spacing. I made the spacing as close to what was possible previously.
2. Less pages to go through if future revisions are made to icon naming.
3. We had a Schwab.html page but it was not being shown through the UI. Making the pages in the notes folder appear dynamically will prevent this from ever happening again.
4. Index.html in the notes folder is poor practice. It is instead advisable under Jekyll best practices to have it named `notes.html` and let Jekyll make it into the `index.html` in the `notes` subfolder.

2018-06-15 17:08 UTC, kenman345 commented
someone should take a look at this...

2018-07-10 13:41 UTC, kenman345 commented
No ones even reviewing this?

2018-11-19 21:23 UTC, kenman345 commented
Fixed the merge conflict, this still hasnt been reviewed though. Can this PR get some love?

2018-11-22 04:25 UTC, fpigerre commented
Hello @kenman345!

Sorry this pull request hasn't been looked at. I'll try my best to show it some ❤️ .
So far the changes you've made look great! Awesome work with the tags.
Do you think you might be able to refactor the `notes.html` pages as a `notes/index.html` page? This makes the root of the site a lot cleaner.

Thankyou very much!
psgs 🌴

2018-11-22 04:25 UTC, fpigerre requested changes
* Please refactor `notes.html` as `notes/index.html` if possible

2018-11-22 04:25 UTC, fpigerre commented on _layouts/secondary.html
> +{%- if page.name == 'notes.html' -%}
This is great for moving the notes pages to their own layout page :+1:

2018-11-22 04:28 UTC, fpigerre commented on notes.html
> +{%- for related_page in site.pages -%}
Beautiful 🌴

2018-11-22 05:22 UTC, kenman345 commented
Just oooking at this on my email, will fix things up tomorrow when I get
the chance. Thanks for the feedback

On Wed, Nov 21, 2018 at 11:28 PM Francois <notifications@github.com> wrote:

> *@psgs* commented on this pull request.
> ------------------------------
>
> In notes.html
> <https://github.com/2factorauth/twofactorauth/pull/3242#discussion_r235599020>
> :
>
> > @@ -0,0 +1,29 @@
> +---
> +layout: secondary
> +---
> +<div class="ui stackable grid container">
> +  <div class="three column row">
> +{%- assign row_count = 0 -%}
> +{%- for related_page in site.pages -%}
>
> Beautiful 🌴
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/2factorauth/twofactorauth/pull/3242#pullrequestreview-177501368>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AKeM15nRNEWwWGWmKeTzHoK3sycqw19Mks5uxigDgaJpZM4UXM5l>
> .
>

2018-11-28 19:14 UTC, kenman345 commented on _layouts/secondary.html
> +{%- if page.name == 'notes.html' -%}
Made a change to this based on moving the notes.html page to the subfolder for notes and renaming it to index.html

2018-11-28 19:21 UTC, kenman345 commented
@psgs All the changes around moving the notes.html page to be `notes/index.html` have been made. This should be ready for further review now!

2018-12-06 06:29 UTC, fpigerre approved these changes
Thankyou very much @kenman345! :+1:

2018-12-06 06:34 UTC, psgs commented
@carlgo11 Would you like to take a look and approve this pull request?

2018-12-06 12:13 UTC, kenman345 commented
@psgs just noting contrary to my item 4 of the initial post of this PR I did make your change to the index.html. I think your call is correct about keeping it in the sub folder considering the page is not a single page but a section with linked pages in the notes folder. If it were just a single page it might make sense to keep it as a notes.html page in the root of the repository.

This PR fixes an issue with the current site, and brings back the Schwab page. Would be nice to get the second approval and get this live on the site

2018-12-07 03:37 UTC, Carlgo11 approved these changes
Nice work! 👍

2018-12-07 03:37 UTC, merged