Update Etsy
2factorauth/twofactorauth pull request #3250
Opened 2018-06-08 09:45 UTC by brycx

Fixes #3248.

2018-06-08 14:36 UTC, mxxcon approved these changes

2018-06-25 21:35 UTC, Carlgo11 approved these changes

2018-06-25 21:37 UTC, Carlgo11 requested changes
I don't see anything mentioning software TFA. Are we sure that they support that?

2018-07-04 00:04 UTC, fleish commented
Attaching screenshot showing options for 2FA on etsy.com as of 20180703

<img width="1144" alt="screen shot 2018-07-03 at 5 01 01 pm" src="https://user-images.githubusercontent.com/2106430/42249983-262e0488-7ee3-11e8-81c3-309d5ae680e9.png">

2018-07-04 15:28 UTC, Carlgo11 requested changes
Alright, thanks for the screenshot! :smiley:

2018-07-04 15:29 UTC, Carlgo11 approved these changes

2018-07-04 15:29 UTC, merged