Add Jitbit Helpdesk
2factorauth/twofactorauth pull request #3291
Opened 2018-07-04 11:05 UTC by maxt3r

2018-07-04 11:12 UTC, maxt3r commented
How to check why it failed?

2018-07-04 13:06 UTC, mxxcon requested changes
At this point in time we do not list self-hosted software since that brings too many variables in how to do display such data.

2018-07-04 13:06 UTC, mxxcon commented on _data/other.yml
> +      sms: No
No need for explicit `no` tag.

2018-07-04 18:48 UTC, maxt3r commented
I changed the link to the hosted version (we have both)

2018-07-04 19:04 UTC, mxxcon approved these changes

2018-07-10 14:02 UTC, brycx approved these changes

2018-07-10 14:03 UTC, merged