Update Wikipedia/Wikimedia entry
2factorauth/twofactorauth pull request #3294
Opened 2018-07-11 16:47 UTC by AntiCompositeNumber

Two-factor authentication is available for certain users across all Wikimedia projects. Logo changed from Wikipedia to Wikimedia, and data updated.

2018-07-11 16:54 UTC, mxxcon requested changes
I would keep Wikipedia name since it's by far the most well known and probably most used/searched service of all those.
Also indentations are significant in yaml format. Please correct that.

2018-07-11 22:50 UTC, AntiCompositeNumber commented
I believe I have fixed the indentation issue. I changed everything back to Wikipedia as well. There are some that would be morally opposed to that, but I am not one of them.

2018-07-12 13:39 UTC, mxxcon approved these changes
Why would they be _morally_ opposed to that?

2018-07-13 10:29 UTC, brycx approved these changes

2018-07-13 10:29 UTC, merged