Update Indeed
2factorauth/twofactorauth pull request #3329
Opened 2018-07-26 11:00 UTC by brycx

Fixes #3324.

2018-07-28 02:53 UTC, mxxcon submitted a review, later dismissed

2018-07-28 13:43 UTC, Carlgo11 requested changes

2018-07-28 13:43 UTC, Carlgo11 commented on _data/other.yml
> +      doc: https://support.indeed.com/hc/en-us/articles/360000244123-What-is-Two-Step-Verification-
Could you just do a quick change and make the doc url to `https://support.indeed.com/hc/en-us/articles/360000244123`?
I think that would help if they decided to change the tile of the page which sometimes happens.

2018-07-30 08:48 UTC, brycx commented
Good idea @Carlgo11.

2018-07-30 12:58 UTC, mxxcon approved these changes

2018-07-30 18:38 UTC, Carlgo11 approved these changes

2018-07-30 18:38 UTC, merged