Add Hydrawise
2factorauth/twofactorauth pull request #3351
Opened 2018-08-03 14:08 UTC by mobilutz

2018-08-03 14:27 UTC, mxxcon requested changes

2018-08-03 14:27 UTC, mxxcon commented on _data/other.yml
> +      fta: No
it's `tfa`, not `fta`.

2018-08-03 14:37 UTC, mobilutz commented
@mxxcon Thanks for the hint. I changed it.

2018-08-03 14:54 UTC, mxxcon requested changes

2018-08-03 14:54 UTC, mxxcon commented on _data/other.yml
> +      tritter: Hunter_Ind
This should be `twitter`, not tritter. didn't notice it the first time, but spelling is important ;)

2018-08-06 07:45 UTC, mobilutz commented
@mxxcon So sorry about these typos. It looks like I was not really paying attention.
Thanks for your feedback

2018-08-06 10:46 UTC, brycx commented
Thanks for the PR @mobilutz. We currently have a limitation on new additions, that require a site to be within the Alexa top 200k, which Hydrawise [is sadly not](https://www.alexa.com/siteinfo/hydrawise.com). It's rising though, so maybe we can add it later.

2018-08-06 10:46 UTC, closed without merging

2018-08-06 13:48 UTC, mxxcon commented
Hmm. when I was looking at it it had a higher alexa ranking 🤔

2018-08-06 14:06 UTC, mobilutz commented
@mxxcon I think that @brycx mean global rank.
![screen shot 2018-08-06 at 16 06 25](https://user-images.githubusercontent.com/491877/43721302-b9f9d380-9992-11e8-977a-e15f5ad2641d.png)