Add Plastiq
2factorauth/twofactorauth pull request #3353
Opened 2018-08-03 16:37 UTC by brosnt

2018-08-04 21:29 UTC, Carlgo11 requested changes

2018-08-04 21:29 UTC, Carlgo11 commented on _data/payments.yml
> +      doc: https://help.plastiq.com/hc/en-us/articles/360006794893-How-do-I-enable-2-Step-Authentication-on-my-account-
Could you change the doc url to `https://help.plastiq.com/hc/en-us/articles/360006794893`?

2018-08-05 03:01 UTC, mxxcon approved these changes

2018-08-05 04:15 UTC, Carlgo11 approved these changes

2018-08-05 04:16 UTC, Carlgo11 reviewed
Just to be sure, you realize that we display the logos in a rounded format and that the circle of the Q won't be displayed, right?

2018-08-05 21:25 UTC, brosnt commented
Re: Logo in rounded format - yup, that is fine!

2018-08-06 02:07 UTC, Carlgo11 commented
Alright.

2018-08-06 02:07 UTC, merged