Add Exact Online
2factorauth/twofactorauth pull request #3358
Opened 2018-08-06 12:19 UTC by jeohist

I know the CONTRIBUTING.MD says not to add multiple URLs, but since this is one website hosted on multiple URLs for different countries and we'd really like them to be shown in 1Password's Watchtower functionality... 

I don't think there's really a way for this to be more elegant, other than implementing something like the YAML files in #1025 or straight-up allowing multiple URLs for one website (or Exact Online hosting everything in one domain).

2018-08-06 14:09 UTC, mxxcon commented
Are all those sites use the same login system or are they all separate?
If it's all the same then we should not have multiple entries, just a single main one is sufficient.

If you want 1pass' watchtower to display green checkmark or whatever, then you should approach them to implement the concept of related domains. Other password managers have it and it works great. I would not want us to mangle our data to compensate for deficiencies of 1pass.

2018-08-06 14:10 UTC, jeohist commented
They are all separate login systems (i.e. they don't share usernames or passwords and the TOTP token is unique for each site).


________________________________
From: mxxcon <notifications@github.com>
Sent: Monday, August 6, 2018 4:09 PM
To: 2factorauth/twofactorauth
Cc: Joey den Broeder; Author
Subject: Re: [2factorauth/twofactorauth] Add Exact Online (#3358)


Are all those sites use the same login system or are they all separate?
If it's all the same then we should not have multiple entries, just a single main one is sufficient.

If you want 1pass' watchtower to display green checkmark or whatever, then you should approach them to implement the concept of related domains. Other password managers have it and it works great. I would not want us to mangle our data to compensate for deficiencies of 1pass.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2F2factorauth%2Ftwofactorauth%2Fpull%2F3358%23issuecomment-410720726&data=02%7C01%7Cjoey.den.broeder%40exact.com%7Cbb2f2f6235b14eff3cfd08d5fba6343e%7C88a15be71abe4beda8d0e3521bcb4cfe%7C0%7C0%7C636691613614693220&sdata=Ql2KCien2OAVFi3eNWksNEFgoPAuHMu7TNxu9K9u4K4%3D&reserved=0>, or mute the thread<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAhTLQm07BG6_wmNKar1mmcCTMmavYif-ks5uOE4OgaJpZM4VwSKs&data=02%7C01%7Cjoey.den.broeder%40exact.com%7Cbb2f2f6235b14eff3cfd08d5fba6343e%7C88a15be71abe4beda8d0e3521bcb4cfe%7C0%7C0%7C636691613614703225&sdata=Iz8KGH8XEO7bpEuG53HoyEK5xeMdpLfyLfS1mlo21rM%3D&reserved=0>.

This e-mail is sent from an external email address. Please do not open attachments or click links from an unknown or suspicious origin. If you have any questions or concerns, please contact the IT Services team.
________________________________

2018-09-02 20:54 UTC, jeohist commented
Is anything required from my side at this point in order to get this merged?

2018-09-03 01:06 UTC, Carlgo11 requested changes
For the `url` tag we list the homepage of the site and not the login page..
For star.exactonline.* the main page seems to be exact.com so please change the urls to that. Furthermore since they all would have the same url after the edit mentioned above I suggest you only use one entry instead of the 7 you added.

For the `doc` tags we require a url that isn't behind a login-page so if there's no other link that's open to the public then remove the tag.

We'll need some sort of confirmation that they indeed support 2FA so please send a screenshot of the login process or documentation page (with personal information blurred out or painted over)

2018-09-03 08:39 UTC, jeohist commented
Thanks for the response @Carlgo11.

start.exactonline.* is the website of the Exact Online application. The only reason exactonline.* redirects to exact.com is a marketing thing. Here's how it looks on the inside: https://i.imgur.com/GKp9MjB.png
Consider it the same situation as GMail :-)

With regards to the documentation pages: Those work fine here without logging on, they are publicly available. I do notice a few of the applications have a broken URL, I'll fix that. 

Login process:
Login page: https://i.imgur.com/fZyaC3k.png
2FA: https://i.imgur.com/DObnyVH.png

2018-09-06 22:03 UTC, Carlgo11 commented
@jeohist what would you say the main page of the company/services are?

2018-09-10 14:49 UTC, jeohist commented
Since #3414 was implemented, I will simplify this PR by only including start.exactonline.nl. The others are not (yet) in the Alexa Top 200k. 

And in the meantime, it'll be a fun pet project to think about #1025 :-)

2018-09-15 15:15 UTC, mxxcon submitted a review, later dismissed

2018-10-12 00:45 UTC, Carlgo11 requested changes

2018-10-12 00:45 UTC, Carlgo11 commented on _data/finance.yml
> +      url: https://start.exactonline.nl
One last thing, for the url we list the main page of a site. That page can't be a login page and so I suppose the url value would be https://www.exact.com/

2018-10-12 07:26 UTC, jeohist commented on _data/finance.yml
> +      url: https://start.exactonline.nl
start.exactonline.* is the website of the Exact Online application. The only reason exactonline.* redirects to exact.com is a marketing thing. Here's how it looks on the inside: https://i.imgur.com/GKp9MjB.png
Consider it the same situation as GMail :-)

2018-10-26 14:33 UTC, Carlgo11 commented on _data/finance.yml
> +      url: https://start.exactonline.nl
Still, we don't list login pages in the `url` field so either make start.exactonline.nl redirect to something else than a login page or change the `url` value to https://www.exact.com/.

2018-10-26 16:01 UTC, jeohist commented
I'm part of the team maintaining the website. Literally any request you send to the Exact Online application is sent to start.exactonline.nl. I don't see what the problem is here, it's not just a login page, it's the entire bloody application.

2018-10-26 16:19 UTC, Carlgo11 commented
@jeohist The `url` tag is designed to list a sites main page. If it's a login page then it's not a main page (or at least not 99.99% of the time.)

If a new user wants to see what a service does then the first thing they'll look at is the main page and not the login page.
If you didn't know anything about Exact Online what would this tell you? My guess is not a lot.
![screenshot](https://user-images.githubusercontent.com/3535780/47579156-814ecd80-d94b-11e8-9fd7-afbb5c0655f6.png)

2018-10-27 19:27 UTC, Carlgo11 requested changes

2018-10-27 19:27 UTC, Carlgo11 commented on _data/finance.yml
> +      url: https://exactonline.nl
![chrome_2018-10-27_21-25-54](https://user-images.githubusercontent.com/3535780/47608499-0959d380-da2f-11e8-9138-92174615cd41.png)
And the site does a 301 to exact.com
```suggestion
      url: https://exact.com/
```

2018-11-19 07:57 UTC, Carlgo11 submitted a review, later dismissed

2018-11-19 09:45 UTC, brycx approved these changes

2018-11-19 09:48 UTC, Carlgo11 approved these changes

2018-11-19 09:49 UTC, merged