Updated Twitch (exception: phone number required)
2factorauth/twofactorauth pull request #3392
Opened 2018-08-22 01:15 UTC by melgu

2018-08-22 01:43 UTC, mxxcon submitted a review, later dismissed

2018-08-22 02:26 UTC, Carlgo11 requested changes

2018-08-22 02:26 UTC, Carlgo11 commented on _data/entertainment.yml
> +          text: "To activate 2-Step Verification, you must provide a mobile phone number."
Please change `2-Step Verification` to `2FA` or `two factor authentication`.
2SV and 2FA are different. See [Contributing.md](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#a-note-on-definitions) for more info

2018-08-22 02:35 UTC, Carlgo11 approved these changes

2018-08-24 14:27 UTC, brycx approved these changes

2018-08-24 14:27 UTC, merged