Mobile layout improvements
2factorauth/twofactorauth pull request #3413
Opened 2018-08-29 05:57 UTC by dsoegijono

- Move mobile supported methods to 2-column rows instead of a paragraph
- Add `checkmark` icon to supported methods, add `ban` icon to unsupported
- Reduce cell padding

<img width="376" alt="screen shot 2018-08-28 at 22 54 00" src="https://user-images.githubusercontent.com/867840/44768273-aa9ed900-ab15-11e8-9707-bc74df54908e.png">

2018-08-29 16:12 UTC, mxxcon reviewed
I have no commend on the underlying code, but visually it's better than before :)

2018-08-29 18:57 UTC, Carlgo11 commented
Screenshot from iPhone X

<img src="https://user-images.githubusercontent.com/3535780/44809015-eac19280-abcd-11e8-9c05-7f959cf1dce8.png" height="600px"></img>

Looks good but I noticed all categories are opened automatically on mobile devices (also happens on the live site). When was that implemented?

2018-08-29 19:00 UTC, Carlgo11 submitted a review, later dismissed

2018-08-29 20:07 UTC, dsoegijono commented
> When was that implemented?

@Carlgo11 I don't think it was intentional. @jamcat22 mentioned it on Slack as something we should fix but I haven't had the chance to look into it.

2018-08-30 04:13 UTC, fpigerre requested changes
This looks really good! :+1:

Do we know if the categories being opened automatically started occurring before these changes were made?

2018-08-30 04:13 UTC, psgs commented on css/base.scss
> +      &.positive {
I would recommend putting all these selectors on one line unless separate declarations are to be inserted at different levels.

2018-08-30 04:13 UTC, psgs commented on css/base.scss
> +        > p {
It seems unnecessary to include the `<` in `< p {`, as there seems to be only one `<p>` tag under the "methods" class.

2018-08-30 05:19 UTC, dsoegijono commented
> Do we know if the categories being opened automatically started occurring before these changes were made?

@psgs Yes, it's happening on the live site too.

2018-08-30 05:20 UTC, dsoegijono commented
<img width="311" alt="screen shot 2018-08-29 at 22 18 30" src="https://user-images.githubusercontent.com/867840/44831043-9f14e600-abd9-11e8-9ba3-c0cc7966a0d9.png">

Btw, just wondering if you guys have any opinions on the text "No two factor auth". I wasn't sure what to put there.

2018-08-30 20:46 UTC, Carlgo11 commented
@dsoegijono how about 2FA? That's used on most exception texts so it would probably fit here as well.

2018-08-30 21:51 UTC, dsoegijono commented
@Carlgo11 Just "No 2FA" or  "2FA not supported"?

2018-08-30 21:53 UTC, jamcat22 commented
I suggest "2FA not supported". Also, any way to find out why icons aren't centered on buttons?

2018-08-30 22:02 UTC, dsoegijono commented
@jamcat22 [this](https://github.com/2factorauth/twofactorauth/pull/3413/files#diff-99125772e23d9230b4d830624fb79adcR232) should have fixed the button centering. There were some left/right margins.

I'll add alt texts. What kind of explainer text do you think we should add to doc button?

2018-08-30 22:21 UTC, jamcat22 commented
@dsoegijono maybe just the word "Docs" like the heading on the desktop table?

I tried measuring using the screenshot you posted. Am I just measuring wrong? Or maybe the button size isn't equal or the icon itself isn't centered? 🤔

![Twitter button, left side measurement of 156](https://user-images.githubusercontent.com/1897053/44882316-07160b80-ac70-11e8-8040-0f93d90a088b.png)
![Twitter button, right side measurement of 165](https://user-images.githubusercontent.com/1897053/44882330-172deb00-ac70-11e8-9a3a-6d8090431a38.png)
![Facebook button, left side measurement of 156](https://user-images.githubusercontent.com/1897053/44882331-1c8b3580-ac70-11e8-9cff-923f7f3fecd0.png)
![Facebook button, right side measurement of 165](https://user-images.githubusercontent.com/1897053/44882337-214fe980-ac70-11e8-9041-8a9b0a9a37a6.png)

2018-08-31 00:08 UTC, fpigerre submitted a review, later dismissed

2018-09-03 01:08 UTC, dsoegijono commented
<img width="349" alt="screen shot 2018-09-03 at 11 07 15" src="https://user-images.githubusercontent.com/867840/44962922-206ec000-aedb-11e8-99ec-cb263556f00f.png">

@jamcat22 Would "Documentation" be too technical? I was thinking something like "How to enable" but that might be too long for smaller screens.

2018-09-03 01:37 UTC, Carlgo11 commented
I like Documentation. Seems to fit just fine.

2018-09-03 01:37 UTC, Carlgo11 submitted a review, later dismissed

2018-09-03 02:15 UTC, jamcat22 commented
@dsoegijono is “Docs” too ambiguous? Should we consider changing the desktop heading?

2018-09-03 04:22 UTC, dsoegijono commented
- Added alt text to links
- Added "Docs" to doc link

2018-09-06 22:05 UTC, Carlgo11 commented
pssst, @jamcat22 ☝️

2018-09-15 01:50 UTC, jamcat22 approved these changes

2018-09-19 22:13 UTC, dsoegijono commented
@Carlgo11 / @psgs want to help re-approve? :)

2018-09-20 19:28 UTC, Carlgo11 commented
I’ll review it in a couple of hours :wink:

2018-09-22 02:06 UTC, Carlgo11 approved these changes

2018-09-22 02:25 UTC, Carlgo11 commented
I'm fine with both "Docs" and "Documentation" however I do think it's easier for non natives to understand 'documentation'. If someone searches for "Define Docs" or similar it shows Google Docs or the .doc format.
But as I said, I'm fine with whatever.

2018-09-22 15:03 UTC, merged

2018-09-22 15:03 UTC, dsoegijono commented
I prefer keeping it as "Docs" for now, as it's consistent with desktop version.

2018-09-22 15:16 UTC, jamcat22 commented
New design is much better. Thanks @dsoegijono! Now we just have to figure out why all the categories open when loading the page.