Update US Bank
2factorauth/twofactorauth pull request #3438
Opened 2018-09-07 02:37 UTC by stevea1

US Bank now offers SMS (issue #3405)

2018-09-07 03:32 UTC, mxxcon requested changes

2018-09-07 03:32 UTC, mxxcon commented on _data/banking.yml
> +      doc: https://github.com/2factorauth/twofactorauth.git
This is not a correct docs url..

2018-09-07 03:41 UTC, stevea1 commented
Fixed...

2018-10-03 09:33 UTC, brycx requested changes
I checked that docs URL, and I see no described steps of how to setup 2FA for an account. Have I missed something @stevea1?

2018-10-08 00:40 UTC, stevea1 commented
@brycx, right you are. I was not able to find any publicly accessible TFA documentation, so I removed the doc link.

2018-10-12 21:19 UTC, bishtawi commented
I am a US Bank customer and I could not find any setting on their website allowing me to enable 2factor. I think the one-time passcode support mentioned [here](https://www.usbank.com/online-security/mobile-security.html) might for their mobile app only? I cannot confirm this as I do not have their app installed.

2018-10-12 21:44 UTC, bishtawi commented
Nevermind, I was able to follow the directs in https://github.com/2factorauth/twofactorauth/pull/3477 and enable SMS 2factor.

2018-10-26 15:30 UTC, mxxcon commented
Looks like this was fixed in #3477

2018-10-26 15:30 UTC, closed without merging