Remove xapo doc
2factorauth/twofactorauth pull request #3444
Opened 2018-09-07 17:19 UTC by stephengroat

2018-09-07 23:34 UTC, jamcat22 requested changes
Use this one instead: https://support.xapo.com/en/my-account/second-factor-authentication-2fa/

2018-09-07 23:35 UTC, stephengroat commented
@jamcat22 go for the change!

2018-09-07 23:54 UTC, jamcat22 approved these changes
👍

2018-09-15 15:05 UTC, mxxcon approved these changes

2018-09-15 15:06 UTC, merged