Update SecureSafe doc
2factorauth/twofactorauth pull request #3445
Opened 2018-09-07 17:20 UTC by stephengroat

2018-09-07 23:36 UTC, jamcat22 requested changes
Use this instead: https://www.securesafe.com/en/faq/general-questions/how-can-i-activate-2-factor-authentication/

2018-09-07 23:36 UTC, stephengroat commented
@jamcat22 go for it!

2018-09-07 23:53 UTC, jamcat22 approved these changes
Sorry @stephengroat! Just marked it so I’d remember when I got back to my computer. 😄

2018-09-10 01:59 UTC, mxxcon approved these changes

2018-09-10 01:59 UTC, merged