Add bHosted.nl
2factorauth/twofactorauth pull request #3448
Opened 2018-09-10 09:18 UTC by Stefanbs23

2018-09-10 09:19 UTC, stef007a commented
Add bHosted.nl

2018-09-14 00:09 UTC, Carlgo11 requested changes

2018-09-14 00:09 UTC, Carlgo11 commented on _data/hosting.yml
> +    - name: bHosted.nl
Hello @Stefanbs23,
inside our YAML files we use alphabetical order when listing sites. Please put ´bHosted` below `ARP Networks`

2018-09-14 23:37 UTC, Carlgo11 requested changes
@Stefanbs23 still not alphabetical.

2018-09-14 23:37 UTC, closed without merging