Add Buddy
2factorauth/twofactorauth pull request #3463
Opened 2018-09-17 12:26 UTC by Kivlov84

2018-09-17 12:41 UTC, Carlgo11 requested changes
Hello @Kivlov84,
there are a few issues with this PR.
1. You can't have twitter and facebook tags when `tfa` is set to `Yes`.
2. You need a 32x32px image in the **same PR** as the one you added the site in.
3. The site also supports SMS authentication so please add `sms: Yes`

2018-09-17 12:47 UTC, Carlgo11 approved these changes

2018-09-17 12:47 UTC, Kivlov84 commented
Hey @Carlgo11,
Please check now.

2018-09-26 08:38 UTC, Kivlov84 commented
Hey @Carlgo11,
Any chance of informing another reviewer so we can proceed?

2018-09-26 17:48 UTC, stephengroat approved these changes

2018-09-26 17:48 UTC, merged