Update banking.yml - "Commonwealth Bank of Australia" does support TFA
2factorauth/twofactorauth pull request #3489
Opened 2018-10-05 01:10 UTC by AusMatt

- name: Commonwealth Bank of Australia
      url: https://www.commbank.com.au/
      img: commbank.png
      tfa: Yes
      sms: Yes
      software: Yes
      phone: No
      hardware: Yes
      doc: https://www.commbank.com.au/support.digital-banking.explain-netcode-token.html

2018-10-06 00:53 UTC, Carlgo11 requested changes

2018-10-06 00:53 UTC, Carlgo11 commented on _data/banking.yml
> +      phone: No
Please remove the `phone: No` part as we don't list any tags with the value "No".

2018-10-06 00:53 UTC, Carlgo11 commented on _data/banking.yml
> +      software: Yes
I don't see any mentions of a software based 2FA solution for the documentation page you provided. Could you help clarify what type of software 2FA they use?

2018-10-06 03:54 UTC, AusMatt commented
They have both and Android and an iOS phone app.
It would be good if multiple doc: tags could be provided

On Sat, 6 Oct 2018 at 10:23, Carlgo11 <notifications@github.com> wrote:

> *@Carlgo11* requested changes on this pull request.
> ------------------------------
>
> In _data/banking.yml
> <https://github.com/2factorauth/twofactorauth/pull/3489#discussion_r223166133>
> :
>
> > @@ -288,9 +288,12 @@ websites:
>      - name: Commonwealth Bank of Australia
>        url: https://www.commbank.com.au/
>        img: commbank.png
> -      tfa: No
> -      twitter: CommBank
> -      facebook: commonwealthbank
> +      tfa: Yes
> +      sms: Yes
> +      software: Yes
> +      phone: No
>
> Please remove the phone: No part as we don't list any tags with the value
> "No".
> ------------------------------
>
> In _data/banking.yml
> <https://github.com/2factorauth/twofactorauth/pull/3489#discussion_r223166182>
> :
>
> > @@ -288,9 +288,12 @@ websites:
>      - name: Commonwealth Bank of Australia
>        url: https://www.commbank.com.au/
>        img: commbank.png
> -      tfa: No
> -      twitter: CommBank
> -      facebook: commonwealthbank
> +      tfa: Yes
> +      sms: Yes
> +      software: Yes
>
> I don't see any mentions of a software based 2FA solution for the
> documentation page you provided. Could you help clarify what type of
> software 2FA they use?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/2factorauth/twofactorauth/pull/3489#pullrequestreview-162238333>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AIQvF9gOWJtpe6trAVT2XRfdkzoN-9OCks5uh_7rgaJpZM4XJY8q>
> .
>

2018-10-06 21:58 UTC, Carlgo11 approved these changes

2018-10-12 05:52 UTC, mxxcon approved these changes

2018-10-12 05:53 UTC, merged