Update Adobe 2FA status
2factorauth/twofactorauth pull request #3490
Opened 2018-10-06 00:48 UTC by Carlgo11

This PR closes #3486.
I also removed the email tag as there's no mention of supporting email authentication any longer (except from password recovery)

2018-10-06 06:19 UTC, jamcat22 requested changes

2018-10-06 06:19 UTC, jamcat22 commented on _data/other.yml
> -      email: Yes
Email is still supported. See [doc link](
https://helpx.adobe.com/x-productkb/global/2-step-verification-account-security.html) and screenshot below:
![Adobe 2FA Sign In Options](https://user-images.githubusercontent.com/1897053/46568141-56013180-c8fd-11e8-96b6-cce57ae07659.png)

2018-10-26 14:27 UTC, mxxcon approved these changes

2018-10-26 14:44 UTC, jamcat22 approved these changes

2018-10-26 14:45 UTC, merged