Add Mercado Bitcoin
2factorauth/twofactorauth pull request #3511
Opened 2018-10-24 14:01 UTC by matheusazzi

2018-10-24 18:12 UTC, Carlgo11 requested changes

2018-10-24 18:12 UTC, Carlgo11 commented on _data/cryptocurrencies.yml
> +      doc: https://suporte.mercadobitcoin.com.br/hc/pt-br/articles/360000385152-O-que-%C3%A9-e-como-ativar-autentica%C3%A7%C3%A3o-em-2-passos-token-
Please change the doc link to this one:
```suggestion
      doc: https://suporte.mercadobitcoin.com.br/hc/pt-br/articles/360000385152
```

2018-10-24 18:41 UTC, Carlgo11 approved these changes

2018-11-13 19:47 UTC, mxxcon approved these changes

2018-11-13 19:48 UTC, merged