Add Bitcoin Trade
2factorauth/twofactorauth pull request #3513
Opened 2018-10-24 14:11 UTC by matheusazzi

2018-11-06 06:06 UTC, Carlgo11 requested changes
Could you provide any documentation link that describes how to enable 2FA on BitcoinTrade? If not, could you provide any screenshots of the setup process alternate the login process? (with personal information blurred out)

2018-11-06 06:06 UTC, Carlgo11 commented on _data/cryptocurrencies.yml
> +    - name: Bitcoin Trade
```suggestion
    - name: BitcoinTrade
```

2018-11-06 06:06 UTC, Carlgo11 commented on _data/cryptocurrencies.yml
> +      url: https://www.bitcointrade.com.br/
```suggestion
      url: https://bitcointrade.com.br/
```

2018-11-06 06:09 UTC, Carlgo11 requested changes
Travis output:
```
<------------ ERROR ------------>
1. _data/cryptocurrencies.yml is not alphabetized by name
```

2018-12-05 16:13 UTC, mxxcon approved these changes

2018-12-05 21:56 UTC, Carlgo11 approved these changes

2018-12-05 21:56 UTC, merged