Update gofundme doc
2factorauth/twofactorauth pull request #3516
Opened 2018-10-24 14:46 UTC by stephengroat

2018-10-24 18:20 UTC, Carlgo11 requested changes

2018-10-24 18:20 UTC, Carlgo11 commented on _data/other.yml
> +      doc: https://support.gofundme.com/hc/en-us/articles/360001980947-Phone-Verification
```suggestion
      doc: https://support.gofundme.com/hc/en-us/articles/360001980947
```

2018-10-24 18:30 UTC, Carlgo11 approved these changes

2018-10-31 18:30 UTC, jdavis approved these changes

2018-10-31 18:30 UTC, merged