Add Linxo
2factorauth/twofactorauth pull request #3519
Opened 2018-10-24 15:17 UTC by notflorian

2018-10-24 18:29 UTC, Carlgo11 requested changes
The logo should be exactly 32x32 pixels.
I suggest you use this one instead:
![linxo](https://user-images.githubusercontent.com/3535780/47452882-8e44b300-d7cb-11e8-9fc5-e99a7b2681fb.png)

2018-10-24 18:29 UTC, Carlgo11 commented on _data/finance.yml
> +      url: https://wwws.linxo.com
Please change the url to:
```suggestion
      url: https://www.linxo.com/
```

2018-10-25 08:32 UTC, notflorian commented
Done, thanks for your comments. :)

2018-10-25 12:14 UTC, Carlgo11 approved these changes

2018-11-01 16:31 UTC, stephengroat approved these changes

2018-11-01 16:31 UTC, merged