Add DEGIRO
2factorauth/twofactorauth pull request #3520
Opened 2018-10-25 14:44 UTC by remco25

2018-10-26 08:16 UTC, Carlgo11 requested changes
We usually only allow one site addition per PR but since this is your first pull request I guess it'll work.

I've made some changes, please merge those.

Also, here are updated versions of the logos, please use those instead:
![anycoin](https://user-images.githubusercontent.com/3535780/47553501-96a20880-d907-11e8-872c-f3cc4e9f3f7b.png)
![degiro](https://user-images.githubusercontent.com/3535780/47553717-0c0dd900-d908-11e8-96c6-4e86264125e0.png)

2018-10-26 08:16 UTC, Carlgo11 commented on _data/cryptocurrencies.yml
> +
```suggestion

```

2018-10-26 08:16 UTC, Carlgo11 commented on _data/cryptocurrencies.yml
> +      doc: https://support.anycoindirect.eu/hc/en-gb/articles/115001423191-How-to-add-delete-2FA-on-my-Anycoin-Direct-account-
```suggestion
      doc: https://support.anycoindirect.eu/hc/en-gb/articles/115001423191
```

2018-10-26 08:16 UTC, Carlgo11 commented on _data/finance.yml
> +
```suggestion

```

2018-10-26 08:16 UTC, Carlgo11 commented on _data/finance.yml
Can you provide some form of documentation on how to enable 2FA on DEGIRO?
If not, could you please attach a screenshot of the login process or 2FA setup process? (With personal information blurred out)

2018-10-26 12:22 UTC, remcoverstappen commented on _data/finance.yml
Unfortunately DEGIRO does not provide documentation for 2FA. I've attached a screenshot of the setup and logon page (pages are only provided in Dutch).

![2018-10-26_14-20-29](https://user-images.githubusercontent.com/44469398/47565982-83ecfb00-d92a-11e8-92a6-383f6f278610.png)
![2018-10-26_14-21-35](https://user-images.githubusercontent.com/44469398/47565983-83ecfb00-d92a-11e8-8f2b-9243641a6bcf.png)

2018-10-26 16:23 UTC, Carlgo11 submitted a review, later dismissed

2018-11-01 16:45 UTC, stephengroat approved these changes

2018-11-01 19:24 UTC, Carlgo11 approved these changes

2018-11-01 19:24 UTC, merged