Add Mimecast
2factorauth/twofactorauth pull request #3523
Opened 2018-10-26 16:24 UTC by cez81

Global Alexa rank 6727
https://www.alexa.com/siteinfo/mimecast.com

Closes #3421

2018-10-26 16:27 UTC, Carlgo11 requested changes

2018-10-26 16:27 UTC, Carlgo11 commented on _data/email.yml
> +      doc: https://community.mimecast.com/docs/DOC-1913
I think this page is better. It describes how two enable 2FA. Something that the other page doesn't do.
```suggestion
      doc: https://community.mimecast.com/docs/DOC-1915
```

2018-10-27 19:24 UTC, Carlgo11 approved these changes

2018-11-01 16:24 UTC, stephengroat approved these changes

2018-11-01 16:24 UTC, merged