Update Dreamhost doc
2factorauth/twofactorauth pull request #3527
Opened 2018-11-01 15:23 UTC by stephengroat

2018-11-01 19:25 UTC, Carlgo11 requested changes

2018-11-01 19:25 UTC, Carlgo11 commented on _data/hosting.yml
> +      doc: https://help.dreamhost.com/hc/en-us/articles/216013897-Multifactor-Authentication-overview
```suggestion
      doc: https://help.dreamhost.com/hc/en-us/articles/216013897
```

2018-11-01 19:31 UTC, Carlgo11 approved these changes

2018-11-03 18:38 UTC, brycx approved these changes

2018-11-03 18:38 UTC, merged