Remove softlayer hosting doc
2factorauth/twofactorauth pull request #3529
Opened 2018-11-01 15:33 UTC by stephengroat

doc hosting no longer exists

2018-11-01 19:37 UTC, Carlgo11 requested changes
Seems like it's been completely moved to IBM Cloud so I'd say we could remove the entire listing.

2018-11-01 19:39 UTC, stephengroat commented
app hasn't been ported yet https://control.softlayer.com/

2018-11-01 19:44 UTC, Carlgo11 commented
![screenshot](https://tempfiles.carlgo11.com/download/D5BDB5769D0E7B/?p=RWr8hQCbIke6Og24StDi)
Seems like Microsoft and Skype. Legacy accounts will be merged and new user have to use IBM accounts.

2018-11-19 14:57 UTC, Carlgo11 approved these changes

2018-11-26 16:20 UTC, brycx approved these changes

2018-11-26 16:20 UTC, merged