Add eset
2factorauth/twofactorauth pull request #3539
Opened 2018-11-05 15:59 UTC by stephengroat

closes #3393

2018-11-05 16:23 UTC, brycx submitted a review, later dismissed

2018-11-06 05:59 UTC, Carlgo11 requested changes

2018-11-06 05:59 UTC, Carlgo11 commented on _data/security.yml
> +      twitter: eset
```suggestion
      twitter: ESET
```

2018-11-06 06:07 UTC, Carlgo11 approved these changes

2018-11-06 10:12 UTC, brycx approved these changes

2018-11-06 10:12 UTC, merged