Update mint.com doc link
2factorauth/twofactorauth pull request #3541
Opened 2018-11-05 23:45 UTC by devnall

The current doc link points to a TurboTax-specific help page which does not give correct 2FA info for mint.com

There are two potentially relevant help pages for mint.com:
https://help.mint.com/Security/908045661/How-do-I-use-Google-Authenticator-to-login-to-Mint
https://help.mint.com/Mint-Account-Management/888963021/How-to-protect-your-Mint-account

I chose the former since it is wholly about 2FA and because it contains instructions for enabling both sms/email 2FA and an authenticator app 2FA, though it isn't explicit about where to stop in the event that you only want sms/email 2FA. I'm amenable to using the other link if it better fits this project's definition requirements but it didn't seem to.

2018-11-06 06:01 UTC, Carlgo11 requested changes

2018-11-06 06:01 UTC, Carlgo11 commented on _data/finance.yml
> +      doc: https://help.mint.com/Security/908045661/How-do-I-use-Google-Authenticator-to-login-to-Mint
```suggestion
      doc: https://help.mint.com/Security/908045661
```

2018-11-06 18:46 UTC, Carlgo11 approved these changes

2018-11-07 07:15 UTC, brycx approved these changes

2018-11-07 07:16 UTC, merged