Added details of ICICI bank
2factorauth/twofactorauth pull request #3575
Opened 2018-12-08 13:35 UTC by onkarshinde

2018-12-09 16:24 UTC, mxxcon requested changes
Please compress the logo so that it's under 2500 bytes in size
Consider using this image 
![icici](https://user-images.githubusercontent.com/847140/49699954-d6663c00-fba5-11e8-94a9-5ffeffacbb68.png)

2018-12-14 05:17 UTC, onkarshinde commented
@mxxcon I have used the icon you have provided.

2018-12-15 06:22 UTC, mxxcon approved these changes

2018-12-16 18:56 UTC, stephengroat approved these changes

2018-12-22 03:36 UTC, merged