Added ShapeShift Cryptocurrency Exchange
2factorauth/twofactorauth pull request #3583
Opened 2018-12-19 23:15 UTC by mperklin

I added an entry in the "CryptoCurrencies" section for ShapeShift digital asset exchange.

Thanks for maintaining this great repo!

--Michael

2018-12-20 14:29 UTC, mxxcon requested changes
Please optimize your image. It must be under 2500 bytes.

2018-12-20 18:51 UTC, stephengroat submitted a review, later dismissed

2018-12-22 01:16 UTC, Carlgo11 requested changes

2018-12-22 01:16 UTC, Carlgo11 commented on _data/cryptocurrencies.yml
> +      doc: https://shapeshift.zendesk.com/hc/en-us/articles/360001374159-I-Am-Having-Trouble-With-2FA
Change the URL to:
```suggestion
      doc: https://shapeshift.zendesk.com/hc/en-us/articles/360001374159
```

2018-12-22 04:34 UTC, Carlgo11 requested changes
Just as @mxxcon mentioned in https://github.com/2factorauth/twofactorauth/pull/3583#pullrequestreview-187020321, the logo needs to be less than 2500Kb. I compressed it down to 939 bytes.
Just replace shapeshift.png with this one:
![shapeshift](https://user-images.githubusercontent.com/3535780/50370672-3c41c300-05ab-11e9-86c0-e5aa3abcfb12.png)

2019-02-04 03:02 UTC, Carlgo11 commented
Closing due to inactivity.

2019-02-04 03:02 UTC, closed without merging