Update gandi doc
2factorauth/twofactorauth pull request #3592
Opened 2018-12-22 04:17 UTC by stephengroat

2018-12-22 04:31 UTC, Carlgo11 requested changes

2018-12-22 04:31 UTC, Carlgo11 commented on _data/domains.yml
> +      doc: https://docs.gandi.net/en/account_management/security/index.html
To make it less likely to break, how about just removing the `index.html` part?
```suggestion
      doc: https://docs.gandi.net/en/account_management/security/
```

2018-12-22 04:35 UTC, Carlgo11 approved these changes

2018-12-23 21:58 UTC, grigouze commented
+1

2018-12-30 07:46 UTC, mxxcon approved these changes

2018-12-30 07:47 UTC, merged