Adding MacStadium
2factorauth/twofactorauth pull request #3598
Opened 2018-12-24 03:10 UTC by Sunit-Kulkarni

Adding the popular MacStadium cloud computing platform.

2018-12-26 15:03 UTC, stephengroat commented
@Sunit-Kulkarni could you cleanup this pr? not sure if you got the right branch pushed

2019-01-09 15:34 UTC, mxxcon requested changes
It seems like you are also updating formatting and changing `education.yml` file.
Let's keep each PR atomic where site additions and format changes are separate PRs which can be reviewed independently..

2019-01-29 18:13 UTC, mxxcon approved these changes

2019-01-29 18:14 UTC, stephengroat approved these changes

2019-01-29 18:14 UTC, merged