Move Tibia to HTTPS
2factorauth/twofactorauth pull request #3609
Opened 2019-01-03 17:42 UTC by stephengroat

2019-01-07 22:49 UTC, Carlgo11 requested changes

2019-01-07 22:49 UTC, Carlgo11 commented on _data/gaming.yml
> +      doc: https://www.tibia.com/support/?subtopic=faq&question=authenticator
How about
```suggestion
      doc: https://www.tibia.com/support/?subtopic=gethelp&topicid=21
```

2019-01-07 22:54 UTC, Carlgo11 approved these changes

2019-01-09 16:39 UTC, mxxcon approved these changes

2019-01-09 16:39 UTC, merged