Add Boursorama
2factorauth/twofactorauth pull request #3615
Opened 2019-01-09 11:23 UTC by Jipem

Boursorama is a French bank and 2FA would be useful.

2019-01-09 17:07 UTC, mxxcon requested changes
Logo must be 32x32 and under 2500 bytes in size.

2019-01-10 19:16 UTC, mxxcon requested changes

2019-01-10 19:16 UTC, mxxcon commented on _data/banking.yml
> +      img: Boursorama.png
capitalization matters.
```suggestion
      img: boursorama.png
```

2019-01-11 16:28 UTC, mxxcon approved these changes

2019-01-12 01:08 UTC, Carlgo11 approved these changes

2019-01-12 01:09 UTC, Carlgo11 commented
Are you sure they don't support 2FA? I haven't see a bank in EU that doesn't support some form of 2FA yet.

2019-01-12 17:49 UTC, Jipem commented
@Carlgo11 : 
> Are you sure they don't support 2FA? I haven't see a bank in EU that doesn't support some form of 2FA yet.

Yes, only login + password : https://clients.boursorama.com/connexion/

2019-01-15 03:17 UTC, merged