Add Wyze to iot.yml
2factorauth/twofactorauth pull request #3617
Opened 2019-01-09 16:00 UTC by mxxcon

2019-01-09 17:21 UTC, stephengroat submitted a review, later dismissed

2019-01-10 20:51 UTC, Carlgo11 requested changes

2019-01-10 20:51 UTC, Carlgo11 commented on _data/iot.yml
> +      twitter: wyzecam
```suggestion
      twitter: WyzeCam
```

2019-01-10 20:51 UTC, Carlgo11 commented on _data/iot.yml
> +      facebook: wyzecam
```suggestion
      facebook: WyzeCam
```

2019-01-11 01:32 UTC, stephengroat approved these changes

2019-01-12 01:04 UTC, Carlgo11 approved these changes

2019-01-12 01:04 UTC, merged