Remove Max facebook
2factorauth/twofactorauth pull request #3629
Opened 2019-01-14 05:52 UTC by stephengroat

currently 404ing

2019-01-27 10:04 UTC, brycx commented
Their Twitter page also seems to be gone.

2019-01-29 20:39 UTC, Carlgo11 commented
I'm still waiting from a response from them.
@brycx their Twitter account is up and they respond somewhat regularly.

2019-01-31 03:19 UTC, Carlgo11 requested changes

2019-01-31 03:19 UTC, Carlgo11 commented on _data/food.yml
> -      facebook: maxhamburgare
Finally got a reply. Try this instead:
`facebook: maxburgers`

2019-01-31 19:21 UTC, Carlgo11 approved these changes

2019-02-04 15:30 UTC, mxxcon approved these changes

2019-02-04 15:30 UTC, merged