groupme: add entry
2factorauth/twofactorauth pull request #3633
Opened 2019-01-15 01:31 UTC by mathstuf

Fixes #3631

2019-01-15 01:33 UTC, mathstuf commented
Amended for `optipng` (4.45% savings).

2019-01-15 02:01 UTC, Carlgo11 requested changes
How about this image? It's 85% compressed.
![groupme](https://user-images.githubusercontent.com/3535780/51153816-dd9dfb00-1871-11e9-9348-8de2f271664a.png)

2019-01-15 02:01 UTC, Carlgo11 commented on _data/communication.yml
> +      doc: https://help.groupme.com/hc/en-us/articles/360000579167-GroupMe-two-step-verification-FAQ
As it's a Zendesk page the article number is sufficient.
```suggestion
      doc: https://help.groupme.com/hc/en-us/articles/360000579167
```

2019-01-16 03:07 UTC, Carlgo11 approved these changes

2019-01-17 16:21 UTC, mxxcon approved these changes

2019-01-17 16:21 UTC, merged