Update Questrade
2factorauth/twofactorauth pull request #3648
Opened 2019-01-19 15:29 UTC by anault

2019-01-21 03:59 UTC, mxxcon requested changes

2019-01-21 03:59 UTC, mxxcon commented on _data/investing.yml
>        twitter: Questrade
This line is not needed with `tfa:yes`
```suggestion
```

2019-01-27 09:58 UTC, brycx submitted a review, later dismissed
Please include a `doc` link that points to a description of how to enable these features. If the docs are only for registered users, could you please include a screenshot of it here, with any personal information blurred out?

2019-01-27 18:52 UTC, anault commented
I cannot find any public reference to it, but it was announced via email to current customers back in October. I have been using it since and it works:

> **Extra security for your account: 2-step verification (2SV)**
 
We’re pleased to let you know you can now set up 2SV for your Questrade account. 2SV is a time-sensitive, auto-generated code that you enter, with your user ID and password, to log in to your account. To set up 2SV, [log in](https://login.questrade.com/Signin.aspx) to your account, go to your **Settings**, and click **2-step verification**.

![questrade_2fa](https://user-images.githubusercontent.com/6646230/51805374-69346600-223a-11e9-9b15-317fde4c40e2.png)

2019-01-28 14:33 UTC, mxxcon approved these changes

2019-01-29 02:12 UTC, Carlgo11 approved these changes

2019-01-29 02:13 UTC, merged