Add BGL Corp
2factorauth/twofactorauth pull request #3678
Opened 2019-01-30 00:54 UTC by ruiyang

2019-01-31 01:31 UTC, Carlgo11 requested changes
Is the 2FA solution only for Simple Fund 360?

2019-01-31 01:31 UTC, Carlgo11 commented on _data/finance.yml
> +      doc: https://sf360.zendesk.com/hc/en-au/articles/360020963051-Multi-Factor-Authentication-MFA-
```suggestion
      doc: https://sf360.zendesk.com/hc/en-au/articles/360020963051
```

2019-02-01 03:27 UTC, ryangcode commented on _data/finance.yml
> +      doc: https://sf360.zendesk.com/hc/en-au/articles/360020963051-Multi-Factor-Authentication-MFA-
Thanks for reviewing it.  The MFA is for all our products, not only for simple fund 360. The login part is handled by the same app and the process is the same for all products.

2019-02-03 22:59 UTC, ruiyang commented
@Carlgo11 Hi, wonder if you could merge the changes. Thanks.

2019-02-04 02:34 UTC, Carlgo11 submitted a review, later dismissed

2019-02-04 04:56 UTC, ruiyang commented
@Carlgo11 Hi, seemed that at least two reviewers are required for it to be merged. Wonder if you know anyone else could help to review this pull request. Thanks.

2019-02-04 20:35 UTC, mxxcon commented
@ruiyang does this 2fa apply only to SimpleFund360 or to CAS360 and BGL Client Centre and other sites too?

2019-02-05 05:10 UTC, ruiyang commented
@mxxcon it is for SimpleFund360, CAS360 and BGL API. not for BGL Client Centre.

2019-02-05 21:38 UTC, mxxcon commented
> @mxxcon it is for SimpleFund360, CAS360 and BGL API. not for BGL Client Centre.

Perhaps it should be mentioned in `exceptions:`?

2019-02-06 14:19 UTC, mxxcon approved these changes

2019-02-06 23:14 UTC, ruiyang commented
@Carlgo11 Hi, I have made all required changes, pls have a look and approve this pull request. Thanks.

2019-02-13 03:56 UTC, ruiyang commented
@Carlgo11 Hi, any feedback?

2019-02-15 00:15 UTC, ruiyang commented
@mxxcon Hi, could you help to ask another repository owner to review and approve this pull request? It needs another pull request approval to be merged. @Carlgo11 seems on leave. Thanks.

2019-02-20 02:59 UTC, ruiyang commented
@jdavis Hi, seems that you are one of the maintainers of this repo. Wonder if you could help to review this pull request and merge it. Thanks.

2019-03-19 23:09 UTC, ruiyang commented
@Carlgo11 Seemed that you are busy with other things and no response after I responded to your review comment after 1 and a half month.

@jdavis I assume you are the main maintainer of this repo. given the current situation, I'll close the pull request and submit a new one if still no response in 7 days. Please let me know if any issues.

2019-04-11 08:58 UTC, kmpoppe approved these changes

2019-04-11 08:58 UTC, merged