Update ID.me
2factorauth/twofactorauth pull request #3680
Opened 2019-01-30 07:37 UTC by kmpoppe

ID.me now supports 2FA as described in #3356.

2019-01-31 01:24 UTC, Carlgo11 requested changes
They also seem to support phone calls.
`phone: Yes`

2019-01-31 01:24 UTC, Carlgo11 commented on _data/identity.yml
> +      doc: https://help.id.me/hc/en-us/sections/115000551794-Securing-My-Account-with-2FA
```suggestion
      doc: https://help.id.me/hc/en-us/sections/115000551794
```

2019-02-01 18:19 UTC, kmpoppe commented
@Carlgo11 Incorporated your requested changes yesterday.

2019-02-04 14:54 UTC, mxxcon approved these changes

2019-02-05 07:22 UTC, Carlgo11 approved these changes

2019-02-05 07:22 UTC, merged