Update USAA exception with Symantec VIP app requirement
2factorauth/twofactorauth pull request #3710
Opened 2019-02-07 18:16 UTC by jakejarvis

USAA annoyingly requires a Symantec app ([Symantec VIP](https://vip.symantec.com/)) to get the software token.

Info here: https://www.usaa.com/inet/pages/security_token_logon_options (CyberCode Token tab)

2019-02-11 00:48 UTC, mxxcon commented
I don't think this should go into `exceptions`...

2019-02-11 20:21 UTC, jakejarvis commented
No worries, I'll close. Should we maybe add something to `CONTRIBUTING.md` [under Exceptions](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#exceptions--restrictions) about noting app requirements (or not noting)? I see a ton of sites listed that note specific app requirements under their exception (notably Authy).

<img width="361" alt="screen shot 2019-02-11 at 3 17 12 pm" src="https://user-images.githubusercontent.com/1703673/52590824-56ac5600-2e10-11e9-93bf-e76585f3ff92.png">
<img width="358" alt="screen shot 2019-02-11 at 3 17 33 pm" src="https://user-images.githubusercontent.com/1703673/52590831-58761980-2e10-11e9-939c-f4acac2830f5.png">
<img width="356" alt="screen shot 2019-02-11 at 3 16 32 pm" src="https://user-images.githubusercontent.com/1703673/52590833-59a74680-2e10-11e9-8ae9-38150ed22fc1.png">
<img width="362" alt="screen shot 2019-02-11 at 3 15 07 pm" src="https://user-images.githubusercontent.com/1703673/52590835-5b710a00-2e10-11e9-94ad-6e1f01655cca.png">

...etc.

2019-04-12 09:59 UTC, jtagcat requested changes
Needs one more space

2019-04-12 09:59 UTC, vc7ee commented on _data/banking.yml
> +       text: "Software authentication requires the Symantec VIP mobile app."
```suggestion
        text: "Software authentication requires the Symantec VIP mobile app."
```

2019-08-20 16:57 UTC, closed without merging