Added NationBuilder to Other list
2factorauth/twofactorauth pull request #3719
Opened 2019-02-09 21:09 UTC by asayler

PR to add https://nationbuilder.com to the Other 2FA list as a site that does not support 2FA.

2019-02-10 19:29 UTC, kmpoppe commented
@asayler The Travis Check In Build failed because the image is larger than 2500 bytes. Please reduce the size :-)

2019-02-11 02:41 UTC, asayler commented
Thanks. I shrink the png. SHould be under the limit now.

2019-04-12 07:45 UTC, jtagcat submitted a review, later dismissed

2019-08-17 02:32 UTC, Carlgo11 requested changes

2019-08-17 02:32 UTC, Carlgo11 commented on _data/other.yml
> +      twitter: nationbuilder
```suggestion
      twitter: NationBuilder
```

2019-08-17 02:59 UTC, Carlgo11 approved these changes

2019-08-20 19:12 UTC, kmpoppe approved these changes

2019-08-20 19:12 UTC, merged