Uphold requires Authy
2factorauth/twofactorauth pull request #3724
Opened 2019-02-10 18:55 UTC by sebflipper

2019-02-21 07:13 UTC, Carlgo11 requested changes

2019-02-21 07:13 UTC, Carlgo11 commented on _data/cryptocurrencies.yml
> +      doc: https://support.uphold.com/hc/en-us/articles/210689043-How-to-set-up-Authy-Two-Factor-Authentication-for-Uphold
```suggestion
      doc: https://support.uphold.com/hc/en-us/articles/210689043
```

2019-02-22 20:46 UTC, Carlgo11 commented
According to [this page](https://support.uphold.com/hc/en-us/articles/360024042131-How-do-I-set-up-Two-Factor-Authentication-using-the-Uphold-mobile-app-) the site supports all TOTP apps using RFC-6238

2019-02-22 22:44 UTC, jamcat22 requested changes
Looks like Uphold just changed their 2FA to standard TOTP only, dropping support for Authy. They also changed their help center article ID, so I suggest changing the doc link and removing SMS, phone, and the exception text.

2019-02-22 22:44 UTC, jamcat22 commented on _data/cryptocurrencies.yml
> +      doc: https://support.uphold.com/hc/en-us/articles/210689043
```suggestion
      doc: https://support.uphold.com/hc/en-us/articles/360024042471
```

2019-02-22 22:44 UTC, jamcat22 commented on _data/cryptocurrencies.yml
> +      exceptions:
```suggestion
```

2019-02-22 22:44 UTC, jamcat22 commented on _data/cryptocurrencies.yml
> +          text: "Software authentication requires the Authy app."
```suggestion

```

2019-02-22 22:44 UTC, jamcat22 commented on _data/cryptocurrencies.yml
>        sms: Yes
```suggestion
```

2019-02-22 22:44 UTC, jamcat22 commented on _data/cryptocurrencies.yml
>        phone: Yes
```suggestion
```

2019-02-24 17:59 UTC, jamcat22 approved these changes

2019-02-25 03:28 UTC, Carlgo11 approved these changes

2019-02-25 03:28 UTC, merged