Update leage of legends
2factorauth/twofactorauth pull request #3749
Opened 2019-03-06 18:29 UTC by mmuffins

2FA support for leage of legends was added today by riot.

2019-03-12 20:21 UTC, Carlgo11 requested changes

2019-03-12 20:21 UTC, Carlgo11 commented on _data/gaming.yml
> +      doc: https://support.riotgames.com/hc/en-us/articles/360010366413-2FA-and-Trusted-Devices
```suggestion
      doc: https://support.riotgames.com/hc/en-us/articles/360010367273
```

2019-04-10 19:36 UTC, kmpoppe approved these changes

2019-04-10 22:39 UTC, Carlgo11 approved these changes

2019-04-10 22:39 UTC, merged