Add Zomato To The Food List.
2factorauth/twofactorauth pull request #3752
Opened 2019-03-12 00:40 UTC by saviokay

Zomato, a popular Indian restaurant search and discovery web service. In 2017, the credentials of millions of its users were hacked and was known as one of the largest data leaks in Indian history. Even after this event, the service hasn't implemented any concert measures to avoid that incident from occurring again. The service is known to be used by the bulk of the population daily.  I have included Zomato to the Food list to help push the service to understand about a safe internet and of dependable practices.

(`https://economictimes.indiatimes.com/small-biz/security-tech/security/zomato-hacked-security-breach-results-in-17-million-user-data-stolen/articleshow/58729251.cms`)

2019-03-12 20:18 UTC, Carlgo11 requested changes
Thanks for the pull request @saviokay,
the image needs to be 32x32 pixels. 
Try this one:
![zomato](https://user-images.githubusercontent.com/3535780/54233010-4a4d1300-450c-11e9-8fe4-23a3d0b40cb4.png)

2019-03-12 23:58 UTC, saviokay commented
@Carlgo11 Sure Thing!. Thanks for the comment.
I'll make the required changes.

2019-03-13 01:30 UTC, Carlgo11 requested changes

2019-03-13 01:30 UTC, Carlgo11 commented on _data/food.yml
> +      twitter: zomato
Just noticed that they spell their twitter handle with a capital Z.
```suggestion
      twitter: Zomato
```

2019-03-15 03:29 UTC, saviokay commented
I have made all the required changes including the suggestions. Kindly review the pull request.

2019-03-19 05:29 UTC, Carlgo11 commented
@saviokay you did but you also reverted those changes in 9876ed1

2019-03-31 18:21 UTC, saviokay commented
Apologies @Carlgo11 . I have made the corrections.

2019-03-31 21:11 UTC, Carlgo11 approved these changes

2019-04-04 15:57 UTC, saviokay commented
If everything seems okay. Can we approve this pull request and merge it?
Thank you.

2019-04-10 19:27 UTC, kmpoppe approved these changes

2019-04-10 19:27 UTC, merged