Update 2FA info + icon of Infomaniak (hosting)
2factorauth/twofactorauth pull request #3764
Opened 2019-03-22 10:27 UTC by sam-infomaniak

2019-03-22 15:40 UTC, RichJeanes submitted a review, later dismissed

2019-03-25 09:34 UTC, Carlgo11 requested changes
The image size is just below our limit and there's no real reason for it to be that large.
Try this one instead:
![infomaniak-1](https://user-images.githubusercontent.com/3535780/54908956-5a3ffc00-4ee9-11e9-8253-a5f6cfe2f090.png)

2019-04-14 17:20 UTC, kmpoppe commented
@sam-infomaniak PTAL

2019-07-18 20:20 UTC, kmpoppe approved these changes

2019-07-18 20:21 UTC, kmpoppe commented
@Carlgo11 @RichJeanes PTAL, I have changed the logo to the one sent by Carl as the OP did not react to the change request.

2019-07-19 01:07 UTC, Carlgo11 approved these changes

2019-07-19 01:07 UTC, merged