Miami University
2factorauth/twofactorauth pull request #3766
Opened 2019-03-23 04:03 UTC by Nap14hockey

Added Miami University

2019-03-25 09:29 UTC, Carlgo11 requested changes
We don't use `otp` and `u2f` tags. Instead change them to  `software` and `hardware`. (See [CONTRIBUTING.md#adding-a-site-that-supports-tfa](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#adding-a-site-that-supports-tfa) for all available tags)

The logo you uploaded is the largest size I've ever seen for a 32x32 pixel image 😄 
I compressed it from 16KB to 540Bytes. I suggest you use this one instead:
![miamioh](https://user-images.githubusercontent.com/3535780/54908619-9cb50900-4ee8-11e9-9030-9e9cca44e888.png)

2019-03-25 22:45 UTC, Nap14hockey commented
So Sorry!  I thought I saw those two tags somewhere, must have been something weird.

Anyways, updated with new image and fixed doc.

Thanks!

2019-03-27 01:07 UTC, Carlgo11 approved these changes

2019-03-27 15:18 UTC, ghost approved these changes

2019-04-10 19:32 UTC, kmpoppe approved these changes

2019-04-10 19:32 UTC, merged