Add Mountain America Credit Union
2factorauth/twofactorauth pull request #3771
Opened 2019-03-29 03:24 UTC by parkerbxyz

2019-04-12 07:05 UTC, jtagcat reviewed
The doc doesn't actually give any information other than proof, that it exists.

2019-04-12 07:05 UTC, RasmusKallas commented on _data/banking.yml
> +      doc: https://www.macu.com/home/services/online-banking/new-online-branch
```suggestion

```

2019-04-13 05:17 UTC, kmpoppe requested changes

2019-04-13 05:17 UTC, kmpoppe commented on _data/banking.yml
> -      doc: https://www.macu.com/home/services/online-banking/new-online-branch
The documentation you provided says "Receive MFA PINs through text, email or automated phone call."

2019-04-13 05:17 UTC, kmpoppe commented on _data/banking.yml
> -      doc: https://www.macu.com/home/services/online-banking/new-online-branch
```suggestion
      phone: yes
```

2019-04-18 05:44 UTC, kmpoppe approved these changes

2019-04-22 15:48 UTC, Carlgo11 approved these changes

2019-04-22 15:49 UTC, merged