Add niconico
2factorauth/twofactorauth pull request #3774
Opened 2019-03-31 08:51 UTC by sckemu

[Niconico](https://www.nicovideo.jp/) is a popular video site in Japan ([Alexa Rank 107](https://www.alexa.com/siteinfo/nicovideo.jp)).
However, I could not find an English TFA setup steps.
Japanese: https://qa.nicovideo.jp/faq/show/4500

2019-03-31 21:17 UTC, Carlgo11 requested changes
I compressed the logo 60%:
![niconico](https://user-images.githubusercontent.com/3535780/55295243-0cf0ec80-540b-11e9-826e-bb14f020b15c.png)
Other than that the PR looks good 👍

2019-03-31 21:21 UTC, Carlgo11 commented
On a side note, is it just me or does Japanese sites seem to prefer low quality fonts?
They look like Arial in a really lossy compression of JPEG. 🤔

2019-04-01 05:59 UTC, sckemu commented
It may be because I'm looking at a browser with Japanese settings, but I can see this page without any problems.

2019-04-02 23:07 UTC, Carlgo11 submitted a review, later dismissed

2019-04-11 07:06 UTC, kmpoppe commented on _data/entertainment.yml
> +
`     lang: jp`

2019-04-11 07:07 UTC, kmpoppe commented on _data/entertainment.yml
> +
I think the language could be included.

2019-04-11 07:07 UTC, kmpoppe commented on _data/entertainment.yml
> +
```suggestion
lang: jp
```

2019-04-11 08:12 UTC, sckemu commented on _data/entertainment.yml
> +
"ja" instead of "jp" is correct.

2019-04-11 08:35 UTC, kmpoppe approved these changes

2019-04-11 22:06 UTC, Carlgo11 approved these changes

2019-04-11 22:06 UTC, merged