Added Wix
2factorauth/twofactorauth pull request #3776
Opened 2019-04-01 11:19 UTC by barakplasma

Wix.com is a website hosting platform, which allows users to collect payments from their customers.

2019-04-02 23:06 UTC, Carlgo11 requested changes
I suggest you use this logo instead:
![Wix](https://user-images.githubusercontent.com/3535780/55441894-a572a280-55ac-11e9-8319-e6d0c88bae43.png)

2019-04-02 23:06 UTC, Carlgo11 commented on _data/hosting.yml
> +      twitter: wixhelp
```suggestion
      twitter: WixHelp
```

2019-04-07 07:31 UTC, barakplasma commented
@Carlgo11 I made the changes your requested

Wix has a two factor authentication feature request webpage ( https://support.wix.com/en/article/request-two-factor-authentication-for-wix-accounts ) where user's can vote for 2FA, but I didn't see a place to put this into yaml file.

2019-04-07 08:15 UTC, Carlgo11 approved these changes

2019-04-11 22:29 UTC, Carlgo11 requested changes

2019-04-11 22:29 UTC, Carlgo11 commented on _data/hosting.yml
> +
Looks like there's a new line at the bottom that shouldn't be there.
```suggestion
```

2019-04-12 09:06 UTC, kmpoppe approved these changes

2019-04-12 22:33 UTC, Carlgo11 approved these changes

2019-04-12 22:33 UTC, merged