Add COBINHOOD
2factorauth/twofactorauth pull request #3777
Opened 2019-04-03 11:33 UTC by xnum

Alexa rank: 136,423

2019-04-04 02:18 UTC, Carlgo11 requested changes

2019-04-04 02:18 UTC, Carlgo11 commented on _data/cryptocurrencies.yml
> +      doc: https://cobinhood.zendesk.com/hc/en-us/articles/115003476871-Setting-up-two-factor-authentication-2FA-
When linking to Zendesk links, only the numbers of the article ID are needed.
```suggestion
      doc: https://cobinhood.zendesk.com/hc/en-us/articles/115003476871
```

2019-04-04 09:28 UTC, Carlgo11 approved these changes

2019-04-10 18:58 UTC, kmpoppe approved these changes

2019-04-10 18:59 UTC, merged