Added wirex
2factorauth/twofactorauth pull request #3789
Opened 2019-04-07 13:59 UTC by kmpoppe

Global alexa rank: 37,054

2019-04-10 22:43 UTC, Carlgo11 requested changes

2019-04-10 22:43 UTC, Carlgo11 commented on _data/cryptocurrencies.yml
> +    - name: wirex
```suggestion
    - name: Wirex
```

2019-04-11 21:59 UTC, Carlgo11 submitted a review, later dismissed

2019-04-12 06:44 UTC, jtagcat submitted a review, later dismissed

2019-05-24 06:11 UTC, dsoegijono commented on _data/cryptocurrencies.yml
> +      doc: https://wirexapp.com/help/article/how-to-enable-enhanced-security-2fa-for-my-wirex-account-0021
Do we want to use short URLs for doc? https://wirexapp.com/hc/articles/207160259

2019-05-24 06:32 UTC, kmpoppe commented on _data/cryptocurrencies.yml
> +      doc: https://wirexapp.com/help/article/how-to-enable-enhanced-security-2fa-for-my-wirex-account-0021
```suggestion
      doc: https://wirexapp.com/hc/articles/207160259
```

2019-05-24 06:32 UTC, kmpoppe commented on _data/cryptocurrencies.yml
> +      doc: https://wirexapp.com/help/article/how-to-enable-enhanced-security-2fa-for-my-wirex-account-0021
@dsoegijono yes, we want short urls ;-)

2019-07-22 22:53 UTC, Carlgo11 approved these changes

2019-07-22 22:53 UTC, merged