Wolt
2factorauth/twofactorauth pull request #3797
Opened 2019-04-10 16:56 UTC by RasmusKallas

2019-04-11 10:59 UTC, RasmusKallas commented
Fixed conflict.

2019-04-11 21:57 UTC, Carlgo11 requested changes
1.5Kb logo version:
![wolt](https://user-images.githubusercontent.com/3535780/55995726-8adbb000-5cb5-11e9-9a0f-7405116764f8.png)

2019-04-11 21:57 UTC, Carlgo11 commented on _data/food.yml
> +      facebook: zomato
All files should end with a blank line.
I recommend you to use a decent text editor like Atom, Notepad++, VS Code, Sublime etc. They fix that for you.
```suggestion
      facebook: zomato

```

2019-04-11 21:57 UTC, Carlgo11 commented on _data/food.yml
> +      email_address: info@wolt.com
info@ seems to be a general inquiry address, support@ would probably fit better.  _(source: [wolt.com/help#contact-support](https://wolt.com/help#contact-support))_ 
```suggestion
      email_address: support@wolt.com
```

2019-04-11 22:30 UTC, RasmusKallas commented
Changes made.

2019-04-11 22:33 UTC, Carlgo11 commented
@RasmusKallas you forgot the logo change 😉 
Also, when do you sleep? 👀 
Should be around 01:30am in Estonia now.

2019-04-11 22:36 UTC, Carlgo11 approved these changes

2019-04-11 22:37 UTC, RasmusKallas commented
I don't :)
Usually 2 hours a day and whenever I get near a bed the next day (same day), then 14 hours and repeat..
I just collapse on the weekends ;) Very healthy.....

2019-04-11 22:39 UTC, Carlgo11 commented
I guess that's one way to manage sleep. To simply not do it. ¯\_(ツ)_/¯

2019-04-11 22:43 UTC, RasmusKallas commented
It's not my fault I need to be sleeping elsewhere by 8:15, When I get to sleep normal for 3-5 days, I usually wake 10-11, I'd recommend 11am for a start.. Also I don't like git really.. It seems overly complicated, while managing multiple repositories and branches at once, tough I can say it from only github's point, git's setup has scared me away, even tough I do well with CLI..

2019-04-11 22:46 UTC, RasmusKallas commented
Waait, Sweedeen, isn't it :46? @Carlgo11

2019-04-11 22:57 UTC, Carlgo11 commented
![](https://media.giphy.com/media/fDO2Nk0ImzvvW/giphy.gif)

2019-04-12 04:20 UTC, kmpoppe approved these changes

2019-04-12 04:21 UTC, merged