Anydesk
2factorauth/twofactorauth pull request #3799
Opened 2019-04-10 17:24 UTC by RasmusKallas

2019-04-18 18:01 UTC, kmpoppe submitted a review, later dismissed

2019-04-22 15:45 UTC, Carlgo11 requested changes

2019-04-22 15:45 UTC, Carlgo11 commented on _data/remote.yml
> +      facebook: anydesk
```suggestion
      facebook: AnyDesk
```

2019-04-22 15:50 UTC, Carlgo11 approved these changes

2019-04-23 04:06 UTC, kmpoppe approved these changes

2019-04-23 04:06 UTC, merged