Njalla
2factorauth/twofactorauth pull request #3802
Opened 2019-04-10 17:44 UTC by RasmusKallas

2019-04-10 22:49 UTC, Carlgo11 requested changes
Social media handles and email address isn't needed if the site supports 2FA. See [CONTRIBUTING.MD](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#new-sites) for the different tags and when to use them.

2019-04-10 22:49 UTC, Carlgo11 commented on _data/domains.yml
> +      img: networksolutions.png
```suggestion
```

2019-04-10 22:49 UTC, Carlgo11 commented on _data/domains.yml
> +      tfa: No
```suggestion
```

2019-04-10 22:49 UTC, Carlgo11 commented on _data/domains.yml
> +      url: https://www.networksolutions.com/
```suggestion
      url: https://njal.la/
```

2019-04-10 22:49 UTC, Carlgo11 commented on _data/domains.yml
> +      twitter: njal_la
```suggestion
```

2019-04-10 22:49 UTC, Carlgo11 commented on _data/domains.yml
> +
```suggestion
```

2019-04-10 22:49 UTC, Carlgo11 commented on _data/domains.yml
> +      email_address: support@njal.la
```suggestion
```

2019-04-10 23:14 UTC, Carlgo11 approved these changes

2019-04-10 23:20 UTC, Carlgo11 commented
Oh I just noticed the site is ranked above 200k on [alexa](https://www.alexa.com/siteinfo/njal.la) 😞 
We've set a rule on only allowing new sites that are ranked below 200k on Alexa as a way to keep our lists more manageable. Sadly that means we can't approve this pull request.
If the site reaches a rank below 200k, feel free to request to have this PR reopened.

Again, sorry for the inconvenience!

2019-04-10 23:20 UTC, closed without merging

2019-04-11 04:46 UTC, RasmusKallas commented
Sorry, I tought Njall.la is a good addition and didn't check.