Riot.im
2factorauth/twofactorauth pull request #3804
Opened 2019-04-10 17:56 UTC by RasmusKallas

2019-04-10 23:33 UTC, Carlgo11 commented
GitHub should really have a scratchpad.
I'll just leave this here temporarily so that I know what parts of the PR that I've already reviewed.

```
Note to maintainers and myself:

Alexa ranking and category is ok
Name: "Riot"
Doc link might not be allowed if tfa = no. I'll have to check that tomorrow.
Facebook: RiotChat
Double blank lines at end.
```

2019-04-12 02:43 UTC, Carlgo11 requested changes
I suggest you also add their facebook handle "RiotChat".
`facebook: RiotChat`

2019-04-12 02:43 UTC, Carlgo11 commented on _data/communication.yml
> +      doc: https://github.com/vector-im/riot-web/issues/2772
So I ran the PR locally and `doc` links are ignored when tfa is set to No.
![](https://tempfiles.carlgo11.com/download/D5CAFFA58D3FD7/?p=6oCrxfN7v)

Therefore, please remove the doc link:
```suggestion
```

2019-04-12 02:43 UTC, Carlgo11 commented on _data/communication.yml
> +
Double blank lines.
```suggestion
```

2019-04-12 02:43 UTC, Carlgo11 commented on _data/communication.yml
> +    - name: Riot.im
On their website they use "Riot" as their name.
```suggestion
    - name: Riot
```

2019-04-18 17:56 UTC, kmpoppe commented
@vc7ee I might have overlooked, but did you add the `facebook`-tag as @Carlgo11 suggested?

2019-04-18 18:45 UTC, kmpoppe submitted a review, later dismissed
Was sceptical about `status` with a non-Twitter-URL (because never seen before) but it compiles and works just fine. Thanks again for your contribution @vc7ee!

2019-04-22 03:30 UTC, Carlgo11 commented
The status tag is supposed to be set when a company is actively working on implementing 2FA. That way the Twitter message changes from "Please support two factor authentication" to "Thank you for working on two factor authentication".

From what I read on https://github.com/vector-im/riot-web/issues/2772 it doesn't sound like they're actively working on it.

2019-04-22 10:59 UTC, vc7ee commented
How do you 'request review from *'?

2019-04-22 14:21 UTC, Carlgo11 commented
That’s a Maintainer only feature.

2019-04-27 22:59 UTC, Carlgo11 approved these changes

2019-04-28 02:18 UTC, kmpoppe approved these changes

2019-04-28 02:18 UTC, merged