Namecheap now supports hardware 2FA
2factorauth/twofactorauth pull request #3807
Opened 2019-04-13 08:28 UTC by golf1052

See https://www.namecheap.com/support/knowledgebase/article.aspx/10102/45/how-can-i-use-the-u2f-method-for-twofactor-authentication

2019-04-13 09:05 UTC, kmpoppe requested changes
Hi @golf1052 ,
Going through the documentation, it looks like the `phone`-option (an automated phone call to give you the two factor code) does not exist (anymore). Would you please remove that option from the file while you're at it?

2019-04-13 09:19 UTC, kmpoppe approved these changes
Thanks!

2019-04-16 10:12 UTC, jtagcat approved these changes

2019-04-16 15:21 UTC, RichJeanes approved these changes

2019-04-16 15:33 UTC, merged