Add Seznam.cz
2factorauth/twofactorauth pull request #3808
Opened 2019-04-14 07:05 UTC by radeksimko

Replaces #2694

2019-04-14 10:20 UTC, kmpoppe requested changes
Hello Radek!

Thank you for your contribution to this project! Could you please use tinypng.com to reduce the size of the logo? Even though it's only 2.19kb, tinyjpg reduces the size by 60%.

Thank you!

Kai

2019-04-14 11:46 UTC, radeksimko commented
Of course, I am happy to.

Related question - would you like me to add this tip to the [contributing guidelines](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#guidelines) (next to OptiPNG)?

2019-04-14 11:49 UTC, radeksimko commented
@kmpoppe PTAL.

2019-04-14 12:03 UTC, kmpoppe commented
@radeksimko Will do later, thanks!

2019-04-14 15:51 UTC, kmpoppe requested changes

2019-04-14 15:51 UTC, kmpoppe commented on _data/email.yml
> +
Please add `lang`-field.

2019-04-14 15:51 UTC, kmpoppe commented on _data/email.yml
> +
```suggestion
      lang: cz
      
```

2019-04-16 10:13 UTC, jtagcat approved these changes

2019-04-22 15:59 UTC, Carlgo11 approved these changes

2019-04-23 04:04 UTC, kmpoppe approved these changes

2019-04-23 04:05 UTC, merged