Add Fio.cz (bank)
2factorauth/twofactorauth pull request #3809
Opened 2019-04-14 08:06 UTC by radeksimko

2019-04-14 15:53 UTC, kmpoppe submitted a review, later dismissed

2019-04-14 15:53 UTC, kmpoppe commented on _data/banking.yml
> +
Please add `lang`-field.

2019-04-14 15:53 UTC, kmpoppe commented on _data/banking.yml
> +
```suggestion
      lang: cz
      
```

2019-04-16 10:11 UTC, vc7ee commented
I suggest you to reduce the png size with this image.
![fio-cz](https://user-images.githubusercontent.com/38327267/56201221-f4e6b300-602f-11e9-890a-c247ffd2ef11.png)

2019-04-22 15:43 UTC, Carlgo11 requested changes
Change the image to the one provided in https://github.com/2factorauth/twofactorauth/pull/3809#issuecomment-483598082

2019-04-22 16:33 UTC, radeksimko commented
@Carlgo11 @kmpoppe PTAL, I implemented both suggestions.

2019-04-23 18:29 UTC, kmpoppe submitted a review, later dismissed

2019-04-29 19:09 UTC, Carlgo11 requested changes

2019-04-29 19:09 UTC, Carlgo11 commented on _data/banking.yml
> +    - name: Fio.cz
On both Twitter and Facebook they refer to themselves as "Fio banka" so I suggest you change the name tag to reflect that.
```suggestion
    - name: Fio banka
```

2019-04-29 19:11 UTC, Carlgo11 approved these changes

2019-04-29 20:02 UTC, kmpoppe approved these changes

2019-04-29 20:02 UTC, merged