Update Moniker to include Software and Email
2factorauth/twofactorauth pull request #3822
Opened 2019-04-20 19:20 UTC by kmpoppe

Close #3821.

2019-04-22 15:22 UTC, Carlgo11 approved these changes

2019-04-24 14:04 UTC, Carlgo11 requested changes

2019-04-24 14:04 UTC, Carlgo11 commented on _data/domains.yml
> +      email: Yes
Looks like they only support 2FA through software 2FA. Email seems to only be authorization.
```suggestion
```

2019-04-25 12:26 UTC, Carlgo11 submitted a review, later dismissed

2019-05-11 06:24 UTC, jamcat22 submitted a review, later dismissed
Based on the doc and the screenshots in #3821, it looks like the "Authentication via e-mail prior to login" option does indeed trigger with each login, making it qualify for an `email: Yes` tag. @Carlgo11 any reason to think it's only authorization?

2019-06-07 23:19 UTC, Carlgo11 commented
I reviewed it so long ago but you're right @jamcat22, it does seem like it would trigger on each auth request. 
@kmpoppe could you revert that commit? Sorry 😅

2019-06-09 14:29 UTC, kmpoppe commented
@Carlgo11, could you just commit to my branch, please? I don't quite read what you want it to show 😅

2019-06-09 17:51 UTC, Carlgo11 approved these changes

2019-07-22 22:52 UTC, merged