Add AdGuard
2factorauth/twofactorauth pull request #3825
Opened 2019-04-22 21:27 UTC by Rakleed

2019-04-27 11:29 UTC, kmpoppe requested changes
I downloaded their favicon, resized and compressed it. Would you please use this in your PR?
![adguard](https://user-images.githubusercontent.com/24451207/56849081-6b1ccc80-68f0-11e9-9435-bb2b94e61ea8.png)

2019-05-24 10:07 UTC, Rakleed commented
@kmpoppe I did the right thing?

2019-05-24 10:40 UTC, kmpoppe approved these changes

2019-05-24 10:41 UTC, kmpoppe commented
@Rakleed Yep, thanks. Another reviewer is required before we can merge your pull request.
Thanks for your contribution!

2019-05-25 08:58 UTC, Carlgo11 approved these changes

2019-05-25 08:58 UTC, merged