Add Weclapp CRM
2factorauth/twofactorauth pull request #3834
Opened 2019-04-30 05:37 UTC by alexplusde

A German CRM/ERP-System.

2019-04-30 05:41 UTC, alexplusde commented
not sure about the URL - weclapp provides subdomains for every client, like iamaclientof.weclapp.com

2019-04-30 07:02 UTC, kmpoppe commented on _data/other.yml
> +      url: https://*.weclapp.com/
To make the PR pass travis, please remove the *.
```suggestion
      url: https://weclapp.com/
```

2019-05-01 07:32 UTC, kmpoppe submitted a review, later dismissed
Alexa-Rank 138,464.
@alexplusde I took myself the liberty to tweak your PR (image and removing superfluous tags).
Thank you for your contribution!

2019-05-03 16:41 UTC, Carlgo11 requested changes

2019-05-03 16:41 UTC, Carlgo11 commented on _data/other.yml
> +      doc: https://www.weclapp.com/de/blog/2-faktor-authentifizierung/
The blog post describes U2F implementation which we categorize as hardware 2FA.
```suggestion
      hardware: Yes
      doc: https://www.weclapp.com/de/blog/2-faktor-authentifizierung/
```

2019-05-03 17:07 UTC, alexplusde commented
@kmpoppe Thank you so much!

I somehow clicked the wrong button and dismissed the change at first. It should be ok now, shouldn't it?

2019-05-04 11:13 UTC, kmpoppe commented on _data/other.yml
> +      hardware: Yes
```suggestion
```
I now see hardware twice, that should not be the case, I think.

2019-05-06 07:22 UTC, ertanoe commented
@kmpoppe Could you please adjust the doc link to be this one here: https://doc.weclapp.com/knowledgebase/zwei-wege-authentifizierung-2fa/
We from weclapp did review this as well and the rest seems to be fine

2019-05-06 09:27 UTC, kmpoppe commented on _data/other.yml
> +      doc: https://www.weclapp.com/de/blog/2-faktor-authentifizierung/
```suggestion
      doc: https://doc.weclapp.com/knowledgebase/zwei-wege-authentifizierung-2fa/
```

Change to documentation link as per @ertanoe 's request.

2019-05-11 05:28 UTC, kmpoppe approved these changes

2019-06-07 23:21 UTC, Carlgo11 approved these changes

2019-06-07 23:21 UTC, merged

2019-06-07 23:22 UTC, Carlgo11 commented
Sorry for the delay. Your commits have been merged now @alexplusde