Update the bank ZKB
2factorauth/twofactorauth pull request #3849
Opened 2019-05-13 21:03 UTC by olikami

* Remove the phone, sms & email options
* Removed whitespace in the image line

This implements and closes #3848

2019-05-25 11:29 UTC, kmpoppe submitted a review, later dismissed

2019-06-06 17:43 UTC, Carlgo11 requested changes
Please add an exception text. Something like 'Software & Hardware authentication requires the ZKB app or PhotoTAN device.' (Or whatever the app and device is called. I only studied German for two weeks in elementary :wink:)

2019-06-06 18:13 UTC, Carlgo11 approved these changes

2019-06-09 10:34 UTC, kmpoppe approved these changes

2019-06-09 10:34 UTC, merged