Add nexusmods.com
2factorauth/twofactorauth pull request #3873
Opened 2019-06-07 22:24 UTC by DandelionSprout

Apparently nexusmods.com supports 2FA by E-mail, as per https://help.nexusmods.com/article/74-two-factor-authentication-for-nexus-mods.

The site is ranked at a pretty impressive 494th on Alexa. The site deals with data (Criteria 2) in the form of uploaded mods, as well as personal image (Criteria 1) if the mod uploader has a large reputation. It also has a detailed documentation of its 2FA support.

2019-06-08 13:47 UTC, Carlgo11 submitted a review, later dismissed

2019-06-08 13:47 UTC, Carlgo11 commented on _data/gaming.yml
> +      doc: https://help.nexusmods.com/article/74-two-factor-authentication-for-nexus-mods
```suggestion
      doc: https://help.nexusmods.com/article/74--
```

2019-06-09 10:15 UTC, kmpoppe requested changes
Looking at the logo I would suspect it could be shrunk a bit. Would you try running it through tinypng.com or any other service?

2019-06-09 15:24 UTC, DandelionSprout commented
I have been using an OptiPNG plugin for Paint.NET, and I can't seem to get it below 1.6KB without heavily affecting the image quality (or 1.4KB in any way at all).

2019-06-09 15:28 UTC, DandelionSprout commented
That being said, it appears that you (kmpoppe) were correct about the efficiency of TinyPNG after all.

2019-06-09 16:52 UTC, kmpoppe commented
I have my bright moments, @dandelionsprout :-)
Thanks for checking tinypng again.

2019-06-09 16:52 UTC, kmpoppe approved these changes

2019-06-09 18:15 UTC, Carlgo11 approved these changes

2019-06-09 18:15 UTC, merged