Update Vultr
2factorauth/twofactorauth pull request #3882
Opened 2019-06-12 12:58 UTC by seonwoolee

Vultr's docs say they support Yubikey, but if you go to add a Yubkey, it states they're only supported in OTP mode, not U2F mode. Unfortunately their docs do not clarify this point.

2019-07-06 00:15 UTC, Carlgo11 requested changes
I suggest this exception message instead. It's more in line with our other 'proprietary 2FA'-exceptions.

2019-07-06 00:15 UTC, Carlgo11 commented on _data/cloud.yml
> +        text: "While the documentation makes no mention of this, when you go to add a Yubikey (the only hardware token supported), it says U2F Yubikeys are not supported. Yubikeys are only supported
```suggestion
        text: "Hardware 2FA only supports YubiKeys with Yubico OTP credentials."
```

2019-07-06 22:43 UTC, seonwoolee commented on _data/cloud.yml
> +        text: "While the documentation makes no mention of this, when you go to add a Yubikey (the only hardware token supported), it says U2F Yubikeys are not supported. Yubikeys are only supported
Sounds good.

2019-07-06 23:01 UTC, Carlgo11 approved these changes

2019-07-18 19:47 UTC, kmpoppe approved these changes

2019-07-18 19:47 UTC, merged