Added ScriptingHelpers
2factorauth/twofactorauth pull request #3887
Opened 2019-06-13 23:26 UTC by EcoGames

I added the site _ScriptingHelpers_ and it's icon in the _development_ section.

2019-09-20 05:47 UTC, kmpoppe commented on _data/developer.yml
> +      tfa: Yes
```suggestion
      tfa: Yes
      software: Yes
```

2019-09-20 05:50 UTC, kmpoppe requested changes
Hi @EcoGames and thank you for your contribution. I've added a single line comment that I'd ask you to commit because you didn't incorporate the 2fa-method in your PR.

2019-09-20 05:53 UTC, kmpoppe commented
Also, would you be able to add some documentation or screenshots of the enabling process?

2019-09-20 23:09 UTC, EcoGames commented
Where would you like the screenshots?

2019-09-20 23:21 UTC, kmpoppe commented
You can just add them into a comment using drag & drop. If possible, add a describing line per step you take.

2019-09-20 23:40 UTC, EcoGames commented
1. From the [main page](https://scriptinghelpers.org/), hover over your account name and click on "Settings".
![image](https://user-images.githubusercontent.com/25782944/65364138-c7ed8c00-dbdd-11e9-8bfa-88a0ed348ad6.png)
2. From the "Settings" page, click on the Security tab.
![image](https://user-images.githubusercontent.com/25782944/65364154-e6538780-dbdd-11e9-933c-244d6e1e7b2d.png)
3. From the "Security" tab, click on "Enable" under the "Two-Factor Auth" section.
![image](https://user-images.githubusercontent.com/25782944/65364173-0f741800-dbde-11e9-9e47-7fa782f17e87.png)
4. Scan the QR code provided on-screen using any third-party authenticator app. (It doesn't have to be Google Authenticator!) Then, type in the code provided by your third-party app after you scan the QR code.
![image](https://user-images.githubusercontent.com/25782944/65364195-2f0b4080-dbde-11e9-8ac4-00c6e2cc6abb.png)
5. From there, when you go back to the "Security" tab, you will see that 2FA is enabled.
![image](https://user-images.githubusercontent.com/25782944/65364215-55c97700-dbde-11e9-997c-5ee46fc73835.png)

2019-09-21 15:10 UTC, kmpoppe approved these changes

2019-10-16 07:54 UTC, kmpoppe submitted a review, later dismissed

2019-11-05 12:26 UTC, Jawshy commented
Hi @Reprevise. Which [site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#site-criteria) does Scripting Helpers meet?

2019-11-05 13:20 UTC, Reprevise commented
ScriptingHelpers is essentially a StackOverflow for Lua scripting on Roblox. It deals with personal information.

2019-11-08 12:52 UTC, Jawshy approved these changes

2019-11-09 05:39 UTC, kmpoppe requested changes
See inline comments, please :-)

2019-11-09 05:39 UTC, kmpoppe commented on _data/developer.yml
> +      - software
```suggestion
      - totp
```
That would be totp now :)

2019-11-28 19:12 UTC, kmpoppe approved these changes

2019-11-28 19:12 UTC, merged