Added TVTime
2factorauth/twofactorauth pull request #3888
Opened 2019-06-14 18:55 UTC by EcoGames

I added the data for TVTime in the entertainment YML file and the icon of TVTime in the entertainment images folder.

2019-07-23 07:56 UTC, theoricher approved these changes
I approve this change

2019-07-23 07:57 UTC, theoricher submitted a review, later dismissed
It's ok for me

2019-07-23 07:58 UTC, kmpoppe commented on _data/entertainment.yml
> +      url: https://wwwtvtime.com
```suggestion
      url: https://www.tvtime.com
```
Typo in URL

2019-07-23 08:00 UTC, theoricher commented on _data/entertainment.yml
> +      url: https://wwwtvtime.com
> 
> 
> Typo in URL

Yes !

2019-08-14 00:07 UTC, Carlgo11 reviewed
How does this fit the site criteria?

2019-09-20 12:32 UTC, kmpoppe commented
@EcoGames what site criteria (https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#site-criteria) does TVTime.com match?

2019-09-20 23:13 UTC, EcoGames commented
Users can create profiles on TVTime which allows users to upload profile photos, sometimes of themselves.

2019-12-03 22:57 UTC, Carlgo11 requested changes

2019-12-03 22:57 UTC, Carlgo11 commented on _data/entertainment.yml
> +  - name: TVTime
```suggestion
  - name: TV Time
```

2019-12-04 01:28 UTC, Carlgo11 approved these changes

2019-12-11 18:43 UTC, kmpoppe approved these changes

2019-12-11 18:44 UTC, merged