Add Rebrandly
2factorauth/twofactorauth pull request #3903
Opened 2019-06-17 16:16 UTC by yllcapitan

2019-06-18 10:18 UTC, rebrandly-dev submitted a review, later dismissed

2019-06-18 10:23 UTC, giannifiore submitted a review, later dismissed

2019-06-24 22:41 UTC, Carlgo11 requested changes
The logo you provided is just below our size limit and there's no real reason for it to be that large.
Here's a compressed version that's 34% the size:
![rebrandly-logo](https://user-images.githubusercontent.com/3535780/60056622-d06b1f00-96e1-11e9-82b1-8dedc7c556a0.png)

2019-07-05 20:05 UTC, Carlgo11 approved these changes

2019-07-18 19:39 UTC, kmpoppe approved these changes

2019-07-18 19:40 UTC, merged