Update Coinbase
2factorauth/twofactorauth pull request #3917
Opened 2019-07-02 12:31 UTC by jdabs

Coinbase allows hardware keys:
https://support.coinbase.com/customer/portal/articles/2973914-using-and-managing-security-keys

2019-07-05 20:30 UTC, Carlgo11 requested changes

2019-07-05 20:30 UTC, Carlgo11 commented on _data/cryptocurrencies.yml
>        doc: https://support.coinbase.com/customer/en/portal/articles/1658338-how-do-i-set-up-2-factor-authentication-
Let's compress that documentation URL :wink:
```suggestion
      doc: https://support.coinbase.com/customer/en/portal/articles/1658338
```

2019-07-05 20:39 UTC, jdabs commented
Ok, might as well do that too while we're deep in the .yaml

2019-07-05 20:43 UTC, Carlgo11 approved these changes

2019-07-18 19:16 UTC, kmpoppe approved these changes

2019-07-18 19:17 UTC, merged