Add Endomondo
2factorauth/twofactorauth pull request #3928
Opened 2019-07-13 20:07 UTC by Rakleed

Fix https://github.com/2factorauth/twofactorauth/issues/3927

2019-07-14 15:43 UTC, Carlgo11 requested changes
I suggest you use this image instead:
![endomondo.png](https://user-images.githubusercontent.com/3535780/61185888-b5dff200-a65e-11e9-9175-26e8f407677d.png)

2019-07-14 17:37 UTC, Rakleed commented
@Carlgo11 done.

2019-07-15 17:12 UTC, Carlgo11 approved these changes

2019-07-18 19:15 UTC, kmpoppe approved these changes

2019-07-18 19:15 UTC, merged