Add Runkeeper
2factorauth/twofactorauth pull request #3930
Opened 2019-07-13 20:22 UTC by Rakleed

Fix https://github.com/2factorauth/twofactorauth/issues/3929

2019-07-14 15:54 UTC, Carlgo11 requested changes
Here's a better logo:
![runkeeper.png](https://user-images.githubusercontent.com/3535780/61186018-6ef2fc00-a660-11e9-9e90-886c31b983aa.png)

2019-07-14 17:39 UTC, Rakleed commented
@Carlgo11 done. And should I write such messages as this, or do you get a notification after I add the right file?

2019-07-14 22:18 UTC, Carlgo11 commented
@Rakleed I receive an email when you change something however it’s alright if you want to write a message about it as well. Many people do that so it’s not really a problem. 🙂
![A02EE901-61E3-4F42-856E-8AA44B2BE3C7](https://user-images.githubusercontent.com/3535780/61189998-a334df80-a695-11e9-8689-4744d04c5848.png)

2019-07-16 10:50 UTC, Carlgo11 requested changes

2019-07-16 10:50 UTC, Carlgo11 commented on _data/health.yml
> +      twitter: Runkeeper
```suggestion
      twitter: RKSupport
```

2019-07-16 17:37 UTC, Carlgo11 approved these changes

2019-07-18 19:13 UTC, kmpoppe approved these changes

2019-07-18 19:14 UTC, merged