Added GMX.net (renamed GMX to GMX.com)
2factorauth/twofactorauth pull request #3940
Opened 2019-07-18 18:06 UTC by GeileHirnbude

Added the German sister site to GMX.com, which is GMX.net. Accordingly, I renamed the English (and Spanish/French) site to GMX.com.

By the way, [Wikipedia claims](https://en.wikipedia.org/wiki/GMX_Mail#Security) both gmx.com and gmx.net have tfa, but on gmx.com you still cannot find concrete evidence.

2019-07-19 15:40 UTC, kmpoppe commented
Closes #3870

2019-07-19 15:41 UTC, kmpoppe commented on _data/email.yml
> +      img: gmx.png
```suggestion
      img: gmx.net.png
```

2019-07-19 15:42 UTC, kmpoppe commented on _data/email.yml
> +      img: gmx.png
@GeileHirnbude I am not allowed to push changes to your repository, please commit this change so that the travis check runs ok. Thanks!
// Kai

2019-07-19 15:42 UTC, kmpoppe requested changes
See single line comment.

2019-07-20 05:52 UTC, kmpoppe requested changes
@GeileHirnbude Sorry, I'd need you to change it again:
Rake information:
1. GMX.net: 'gmx.net.png': not matched to pattern /^[a-z0-9_\-\+]+\.png/.
So please change the filename to gmx_net.png and change it in the email.yml as well. Thanks!
// Kai

2019-07-20 10:51 UTC, GeileHirnbude commented
> @GeileHirnbude Sorry, I'd need you to change it again:
> Rake information:
> 
> 1. GMX.net: 'gmx.net.png': not matched to pattern /^[a-z0-9_-+]+.png/.
>    So please change the filename to gmx_net.png and change it in the email.yml as well. Thanks!
>    // Kai

No worries! I applied these changes.

2019-07-20 12:51 UTC, kmpoppe approved these changes

2019-07-21 21:03 UTC, Carlgo11 approved these changes

2019-07-21 21:03 UTC, merged