Update Vanguard
2factorauth/twofactorauth pull request #3963
Opened 2019-08-11 08:24 UTC by kmpoppe

Changed exception wording according to #2962.

2019-08-11 21:52 UTC, Carlgo11 commented
Do you mean that a phone number is required for 2FA?

2019-09-09 02:16 UTC, Carlgo11 commented
@kmpoppe ^

2019-09-15 06:14 UTC, kmpoppe commented
@Carlgo11 I just took what was in #2962 and put it in a new PR because the other one was so garbled. As vanguard.com always seems to be in maintenance mode when I want to check back on the documentation I can't get any further :-/

2019-09-15 08:40 UTC, kmpoppe commented
@Carlgo11 After the site maintenance (looks like saturday nigth in the US) is over, I've got further information:
- From https://investor.vanguard.com/security/security-keys
	- Do I need to register for **security codes** if I have a security key?
		- **Yes**, because if you don't have your key or if you're logging on from a device that isn't compatible, we'll need to send you a security code instead.

- From https://investor.vanguard.com/security/security-codes
	- What are **security codes** and how do they work?
		- A **security code** is a unique, single-use, 6-digit number you receive by **text** or **automated phone** call that you'll enter when you log on to your Vanguard account from a device we don't recognize as one you regularly use.

2019-09-15 08:42 UTC, kmpoppe commented on _data/investing.yml
> +        text: "SMS/Phone require for 2FA. Hardware 2FA requires using a Chrome browser and only supports the following hardware keys: Yubikey 4 Series, YubiKey 5 Series, Yubikey Security Key Series."
```suggestion
        text: "SMS/Phone 2FA activation required before hardware 2FA can be used. Hardware 2FA requires using a Chrome browser and only supports the following hardware keys: Yubikey 4 Series, YubiKey 5 Series, Yubikey Security Key Series."
```

2019-09-15 14:27 UTC, Carlgo11 requested changes

2019-09-15 14:27 UTC, Carlgo11 commented on _data/investing.yml
> +        text: "SMS/Phone 2FA activation required before hardware 2FA can be used. Hardware 2FA requires using a Chrome browser and only supports the following hardware keys: Yubikey 4 Series, YubiKey
```suggestion
        text: "Hardware based 2FA requires SMS / Phone call 2FA as a backup. Hardware 2FA is only supported on Chrome browsers and works with the following hardware keys: Yubikey 4 Series, YubiKey 5 Series, Yubikey Security Key Series."
```

2019-09-16 21:50 UTC, Carlgo11 submitted a review, later dismissed

2019-10-03 02:12 UTC, Carlgo11 approved these changes

2019-10-03 02:12 UTC, merged