Add British Telecom (BT)
2factorauth/twofactorauth pull request #3966
Opened 2019-08-15 11:39 UTC by Carlgo11

Closes #3744

2019-08-20 19:02 UTC, kmpoppe submitted a review, later dismissed

2019-09-05 23:06 UTC, jamcat22 approved these changes

2019-09-05 23:07 UTC, jamcat22 requested changes
Needs new logo. On phone and can't upload at the moment.

2019-09-05 23:29 UTC, Carlgo11 commented
@jamcat22 what's wrong with the logo? It's below the size limit and seems to be their current logo :shrug:

2019-09-06 03:34 UTC, jamcat22 commented
@carlgo11 my bad. They haven't fully rolled out their redesign yet. Looks good. 👍

2019-09-06 03:34 UTC, jamcat22 approved these changes

2019-09-06 07:55 UTC, kmpoppe approved these changes

2019-09-06 07:56 UTC, merged