Update sparkasse and comdirect
2factorauth/twofactorauth pull request #3967
Opened 2019-08-17 08:21 UTC by MartinThoma

2019-08-20 18:52 UTC, kmpoppe requested changes
See single line comments.

2019-08-20 18:52 UTC, kmpoppe commented on _data/banking.yml
>        lang: de
```suggestion
```

2019-08-20 18:52 UTC, kmpoppe commented on _data/banking.yml
>        lang: de
```suggestion
```

2019-08-20 18:52 UTC, kmpoppe commented on _data/banking.yml
>        lang: de
As per rake: 'lang' should NOT be present when tfa: true.

2019-08-20 18:52 UTC, kmpoppe commented on _data/banking.yml
>        lang: de
As per rake: 'lang' should NOT be present when tfa: true.

2019-08-20 18:54 UTC, kmpoppe commented
Hey @MartinThoma - as you set the commit to be only changeable by you, I'd kindly ask you to remove the lang: tags because they are no longer needed, when tfa is already true. 
Thank you!
// Kai

2019-08-20 20:49 UTC, MartinThoma commented
Ok, I removed them :+1:

2019-08-23 05:42 UTC, kmpoppe commented
@MartinThoma Thank you for your contribution. I just now looked at the pages you provided, and even though they speak of "Zwei-Faktor-Authentifizierung" (two-factor authentication), what they really mean is authorization. Two Factor Authentication, as we see it for this project, means that you are directly challenged to provide a second factor upon login, not just for a sensitive transaction. This is also described in our Contribution Guidelines: https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#a-note-on-definitions

Therefore I think that this pull request can not be merged. If I perceived any information wrongly, please do not hesitate to tell me so. Otherwise, I'd be glad, if you closed this PR.

Thanks again for taking the time to contribute to our project!

// Kai

2019-08-23 08:10 UTC, MartinThoma commented
> I just now looked at the pages you provided, and even though they speak of "Zwei-Faktor-Authentifizierung" (two-factor authentication), what they really mean is authorization. Two Factor Authentication, as we see it for this project, means that you are directly challenged to provide a second factor upon login, not just for a sensitive transaction.

Ok, I didn't know that. In this case you are right, the PR should not be merged. I close it.

2019-08-23 08:10 UTC, closed without merging