Add ICDSoft to hosting, second attempt
2factorauth/twofactorauth pull request #3970
Opened 2019-08-21 02:37 UTC by korikori

Hi, not sure if this is the proper way to "re-open" PR #3578, when we were short of Alexa 200K. As of right now, we are closer to 135K. Thank you in advance.

2019-08-22 01:27 UTC, Carlgo11 requested changes

2019-08-22 01:27 UTC, Carlgo11 commented on _data/hosting.yml
> +      doc: https://tickets.suresupport.com/faq/article-1700/en/what_is_two_factor_authentication
```suggestion
      doc: https://tickets.suresupport.com/faq/article-1700
```

2019-08-23 00:58 UTC, Carlgo11 approved these changes

2019-08-23 04:44 UTC, kmpoppe approved these changes

2019-08-23 04:44 UTC, merged