Update doc URL for Salesforce
2factorauth/twofactorauth pull request #3971
Opened 2019-08-22 11:00 UTC by dst87

2019-08-23 00:59 UTC, Carlgo11 approved these changes

2019-08-23 04:46 UTC, kmpoppe submitted a review, later dismissed

2019-08-23 05:20 UTC, kmpoppe commented
@Carlgo11 Travis seems to have gotten stuck in reporting the status here. Can you reset that?

2019-08-24 15:11 UTC, Carlgo11 commented
Seems like Travis-CI didn't receive the PR data.
@dst87 could you enable edits from maintainers to the PR? It should be on the right hand side of your screen.
<img width="268" alt="Screen Shot 2019-08-24 at 17 08 19" src="https://user-images.githubusercontent.com/3535780/63639334-259bc080-c692-11e9-9469-4d846ac798de.png">

2019-08-26 13:29 UTC, dst87 commented
@Carlgo11 - it was already checked, so I unchecked it and checked it again. Did that help?

2019-08-26 16:21 UTC, kmpoppe commented on _data/communication.yml
> +      doc: https://developer.salesforce.com/docs/atlas.en-us.securityImplGuide.meta/securityImplGuide/add_time-based_token.htm
```suggestion
      doc: https://developer.salesforce.com/docs/atlas.en-us.securityImplGuide.meta/securityImplGuide/add_time-based_token.htm
```

2019-08-26 16:23 UTC, kmpoppe commented on _data/communication.yml
```suggestion
    exceptions:
      text: "*Travis Reset. Ignore*"
      
```

2019-08-26 16:27 UTC, kmpoppe commented
@dst87 This still doesn't seem to work. Could you please move your change to a new branch within your fork of the project and the open another pull request? This seems to have been lost in obscurity ;-)

Thanks!

// Kai

2019-08-26 22:16 UTC, Carlgo11 requested changes
The issue is that the commit you did wasn't registered by Travis-CI. (I'll report the bug to them)
We could always do another change so that the next commit gets registered.

Looking at the stored logo for Salesforce it could certainly be improved.
@dst87 could you please merge my pull request over at dst87#1 and that should be enough to get Travis to accept this PR.

2019-08-27 07:05 UTC, dst87 commented
@Carlgo11 I've merged your PR.  If that doesn't fix it, I'll re-do the PR entirely from a new branch as @kmpoppe suggested.  Let me know!

2019-08-27 07:34 UTC, Carlgo11 approved these changes
It worked.

2019-08-27 08:05 UTC, kmpoppe approved these changes

2019-08-27 08:05 UTC, merged