Add emails for some services
2factorauth/twofactorauth pull request #3994
Opened 2019-09-06 19:10 UTC by Rakleed

I wrote to each of these email addresses and received either a response or a notice of reading. If necessary, I can take screenshots of the messages.

2019-09-09 02:15 UTC, Carlgo11 requested changes

2019-09-09 02:15 UTC, Carlgo11 commented on _data/health.yml
> +      twitter: 23andMe
```suggestion
      twitter: 23andMesupport
```

2019-09-09 02:15 UTC, Carlgo11 commented on _data/social.yml
> +      twitter: StackExchange
Looks like they don't monitor that twitter account.
```suggestion
```

2019-09-09 20:01 UTC, Carlgo11 approved these changes

2019-09-10 08:58 UTC, kmpoppe approved these changes

2019-09-10 08:58 UTC, merged