Add VirusTotal
2factorauth/twofactorauth pull request #4005
Opened 2019-09-10 16:02 UTC by jakejarvis

A pretty popular tool in the infosec world (and owned by Alphabet). https://www.virustotal.com/

Can't find any docs unfortunately (except a blog post from a few months ago) but it's pretty self-explanatory in their settings:

<img width="649" alt="Screen Shot 2019-09-10 at 11 56 24 AM" src="https://user-images.githubusercontent.com/1703673/64630281-c7c1e500-d3c2-11e9-9f0c-9f1c1cc3173c.png">

Thanks! :)

2019-09-12 02:21 UTC, Carlgo11 requested changes
The image is a bit larger than what I should be.
Here's a better one:
![virustotal](https://user-images.githubusercontent.com/3535780/64749111-b12ba300-d514-11e9-86ec-9cbdea021add.png)

2019-09-12 02:31 UTC, jakejarvis commented
Yup, that one is definitely much smaller! 👍

2019-09-12 02:32 UTC, Carlgo11 approved these changes

2019-09-13 06:28 UTC, kmpoppe approved these changes

2019-09-13 06:29 UTC, merged