Updates
2factorauth/twofactorauth pull request #4017
Opened 2019-09-15 18:41 UTC by bobmatyas

Updates from issues backlog.

2019-09-16 06:09 UTC, kmpoppe commented on _data/betting.yml
> +      facebook: win2dayat
```suggestion
      facebook: win2dayat
      lang: de
      
```
Adding `lang: de` will translate the text on the call-to-action buttons. Additionally, the data files should end with a new line.

2019-09-16 06:10 UTC, kmpoppe commented on _data/banking.yml
> +      doc: https://www.mbna.ca/help-centre/credit-cards/two-step-verification-faq/index.jsp
```suggestion
      doc: https://www.mbna.ca/help-centre/credit-cards/two-step-verification-faq/
```
`index.jsp` is superflous in that link.

2019-09-16 06:12 UTC, kmpoppe requested changes
Thank you for your contribution @bobmatyas. Please take a look at the line comments I added.
// Kai

2019-09-16 11:32 UTC, bobmatyas commented
> Thank you for your contribution @bobmatyas. Please take a look at the line comments I added.
> // Kai

Thanks. I made the requested changes and will keep the reasons why in mind for future edits.

2019-09-17 06:24 UTC, kmpoppe approved these changes

2019-09-18 19:48 UTC, kmpoppe commented
@bobmatyas Just a quick reminder. Next time, if you have multiple updates, please put them in different branches and different pull requests so that adding/reverting them easier.
Thanks!

2019-09-19 14:23 UTC, bobmatyas commented
> @bobmatyas Just a quick reminder. Next time, if you have multiple updates, please put them in different branches and different pull requests so that adding/reverting them easier.
> Thanks!

Sorry, I missed that part in the contribution guidelines. I will keep things separate in the future.

2019-10-09 21:02 UTC, merged