Update investing.yml
2factorauth/twofactorauth pull request #4055
Opened 2019-10-01 20:40 UTC by StarkDevelopments

New site - Youinvest.co.uk

2019-10-04 17:17 UTC, kmpoppe commented
Alexa rank on 04.10.2019 17:17 UTC: [138,640](https://www.alexa.com/siteinfo/youinvest.co.uk)

2019-10-04 17:29 UTC, kmpoppe submitted a review, later dismissed

2019-10-04 20:28 UTC, Carlgo11 requested changes

2019-10-04 20:28 UTC, Carlgo11 commented on _data/investing.yml
> +    - name: Youinvest
```suggestion
    - name: AJ Bell Youinvest
```

2019-10-04 20:59 UTC, kmpoppe commented on _data/investing.yml
> +    - name: Youinvest
Resolved by 99e79da

2019-10-04 23:11 UTC, Carlgo11 approved these changes

2019-10-05 07:05 UTC, kmpoppe approved these changes

2019-10-05 07:05 UTC, merged