add president's choice financial
2factorauth/twofactorauth pull request #4056
Opened 2019-10-03 00:22 UTC by bobmatyas

closes #4045

2019-10-03 19:51 UTC, Carlgo11 requested changes

2019-10-03 19:51 UTC, Carlgo11 commented on _data/banking.yml
> +      doc: https://www.pcfinancial.ca/en/security
The doc link doesn't describe how to use or setup 2fa on the site so it's better just to leave it out.
```suggestion
```

2019-10-04 00:21 UTC, Carlgo11 submitted a review, later dismissed

2019-10-04 17:11 UTC, kmpoppe approved these changes

2019-10-04 20:24 UTC, Carlgo11 approved these changes

2019-10-04 20:24 UTC, merged

2019-10-05 00:11 UTC, LukeAbellSmith commented
Except PC Financial was already on twofactorauth.org, now there are 2, and they don't do banking.
![image](https://user-images.githubusercontent.com/842506/66246588-6dbaf380-e6d2-11e9-90ee-a4237f947d23.png)

2019-10-05 01:14 UTC, Carlgo11 commented
Hmm that shouldn't have happened 😕 
I'll remove the old one and move this one to the Finance category.

2019-10-05 01:42 UTC, Carlgo11 commented
Fixed in 139407606287a337c57ec4a893dbaca981875e97