Add Yelp
2factorauth/twofactorauth pull request #4094
Opened 2019-10-11 08:28 UTC by rfosu2k2

Add Yelp as not having 2FA.

2019-10-15 17:38 UTC, Carlgo11 requested changes
I think it's better to make the red background cover the entire image so that it doesn't look weird on our site.
![yelp logo](https://user-images.githubusercontent.com/3535780/66855270-39bdb900-ef83-11e9-91ff-1ece7787a459.png)

2019-10-15 18:47 UTC, rfosu2k2 commented
There is an alternate approved image to use as well, but I will let you pick between the two.  Let me know so I can change to the correct image.
![yelp](https://user-images.githubusercontent.com/5554308/66860144-6f41b280-ef41-11e9-8890-c02d41025e5b.png)

2019-10-15 18:59 UTC, Carlgo11 commented
Your image is fine 👍

2019-10-15 19:21 UTC, kmpoppe approved these changes

2019-10-16 07:28 UTC, Carlgo11 approved these changes

2019-10-16 07:28 UTC, merged