fidelity: now offering SMS for retirement accounts
2factorauth/twofactorauth pull request #4098
Opened 2019-10-12 20:06 UTC by mathstuf

Not sure if there still exist account types which are not supported or
not. SMS-only though when through this account type though.

2019-10-19 15:30 UTC, VictorYing reviewed
It seems much of the information here is outdated and no longer matches my recent experience with 2FA on my Fidelity.com account.

2019-10-19 15:30 UTC, VictorYing commented on notes/fidelity.html
>          or the Symantec VIP Access smartphone app.
The first sentence up here needs updating.

2019-10-19 15:30 UTC, VictorYing commented on notes/fidelity.html
> +            supports SMS.
I have an ordinary personal account at Fidelity.com (not set up through an employer). I signed up for 2FA with my phone number. When I log in via an incognito/private browser I get prompted after my password for whether I'd like a text message or automated voice call to receive a security code, so it seems this isn't true.

2019-10-19 15:30 UTC, VictorYing commented on notes/fidelity.html
>      <p>
I believe everything below here about "As of October 2016..." and "That this is different than the weaker Transaction Security..." is outdated. The two links below still link to pages that exist, but the page content has changed and the quoted text is no longer there, and Fidelity is no longer advertising Transaction Security as a feature, instead advertising 2FA at login. I'd recommend replacing all this outdated text with a simple link to Fidelity's newer page documenting 2FA: https://www.fidelity.com/security/extra-security-login

2019-10-19 15:30 UTC, VictorYing commented on notes/fidelity.html
> +        <li>
The organization of this list is not correct. As documented at https://www.fidelity.com/security/extra-security-login, Fidelity has two separate routes to two different kinds of 2FA for logins. You can either set up the Symantec VIP Access proprietary 2FA on logins as before (using either a physical token or the proprietary apps) which still requires a phone call, OR you can set up 2FA via a phone number (SMS or automated voice call) which should be set up through the online security center.

It's not obvious to me whether it's better to try to write your own documentation of this here, or to simply link to (or quote directly from?) the page at Fidelity.com which seems to cover it pretty well: https://www.fidelity.com/security/extra-security-login

2019-10-19 15:35 UTC, kmpoppe commented
@VictorYing thank you for your comments.
From what I read it would seem that the usefulness of our local documentation has ended and we can just link the document of fidelity, maybe with adding since exception text.
I'll look into this later.
Thank you again for your contribution!
// Kai

2019-10-19 17:31 UTC, kmpoppe commented on _data/investing.yml
>      doc: "/notes/fidelity/"
```suggestion
    doc: https://www.fidelity.com/security/how-two-factor-authentication-works
```

2019-10-19 17:35 UTC, kmpoppe commented on _data/investing.yml
>      doc: "/notes/fidelity/"
@mathstuf Ben,
please replace this link to the page of fidelity and delete the `notes/fidelity.html` files.
Thanks!
// Kai

2019-10-19 17:36 UTC, kmpoppe commented on _data/investing.yml
>        - hardware
```suggestion
      - phone
      - hardware
```

2019-10-19 17:37 UTC, kmpoppe commented on _data/investing.yml
>        - hardware
As 2FA pins can be obtained by text or call, this should be included as well.

2019-10-19 17:37 UTC, kmpoppe requested changes
See inline comments

2019-10-25 20:00 UTC, mathstuf commented
Thanks @VictorYing and @kmpoppe. I've updated it and left an exception noting that support may vary between different account types (at least I didn't see anything supporting hardware for my account type).

2019-10-27 12:12 UTC, kmpoppe approved these changes

2019-10-27 12:13 UTC, kmpoppe commented
Closes #4073

2019-10-27 20:48 UTC, Carlgo11 approved these changes

2019-10-27 20:48 UTC, merged