Add Fanatical.com to Gaming
2factorauth/twofactorauth pull request #4118
Opened 2019-10-16 10:07 UTC by webdevian

2019-11-05 12:52 UTC, Jawshy submitted a review, later dismissed
Thanks for the submission, @webdevian.

2019-11-09 05:43 UTC, kmpoppe requested changes
See inline comments, please :)

2019-11-09 05:43 UTC, kmpoppe commented on _data/gaming.yml
> +      - software
```suggestion
      - totp
```
This would be `totp` not just simply `software` from what I see in the doc.

2019-12-01 08:29 UTC, kmpoppe commented
@webdevian As you have not allowed maintainer edits to your branch I can't commit my suggestions myself. May I ask you to change the 2fa-method according to my suggestion?
If we don't hear back from you within 2 weeks, I will close this PR due to inactivity.
Thank you for your contribution and your understanding!
// Kai

2020-01-03 23:19 UTC, closed without merging

2020-01-07 08:45 UTC, webdevian commented
Sorry I missed these comments, I have created a new PR