Add Arkansas Tech University
2factorauth/twofactorauth pull request #4125
Opened 2019-10-17 02:01 UTC by AnalogCyan

Add Arkansas Tech University as they are stating the process of implementing 2FA.

2019-10-17 06:34 UTC, kmpoppe commented on _data/education.yml
> +    exceptions: "Requires submitting a support ticket to activate. Currently only applies to email, but they are looking into implementing it account-wide."
```suggestion
    exception: "Requires submitting a support ticket to activate. Currently only applies to email, but they are looking into implementing it account-wide."
```

2019-10-17 06:35 UTC, kmpoppe commented on _data/education.yml
> +    exceptions: "Requires submitting a support ticket to activate. Currently only applies to email, but they are looking into implementing it account-wide."
The tag has changed with the API v2 commit a few dys ago.

2019-10-17 06:35 UTC, kmpoppe requested changes
See inline comment

2019-10-26 03:44 UTC, Carlgo11 commented on _data/education.yml
> +    exception: "Requires submitting a support ticket to activate. Currently only applies to email, but they are looking into implementing it account-wide."
If 2FA isn't required account wide it's not 2FA according to our definition.

2019-11-21 16:21 UTC, kmpoppe commented
I'm closing this PR because the site currently doesn't fullfil our requirements for an account-wide 2FA setup.

2019-11-21 16:21 UTC, closed without merging