Add Koodo
2factorauth/twofactorauth pull request #4148
Opened 2019-10-20 19:55 UTC by jpayoung

Add entry Koodo in _data/services.yml
- Icon
- No 2FA

2019-10-25 14:50 UTC, Carlgo11 requested changes
I suggest you use this image instead:
![kodo.png](https://user-images.githubusercontent.com/3535780/67581000-881f4480-f747-11e9-8d5b-951016f62618.png)

2019-10-25 14:50 UTC, Carlgo11 commented on _data/utilities.yml
> +    twitter: Koodo
```suggestion
    twitter: koodo
```

2019-10-25 14:50 UTC, Carlgo11 commented on _data/utilities.yml
> +  - name: Koodo
```suggestion
  - name: Koodo Mobile
```

2019-10-27 07:10 UTC, Carlgo11 commented
@jpayoung you forgot to update the image :wink:

2019-10-28 05:56 UTC, jpayoung commented
Ooops! Midterms have me tired ;) Updating now

2019-10-28 06:00 UTC, jpayoung reviewed
@Carlgo11 Image updated! Let me know if there's anything else

2019-10-28 14:16 UTC, Carlgo11 approved these changes

2019-10-28 14:16 UTC, merged