Add Telus
2factorauth/twofactorauth pull request #4150
Opened 2019-10-20 20:01 UTC by jpayoung

Add entry Bell in _data/services.yml
- Icon
- No 2FA

2019-10-20 20:23 UTC, jpayoung commented
Looks like I don't know my alphabet! Fixing now.

2019-10-20 20:28 UTC, Carlgo11 requested changes
The use a rather bad logo but I think this one is the best one:
![telus](https://user-images.githubusercontent.com/3535780/67165707-d10e7c00-f388-11e9-9531-757d395897f7.png)
It doesn't contain any text.

2019-10-20 20:30 UTC, Carlgo11 requested changes

2019-10-20 20:30 UTC, Carlgo11 commented on _data/utilities.yml
> +    twitter: Telus
```suggestion
    twitter: TELUSSupport
```

2019-10-20 20:30 UTC, Carlgo11 commented on _data/utilities.yml
> +    facebook: TELUSSupport
```suggestion
    facebook: telus
```

2019-10-22 00:15 UTC, Carlgo11 requested changes

2019-10-22 00:15 UTC, Carlgo11 commented on _data/utilities.yml
> +    twitter: TELUSSupport
🤔 
```suggestion
    twitter: TELUSsupport
```

2019-10-22 00:24 UTC, Carlgo11 approved these changes
Thanks! 😄

2019-10-28 10:29 UTC, kmpoppe approved these changes

2019-10-28 10:29 UTC, merged