Update Docker 2FA
2factorauth/twofactorauth pull request #4165
Opened 2019-10-22 14:47 UTC by westim

Docker recently announced the beta for Software & Hardware 2FA for the Docker Hub site.

https://www.docker.com/blog/designing-docker-hub-2fa/

2019-10-23 16:39 UTC, Carlgo11 requested changes

2019-10-23 16:39 UTC, Carlgo11 commented on _data/developer.yml
>      facebook: docker.run
```suggestion
```

2019-10-23 16:39 UTC, Carlgo11 commented on _data/developer.yml
>      twitter: Docker
```suggestion
```

2019-10-23 16:39 UTC, Carlgo11 commented on _data/developer.yml
> +      - software
```suggestion
      - totp
```

2019-10-23 16:39 UTC, Carlgo11 commented on _data/developer.yml
> +      - hardware
By the looks of it they don't support WebAuthn or any other hardware solutions yet.
```suggestion
```

2019-10-27 06:53 UTC, kmpoppe commented on _data/developer.yml
> +      - hardware
Resolved by 414add7

2019-10-27 06:53 UTC, kmpoppe commented on _data/developer.yml
> +      - software
Resolved by 414add7

2019-10-27 06:53 UTC, kmpoppe commented on _data/developer.yml
>      twitter: Docker
Resolved by 414add7

2019-10-27 06:53 UTC, kmpoppe commented on _data/developer.yml
>      facebook: docker.run
Resolved by 414add7

2019-10-27 06:54 UTC, kmpoppe approved these changes

2019-10-27 07:06 UTC, Carlgo11 approved these changes

2019-10-27 07:07 UTC, merged