Add OneLogin
2factorauth/twofactorauth pull request #4169
Opened 2019-10-22 18:29 UTC by phallobst

2019-12-03 22:48 UTC, Carlgo11 requested changes

2019-12-03 22:48 UTC, Carlgo11 commented on _data/identity.yml
> +      - u2f
Yubikeys are mentioned but the phrasing makes it sound like it's their normal OTP solution. Other than that no U2F solution is mentioned.
```suggestion
```

2019-12-03 23:48 UTC, Carlgo11 approved these changes

2019-12-11 18:40 UTC, kmpoppe approved these changes

2019-12-11 18:40 UTC, merged