Add Prudential to Finance
2factorauth/twofactorauth pull request #4173
Opened 2019-10-23 00:24 UTC by bobmatyas

Closes #4076

2019-10-25 15:23 UTC, Carlgo11 requested changes
I recommend this image instead:
![prudential.png](https://user-images.githubusercontent.com/3535780/67583589-2f9e7600-f74c-11e9-9515-cd10c49718de.png)

2019-10-27 23:48 UTC, Carlgo11 requested changes

2019-10-27 23:48 UTC, Carlgo11 commented on _data/investing.yml
> +  - name: Prudential
```suggestion
  - name: Prudential Financial
```

2019-10-28 01:12 UTC, Carlgo11 approved these changes

2019-10-28 10:25 UTC, kmpoppe approved these changes

2019-10-28 10:25 UTC, merged