Add sapo
2factorauth/twofactorauth pull request #4183
Opened 2019-10-23 20:23 UTC by esteveste

2019-10-25 15:48 UTC, Carlgo11 requested changes
Try this logo instead
![sapo.png](https://user-images.githubusercontent.com/3535780/67584480-0aab0280-f74e-11e9-9931-8c6dc272f515.png)

2019-10-25 15:48 UTC, Carlgo11 commented on _data/email.yml
> +  - name: Sapo
```suggestion
  - name: SAPO Mail
```

2019-10-25 15:48 UTC, Carlgo11 commented on _data/email.yml
> +
```suggestion
    twitter: sapo
    facebook: sapo
    lang: pt

```

2019-10-25 15:48 UTC, Carlgo11 commented on _data/email.yml
> +    email_address: apoioportalsapo@suporte.sapo.pt
```suggestion
    email_address: conteudos@mail.sapo.pt
```

2019-10-26 03:16 UTC, Carlgo11 approved these changes

2019-10-26 03:18 UTC, Carlgo11 commented
Thanks for the pull request! We just need one more member to approve it before we can merge.
By the way, we're missing a Portuguese translation of our Twitter messages so if that's something you'd like to help with we'd greatly appreciate that 😄 
https://github.com/2factorauth/twofactorauth/blob/master/_data/languages.yml

2019-10-28 10:12 UTC, kmpoppe approved these changes

2019-10-28 10:12 UTC, merged