Update Barclays UK/US
2factorauth/twofactorauth pull request #4186
Opened 2019-10-24 11:50 UTC by phallobst

2019-10-25 16:12 UTC, Carlgo11 approved these changes

2019-10-27 06:33 UTC, kmpoppe requested changes
See inline comment, please.

// Kai

2019-10-27 06:33 UTC, kmpoppe commented on _data/banking.yml
> +    doc: https://www.barclaycardus.com/servicing/security-center?howWeProtectYou=
```suggestion
    doc: https://www.barclaycardus.com/servicing/security-center?howWeProtectYou=#loginProcess
```
Even though `howWeProtectYou` and `howWeProtectYou=` both lead to the same page, I'd go for adding the first subPage `loginProcess` where SafeCode™ is explained.

2019-10-30 09:20 UTC, kmpoppe approved these changes

2019-10-30 09:21 UTC, merged