Add Sunsuper
2factorauth/twofactorauth pull request #4195
Opened 2019-10-26 11:59 UTC by Jawshy

[Sunsuper](https://www.sunsuper.com.au/about-us) 'is one of Australia‘s biggest and fastest growing super funds'.

2019-10-26 16:46 UTC, Carlgo11 requested changes

2019-10-26 16:46 UTC, Carlgo11 commented on _data/investing.yml
> +    twitter: sunsuper
```suggestion
    twitter: Sunsuper
```

2019-10-26 16:46 UTC, Carlgo11 commented on _data/investing.yml
> +    facebook: sunsuper
```suggestion
    facebook: Sunsuper
```

2019-10-27 07:04 UTC, Carlgo11 approved these changes

2019-10-27 20:53 UTC, kmpoppe approved these changes

2019-10-27 20:53 UTC, merged