Add Lake Michigan Credit Union
2factorauth/twofactorauth pull request #4197
Opened 2019-10-26 20:09 UTC by dsbert

lmcu.org/personal/banking/services/mobile-authenticator

Alexa rank 41,731
alexa.com/siteinfo/lmcu.org

2019-10-26 20:42 UTC, Carlgo11 requested changes
Here's a better image to use:
![webclip](https://user-images.githubusercontent.com/3535780/67625709-cb5dde00-f841-11e9-9dd0-62fd01d395ea.png)

2019-10-26 20:42 UTC, Carlgo11 commented on _data/banking.yml
> +      - software
```suggestion
      - proprietary
```

2019-10-26 23:13 UTC, dsbert commented
> 
> 
> Here's a better image to use:
> ![webclip](https://user-images.githubusercontent.com/3535780/67625709-cb5dde00-f841-11e9-9dd0-62fd01d395ea.png)

Thanks

2019-10-27 07:03 UTC, Carlgo11 approved these changes

2019-10-27 08:34 UTC, kmpoppe approved these changes

2019-10-27 08:34 UTC, merged