Added BunnyCDN
2factorauth/twofactorauth pull request #4203
Opened 2019-10-27 18:40 UTC by TheLegendaryMarc

2019-10-27 23:38 UTC, Carlgo11 commented
Thanks for the pull request!

I see that you haven't add any documentation link. Could you maybe find one that describes how to enable 2FA on the site?

If no documentation is available or you can't find it, could you please add some screenshots of the 2FA setup process and/or login process?
__Remember to blur or crop out any personal information linked to you.__

You can attach the screenshots here in a comment, like this:
![screenshot](https://user-images.githubusercontent.com/3535780/62257740-32b4ef00-b407-11e9-8f35-fc7c47ad72fb.gif)

2019-10-28 21:16 UTC, TheLegendaryMarc commented
Login Process:
Step 1
![screen_1](https://user-images.githubusercontent.com/11300323/67718593-5cfb5600-f9d0-11e9-994c-1fd4577d633b.PNG)
Step 2
![screen_2](https://user-images.githubusercontent.com/11300323/67718600-61277380-f9d0-11e9-91cd-6120a1631138.PNG)

Setup 2FA:
Step 1
![screen_3](https://user-images.githubusercontent.com/11300323/67718625-6be20880-f9d0-11e9-91f2-5d905d2eb8fa.PNG)
Step 2
![screen_4](https://user-images.githubusercontent.com/11300323/67718633-6e446280-f9d0-11e9-8f93-89b6aefdd38d.PNG)

2019-10-28 21:40 UTC, Carlgo11 requested changes

2019-10-28 21:40 UTC, Carlgo11 commented on _data/hosting.yml
> +      - software
```suggestion
      - totp
```

2019-11-04 02:16 UTC, Carlgo11 approved these changes

2019-11-04 09:06 UTC, kmpoppe approved these changes

2019-11-04 09:06 UTC, merged