Add Vodafone (DE)
2factorauth/twofactorauth pull request #4209
Opened 2019-10-27 21:40 UTC by jerr0328

Similar to other Vodafone entries, does not offer 2FA options in Germany either.

2019-10-27 23:42 UTC, Carlgo11 requested changes

2019-10-27 23:42 UTC, Carlgo11 commented on _data/utilities.yml
> +    twitter: vodafone_de
```suggestion
    twitter: vodafoneservice
```

2019-10-28 10:09 UTC, kmpoppe approved these changes

2019-10-28 14:10 UTC, Carlgo11 approved these changes

2019-10-28 14:10 UTC, merged