Add Airship
2factorauth/twofactorauth pull request #4218
Opened 2019-10-28 21:00 UTC by phallobst

2019-10-30 09:06 UTC, kmpoppe commented
Alexa rank on 30.10.2019 09:05 UTC: [56,505](https://www.alexa.com/siteinfo/airship.com)

2020-01-27 05:46 UTC, Jawshy requested changes

2020-01-27 05:46 UTC, Jawshy commented on _data/communication.yml
> +
```suggestion
    exception: "2FA is only available upon request for customers on their Essential and Comprehensive plans."
```
As per [Preparing for Two Factor Authentication](https://support.airship.com/hc/en-us/articles/115001994786-Preparing-for-Two-Factor-Authentication).

2020-01-27 08:16 UTC, Jawshy approved these changes

2020-02-24 22:28 UTC, jamcat22 approved these changes

2020-02-24 22:28 UTC, merged