Add Bcnex
2factorauth/twofactorauth pull request #4234
Opened 2019-10-30 20:37 UTC by phallobst

Alexa rank: 61,368

2019-12-03 22:52 UTC, Carlgo11 requested changes

2019-12-03 22:52 UTC, Carlgo11 commented on _data/cryptocurrencies.yml
> +      - totp
The doc link also shows SMS-based 2FA.
```suggestion
      - totp
      - sms
```

2019-12-03 23:49 UTC, Carlgo11 approved these changes

2019-12-06 10:46 UTC, kmpoppe approved these changes

2019-12-06 10:46 UTC, merged