Add Equifax
2factorauth/twofactorauth pull request #4247
Opened 2019-10-31 19:34 UTC by phallobst

Fixes #4083
Alexa rank: 9,390

2020-04-12 00:40 UTC, Carlgo11 commented
I can't connect to the website so I'm unable to review the PR 😒

2020-04-12 03:02 UTC, jamcat22 requested changes

2020-04-12 03:02 UTC, jamcat22 commented on _data/finance.yml
> +    twitter: EquifaxInsights
```suggestion
    twitter: AskEquifax
```
I'd suggest switching to their consumer customer support Twitter username.

2020-04-12 07:42 UTC, jamcat22 approved these changes

2020-05-29 19:32 UTC, Carlgo11 approved these changes
Still unable to visit the site but if @jamcat22 approved it I guess it works in the U.S. 🤷‍♂️

2020-05-29 19:32 UTC, merged