Add ViaBTC
2factorauth/twofactorauth pull request #4259
Opened 2019-11-02 13:46 UTC by dleshem

Alexa rank: [25,077](https://www.alexa.com/siteinfo/viabtc.com)

2019-11-06 23:35 UTC, Carlgo11 requested changes

2019-11-06 23:35 UTC, Carlgo11 commented on _data/cryptocurrencies.yml
> +    doc: https://support.viabtc.com/hc/en-us/articles/360016173751-What-is-two-factor-authentication-What-can-it-do-
```suggestion
    doc: https://support.viabtc.com/hc/en-us/articles/360016173751
```

2019-11-20 08:49 UTC, Carlgo11 requested changes
Try this image instead. It's a bit smaller and transparent.
![viabtc.png](https://user-images.githubusercontent.com/3535780/69223043-e7bc1480-0b7a-11ea-8741-9403b5d3d77b.png)

2019-11-21 05:57 UTC, Carlgo11 approved these changes

2019-11-21 06:24 UTC, kmpoppe approved these changes

2019-11-21 06:24 UTC, merged