Add BlockFi
2factorauth/twofactorauth pull request #4269
Opened 2019-11-04 08:16 UTC by dleshem

Alexa rank: [78,461](https://www.alexa.com/siteinfo/blockfi.com)

2019-11-04 23:30 UTC, Carlgo11 requested changes
Use this image instead: ![blockfi](https://user-images.githubusercontent.com/3535780/68166691-69992480-ff63-11e9-8178-59c93c52f9dd.png)

2019-11-04 23:30 UTC, Carlgo11 commented on _data/cryptocurrencies.yml
> +      - software
```suggestion
      - totp
```

2019-11-06 00:24 UTC, Carlgo11 approved these changes

2019-11-09 05:29 UTC, kmpoppe approved these changes

2019-11-09 05:29 UTC, merged