Add Ameriprise Financial
2factorauth/twofactorauth pull request #4279
Opened 2019-11-07 22:59 UTC by Rfosu2k2

Fixes #4077

I did find this while investigating, and they appear to have OTP.  Without having an account I can't verify  if it's sms/email/phone.

https://www.ameriprise.com/privacy-security-fraud/how-we-protect-information/#04

2019-11-09 07:06 UTC, kmpoppe commented
I'll contact them about what "one-time passcodes" means and how you set them up.

2019-11-28 18:58 UTC, Carlgo11 requested changes

2019-11-28 18:58 UTC, Carlgo11 commented on _data/banking.yml
> +    email_address: anti.fraud@ampf.com
I don't think the Anti Fraud department is the correct place to contact for this.
```suggestion
```

2020-02-14 21:49 UTC, phallobst commented
It seems to be SMS 2FA according to https://www.ameriprise.com/privacy-security-fraud/how-we-protect-information/#02
> Each time you log in to the secure site on ameriprise.com, we'll send a verification code, to your enrolled phone number, that you will enter along with your password.

2020-05-30 00:33 UTC, Carlgo11 requested changes

2020-05-30 00:33 UTC, Carlgo11 commented on _data/banking.yml
> +    facebook: ameriprise
```suggestion
    facebook: Ameriprise
```

2020-05-30 00:35 UTC, Carlgo11 approved these changes

2020-05-30 15:10 UTC, phallobst commented
Either the branch is corrupted or the _workflow_ check is not correct, @Carlgo11.

Besides, this entry should probably be changed to show 2FA support via SMS (see my [comment](https://github.com/2factorauth/twofactorauth/pull/4279#issuecomment-586486433)).

2020-09-18 00:07 UTC, Carlgo11 commented
@phallobst author seems gone. Want to make a new PR with the changes you requested?

2020-09-18 01:22 UTC, Rfosu2k2 commented
> @phallobst author seems gone. Want to make a new PR with the changes you requested?

Still here, just not active much these days.  Feel free to reopen as new, and close this.  Thanks for keeping things progressing "@everyone"

2020-09-18 06:14 UTC, phallobst commented
> @phallobst author seems gone. Want to make a new PR with the changes you requested?

Done - see #4960

2020-09-18 06:14 UTC, closed without merging