Add Contentful
2factorauth/twofactorauth pull request #4283
Opened 2019-11-08 14:02 UTC by jpawlyn

Alexa rank: 13,196

2019-11-08 15:15 UTC, raza approved these changes

2019-11-14 17:03 UTC, Carlgo11 requested changes

2019-11-14 17:03 UTC, Carlgo11 commented on _data/other.yml
> +      - software
```suggestion
      - totp
```

2019-11-14 18:26 UTC, Carlgo11 approved these changes

2019-11-15 15:48 UTC, kmpoppe approved these changes

2019-11-15 15:48 UTC, merged