Move Other/Wikia to Social/Fandom
2factorauth/twofactorauth pull request #4290
Opened 2019-11-09 15:28 UTC by phallobst

[Wikia](https://wikia.com) redirects to [Fandom](https://fandom.com/explore)

2019-11-11 08:59 UTC, Carlgo11 requested changes
I don't think Fandom should be in the social media category.

2019-11-11 09:03 UTC, phallobst commented
The category is called "Social", not "Social Media", so I think it fits. The argument is the same as for [Wikipedia](https://github.com/2factorauth/twofactorauth/pull/4286#issuecomment-552074433).

2020-08-06 07:31 UTC, kmpoppe approved these changes

2020-08-31 23:51 UTC, jamcat22 commented
Closing since the rebranding part is addressed in #4869. If we move Wikipedia in #4286, then we can also move FANDOM as well. If this PR switches to just moving FANDOM, feel free to reopen it @phallobst.

2020-08-31 23:51 UTC, closed without merging