Update Registro.br documentation URL
2factorauth/twofactorauth pull request #4302
Opened 2019-11-12 18:58 UTC by hkkobayashi

URL changed after website refactoring.

2019-11-13 01:14 UTC, Carlgo11 requested changes

2019-11-13 01:14 UTC, Carlgo11 commented on _data/domains.yml
>        - hardware
Remove these old 2fa solutions.

2019-11-13 13:47 UTC, hkkobayashi commented on _data/domains.yml
>        - hardware
Removed.

2019-11-13 17:12 UTC, Carlgo11 approved these changes
Thank you!

2019-11-15 15:45 UTC, kmpoppe approved these changes

2019-11-15 15:45 UTC, merged