Update JetBrains
2factorauth/twofactorauth pull request #4307
Opened 2019-11-14 19:44 UTC by spodin

<img width="608" alt="Screen Shot 2019-11-14 at 21 43 14" src="https://user-images.githubusercontent.com/8811713/68890623-ef695c80-0727-11ea-8ec4-43c00d245e1d.png">

2019-11-14 19:57 UTC, Carlgo11 requested changes

2019-11-14 19:57 UTC, Carlgo11 commented on _data/developer.yml
> +      - software
```suggestion
      - totp
```

2019-11-14 21:32 UTC, Carlgo11 approved these changes

2019-11-15 15:40 UTC, kmpoppe approved these changes

2019-11-15 15:40 UTC, merged