updated GOG help URL
2factorauth/twofactorauth pull request #4330
Opened 2019-11-21 14:52 UTC by trockenasche

Old URL link to 404.

2019-11-21 15:32 UTC, kmpoppe requested changes
See inline comment please :-)

2019-11-21 15:32 UTC, kmpoppe commented on _data/gaming.yml
> +    doc: https://support.gog.com/hc/en-us/articles/115003660533-What-is-two-step-login-and-how-does-it-work-
```suggestion
    doc: https://support.gog.com/hc/en-us/articles/115003660533
```
For HelpCenter URLs we do not need the slug after the ID.

2019-11-21 20:55 UTC, Carlgo11 approved these changes

2019-11-22 07:18 UTC, Carlgo11 approved these changes

2019-11-26 02:09 UTC, kmpoppe approved these changes

2019-11-26 02:10 UTC, merged