Update CIBC
2factorauth/twofactorauth pull request #4343
Opened 2019-11-24 19:40 UTC by phallobst

2019-11-25 14:08 UTC, Carlgo11 commented
> Sign on from a different location

That's the only mention of the verification process being required when logging in.
The wording makes me skeptic to if it's really 2FA or 2SV 🤔 

If they said "Sign on from a different device" it'd be like most banking sites on our list classified as supporting 2FA but "location" makes me think it might be based on geo ip data or ip-address based which I wouldn't say can be classified as 2FA.

2019-11-25 16:49 UTC, phallobst commented
On the [doc page](https://www.cibc.com/en/privacy-security/two-step-verification-b.html), it says right under the top picure:
> Starting November 6, you will not be able to sign on if you have not set up your account to receive one-time verification codes.

That sounds like 2FA is mandatory for signing (logging) in. Whether they use cookies to determine that you use a trusted device/browser should not be of our concern, I think.
It would be very surprising for me if they actually used geo location data, but if we really want be sure, either someone with a CIBC account or their support would have to clarify.

2020-03-24 23:41 UTC, Carlgo11 approved these changes

2020-03-25 04:03 UTC, jamcat22 requested changes

2020-03-25 04:03 UTC, jamcat22 commented on _data/banking.yml
>      url: https://www.cibc.ca
```suggestion
    url: https://www.cibc.com
```
Permanent redirect, even from Canadian IPs.

2020-03-25 07:39 UTC, jamcat22 approved these changes

2020-03-25 07:53 UTC, jamcat22 commented
Twitter handle check issue already resolved in #4478.

2020-03-25 07:53 UTC, merged