Change Questrade
2factorauth/twofactorauth pull request #4392
Opened 2019-12-08 09:59 UTC by obscurans

2019-12-10 02:44 UTC, Carlgo11 requested changes

2019-12-10 02:44 UTC, Carlgo11 commented on _data/investing.yml
> +    exception: "SMS must be used as primary, and email must be used as secondary. SMS number and email must be the ones on the account profile."
```suggestion
```

2019-12-10 02:44 UTC, Carlgo11 commented on _data/investing.yml
>        - email
Thanks for the doc link! If email 2FA only is used as a backup method then it shouldn't be listed here at all.
```suggestion
```

2019-12-10 19:03 UTC, Carlgo11 approved these changes

2019-12-11 18:03 UTC, kmpoppe approved these changes

2019-12-11 18:03 UTC, merged