Hrblock
2factorauth/twofactorauth pull request #4416
Opened 2019-12-15 17:10 UTC by legoguy1000

Adding H&R Block

2019-12-29 17:40 UTC, Carlgo11 commented
Thanks for the pull request!

I see that you haven't add any documentation link. Could you maybe find one that describes how to enable 2FA on the site?

If no documentation is available or you can't find it, could you please add some screenshots of the 2FA setup process and/or login process?
__Remember to blur or crop out any personal information linked to you.__

You can attach the screenshots here in a comment, like this:
![screenshot](https://user-images.githubusercontent.com/3535780/62257740-32b4ef00-b407-11e9-8f35-fc7c47ad72fb.gif)

2019-12-29 18:02 UTC, legoguy1000 commented
This is the only documentation I could find which doesn't really help,  https://www.hrblock.com/tax-center/support/online/technical-issues-online/hr-block-security-code/, I've uploaded screenshots below.

![image](https://user-images.githubusercontent.com/13125104/71560710-18715280-2a33-11ea-848a-a66dd18e5a7b.png)
![image](https://user-images.githubusercontent.com/13125104/71560688-c6c8c800-2a32-11ea-91f8-2fd640107a87.png)
![image](https://user-images.githubusercontent.com/13125104/71560698-dcd68880-2a32-11ea-9bcd-3c07f69f74a7.png)

2019-12-29 18:12 UTC, Carlgo11 requested changes
Based on the screenshots you provided I'd say these are the correct 2fa methods to list.

2019-12-29 18:12 UTC, Carlgo11 commented on _data/finance.yml
> +      - sms
```suggestion
```

2019-12-29 18:12 UTC, Carlgo11 commented on _data/finance.yml
> +      - software
```suggestion
      - totp
```

2019-12-29 18:17 UTC, legoguy1000 commented
I updated the PR with the changes.  I know in the past I had used SMS to get the code but they may have removed that since.

2019-12-29 18:20 UTC, Carlgo11 approved these changes

2020-01-05 08:12 UTC, Jawshy approved these changes

2020-01-05 08:13 UTC, merged