Update "software" method in Identity Management
2factorauth/twofactorauth pull request #4427
Opened 2019-12-15 19:04 UTC by phallobst

See #4410

2019-12-17 20:03 UTC, Carlgo11 requested changes

2019-12-17 20:03 UTC, Carlgo11 commented on _data/identity.yml
>        - hardware
```suggestion
      - u2f
```

2019-12-17 20:03 UTC, Carlgo11 commented on _data/identity.yml
> +      - hardware
```suggestion
      - u2f
```

2019-12-17 20:03 UTC, Carlgo11 commented on _data/identity.yml
> +      - totp
I can't find anything about totp support other than that their proprietary app "CENTRIFY MOBILE APP" does MFA using TOTP codes and push notifications.

2019-12-17 20:46 UTC, phallobst commented on _data/identity.yml
> +      - hardware
see below

2019-12-17 20:46 UTC, phallobst commented on _data/identity.yml
> +      - totp
see below

2019-12-17 20:47 UTC, phallobst commented
I changed the Centrify doc and updated the tfa section accordingly.

2019-12-18 00:33 UTC, Carlgo11 requested changes

2019-12-18 00:33 UTC, Carlgo11 commented on _data/identity.yml
> +      - totp
```suggestion
```

2019-12-18 08:15 UTC, phallobst commented on _data/identity.yml
> +      - totp
I'm not sure. The doc says:
> OATH Tokens such as managed by Google Authenticator...

This means TOTP, doesn't it?

2019-12-19 01:29 UTC, Carlgo11 approved these changes

2020-01-12 02:56 UTC, Jawshy approved these changes
All sites with documentation ✅

2020-01-12 14:05 UTC, phallobst commented
Okay, what happened here? I just merged _master_ to get the "workflow" check running again, and now there are changes all over the place... I must have messed up something.

Shall I close this PR and open a new one with just the "identity.yml" file?

2020-01-12 18:42 UTC, closed without merging