Update "software" method in Retail
2factorauth/twofactorauth pull request #4428
Opened 2019-12-15 19:05 UTC by phallobst

See #4410

Mercado Libre (in Spanish) must still be checked

2019-12-18 00:43 UTC, Carlgo11 requested changes

2019-12-18 00:43 UTC, Carlgo11 commented on _data/retail.yml
>      doc: https://ayuda.mercadolibre.com.ar/ayuda/Consejos-para-fortalecer-la-se_961
Link no longer works but I can confirm that they use Authy.
```suggestion
```

2019-12-19 01:36 UTC, Carlgo11 approved these changes

2020-01-07 14:06 UTC, Jawshy approved these changes
All English sites checked ✅

2020-01-07 14:06 UTC, merged