Update "software" method in Social
2factorauth/twofactorauth pull request #4429
Opened 2019-12-15 19:05 UTC by phallobst

See #4410

Wykop (in Polish) must still be checked

2019-12-18 01:03 UTC, Carlgo11 requested changes

2019-12-18 01:03 UTC, Carlgo11 commented on _data/social.yml
>      doc: https://vk.com/page-59800369_47885415
```suggestion
    doc: https://vk.com/page-777107_53677752
```

2019-12-18 01:05 UTC, Carlgo11 commented
Let's remove the Wykop listing. I can't find anything about 2FA, registration requires a Polish number and their contact info is only in Polish (with a whois email that goes to Cyprus).

2019-12-18 09:02 UTC, phallobst commented
I dug a little bit deeper... The Polish fork of 2FA at https://dwa-skladniki.pl/ has this as the doc:
> https://www.wykop.pl/wpis/24198791/wykopowicze-na-waszych-profilach-w-ustawieniach-ko/

I sounds like it's totp, since there are mentions of freeOTP and Authy. Shall we go for it?

2019-12-22 20:05 UTC, Carlgo11 approved these changes

2020-01-12 02:28 UTC, Jawshy approved these changes
All English sites ✅

2020-01-12 02:49 UTC, merged