Update "software" method in Education
2factorauth/twofactorauth pull request #4439
Opened 2019-12-17 14:44 UTC by phallobst

See #4410

2020-01-05 00:58 UTC, Carlgo11 requested changes

2020-01-05 00:58 UTC, Carlgo11 commented on _data/education.yml
>        - hardware
```suggestion
      - u2f
```

2020-01-05 00:58 UTC, Carlgo11 commented on _data/education.yml
>        - hardware
```suggestion
      - u2f
```

2020-01-05 00:58 UTC, Carlgo11 commented on _data/education.yml
>        - hardware
```suggestion
      - u2f
```

2020-01-05 00:58 UTC, Carlgo11 commented on _data/education.yml
>        - hardware
```suggestion
      - u2f
```

2020-01-05 00:58 UTC, Carlgo11 commented on _data/education.yml
>        - hardware
```suggestion
      - u2f
```

2020-01-05 00:58 UTC, Carlgo11 commented on _data/education.yml
>        - hardware
```suggestion
      - u2f
```

2020-01-05 01:09 UTC, Carlgo11 commented
I have no idea how the Halifax Bank Twitter handle suddenly starts blocking the build 😕

2020-01-05 01:13 UTC, Carlgo11 commented
Updating the branch seems to have worked 🤷‍♂

2020-01-05 01:13 UTC, Carlgo11 approved these changes

2020-01-11 06:35 UTC, Jawshy approved these changes
All English websites ✅

2020-01-11 06:45 UTC, merged