Update "software" method in Betting
2factorauth/twofactorauth pull request #4445
Opened 2019-12-18 09:52 UTC by phallobst

See #4410

2020-01-05 01:15 UTC, Carlgo11 requested changes

2020-01-05 01:15 UTC, Carlgo11 commented on _data/betting.yml
> +    doc: https://github.com/2factorauth/twofactorauth/pull/3726#issuecomment-482496615
```suggestion
```

2020-01-05 01:18 UTC, Carlgo11 approved these changes

2020-01-07 14:09 UTC, Jawshy commented
> It appears you are accessing our website from a prohibited location.

What location do you need to appear to be from in order to access their site?

2020-01-07 17:30 UTC, phallobst commented
The list of restricted territories for BetVictor has 190 entries (yep, no kidding):
* https://help.betvictor.com/portal/articles/4363
* Google cache: https://webcache.googleusercontent.com/search?q=cache:https://help.betvictor.com/portal/articles/4363

Australia is on there as well, so that's probably why you are blocked, @Jawshy.

2020-01-08 12:54 UTC, Jawshy approved these changes

2020-01-08 12:54 UTC, merged