Add Techniker Krankenkasse
2factorauth/twofactorauth pull request #4456
Opened 2019-12-20 19:53 UTC by phallobst

2020-06-26 09:22 UTC, wackerm approved these changes

2020-06-26 09:27 UTC, wackerm approved these changes

2020-06-26 09:27 UTC, wackerm commented on _data/finance.yml
> +
i am not sure, if "finance" is the correct category, since "Krankenkasse" means health care...

2020-07-07 20:45 UTC, Carlgo11 requested changes

2020-07-07 20:45 UTC, Carlgo11 commented on _data/finance.yml
> +    doc: https://www.tk.de/techniker/unternehmensseiten/unternehmen/die-tk-app/tk-app-sicherheitskonzept-2023678
```suggestion
    doc: https://www.tk.de/techniker/unternehmensseiten/unternehmen/die-tk-app/2023678
```

2020-07-07 20:45 UTC, Carlgo11 approved these changes

2020-07-07 20:52 UTC, Carlgo11 commented
Just outdated test. The PR looks fine :+1:

2020-11-01 17:37 UTC, kmpoppe approved these changes

2020-11-01 17:37 UTC, merged