Rename Incapsula to Imperva
2factorauth/twofactorauth pull request #4472
Opened 2019-12-28 17:52 UTC by phallobst

2019-12-29 17:29 UTC, Carlgo11 requested changes

2019-12-29 17:29 UTC, Carlgo11 commented on _data/domains.yml
>        - software
```suggestion
      - totp
```

2019-12-29 17:30 UTC, Carlgo11 commented
Changing the name will probably mean a merge conflict with your other domain PRs either way so let's just change the software 2fa to totp.

2019-12-29 17:35 UTC, Carlgo11 approved these changes

2019-12-29 17:35 UTC, Carlgo11 commented
Thanks @phallobst!
I tried to commit the change myself but GitHub wouldn't let me 🙄

2020-01-04 22:59 UTC, kmpoppe approved these changes

2020-01-04 22:59 UTC, merged