Add APMEX (apmex.com) to the investing category.
2factorauth/twofactorauth pull request #4480
Opened 2019-12-29 23:05 UTC by ItsMattL

Add APMEX (apmex.com) to the investing category.

APMEX is a major precious metals dealer. Their website currently does not support 2FA.

Issue #4036

2020-01-25 08:54 UTC, Jawshy requested changes
@ItsMattL, would you kindly update the icon with this smaller icon? 
![apmex](https://user-images.githubusercontent.com/10876578/73118733-00b4bd80-3f50-11ea-9b9d-12e91aa3456e.png)
[I tried too](https://github.com/2factorauth/twofactorauth/commit/df9e9ad5c6f653814547721ed7d8f90506662cd2), but the commit isn't recognised in this pull request.

2020-03-16 01:36 UTC, ItsMattL commented
Changes made

2020-03-17 07:23 UTC, phallobst approved these changes

2020-03-18 09:38 UTC, Jawshy approved these changes

2020-03-18 09:38 UTC, merged