Updating Bitdefender to add TFA
2factorauth/twofactorauth pull request #4490
Opened 2020-01-02 18:37 UTC by ilovecats516

2020-01-03 23:08 UTC, Carlgo11 requested changes

2020-01-03 23:08 UTC, Carlgo11 commented on _data/security.yml
> +      - software
```suggestion
      - totp
```

2020-01-03 23:18 UTC, Carlgo11 approved these changes

2020-01-04 22:54 UTC, kmpoppe approved these changes

2020-01-04 22:54 UTC, merged