Adding Canva
2factorauth/twofactorauth pull request #4493
Opened 2020-01-03 22:53 UTC by ilovecats516

2020-01-06 17:36 UTC, phallobst commented
According to https://support.canva.com/account-basics/security/keep-your-account-secure/ there is basic support for 2FA, with more to come. I think SMS should be listed together with an exception text ("only Australia"), or at least include a `status` line with this link.

2020-01-09 00:54 UTC, ilovecats516 commented
@phallobst I've updated the pull request, thank you.

2020-01-09 01:24 UTC, Carlgo11 requested changes

2020-01-09 01:24 UTC, Carlgo11 commented on _data/other.yml
> +    exception: "2FA only for Australian customers."
```suggestion
    exception: "2FA only available for Australian customers."
```

2020-01-09 01:26 UTC, Carlgo11 approved these changes

2020-01-19 08:23 UTC, kmpoppe approved these changes

2020-01-19 08:23 UTC, merged