Added elmah.io
2factorauth/twofactorauth pull request #4498
Opened 2020-01-06 07:52 UTC by ThomasArdal

2020-01-06 12:02 UTC, Carlgo11 requested changes

2020-01-06 12:02 UTC, Carlgo11 commented on _data/developer.yml
> +      - software
```suggestion
      - totp
```

2020-01-06 13:37 UTC, Carlgo11 approved these changes

2020-01-09 09:13 UTC, ThomasArdal commented
Are you missing anything from me or do you wait with merging until you release a new version of the site?

2020-01-09 11:30 UTC, Carlgo11 commented
Two approvals are needed to merge so we’re just waiting for another maintainer to look at this PR before it can be merged.

2020-01-19 08:03 UTC, kmpoppe approved these changes

2020-01-19 08:03 UTC, merged