NexusMod link updated
2factorauth/twofactorauth pull request #4501
Opened 2020-01-06 20:29 UTC by apollo2k4

Nexusmod enable software tokens

2020-01-06 20:39 UTC, Carlgo11 requested changes
Please revert the doc link change. They both work but the old one is shorter.

2020-01-06 20:49 UTC, apollo2k4 commented
Revert to the old link. Thanks for the comment.

2020-01-07 04:25 UTC, Carlgo11 approved these changes
Thanks!

2020-01-19 08:01 UTC, kmpoppe approved these changes

2020-01-19 08:02 UTC, merged