Update tfa support for clearscore
2factorauth/twofactorauth pull request #4508
Opened 2020-01-11 11:51 UTC by poisonadder1

Clearscore has added support for sms based 2fa.

2020-01-11 22:40 UTC, Carlgo11 requested changes

2020-01-11 22:40 UTC, Carlgo11 commented on _data/finance.yml
> +    doc: https://help.clearscore.com/hc/en-us/articles/360010189440-About-two-factor-authentication
```suggestion
    doc: https://help.clearscore.com/hc/en-us/sections/360003360940
```

2020-01-11 22:40 UTC, Carlgo11 commented
The documentation doesn't mention what kind of 2FA they support. Are you sure they only use SMS based 2FA?

2020-01-19 17:19 UTC, poisonadder1 commented
> The documentation doesn't mention what kind of 2FA they support. Are you sure they only use SMS based 2FA?

As far as I've been able to tell.

2020-01-25 01:43 UTC, Jawshy approved these changes
@Carlgo11 see [What happens after I’ve enabled Two-Factor Authentication (2FA)?](https://help.clearscore.com/hc/en-us/articles/360011124640-What-happens-after-I-ve-enabled-Two-Factor-Authentication-2FA-) 

> If you log in on a new device (or not actively logged in on your app), you’ll need to enter your email and password and the verification code will be sent to you via text as you’ve enabled 2FA.

2020-01-25 01:43 UTC, Carlgo11 approved these changes

2020-01-25 01:44 UTC, merged