Update Backblaze
2factorauth/twofactorauth pull request #4526
Opened 2020-01-12 02:42 UTC by djfredalert

Blackblaze lets you turn off SMS as a back-up option.

<img width="593" alt="Backblaze Screenshot" src="https://user-images.githubusercontent.com/58055115/72213335-12747a80-34e5-11ea-9f4f-b1b5d692e2d7.png">

2020-01-13 15:33 UTC, Carlgo11 requested changes

2020-01-13 15:33 UTC, Carlgo11 commented on _data/backup.yml
> +    exception: "SMS is required to set up 2FA."
Standard phrasing for these kinds of exceptions. See Yandex etc.
```suggestion
    exception: "SMS-capable phone required for initial setup."
```

2020-01-13 17:47 UTC, Carlgo11 approved these changes

2020-01-18 20:02 UTC, kmpoppe approved these changes

2020-01-18 20:02 UTC, merged