Update ConEd
2factorauth/twofactorauth pull request #4527
Opened 2020-01-12 03:20 UTC by djfredalert

- the documentation link was broken; what I found is not ideal but I couldn't find anything else
- 2FA can be bypassed by customer service

2020-01-12 10:39 UTC, phallobst commented
Does the phrase "Can be bypassed by customer support." really merit to be an exception here? I'm aware that it opens up social engineering options, but having the support helping the user to log in would apply to quite a number of sites, I guess.

2020-01-12 16:01 UTC, djfredalert commented
> Does the phrase "Can be bypassed by customer support." really merit to be an exception here? I'm aware that it opens up social engineering options, but having the support helping the user to log in would apply to quite a number of sites, I guess.

I think that's a fair point. Con Ed states it explicitly during the login process which is why I thought it was warranted here, if not elsewhere.

2020-01-13 15:29 UTC, Carlgo11 requested changes

2020-01-13 15:29 UTC, Carlgo11 commented on _data/utilities.yml
> +    exception: "Requires phone # to set up. Can be bypassed by customer support."
Proper English without slang is preferred when writing exceptions. That way more people and translation services can understand it.
```suggestion
    exception: "Requires phone number to set up. Can be bypassed by customer support." 
```

2020-01-13 17:47 UTC, Carlgo11 approved these changes

2020-01-18 19:58 UTC, kmpoppe approved these changes

2020-01-18 19:58 UTC, merged