Update Tresorit
2factorauth/twofactorauth pull request #4528
Opened 2020-01-12 03:29 UTC by djfredalert

Tresorit requires enabling at least two methods.

2020-01-12 10:44 UTC, phallobst commented
According to the doc page, this is not actually required. It says
> If you have multiple verification methods set up, ...
> ...if you set up a secondary option as a backup.

Is the documentation out of date, i.e. do you have first-hand information here?

2020-01-12 16:05 UTC, djfredalert commented
> According to the doc page, this is not actually required. It says
> 
> > If you have multiple verification methods set up, ...
> > ...if you set up a secondary option as a backup.
> 
> Is the documentation out of date, i.e. do you have first-hand information here?

@phallobst It's actually in the documentation, albeit hard to spot: It's actually in the documentation, albeit hard to spot: [https://support.tresorit.com/hc/article_attachments/360003584614/primary_2x.gif](https://support.tresorit.com/hc/article_attachments/360003584614/primary_2x.gif)

2020-01-12 16:08 UTC, phallobst commented
I did see that, but it's still contradicting the text. Either the text or the GIF is out of date, I guess.

2020-01-12 16:19 UTC, djfredalert commented
The text is out-of-date. I have a Tresorit account and confirmed two are required.

2020-01-13 15:30 UTC, Carlgo11 requested changes

2020-01-13 15:30 UTC, Carlgo11 commented on _data/backup.yml
> +    exception: Requires enabling at least two methods.
```suggestion
    exception: "Requires enabling at least two 2FA methods."
```

2020-01-17 18:46 UTC, Carlgo11 approved these changes

2020-01-18 19:57 UTC, kmpoppe approved these changes

2020-01-18 19:57 UTC, merged