Fasthosts has enabled 2FA and is rolling out to all existing customers
2factorauth/twofactorauth pull request #4560
Opened 2020-01-27 12:30 UTC by gretheridgefh

2020-01-27 15:48 UTC, Carlgo11 requested changes
Use this image instead:
![fasthosts](https://user-images.githubusercontent.com/3535780/73189556-e08a2780-4124-11ea-85f6-356b526aad46.png)

2020-01-27 17:12 UTC, gretheridgefh commented
logo updated as requested.

2020-01-28 02:58 UTC, Carlgo11 approved these changes

2020-02-04 13:11 UTC, Jawshy approved these changes

2020-02-04 13:11 UTC, merged