Add Experian Ltd
2factorauth/twofactorauth pull request #4569
Opened 2020-02-02 18:37 UTC by gazelle-24

Experian Ltd is credit monitoring service. Not documented, but they support 2FA codes via SMS and phone calls (https://i.imgur.com/K0QUZ0t.png).

2020-02-05 12:15 UTC, Carlgo11 requested changes
I suggest you use this image instead https://expcdn.co.uk/www/images/icon-32x32.png

2020-02-05 20:16 UTC, gazelle-24 commented
> 
> 
> I suggest you use this image instead https://expcdn.co.uk/www/images/icon-32x32.png

Sorry about that, that image is better, have replaced it.

2020-02-18 16:13 UTC, Carlgo11 approved these changes

2020-02-18 19:15 UTC, phallobst approved these changes

2020-02-18 19:15 UTC, merged