Add Aetna
2factorauth/twofactorauth pull request #4573
Opened 2020-02-05 16:14 UTC by miamimanni

2020-02-06 00:23 UTC, Carlgo11 requested changes
The health category is for health apps and services. Insurance is supposed to be in the finance category.

2020-02-06 15:08 UTC, miamimanni commented
> The health category is for health apps and services. Insurance is supposed to be in the finance category.

Ah gotcha! Fixed

2020-02-06 19:48 UTC, Carlgo11 approved these changes

2020-02-10 04:22 UTC, Jawshy approved these changes

2020-02-10 11:35 UTC, merged