Add Todo Pago (AR)
2factorauth/twofactorauth pull request #4613
Opened 2020-02-18 13:46 UTC by fainpablo

2020-02-18 16:04 UTC, Carlgo11 requested changes

2020-02-18 16:04 UTC, Carlgo11 commented on _data/payments.yml
> +    url: https://portal.todopago.com.ar/
This seems to be the main page.
```suggestion
    url: https://todopago.com.ar/
```

2020-02-19 00:57 UTC, Carlgo11 approved these changes

2020-02-19 18:56 UTC, phallobst approved these changes

2020-02-19 18:56 UTC, merged