Add Visa Argentina
2factorauth/twofactorauth pull request #4614
Opened 2020-02-18 21:54 UTC by fainpablo

2020-02-18 21:57 UTC, phallobst commented
Visa should rather go into "Payments".

2020-02-18 22:03 UTC, fainpablo commented
I thought the same, but why AMEX is in the "Banking" category?

2020-02-18 22:22 UTC, fainpablo commented
I thought the same, but AMEX in the "Banking" category got me confused.

2020-02-19 01:19 UTC, Carlgo11 requested changes
AmEx was added back in 2014 (#38) when there was only one category. My guess is that it got moved to the bank category because there wasn't any payments category yet and no one have thought about it since that.

Please move Visa to the payments section.

2020-02-19 14:52 UTC, fainpablo commented
Makes sense. I've just moved Visa to payments. Will submit a new PR to update AMEX.

2020-02-19 18:59 UTC, phallobst requested changes

2020-02-19 18:59 UTC, phallobst commented on _data/payments.yml
> +    twitter: VisaArgentina
```suggestion
    twitter: VisaArgentina
    lang: es
```

2020-02-19 19:29 UTC, phallobst approved these changes

2020-02-26 07:23 UTC, Carlgo11 approved these changes
I approve your visa!

2020-02-26 07:23 UTC, merged