Add MasterCard Argentina
2factorauth/twofactorauth pull request #4615
Opened 2020-02-18 22:01 UTC by fainpablo

2020-02-19 13:27 UTC, phallobst commented
This one should go into "Payments" as well.

2020-02-19 14:56 UTC, fainpablo commented
Moved, thanks.

2020-02-19 18:59 UTC, Carlgo11 commented
Is it just me or is there no login button?

2020-02-19 19:02 UTC, phallobst requested changes

2020-02-19 19:02 UTC, phallobst commented on _data/payments.yml
> +    facebook: MastercardArgentina
```suggestion
    facebook: MastercardArgentina
    lang: es
```

2020-02-19 19:06 UTC, phallobst commented
Login is in the top right hand corner:
![image](https://user-images.githubusercontent.com/520841/74866490-3c765380-5353-11ea-9bd8-665fb3359b73.png)

2020-02-19 19:21 UTC, fainpablo commented
> Is it just me or is there no login button?

Top right corner. "Acceda a sus cuentas on-line" and then you have to select the type of customer you are.


<img width="331" alt="Screen Shot 2020-02-19 at 16 21 12" src="https://user-images.githubusercontent.com/17606465/74867681-dfb77080-5333-11ea-970b-ccd30d5ae80c.png">

2020-02-19 19:22 UTC, Carlgo11 commented
And what can you do when logged in?

2020-02-19 19:27 UTC, fainpablo commented
> And what can you do when logged in?

You can manage your credit cards no matter which bank has issued them. Issue a new plastic, request cards for additional holders, cancel your card, pay bills, etc. Same as Visa Argentina.

2020-02-19 22:01 UTC, phallobst approved these changes

2020-02-22 17:20 UTC, Carlgo11 approved these changes

2020-02-22 17:20 UTC, merged