Add ANSES (AR)
2factorauth/twofactorauth pull request #4617
Opened 2020-02-19 15:59 UTC by fainpablo

Social Security government site.

2020-02-19 19:04 UTC, phallobst requested changes

2020-02-19 19:04 UTC, phallobst commented on _data/government.yml
> +    facebook: ansesgob
```suggestion
    facebook: ansesgob
    lang: es
```

2020-02-19 19:17 UTC, fainpablo commented
Thanks for noticing the missing tag @phallobst !

2020-02-23 15:41 UTC, phallobst approved these changes

2020-03-08 18:41 UTC, fainpablo commented
Is there any outstanding concern here @phallobst or are we good?

2020-03-08 18:43 UTC, phallobst commented
I already approved this PR two weeks ago, we just need a second reviewer here.

2020-03-23 14:03 UTC, Carlgo11 approved these changes

2020-03-23 14:03 UTC, merged