Add MediaMarkt
2factorauth/twofactorauth pull request #4620
Opened 2020-02-19 19:51 UTC by phallobst

2020-02-21 04:35 UTC, Carlgo11 requested changes

2020-02-21 04:35 UTC, Carlgo11 commented on _data/retail.yml
> +  - name: MediaMarkt
MediaMarkt operates in several countries. Please specify the country in some way. (Germany/Deutschland etc)

2020-02-22 17:18 UTC, Carlgo11 approved these changes

2020-02-24 22:37 UTC, jamcat22 approved these changes

2020-02-24 22:37 UTC, merged