Add eToro
2factorauth/twofactorauth pull request #4621
Opened 2020-02-19 19:55 UTC by fainpablo

2020-02-20 20:13 UTC, phallobst commented
This icon is used as their favicon, and looks better to me:
![etoro](https://user-images.githubusercontent.com/520841/74974463-98111180-5425-11ea-976c-61ba3cad4787.png)

2020-02-20 23:34 UTC, fainpablo commented
I usually try to get the same logo they use on social media, but this one definitely looks better.

2020-02-21 04:10 UTC, Carlgo11 requested changes

2020-02-21 04:10 UTC, Carlgo11 commented on _data/investing.yml
> +    doc: https://www.etoro.com/en-us/customer-service/help/1281239912/how-can-i-make-my-account-more-secure/
```suggestion
    doc: https://www.etoro.com/en-us/customer-service/help/1281239912/-
```

2020-02-21 16:53 UTC, phallobst approved these changes

2020-02-22 03:03 UTC, Carlgo11 approved these changes

2020-02-22 03:03 UTC, merged