Add Stash
2factorauth/twofactorauth pull request #4626
Opened 2020-02-20 16:32 UTC by phallobst

Closes #4483

2020-02-21 04:19 UTC, Carlgo11 requested changes
This one looks better. It's their favicon.
![stash](https://user-images.githubusercontent.com/3535780/75003808-69b52580-5469-11ea-9a1e-0780c93206a6.png)

2020-02-21 17:12 UTC, phallobst commented
They can't seem to make up their mind. The link to their logo download at https://www.stashinvest.com/newsroom#media-kit uses a gradient - but that one is nowhere to be seen in the media kit... :man_facepalming:

The favicon it is, then.

2020-02-22 03:02 UTC, Carlgo11 approved these changes

2020-02-24 22:37 UTC, jamcat22 approved these changes

2020-02-24 22:37 UTC, merged