Update Engine Yard
2factorauth/twofactorauth pull request #4637
Opened 2020-02-23 08:45 UTC by phallobst

2020-02-23 15:19 UTC, Carlgo11 requested changes

2020-02-23 15:19 UTC, Carlgo11 commented on _data/cloud.yml
> +    doc: https://blog.engineyard.com/engine-yards-two-factor-authentication
That doc link talks more about what 2FA is than how users should enable it. I think this link works better:
```suggestion
    doc: https://support.cloud.engineyard.com/hc/en-us/community/posts/203752678
```

2020-02-23 15:23 UTC, Carlgo11 approved these changes

2020-02-24 23:25 UTC, jamcat22 approved these changes

2020-02-24 23:25 UTC, merged