Update Campfire
2factorauth/twofactorauth pull request #4638
Opened 2020-02-23 08:51 UTC by phallobst

2020-02-23 15:13 UTC, Carlgo11 approved these changes

2020-02-24 22:21 UTC, jamcat22 approved these changes
Both Basecamp and Campfire also support U2F security keys for their shared login system. Updated Basecamp and Campfire entries to reflect this.

2020-02-24 22:58 UTC, Carlgo11 requested changes

2020-02-24 22:58 UTC, Carlgo11 commented on _data/communication.yml
> +    doc: https://3.basecamp-help.com/article/443-two-factor-authentication-2fa
```suggestion
    doc: https://3.basecamp-help.com/article/443--
```

2020-02-24 23:09 UTC, Carlgo11 approved these changes

2020-02-24 23:09 UTC, merged