Update Arcadia
2factorauth/twofactorauth pull request #4660
Opened 2020-02-27 21:51 UTC by phallobst

2020-02-28 03:17 UTC, Carlgo11 requested changes

2020-02-28 03:17 UTC, Carlgo11 commented on _data/utilities.yml
> +    twitter: arcadia
```suggestion
    twitter: arcadia
    facebook: ArcadiaHQ
```

2020-02-28 10:26 UTC, jamcat22 approved these changes

2020-03-23 13:59 UTC, Carlgo11 approved these changes

2020-03-23 13:59 UTC, merged