Add nextcloud
2factorauth/twofactorauth pull request #4662
Opened 2020-02-28 16:00 UTC by domi20

Add nextcloud to Backup section

2020-02-28 16:41 UTC, phallobst requested changes

2020-02-28 16:41 UTC, phallobst commented on _data/backup.yml
> +
```suggestion

```
Just superfluous whitespace...

2020-02-28 16:41 UTC, phallobst commented on _data/backup.yml
> +      - totp
```suggestion
      - totp
      - u2f
```
According to the docs, ` u2f` keys are supported.

2020-02-28 16:41 UTC, phallobst commented on _data/backup.yml
> +
```suggestion

```
Whitespace again

2020-02-28 16:42 UTC, phallobst commented
This image comes straight from their favicon, and looks better in my opinion.
![nextcloud](https://user-images.githubusercontent.com/520841/75567335-a5e01b80-5a51-11ea-9964-b74b79f937f6.png)

2020-02-28 16:57 UTC, phallobst commented
Is this exclusively a self-hosted software package? If that's the case, we cannot include it here unfortunately, based on our [exclusion page](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md#self-hosted-services).

If it's not, maybe we should move it into another category. Being a groupware solution, it fits better in "Communication", I guess.

2020-02-28 17:10 UTC, RichJeanes commented
They have " hosting partners" that you can sign up with, but it is primarily a self-hosted platform.

2020-02-28 17:12 UTC, closed without merging

2020-03-03 09:39 UTC, papaita commented
End