Add Rocket Beans TV (Germany)
2factorauth/twofactorauth pull request #4663
Opened 2020-02-29 12:20 UTC by oliverschloebe

Added rocketbeans.tv. Tested by having an account there using 2FA via *Google Authenticator* app.

2020-02-29 12:31 UTC, phallobst requested changes

2020-02-29 12:31 UTC, phallobst commented on _data/entertainment.yml
> +
```suggestion
    doc: https://forum.rocketbeans.tv/t/35407/31

```

2020-02-29 12:45 UTC, phallobst approved these changes

2020-03-09 03:56 UTC, jamcat22 approved these changes
Thanks @oliverschloebe!

2020-03-09 03:56 UTC, merged