Add Cornell University
2factorauth/twofactorauth pull request #4677
Opened 2020-03-07 21:43 UTC by willbarkoff

2020-03-07 22:02 UTC, phallobst requested changes

2020-03-07 22:02 UTC, phallobst commented on _data/education.yml
> +      - hardware
```suggestion
      - hardware
      - u2f
```

2020-03-07 22:11 UTC, phallobst approved these changes

2020-03-08 02:17 UTC, Carlgo11 approved these changes

2020-03-08 02:17 UTC, merged