Added buda.com crypto site
2factorauth/twofactorauth pull request #4678
Opened 2020-03-09 03:09 UTC by julian-alarcon

Added cryptocurrency buda.com site. Alexa rank is [66,668](https://www.alexa.com/siteinfo/buda.com)

2020-03-09 11:24 UTC, phallobst commented
Please replace the icon with this one:
![buda](https://user-images.githubusercontent.com/520841/76208873-da499980-6200-11ea-99e1-68acb344178a.png)

2020-03-09 11:25 UTC, phallobst requested changes

2020-03-09 11:25 UTC, phallobst commented on _data/cryptocurrencies.yml
> +    doc: https://soporte.buda.com/es/articles/2379080-que-es-la-clave-dinamica-y-como-activarla
```suggestion
    doc: https://soporte.buda.com/es/articles/2379080
```

2020-03-09 22:42 UTC, julian-alarcon commented on _data/cryptocurrencies.yml
> +    doc: https://soporte.buda.com/es/articles/2379080-que-es-la-clave-dinamica-y-como-activarla
Done!

2020-03-09 22:43 UTC, julian-alarcon commented
Done with the suggested changes. Please review it!

2020-03-09 22:48 UTC, phallobst approved these changes

2020-03-23 13:53 UTC, Carlgo11 approved these changes

2020-03-23 13:53 UTC, merged