Update Hootsuite
2factorauth/twofactorauth pull request #4686
Opened 2020-03-09 15:34 UTC by fainpablo

I just noticed that you can click "Skip this step" when asked for TOTP and Hootsuite gives you the option to receive a passphrase on your email.

<img width="1030" alt="Screen Shot 2020-03-09 at 12 30 28" src="https://user-images.githubusercontent.com/17606465/76230244-3365fd00-6202-11ea-9f34-006e5954f6c9.png">

2020-03-09 17:44 UTC, phallobst requested changes

2020-03-09 17:44 UTC, phallobst commented on _data/social.yml
> +    exception: Email is always enabled as backup method for Software Token.
```suggestion
    exception: "Email is always enabled as backup method for Software Token."
```
Quotes are not strictly necessary, but used by convention.

2020-03-09 19:04 UTC, phallobst approved these changes

2020-03-23 13:49 UTC, Carlgo11 approved these changes

2020-03-23 13:49 UTC, merged