Update Name.com
2factorauth/twofactorauth pull request #4687
Opened 2020-03-09 15:41 UTC by fainpablo

While not specified in the documentation, SMS is enabled as a backup method by default. You can opt-out anytime.
<img width="500" alt="Screen Shot 2020-03-09 at 12 36 23" src="https://user-images.githubusercontent.com/17606465/76230869-1c73da80-6203-11ea-9393-6c3d568371f2.png">

<img width="747" alt="Screen Shot 2020-03-09 at 12 37 44" src="https://user-images.githubusercontent.com/17606465/76230957-4200e400-6203-11ea-829d-27aad2838006.png">

2020-03-09 17:26 UTC, phallobst commented
There is actually a documentation page for this: https://www.name.com/support/articles/115013791328

Maybe we should change the doc entry to the "My Account" knowledge base overview page: https://www.name.com/support/categories/200296798

2020-03-09 18:18 UTC, fainpablo commented
> https://www.name.com/support/categories/200296798

The first link you shared has a mention to Google Authenticator, maybe we can use this one?

"Note: This process is dependant upon you having a device already setup. If you have not setup Google Authenticator, please see this guide".

2020-03-09 19:28 UTC, phallobst commented
I'm confused: You mentioned the first link, but quoted the second...

I'd prefer https://www.name.com/support/categories/200296798 since it's probably more stable (being the overview page) and provides links to all relevant info at one go.

2020-03-09 19:32 UTC, fainpablo commented
It wasn't me. I quoted the first link, I swear 🙄

2020-03-09 19:43 UTC, phallobst approved these changes

2020-03-23 13:48 UTC, Carlgo11 commented
@jamcat22 what's our stance on backup methods? Do we list those?

2020-03-25 03:02 UTC, jamcat22 requested changes
@Carlgo11 we typically do not list backup methods, unless they're able to be used as primary methods. So in this case, we would not list SMS as a method, as software is the main method and is required for 2FA, while SMS is only used as a backup method. 2FA can't be turned on using only SMS.

The exception to this is when a service requires a backup method to be added. In that case, we add an exception text stating what other method is required, but unless the method can be used as a main method, it's not selected.

Here are a few examples:
**Name.com**
- Site supports software for 2FA.
- Site allows SMS as an optional backup, but not as the primary method.
- Since SMS can't be used as the main method, and SMS is not required as a backup method, SMS is **NOT** listed as a method and exception text is **NOT** added.

**Yandex**
- Site supports software for 2FA.
- Site allows SMS as a required backup, but not as the primary method.
- Since SMS can't be used as the main method, and SMS is required as a backup method, SMS is **NOT** listed as a method and exception text **IS** added stating that SMS is required to enable 2FA.

**WordPress.com**
- Site supports software for 2FA.
- Site allows SMS as a required backup, or as the primary method.
- Since SMS can be used as the main method, and SMS is required as a backup method, SMS **IS** listed as a method and exception text **IS** added stating that SMS is required to enable 2FA.

**Uber**
- Site supports software for 2FA.
- Site allows SMS as an optional backup, or as the primary method.
- Since SMS can be used as the main method, and SMS is not required as a backup method, SMS **IS** listed as a method and exception text **NOT** added.

2020-03-25 03:03 UTC, jamcat22 commented on _data/domains.yml
> +    doc: https://www.name.com/support/categories/200296798
```suggestion
    doc: https://www.name.com/support/categories/200296798
```

2020-03-29 01:13 UTC, jamcat22 approved these changes

2020-03-29 01:13 UTC, merged