Add InvoiceBerry
2factorauth/twofactorauth pull request #4701
Opened 2020-03-17 09:21 UTC by newah

2020-03-17 10:23 UTC, phallobst requested changes
Please replace the icon with this one which is much smaller in file size:
![invoiceberry](https://user-images.githubusercontent.com/520841/76846825-6aab5e00-6841-11ea-86c3-228672bd9731.png)

Also, the newline at the end of "finance.yml" is missing now.

2020-03-17 10:35 UTC, newah commented
@phallobst thanks for the comments, made the changes

2020-03-17 11:15 UTC, phallobst approved these changes

2020-03-23 13:42 UTC, Carlgo11 approved these changes

2020-03-23 13:42 UTC, merged