Add coincheck
2factorauth/twofactorauth pull request #4704
Opened 2020-03-26 07:28 UTC by cc-ShuheiSawamura

Coincheck(https://coincheck.com) is one of the largest crypto exchange in Japan. Alexa rank of the exchange is 14977 globally and 1225 in Japan. 

https://www.alexa.com/siteinfo/coincheck.com

2020-03-26 11:22 UTC, phallobst requested changes

2020-03-26 11:22 UTC, phallobst commented on _data/cryptocurrencies.yml
> +    doc: https://faq.coincheck.com/s/article/20204
```suggestion
    doc: https://faq.coincheck.com/s/article/20204?language=en_US
```

2020-03-27 00:07 UTC, cc-ShuheiSawamura commented on _data/cryptocurrencies.yml
> +    doc: https://faq.coincheck.com/s/article/20204
Thanks phallobst. I committed your suggestion.

2020-03-27 08:09 UTC, phallobst commented
Could you pass the icon through tinypng.com to shrink its file size, please?

2020-03-27 08:21 UTC, cc-ShuheiSawamura commented
> Could you pass the icon through tinypng.com to shrink its file size, please?

I changed the picture to the one shrinked by tinypng.com.

2020-03-27 08:29 UTC, phallobst approved these changes

2020-03-27 09:02 UTC, Carlgo11 approved these changes

2020-03-27 09:03 UTC, merged