Add Zoom
2factorauth/twofactorauth pull request #4712
Opened 2020-04-06 04:13 UTC by jimmyvanau

Add Zoom as a site + link to documentation (https://support.zoom.us/hc/en-us/articles/360038247071-Setting-up-and-using-two-factor-authentication)

2020-04-06 06:07 UTC, jamcat22 requested changes

2020-04-06 06:07 UTC, jamcat22 commented on _data/communication.yml
> +    doc: https://support.zoom.us/hc/en-us/articles/360038247071-Setting-up-and-using-two-factor-authentication
```suggestion
    doc: https://support.zoom.us/hc/en-us/articles/360038247071
    exception: "2FA is only available on paid plans and doesn't protect the desktop or mobile apps."
```

2020-04-06 06:28 UTC, jamcat22 approved these changes
Thanks @jimmyvanau!

2020-04-06 12:42 UTC, Carlgo11 commented
Is 2FA completely ignored when signing in through a desktop or phone app?

2020-04-06 21:18 UTC, jimmyvanau commented
Looks that way, 2FA only for web settings

2020-04-07 14:13 UTC, Carlgo11 commented
@jamcat22 is that even 2FA then?

2020-04-11 20:07 UTC, prkls commented
> @jamcat22 is that even 2FA then?

Arguably, yes. The 2FA is to the web console where changes to the user's defaults are done. Also, if you're an admin or owner of the Zoom account, any changes to the environment, adding and deleting users, etc. can be 2FA protected.

2020-04-12 02:26 UTC, jamcat22 commented
I'd say adding it with the exception noted is good. It at least adds some protection to admin settings and recordings. The app now integrating chat features makes it a larger target than when it just was used for joining meetings, but that doesn't mean 2FA should be disabled altogether.

2020-04-12 02:57 UTC, Carlgo11 approved these changes

2020-04-12 02:58 UTC, merged