Add Houseparty
2factorauth/twofactorauth pull request #4714
Opened 2020-04-07 00:44 UTC by jimmyvanau

2020-04-07 14:15 UTC, Carlgo11 requested changes

2020-04-07 14:15 UTC, Carlgo11 commented on _data/communication.yml
> +    facebook: houseparty
```suggestion
    facebook: houseparty
    email_address: support@houseparty.com
```

2020-04-07 14:23 UTC, Carlgo11 requested changes
Here's a logo with less JPEG artifacts and smaller size.
![houseparty.png](https://user-images.githubusercontent.com/3535780/78680655-0c2b4a00-78ec-11ea-8d2f-382be68c31a5.png)

2020-04-08 01:19 UTC, Carlgo11 approved these changes

2020-04-08 06:08 UTC, phallobst approved these changes

2020-04-08 06:08 UTC, merged