Add Bendigo Bank
2factorauth/twofactorauth pull request #4718
Opened 2020-04-08 12:47 UTC by jimmyvanau

2020-04-08 13:56 UTC, phallobst commented
> In order to access some services in Bendigo e-banking, like updating your Contact Details or sending money using Pay Anyone, a Security Token is required.

This sounds more like _authorization_, not _authentication_. Do you need an "e-token" when logging into your account?

2020-04-09 04:32 UTC, jimmyvanau commented
This is the logon screen
![image](https://user-images.githubusercontent.com/7769349/78858080-b501b280-7a6e-11ea-982f-4a5bc1809e40.png)

And I've always used the token. Testing again, it seems to ignore that input for my account, as in I can leave it empty. That is interesting 🤔 Seems like it's not proper 2FA then.

2020-04-09 11:25 UTC, phallobst commented
Could it be that entering the security token enables a "super user" mode that allows you to change account details or use "Pay Anyone", whereas leaving it blank just gives you basic functions, like checking your balance?
Or do you need to enter a token every time that you want to authorize something?

2020-09-28 15:51 UTC, phallobst commented
@jimmyvanau Can you provide more information regarding my [comment](https://github.com/2factorauth/twofactorauth/pull/4718#issuecomment-611477101)?

2020-09-29 09:34 UTC, jimmyvanau commented
Hi @phallobst thanks for following up - forgot about this.

Just tested it. It looks like the token is required for extra/secure actions. I can login, check balance and transfer to known users with username + pw. If I attempt to pay a new person after logging in with username + pw only, then it prompts for the token.

2020-09-29 13:44 UTC, Carlgo11 commented
So that would be closer to two step [authorization](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#a-note-on-definitions) than authentication.

2020-09-29 15:36 UTC, phallobst requested changes

2020-09-29 15:36 UTC, phallobst commented on _data/banking.yml
> +    doc: https://www.bendigobank.com.au/help/security/online-security/e-tokens/
Let's list it as non-supporting then.
```suggestion
    facebook: BendigoBank 
    twitter: bendigobank
```

2020-09-29 22:18 UTC, Carlgo11 requested changes

2020-09-29 22:18 UTC, Carlgo11 commented on _data/banking.yml
> +    facebook: BendigoBank
Whoops, seems to be an extra space here 😅 
```suggestion
    facebook: BendigoBank
```

2020-09-30 10:40 UTC, phallobst approved these changes

2020-10-01 02:05 UTC, Carlgo11 approved these changes

2020-10-01 02:05 UTC, merged