Add Netlify
2factorauth/twofactorauth pull request #4719
Opened 2020-04-09 04:50 UTC by jimmyvanau

2020-04-10 14:10 UTC, phallobst requested changes
This logo is a bit smaller in file size:
![netlify](https://user-images.githubusercontent.com/520841/78996854-c4076400-7b45-11ea-962a-1d45e6c392f1.png)

2020-04-10 14:10 UTC, phallobst commented on _data/hosting.yml
> +    twitter: netlify
```suggestion
    twitter: Netlify
```

2020-04-12 00:35 UTC, Carlgo11 requested changes

2020-04-12 00:35 UTC, Carlgo11 commented on _data/hosting.yml
> +    status: https://community.netlify.com/t/feature-request-two-factor-authentication-2fa-on-accounts/2876
The status tag is only meant to be used when a site is actively working on implementing 2FA. From reading the thread it looks like they're not working on it at the moment.
```suggestion
```

2020-04-12 02:57 UTC, Carlgo11 approved these changes

2020-04-12 06:31 UTC, phallobst approved these changes

2020-04-12 06:31 UTC, merged