Add regions tag
2factorauth/twofactorauth pull request #4721
Opened 2020-04-15 00:22 UTC by Carlgo11

😣 finally done

Have fun going through the banking.yml file! (or just approve 🤷 )

2020-04-15 20:33 UTC, phallobst requested changes
These are missing, and I can't seem to mark the lines for suggestions:
- norisbank: de
- Woodforest National Bank: us

2020-04-17 07:55 UTC, phallobst approved these changes

2020-04-24 23:39 UTC, Carlgo11 commented
So... this would be good to have merged 😁

2020-04-24 23:40 UTC, Carlgo11 commented
There's also a `regions` branch here on 2factorauth/twofactorauth where anyone can add region tags

2020-04-26 16:06 UTC, closed without merging