Update banking.yml
2factorauth/twofactorauth pull request #4722
Opened 2020-04-18 01:18 UTC by rdgarfinkel

Add Fifth Third. Just had to log in with a code sent to my cell phone, hadn't logged in on this device.

2020-04-18 05:59 UTC, phallobst requested changes
Is there a public documentation page for 2FA available?

2020-04-18 05:59 UTC, phallobst commented on _data/banking.yml
>      facebook: FifthThirdBank
```suggestion
    twitter: FifthThird
    facebook: FifthThirdBank
```

2020-04-18 12:31 UTC, rdgarfinkel commented
> Is there a public documentation page for 2FA available?

I don’t see one in looking for about five minutes

2020-04-21 21:43 UTC, rdgarfinkel commented
I got "fatal: reference is not a tree: (code)
##[error]Git checkout failed with exit code: 128" in Jekyll when the test ran. I can't find where to run it again.

2020-04-22 06:00 UTC, phallobst approved these changes

2020-05-14 00:41 UTC, jamcat22 commented
@rdgarfinkel, since it sounds like no public-facing documentation is available, could you please provide screenshots of the 2FA setup process and/or login process so we can verify the entry?

**Please redact/crop out any personal information from your screenshots.**

You can drop or paste screenshots directly into a GitHub comment.

Thanks!

2020-05-14 18:55 UTC, rdgarfinkel commented
Upon login to on a new computer (incognito mode):
1: ![image](https://user-images.githubusercontent.com/7954223/81973517-3d392180-95f2-11ea-9792-676d22dd1619.png)
2:
![image](https://user-images.githubusercontent.com/7954223/81973718-84bfad80-95f2-11ea-8ffc-f65b01ffbd11.png)
3:
![image](https://user-images.githubusercontent.com/7954223/81973874-c9e3df80-95f2-11ea-8091-65863fbe79f4.png)
4:
![image](https://user-images.githubusercontent.com/7954223/81973930-dbc58280-95f2-11ea-90ee-bf4e3f31042f.png)
5:
![image](https://user-images.githubusercontent.com/7954223/81974010-f5ff6080-95f2-11ea-81a0-d1da0a04e368.png)

2020-05-29 19:24 UTC, Carlgo11 approved these changes

2020-05-29 19:24 UTC, merged