Add maicoin.com
2factorauth/twofactorauth pull request #4726
Opened 2020-04-22 05:05 UTC by 4ndersonLin

MaiCoin is a Taiwan cryptocurrency buy/sale site.

2020-04-22 06:09 UTC, phallobst requested changes
Please replace the icon with this one which is much smaller in file size:
![maicoin](https://user-images.githubusercontent.com/520841/79946485-642b8a00-8470-11ea-80ac-2dcf659cdaeb.png)

2020-04-22 06:09 UTC, phallobst commented on _data/cryptocurrencies.yml
> +    doc: https://maicoin2.freshdesk.com/en/support/solutions/articles/32000016118-about-2-factor-authenticator
```suggestion
    doc: https://maicoin2.freshdesk.com/en/support/solutions/articles/32000016116
```

2020-04-22 06:40 UTC, 4ndersonLin commented
Thanks for the suggestions. Updated!

2020-04-22 07:02 UTC, phallobst approved these changes

2020-04-26 16:22 UTC, Carlgo11 requested changes

2020-04-26 16:22 UTC, Carlgo11 commented on _data/cryptocurrencies.yml
> +
Let's add a region code here as well.
```suggestion
    regions:
        - tw
```

2020-04-26 16:24 UTC, Carlgo11 approved these changes

2020-04-26 16:27 UTC, merged