Add Virgin Atlantic
2factorauth/twofactorauth pull request #4732
Opened 2020-04-23 18:36 UTC by fainpablo

2020-04-23 23:31 UTC, Carlgo11 requested changes
![virgin](https://user-images.githubusercontent.com/3535780/80159448-4fafd480-85cb-11ea-8e30-5916b205bb6e.png)

2020-04-24 12:18 UTC, fainpablo commented
I though that was the old logo, but looks like it's still being used. Thanks @Carlgo11 !

2020-04-24 21:46 UTC, Carlgo11 approved these changes

2020-04-25 14:09 UTC, phallobst approved these changes

2020-04-25 14:09 UTC, merged