Update Yahoo Mail
2factorauth/twofactorauth pull request #4739
Opened 2020-04-24 12:56 UTC by fainpablo

Added 'email' for Yahoo Mail

I can no longer see the 'phone' option. Can anyone confirm if it's still there? Maybe it's just related to my country code (+54).

<img width="420" alt="Screen Shot 2020-04-24 at 09 42 07" src="https://user-images.githubusercontent.com/17606465/80214838-e1dacb80-8611-11ea-9e97-8d516d63bb8e.png">

2020-04-26 00:50 UTC, Carlgo11 commented
I don't think anyone here uses Yahoo Mail so it would be hard to verify.
If you feel confident that it's not provided then add it to this PR and we'll merge it.

2020-04-28 10:19 UTC, Carlgo11 approved these changes

2020-05-03 01:33 UTC, fainpablo commented
> I don't think anyone here uses Yahoo Mail so it would be hard to verify.
> If you feel confident that it's not provided then add it to this PR and we'll merge it.

I don't know anyone who still uses Yahoo Mail, but who knows... I've left the question about the phone call verification method on Twitter just to make sure it's not just me.

2020-05-03 15:07 UTC, Carlgo11 commented
Let's add MySpace next! :smile:

2020-05-06 19:53 UTC, jamcat22 commented
Can confirm they still support phone call verification, if you verify the phone number using the "Call me" option when turning on 2FA.
<img width="363" alt="Yahoo Enable 2FA screen, showing phone call verification" src="https://user-images.githubusercontent.com/1897053/81221449-151d4300-8fa0-11ea-9aa2-4d5b689985d5.png">
When logging in, the last option allows for receiving a code via phone call (it's not very well shown, but it's the option without the "Msg & data rates apply" message).
<img width="362" alt="Yahoo Prompt for 2FA screen, showing SMS, proprietary, email, and phone call verification options" src="https://user-images.githubusercontent.com/1897053/81221517-2ebe8a80-8fa0-11ea-8253-229a66a1eb20.png">
They also support using an installed Yahoo app (tested with Yahoo Finance and Yahoo Mail) for verification. It's not supported as the main method unless you use their [Account Key system](https://help.yahoo.com/kb/SLN25781.html) (which is separate and gets rid of your password altogether).
A phone number must be linked to the account to enable 2FA.

2020-05-06 19:54 UTC, jamcat22 commented on _data/email.yml
>      doc: https://help.yahoo.com/kb/SLN5013.html
```suggestion
    doc: https://help.yahoo.com/kb/SLN5013.html
    exception: "Linked phone number required for 2FA."
```

2020-05-06 19:56 UTC, jamcat22 requested changes

2020-05-06 19:56 UTC, jamcat22 commented on _data/email.yml
> +      - email
```suggestion
      - email
      - proprietary
```

2020-05-06 19:56 UTC, jamcat22 commented on _data/email.yml
>      doc: https://help.yahoo.com/kb/SLN5013.html
```suggestion
    doc: https://help.yahoo.com/kb/SLN5013.html
    exception: "Linked phone number required for 2FA."
```

2020-05-12 15:10 UTC, fainpablo commented
Thanks. I just added your changes to the PR.

2020-05-12 15:19 UTC, jamcat22 approved these changes

2020-05-12 15:20 UTC, merged