TD Ameritrade offers proprietary two-factor auth solution now
2factorauth/twofactorauth pull request #4749
Opened 2020-05-01 14:14 UTC by jehart

TD Ameritrade has a two factor auth application:
https://apps.apple.com/us/app/td-ameritrade-authenticator/id1449911854
https://play.google.com/store/apps/details?id=com.tdameritrade.authenticator&hl=en_US

This is not documented on their website but the solution has been available for about a year now in the app stores.

2020-05-01 17:46 UTC, phallobst requested changes
Since the official documentation (https://www.tdameritrade.com/security/online-safety-tips.page, https://www.tdameritrade.com/security/security-procedures.page) only mentions SMS based 2FA, some screenshots of the 2FA setup procedure would be helpful.

Linking to the app store is not really useful, I suppose.

2020-05-01 17:46 UTC, phallobst commented on _data/investing.yml
> +    doc: https://apps.apple.com/us/app/td-ameritrade-authenticator/id1449911854
```suggestion
```

2020-05-03 00:11 UTC, jehart commented
I'm good with that, I wasn't sure how to properly show the links given they don't have it on the website

2020-05-03 00:29 UTC, Carlgo11 commented
"they" as in your company? 😉

2020-05-30 01:01 UTC, Carlgo11 commented
@jehart still need those screenshots in order to approve the PR.

2020-05-30 16:02 UTC, jehart commented
Here is an image
<img width="731" alt="Screen Shot 2020-05-30 at 11 00 22 AM" src="https://user-images.githubusercontent.com/1271120/83333228-18d17c00-a265-11ea-94e4-9d32c47f3c77.png">

2020-05-30 16:03 UTC, jehart commented
> "they" as in your company? 😉
> Just send over some screenshots and it should be good to go.

I don't work there anymore.

2020-09-18 00:00 UTC, Carlgo11 commented
Closing as the source is gone

2020-09-18 00:00 UTC, closed without merging