Add Bank Polski
2factorauth/twofactorauth pull request #4751
Opened 2020-05-02 16:52 UTC by phallobst

Closes #4750

2020-05-02 23:38 UTC, Carlgo11 requested changes

2020-05-02 23:38 UTC, Carlgo11 commented on _data/banking.yml
> +  - name: Bank Polski
```suggestion
  - name: PKO Bank Polski
```

2020-05-03 06:26 UTC, phallobst commented on _data/banking.yml
> +  - name: Bank Polski
Renaming requires moving as well...

2020-05-03 06:34 UTC, Carlgo11 approved these changes

2020-05-14 00:33 UTC, jamcat22 approved these changes

2020-05-14 00:33 UTC, merged