OVH: Add documentation and U2F support
2factorauth/twofactorauth pull request #4752
Opened 2020-05-03 13:13 UTC by rbeuque74

Adding the documentation link for setting up 2FA on your account.
Also indicating U2F support, as listed in the documentation (I have been testing it myself, works with a Yubikey blue security key)

2020-05-03 13:25 UTC, Carlgo11 requested changes
Looks like you don’t support any other hardware implementation than U2F so the hardware tag can be removed.

2020-05-03 13:25 UTC, Carlgo11 commented on _data/hosting.yml
>        - hardware
```suggestion

```

2020-05-03 19:25 UTC, rbeuque74 commented on _data/hosting.yml
>        - hardware
Applied

2020-05-10 18:09 UTC, Carlgo11 approved these changes

2020-05-12 15:22 UTC, jamcat22 approved these changes

2020-05-12 15:22 UTC, merged