Update Epic Games doc URL
2factorauth/twofactorauth pull request #4766
Opened 2020-05-13 19:19 UTC by bsawyer

Current doc URL returns 404, this changes the URL to the most recent help document.

2020-05-13 19:26 UTC, phallobst approved these changes

2020-05-13 20:44 UTC, Carlgo11 requested changes

2020-05-13 20:44 UTC, Carlgo11 commented on _data/gaming.yml
> +    doc: https://www.epicgames.com/help/en-US/epic-accounts-c74/account-security-c112/twofactor-authentication-and-how-to-enable-it-a3218
```suggestion
    doc: https://www.epicgames.com/help/en-US/c74/c112/a3218
```

2020-05-14 02:06 UTC, Carlgo11 approved these changes

2020-05-14 03:03 UTC, jamcat22 approved these changes

2020-05-14 03:03 UTC, merged