Update to surfshark entry.
2factorauth/twofactorauth pull request #4767
Opened 2020-05-13 20:08 UTC by ahopgood

2020-05-13 20:43 UTC, Carlgo11 requested changes

2020-05-13 20:43 UTC, Carlgo11 commented on _data/security.yml
> +    doc: https://support.surfshark.com/hc/en-us/articles/360011448319-How-to-enable-2FA-on-your-Surfshark-account-
```suggestion
    doc: https://support.surfshark.com/hc/en-us/articles/360011448319
```

2020-05-14 08:41 UTC, ahopgood commented on _data/security.yml
> +    doc: https://support.surfshark.com/hc/en-us/articles/360011448319-How-to-enable-2FA-on-your-Surfshark-account-
Thanks, updated

2020-05-14 09:38 UTC, jamcat22 approved these changes

2020-05-14 17:23 UTC, Carlgo11 approved these changes

2020-05-14 17:23 UTC, merged