Adds Credit Karma UK
2factorauth/twofactorauth pull request #4780
Opened 2020-05-22 18:10 UTC by ChristopherHammond13

Credit Karma bought Noddle in the UK, and although the site has been rebranded it does not support 2FA. Updated the YAML to reflect this.

2020-05-23 05:58 UTC, phallobst requested changes

2020-05-23 05:58 UTC, phallobst commented on _data/finance.yml
> +  - name: Credit Karma (UK), formally Noddle
```suggestion
  - name: Credit Karma (UK), formerly Noddle
```

2020-05-29 19:17 UTC, Carlgo11 approved these changes

2020-05-29 19:24 UTC, phallobst approved these changes

2020-05-29 19:24 UTC, merged