Bullionexchanges
2factorauth/twofactorauth pull request #4784
Opened 2020-05-27 19:14 UTC by navkaln

add Bullion Exchanges to Investing category

2020-05-27 19:41 UTC, phallobst requested changes

2020-05-27 19:41 UTC, phallobst commented on _data/investing.yml
> +    url: https://www.bullionexchanges.com.com/
```suggestion
    url: https://www.bullionexchanges.com/
```

2020-05-28 10:16 UTC, phallobst approved these changes

2020-05-29 19:19 UTC, Carlgo11 approved these changes

2020-05-29 19:20 UTC, merged