Added buxfer.com
2factorauth/twofactorauth pull request #4794
Opened 2020-06-07 13:09 UTC by rj175

Added buxfer.com, financial management platform.

2FA only supported on prime accounts (annoyingly) and software 2FA only by authy app (again, annoyingly!), these are noted in the exceptions.

Alexa ranking:
![image](https://user-images.githubusercontent.com/5339261/83969549-8a927100-a8c8-11ea-875e-655db151979a.png)

2020-06-07 13:45 UTC, phallobst requested changes
Is there any publicly accessible documentation for the 2FA support? Or could you provide screenshots (without personal information) that shows the setup process?

2020-06-07 13:45 UTC, phallobst commented on _data/finance.yml
> +    exception: "Only supported on 'Prime' accounts, software 2FA via Authy app only."
```suggestion
      - proprietary
    exception: "Only supported on 'Prime' accounts."
```

2020-06-07 20:44 UTC, rj175 commented
> Is there any publicly accessible documentation for the 2FA support? Or could you provide screenshots (without personal information) that shows the setup process?
Hello! This is the only screenshot I can get at the moment as there seems to be an issue with me setting up 2FA.

![Screenshot from 2020-06-07 21-35-30](https://user-images.githubusercontent.com/5339261/83979668-f811c200-a907-11ea-9be5-df1fbcd97969.png)

2020-06-08 00:15 UTC, Carlgo11 commented
And you use this service yourself?

From looking at the [terms of use](https://www.buxfer.com/terms) the company seems to be, or borderline to, illegal. They take no responsibility for the security of their systems or data they collect; They don't disclose what kind of data that they collect or to which parties they share it with; No GDPR compliance whatsoever.

I'd recommend adding a 
```YAML
regions:
  - us
```
tag as they seem to only focus on the U.S.

2020-06-08 21:53 UTC, rj175 commented
Yes, for my sins I do use this service.
I'm not sure about the tag, the API they use does have a large amount of international banks, probably the largest selection I've seen for the UK.

2020-06-24 23:08 UTC, Carlgo11 commented
It isn't legal in the UK though 😞

2020-12-10 22:26 UTC, phallobst approved these changes

2021-08-18 15:18 UTC, Carlgo11 commented
Closing due to inactivity.

2021-08-18 15:18 UTC, closed without merging