Added resolver.co.uk
2factorauth/twofactorauth pull request #4795
Opened 2020-06-07 22:08 UTC by rj175

Added resolver.co.uk, complain handling assistant. Alexa rank:

![image](https://user-images.githubusercontent.com/5339261/83981214-cdc60180-a913-11ea-8e80-84c00ea8cabc.png)

2020-06-08 00:18 UTC, Carlgo11 requested changes

2020-06-08 00:18 UTC, Carlgo11 commented on _data/other.yml
> +
```suggestion
    regions:
      - gb

```

2020-06-08 00:19 UTC, Carlgo11 commented
Maybe `legal` would be a fitting category? 🤔

2020-06-08 00:33 UTC, rj175 commented
Sure. I wasn't sure where to put it and since they help consumers with problems with many companies in different sectors id put it under other. Happy to move it to legal though

2020-06-08 22:04 UTC, ohheyrj commented
Moved to legal as suggested :)

2020-06-09 22:18 UTC, Carlgo11 approved these changes
Great! Thanks 😄

2020-06-13 08:43 UTC, phallobst approved these changes

2020-06-13 08:43 UTC, merged