Add intigriti
2factorauth/twofactorauth pull request #4796
Opened 2020-06-08 11:42 UTC by ErazerBrecht

Hello,

Intigriti is a bug bounty platform focussed on Europe.
I hereby ask to be included in the list.

This week we passed the 200K on Alexa
![image](https://user-images.githubusercontent.com/6287467/84026467-a875d980-a98d-11ea-8fd9-57f0c8c85e2f.png)

Sincerely, Brecht

2020-06-08 14:27 UTC, phallobst requested changes

2020-06-08 14:27 UTC, phallobst commented on _data/security.yml
> +    doc: https://kb.intigriti.com/en/articles/2642631-2-factor-authentication
```suggestion
    doc: https://kb.intigriti.com/en/articles/2642631
```

2020-06-08 14:58 UTC, ErazerBrecht commented on _data/security.yml
> +    doc: https://kb.intigriti.com/en/articles/2642631-2-factor-authentication
Fair point ;)

2020-06-08 16:02 UTC, phallobst approved these changes

2020-06-10 14:48 UTC, Carlgo11 approved these changes

2020-06-10 14:48 UTC, merged