Add regions to government
2factorauth/twofactorauth pull request #4824
Opened 2020-06-29 12:55 UTC by Carlgo11

2020-06-29 21:51 UTC, jamcat22 requested changes
Rest looks good. 👍

2020-06-29 21:51 UTC, jamcat22 commented on _data/government.yml
> +      - it
```suggestion
      - cz
```

2020-07-03 15:09 UTC, phallobst approved these changes

2020-07-05 23:02 UTC, jamcat22 approved these changes

2020-07-05 23:02 UTC, merged