Fix icon transparency
2factorauth/twofactorauth pull request #4843
Opened 2020-07-10 11:33 UTC by phallobst

Some icons were updated as well

2020-07-10 12:58 UTC, Carlgo11 requested changes
I think `img/developer/pythonanywhere.png` might need to have a white background.

that said, the iCloud logo looks amazing! 😮

2020-07-10 14:27 UTC, phallobst commented
The python logo does look a bit frail, I give you that. How about this one, straight from their favicon?
![pythonanywhere](https://user-images.githubusercontent.com/520841/87165237-28af9780-c2ca-11ea-9b1f-aaf48a0d614b.png)
This should work without a white background.

2020-07-10 15:29 UTC, Carlgo11 commented
That works 👍

2020-07-10 16:05 UTC, Carlgo11 approved these changes

2020-07-22 09:11 UTC, kmpoppe approved these changes

2020-07-22 09:11 UTC, merged