Add CharlieHR
2factorauth/twofactorauth pull request #4855
Opened 2020-07-18 21:59 UTC by aquacash5

Adds CharlieHR to `other.yml`

2020-07-19 07:04 UTC, phallobst requested changes

2020-07-19 07:04 UTC, phallobst commented on _data/other.yml
> +    doc: https://www.charliehr.com/hr-online/security/security-measures
```suggestion
    doc: https://intercom.help/charliehr/en/articles/1037152
```

2020-07-19 14:31 UTC, phallobst approved these changes

2020-07-22 16:17 UTC, Carlgo11 approved these changes

2020-07-22 16:17 UTC, merged