add ACTIVE 24 hosting
2factorauth/twofactorauth pull request #4865
Opened 2020-07-30 21:23 UTC by TomasHala

2020-07-31 09:09 UTC, phallobst requested changes

2020-07-31 09:09 UTC, phallobst commented on _data/hosting.yml
> +
I don't think there should be multiple entries, but region specifiers instead.

The fact that there is no doc page in English yet is unfortunate. However, we can at least shorten the URL.

```suggestion
    doc: https://faq.active24.com/cz/183996-
    regions:
      - cz
      - gb
      - nl
      - sk
      - de
      - es

```

2020-07-31 13:54 UTC, phallobst approved these changes
Once the doc is available in English, we can adjust the link. For now, this should be sufficient.

2020-08-10 23:40 UTC, Carlgo11 approved these changes

2020-08-10 23:41 UTC, merged