Added VRV and Repl.it
2factorauth/twofactorauth pull request #4894
Opened 2020-08-21 01:09 UTC by shawnshyguy

Added VRV (entertainment) and Repl.it (developer), neither of which have 2FA yet.

2020-08-21 21:31 UTC, Carlgo11 requested changes
1. For future reference, please only create one PR per site addition.
2. The images you use are unnecessarily large. Here are some smaller images:
![vrv](https://user-images.githubusercontent.com/3535780/90936689-013e0580-e406-11ea-85de-4beae9e52338.png)
![replit](https://user-images.githubusercontent.com/3535780/90936802-419d8380-e406-11ea-9e4d-8587ab1e5ede.png)

2020-08-21 21:31 UTC, Carlgo11 commented on _data/entertainment.yml
```suggestion
    regions:
      - us

```

2020-08-21 21:32 UTC, Carlgo11 requested changes

2020-08-21 21:32 UTC, Carlgo11 commented on _data/entertainment.yml
> +    facebook: WatchVRV
```suggestion
    facebook: WatchVRV
```

2020-08-22 17:53 UTC, phallobst commented
Also, `replit.png` should be in `img/developer`, not `img`.

2020-09-16 08:50 UTC, Carlgo11 commented
@shawnshyguy please fix the requested changes within a couple of days or the PR will be closed due to inactivity.

2020-11-01 18:30 UTC, closed without merging