Add hCaptcha
2factorauth/twofactorauth pull request #4896
Opened 2020-08-22 14:55 UTC by jamiehowarth0

2020-08-22 15:00 UTC, Carlgo11 requested changes

2020-08-22 15:00 UTC, Carlgo11 commented on _data/security.yml
> +    twitter: hcaptcha
```suggestion
    twitter: hCaptcha
```

2020-08-23 10:57 UTC, phallobst approved these changes
The problem with the _workflow_ check has already been addressed in PR #4858.

2020-08-24 12:21 UTC, Carlgo11 approved these changes

2020-08-24 12:22 UTC, merged