Add Cookiebot
2factorauth/twofactorauth pull request #4936
Opened 2020-09-06 21:06 UTC by hassankhan

Add [Cookiebot](https://www.cookiebot.com/)

2020-09-06 21:15 UTC, phallobst requested changes
This icon is much more suitable, I guess. It's straight from their favicon:
![cookiebot](https://user-images.githubusercontent.com/520841/92335358-9bed4400-f096-11ea-971f-33cac4fcbefb.png)

2020-09-06 21:26 UTC, hassankhan commented
Absolutely, I didn't even think to check their favicon. Thanks for pointing that out, will update the PR shortly.

2020-09-06 21:29 UTC, phallobst approved these changes

2020-09-17 23:53 UTC, Carlgo11 approved these changes

2020-09-17 23:53 UTC, merged