Update AOL Mail
2factorauth/twofactorauth pull request #4952
Opened 2020-09-14 12:44 UTC by fainpablo

Added 'hardware' for AOL Mail. While they KB article is still not updated, users can go to https://login.aol.com/account/security/security-key for instructions after login.

![Screen Shot 2020-09-14 at 09 14 29](https://user-images.githubusercontent.com/17606465/93085755-6afba900-f66c-11ea-8b21-e12b4f07b03a.png)

![Screen Shot 2020-09-14 at 09 20 50](https://user-images.githubusercontent.com/17606465/93085748-68994f00-f66c-11ea-801c-460f8ef6dba9.png)

2020-09-14 12:57 UTC, phallobst requested changes

2020-09-14 12:57 UTC, phallobst commented on _data/email.yml
> +      - hardware
```suggestion
      - u2f
```

2020-09-14 14:08 UTC, phallobst approved these changes

2020-09-15 00:14 UTC, Carlgo11 approved these changes

2020-09-15 00:14 UTC, merged