Update Yahoo Mail
2factorauth/twofactorauth pull request #4953
Opened 2020-09-14 12:48 UTC by fainpablo

Added 'hardware' for Yahoo Mail. While they KB article is still not updated, users can go to https://login.yahoo.com/account/security/security-key for instructions after login.

Similar to #4952

![Screen Shot 2020-09-14 at 09 47 56](https://user-images.githubusercontent.com/17606465/93087798-743a4500-f66f-11ea-9fd1-854244c6ba8c.png)

2020-09-14 12:58 UTC, phallobst requested changes

2020-09-14 12:58 UTC, phallobst commented on _data/email.yml
> +      - hardware
```suggestion
      - u2f
```

2020-09-14 14:08 UTC, phallobst approved these changes

2020-09-15 00:15 UTC, Carlgo11 approved these changes

2020-09-15 00:15 UTC, merged