Fix various minor errors (spelling, grammar, punctuation, formatting)
2factorauth/twofactorauth pull request #4976
Opened 2020-09-27 10:51 UTC by phallobst

2020-09-27 11:04 UTC, kmpoppe commented on CONTRIBUTING.md
> +Sites supporting TFA should not have a `twitter:`, `facebook:` or `email_address:` field.
```suggestion
Sites supporting TFA must not have a `twitter:`, `facebook:` or `email_address:` field.
```
As the checks fail completely (no warning, error) when 2fa is enabled and one these is present I think the language should be a bit more direct.

2020-09-27 11:04 UTC, kmpoppe requested changes
See inline comment

2020-09-28 09:43 UTC, kmpoppe approved these changes

2020-09-28 13:44 UTC, Carlgo11 commented
I'm unsure if adding a ":" to each YAML key listing is the right thing to do. Technically we're referring to the key values and not the `key:` part of the string.
Just like when talking about Java variables you might refer to a variable named `a` and when doing that you don't say "Public String a;" but just "a" or "string a".

2020-09-28 13:53 UTC, phallobst commented
The YAML field were not referenced consistently; sometimes the colon was used, sometimes not. I just wanted to clean that up. If the colon should be dropped, so be it.

2020-09-28 13:56 UTC, Carlgo11 commented
Yeah we've kind of added it at random 😅
I think the best thing would be to drop it completely and instead just refer to the key value.

2020-09-28 15:42 UTC, Carlgo11 approved these changes
Thanks 😄

2020-09-28 15:43 UTC, merged