Add Galaxus
2factorauth/twofactorauth pull request #4989
Opened 2020-10-04 06:34 UTC by phallobst

2020-10-05 09:04 UTC, Carlgo11 approved these changes
I'm guessing you already ran it through tinypng?

2020-10-05 16:01 UTC, phallobst commented
I did, but it's still rather big. Another pass strips away about 200 bytes. Should we go for it?

2020-11-01 01:17 UTC, jamcat22 requested changes, later dismissed

2020-11-01 01:17 UTC, jamcat22 commented on _data/retail.yml
> +      - de
```suggestion
      - de
      - li
```
Galaxus, like Digitec, also [serves Liechtenstein](https://www.galaxus.ch/en/wiki/556).

2021-05-22 14:25 UTC, ApCoder123 approved these changes

2021-05-22 14:25 UTC, merged