Update Pennsylvania State University
2factorauth/twofactorauth pull request #4990
Opened 2020-10-04 13:06 UTC by phallobst

2020-10-05 09:02 UTC, Carlgo11 approved these changes

2020-10-10 00:53 UTC, jamcat22 requested changes, later dismissed

2020-10-10 00:53 UTC, jamcat22 commented on _data/education.yml
>        - hardware
```suggestion
      - hardware
      - u2f
```
Based on their [FAQ](https://get2fa.psu.edu/faqs/), Penn State also supports U2F 2FA through Duo.

2020-10-10 21:30 UTC, Carlgo11 approved these changes

2020-10-18 06:59 UTC, dsoegijono approved these changes

2020-10-18 20:49 UTC, merged