add Bitrix24
2factorauth/twofactorauth pull request #5058
Opened 2020-10-22 20:35 UTC by trockenasche

2020-10-22 20:52 UTC, phallobst requested changes
The icon does not seem to be in use on the website itself. Maybe the 24 or 24+clock would be better.

2020-10-22 20:54 UTC, trockenasche commented
It's the mobile app icon.
But I can have a look for a difference icon, if you want to.

2020-10-23 20:32 UTC, trockenasche commented
I added a probably better logo.

2020-10-23 21:07 UTC, phallobst approved these changes

2020-11-01 00:35 UTC, Carlgo11 approved these changes

2020-11-01 00:35 UTC, merged