Add Payoneer.com
2factorauth/twofactorauth pull request #5066
Opened 2020-10-29 21:46 UTC by achudinovskyh

2020-10-29 22:06 UTC, phallobst requested changes
It's already listed under "Payments", which is the more fitting category. Please update that entry accordingly.

2020-10-30 09:10 UTC, achudinovskyh commented
Removed Payoneer from "Banking", and updated the record in "Payments" since they support 2FA.

2020-10-30 09:34 UTC, phallobst requested changes

2020-10-30 09:34 UTC, phallobst commented on _data/payments.yml
> +    doc: https://www.payoneer.com/about/security-center
```suggestion
    doc: https://payoneer.custhelp.com/app/answers/detail/a_id/31268
```

2020-10-30 09:49 UTC, phallobst approved these changes

2020-10-31 02:04 UTC, Carlgo11 approved these changes

2020-10-31 02:05 UTC, merged