Add Restream
2factorauth/twofactorauth pull request #5067
Opened 2020-10-30 10:03 UTC by achudinovskyh

2020-10-30 11:32 UTC, phallobst requested changes
My impression is that this should be in the "Social" category rather than "Entertainment".

2020-10-30 11:32 UTC, phallobst commented on _data/entertainment.yml
> +    doc: https://support.restream.io/en/articles/870429-two-factor-authentication
```suggestion
    doc: https://support.restream.io/en/articles/870429
```

2020-10-30 12:10 UTC, phallobst commented
This icon looks a bit nicer, I think:
![restream](https://user-images.githubusercontent.com/520841/97703565-1cd22600-1ab1-11eb-9479-3a8424458775.png)

2020-10-30 13:04 UTC, achudinovskyh commented
both requests were addressed

2020-10-30 14:06 UTC, phallobst approved these changes

2020-11-01 11:00 UTC, dsoegijono approved these changes

2020-11-01 11:01 UTC, dsoegijono requested changes

2020-11-01 11:01 UTC, dsoegijono commented on _data/social.yml
> +    url: http://restream.io/
```suggestion
    url: https://restream.io/
```

Prefer https

2020-11-01 18:24 UTC, Carlgo11 approved these changes

2020-11-01 23:28 UTC, dsoegijono approved these changes

2020-11-01 23:28 UTC, merged