Add API documentation
2factorauth/twofactorauth pull request #5084
Opened 2020-11-14 23:40 UTC by Carlgo11

A more comprahensive documentation than the one that #5075 removes.

Unsure about the grammar. @jamcat22 might want to look at that 🙈

2020-11-15 12:04 UTC, phallobst commented
Maybe it would better to put the v2 paragraph _before_ v1 to indicate the preference.

2020-11-15 12:09 UTC, phallobst requested changes

2020-11-15 12:09 UTC, phallobst commented on API.md
> +|https://twofactorauth.org/api/v2/proprietary.json|non-RFC-6238 software 2FA
```suggestion
|https://twofactorauth.org/api/v2/proprietary.json|non-RFC-6238 software 2FA|
```

2020-11-15 12:09 UTC, phallobst commented on API.md
> +|hardware|Boolean||Hardware token support (including U2F-tokens)|
```suggestion
|hardware|Boolean||Hardware token support (including U2F tokens)|
```

2020-11-15 12:09 UTC, phallobst commented on API.md
> +If you're using our API to match client URLs with our dataset make sure you're only use the domain of the `url`-element as a website commonly uses subdomains and subdirectories.
```suggestion
If you're using our API to match client URLs with our dataset make sure you only use the domain of the `url`-element, as a website commonly uses subdomains and subdirectories.
```

2020-11-15 16:01 UTC, Carlgo11 commented
I put v1 at the top to preserve chronological order but I guess we could use reverse chronological order. Should the remarks still be at the bottom then?

2020-11-15 16:21 UTC, phallobst commented
Having an introduction (along with some development notes/remarks) at the top seems to be better, I think.

2020-11-16 21:33 UTC, Carlgo11 commented
@phallobst I've done a couple of drafts with your suggestions but they all suffer in the readability aspect.
As the remarks rely on Version 2 having been read it can only really be below Version 2. That means that the order would be Version 2, Remarks, Version 1 which looks really weird.

So basically, how strong do you feel about the changes? Because making the changes would require rewriting the entire document in order for it to be coherent.

2020-11-17 19:46 UTC, phallobst commented
What about his one? I didn't really change that much, and it's still quite readable (although lacking a strong story arc).

----

# API usage

## Introduction

The data collected for the twofactorauth.org website is also available as JSON files in order to enable developers to use it in their own programs. It is recommended to use the API with the highest version number, since older versions might not include all available information.

### URL & Domain matching

If you're using our API to match client URLs with our dataset make sure you only use the domain of the `url`-element, as a website commonly uses subdomains and subdirectories. Please note that there are exceptions like `.co.uk`, `.com.au` or `.co.nz` where the actual domain is found at a lower level.

### Caching

If you intent to query our JSON files often and with a lot of traffic, you may be blocked by Cloudflare, our reverse proxy provider. We therefore recommend that you cache the files locally for any large traffic cases.

### Avoid downloading unnecessary data

If you only intent on using a specific dataset, like all sites supporting RFC-6238, we recommend that you use the URI which lists just that. See [URIs](#uris-1) for a list of available paths. The smaller the better.

## Version 2
[...]

## Version 1 (Deprecated) :warning:
[...]

2020-11-17 20:37 UTC, phallobst approved these changes

2020-11-25 06:51 UTC, dsoegijono approved these changes

2020-11-25 06:52 UTC, merged