Rename NSB to Vy Group
2factorauth/twofactorauth pull request #5085
Opened 2020-11-15 13:21 UTC by phallobst

2020-11-15 15:58 UTC, Carlgo11 requested changes

2020-11-15 15:58 UTC, Carlgo11 commented on _data/transport.yml
> +  - name: Vy Group
Vy Group is the parent company.
```suggestion
  - name: Vy
```

2020-11-15 16:25 UTC, Carlgo11 approved these changes

2020-12-17 06:24 UTC, dsoegijono approved these changes

2020-12-17 06:24 UTC, merged