Add emma.ca
2factorauth/twofactorauth pull request #5088
Opened 2020-11-18 17:04 UTC by GPlanteQc

2020-11-18 17:53 UTC, phallobst commented
Please use this icon with a transparent background:
![emma](https://user-images.githubusercontent.com/520841/99567994-27f0e580-29cf-11eb-8c26-a01b7f9b246c.png)

2020-11-18 18:35 UTC, GPlanteQc commented
No problem. Thank you for providing me the new icon. I updated in my commit to include it.

2020-11-18 19:16 UTC, phallobst commented
Their [login page](https://app.emma.ca/en/login) features this information:
> Already have an account? Don't worry! From now on, we will send you an email with a security key each time you connect.

Do you have an account there in order to confirm that? It surely sounds like email 2FA to me. Unfortunately, I could not find any documentation to back me up on this.

2020-11-18 19:26 UTC, Carlgo11 commented
@phallobst could also be one factor authentication with email instead of passwords
🤔

2020-11-18 19:43 UTC, phallobst commented
Crikey, you may be right!
> Emma undertakes to implement all necessary means to ensure the best possible access to the Emma Secure Access. You are solely responsible for the secure link serving as the access key to your account, which is for single use only.

(see https://emma.ca/en/terms-of-use 11.2)

That would be a mind-bendingly stupid idea...

2020-11-18 22:54 UTC, GPlanteQc commented
There is no 2FA. It's simply a passwordless login. The same method has the one presented in this blog post from Okta https://www.okta.com/blog/2020/09/magic-links/

2020-11-19 21:48 UTC, phallobst approved these changes

2020-11-19 22:47 UTC, Carlgo11 requested changes

2020-11-19 22:47 UTC, Carlgo11 commented on _data/finance.yml
> +
```suggestion
    regions:
      - ca

```

2020-11-19 22:48 UTC, Carlgo11 approved these changes

2020-11-20 20:29 UTC, phallobst commented
What happened here? :confused:

2020-11-20 20:31 UTC, Carlgo11 commented
Actions temporarily stopped working so I pushed an empty commit to trigger it again. I did however accidentally also merge our latest commits in master as well 😅

2020-11-20 20:31 UTC, Carlgo11 approved these changes

2020-11-20 20:31 UTC, merged