Add Radius Bank
2factorauth/twofactorauth pull request #5112
Opened 2020-11-30 19:48 UTC by mmomjian

No documentation available, image: 
![image](https://user-images.githubusercontent.com/50788000/100656644-ffe07b00-331a-11eb-973a-efb1cb9ffc11.png)

2020-11-30 20:37 UTC, phallobst commented
The logo is very hard to see against the light green background when the middle part is transparent. Maybe this one with an opaque white center is better:
![radiusbank](https://user-images.githubusercontent.com/520841/100661616-00493800-3354-11eb-80eb-d3ae0c93476b.png)

2020-11-30 20:43 UTC, mmomjian commented
Thank you, updated

2020-11-30 20:44 UTC, phallobst requested changes

2020-11-30 20:44 UTC, phallobst commented on _data/banking.yml
> +
```suggestion
    regions:
      - us

```

2020-11-30 20:52 UTC, phallobst approved these changes

2021-04-08 16:26 UTC, ApCoder123 requested changes
Please use this SVG icon instead:
![Radius Bank SVG](https://raw.githubusercontent.com/ApCoder123/ApCoder123/master/5112.svg)

2021-04-08 16:59 UTC, mmomjian commented
done @ApCoder123

2021-04-08 17:01 UTC, ApCoder123 approved these changes

2021-04-08 17:01 UTC, merged