Add US Citizenship and Immigration Services
2factorauth/twofactorauth pull request #5114
Opened 2020-11-30 20:25 UTC by mmomjian

No docs available, image: 
![image](https://user-images.githubusercontent.com/50788000/100660579-3bca0f00-3320-11eb-9139-f21fa65f0507.png)

2020-11-30 20:58 UTC, phallobst requested changes

2020-11-30 20:58 UTC, phallobst commented on _data/government.yml
> +    url: https://myaccount.uscis.gov/
```suggestion
    url: https://uscis.gov/
```

2020-11-30 21:01 UTC, phallobst approved these changes

2020-12-03 00:29 UTC, Carlgo11 approved these changes
The region tag is quite funny here. Seems like it would be appropriate for every region _except_ the US! 😄 

![](https://i.imgur.com/yw4hlST.png)

2020-12-03 00:30 UTC, merged