Add US Postal Service
2factorauth/twofactorauth pull request #5116
Opened 2020-11-30 22:18 UTC by mmomjian

No public-facing documentation present

![image](https://user-images.githubusercontent.com/50788000/100672465-fa416000-332f-11eb-9be1-07a2c5dd6834.png)

2020-11-30 22:44 UTC, phallobst commented
I'm not sure about the _Government_ category here. There are some postal services under _Other_ already; maybe the entry should be moved there for consistency.

2020-11-30 22:45 UTC, mmomjian commented
I wasn't sure about this, however all the services I saw in other were private companies - I wasn't sure if this was different because it is the official US mailing service, and I didn't see any other governmental postal carriers on the website yet.

2020-11-30 22:49 UTC, phallobst requested changes

2020-11-30 22:49 UTC, phallobst commented on _data/government.yml
> +    doc: https://reg.usps.com/entreg/AccountRecoveryHelpAction_input
```suggestion
    doc: https://faq.usps.com/s/article/USPS-com-Account#Two-Factor_Authentication
```

2020-12-01 17:21 UTC, phallobst commented
Although the USPS is a governmental agency, I do not perceive it as such (as a non-American), but rather as a postal service. In my opinion, it's better to move it to _Other_. Maybe it's even time to create a new category _Postal Service_ or something.

2020-12-01 18:06 UTC, mmomjian commented
If we made a new category such as "Mailing", "Shipping", or "Postal service" we could include the following. Is that enough to justify a new category? If not, I will move USPS to Other with the ones below.

- Australia Post
- DHL Deutschland
- DPD
- Hermes DE
- UK Postbox
- UPS
- US Postal Service

2020-12-01 19:03 UTC, phallobst commented
There's _GLS-ONE_ as well. Regarding _Poste Italiane_, I agree that it rather belongs to the _Postal Services_.

We do not have a fixed number of entries required to start a new category, but 5+ seems reasonable to me.

However, I'd suggest to tackle the new category with a new PR, and add USPS to _Other_ with this one. That way the site is added quickly to the data set, and we can take our time with the new category.

2020-12-02 04:39 UTC, mmomjian commented
I will work on a new category soon.

2020-12-02 04:39 UTC, closed without merging