Add Parimatch
2factorauth/twofactorauth pull request #5122
Opened 2020-12-01 10:56 UTC by 40504

2020-12-01 17:09 UTC, phallobst approved these changes

2021-04-14 14:53 UTC, ApCoder123 requested changes

2021-04-14 14:53 UTC, ApCoder123 commented on _data/betting.yml
> +    doc: https://air.parimatchgoal.com/en/faq/authentication/
```suggestion
    doc: https://faq.parimatch.com/en/account-access-and-security/
```
The doc link provided doesn't seem to work. Perhaps this one might be more suitable?

2021-04-14 16:30 UTC, ApCoder123 approved these changes

2021-04-14 16:30 UTC, merged