Add Smarkets
2factorauth/twofactorauth pull request #5123
Opened 2020-12-01 11:06 UTC by 40504

2020-12-01 17:07 UTC, phallobst requested changes

2020-12-01 17:07 UTC, phallobst commented on _data/betting.yml
> +    doc: https://help.smarkets.com/hc/en-gb/articles/115000822171-Using-two-factor-authentication/
```suggestion
    doc: https://help.smarkets.com/hc/en-gb/articles/115000822171
```

2020-12-01 17:33 UTC, phallobst commented
I hoped that converting this PR to draft and back would trigger the checks again. (_Narrator: It didn't._)

2020-12-01 22:15 UTC, phallobst approved these changes

2020-12-05 05:35 UTC, dsoegijono approved these changes

2020-12-05 05:35 UTC, merged