Update M&T Bank formatting
2factorauth/twofactorauth pull request #5125
Opened 2020-12-01 14:52 UTC by mmomjian

"and" -> "&" as per their logo and website branding

2020-12-01 17:05 UTC, phallobst requested changes

2020-12-01 17:05 UTC, phallobst commented on _data/banking.yml
> +  - name: M&T Bank
I think it's better to use this encoding for HTML entities:
```suggestion
  - name: M&amp;T Bank
```

2020-12-01 17:40 UTC, mmomjian commented
Makes sense, I had just grabbed it from the closest entry, which is "-name: Swedbank & Sparbankerna"

2020-12-01 22:16 UTC, phallobst approved these changes

2021-04-08 13:52 UTC, ApCoder123 requested changes
Please use this PNG with a fully transparent background.

![mtbank](https://user-images.githubusercontent.com/20560218/114038580-e677ae80-9879-11eb-9103-f8f5e26ad6ab.png)

2021-04-08 15:46 UTC, mmomjian commented
@ApCoder123 done!

2021-04-08 15:47 UTC, ApCoder123 approved these changes

2021-04-08 15:47 UTC, merged