Update T-Mobile
2factorauth/twofactorauth pull request #5127
Opened 2020-12-01 15:09 UTC by mmomjian

![image](https://user-images.githubusercontent.com/50788000/100758256-4f778300-33bd-11eb-853c-5db2a480173e.png)

2020-12-01 15:17 UTC, phallobst requested changes

2020-12-01 15:17 UTC, phallobst commented on _data/utilities.yml
> +      - proprietary
The proprietary T-Mobile app is not the authentication factor here, but rather biometric features. These are currently classified as _hardware_.
```suggestion
      - hardware
```

2020-12-01 16:57 UTC, phallobst approved these changes

2020-12-05 05:28 UTC, dsoegijono approved these changes

2020-12-05 05:28 UTC, merged