Add SelfWealth
2factorauth/twofactorauth pull request #5130
Opened 2020-12-02 10:46 UTC by 40504

2020-12-03 00:25 UTC, Carlgo11 requested changes
Nice work! Just one more things before your pull request is good to go! 🤞

2020-12-03 00:25 UTC, Carlgo11 commented on _data/investing.yml
> +
```suggestion
    regions:
      - au

```

2020-12-03 11:41 UTC, Carlgo11 approved these changes

2020-12-06 15:40 UTC, phallobst approved these changes

2020-12-06 15:41 UTC, merged