Add Postmarkapp
2factorauth/twofactorauth pull request #5131
Opened 2020-12-02 11:36 UTC by 40504

2020-12-02 16:58 UTC, phallobst approved these changes

2020-12-05 05:27 UTC, dsoegijono commented
Do we need an exception saying that SMS is required to enable TOTP?

2020-12-05 07:45 UTC, phallobst requested changes

2020-12-05 07:45 UTC, phallobst commented on _data/communication.yml
> +    doc: https://postmarkapp.com/support/article/1081-how-do-i-use-two-factor-authentication-2fa
Including the exception is probably a good idea:
```suggestion
    doc: https://postmarkapp.com/support/article/1081-how-do-i-use-two-factor-authentication-2fa
    exception: "Setup requires SMS verification."
```

2020-12-05 11:26 UTC, phallobst approved these changes

2020-12-05 12:22 UTC, dsoegijono approved these changes

2020-12-05 12:22 UTC, merged