Add 2Checkout
2factorauth/twofactorauth pull request #5148
Opened 2020-12-10 02:13 UTC by 40504

2020-12-10 11:31 UTC, phallobst requested changes
"2Checkout" offers a number of products, and only "2Sell" seems to fit into the _Payments_ category.  Maybe it's better to move this entry to _Other_.

2020-12-10 12:48 UTC, 40504 commented
Done

2020-12-10 13:45 UTC, phallobst approved these changes

2021-03-23 11:50 UTC, Carlgo11 approved these changes

2021-03-23 11:50 UTC, merged