Add Bill
2factorauth/twofactorauth pull request #5151
Opened 2020-12-10 12:01 UTC by 40504

2020-12-10 13:30 UTC, phallobst requested changes

2020-12-10 13:30 UTC, phallobst commented on _data/payments.yml
> +    doc: https://help.bill.com/hc/en-us/articles/360000023843
```suggestion
    doc: https://help.bill.com/hc/en-us/articles/360000023843
    exception: "2FA via phone call is available for US and CA only."
```

2020-12-10 13:41 UTC, 40504 commented
how to find in which countries the service is available?

2020-12-10 13:52 UTC, phallobst commented
On the doc page, it says so in the section "Use an international phone number for MFA/2-step verification":
> Codes via phone call are only available to cell phone numbers from the US and Canada.

2021-03-04 11:59 UTC, phallobst approved these changes

2021-04-10 20:24 UTC, ApCoder123 requested changes
Please change your icon to an SVG:
![](https://raw.githubusercontent.com/ApCoder123/ApCoder123/master/5151.svg)

2021-04-11 07:57 UTC, ApCoder123 approved these changes

2021-04-11 07:58 UTC, merged