Add Guideline
2factorauth/twofactorauth pull request #5184
Opened 2021-01-13 05:22 UTC by alexander-dejeu

* Add Guideline 401k Platform

2021-01-20 18:34 UTC, 40504 commented
I think this icon more suitable:
![guideline](https://user-images.githubusercontent.com/71176569/105219157-697c4900-5b56-11eb-9fad-61343e9e54b5.png)

2021-01-21 06:42 UTC, alexander-dejeu commented
Nice suggestion @40504! Will update to use this icon as it does not have any background

2021-02-28 14:06 UTC, phallobst commented
Please rebase your branch to the current master.

2021-03-02 00:55 UTC, alexander-dejeu commented
Hi @Carlgo11! Thank you for the tag - I think I resolved the merge conflicts earlier today, let me know if that is not the case.  Diff looks good from a merge conflict perspective.  Cheers!

2021-03-02 00:56 UTC, Carlgo11 commented
@alexander-dejeu if you look at the [commit list](https://github.com/2factorauth/twofactorauth/pull/5184/commits) you'll see there are a bunch of unrelated commits.

2021-03-02 01:02 UTC, alexander-dejeu commented
Ophh! Good callout @Carlgo11 - let me take a look as to why that would be the case - thanks!

2021-03-02 01:05 UTC, Carlgo11 commented
Try
```PWSH
git add remote upstream https://github.com/2factorauth/twofactorauth.git
git fetch upstream

git reset --hard upstream/master
git cherry-pick e091c31503bb7e7525080f87958f4cf4f707a81e
git cherry-pick 8e8a1419478f1e85694ac5fc6d44fc15c9e602d9

git push origin alex/add-guideline -f
```

2021-03-02 01:43 UTC, alexander-dejeu commented
You rock @Carlgo11! 🔥 Looks much more clean now :)

2021-03-09 01:33 UTC, alexander-dejeu commented
Anything I can do to help move this from being inactive to active and then into master?

2021-03-09 01:54 UTC, Carlgo11 requested changes
Sorry for the delay.

As SVGs are prefered, please use this logo instead:<img src="https://d.carlgo11.com/D6046D4CD9A7FE/?p=bd3MuzDLS7RAVsgFP" height="32"/>

2021-03-09 01:54 UTC, Carlgo11 commented on _data/finance.yml
> +
```suggestion
    regions:
      - us
```

2021-03-09 03:02 UTC, Carlgo11 approved these changes
Thanks! 👍

2021-03-09 03:02 UTC, alexander-dejeu commented
Glad to see SVG is the preferred asset type! Thank you for pushing the PR along @Carlgo11!

2021-03-27 13:33 UTC, phallobst approved these changes

2021-03-27 13:34 UTC, merged