Add Indexa capital
2factorauth/twofactorauth pull request #5186
Opened 2021-01-15 12:35 UTC by frandieguez

2021-02-28 14:04 UTC, phallobst commented
Please rebase your branch to the current master.

2021-03-04 21:59 UTC, frandieguez commented
rebased to master

2021-03-09 02:39 UTC, Carlgo11 commented
@frandieguez Are you going to rebase? Let me know otherwise and I'll close this pull request.

2021-03-09 08:29 UTC, frandieguez commented
I have just rebased against master. Please let me know if this is what you expected

2021-03-09 14:47 UTC, Carlgo11 commented
Try:
```PWSH
git remote add upstream https://github.com/2factorauth/twofactorauth.git
git fetch upstream
git reset --hard upstream/master
git cherry-pick 4b3a518
git cherry-pick 5041d5b
git push origin master -f
```
When it's done there should only be 2 commits listed in this PR.
Let me know if you need further help.

2021-03-10 17:33 UTC, frandieguez commented
Done, now only two commits are in the PR, sorry for the back-and-forth

2021-03-10 20:49 UTC, Carlgo11 requested changes
Alright now I can see your actual changes! 🥳 

Just a few things that need to be changed before we can merge:
* The image must be a file stored in `img/investing/`. I recommend you use this one: <img src="https://d.carlgo11.com/D60492FE00B140/?p=lySsLPXd1tT" height="32"> and save it as indexa.svg.
* The documentation can't be reached without logging in. Either upload a screenshot of the doucmentation or screenshot(s) of the 2fa process. (I'll post a comment on how to upload screenshots below)
* Is the company only operating in Spain? If so, commit the suggested change's below.

2021-03-10 20:49 UTC, Carlgo11 commented on _data/investing.yml
> +
```suggestion
    regions:
      - es

```

2021-03-10 20:50 UTC, Carlgo11 commented
Screenshot note:
> Thanks for the pull request!
> 
> I see that you haven't add any documentation link. Could you maybe find one that describes how to enable 2FA on the site?
> 
> If no documentation is available or you can't find it, could you please add some screenshots of the 2FA setup process and/or login process?
> __Remember to blur or crop out any personal information linked to you.__
> 
> You can attach the screenshots here in a comment, like this:
> ![screenshot](https://user-images.githubusercontent.com/3535780/62257740-32b4ef00-b407-11e9-8f35-fc7c47ad72fb.gif)

2021-03-10 21:41 UTC, Carlgo11 commented
Oh no 😞 
Apparently indexacapital.com doesn't meet our requirement of being ranked <200K on Alexa.
It is currently above 1M (https://www.alexa.com/siteinfo/indexacapital.com)

Sadly this means the site can't be listed. Sorry for the inconvenience!

2021-03-10 21:41 UTC, closed without merging

2021-03-10 21:44 UTC, frandieguez commented
Oh! I understand sorry for the inconvenience