Added Backlog
2factorauth/twofactorauth pull request #5209
Opened 2021-01-26 12:52 UTC by gillax

2021-01-26 14:40 UTC, 40504 commented
when trying to log in, both Backlog and Typetalk are redirecting to the nulab.com account, already listed.

2021-01-27 01:21 UTC, gillax commented
Oh, I see. Nulab is already there.

2021-01-27 03:01 UTC, 40504 commented
better to let the PR open, the maintainers will decide to add or not

2021-02-28 14:01 UTC, phallobst commented
Please rebase your branch to the current master.

2021-03-02 02:50 UTC, gillax commented
I've updated it, thank you.

2021-03-10 01:19 UTC, Carlgo11 requested changes
Logo Santa is here with gifts! 🎅 
Try this logo instead: <img src="https://d.carlgo11.com/D60481E63A300B/?p=RwVvrT8z" height="32" alt="backlog.svg">

2021-03-10 01:19 UTC, Carlgo11 commented on _data/developer.yml
> +    doc: https://support.backlog.com/hc/en-us/community/posts/360029520833
Old link doesn't work for me. Here's one that does work:
```suggestion
    doc: https://support.nulab.com/hc/en-us/articles/115001025087
```

2021-05-12 20:12 UTC, closed without merging