Update netcup
2factorauth/twofactorauth pull request #5246
Opened 2021-02-25 11:29 UTC by Virinum

Three changes: 

- Update casing (it's **n**etcup, not **N**etcup)
- Update logo ([changed in 2019](https://www.netcup-news.de/2019/07/09/redesign-aller-websites-und-controlpanel/))
- Update domain (user interface is now only availabe at [customercontrolpanel.de](https://www.customercontrolpanel.de/), [also changed in 2019](https://www.netcup-news.de/2019/02/05/netcup-stellt-neues-customer-control-panel-vor/))

2021-02-28 13:11 UTC, phallobst requested changes

2021-02-28 13:11 UTC, phallobst commented on _data/hosting.yml
> +    url: https://www.customercontrolpanel.de/
We usually list the main page, not the login page.
```suggestion
    url: https://netcup.eu/
```

2021-03-04 11:57 UTC, phallobst approved these changes

2021-04-07 19:21 UTC, ApCoder123 approved these changes

2021-04-07 19:21 UTC, merged