Add Nozbe Teams
2factorauth/twofactorauth pull request #5250
Opened 2021-03-03 09:58 UTC by radex

2021-03-03 10:04 UTC, phallobst requested changes

2021-03-03 10:04 UTC, phallobst commented on _data/task.yml
> +      - totp
```suggestion
    tfa:
      - totp
      - sms
    doc: https://teams.nozbe.help/management/settings/#settings_2fa
```

2021-03-23 13:37 UTC, radex commented
@phallobst ⬆️

2021-03-23 16:10 UTC, Carlgo11 commented
@radex You need to reorder your entry so that it's alphabetical. See https://github.com/2factorauth/twofactorauth/runs/2175625465

2021-03-24 20:51 UTC, Carlgo11 approved these changes

2021-03-28 19:02 UTC, phallobst approved these changes

2021-03-28 19:02 UTC, merged