Add Litmus
2factorauth/twofactorauth pull request #5260
Opened 2021-03-06 18:23 UTC by phallobst

Closes #5259

2021-04-07 19:02 UTC, ApCoder123 requested changes
I found an SVG copy of the logo:
![SVG Logo](https://raw.githubusercontent.com/ApCoder123/ApCoder123/master/5260.svg)

2021-04-07 19:02 UTC, ApCoder123 commented on _data/communication.yml
> +    doc: https://help.litmus.com/article/128-two-step-verification
```suggestion
    doc: https://help.litmus.com/article/128--
```

2021-04-10 19:38 UTC, ApCoder123 requested changes

2021-04-10 19:38 UTC, ApCoder123 commented on _data/communication.yml
> +      - sms
```suggestion
      - sms
      - proprietary
```
According to the site:

> Is there an alternative to SMS-based verification? You can use Authy for our two-step verification. If you download and install the Authy apps you will need to enter the same phone number you used for your Litmus SMS-based two-step verification.
> 
> Once your Authy account is set up, when you're prompted for your two-step verification code, you can use either the code sent by SMS or the code generated by Authy.

2021-04-10 19:47 UTC, ApCoder123 approved these changes

2021-05-12 13:01 UTC, Carlgo11 approved these changes

2021-05-12 13:01 UTC, merged