Added Back4App
2factorauth/twofactorauth pull request #5266
Opened 2021-03-07 19:53 UTC by ApCoder123

2021-03-07 20:05 UTC, phallobst requested changes
The icon looks a bit strange... Please replace it with this one:
![back4app](https://user-images.githubusercontent.com/520841/110253090-bc845100-7f88-11eb-9629-8ecc773f4d9d.png)

2021-03-07 20:18 UTC, ApCoder123 commented
Okay, I have updated the image.

2021-03-07 20:19 UTC, phallobst approved these changes

2021-03-23 11:45 UTC, Carlgo11 approved these changes

2021-03-23 11:45 UTC, merged