Added TuneCore
2factorauth/twofactorauth pull request #5267
Opened 2021-03-07 20:39 UTC by ApCoder123

Alexa Rank 11,378

2021-03-07 21:59 UTC, phallobst requested changes

2021-03-07 21:59 UTC, phallobst commented on _data/entertainment.yml
> +    doc: https://support.tunecore.com/hc/en-us/articles/360000650226-Two-Factor-Authentication
```suggestion
    doc: https://support.tunecore.com/hc/en-us/articles/360000650226
```

2021-03-23 11:44 UTC, Carlgo11 approved these changes

2021-04-25 15:10 UTC, phallobst approved these changes

2021-04-25 15:10 UTC, merged