Update Vanguard
2factorauth/twofactorauth pull request #5268
Opened 2021-03-07 21:07 UTC by ApCoder123

Resolves #5164

2021-03-07 21:46 UTC, phallobst commented
I reckon it might be better to create a separate entry for the uk domain in order to make the difference more obvious.

2021-03-08 09:15 UTC, ApCoder123 commented
I have added a separate entry for the UK domain, but I'm not sure why the workflow checks are failing.

2021-03-08 19:22 UTC, Carlgo11 requested changes

2021-03-08 19:22 UTC, Carlgo11 commented on _data/investing.yml
> +
```suggestion
   regions:
     - gb
```

2021-03-08 22:48 UTC, Carlgo11 approved these changes

2021-03-27 13:29 UTC, phallobst approved these changes

2021-03-27 13:29 UTC, merged