Added RedShelf
2factorauth/twofactorauth pull request #5272
Opened 2021-03-08 14:12 UTC by ApCoder123

Resolves #5270

2021-03-09 15:01 UTC, Carlgo11 requested changes
Use this image instead: ![redshelf.svg](https://d.carlgo11.com/D60478D8F59EEC/?p=BCVvJ04wLaMERpdX)

2021-03-09 15:01 UTC, Carlgo11 commented on _data/education.yml
> +
```suggestion
    regions:
      - us

```

2021-03-09 15:01 UTC, Carlgo11 commented on _data/education.yml
> +    img: redshelf.png
```suggestion
    img: redshelf.svg
```

2021-03-09 20:08 UTC, ApCoder123 commented
Okay, I have updated the branch with the requested changes.

2021-03-09 20:09 UTC, Carlgo11 approved these changes
Super. Thanks! 👍

2021-03-27 13:47 UTC, phallobst approved these changes

2021-03-27 13:47 UTC, merged