Added MyGovID.ie
2factorauth/twofactorauth pull request #5274
Opened 2021-03-08 14:36 UTC by ApCoder123

Resolves #5243

2021-03-27 13:23 UTC, phallobst requested changes

2021-03-27 13:23 UTC, phallobst commented on _data/government.yml
> +  - name: MyGovID.ie
```suggestion
  - name: MyGovID
```

2021-04-02 11:39 UTC, phallobst approved these changes

2021-05-20 18:20 UTC, Carlgo11 approved these changes

2021-05-20 18:20 UTC, merged