Fix broken PRs
2factorauth/twofactorauth pull request #5275
Opened 2021-03-08 16:45 UTC by ApCoder123

Not sure why this happened, but the following PRs: #5173 #5175 #5177 were all merged, but the changes don't seem to be present on `2factorauth:master` and the commit that merged them can't be found in commit history, so I am submitting this PR to merge the PRs that didn't work.

2021-03-08 23:32 UTC, Carlgo11 requested changes
The PRs you mentioned were merged incorrectly by a maintainer who's no longer part of the project.

Looking at this PR I have a few change requests:
* Please change the call of duty logo. The provided one will look bad on the site.
* Use the following SVG for razer: ![razer.svg](https://tempfiles.ninja/d/JvRUuesql9kg8nTF/N2uNH12PldMTEtSU5cP1futd6OlP898q)
* Change the nordpass logo to this icon: ![nordpass.svg](https://tempfiles.ninja/d/pVZ5CM3nt6YpsPbE/QNCtXUFpTKVVh3QKvvZH0iZDO3x73ts9)

)

2021-03-09 12:27 UTC, ApCoder123 commented
Ok, I have updated the images for all of those sites.

2021-03-09 14:39 UTC, Carlgo11 approved these changes

2021-03-27 13:40 UTC, phallobst approved these changes

2021-03-27 13:40 UTC, merged