Update with Target current 2FA status
2factorauth/twofactorauth pull request #5276
Opened 2021-03-09 21:12 UTC by bencooper222

Target

2021-03-09 21:18 UTC, Carlgo11 requested changes

2021-03-09 21:18 UTC, Carlgo11 commented on _data/retail.yml
Let's add a region tag as well while you're at it 😉 
```suggestion
    regions:
      - us

```

2021-03-09 21:18 UTC, Carlgo11 approved these changes

2021-03-27 13:49 UTC, phallobst approved these changes

2021-03-27 13:49 UTC, merged