Add Engyte
2factorauth/twofactorauth pull request #5290
Opened 2021-03-13 14:54 UTC by ApCoder123

2021-03-13 21:26 UTC, phallobst requested changes

2021-03-13 21:26 UTC, phallobst commented on _data/other.yml
> +      - totp
Authy push notification would be `proprietary`.
```suggestion
      - totp
      - proprietary
```

2021-03-13 22:03 UTC, phallobst approved these changes

2021-03-23 11:41 UTC, Carlgo11 approved these changes

2021-03-23 11:41 UTC, merged