Add Paxful
2factorauth/twofactorauth pull request #5295
Opened 2021-03-14 17:57 UTC by ApCoder123

2021-03-27 14:33 UTC, phallobst approved these changes

2021-03-28 22:28 UTC, Carlgo11 requested changes
Found an SVG for paxful.
![paxful.svg](https://camo.githubusercontent.com/43b2bdcfb07eb66bd17dbd71b03a31ffb9f3d28d05d699a3e76b8f802d9218ed/68747470733a2f2f642e74656d7066696c65732e646f776e6c6f61642f44363036313032374534444536362f3f703d455a767144794c4357564175684a506c46)

2021-03-29 15:49 UTC, ApCoder123 commented
Ok, updated to svg.

2021-03-29 16:40 UTC, Carlgo11 approved these changes

2021-03-29 16:40 UTC, merged