Add WHC
2factorauth/twofactorauth pull request #5301
Opened 2021-03-16 13:09 UTC by ApCoder123

2021-04-02 11:20 UTC, phallobst requested changes

2021-04-02 11:20 UTC, phallobst commented on _data/hosting.yml
> +  - name: Web Hosting Canada (WHC)
```suggestion
  - name: Web Hosting Canada
```

2021-04-02 11:20 UTC, phallobst commented on _data/hosting.yml
> +    doc: https://clients.whc.ca/en/knowledgebase/1430/How-to-activate-and-use-Two-Factor-Authentication.html
```suggestion
    doc: https://clients.whc.ca/en/knowledgebase/1430
```

2021-04-05 07:29 UTC, phallobst approved these changes

2021-05-20 09:31 UTC, Carlgo11 approved these changes

2021-05-20 09:31 UTC, merged