Update ClickUp
2factorauth/twofactorauth pull request #5302
Opened 2021-03-16 17:49 UTC by ApCoder123

Updated ClickUp 2FA options and changed image to svg in the process.

2021-03-17 00:12 UTC, Carlgo11 requested changes

2021-03-17 00:12 UTC, Carlgo11 commented on _data/task.yml
> +    exception: "Availability of 2FA options depends on your account type."
```suggestion
    exception: "SMS only available on Business and Enterprise price plans."
```

2021-03-17 00:12 UTC, Carlgo11 approved these changes

2021-03-27 18:27 UTC, phallobst approved these changes

2021-03-27 18:27 UTC, merged