Update Rebel
2factorauth/twofactorauth pull request #5306
Opened 2021-03-16 18:10 UTC by ApCoder123

2021-03-21 13:17 UTC, phallobst requested changes
The icon is not centered in its viewbox, so it looks a bit strange.

FYI: You may want to save the effort to update all the icons to SVG. We were already planning to do just that (see #5061) and have completed most of the work by now.

2021-03-21 13:53 UTC, ApCoder123 commented
Ok, I have fixed this icon
If that is the case with updating svgs, I will probably revert the commits to change to svg on some of my unreviewed PRs to save both of our time. Thanks for letting me know :+1:

2021-03-23 11:51 UTC, Carlgo11 approved these changes

2021-04-05 07:32 UTC, phallobst approved these changes

2021-04-05 07:32 UTC, merged