Update ArtStation
2factorauth/twofactorauth pull request #5315
Opened 2021-03-16 20:11 UTC by ApCoder123

2021-03-20 19:33 UTC, phallobst requested changes
The icon is overflowing the viewbox; please replace it with this one:
![img](https://raw.githubusercontent.com/phallobst/phallobst/main/resterampe/artstation.svg)

2021-03-20 19:33 UTC, phallobst commented on _data/social.yml
> +    doc: https://help.artstation.com/en/articles/220-setting-up-two-factor-authentication
```suggestion
    doc: https://help.artstation.com/en/articles/220
```

2021-03-20 21:31 UTC, ApCoder123 commented
Ok, have changed the link and image

2021-03-20 22:44 UTC, phallobst commented
On the doc page it says:
> To complete the set up, you will need to confirm via an email that will be sent to you. Please check your spam folder as it may end up in there. Once enabled, you can confirm or deny any log-in requests from the Two Factor Auth Requests page located at the top of your mobile menu bar.

This seems to indicate that only the _set-up_ is done with an email confirmation, but any subsequent 2FA is performed via the app. Can you confirm this?

2021-03-20 23:14 UTC, ApCoder123 commented
Yes, I can confirm that you are correct. According to [this blog post](https://magazine.artstation.com/2020/07/protect-your-account-with-two-factor-authentication/)

> You can now enable a Two-Factor Authentication (2FA) system using the ArtStation App as an authentication device.

so I have updated tfa to proprietary and added info in the exception about the email confirmation

2021-03-21 09:20 UTC, phallobst approved these changes

2021-03-21 20:56 UTC, Carlgo11 approved these changes

2021-03-21 20:56 UTC, merged