Update Asana
2factorauth/twofactorauth pull request #5316
Opened 2021-03-16 20:14 UTC by ApCoder123

2021-03-20 19:28 UTC, phallobst requested changes
This icon is centered in a square bounding box and has been optimized for file size:
![img](https://raw.githubusercontent.com/phallobst/phallobst/main/resterampe/asana.svg)

2021-03-20 21:31 UTC, ApCoder123 commented
Ok, have updated the image

2021-03-20 22:39 UTC, phallobst approved these changes

2021-03-23 11:31 UTC, Carlgo11 approved these changes

2021-03-23 11:31 UTC, merged