Update contabo
2factorauth/twofactorauth pull request #5323
Opened 2021-03-20 15:49 UTC by ApCoder123

Update contabo doc link and logo

2021-03-20 16:05 UTC, 40504 commented
https://contabo.com/en/customer-support/faq/#2fa-questions better suited for 2fa.directory

2021-03-20 19:04 UTC, phallobst requested changes
Please replace the icon with this one (without superfluous whitespace):
![img](https://raw.githubusercontent.com/phallobst/phallobst/main/resterampe/contabo.svg)

2021-03-20 21:31 UTC, ApCoder123 commented
Ok, have replaced the image

2021-03-20 22:44 UTC, phallobst approved these changes

2021-03-23 11:39 UTC, Carlgo11 approved these changes

2021-03-23 11:39 UTC, merged