Update Paypal
2factorauth/twofactorauth pull request #5330
Opened 2021-03-22 00:54 UTC by 40504

2021-03-22 01:33 UTC, Carlgo11 requested changes
While your PNG is smaller, SVGs are perfered as they allow for perfect resolution in all sizes.
I suggest this one instead:
<img src="https://d.tempfiles.download/D6057F3D96F938/?p=eFPy6tHz2JYB5L" height="32" alt="paypal.svg"/>

2021-03-22 01:46 UTC, 40504 commented
> While your PNG is smaller, SVGs are perfered as they allow for perfect resolution in all sizes.
> I suggest this one instead:
> <img alt="paypal.svg" height="32" src="https://camo.githubusercontent.com/198dd205f8fe2585ee075e2fe2bf597b26ad8d6309c696a87a6e70c09799a27f/68747470733a2f2f642e74656d7066696c65732e646f776e6c6f61642f44363035374633443936463933382f3f703d654650793674487a324a5942354c">

Done

2021-03-22 02:03 UTC, Carlgo11 approved these changes

2021-03-27 19:50 UTC, phallobst approved these changes

2021-03-27 19:50 UTC, merged