Add Huobi
2factorauth/twofactorauth pull request #5338
Opened 2021-03-22 08:58 UTC by 40504

2021-03-22 21:17 UTC, Carlgo11 requested changes

2021-03-22 21:17 UTC, Carlgo11 commented on _data/cryptocurrencies.yml
> +    url: https://huobi.com
Other URL points to an invalid certificate.
```suggestion
    url: https://www.huobi.com/
```

2021-03-22 22:25 UTC, Carlgo11 approved these changes

2021-03-28 12:07 UTC, phallobst requested changes

2021-03-28 12:07 UTC, phallobst commented on _data/cryptocurrencies.yml
> +  - name: HUOBI
```suggestion
  - name: Huobi
```

2021-03-28 12:07 UTC, phallobst commented on _data/cryptocurrencies.yml
> +    tfa:
```suggestion
    tfa:
      - email
```
See https://huobiglobal.zendesk.com/hc/en-us/articles/360000191302

2021-04-03 11:45 UTC, phallobst approved these changes

2021-04-03 11:45 UTC, merged