Add Strato
2factorauth/twofactorauth pull request #5346
Opened 2021-03-22 11:30 UTC by 40504

2021-03-22 18:33 UTC, Carlgo11 approved these changes

2021-03-28 09:53 UTC, phallobst commented
This seems to apply only to "HiDrive" (i.e. its cloud storage product). Does it work for the domain account as well? Otherwise, a separate entry in the "Backup" category would probably be better.

2021-04-11 08:31 UTC, ApCoder123 requested changes

2021-04-11 08:31 UTC, ApCoder123 commented on _data/backup.yml
> +  - name: STRATO
```suggestion
  - name: STRATO HiDrive
```

2021-04-11 08:31 UTC, ApCoder123 commented on _data/backup.yml
> +      - de
```suggestion
      - de
      - nl
```
Also is available for Netherlands: https://www.strato.nl/faq/cloud-storage/Twee-factor-authenticatie/

2021-04-11 08:31 UTC, ApCoder123 commented on img/backup/strato.svg
> +<svg version="1.1" viewBox="0 0 90 90" xmlns="http://www.w3.org/2000/svg"><path d="m57.855 25.713 0.23074 0.0040598c3.446 0.12145 6.1998 2.9526 6.1998 6.4264v51.428l-0.0040571 0.23061c-0.12137 3.4441
```suggestion
<svg viewBox="0 0 90 90" xmlns="http://www.w3.org/2000/svg"><path d="m57.855 25.713 0.23074 0.0040598c3.446 0.12145 6.1998 2.9526 6.1998 6.4264v51.428l-0.0040571 0.23061c-0.12137 3.4441-2.9507 6.1979-6.4265 6.1979h-51.427l-0.23061-0.004057c-3.4442-0.12137-6.198-2.9506-6.198-6.4244v-51.428l0.0040571-0.23061c0.12137-3.4442 2.9507-6.1998 6.4245-6.1998h51.427zm19.288-25.713c7.1001 0 12.857 5.755 12.857 12.857l-0.00158 44.999c-7.1001 0-12.857-5.755-12.857-12.855l0.00158-25.716c0-3.551-2.8795-6.4285-6.4286-6.4285h-25.714c-7.1001 0-12.857-5.757-12.857-12.857h45z" fill="#FF8802"/></svg>
```
The `version` attribute is unnecessary.

2021-04-11 15:58 UTC, phallobst commented
Sorry, but the 2FA only applies to the HiDrive service. As long as the regular domain/hosting service of strato.de does not provide 2FA as well, we cannot merge this change in the current form. You are welcome to re-open this PR once the situation changes.

2021-04-11 15:58 UTC, closed without merging