Update infobip
2factorauth/twofactorauth pull request #5365
Opened 2021-03-22 18:12 UTC by ApCoder123

The current doc link doesn't work and this blog post was the best I could find

2021-03-22 18:19 UTC, Carlgo11 requested changes

2021-03-22 18:19 UTC, Carlgo11 commented on _data/developer.yml
>        - sms
Sounds like they support 2FA using both SMS and Phone calls.
```suggestion
      - sms
      - phone
```

2021-03-22 18:22 UTC, Carlgo11 approved these changes

2021-03-28 09:32 UTC, phallobst approved these changes

2021-03-28 09:32 UTC, merged