Add Intuit
2factorauth/twofactorauth pull request #5376
Opened 2021-03-22 22:35 UTC by 40504

2021-03-23 09:01 UTC, Carlgo11 requested changes

2021-03-23 09:01 UTC, Carlgo11 commented on _data/finance.yml
> +
```suggestion
    regions:
    - us

```

2021-03-23 09:01 UTC, Carlgo11 commented
Since Mint is a part of Intuit and they seem to use the same login process I think this PR can replace the Mint entry completly.
Especially since they use the same domain name.

2021-06-03 08:21 UTC, 40504 commented
https://accounts-help.intuit.com/app/intuit/1995121

2021-06-03 15:37 UTC, Carlgo11 approved these changes

2021-08-25 07:18 UTC, phallobst approved these changes

2021-08-25 07:19 UTC, merged