Add Hack The Box
2factorauth/twofactorauth pull request #5396
Opened 2021-03-23 12:27 UTC by ApCoder123

2021-03-23 23:03 UTC, Carlgo11 requested changes
There are already similar services listed under `education`. Whilst not being a perfect fit I still think it's the better category for now.
If enough similar services gets added we could potentially make it a seperate category in the future.

2021-03-24 20:53 UTC, Carlgo11 approved these changes

2021-03-24 21:34 UTC, phallobst commented
If only we had keywords instead of categories... :wink:

2021-03-24 21:34 UTC, phallobst approved these changes

2021-03-24 21:34 UTC, merged