Add Arduino
2factorauth/twofactorauth pull request #5397
Opened 2021-03-23 12:29 UTC by ApCoder123

2021-03-23 12:31 UTC, Carlgo11 approved these changes

2021-03-28 18:23 UTC, phallobst requested changes
Better have the icon centered in a square viewbox:
![img](https://raw.githubusercontent.com/phallobst/phallobst/main/resterampe/arduino.svg)

2021-03-28 18:50 UTC, ApCoder123 commented
Ok, updated.

2021-04-02 11:41 UTC, phallobst approved these changes

2021-04-02 11:41 UTC, merged