Add LogicMonitor
2factorauth/twofactorauth pull request #5398
Opened 2021-03-23 12:34 UTC by ApCoder123

2021-03-28 18:27 UTC, phallobst requested changes

2021-03-28 18:27 UTC, phallobst commented on _data/developer.yml
> +      - totp
```suggestion
```
I don't think regular `totp` is available here - you _have_ to use Authy, it seems.

2021-04-02 11:40 UTC, phallobst approved these changes

2021-05-28 20:47 UTC, Carlgo11 approved these changes

2021-05-28 20:47 UTC, merged