Add Voyager
2factorauth/twofactorauth pull request #5426
Opened 2021-03-26 00:21 UTC by 40504

2021-04-02 10:34 UTC, phallobst approved these changes

2021-04-07 18:56 UTC, ApCoder123 requested changes

2021-04-07 18:56 UTC, ApCoder123 commented on _data/cryptocurrencies.yml
> +    doc: https://www.investvoyager.com/blog/introducing-2fa/
```suggestion
    doc: https://support.investvoyager.com/support/solutions/43000367274
```

I reckon that this page is a more useful doc

2021-04-11 08:09 UTC, ApCoder123 approved these changes

2021-04-11 08:10 UTC, merged