Add Termius
2factorauth/twofactorauth pull request #5437
Opened 2021-03-27 13:16 UTC by ApCoder123

2021-04-02 10:55 UTC, phallobst requested changes
I think this entry belongs in the "Remote Access" category.

2021-04-04 09:28 UTC, phallobst requested changes

2021-04-04 09:28 UTC, phallobst commented on _data/remote.yml
> +    doc: https://github.com/Crystalnix/Termius-Documentation/blob/master/general/what_is_2fa.md
```suggestion
    doc: https://docs.termius.com/account/subscription#enable-2fa
```

2021-04-05 19:21 UTC, phallobst approved these changes

2021-05-20 09:15 UTC, Carlgo11 approved these changes

2021-05-20 09:15 UTC, merged