Update Fastmail
2factorauth/twofactorauth pull request #5438
Opened 2021-03-27 13:19 UTC by ApCoder123

Fastmail uses u2f according to doc.

2021-03-28 21:39 UTC, Carlgo11 requested changes

2021-03-28 21:39 UTC, Carlgo11 commented on _data/email.yml
> +      - u2f
Actually they refer to both u2f and the proprietary hardware system of Yubico called "Yubikey OTP"
```suggestion
      - hardware
      - u2f
```

2021-04-03 12:17 UTC, phallobst approved these changes

2021-04-03 14:31 UTC, Carlgo11 approved these changes

2021-04-03 14:31 UTC, merged