Add Baremetrics
2factorauth/twofactorauth pull request #5441
Opened 2021-03-27 14:06 UTC by ApCoder123

Although the doc doesn't say, it uses TOTP
![image](https://user-images.githubusercontent.com/20560218/112723305-a58cab00-8f05-11eb-9c71-06ea4f1e261f.png)

2021-04-02 11:09 UTC, phallobst requested changes

2021-04-02 11:09 UTC, phallobst commented on _data/other.yml
> +    doc: https://changelog.baremetrics.com/two-factor-authentication-3X2v9m
This page doesn't provide any meaningful information, The screenshot is much more helpful.
```suggestion
```

2021-04-04 09:29 UTC, phallobst approved these changes

2021-05-22 05:17 UTC, Carlgo11 approved these changes

2021-05-22 05:17 UTC, merged