Add NairaEx
2factorauth/twofactorauth pull request #5453
Opened 2021-03-28 23:34 UTC by 40504

2021-04-03 11:53 UTC, phallobst requested changes

2021-04-03 11:53 UTC, phallobst commented on _data/cryptocurrencies.yml
> +      - email
```suggestion
```
Does this refer to the "IP authorize via email" entry on the doc page? If so, it probably doesn't apply here.

2021-04-03 23:46 UTC, 40504 commented
<img width="1204" alt="1" src="https://user-images.githubusercontent.com/71176569/113494310-605d1000-94e7-11eb-8503-738e1dd790da.png">

how PIN should be categorized?

2021-04-05 19:16 UTC, phallobst commented
PIN is probably "something you know", i.e. similar to a password. That is not a second factor.

2021-04-10 17:12 UTC, phallobst approved these changes

2021-04-10 19:27 UTC, ApCoder123 requested changes

2021-04-10 19:27 UTC, ApCoder123 commented on _data/cryptocurrencies.yml
> +
```suggestion
    regions:
      - ng

```

The website mentions 

> Nigeria's Premier Bitcoin Exchange

Is this site available outside of Nigeria?

2021-04-11 08:08 UTC, ApCoder123 requested changes

2021-04-11 08:08 UTC, ApCoder123 commented on _data/cryptocurrencies.yml
> +      - ng
```suggestion
      - ng

```
There should be a new line between entries.

2021-04-11 15:56 UTC, ApCoder123 approved these changes

2021-04-11 15:56 UTC, merged