Add BuyCoins
2factorauth/twofactorauth pull request #5454
Opened 2021-03-28 23:34 UTC by 40504

2021-04-03 11:57 UTC, phallobst approved these changes

2021-04-07 17:11 UTC, ApCoder123 requested changes

2021-04-07 17:11 UTC, ApCoder123 commented on _data/cryptocurrencies.yml
> +
```suggestion
    regions:
      - ng

```

According to the [terms and conditions](https://buycoins.africa/terms/):

> Your eligibility to access certain BuyCoins services also depends on the country in which you reside. At the moment, BuyCoins operates in Nigeria, and is only available to users who hold Nigerian bank accounts.

2021-04-10 20:13 UTC, ApCoder123 reviewed
According to the docs:

> BuyCoins Two-Factor Authentication requires you to enter an OTP sent to your phone each time you want to:
> 
> Buy Coins
> Sell Coins
> Send Coins to another Wallet

This sounds to me like [authorization](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#a-note-on-definitions) rather than authentication, so I don't believe it meets the definitions for the site.

2021-04-10 23:52 UTC, 40504 commented
> According to the docs:
> 
> > BuyCoins Two-Factor Authentication requires you to enter an OTP sent to your phone each time you want to:
> > Buy Coins
> > Sell Coins
> > Send Coins to another Wallet
> 
> This sounds to me like [authorization](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#a-note-on-definitions) rather than authentication, so I don't believe it meets the definitions for the site. Please do correct me if the site does provide 2FA that meets the definitions.

I created an account and can confirm you're right. So I close this pr.

2021-04-10 23:52 UTC, closed without merging