Add GoPro
2factorauth/twofactorauth pull request #5485
Opened 2021-04-02 12:13 UTC by ApCoder123

Decided to use the favicon for the icon, as the logo is too rectangular.

2021-04-04 09:45 UTC, phallobst requested changes
I suggest to go with the normal "too rectangular" logo instead of just the blue square.

2021-04-05 19:35 UTC, phallobst requested changes
That logo doesn't look incredibly appealing either... How about this one (it has a white box at the right, don't worry):
![](https://raw.githubusercontent.com/phallobst/phallobst/main/resterampe/gopro.svg)

2021-04-10 09:44 UTC, phallobst approved these changes

2021-05-12 22:09 UTC, Carlgo11 approved these changes

2021-05-12 22:10 UTC, merged