nfcu also has sms 2fa
2factorauth/twofactorauth pull request #5494
Opened 2021-04-02 19:53 UTC by 7redeagle

https://www.navyfederal.org/services/security/two-step-verification.html

2021-04-02 19:57 UTC, ApCoder123 requested changes

2021-04-02 19:57 UTC, ApCoder123 commented on _data/banking.yml
>      doc: https://nfcucloud.custhelp.com/app/answers/list/c/543
```suggestion
    doc: https://www.navyfederal.org/services/security/two-step-verification.html
```

2021-04-02 21:32 UTC, ApCoder123 approved these changes

2021-04-04 18:47 UTC, phallobst approved these changes

2021-04-07 16:50 UTC, merged