Add Current RMS
2factorauth/twofactorauth pull request #5497
Opened 2021-04-02 20:51 UTC by ApCoder123

Although the docs make it seem like only Authy can be used, according to the enable page

> If you are already using another authenticator app, we will provide a QR code to scan on the next screen.

![image](https://user-images.githubusercontent.com/20560218/113453226-71c9ed80-93fd-11eb-921a-372ef110578d.png)

2021-04-04 18:35 UTC, phallobst requested changes
This SVG version of the icon seems to be better:
![](https://raw.githubusercontent.com/phallobst/phallobst/main/resterampe/current-rms.svg)

2021-04-04 20:49 UTC, phallobst approved these changes

2021-05-12 21:13 UTC, Carlgo11 approved these changes

2021-05-12 21:13 UTC, Carlgo11 commented
@ApCoder123 can you fix the merge conflict please?

2021-05-13 07:27 UTC, merged