Add ContentStack
2factorauth/twofactorauth pull request #5500
Opened 2021-04-02 21:12 UTC by ApCoder123

2021-04-04 18:46 UTC, phallobst requested changes

2021-04-04 18:46 UTC, phallobst commented on _data/developer.yml
> +      - totp
```suggestion
      - proprietary
```
This website does not seem to use the regular `totp` style token generation, but the proprietary Authy method instead.

2021-04-04 20:48 UTC, phallobst approved these changes

2021-04-07 16:23 UTC, Carlgo11 approved these changes

2021-04-07 16:23 UTC, merged