Add Quidco
2factorauth/twofactorauth pull request #5501
Opened 2021-04-03 12:04 UTC by ApCoder123

2021-04-04 18:53 UTC, phallobst requested changes
I don't think this fits into "Retail". It's similar to "AwardWallet" in the "Other" category.

2021-04-04 19:14 UTC, ApCoder123 commented
Ok, category updated.

2021-04-04 20:47 UTC, phallobst approved these changes

2021-05-19 21:41 UTC, Carlgo11 approved these changes

2021-05-19 21:41 UTC, merged