Add Cashrewards
2factorauth/twofactorauth pull request #5502
Opened 2021-04-03 12:13 UTC by ApCoder123

2021-04-04 18:55 UTC, phallobst requested changes
See #5501 - this should go into "Other" as well.

2021-04-04 19:14 UTC, ApCoder123 commented
Ok, category updated.

2021-04-04 20:47 UTC, phallobst approved these changes

2021-05-19 21:43 UTC, Carlgo11 approved these changes

2021-05-19 21:43 UTC, merged