Add PracticePanther
2factorauth/twofactorauth pull request #5505
Opened 2021-04-03 14:15 UTC by ApCoder123

2021-04-05 07:40 UTC, phallobst requested changes
The icon in SVG format:
![](https://raw.githubusercontent.com/phallobst/phallobst/main/resterampe/practicepanther.svg)

2021-04-09 20:40 UTC, phallobst approved these changes

2021-05-12 21:40 UTC, Carlgo11 requested changes

2021-05-12 21:40 UTC, Carlgo11 commented on _data/legal.yml
> +
```suggestion
    regions:
      - us

```

2021-05-13 16:20 UTC, Carlgo11 approved these changes

2021-05-13 16:20 UTC, merged