Update Three
2factorauth/twofactorauth pull request #5509
Opened 2021-04-03 15:14 UTC by ApCoder123

Three now support SMS 2FA

![image](https://user-images.githubusercontent.com/20560218/113482664-94a8e000-9497-11eb-8dd0-72b9e9a9eabc.png)

2021-04-03 17:27 UTC, Carlgo11 approved these changes

2021-04-05 08:23 UTC, phallobst requested changes

2021-04-05 08:23 UTC, phallobst commented on _data/utilities.yml
> +      - sms
```suggestion
      - sms
    doc: http://www.three.co.uk/hub/stay-safe-from-fraudsters/
```
I mean, it's not much, but better than nothing...

2021-04-09 20:42 UTC, phallobst approved these changes

2021-04-10 09:04 UTC, merged