Update BTC Markets
2factorauth/twofactorauth pull request #5524
Opened 2021-04-04 14:29 UTC by ApCoder123

Update doc link

2021-04-09 20:33 UTC, phallobst requested changes

2021-04-09 20:33 UTC, phallobst commented on _data/cryptocurrencies.yml
> +    doc: https://www.btcmarkets.net/frequently-asked-questions#what-is-two-factor-authentication-2fa
```suggestion
    doc: https://www.btcmarkets.net/frequently-asked-questions
```
The direct link does not work for me, as it's not a regular HTML anchor.

2021-04-11 07:58 UTC, phallobst approved these changes

2021-05-12 21:38 UTC, Carlgo11 approved these changes

2021-05-12 21:38 UTC, merged