Add Brex
2factorauth/twofactorauth pull request #5542
Opened 2021-04-05 19:26 UTC by ApCoder123

2021-04-10 09:42 UTC, phallobst requested changes

2021-04-10 09:42 UTC, phallobst commented on _data/finance.yml
> +
From their FAQ:
> Only companies organized and registered in the United States (such as C-corps, S-corps, LLCs, or LLPs) may apply for a Brex Account.

```suggestion
    regions:
      - us

```

2021-04-11 08:00 UTC, phallobst approved these changes

2021-05-12 13:50 UTC, Carlgo11 approved these changes

2021-05-12 13:50 UTC, merged