Add Canary
2factorauth/twofactorauth pull request #5544
Opened 2021-04-05 19:38 UTC by ApCoder123

2021-04-10 09:43 UTC, phallobst approved these changes

2021-04-11 19:24 UTC, Carlgo11 approved these changes

2021-04-11 19:26 UTC, Carlgo11 commented
Maybe a regions array could be used here?
Seems like they sell to the U.S. but support Germany and France as well.

2021-04-11 19:29 UTC, Carlgo11 requested changes

2021-04-11 19:29 UTC, Carlgo11 commented on _data/iot.yml
> +
```suggestion
    regions:
      - ca
      - de
      - fr
      - gb
      - ie
      - us

```

2021-04-27 19:41 UTC, Carlgo11 approved these changes

2021-04-27 19:41 UTC, merged