Add docker files
2factorauth/twofactorauth pull request #5546
Opened 2021-04-05 21:13 UTC by Carlgo11

Adds an option to test the site locally with the same scripts and environment that the GH action uses.

2021-04-10 09:52 UTC, phallobst requested changes

2021-04-10 09:52 UTC, phallobst commented on _deployment/minify-js.sh
> +#!/bin/sh
```suggestion
#!/bin/sh
PATH="./node_modules/.bin:$PATH"
```
Now this should also work for people that have installed the node modules locally.

2021-04-11 08:18 UTC, phallobst approved these changes

2021-05-12 13:43 UTC, Carlgo11 commented
Closing in favor of #5695

2021-05-12 13:43 UTC, closed without merging

2024-11-14 01:28 UTC, alphachart reviewed
.