Add Frontify
2factorauth/twofactorauth pull request #5566
Opened 2021-04-06 19:59 UTC by ApCoder123

2021-04-10 15:13 UTC, phallobst requested changes
This is their current logo. Was it updated recently, perhaps?
![](https://raw.githubusercontent.com/phallobst/phallobst/main/resterampe/frontify.svg)

2021-04-10 15:50 UTC, ApCoder123 commented
Ok, updated the logo. It must have been changed very recently, as I only got that logo off their site a few days ago.

2021-04-11 08:09 UTC, phallobst approved these changes

2021-05-12 13:52 UTC, Carlgo11 approved these changes

2021-05-12 13:52 UTC, merged