Add Swyftx
2factorauth/twofactorauth pull request #5569
Opened 2021-04-06 22:59 UTC by 40504

2021-04-07 16:05 UTC, Carlgo11 requested changes

2021-04-07 16:05 UTC, Carlgo11 commented on _data/cryptocurrencies.yml
> +
Looks like they only support customers in the following countries:
```suggestion
    regions:
      - au
      - nz
      - gb
      - ca

```

2021-04-08 15:52 UTC, Carlgo11 approved these changes

2021-04-08 16:01 UTC, ApCoder123 approved these changes

2021-04-08 16:01 UTC, merged