Add Macquarie Bank
2factorauth/twofactorauth pull request #5585
Opened 2021-04-10 02:50 UTC by jimsug

G'day,

Adding this... the default setting is 2FA for authorisation, though it is possible to enable 2FA for authentication (see: https://help.macquarie.com/s/article/What-are-the-different-levels-of-security, "Ultimate"" security) on browser logins, so I believe this fits our definition.

2021-04-10 09:00 UTC, ApCoder123 requested changes
Thanks for your PR.
- Please make the changes requested. 
- SVGs are the preferred format for icons. Please use this one:
![SVG Logo](https://raw.githubusercontent.com/ApCoder123/ApCoder123/master/5585.svg)

2021-04-10 09:00 UTC, ApCoder123 commented on _data/banking.yml
> +
```suggestion
    exception: "2FA is only available when 'Ultimate' security is enabled and an SMS-capable phone is required for initial setup.
    regions:
      - au

```

2021-04-11 15:29 UTC, jimsug commented on _data/banking.yml
> +
Requested changes implemented in 141c82fb and 4e1a263e.

2021-04-11 15:33 UTC, ApCoder123 approved these changes

2021-04-11 15:40 UTC, phallobst approved these changes

2021-04-11 15:47 UTC, merged