Update Delighted
2factorauth/twofactorauth pull request #5594
Opened 2021-04-11 23:27 UTC by 40504

2021-04-12 11:08 UTC, ApCoder123 requested changes

2021-04-12 11:08 UTC, ApCoder123 commented on _data/other.yml
> +    doc: https://help.delighted.com/article/526-security-and-privacy#2-step
```suggestion
    doc: https://help.delighted.com/article/526--#2-step
```

2021-04-12 15:27 UTC, 40504 commented
@ApCoder123 Done ✅

2021-04-12 15:41 UTC, ApCoder123 approved these changes

2021-04-13 23:56 UTC, Carlgo11 approved these changes

2021-04-13 23:56 UTC, merged