Add bitrise
2factorauth/twofactorauth pull request #5623
Opened 2021-04-19 23:21 UTC by 40504

2021-04-20 11:27 UTC, ApCoder123 requested changes

2021-04-20 11:27 UTC, ApCoder123 commented on _data/developer.yml
> +  - name: bitrise
```suggestion
  - name: Bitrise
```
Their webpage and social media uses this capitalisation

2021-04-20 19:41 UTC, ApCoder123 approved these changes

2021-04-25 08:06 UTC, phallobst approved these changes

2021-04-25 08:06 UTC, merged