Update VoIP.ms
2factorauth/twofactorauth pull request #5632
Opened 2021-04-24 11:22 UTC by ApCoder123

Closes #5627

2021-04-25 08:42 UTC, phallobst requested changes

2021-04-25 08:42 UTC, phallobst commented on _data/utilities.yml
> +    doc: https://wiki.voip.ms/article/TOTP_Authentication
```suggestion
    doc: https://wiki.voip.ms/article/TOTP_Authentication
    exception: "Only one of the 2FA methods can be enabled at the same time."
```

2021-04-25 15:06 UTC, phallobst approved these changes

2021-04-28 22:39 UTC, Carlgo11 approved these changes

2021-04-28 22:40 UTC, merged