Add Passfolio
2factorauth/twofactorauth pull request #5634
Opened 2021-04-24 11:46 UTC by ApCoder123

SMS 2FA is not mentioned on doc page. Info can be found at https://www.passfolio.com/faq/two-factor-authentication

2021-04-25 08:53 UTC, phallobst approved these changes

2021-05-12 13:11 UTC, Carlgo11 requested changes

2021-05-12 13:11 UTC, Carlgo11 commented on _data/investing.yml
> +    exception: "SMS 2FA is enabled by default."
I don't think it being enabled by default is a good exception note :thinking: 
```suggestion
```

2021-05-12 19:04 UTC, Carlgo11 approved these changes

2021-05-12 19:05 UTC, merged