Add Heap
2factorauth/twofactorauth pull request #5650
Opened 2021-04-27 11:49 UTC by 40504

2021-04-27 13:57 UTC, ApCoder123 requested changes

2021-04-27 13:57 UTC, ApCoder123 commented on _data/other.yml
> +    doc: https://help.heap.io/category/heap-administration/secure-access/
```suggestion
    doc: https://help.heap.io/heap-administration/secure-access/2fa/
```

2021-04-27 13:57 UTC, ApCoder123 commented on _data/other.yml
> +
```suggestion
    exception: "2FA is only available for users on the Business plan."

```

2021-05-01 08:56 UTC, phallobst approved these changes

2021-05-01 10:14 UTC, ApCoder123 approved these changes

2021-05-01 10:14 UTC, merged