Add Mercury to banking
2factorauth/twofactorauth pull request #5653
Opened 2021-04-27 20:16 UTC by jkeuhlen

This was started previously in https://github.com/2factorauth/twofactorauth/pull/4643, but the PR went stale. 

Mercury requires 2FA for all approved customers. 

(Copying the image from previous PR) 
![image](https://user-images.githubusercontent.com/10284802/116307109-25a36c00-a763-11eb-808f-f09723f3a0bf.png)

2021-04-28 14:48 UTC, ApCoder123 requested changes

2021-04-28 14:48 UTC, ApCoder123 commented on _data/banking.yml
> +    doc: https://help.mercury.com/t/m1h3d07/setting-up-2fa
```suggestion
    doc: https://help.mercury.com/t/m1h3d07
```

2021-04-28 16:15 UTC, ApCoder123 approved these changes

2021-05-01 09:15 UTC, phallobst approved these changes

2021-05-01 09:15 UTC, merged