Add Domain
2factorauth/twofactorauth pull request #5659
Opened 2021-04-27 23:55 UTC by 40504

<img width="1427" alt="4" src="https://user-images.githubusercontent.com/71176569/116326477-d2620580-a7c4-11eb-856c-d606cd326088.png">

2021-04-28 15:21 UTC, ApCoder123 requested changes

2021-04-28 15:21 UTC, ApCoder123 commented on _data/other.yml
> +
```suggestion
    exception: "2FA is not available on the app."

```

> You don’t need 2FA for the Domain or Commercial Real Estate app. Only website.

2021-04-28 18:55 UTC, ApCoder123 approved these changes

2021-05-01 09:24 UTC, phallobst approved these changes

2021-05-01 09:24 UTC, merged