Update Flexera
2factorauth/twofactorauth pull request #5662
Opened 2021-04-28 00:34 UTC by 40504

2021-05-01 09:02 UTC, phallobst requested changes

2021-05-01 09:02 UTC, phallobst commented on _data/cloud.yml
> +      - totp
```suggestion
      - totp
      - sms
```

2021-05-01 09:18 UTC, 40504 commented
If services support multiple 2FA options, like in Flexera case, TOTP, and SMS, it's not better `doc` to link to https://docs.flexera.com/svr/ug/Content/helplibrary/Configure_Two_Factor_Authentication__2FA_.htm instead of https://docs.flexera.com/svr/ug/Content/helplibrary/Token_Based_Two_Factor_Authentication.htm

2021-05-01 09:45 UTC, phallobst commented
The link to "Configure Two-Factor Authentication" seems to be the better choice here.

2021-05-01 10:19 UTC, 40504 commented
> The link to "Configure Two-Factor Authentication" seems to be the better choice here.

done

2021-05-01 10:22 UTC, ApCoder123 commented
From the doc link provided, it appears that 2FA only applies to their [Software Vulnerability Research](https://www.flexera.com/products/software-vulnerability-research.html) product. I can't find any reference to 2FA for the main Flexera account. If this is the case, then it may be better to leave the current entry how it is and create a separate entry in the security category? It seems to use a separate login system as well - this is the [main login page](https://app.flexera.com/login) while it seems you can only login to the Vulnerability research product [here](https://csi7.secunia.com/csi/).

2021-05-01 10:30 UTC, 40504 commented
I can't confirm because don't have an account there. From this page, https://app.flexera.com/login seems like they have multiple services with separate login details

2021-05-01 10:32 UTC, ApCoder123 commented
Okay, since that is the case, I think that a separate entry should be made for the Vulnerability Research product in the `Security` category, and the current Flexera entry should be kept as it is.

2021-05-01 10:34 UTC, 40504 commented
doc for 2FA is related to Flexera’s Software Vulnerability Research
<img width="1193" alt="1" src="https://user-images.githubusercontent.com/71176569/116779937-7d024e80-aa79-11eb-8c69-5f0377599edb.png">

2021-08-17 16:01 UTC, Carlgo11 commented
@40504 do you intend on updating the PR with the [suggestions](https://github.com/2factorauth/twofactorauth/pull/5662#issuecomment-830607457) from @ApCoder123?

2021-08-18 23:31 UTC, 40504 commented
At the moment I can't. I will do it as soon as possible.

2021-09-02 20:44 UTC, closed without merging