Add Caspio
2factorauth/twofactorauth pull request #5663
Opened 2021-04-28 00:55 UTC by 40504

https://howto.caspio.com/caspio-id/managing-caspio-id/ -> scroll down to `Enabling two-factor authentication` section

2021-04-28 15:14 UTC, ApCoder123 requested changes

2021-04-28 15:14 UTC, ApCoder123 commented on _data/developer.yml
> +    doc: https://howto.caspio.com/caspio-id/managing-caspio-id/
```suggestion
    doc: https://howto.caspio.com/caspio-id/managing-caspio-id/#Enable2FA
```

2021-04-28 18:54 UTC, ApCoder123 approved these changes

2021-05-01 09:19 UTC, phallobst approved these changes

2021-05-01 09:19 UTC, merged