Add Drift
2factorauth/twofactorauth pull request #5669
Opened 2021-04-28 16:32 UTC by 40504

2021-04-28 18:54 UTC, ApCoder123 reviewed
Please could you provide some evidence that 2FA is offered. 
The doc page linked just states that all Drift employees use 2FA, with no mention of 2FA being available for Drift users.

> Everyone on our team has two-factor authentication setup for their accounts where possible, which means that nobody can access their accounts without a security code sent to our mobile devices at the time of attempted login.

2021-04-28 21:17 UTC, 40504 commented
Ups, I forgot to attach the screenshot 🤦🏻‍♂️

2021-04-28 22:05 UTC, 40504 commented
<img width="1423" alt="1" src="https://user-images.githubusercontent.com/71176569/116478550-82e01000-a87e-11eb-829e-3198a656c8e5.png">

2021-04-28 22:42 UTC, Carlgo11 approved these changes

2021-04-29 14:39 UTC, ApCoder123 requested changes

2021-04-29 14:39 UTC, ApCoder123 commented on _data/other.yml
> +    doc: https://gethelp.drift.com/hc/en-us/articles/360019504214
```suggestion

```
Probably best to remove this doc link - it doesn't tell a user any useful info about 2FA on their account

2021-04-30 14:50 UTC, ApCoder123 approved these changes

2021-04-30 14:50 UTC, merged