Add IG
2factorauth/twofactorauth pull request #5673
Opened 2021-05-01 15:42 UTC by ApCoder123

2021-05-01 21:25 UTC, phallobst approved these changes

2021-05-27 23:40 UTC, Carlgo11 requested changes

2021-05-27 23:40 UTC, Carlgo11 commented on entries/i/ig.com.json
> +      ],
```suggestion
      ],
      "custom-software": [ "IG Authentication" ],
```

2021-05-27 23:44 UTC, Carlgo11 approved these changes

2021-05-27 23:45 UTC, merged