Update signNow
2factorauth/twofactorauth pull request #5676
Opened 2021-05-03 23:37 UTC by 40504

2021-05-04 00:10 UTC, 40504 commented
<img width="988" alt="2" src="https://user-images.githubusercontent.com/71176569/116947740-d509a280-ac7d-11eb-9eb3-be1f977efda2.png">

2021-05-04 11:50 UTC, ApCoder123 reviewed
The doc page describes how to protect a specific document with "_dual factor authentication_". This seems to force the signer to receive a text to the number that the sender has specified before they can sign the document. I don't believe that this meets our definitions of 2FA, as it does not affect the user's sign in process & is not protecting the account with a redundant layer of authentication. Please confirm whether the account has 2FA or just specific documents.

2021-05-04 12:00 UTC, 40504 commented
Just created an account and can confirm:
<img width="749" alt="2" src="https://user-images.githubusercontent.com/71176569/117000255-197a5a00-ace1-11eb-82b4-8beb9c949e09.png">

2021-05-04 12:05 UTC, ApCoder123 requested changes

2021-05-04 12:05 UTC, ApCoder123 commented on _data/other.yml
> +    doc: https://www.signnow.com/features/setup-dual-factor-authentication
```suggestion

```
I think we can remove the doc link - it doesn't have any useful info about the 2FA features that you showed in the screenshot.

2021-05-04 12:09 UTC, 40504 commented
done

2021-05-04 14:39 UTC, ApCoder123 approved these changes

2021-05-08 16:00 UTC, phallobst approved these changes

2021-05-08 16:00 UTC, merged