Add CoinSmart
2factorauth/twofactorauth pull request #5689
Opened 2021-05-07 12:19 UTC by 40504

2021-05-07 13:12 UTC, ApCoder123 requested changes

2021-05-07 13:12 UTC, ApCoder123 commented on _data/cryptocurrencies.yml
> +    doc: https://coinspot.zendesk.com/hc/en-us/sections/115000049254
```suggestion
    doc: https://coinsmart.zendesk.com/hc/en-us/articles/360014948893
```
The doc link provided is for a different website called "CoinSpot". Here is the doc link I think you meant to include.

2021-05-07 13:12 UTC, ApCoder123 commented on _data/cryptocurrencies.yml
> +    regions:
I don't think a regions array is required here - the site seems to allow users from different countries to register on the sign up page and the terms of service mention that users outside of Canada can sign up.

2021-05-08 15:57 UTC, ApCoder123 approved these changes

2021-05-09 21:07 UTC, phallobst approved these changes

2021-05-09 21:07 UTC, merged