Add NDAX
2factorauth/twofactorauth pull request #5690
Opened 2021-05-07 12:26 UTC by 40504

2021-05-07 13:03 UTC, ApCoder123 requested changes

2021-05-07 13:03 UTC, ApCoder123 commented on _data/cryptocurrencies.yml
> +    doc: https://help.ndax.io/en-ca/article/setting-up-google-authenticator-for-2fa-mfz047/
```suggestion
    doc: https://help.ndax.io/en-ca/category/2fa-rgk6to/
```
I think that this page may be slightly more useful

2021-05-07 17:20 UTC, Carlgo11 approved these changes

2021-05-08 15:49 UTC, ApCoder123 approved these changes

2021-05-08 15:49 UTC, merged