Update Pepper
2factorauth/twofactorauth pull request #5737
Opened 2021-06-03 18:56 UTC by ApCoder123

2021-06-19 09:30 UTC, phallobst requested changes

2021-06-19 09:30 UTC, phallobst commented on entries/p/pepper.com.json
> +    ],
May sorting these alphabetically is useful:
```suggestion
    "additional-domains": [
      "chollometro.com",
      "dealabs.com",
      "desidime.com",
      "hotukdeals.com",
      "mydealz.de",
      "pelando.com.br",
      "pepper.it",
      "pepper.pl",
      "pepper.ru",
      "preisjaeger.at",
      "promodescuentos.com"
    ],
```

2021-06-19 15:11 UTC, phallobst approved these changes

2021-07-08 21:34 UTC, Carlgo11 approved these changes

2021-07-08 21:34 UTC, merged