Rename BofI Federal Bank to Axos Bank
2factorauth/twofactorauth pull request #5741
Opened 2021-06-05 10:25 UTC by phallobst

2FA is not supported, it seems

2021-06-05 11:28 UTC, ApCoder123 requested changes

2021-06-05 11:28 UTC, ApCoder123 commented on entries/a/axosbank.com.json
> +    ]
```suggestion
    ],
    "regions": [
      "us"
    ]
```

2021-06-05 16:44 UTC, ApCoder123 approved these changes

2021-06-09 03:21 UTC, Carlgo11 approved these changes

2021-06-09 03:21 UTC, merged