Update Garmin
2factorauth/twofactorauth pull request #5743
Opened 2021-06-05 16:42 UTC by ApCoder123

Closes #5740

2021-06-06 09:29 UTC, phallobst requested changes

2021-06-06 09:29 UTC, phallobst commented on entries/g/garmin.com.json
> +    "documentation": "https://support.garmin.com/en-GB/?faq=uGHS8ZqOIhA0usBzBMdJu7&productID=73207",
```suggestion
    "documentation": "https://support.garmin.com/en-GB/?faq=uGHS8ZqOIhA0usBzBMdJu7",
```

2021-06-06 10:21 UTC, phallobst approved these changes

2021-06-09 03:26 UTC, Carlgo11 approved these changes

2021-06-09 03:26 UTC, merged