Add MoneyGuide
2factorauth/twofactorauth pull request #5759
Opened 2021-06-09 19:34 UTC by ApCoder123

Closes #5752

2021-06-09 19:36 UTC, phallobst requested changes

2021-06-09 19:36 UTC, phallobst commented on entries/m/moneyguidepro.com.json
> +  "Evestnet MoneyGuide": {
```suggestion
  "Envestnet MoneyGuide": {
```

2021-06-09 20:18 UTC, phallobst approved these changes

2021-06-09 21:35 UTC, Carlgo11 requested changes
Looks like it's a U.S. only thing.

2021-06-09 21:35 UTC, Carlgo11 commented on entries/m/moneyguidepro.com.json
> +    ]
```suggestion
    ],
    "regions": [
      - us
    ]
```

2021-06-10 11:47 UTC, Carlgo11 approved these changes

2021-06-10 11:47 UTC, merged