Update bankofamerica.com.json
2factorauth/twofactorauth pull request #5769
Opened 2021-06-11 18:43 UTC by person1234-ux

bank of amarica is adding support for yubikeys meaning they now support hardware keys
  "custom-hardware",

2021-06-11 18:51 UTC, ApCoder123 requested changes, later dismissed

2021-06-11 18:51 UTC, ApCoder123 commented on entries/b/bankofamerica.com.json
>        "email"
```suggestion
      "email",
```

2021-06-11 18:53 UTC, person1234-ux commented
Sorry about the typo with the pull request causing an invalid json file now it all fixed

2021-06-11 18:58 UTC, ApCoder123 reviewed
Based on the link you added in #5771 (for future reference, you don't need to create an issue along with a PR. It is perfectly fine to have all the info in the pull request 😁), it looks like they haven't yet added support for U2F keys, but are planning to. Can you confirm if that is the case? It might be better to wait until they implement support for hardware 2FA before displaying it on the site.

2021-06-11 18:58 UTC, ApCoder123 commented on entries/b/bankofamerica.com.json
> +      "custom-hardware"
```suggestion
      "u2f"
```
Based on the link provided in the issue, U2F is supported.

2021-06-11 19:00 UTC, person1234-ux commented
Yes this is the case

2021-06-11 19:07 UTC, person1234-ux commented
when you make updates like that do you want me to re-resquest review or should I just leave it ounce I approve your changes

2021-06-11 19:40 UTC, ApCoder123 commented
> when you make updates like that do you want me to re-resquest review or should I just leave it ounce I approve your changes

It's up to you - I get notified when you make changes, so it's not really necessary to re-request review.

2021-06-19 09:26 UTC, phallobst approved these changes

2021-06-22 13:55 UTC, Carlgo11 approved these changes

2021-06-22 13:55 UTC, merged