Add Unstoppable Domains
2factorauth/twofactorauth pull request #5779
Opened 2021-06-13 22:42 UTC by jkmartindale

Currently Alexa #10,909, <https://unstoppabledomains.com>

2021-06-14 09:51 UTC, ApCoder123 commented
Since there is no documentation available, can you provide us with screenshots of the setup/login process as evidence of 2FA? Please remember to block out any personal information.

2021-06-14 09:55 UTC, ApCoder123 requested changes

2021-06-14 09:55 UTC, ApCoder123 commented on entries/u/unstoppabledomains.com.json
> +    "img": "unstoppabledomains.com.png",
Please use this SVG version of the logo instead:
![](https://raw.githubusercontent.com/ApCoder123/ApCoder123/master/5779.svg)

2021-06-15 04:32 UTC, jkmartindale commented
![image](https://user-images.githubusercontent.com/11380394/121991759-f1f9c100-cd65-11eb-89e1-1fed556647a4.png)  
![image](https://user-images.githubusercontent.com/11380394/121992341-0ee2c400-cd67-11eb-9f96-73299ff12de2.png)  
![image](https://user-images.githubusercontent.com/11380394/121992819-0048dc80-cd68-11eb-895a-7e4d66c165f3.png)  
![image](https://user-images.githubusercontent.com/11380394/121992868-10f95280-cd68-11eb-9345-cb6d1219fdf9.png)  
![image](https://user-images.githubusercontent.com/11380394/121992965-42721e00-cd68-11eb-869c-55f6471e2d7a.png)  
![image](https://user-images.githubusercontent.com/11380394/121993013-5b7acf00-cd68-11eb-8001-3930b5916d28.png)

2021-06-15 11:05 UTC, ApCoder123 approved these changes
Thanks!

2021-06-15 16:32 UTC, Carlgo11 approved these changes

2021-06-15 16:32 UTC, merged