Update wordpress.com.json
2factorauth/twofactorauth pull request #5785
Opened 2021-06-15 03:47 UTC by person1234-ux

updated wordpress to include the fact that a hardware key with webauth is now an option for 2fa

2021-06-15 16:55 UTC, Carlgo11 requested changes

2021-06-15 16:55 UTC, Carlgo11 commented on entries/w/wordpress.com.json
> +      "custom-software"
I see you tried to add security keys. Here's how to do that:
```suggestion
      "u2f"
```

2021-06-15 17:28 UTC, Carlgo11 approved these changes

2021-06-19 09:01 UTC, phallobst approved these changes

2021-06-19 09:01 UTC, merged