Add Marketo
2factorauth/twofactorauth pull request #5791
Opened 2021-06-15 11:39 UTC by ApCoder123

Implements changes from 9f23768

2021-06-19 09:18 UTC, phallobst approved these changes

2021-07-08 21:44 UTC, Carlgo11 approved these changes

2021-07-08 21:49 UTC, Carlgo11 requested changes

2021-07-08 21:49 UTC, Carlgo11 commented on entries/m/marketo.com.json
> +      "facebook": "Marketo",
Not sure if this page is the correct one. I can't see as I don't have Facebook :sweat: 
```suggestion
      "facebook": "adobemarketoengage",
```

2021-08-17 18:45 UTC, Carlgo11 approved these changes

2021-08-17 18:47 UTC, Carlgo11 commented
Depends on #5791

2021-08-23 12:15 UTC, merged