Add CuriosityStream
2factorauth/twofactorauth pull request #5797
Opened 2021-06-15 12:02 UTC by ApCoder123

Supersedes #4947

2021-06-17 15:20 UTC, Carlgo11 requested changes

2021-06-17 15:20 UTC, Carlgo11 commented on entries/c/curiositystream.com.json
> +      "facebook": "curiositystream",
Facebook page is region locked :/
```suggestion
```

2021-06-17 19:50 UTC, Carlgo11 approved these changes

2021-06-19 08:47 UTC, phallobst approved these changes

2021-06-19 08:48 UTC, merged