Add Localize
2factorauth/twofactorauth pull request #5826
Opened 2021-06-19 14:25 UTC by ApCoder123

2021-06-19 15:29 UTC, phallobst commented
The icon should not have the white backdrop in the middle:
![](https://raw.githubusercontent.com/phallobst/phallobst/main/resterampe/localizejs.com.svg)

2021-06-20 18:13 UTC, phallobst requested changes
Please rename the JSON file to `localizejs.com.json`.

2021-06-20 18:58 UTC, phallobst approved these changes

2021-07-08 21:51 UTC, Carlgo11 approved these changes

2021-07-08 21:51 UTC, merged