Update vy.no
2factorauth/twofactorauth pull request #5828
Opened 2021-06-19 22:54 UTC by 40504

2021-06-19 23:59 UTC, Carlgo11 requested changes

2021-06-19 23:59 UTC, Carlgo11 commented on entries/v/vy.no.json
> +      "twitter": "VyNordic"
@VyNordic doesn't seem to be any official account. Use this one instead:
```suggestion
      "twitter": "vygruppen"
```

2021-06-20 00:51 UTC, Carlgo11 approved these changes

2021-06-20 06:21 UTC, phallobst approved these changes

2021-06-20 06:21 UTC, merged