Update Internet.bs
2factorauth/twofactorauth pull request #5842
Opened 2021-06-20 01:52 UTC by 40504

2021-06-20 06:34 UTC, phallobst requested changes
Please rename the JSON file to "internetbs.net.json".

2021-06-20 21:21 UTC, Carlgo11 approved these changes

2021-06-20 22:49 UTC, 40504 commented
> Please rename the JSON file to "internetbs.net.json".

Done ✅

2021-06-21 21:34 UTC, phallobst approved these changes

2021-06-21 21:34 UTC, merged