Add File Name Checking to JSON Validation Tests
2factorauth/twofactorauth pull request #5846
Opened 2021-06-20 18:59 UTC by ApCoder123

Adds a quick test to make sure that the file name matches the `domain` field in the file. For example, this test would fail in cases such as #5842 and #5826 where the file name does not match the domain.

2021-06-20 19:08 UTC, phallobst requested changes

2021-06-20 19:08 UTC, phallobst commented on tests/validate-json.rb
> +    Recieved: #{file.split('/')[2]}. Expected: #{document.values[0]['domain'] + '.json'}"
```suggestion
    Received: #{file.split('/')[2]}. Expected: #{document.values[0]['domain'] + '.json'}"
```

2021-06-27 23:11 UTC, Carlgo11 approved these changes
Should we use this instead of the domain tag then?

2021-07-05 20:42 UTC, phallobst approved these changes

2021-07-05 20:42 UTC, merged