Update RBC Royal Bank
2factorauth/twofactorauth pull request #5847
Opened 2021-06-20 23:19 UTC by 40504

I'm not sure what type of 2fa is used, please check documentation page :
https://www.rbcroyalbank.com/caribbean/digital-hub/security-two-factor.html

2021-06-21 17:45 UTC, ApCoder123 requested changes
From the links provided, it looks like 2FA for RBC is only available in the Caribbean. 

Given that this is the case, I think it makes sense to break the RBC entries into one without 2FA and RBC Caribbean with 2FA, similar to this:
![image](https://user-images.githubusercontent.com/20560218/122804605-05ee7700-d2c0-11eb-9915-10989fad6dcf.png)

- Please create a new entry under `entries/c/caribbean.rbcroyalbank.com`
- Make sure to add the region codes for the countries listed below. They can be found on [this page](http://www.rbcroyalbank.com/caribbean/tt/index.html?cc=tt_15#)
- ![image](https://user-images.githubusercontent.com/20560218/122804486-e22b3100-d2bf-11eb-991f-e57e30db4470.png)
- The 2FA type would be `custom-software` based on the description of what is needed to create a Soft Token:

> The Advice Centre representative will provide you with the information needed to setup your Soft Token including:
> Name: RBC User ID
> Serial Number
> Activation Code

```JSON
"custom-software": [
  "Entrust Identity Guard"
]
```

- It looks like `custom-hardware` is also available, but only for business customers (There should be a `notes` field to mention this)

Thanks.

2021-06-22 10:40 UTC, ApCoder123 requested changes

2021-06-22 10:40 UTC, ApCoder123 commented on entries/c/caribbean.rbcroyalbank.com.json
> +    "keywords": [
```suggestion
    "regions": [
```

2021-06-22 10:40 UTC, ApCoder123 commented on entries/c/caribbean.rbcroyalbank.com.json
> +    ]
```suggestion
    ],
    "keywords": [
      "banking"
    ]
```

2021-06-22 10:40 UTC, ApCoder123 commented on entries/c/caribbean.rbcroyalbank.com.json
> +      "custom-software"
```suggestion
      "custom-software",
      "custom-hardware"
```

2021-06-22 10:40 UTC, ApCoder123 commented on entries/c/caribbean.rbcroyalbank.com.json
> +    ],
```suggestion
    ],
    "custom-software": [
      "Entrust Identity Guard"
    ],
    "notes": "Hardware 2FA methods are only available for business customers",
```

2021-06-22 11:30 UTC, ApCoder123 approved these changes

2021-06-23 17:08 UTC, phallobst approved these changes

2021-06-23 17:08 UTC, merged