Add Hostwinds
2factorauth/twofactorauth pull request #5850
Opened 2021-06-21 00:41 UTC by 40504

<img width="1150" alt="1" src="https://user-images.githubusercontent.com/71176569/122693449-3390dd00-d23a-11eb-9a78-d5adbe2fe40f.png">

2021-06-21 09:45 UTC, ApCoder123 requested changes
The screenshot provided doesn't really show what types of 2FA are available. Would you be able to take a screenshot of the setup process as evidence? Thanks.

2021-06-21 09:45 UTC, ApCoder123 commented on entries/h/hostwinds.com.json
> +    "domain": "hostwinds.com",
```suggestion
    "domain": "hostwinds.com",
    "additional-domains": [
      "hostwinds.co.uk",
      "hostwinds.in",
      "hostwinds.ng",
      "hostwinds.cn",
      "hostwinds.de",
      "hostwinds.es",
      "hostwinds.pt",
      "hostwinds.fr",
      "hostwinds.ru",
      "hostwinds.nl",
      "hostwinds.kr",
      "hostwinds.it",
      "hostwinds.ae"
    ]
```

2021-06-21 15:20 UTC, 40504 commented
![image](https://user-images.githubusercontent.com/71176569/122786820-fe75a080-d2b4-11eb-8e0c-11b5204ab02a.jpeg)

2021-06-22 10:51 UTC, ApCoder123 approved these changes

2021-06-23 00:29 UTC, Carlgo11 approved these changes
I think we may need to look at regex support for additional-domains :sweat:

2021-06-23 00:29 UTC, merged