Add Niagahoster
2factorauth/twofactorauth pull request #5852
Opened 2021-06-21 01:30 UTC by 40504

2021-06-21 09:36 UTC, ApCoder123 commented
Since there is no documentation available, please could you provide us with screenshots of the setup/login process as evidence of 2FA? Please remember to block out any personal information.

2021-06-21 09:37 UTC, ApCoder123 requested changes

2021-06-21 09:37 UTC, ApCoder123 commented on entries/n/niagahoster.co.id.json
> +    ],
```suggestion
    ],
    "documentation": "https://www.niagahoster.co.id/kb/fitur-keamanan-terbaru-member-area-niagahoster-two-factor-authentication-2fa"
```

2021-06-21 17:47 UTC, ApCoder123 requested changes

2021-06-21 17:47 UTC, ApCoder123 commented on entries/n/niagahoster.co.id.json
> +    ]
```suggestion
    ],
    "regions": [
      "id"
    ]
```

2021-06-22 07:24 UTC, ApCoder123 approved these changes

2021-06-22 13:53 UTC, Carlgo11 approved these changes

2021-06-22 13:53 UTC, merged