Add Arkansas Tech University
2factorauth/twofactorauth pull request #5853
Opened 2021-06-21 12:46 UTC by AnalogCyan

Add Arkansas Tech University as they are now fully implementing 2FA.

2021-06-21 16:18 UTC, Carlgo11 requested changes, later dismissed
SVG logos are preferred. Please search for one and if you can't find any, use a PNG image that is exactly 32x32 pixels, doesn't contain any text and less than 2KiB in file size.

2021-06-23 01:09 UTC, 40504 commented
@AnalogCyan look at this :), enjoy

<img width="90" src="https://raw.githubusercontent.com/40504/twofactorauth/084b717bdae376d2ad38339f4a730f5504522d19/img/e/atu.edu.svg">

2021-06-23 01:16 UTC, AnalogCyan commented
@40504 nice, thanks!

2021-06-23 16:53 UTC, phallobst approved these changes

2021-06-23 19:17 UTC, ApCoder123 requested changes

2021-06-23 19:17 UTC, ApCoder123 commented on entries/a/atu.edu.json
> +    ]
```suggestion
    ],
    regions: [
      "us"
    ]
```

2021-07-05 11:45 UTC, ApCoder123 approved these changes

2021-07-05 11:46 UTC, merged