Add RapidAPI
2factorauth/twofactorauth pull request #5861
Opened 2021-06-25 00:53 UTC by 40504

<img width="738" alt="1" src="https://user-images.githubusercontent.com/71176569/123352794-61d72b00-d560-11eb-80fb-004dec1682f8.png">
<img width="768" alt="2" src="https://user-images.githubusercontent.com/71176569/123352809-67cd0c00-d560-11eb-9caf-c938ac21c35f.png">
<img width="750" alt="3" src="https://user-images.githubusercontent.com/71176569/123352837-774c5500-d560-11eb-8c7e-d11ee0e56eca.png">

2021-06-25 13:32 UTC, ApCoder123 requested changes

2021-06-25 13:32 UTC, ApCoder123 commented on entries/r/rapidapi.com.json
> +    ],
```suggestion
    ],
    "documentation": "https://docs.rapidapi.com/docs/account-creation-and-settings#two-factor-authentication-2fa",
```

2021-06-25 13:43 UTC, ApCoder123 approved these changes

2021-06-26 14:32 UTC, phallobst approved these changes

2021-06-26 14:32 UTC, merged