Add Sinch
2factorauth/twofactorauth pull request #5862
Opened 2021-06-25 12:30 UTC by 40504

<img width="2354" alt="2" src="https://user-images.githubusercontent.com/71176569/123424974-d1c9cd80-d5c1-11eb-87db-c63e690f0f7c.png">

2021-06-25 13:37 UTC, ApCoder123 approved these changes

2021-06-26 14:40 UTC, phallobst requested changes

2021-06-26 14:40 UTC, phallobst commented on entries/s/sinch.com.json
> +    ],
```suggestion
    ],
    "documentation": "https://community.sinch.com/t5/Account-Management/How-do-I-enable-2FA-in-the-Sinch-Customer-Dashboard/ta-p/7191",
```

2021-06-27 11:09 UTC, phallobst approved these changes

2021-06-27 11:09 UTC, merged