Add Hostek.com
2factorauth/twofactorauth pull request #5867
Opened 2021-06-25 15:49 UTC by 40504

2021-06-25 18:42 UTC, ApCoder123 requested changes

2021-06-25 18:42 UTC, ApCoder123 commented on entries/h/hostek.com.json
> +  "Hostek.com": {
```suggestion
  "Hostek": {
```

2021-06-25 18:42 UTC, ApCoder123 commented on entries/h/hostek.com.json
> +    "domain": "hostek.com",
```suggestion
    "domain": "hostek.com",
    "additional-domains": [
      "hostek.co.uk"
    ],
```

2021-06-28 00:13 UTC, Carlgo11 approved these changes

2021-06-28 09:36 UTC, ApCoder123 approved these changes

2021-06-28 09:36 UTC, merged

2021-06-29 00:01 UTC, 40504 commented
![image](https://user-images.githubusercontent.com/71176569/123717798-e639ee80-d87d-11eb-94cd-db8868597ce9.jpeg)

2021-06-29 00:04 UTC, 40504 commented
Also in terms & conditions they called their self HOSTEK.COM

2021-06-29 00:05 UTC, 40504 commented
https://hostek.com/tos.html

2021-06-29 13:57 UTC, 40504 commented
@Carlgo11 @ApCoder123 what do you think about this?

2021-06-29 14:18 UTC, ApCoder123 commented
Hmm... They don't seem to be very consistent with their brand name. E.g. 

The `<title>` tag on their website uses "Hostek" rather than "Hostek.com"
![image](https://user-images.githubusercontent.com/20560218/123812691-32bc1300-d8ec-11eb-9e15-577d0cc5211b.png)

and they refer to themselves as "Hostek" on Linkedin as well
![image](https://user-images.githubusercontent.com/20560218/123813022-77e04500-d8ec-11eb-9374-5d91c25b40f8.png)

Most of the entries on the site don't tend to include a full domain name either, so I think it is probably fine how it is at the moment.