Update API Documentation
2factorauth/twofactorauth pull request #5872
Opened 2021-06-26 16:05 UTC by ApCoder123

2021-06-28 19:27 UTC, Carlgo11 approved these changes

2021-07-01 18:59 UTC, phallobst requested changes

2021-07-01 18:59 UTC, phallobst commented on api.md
> +|img|String||Image name used. If this is not defined, the image name is `domain`.png|
```suggestion
|img|String||Image name used. If this is not defined, the image name is `domain`.svg|
```

2021-07-01 19:03 UTC, phallobst approved these changes

2021-07-01 19:03 UTC, merged