Update 1Password
2factorauth/twofactorauth pull request #5875
Opened 2021-06-26 19:53 UTC by ApCoder123

2021-08-01 18:38 UTC, phallobst requested changes

2021-08-01 18:38 UTC, phallobst commented on entries/1/1password.com.json
> +    "recovery": "https://support.1password.com/two-factor-authentication/#if-you-lose-access-to-your-authenticator-app",
It's the same page as `documentation`, just with an anchor - this provides no additional info.
```suggestion
```

2021-08-01 19:00 UTC, phallobst approved these changes

2021-08-23 23:58 UTC, Carlgo11 approved these changes

2021-08-23 23:58 UTC, merged