Add Regions to Food
2factorauth/twofactorauth pull request #5883
Opened 2021-06-27 14:40 UTC by ApCoder123

2021-06-27 15:44 UTC, Carlgo11 approved these changes

2021-08-23 10:16 UTC, phallobst requested changes
Some regions are missing:
- `au` for "DoorDash"
- several ones for "Taco Bell" (according to https://www.yum.com/wps/portal/yumbrands/Yumbrands/company/our-brands/taco-bell)

2021-08-23 10:16 UTC, phallobst commented on entries/d/deliveroo.com.json
> +      "kw"
```suggestion
      "kw",
      "de",
      "tw"
```

2021-08-23 10:16 UTC, phallobst commented on entries/d/deliveroo.com.json
> +      "deliveroo.com.kw"
```suggestion
      "deliveroo.com.kw",
      "deliveroo.de",
      "deliveroo.tw"
```

2021-08-23 12:42 UTC, phallobst approved these changes

2021-08-23 12:42 UTC, merged