Add Regions to Entertainment
2factorauth/twofactorauth pull request #5889
Opened 2021-06-29 11:28 UTC by ApCoder123

Also moved IBM video to other, as I don't feel that it fits the current category particularly well

2021-06-29 22:39 UTC, Carlgo11 approved these changes

2021-08-23 10:54 UTC, phallobst requested changes
Did you want to add regions to "TuneCore" as well?

2021-08-23 10:54 UTC, phallobst commented on entries/h/hotstar.com.json
>        "in",
```suggestion
      "in",
      "id",
      "my",
      "th",
      "ph",
```

2021-08-23 12:34 UTC, ApCoder123 commented
Although tunecore has regional domains, from what I could tell, it was available globally:
![image](https://user-images.githubusercontent.com/20560218/130447762-3caa5249-ba68-4229-ae1b-ced6ce1b32a1.png)
See https://web.tunecore.com/signup

2021-08-23 12:44 UTC, phallobst approved these changes

2021-08-23 12:44 UTC, merged