Add Shift4Shop
2factorauth/twofactorauth pull request #5922
Opened 2021-07-06 23:13 UTC by 40504

also found this one: https://support.3dcart.com/knowledgebase/article/View/866/11

2021-07-07 17:14 UTC, ApCoder123 requested changes

2021-07-07 17:14 UTC, ApCoder123 commented on entries/s/shift4shop.com.json
> +		"documentation": "https://www.shift4shop.com/lp/features/2-factor-authentication/",
```suggestion
		"documentation": "https://support.3dcart.com/knowledgebase/article/View/866/11/",
```
I think it's probably better to use this as the documentation link. The current one links to this one as a "Knowledgebase Article" and this one provides far greater detail and clarity than the current one.

2021-07-08 11:24 UTC, ApCoder123 approved these changes

2021-07-08 21:15 UTC, Carlgo11 approved these changes

2021-07-08 21:15 UTC, merged