Add Cordial
2factorauth/twofactorauth pull request #5934
Opened 2021-07-08 00:29 UTC by 40504

2021-07-08 21:13 UTC, Carlgo11 approved these changes

2021-07-10 13:48 UTC, phallobst requested changes

2021-07-10 13:48 UTC, phallobst commented on entries/c/cordial.com.json
> +    "recovery": "https://support.cordial.com/hc/en-us/requests/new",
This page isn't really helpful by itself - the link is provided on the doc page as well, so that should be enough.
```suggestion
```

2021-07-10 18:36 UTC, phallobst approved these changes

2021-07-10 18:36 UTC, merged