Add Buildium
2factorauth/twofactorauth pull request #5936
Opened 2021-07-08 01:14 UTC by 40504

2021-07-08 11:53 UTC, ApCoder123 requested changes

2021-07-08 11:53 UTC, ApCoder123 commented on entries/b/buildium.com.json
> +    "domain": "buildium.com",
```suggestion
    "domain": "buildium.com",
    "additional-domains": [
      "managebuilding.com"
    ],
```
It seems that they have a login page available at this domain

2021-07-08 11:53 UTC, ApCoder123 commented on entries/b/buildium.com.json
> +      "totp"
```suggestion
      "totp",
      "call"
```
The doc page also mentions 2FA via phone call

2021-07-28 15:24 UTC, ApCoder123 approved these changes

2021-08-01 18:27 UTC, phallobst approved these changes

2021-08-01 18:27 UTC, merged