Update BigCommerce
2factorauth/twofactorauth pull request #5962
Opened 2021-07-13 22:48 UTC by 40504

2021-07-15 19:07 UTC, ApCoder123 requested changes

2021-07-15 19:07 UTC, ApCoder123 commented on entries/b/bigcommerce.com.json
> -      "url": "https://www.bigcommerce.com",
The `url` field is needed in this case, as the `url.rb` tests are failing

2021-07-16 12:10 UTC, ApCoder123 approved these changes

2021-07-17 10:01 UTC, phallobst commented
It's not really `retail`, is it?

2021-07-17 21:26 UTC, 40504 commented
> It's not really `retail`, is it?

I don't know which category to include 🤷🏻‍♂️

2021-07-29 13:35 UTC, ApCoder123 commented
> It's not really `retail`, is it?

@phallobst Do you think that other similar services should be moved out of the `retail` category? E.g. Shift4Shop and Shopify

2021-07-31 09:36 UTC, phallobst commented
Maybe a `commerce` category would be useful. This could include some more entries:
2checkout, clover, refersion, revenuecat, spring, thrivecart, tito

2021-08-15 19:20 UTC, phallobst approved these changes

2021-08-15 19:21 UTC, merged