Add Plus500
2factorauth/twofactorauth pull request #5965
Opened 2021-07-14 00:08 UTC by 40504

<img width="1427" alt="1" src="https://user-images.githubusercontent.com/71176569/125540643-955859ac-ed4b-4e9c-942d-e24dc20daa60.png">

2021-07-15 19:30 UTC, ApCoder123 requested changes

2021-07-15 19:30 UTC, ApCoder123 commented on entries/p/plus500.com.json
> +      "plus500.ru"
```suggestion
    "additional-domains": [
      "plus500.at",
      "plus500.bg",
      "plus500.co.il",
      "plus500.co.nz",
      "plus500.co.uk",
      "plus500.com.au",
      "plus500.com.hr",
      "plus500.com.mt",
      "plus500.cz",
      "plus500.es",
      "plus500.de",
      "plus500.dk",
      "plus500.ee",
      "plus500.fr",
      "plus500.fi",
      "plus500.gr",
      "plus500.hu",
      "plus500.is",
      "plus500.it",
      "plus500.lv",
      "plus500.lt",
      "plus500.nl",
      "plus500.pt",
      "plus500.pl",
      "plus500.ru",
      "plus500.ro",
      "plus500.sk",
      "plus500.si",
      "plus500.se"
```

2021-07-15 19:30 UTC, ApCoder123 commented on entries/p/plus500.com.json
> +      "sms"
```suggestion
      "sms",
      "call"
```
The screenshot provided also mentions 2FA via phone call

2021-07-16 12:20 UTC, ApCoder123 approved these changes

2021-08-01 18:34 UTC, phallobst approved these changes

2021-08-01 18:34 UTC, merged