Add Onet
2factorauth/twofactorauth pull request #5980
Opened 2021-07-19 08:18 UTC by mimi89999

2021-07-19 14:03 UTC, ApCoder123 requested changes

2021-07-19 14:03 UTC, ApCoder123 commented on entries/o/onet.pl.json
> +    "url": "https://www.onet.pl/",
```suggestion
```
The `url` field is not necessary in this case, as the site is accessible from https://`domain`

2021-07-19 14:03 UTC, ApCoder123 commented on img/o/onet.pl.svg
> +<?xml version="1.0" encoding="UTF-8" standalone="no"?>
Please use this optimised SVG instead:
![](https://raw.githubusercontent.com/ApCoder123/ApCoder123/master/5980.svg)

2021-07-19 14:03 UTC, ApCoder123 commented on entries/o/onet.pl.json
> +    ]
```suggestion
    ],
    "regions": [
      "pl"
    ]
```

2021-07-19 14:35 UTC, ApCoder123 approved these changes

2021-07-24 10:59 UTC, phallobst approved these changes

2021-07-24 10:59 UTC, merged