Add Delivra
2factorauth/twofactorauth pull request #5984
Opened 2021-07-19 14:24 UTC by ApCoder123

2021-08-15 21:24 UTC, Carlgo11 approved these changes

2021-08-23 08:31 UTC, phallobst requested changes

2021-08-23 08:31 UTC, phallobst commented on entries/d/delivra.com.json
> +      "communication"
```suggestion
      "marketing"
```

2021-08-23 12:45 UTC, phallobst approved these changes

2021-08-23 12:45 UTC, merged