Add Coinzilla
2factorauth/twofactorauth pull request #6019
Opened 2021-07-30 14:26 UTC by 40504

<img width="991" alt="23" src="https://user-images.githubusercontent.com/71176569/127667603-0774c20b-46ed-4b60-8101-1608118fe542.png">

![Group 12](https://user-images.githubusercontent.com/71176569/127667621-33c049c3-b02b-4227-a938-102a588e2417.png)

2021-08-15 19:17 UTC, phallobst requested changes

2021-08-15 19:17 UTC, phallobst commented on entries/c/coinzilla.com.json
> +      "cryptocurrencies"
This is rather a marketing website, right? Therefore, `communication` is (currently) the correct category.
```suggestion
      "communication"
```

2021-08-22 12:39 UTC, phallobst approved these changes

2021-08-22 23:50 UTC, Carlgo11 approved these changes

2021-08-22 23:51 UTC, merged