Documentation Improvements
2factorauth/twofactorauth pull request #6114
Opened 2021-09-05 19:25 UTC by ApCoder123

I've made a couple of modifications to the documentation:

- Consistency (Phrase "two factor authentication", rather than a mixture of "two factor auth" and "Two Factor Authentication")
- Remove outdated references (there were a couple of references to the old schema in CONTRIBUTING.md)
- Move new categories to end of contributing guidelines (the majority of contributors are looking to add sites)
- A couple of minor language changes & typo fixes 
- Mark v2 API as deprecated

2021-09-05 21:12 UTC, Carlgo11 approved these changes

2021-09-06 21:02 UTC, phallobst requested changes

2021-09-06 21:02 UTC, phallobst commented on CONTRIBUTING.md
> +The `language` field inside `contact` can be included for websites that are not in English. The language
Maybe it should be made clearer that the `language` is related to the communication channel(s) for the contact rather than the website itself.

2021-09-06 21:02 UTC, phallobst commented on CONTRIBUTING.md
>    for cleanliness.
```suggestion
- If a site supports TFA, their contact information is not needed and must be left out.
```

2021-09-06 21:02 UTC, phallobst commented on CONTRIBUTING.md
> +* Facebook can also be included using the `facebook` field
```suggestion
* Facebook can also be included using the `facebook` field.
```

2021-09-07 10:08 UTC, phallobst approved these changes

2021-09-07 10:08 UTC, merged