Remove SMS Requirement from wise.com
2factorauth/twofactorauth pull request #6119
Opened 2021-09-08 03:05 UTC by rkelly

wise.com works with Google Voice.

2021-09-09 15:54 UTC, ApCoder123 requested changes

2021-09-09 15:54 UTC, ApCoder123 commented on entries/w/wise.com.json
>      "documentation": "https://wise.com/help/12/managing-your-profile/2932125",
```suggestion
    "documentation": "https://wise.com/help/12/managing-your-profile/2932125",
    "notes": "SMS 2FA must be enabled before software methods can be enabled.",
```
Although Google Voice may be able to be used for SMS 2FA, the documentation page mentions that SMS 2FA must be enabled before the app can be used for 2FA, so a `notes` field is still required.

2021-09-18 11:55 UTC, ApCoder123 approved these changes

2021-09-18 20:30 UTC, Carlgo11 approved these changes
Thanks for the PR!

Btw, love your music :smile:

2021-09-19 19:36 UTC, merged