Add My Plesk
2factorauth/twofactorauth pull request #6122
Opened 2021-09-09 13:58 UTC by Crixu

## Site Name
My PLesk
##Site Url
https://my.plesk.com/
## Supported 2FA methods
- [x] TOTP (RFC-6238, Google Authenticator)
- [ ] Proprietary Software (Authy, Duo, etc.)
- [ ] FIDO2/U2F/WebAuthn security keys
- [ ] Proprietary hardware (Yubikey OTP, RSA keys, etc.)
- [ ] Phone calls
- [ ] SMS tokens
- [ ] Email tokens

## Eligbility
- [x] I have checked that the site meets twofactorauth.org's [contributing guidelines and site criteria.](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md)
- [x] The site is ranked within the top 200,000 sites on [Alexa](https://www.alexa.com/siteinfo/) or has a substantial social media following.
- [x] The site does not contain or promote content that violates twofactorauth.org's [excluded categories and websites guidelines](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md), including pornographic, discriminatory, or unlawful content.

##Additional Information:
While the software Plesk itself is for self-hosting or offer hosting services the new service My Plesk is a user portal with critical information and ability to gain access to the admins Plesk servers.

2021-09-09 14:06 UTC, Crixu commented
![Screenshot 2021-09-09 at 16 05 47](https://user-images.githubusercontent.com/1375321/132701013-5e87b3ad-3cbc-449f-83ef-4d8c3b936443.png)
Settings to enable MFA are located in the My Profile section

2021-09-15 11:41 UTC, Carlgo11 requested changes

2021-09-15 11:41 UTC, Carlgo11 commented on entries/m/my.plesk.com.json
> +      "hosting"
```suggestion
      "remote"
```
Given that My Plesk is neither a hosting provider or a VPS service I think Remote Access is a better category. Would you agree?

2021-09-23 15:26 UTC, Carlgo11 approved these changes

2021-09-23 19:23 UTC, ApCoder123 approved these changes

2021-09-23 19:23 UTC, merged