Add Trovo
2factorauth/twofactorauth pull request #6173
Opened 2021-10-06 17:29 UTC by phallobst

Closes #6172

2021-10-06 18:48 UTC, Carlgo11 requested changes

2021-10-06 18:48 UTC, Carlgo11 commented on entries/t/trovo.live.json
> +      "gaming"
Entertainment seems like a better fit.
```suggestion
      "entertainment"
```

2021-10-06 19:22 UTC, Carlgo11 approved these changes

2021-10-07 09:30 UTC, ApCoder123 approved these changes

2021-10-07 09:30 UTC, merged