Update GleSYS image
2factorauth/twofactorauth pull request #6174
Opened 2021-10-06 19:25 UTC by Carlgo11

And specify custom-software solutions.

2021-10-06 19:43 UTC, Carlgo11 commented
Still no documentation but when creating an account I found these notes:
![image](https://user-images.githubusercontent.com/3535780/136272248-9ccfe2ee-0ae3-4cf4-b6e0-ff9173405fe4.jpeg)![image](https://user-images.githubusercontent.com/3535780/136272249-85132825-3f31-4bcf-898b-50758b855489.jpeg)

2021-10-06 19:47 UTC, Carlgo11 commented
No documentation available but after signing up I found these notes on the settings page:
![IMG_1022](https://user-images.githubusercontent.com/3535780/136272823-8d7e63df-a7c0-4033-80fa-fef407e5e533.JPEG)
![IMG_1023](https://user-images.githubusercontent.com/3535780/136272826-52fc9995-692e-4e2a-b736-59642b459596.JPEG)

2021-10-07 21:26 UTC, phallobst requested changes

2021-10-07 21:26 UTC, phallobst commented on entries/g/glesys.com.json
>    "Glesys": {
```suggestion
  "GleSYS": {
```

2021-10-08 07:39 UTC, phallobst approved these changes

2021-10-08 07:43 UTC, dsoegijono approved these changes

2021-10-08 08:08 UTC, merged