Update Sites - Backup
2factorauth/twofactorauth pull request #6176
Opened 2021-10-09 16:54 UTC by ApCoder123

- Added recovery documentation
- Specified custom-* values
- Updated a few doc links

2021-10-09 17:01 UTC, ApCoder123 commented
@Carlgo11 I think something might have gone wrong with overriding `redirect_uri_callback`?

2021-10-09 17:04 UTC, Carlgo11 commented
@ApCoder123 😩
I'll have a look at it when I get home in an hour.

2021-10-09 17:20 UTC, ApCoder123 commented
I've done some debugging and it looks like one of the redirects is to a relative path, which isn't handled by the new `redirect_uri_callback`. Adding the relevant code from [`default_redirect_uri_callback`](https://github.com/nahi/httpclient/blob/master/lib/httpclient.rb#L727) (which allows relative redirects) should solve the issue.

2021-10-09 17:29 UTC, phallobst requested changes

2021-10-09 17:29 UTC, phallobst commented on entries/m/mega.io.json
> +    "documentation": "https://mega.io/help/client/webclient/security-and-privacy#how-do-i-enable-two-factor-authentication-on-my-account-5bb525f9f1b70989348b45de",
```suggestion
    "documentation": "https://mega.io/help/client/webclient/security-and-privacy#5bb525f9f1b70989348b45de",
```

2021-10-11 20:05 UTC, phallobst commented on entries/d/drive.google.com.json
> +      "Google Prompts via Compatible iPhone App (Smart Lock, Gmail, Google app)"
That's a bit of a mouthful, isn't it? Wouldn't `Google Prompts` or `Google push notification` be sufficient? Nobody will be updating the list of compatible apps anyway.

2021-10-12 21:17 UTC, phallobst approved these changes

2021-10-15 18:03 UTC, Carlgo11 approved these changes

2021-10-15 18:03 UTC, merged