Replace PNG by SVG icons
2factorauth/twofactorauth pull request #6181
Opened 2021-10-10 11:00 UTC by phallobst

2021-10-13 01:37 UTC, Carlgo11 requested changes

2021-10-13 01:37 UTC, Carlgo11 commented on img/b/bitbond.com.svg
> +<svg xmlns="http://www.w3.org/2000/svg" xml:space="preserve" width="793.701" height="793.701"><path style="fill:#03a9f4" d="M566.929 41.989h226.772v226.772H566.929zM566.929 325.454h226.772v226.772H56
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><path fill="#03a9f4" d="M71 0h29v29H71Zm0 36h29v28H71Zm0 35h29v29H71ZM36 36h28v28H36Zm0 35h28v29H36ZM0 71h29v29H0Z"/></svg>
```

2021-10-13 01:37 UTC, Carlgo11 commented on img/b/brightbox.com.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="35.996" height="36" xml:space="preserve"><path d="M7.496 16.808a92.408 92.408 0 0 0-7.341 5.794.487.487 0 0 0-.095.589l6.078 10.262a.483.483 0 0 0 .562.
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" xml:space="preserve" viewBox="0 0 36 36"><path fill="#2ce0df" d="M7.5 15.3a92.4 92.4 0 0 0-7.34 5.8.49.49 0 0 0-.1.6l6.08 10.25a.48.48 0 0 0 .56.2 92.66 92.66 0 0 0 8.61-3.65A92.03 92.03 0 0 1 7.5 15.3zM29.3 3.85a92 92 0 0 0-8.61 3.66 92.57 92.57 0 0 1 7.81 13.19 91.22 91.22 0 0 0 7.34-5.8.48.48 0 0 0 .1-.58L29.86 4.04a.48.48 0 0 0-.56-.2Z"/><path fill="#a7f501" d="M20.69 7.5a91.94 91.94 0 0 0-5.8-7.34.49.49 0 0 0-.58-.1L4.04 6.14a.48.48 0 0 0-.2.56 92.07 92.07 0 0 0 3.66 8.6 92.48 92.48 0 0 1 13.19-7.8zm-5.38 21a91.98 91.98 0 0 0 5.8 7.34.49.49 0 0 0 .58.1l10.26-6.08a.49.49 0 0 0 .2-.56 93.16 93.16 0 0 0-3.65-8.6 92.58 92.58 0 0 1-13.2 7.8z"/><path fill="#01cc00" d="M20.69 7.5a92.53 92.53 0 0 0-13.2 7.8 92.64 92.64 0 0 0 7.82 13.2A92.42 92.42 0 0 0 28.5 20.7a92.17 92.17 0 0 0-7.81-13.2z"/></svg>
```

2021-10-13 01:37 UTC, Carlgo11 commented on img/b/bsag.de.svg
> +<svg xmlns="http://www.w3.org/2000/svg" version="1.1" id="svg9734" width="365.401" height="365.401"><defs id="defs9686"><style id="style9684">.a{fill:#fff}</style></defs><g id="g10289" transform="tra
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 365.4 365.4"><path fill="#fff" d="M316.3 182.7A133.7 133.7 0 0 0 182.6 49 133.7 133.7 0 0 0 49 182.7a133.7 133.7 0 0 0 133.7 133.7 133.7 133.7 0 0 0 133.6-133.7m-61.8 0a71.9 71.9 0 0 1-71.9 71.9 71.9 71.9 0 0 1-71.9-71.9 71.9 71.9 0 0 1 72-71.9 71.9 71.9 0 0 1 71.8 71.9"/><path fill="#e52629" d="M310.3 182.7A127.6 127.6 0 0 0 182.7 55.1 127.6 127.6 0 0 0 55.1 182.7a127.6 127.6 0 0 0 127.6 127.6 127.6 127.6 0 0 0 127.6-127.6m-49.4 0a78.2 78.2 0 0 1-78.2 78.2 78.2 78.2 0 0 1-78.3-78.2 78.2 78.2 0 0 1 78.3-78.2 78.2 78.2 0 0 1 78.2 78.2"/><path fill="#fff" d="M365.3 180.4v-55.2a2.4 2.4 0 0 0-2.4-2.4H236.8a26.8 26.8 0 0 0-11.6 2.7l-.3.1-45.8 23.2-14.2 7.2-45 22.2-4 1.8-.6.4a25.1 25.1 0 0 1-10 2.1H2.3a2.4 2.4 0 0 0-2.3 2.4v55.3a2.4 2.4 0 0 0 2.4 2.4h127a26.8 26.8 0 0 0 11.6-2.7l.3-.2 103.2-52.1 4.9-2.3.6-.3a25.1 25.1 0 0 1 10-2.1h103a2.4 2.4 0 0 0 2.4-2.5"/><path fill="#231f20" d="m242.7 182.3 4.9-2.3.7-.3a25.1 25.1 0 0 1 9.9-2.1h99.4a2.4 2.4 0 0 0 2.4-2.4v-44.7a2.4 2.4 0 0 0-2.4-2.4h-119a26.6 26.6 0 0 0-11.7 2.7l-.3.2-45.7 23.1-14.2 7.2-45 22.3-4 1.8-.7.3a25 25 0 0 1-9.9 2.1H7.7a2.4 2.4 0 0 0-2.4 2.5v44.6a2.4 2.4 0 0 0 2.4 2.4h119.9a26.6 26.6 0 0 0 11.6-2.7l.3-.1 103.2-52.2"/></svg>
```

2021-10-13 01:37 UTC, Carlgo11 commented on img/c/cloud.ca.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="87.099" height="95.309" viewBox="0 0 23.045 25.217"><path d="m3.64 159.925-6.548 3.982v-4.862a1.161 1.161 0 1 0-2.323 0v4.878l-6.613-3.962a1.23 1.23 0 1
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 23.045 25.217"><path d="m19.351 17.653-6.548 3.982v-4.862a1.161 1.161 0 1 0-2.323 0v4.878l-6.613-3.962a1.23 1.23 0 1 0-1.264 2.11l9.043 5.419 8.983-5.464a1.23 1.23 0 1 0-1.278-2.101m-16.89-2.3V8.119l4.708 2.809a1.161 1.161 0 1 0 1.19-1.995l-4.76-2.84 6.63-3.795A1.23 1.23 0 1 0 9.007.163L0 5.319v10.033a1.23 1.23 0 0 0 2.46 0M12.545.609a1.23 1.23 0 0 0 .441 1.684l6.502 3.803-4.587 2.814a1.161 1.161 0 1 0 1.214 1.98l4.47-2.74v7.043a1.23 1.23 0 1 0 2.46 0V5.327L14.228.169a1.23 1.23 0 0 0-1.683.44"/><path fill="#ee3425" d="M11.641 10.258a1.998 1.998 0 1 0 0 3.995 1.998 1.998 0 0 0 0-3.995"/></svg>
```

2021-10-13 01:37 UTC, Carlgo11 commented on img/c/coinapult.com.svg
> +<svg xmlns="http://www.w3.org/2000/svg" version="1.1" id="Layer_1" x="0" y="0" xml:space="preserve" width="21.7" height="21.7"><style type="text/css" id="style2395">.st3{fill:none;stroke:#75bda7;stro
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 21.7 21.7"><path fill="none" stroke="#75bda7" stroke-miterlimit="10" stroke-width="2.05" d="M5.79 2.3c-5.7 6.4-.5 14.2 4.9 14.7" class="st3"/><path fill="none" stroke="#75bda7" stroke-miterlimit="10" stroke-width=".51" d="M6.99 3.3c-4.6 5.2-.5 11.6 3.9 12"/><path fill="none" stroke="#75bda7" stroke-miterlimit="10" stroke-width="2.05" d="M14.29 16.9c1.2-.1 2.4-.6 3-1.2" class="st3"/><path fill="none" stroke="#75bda7" stroke-miterlimit="10" stroke-width=".51" d="M14.09 15.3c.2 0 1.3-.1 1.9-.7"/><path fill="#ea7c39" d="m4.99.9.8-.9c1.1 2.1 2.7 2.4 2.7 2.4l-.2.4 3.2 2.6s1.6-.5 2.5.4c.8 1 .3 2 .3 2.1l5 5.5.1.2-.2.1v1.4l-.7.8h-.1l-2.2-2v-.1l.2-.2c.5-.6.4-.5.4-.5l1.4-.1-4.6-4.2c-.2.1-.4.1-.5.2.2 3.3.5 6.6.7 9.9l2.8 2.8h-1.9l-.7-.9.1.9h-3.1l.1-.9-.7.9h-1.9c.9-.9 1.8-1.9 2.7-2.8.3-3.3.5-6.7.8-10-.4-.2-1-.5-1.2-1.1-.2-.6 0-1.2.1-1.4zm7.5 5.6c-.3 0-.6.3-.6.6s.3.6.6.6.6-.3.6-.6-.3-.6-.6-.6z"/></svg>
```

2021-10-13 01:37 UTC, Carlgo11 commented on img/c/coinfalcon.com.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="42" height="42"><path style="fill:#1ab6ff;fill-rule:evenodd" d="m42 12-6.347 7.623-10.266 5.063 3.126 2.585L21 30l-7.49-2.729 3.103-2.585-10.266-3.743L0
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 42 42"><path fill="#1ab6ff" d="m42 12-6.35 7.62L25.4 24.7l3.12 2.58L21 30l-7.49-2.73 3.1-2.58-10.26-3.75L0 12h9.44L21 23.8 32.56 12Zm-17 5.71-4 4.12-4-4.12Z"/></svg>
```

2021-10-13 01:37 UTC, Carlgo11 commented on img/d/degussa-bank.de.svg
> +<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" height="310" width="310"><style>.E{clip-path:url(#I)}.F{fill:#1d1d1b}</style><g transform="translate(1.3 101.2)"><de
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 310 310"><path fill-rule="evenodd" d="M77.9 130v18.3s0 1 .9 1.5c.8.6 1.9.6 1.9.6h2.2c6.3-.5 6.9-6.2 6.9-11.4 0-5-.8-10.6-6.2-11.1h-2.5c-.7 0-1.9 0-2.7.5a2 2 0 0 0-.5 1.6m-8.7-3.7h14.6c7.4.5 11.1 6.3 11 12.9-.1 7.4-4.5 13-13.8 13H69.2v-1.3h1.3c.9 0 1.5-.1 2.2-.8.6-.6.7-1.1.7-2.1v-18.6s0-1-1.2-1.4c-.6-.2-2.2-.2-2.2-.2h-.8zm156.6 15 3.7-9.5 4 9.5zm-9.7 11.6v-1.3c1.3-.2 3.9-.7 4.8-3.3l9.1-21.6h2l9.3 22.3c1.1 2.7 2.4 2.4 4.2 2.5v1.3h-12.1v-1.2c1.2 0 2.9.1 3.3-1.2.2-.6 0-1.3-.6-2.8l-2.2-5.4h-8.6l-1.9 4.8c-2.1 4.4 2.3 4.3 3.6 4.3v1.4h-10.9zM134 176l3.6-9.3 4.1 9.3zm-9.7 11.5v-1.3a6.7 6.7 0 0 0 5.5-4l8.2-20.7h2.1l9.2 22.2c1.1 2.7 2.5 2.4 4.4 2.5v1.3h-12v-1.2c1.2 0 2.9.1 3.3-1.2.2-.6 0-1.3-.6-2.8l-2.2-5.4h-8.8l-1.9 4.8c-2.1 4.6 3 4.3 4.3 4.3v1.4h-11.5zm-14.3-.3c2.7 0 7.5.2 10.3-.8 2.7-.9 5-2.5 5-5.9.1-4.3-3.8-6.9-7.5-7.2v-.1c3.7-.6 6.6-1.4 6.6-5.3 0-5.8-6.7-6.4-11.5-6.3h-11.8v1.4h2.1s1.2-.1 1.8.3c.5.3.4 1.5.4 1.5v19.1s.1 1.1-.3 1.6c-.5.6-1.9.6-1.9.6h-2v1.1zm.5-23.7c.7-.7 1.8-.5 2.9-.6 3.4.1 6.3.1 6 5.4-.2 3.4-3.3 3.6-6.2 3.5h-3.4V166c0 .1-.1-1.7.7-2.5m-.7 10.3h3.6c5.4-.1 7.3 2.6 7.3 6.2 0 2.7-.5 5.9-6.1 5.9H113s-1.9.2-2.7-.6c-.7-.7-.5-2.4-.5-2.4zm-15-21.4v-1.2h.9c.9 0 3.1-.1 3-2.7v-18.3s.3-2.7-4.3-2.4v-1.1h22.2l.1 9.7h-1c0-.6-.7-5.2-2.8-6.8-1.5-1.2-3.4-1.3-5.3-1.3h-2.3c-.9 0-2.6 0-2.4 1.9v7.9h1.4c1.6 0 2.7-.4 3.8-1.6 1.2-1.3 1.1-2.6 1.2-4.2h1.2v13.5h-1.4v-.6c-.2-4-1.6-5.6-4.2-5.7H103v10s-.2 1.4 1.8 1.3h3.4c7.8.4 7.7-6.3 8.2-8.5h1.1l-.2 10.2H94.8zm44.3-2.4a8.6 8.6 0 0 1-6.5 2.8c-6.3 0-11.7-6-11.7-13.5s5.1-13.2 11.4-13.5c2.7-.1 4.9.8 6.6 2.5.5.5 1.2 1.6 2.2-1.8h1v10.1h-1c-.7-2.7-3.4-9.4-8.6-9.3-5.8.1-7.2 6.3-7.2 11.7 0 5.8 2.3 12.4 8.4 12.2 2.9-.1 5.1-1.2 5.2-5.1 0-2.7 0-4.6-1.1-5.3-.9-.5-1.6-.6-2.8-.7v-.9h12.6v1c-1.1.1-4.5.1-4.2 3.1v9.4h-1.5c0-.8.1-3.4-.8-3.7-.9-.2-2 1-2 1m11.2-4.9v-15s-.2-1.6-1.4-2c-.6-.2-2.2-.2-2.2-.2h-.8v-1.2h12.9v1.2c-1.5.1-4.7-.4-4.4 3v13.4c-.6 9.9 12.9 8.8 12.9.9v-12.9a4 4 0 0 0-1.2-3.4c-.9-.9-1.9-1-3.1-1v-1.2h10.8v1.2c-1.4-.1-2.5-.1-3.4.9-.9.9-1.1 2-1 3.2v10.3c.4 9.4-5.5 10.7-8.2 10.8-7 .3-11-2.7-10.9-8m28 6c1.4 1.3 4.2 2 7 2 5.1 0 9.2-2.8 9-8-.1-3.6-2.4-6.9-7.8-8.2l-3.2-.9c-2.5-.7-5.4-1.1-5.4-4.1 0-2.7 2.3-4 5.1-4.2 5.2-.3 8.3 5.4 8.8 9.2h1l-.3-10.2h-.9s-.1 1.9-1 2.1c-.5.1-1.9-.8-1.9-.8a9.3 9.3 0 0 0-5.8-1.8c-5.2 0-8.2 2.8-8.2 7 0 3.8 2.6 6 6.8 7.2l2.2.6c3 1 7.1 1.1 7.2 5.4 0 3.3-2.2 4.9-5.3 4.9-4.7.1-9.3-5.4-10.2-10.6h-1.1v12h1s.2-2 1.1-2.3c.7-.1 1.9.7 1.9.7m22.9 0c1.4 1.3 4.2 2 7 2 5.1 0 9.2-2.8 9-8-.1-3.6-2.4-6.9-7.9-8.2l-3.2-.9c-2.5-.7-5.4-1.1-5.4-4.1 0-2.7 2.3-4 5.1-4.2 5.2-.3 8.3 5.4 8.8 9.2h1l-.3-10.2h-.9s-.1 1.9-1 2.1c-.5.1-1.9-.8-1.9-.8a9.3 9.3 0 0 0-5.8-1.8c-5.2 0-8.2 2.8-8.2 7 0 3.8 2.6 6 6.8 7.2l2.2.6c3 1 7.1 1.1 7.2 5.4 0 3.3-2.2 4.9-5.3 4.9-4.7.1-9.3-5.4-10.2-10.6h-1.1v12h1s.2-2 1.1-2.3c.8-.1 2 .7 2 .7m-47.3 11.6c3.9 0 4.2 1.3 4.2 4.8v14.4c-.4 3.7-2.2 4.2-3.8 4.3v1.4h10.3v-1.4c-3.7.1-4.8-2.6-4.8-4.9v-14l14.6 20.2h1.7v-19.1c0-3.8.9-5.1 4.5-5.7v-1.1h-10.9v1.3c3.3.3 4.6 1.8 4.6 5.6v11.7l-13-18.5h-7.4zm27.5 24.8h12.2v-1.1c-3.1-.1-4-.6-4-3.7v-5.3l3.8-3.8 6.3 10.7c.5 1.4-.4 2-2.9 1.9v1.2h13v-1.2c-1.5-.2-3.1.5-5.4-2.7l-7.9-12.8 4.5-4.6c3.1-3.2 4.9-3.4 7.2-3.6v-1.2h-12.5l.1 1.2c3.5-.2 4.1 2.4 2.1 4.1l-8.3 8.1v-8.8c0-3.4 1.5-3.4 4.3-3.4l.1-1.2h-12.8v1.2c3.2.2 4.6.4 4.4 3.4v16.6c.2 3-1.3 3.4-4.1 3.6v1.4z"/><path fill="#e1bb47" d="M310 161.7v12.4h-36l-2.8-5.7 6.9-13.9 3.5 7.2z"/><path fill="#1a2e50" d="M251.2 208.8H58.8l-30.1-60.6L0 148v-12h36l30.5 60.2h177.1l30.1-60.5h36.5l-.2 12.4-28.7.1Z"/><path fill="#e1bb47" d="M264.3 154.6 244 113.7H66.2L36 174.1 0 174v-12h28l30.6-60.8h193.1l19.6 39.5z"/></svg>
```

2021-10-13 01:37 UTC, Carlgo11 commented on img/e/entrust.net.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="39.507" height="39.507"><defs><linearGradient x1="18.384" y1="5.914" x2="18.384" y2="30.854" id="a" gradientTransform="matrix(.93063 0 0 1.07454 -.002 0
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 39.5 39.5"><defs><linearGradient id="a" x1="18.4" x2="18.4" y1="5.9" y2="30.9" gradientTransform="scale(.93063 1.07454)" gradientUnits="userSpaceOnUse"><stop offset="20%" stop-color="#C6168D"/><stop offset="80%" stop-color="#762B8A"/></linearGradient></defs><path fill="#762b8a" d="M19.8 39.5 2.6 29.6V10L19.8 0l17 9.9v19.7ZM34 28V11.5L19.8 3.2 5.4 11.5V28l14.4 8.3z"/><path fill="url(#a)" d="M28.7 21v-2.8l-8.9 5.1v-2.7l9-5.2v-2.3L17 6.4 5.5 13v13.4l11.6 6.7 11.6-6.7v-2.8l-8.9 5.2V26z" transform="translate(2.6)"/></svg>
```

2021-10-13 01:37 UTC, Carlgo11 commented on img/f/fruux.com.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="31.011" height="29.473" viewBox="0 0 8.205 7.798"><path d="M82.924 86.574a1.944 1.944 0 0 1 2.437-3.028 1.944 1.944 0 0 1-2.437 3.028zm4.082-3.499-1.073
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 10 10"><path fill="#ed1c24" d="M2.761 7.35a2.37 2.37 0 0 1 2.97-3.69 2.37 2.37 0 0 1-2.97 3.69Zm4.976-4.265-1.308.141a.384.384 0 0 1-.423-.34l-.141-1.31A4.245 4.245 0 0 0 .939 2.84a4.25 4.25 0 0 0-.183 5.085l1.308-.141a.385.385 0 0 1 .423.34l.142 1.309a4.248 4.248 0 0 0 5.108-6.348"/><path fill="#80cc28" d="M7.032.25 6.66.29a.412.412 0 0 0-.366.453l.171 1.573a.414.414 0 0 0 .452.364c.924-.097 1.89-.203 2.717-.292a.412.412 0 0 0 .364-.453l-.04-.376a.412.412 0 0 0-.453-.364l-1.933.21c-.916.096-.867.103 0 0l-.086-.79A.412.412 0 0 0 7.032.25Z"/></svg>
```

2021-10-13 01:37 UTC, Carlgo11 commented on img/k/koofr.eu.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="43.649" height="43.649" viewBox="0 0 11.549 11.549"><path d="m9.948 10.046-1.178-.62-1.179.62.225-1.312-.953-.929 1.318-.191.589-1.194.589 1.194 1.317.1
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 10 10"><path fill="#71b627" d="M8.61 8.7 7.6 8.16l-1.02.54.2-1.14-.83-.8 1.14-.17.51-1.03.51 1.04 1.15.15-.83.8ZM2.65 4.62l-.72 3.7c-.09.27-.22.47-.48.47a.47.47 0 0 1-.48-.48V3.46c0-.26.22-.47.48-.47h1.77v-1.3c0-.26.22-.48.49-.48h2.58a.5.5 0 0 1 .49.48v1.3h1.77c.26 0 .48.21.48.47v.5H3.49s-.72.01-.84.66zm5.9-2.6h-.81v-.33c0-.8-.65-1.45-1.45-1.45H3.71C2.9.24 2.26.9 2.26 1.7v.33h-.81C.65 2.02 0 2.67 0 3.46v4.85c0 .8.65 1.45 1.45 1.45h7.1c.8 0 1.45-.65 1.45-1.45V3.46c0-.8-.65-1.44-1.45-1.44Z"/></svg>
```

2021-10-13 01:37 UTC, Carlgo11 commented on img/m/mbconnectline.com.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="80.667" height="80.665" viewBox="0 0 21.343 21.343"><path d="M20.208 10.672a9.537 9.537 0 1 1-9.536-9.536 9.537 9.537 0 0 1 9.537 9.536" fill="#e30613"/
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 21.34 21.34"><path fill="#e30613" d="M20.2 10.67a9.54 9.54 0 1 1-9.53-9.53 9.54 9.54 0 0 1 9.54 9.53"/><path fill="#d20a11" d="M10.67 20.92a10.25 10.25 0 1 1 0-20.5 10.25 10.25 0 0 1 0 20.5m0-20.92a10.67 10.67 0 1 0 0 21.34 10.67 10.67 0 0 0 0-21.34m9.6 10.67a9.6 9.6 0 1 1-19.2 0 9.6 9.6 0 0 1 19.2 0"/><path fill="#fff" d="M7.5 11.82 5.94 6.94h-2.4v7.46h1.9v-1.9l-.12-2.62 1.54 4.52h1.29l1.56-4.57-.12 2.66v1.91h1.9V6.94h-2.4zm8.33-2.06c-.17.13-.43.2-.79.2h-.73V8.45h.7c.37 0 .65.06.82.19.17.12.24.31.24.59 0 .24-.07.41-.24.53m-1.52 1.53h1.15c.31 0 .54.07.67.21s.2.36.2.64c0 .26-.07.45-.22.57-.16.12-.41.19-.75.19h-1.05zm3.6-.2a1.5 1.5 0 0 0-.74-.55c.23-.13.42-.3.55-.52a1.86 1.86 0 0 0 .26-.98c0-.7-.27-1.23-.8-1.58A3.9 3.9 0 0 0 15 6.94h-2.6v7.47h2.96c.9 0 1.61-.2 2.1-.57a2 2 0 0 0 .76-1.69c0-.4-.11-.76-.33-1.06"/></svg>
```

2021-10-13 01:37 UTC, Carlgo11 commented on img/n/nh-hotels.com.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="37.219" height="37.219" viewBox="0 0 9.847 9.847"><path d="M3.819 3.502c.077.134.116.325.116.55v3.503H4.9V3.756c0-.36-.08-.668-.239-.914-.244-.36-.645-.
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 9.847 9.847"><path fill="#003a70" d="M3.819 3.502c.077.134.116.325.116.55v3.503H4.9V3.756c0-.36-.08-.668-.239-.914-.244-.36-.645-.55-1.16-.55-.676 0-1.182.311-1.629.734l-.222.21v-.857H0v.749h.73v4.426h.966V3.74l.046-.038c.333-.267.837-.584 1.355-.584.425 0 .627.207.722.383m5.045 4.053v-2.14H6.578v2.14h-.992V2.379h.992v2.146h2.286V2.379h.983v5.175z"/></svg>
```

2021-10-13 01:37 UTC, Carlgo11 commented on img/n/noez.de.svg
> +<svg xmlns="http://www.w3.org/2000/svg" version="1.0" width="1172.455" height="975.515" viewBox="0 0 879.341 731.637"><path style="fill:#1062fe;fill-opacity:1;stroke:none;stroke-width:.1" d="M706.075
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" version="1.0" viewBox="0 0 879 732"><path fill="#1062fe" d="M706 0c-57 6-106 40-151 73-35 20-75 31-115 39a338 338 0 0 0-256 8c-16-19-20-65-31-70-13 10-18 70-26 48-8-24-14-64-26-21-9 17-13 51-22 14-5-28-12-41-22-8-21 47-21 102-6 152-12 20-24 45-33 65a321 321 0 0 0 256 427c17 2 35 5 46 3 15 3 37-2 56-5 92-16 175-74 221-155 45 1 93-5 129-33 27-19 49-46 59-76-47 18-101 25-150 10 10-26-12-84 34-71 19-1 72 19 34-10-17-26-65-18-70-47-19-35-5-70 31-88 53-31 118-12 170 13 27 26 32-15 37-37 3-19 10-39 6-52 4-17-3-37-6-58C857 57 799 1 731 0h-25Z"/></svg>
```

2021-10-13 01:37 UTC, Carlgo11 commented on img/o/oderland.se.svg
> +<svg xmlns="http://www.w3.org/2000/svg" height="36" width="36"><path d="M19.192 17.861c-.96 0-2.247.555-3.863 1.664-1.7 1.162-2.548 2.178-2.548 3.05 0 .738.493 1.36 1.48 1.86.821.45 1.657.674 2.506.6
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 36 36"><path fill="#cc1e1f" d="M19.2 17.9c-1 0-2.3.5-3.9 1.6-1.7 1.2-2.5 2.2-2.5 3 0 .8.5 1.4 1.5 2 .8.4 1.6.6 2.5.6 1.2 0 2.4-.3 3.5-1 1.2-.8 1.8-1.8 1.8-3 0-.7-.3-1.4-.9-2.1-.6-.8-1.3-1.1-2-1.1zm6.6 2.4c0 2.7-1 4.7-3 6.3a11.2 11.2 0 0 1-7 2 8 8 0 0 1-4.1-1c-1.4-.7-2-1.8-2-3.4 0-1.7.8-3.7 2.6-6.1a8.4 8.4 0 0 1 7.1-3.6c1 0 2 0 3 .3-.1-1-.4-1.6-.8-2-.4-.4-1.1-.6-2-.6-.8 0-2 .2-3.4.5a18 18 0 0 1-3.1.4c-.6 0-1-.2-1.4-.7a2 2 0 0 1-.7-1.5c0-.6.5-1 1.5-1.3 2.6-.7 5.2-1 7.7-1 1.6 0 2.7.2 3.3.7 1 .7 1.5 2 1.8 4a252.7 252.7 0 0 0 .5 7zm4.8-2.9c0-3.3-1-6.3-3-8.8a10 10 0 0 0-8.2-4.2 13 13 0 0 0-6.6 1.9A14 14 0 0 0 5 19.1c0 3.4 1 6.4 3 8.9a10 10 0 0 0 8.2 4.2 13 13 0 0 0 6.6-2 14 14 0 0 0 7.8-12.8zM36 15c0 3.3-1 6.6-3 9.9-2 3.3-4.5 6-7.6 8A18.6 18.6 0 0 1 15.2 36 15 15 0 0 1 0 21.2c0-3.3 1-6.6 3-10 2-3.2 4.5-5.9 7.6-8C13.9 1.1 17.2 0 20.7 0a15 15 0 0 1 10.8 4.4A14 14 0 0 1 36 14.9Z"/></svg>
```

2021-10-13 01:37 UTC, Carlgo11 commented on img/p/pobox.com.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32"><defs><radialGradient id="a" cx="12.88" cy="19.64" r="17.7" gradientUnits="userSpaceOnUse"><stop offset="0" stop-color="#00cfff"/><stop
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><defs><radialGradient id="a" cx="12.88" cy="19.64" r="17.7" gradientUnits="userSpaceOnUse"><stop offset="0" stop-color="#00cfff"/><stop offset="1" stop-color="#00a2ff"/></radialGradient></defs><path fill="none" d="M0 0h32v32H0z"/><rect width="29.99" height="29.98" x="1.01" y="1" fill="url(#a)" rx="2.6"/><path fill="#fff" fill-rule="evenodd" d="M18.8 9.63c-3 0-4.9 2.22-6.55 4.07-1.64-1.85-3.59-4.07-6.54-4.07-2.41 0-4.83 1.64-4.71 5.2.33 6 5.4 10.93 11.25 16.17 5.86-5.24 10.93-10.18 11.26-16.17.13-3.56-2.3-5.2-4.71-5.2Z"/></svg>
```

2021-10-13 01:37 UTC, Carlgo11 commented on img/s/saaspass.com.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="67.32" height="67.32" viewBox="0 0 17.81 17.81"><path style="fill:#fff;fill-opacity:1;fill-rule:nonzero;stroke:none" d="M0 0a24.77 24.77 0 1 0 0-49.55A2
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 18 18"><path fill="#fff" d="M9 .16a8.84 8.84 0 1 1 0 17.68A8.84 8.84 0 0 1 9 .16"/><path fill="#091a2c" d="M9 18A9 9 0 1 1 9 0a9 9 0 0 1 0 18M9 .49a8.5 8.5 0 0 0-8.51 8.5A8.5 8.5 0 0 0 9 17.49a8.5 8.5 0 0 0 8.51-8.5A8.5 8.5 0 0 0 9 .48Zm3.84 10.9c-.56-.57-.94-.88-.94-.88-.32-.26-.38-.12-.32-.7 0-.12.07-.24.07-.31.25-2.08-.76-2.96-.76-2.96-.88-1.13-1.76-.38-1.76-1.13 0-.82-.13-3.96-.13-3.96s-.12 3.08-.12 3.96c0 .76-.9 0-1.77 1.13 0 0-1.06.94-.69 3.28.06.63 0 .5-.31.69 0 0-2.6 2.02-2.97 4.03 0 0 2.6-1.2 3.46-3.66.13-.57.2-.43.2-.43s.12.2.25.33l.18.17c.2.18.83.57 1.77.57a2.81 2.81 0 0 0 1.88-.67l.32-.4c.07 0 .07-.14.19.43.88 2.53 3.47 3.66 3.47 3.66-.25-1.14-1.2-2.32-2.02-3.15m-1.76-3.53c.19 0 .44.12.38.37 0 0-.13.45-.58.45-.37.07.01-.81.2-.81m-3.97.8c-.44 0-.57-.43-.57-.43-.06-.25.2-.37.38-.37.19 0 .56.88.2.8m4.4.96c0 .06 0 .12-.06.12-1.01.56-.95.7-1.01 1.01-.06.2.06.25.12.25a2.95 2.95 0 0 1-1.58.44A2.96 2.96 0 0 1 7.41 11c.13 0 .2-.06.13-.25-.06-.37 0-.5-1-1.01-.19-.12.12-.94.2-.94 0 0-.14.43.8-.18.39.18.58.06.76 0h1.4c.18.06.37.18.76 0 .94.62.8.18.8.18l.14.25a1.01 1.01 0 0 1 .12.44v.13"/></svg>
```

2021-10-13 01:37 UTC, Carlgo11 commented on img/s/southwesternrailway.com.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="18.58" height="18.6"><path d="M17.96.01H.74C.4.01 0 .33 0 .71v1.92c0 .39.3.72.66.72h12.06L9.4 6.64H.75a.71.71 0 0 0-.73.71v1.96c0 .38.32.69.66.68h5.37L.
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 18.6 18.6"><path fill="#0092cb" d="M18 0H.7C.4 0 0 .3 0 .7v2c0 .3.3.6.7.6h12L9.4 6.6H.7a.7.7 0 0 0-.7.8v2c0 .3.3.6.7.6H6L.3 15.8a1 1 0 0 0-.3.7v1.4c0 .4.4.7.7.7H2c.3 0 .5 0 .7-.3L15.2 6v4.4L7.6 18c-.2.2-.2.7.4.7h3.2c.3 0 .6 0 .8-.3l3.2-3.3v3c0 .3.4.6.7.6h2c.4 0 .7-.3.7-.6V.6A.6.6 0 0 0 18 0"/></svg>
```

2021-10-13 01:37 UTC, Carlgo11 commented on img/s/szkb.ch.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="40.495" height="40.495" viewBox="0 0 10.714 10.714"><path d="M0 9.705V0h10.714v9.705z" style="fill:#e6181a" transform="translate(0 .504)"/><path d="M10.
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 8.4664282 7.6727005" style="background:#e6181aff;fill:#fff"><path d="M.32840048.29067732V7.3820232H8.1380277V.29067732ZM3.7928125.6643144h3.8956261l-2.1540281 3.180611 2.1540281 3.1626442H3.7736202L1.6383763 3.82655Z"/></svg>
```

2021-10-13 01:37 UTC, Carlgo11 commented on img/t/threatconnect.com.svg
> +<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="svg5326" width="62.407" height="62.409"><defs id="defs5298"><linearGradient id="a" x1="-19.48" y1=
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 62.41 62.41"><defs><linearGradient id="a" x1="-19.48" x2="31.46" y1="41.55" y2="-9.85" gradientUnits="userSpaceOnUse"><stop offset="0" stop-color="#f77e08"/><stop offset=".29" stop-color="#f87807"/><stop offset=".69" stop-color="#fc6603"/><stop offset=".99" stop-color="#ff5400"/></linearGradient><linearGradient xlink:href="#a" id="c" x1="13.73" x2="64.66" y1="74.46" y2="23.06"/><linearGradient xlink:href="#a" id="b" x1="-19.48" x2="31.46" y1="41.55" y2="-9.85" gradientUnits="userSpaceOnUse"/></defs><path fill="url(#b)" d="M14.63 18.78a8.2 8.2 0 1 0-11.6 0 8.21 8.21 0 0 0 11.6 0z" transform="translate(-.63 -4.78)"/><path fill="url(#c)" d="M58.74 51.81a7 7 0 0 0-.87-.42c-7.39-3.65-12.91-9-13.13-15v-.38a10.41 10.41 0 0 1 .21-2.08c1.09-5.31 6.25-10 12.93-13.31a7.85 7.85 0 0 0 .88-.42A8.2 8.2 0 1 0 49 7.24a8.14 8.14 0 0 0-1.8 2.64 2.85 2.85 0 0 1-.12.31 21.41 21.41 0 0 1-15.53 13l-.62.11A15.13 15.13 0 0 0 19 35c-.07.36-.14.72-.18 1.09a21.46 21.46 0 0 1-12.61 15.1l-.21.08A8.2 8.2 0 1 0 16 63c.14-.32.29-.63.45-.94 3.72-7.53 9.23-13.11 15.37-13.11 6.14 0 11.66 5.59 15.39 13.12a6.57 6.57 0 0 0 .44.93A8.59 8.59 0 0 0 49 64.81a8.2 8.2 0 0 0 11.56-11.64 8.39 8.39 0 0 0-1.82-1.36ZM31.79 40.32A4.32 4.32 0 1 1 36.11 36a4.32 4.32 0 0 1-4.32 4.32Z" transform="translate(-.63 -4.78)"/></svg>
```

2021-10-13 01:37 UTC, Carlgo11 commented on img/t/thriva.co.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="74.661" height="74.661"><path transform="translate(0 11.131)" style="fill:#fa476f;fill-rule:evenodd" d="M26.811 26.908 37.33 16.39 25.394 4.454c-5.81-5.
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 74.7 74.7"><path fill="#fa476f" d="m37.3 27.5-12-12a14.9 14.9 0 1 0-21 21.1l22.5 22.5"/><path fill="#45d0eb" d="M70.3 15.6a14.9 14.9 0 0 0-21 0l-12 12C42 44 42 44 47.8 59l22.5-22.4a14.9 14.9 0 0 0 0-21"/><path fill="#664277" d="M47.8 38 37.3 27.5 26.8 38a14.9 14.9 0 1 0 21 0"/></svg>
```

2021-10-13 01:37 UTC, Carlgo11 commented on img/u/userify.com.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="266.101" height="266.101"><path d="m27.046 117.151.746-4.564c-3.567 3.736-8.877 5.475-13.275 5.475-7.466 0-13.109-4.725-13.109-13.186 0-1.16.168-2.491.4
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 266.1 266.1"><path fill="#1d4b97" d="m27 171.8.8-4.6a19 19 0 0 1-13.3 5.5c-7.4 0-13-4.7-13-13.2 0-1.2 0-2.5.3-3.8l3-16.5H0L2.2 127H20l-4.4 25a16.6 16.6 0 0 0-.3 2.7c0 4 2 5.9 5.5 5.9 5 0 7.7-3.2 8.8-9.1l2.2-12.3H27l2-12.1h18.4l-5.7 32.5h4.7l-2.2 12.2zm40 1c-6 0-8.7-2-10.7-3.8l-.5 2.8h-9l2.2-12.9h12.7v.2c0 3 1.5 4.2 4.8 4.2 2.8 0 4.7-1.4 5.1-3.5v-.7c0-2.6-3.1-3.4-10.9-5.6-6.1-1.8-9.6-5.6-9.6-11l.3-2.3c1.3-8 8.8-14.1 18.6-14.1 6 0 7.7 2 9 3.5l.5-2.7h8.8l-2.3 13H74v-.5c0-2.2-1.2-3.5-3.8-3.5-2.4 0-4.5 1.3-4.8 3.2v.5c0 6 20.6 2.7 20.6 16 0 1-.1 1.8-.3 2.8-1.4 8-8.6 14.4-18.7 14.4m46.5-35.4c-4.6 0-9.4 2.7-11.9 7.3h21.9c-1.4-5-5.4-7.3-10-7.3m19.7 17H100c1.3 4.7 5.1 7.1 9.7 7.1 3 0 6-1 8.2-3h13.4a28.6 28.6 0 0 1-23.7 14.7c-11.2 0-19.8-7.7-19.8-19.3a29 29 0 0 1 27.9-28.1c10.8 0 19.4 7.5 19.4 19 0 1.4-.1 2.8-.4 4.3a26.5 26.5 0 0 1-1.5 5.3m21.1-3.1-1.5 8.3h4.8l-2.2 12.2h-22.6l2.2-12.2h4.7l3.6-20.4h-4.7l2.1-12.1h16.8l-1.2 6.7c4.6-5.5 8.5-7 14-7.4l-2.4 13.5c-7.5.4-12.3 4.4-13.6 11.4"/><g fill="#408cfe"><path d="m178 124.7 2.1-12.1h13.1l-2 12.1zm-13 47 2.1-12.1h4.7l3.6-20.4h-4.7l2.1-12.1h18l-5.9 32.5h11.4l-3.3 12.2z"/><path d="m212 139.2-3.6 20.4h4.8l-2.2 12.2h-22.6l2.2-12.2h4.7l3.6-20.4h-4.7l2.1-12.1h4.8c2.8-12.8 10-16.6 21.7-16.6l-2 11.5h-1.2c-3.4 0-4.8 2-5.4 5h5.6l-2 12.2z"/><path d="m259.8 139.2-21.3 36h4.5l-2 12.3h-22.5l2.1-12.2h4.1l2.7-5-6.7-31.1h-4.5l2.1-12.1h21.5l-2.2 12h-2.5l2.2 15 8.1-15h-2.6l2.1-12h21.2l-2.2 12z"/></g><path fill="#1d4b97" d="M153.3 88.9a34.5 34.5 0 0 0-64.7-16.4A34.3 34.3 0 0 0 76 70c-16.7 0-30.7 12-33.8 27.7a34.8 34.8 0 0 0-5.3-.4 34.5 34.5 0 0 0-33.6 26.8h6a28.5 28.5 0 0 1 38.2-18.9v-.8A28.5 28.5 0 0 1 76 76a28.4 28.4 0 0 1 15.6 4.6 28.6 28.6 0 0 1 55.6 11.8 28.5 28.5 0 0 1 17.2 26.1 28.4 28.4 0 0 1-.6 5.7l-2 2.2s3-2.3 8-2.2a34.4 34.4 0 0 0 .5-5.7c0-12.3-6.6-23.5-17-29.6"/></svg>
```

2021-10-13 01:37 UTC, Carlgo11 commented on img/w/weclapp.com.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="29.425" height="29.425"><path style="fill:#00ffb0;fill-rule:evenodd" d="m16.62 10.397 2.117 14.005c.293 1.292-.64 2.532-1.906 2.532h-4.237c-1.265 0-2.19
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 29.43 29.43"><path fill="#00ffb0" d="m16.62 10.4 2.12 14c.29 1.3-.64 2.53-1.9 2.53h-4.25c-1.26 0-2.2-1.24-1.9-2.53l2.12-14c.34-2.16 3.53-2.12 3.8 0zM6.2 2.5c1.26 0 2.2 1.23 1.9 2.52l-2.1 14c-.35 2.17-3.54 2.12-3.82 0l-2.12-14C-.24 3.73.7 2.5 1.96 2.5zm21.26 0c1.27 0 2.2 1.23 1.91 2.52l-2.12 14c-.35 2.17-3.54 2.12-3.81 0l-2.12-14c-.29-1.29.64-2.53 1.9-2.53z"/></svg>
```

2021-10-13 19:50 UTC, phallobst commented on img/s/szkb.ch.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="40.495" height="40.495" viewBox="0 0 10.714 10.714"><path d="M0 9.705V0h10.714v9.705z" style="fill:#e6181a" transform="translate(0 .504)"/><path d="M10.
@Carlgo11  This one did not display correctly for me; the red backdrop was missing. I replaced this file with another version.

2021-10-13 19:51 UTC, Carlgo11 approved these changes

2021-10-14 14:54 UTC, ApCoder123 approved these changes

2021-10-14 14:54 UTC, merged