Added Tryhackme Site
2factorauth/twofactorauth pull request #6188
Opened 2021-10-11 13:19 UTC by whiskerwind

2021-10-11 13:51 UTC, ApCoder123 requested changes

2021-10-11 13:51 UTC, ApCoder123 commented on entries/t/tryhackme.com.json
> +  "Try Hack Me": {
```suggestion
  "TryHackMe": {
```

The name doesn't have any spaces in between on the site.

2021-10-11 18:29 UTC, phallobst commented
How about this SVG icon:
![](https://raw.githubusercontent.com/phallobst/phallobst/main/resterampe/tryhackme.com.svg)

2021-10-11 23:55 UTC, whiskerwind commented
Good idea on the logomark instead of the logotype

2021-10-12 06:10 UTC, phallobst requested changes

2021-10-12 06:10 UTC, phallobst commented on entries/t/tryhackme.com.json
> +      "education"
```suggestion
      "security",
      "education"
```

2021-10-12 06:51 UTC, phallobst approved these changes

2021-10-12 14:22 UTC, ApCoder123 approved these changes

2021-10-12 14:22 UTC, merged