Add regions to investing
2factorauth/twofactorauth pull request #6213
Opened 2021-10-17 19:44 UTC by ApCoder123

2021-10-17 20:01 UTC, Carlgo11 commented on entries/p/prudential.com.json
> -    "url": "https://www.prudential.com",
This line needs to be here.

2021-10-17 20:18 UTC, phallobst commented on entries/p/prudential.com.json
> -    "url": "https://www.prudential.com",
I'm afraid that's the same problem as in #6200 - neither URL does work.

2021-10-17 20:36 UTC, Carlgo11 commented on entries/p/prudential.com.json
> -    "url": "https://www.prudential.com",
https://prudential.com didn't work for me anyway :shrug:

I'm not sure how to debug the failed test. For starters I can't find what DNS servers the GitHub workflow uses :thinking:

2021-10-17 22:16 UTC, Carlgo11 commented on entries/i/ig.com.json
>  {
Is it worth listing these countries?
![](https://d.tempfiles.download/D616CA0BB54E62/?p=fOLGMyHDkAl6JW)

2021-10-18 15:38 UTC, ApCoder123 commented on entries/i/ig.com.json
>  {
I didn't include those, as it did seem to allow registrations from any country - see "IG International" at the bottom of that page and https://www.ig.com/en/application-form.

2021-10-18 23:53 UTC, Carlgo11 commented on entries/p/prudential.com.json
> -    "url": "https://www.prudential.com",
After much debugging and some reverse shells into the github workflow I've found that the problem is indeed due to Microsoft Azure's DNS servers. Setting the nameservers to `1.1.1.1` in `/etc/resolv.conf` fixes the problem. Oddly enough it only happens when running the command inside docker on Microsoft Azure :thinking:

2021-10-24 17:16 UTC, Carlgo11 approved these changes

2022-01-30 22:09 UTC, phallobst requested changes

2022-01-30 22:09 UTC, phallobst commented on entries/w/wealthsimple.com.json
> +      "gb",
See https://help.wealthsimple.com/hc/en-gb/articles/4411041188891
```suggestion
```

2022-01-30 23:53 UTC, phallobst approved these changes

2022-01-30 23:53 UTC, merged