Update icons
2factorauth/twofactorauth pull request #6223
Opened 2021-10-20 19:28 UTC by phallobst

2021-10-20 20:01 UTC, Carlgo11 commented on img/f/foursquare.com.svg
> +<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 67 81"><path fill="currentColor" d="M.703 0h24.764v4.064H4.814v11.379h18.358v4.064H4.814v16.449H.704V0zM0 68.043l4.018-.908c.717 4.972
There are two fill tags here :thinking:

2021-10-20 20:10 UTC, Carlgo11 requested changes

2021-10-20 20:10 UTC, Carlgo11 commented on img/n/noke.com.svg
> +<svg xmlns="http://www.w3.org/2000/svg" id="Layer_1" data-name="Layer 1" version="1.1" width="68.695" height="68.695"><defs id="defs1647"><style id="style1645">.cls-1{fill:#0071ce}.cls-2{fill:#939598
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 68.69 26.59"><path d="M15.57 26.59h-1.4v-12a6.4 6.4 0 1 0-12.79 0v12H0v-12a7.8 7.8 0 1 1 15.6 0zm10.98 0c-4.94 0-8.67-4.25-8.67-9.89 0-5.64 3.73-9.89 8.67-9.89 4.94 0 8.66 4.25 8.66 9.89 0 5.64-3.72 9.89-8.65 9.89zm0-18.38c-4.2 0-7.27 3.57-7.27 8.49s3.06 8.49 7.27 8.49c4.21 0 7.26-3.57 7.26-8.49s-3.06-8.49-7.26-8.49z" style="fill:#939598"/><path d="M68.3 16.91h.4v-.21c0-5.82-3.41-9.89-8.3-9.89-4.9 0-8.66 4.25-8.66 9.89 0 5.64 3.74 9.89 8.67 9.89 4 0 7-2.69 7.95-6.83H66.9c-.91 3.3-3.32 5.43-6.5 5.43-4.13 0-7.15-3.47-7.24-8.28zm-7.9-8.7c3.74 0 6.43 3 6.84 7.3h-14c.43-4.29 3.31-7.3 7.16-7.3zm-21.46 8.4V0h-1.4v26.59h1.4v-8.14l3.6-3.07 8.47 11.21h1.75l-9.14-12.11 9.12-7.74h-2.18zM67.11 3.33H56.73l-1.57 1.33h11.95z" style="fill:#0071ce"/></svg>
```

2021-10-20 20:10 UTC, Carlgo11 commented on img/n/nubank.com.br.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="43.5" height="43.5" viewBox="0 0 57.34 58"><path style="fill:#820ad1;fill-opacity:1" class="sc-pQEbo yAvEL" d="M10.47 3.05A9.62 9.62 0 0 1 17.6 0c5.56 0
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 58 32"><path fill="#820ad1" d="M10.47 3.05A9.62 9.62 0 0 1 17.6 0c5.56 0 9.25 4.07 9.96 10.16.23 1.97.23 4.76.23 8v13.1h-7.66V22.3s-.02-7.66-.06-9.1c-.2-6.23-3.9-10.14-9.6-10.15C8.75 4.88 7.83 7.1 7.7 10.5c-.02.47 0 2.15 0 4.37v16.4H.03V16.05c-.03-.96-.05-1.93 0-2.89.1-1.6.37-3.17 1.11-4.63a10.12 10.12 0 0 1 9.33-5.49zm47.5 15.78c.05-.96.03-1.93.01-2.9V.74H50.3v16.4c.01 2.21.02 3.9 0 4.36-.14 3.4-1.06 5.62-2.78 7.44-5.7 0-9.39-3.92-9.6-10.16-.04-1.43-.06-4.98-.06-9.1V.74h-7.65v13.1a79 79 0 0 0 .22 8c.7 6.1 4.4 10.16 9.96 10.16 2.86 0 5.3-1.13 7.13-3.05h.4c3.72 0 7.22-2.15 8.93-5.5a11.34 11.34 0 0 0 1.1-4.62z"/></svg>
```

2021-10-20 20:43 UTC, phallobst commented on img/t/target.com.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 -4.5 .5 9"><circle r="3.7" fill="none" stroke="#c00" stroke-width="1.6"/><circle r="1.4" fill="#c00"/></svg>
The `viewBox` for this one is broken.

2021-10-20 20:47 UTC, Carlgo11 commented on img/t/target.com.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 -4.5 .5 9"><circle r="3.7" fill="none" stroke="#c00" stroke-width="1.6"/><circle r="1.4" fill="#c00"/></svg>
Nice catch! :+1:

2021-10-20 20:49 UTC, Carlgo11 approved these changes

2021-10-21 15:09 UTC, ApCoder123 commented on img/f/foursquare.com.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 67 81"><path d="M.7 0h24.77v4.06H4.8v11.38h18.36v4.07H4.81v16.45H.71V0zM0 68.04l4.02-.9c.72 4.97 4.16 7.93 9.75 7.93 5.02 0 9-2.34 9-6.17 0-2.72-2
I'm not 100% sure whether this logo should be updated - the logo for the company seems to be the "FSQ" logo, however for the specific "City Guide" app, which the entry refers to, the current logo still seems to be in use. 
See:
- https://apps.apple.com/gb/app/foursquare-city-guide/id306934924
- https://foursquare.com/city-guide (favicon)
- From the "Products and Solutions" menu:
![image](https://user-images.githubusercontent.com/20560218/138306175-74f77e4d-6284-4147-8c4f-5d24de4dca20.png)

2021-10-21 15:16 UTC, phallobst commented on img/f/foursquare.com.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 67 81"><path d="M.7 0h24.77v4.06H4.8v11.38h18.36v4.07H4.81v16.45H.71V0zM0 68.04l4.02-.9c.72 4.97 4.16 7.93 9.75 7.93 5.02 0 9-2.34 9-6.17 0-2.72-2
https://foursquare.com/article/a-new-look-and-feel-introducing-foursquare-everywhere/
I'm afraid they can't even keep up with themselves... :smile:

2021-10-21 15:26 UTC, ApCoder123 approved these changes

2021-10-21 15:26 UTC, merged