Add Fahren Lernen
2factorauth/twofactorauth pull request #6229
Opened 2021-10-23 21:17 UTC by sn00py1310

2021-10-23 22:20 UTC, phallobst requested changes

2021-10-23 22:20 UTC, phallobst commented on img/f/fahren-lernen.de.svg
> +</svg>
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" width="240" height="240" viewBox="0 0 180 180"><path d="M0 90v90h180V0H0v90zm47-51v15H32V24h15v15zm23.7-10.9 2.2.8-2.3 7.3c-2.2 7.1-2.3 7.3-5.3 7.1-1.7-.2-4.2-.7-5.6-1.2l-2.4-1 1.5-7.6 1.5-7.6 4.1.7c2.3.3 5.1 1 6.3 1.5zM94 38c0 1.4-7.3 14.1-7.8 13.7-.4-.1-2.5-1.1-4.7-2.1s-4.1-1.9-4.3-2.1c-.3-.3 4.3-12.9 5.3-14.5.6-.9 11.5 3.9 11.5 5zm16.8 10.3c1.2 1.1 2.2 2.4 2.2 2.8 0 .9-9.1 11.9-9.9 11.9-.3-.1-2.3-1.6-4.5-3.4l-3.8-3.3 4.3-6.6c4.4-6.5 4.4-6.6 6.9-5 1.4.9 3.5 2.5 4.8 3.6zm16.7 15.9c17.7 19.7 28.5 47.9 28.5 74.5v10.4l-7.7-.3-7.8-.3-.6-10.5c-1.4-21.6-6.9-38.1-18.8-55.9-.7-1.2-1.9-.6-6.1 2.9l-5.1 4.3-4.9-5.4c-2.7-3-4.9-5.6-4.9-5.9.1-.7 21.2-18.9 22.1-19 .3 0 2.7 2.4 5.3 5.2zM92 89.2c0 .7-8.3 12-18.5 25.1C60.1 131.5 55 138.8 55 140.7c0 4.2-3.7 10.6-7.5 13-9.8 6.4-23.5-1-23.5-12.6 0-8 6.2-14.9 13.7-15.4 3.6-.2 6.8-2.4 27.9-18.9 13.2-10.3 24.5-18.7 25.2-18.7.6-.1 1.2.5 1.2 1.1z" fill="#183e7a"/></svg>
```

2021-10-23 22:41 UTC, sn00py1310 reviewed
Changes made to SVG file

2021-10-24 08:08 UTC, phallobst approved these changes

2021-10-28 10:31 UTC, Carlgo11 commented
So what is Fahren Lernen?
A drivers school? Transports agency?

2021-10-28 19:31 UTC, phallobst commented
You can practice for the written part of the drivers license test on that page.

2021-10-31 21:07 UTC, Carlgo11 approved these changes

2021-10-31 21:07 UTC, merged