Add Rocket League Garage
2factorauth/twofactorauth pull request #6231
Opened 2021-10-24 13:19 UTC by sn00py1310

Didn't find a SVG

2021-10-24 17:13 UTC, phallobst requested changes

2021-10-24 17:13 UTC, phallobst commented on entries/r/rocket-league.com.json
> +    "RL Garage": {
```suggestion
    "Rocket League Garage": {
```

2021-10-24 17:49 UTC, phallobst approved these changes

2022-02-11 22:45 UTC, dsoegijono approved these changes

2022-02-11 22:45 UTC, merged