Update Outlook.com
2factorauth/twofactorauth pull request #6235
Opened 2021-10-26 16:11 UTC by phallobst

See also #6225

2021-10-26 16:22 UTC, sn00py1310 approved these changes

2021-10-26 17:06 UTC, Carlgo11 requested changes

2021-10-26 17:06 UTC, Carlgo11 commented on entries/o/outlook.com.json
> +      "outlook.live.com"
Won't hurt adding hotmail as well. There's probably some edge case where they still use that domain :roll_eyes: 
```suggestion
      "outlook.live.com",
      "hotmail.com"
```

2021-10-26 18:55 UTC, phallobst commented on entries/o/outlook.com.json
> +      "outlook.live.com"
"hotmail"... That's a name I haven't heard in a while.

Do we really want `live.com` here? This could clash with "OneDrive" (`onedrive.live.com`).

2021-10-26 20:30 UTC, Carlgo11 commented on entries/o/outlook.com.json
> +      "outlook.live.com"
I didn't realize they used the live.com domain for anything else. The suggestion is updated now.

Hotmail is still very much alive and sadly being used. Their servers on the other hand are very much [**not** alive](https://postmaster.live.com).

2021-10-27 16:26 UTC, ApCoder123 approved these changes

2021-10-27 20:56 UTC, Carlgo11 approved these changes

2021-10-27 20:56 UTC, merged