Add huaweicloud.com website as MFA capable
2factorauth/twofactorauth pull request #6238
Opened 2021-10-26 17:59 UTC by fcpimenta

Add Huawei Cloud website as an MFA capable platform with enhanced security.

2021-10-26 18:47 UTC, phallobst requested changes
432K for the logo is a bit much, I reckon. :smile: How about this one:
![](https://raw.githubusercontent.com/phallobst/phallobst/main/resterampe/huaweicloud.com.svg)

2021-10-26 18:47 UTC, phallobst commented on entries/h/huaweicloud.com.json
> +      "custom-software"
```suggestion
      "totp"
```

2021-10-27 20:31 UTC, fcpimenta commented
Hi @phallobst,

Do you need me to make any more changes so you can accept the PR?

Tell me, I'll do it right away. Thanks!!

2021-10-27 20:38 UTC, phallobst commented
Please replace the SVG logo with the one I included in my comment. It's only a bit over 1K in size, compared to your version of 432K.

2021-10-27 21:27 UTC, phallobst approved these changes

2021-10-28 09:13 UTC, Carlgo11 approved these changes

2021-10-28 09:19 UTC, merged