Add Fanduel
2factorauth/twofactorauth pull request #6241
Opened 2021-10-28 00:36 UTC by bdonvr

Sports betting website popular in USA. https://www.fanduel.com/2fa-how-it-works

2021-10-28 09:19 UTC, Carlgo11 commented on entries/f/fanduel.com.json
> +    ]
Since it is US-only, a region tag would be good.
```suggestion
    ],
    "regions": [
      "us"
    ]
```

2021-10-28 19:29 UTC, phallobst requested changes

2021-10-28 19:29 UTC, phallobst commented on img/f/fanduel.com.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 92.3 92.1" fill="#fff"><path d="M46.5 92a92.2 92.2 0 0 0 45.8-79.2.8.8 0 0 0-.4-.7A92 92 0 0 0 53.5.3a.8.8 0 0 0-.7.3 84.2 84.2 0 0 0-9.3 15.3.3.3
I think the logo looks better in blue.
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 92.3 92.1" fill="#1493ff"><path d="M46.5 92a92.2 92.2 0 0 0 45.8-79.2.8.8 0 0 0-.4-.7A92 92 0 0 0 53.5.3a.8.8 0 0 0-.7.3 84.2 84.2 0 0 0-9.3 15.3.3.3 0 0 0 .3.4H46a75.8 75.8 0 0 1 29.3 5.8A76 76 0 0 1 46 72.7a76.6 76.6 0 0 1-9-8 .3.3 0 0 0-.4.2 83.4 83.4 0 0 0 9.2 27 .5.5 0 0 0 .6.1ZM30.2 56.2a75.4 75.4 0 0 1-5-8 48 48 0 0 1 4.7-2 .8.8 0 0 0 .5-.7 89 89 0 0 1 2.7-16.7.3.3 0 0 0-.3-.3A64.8 64.8 0 0 0 19.1 33 75.2 75.2 0 0 1 17 22.1a75.7 75.7 0 0 1 19.9-5.3.7.7 0 0 0 .6-.4 91.6 91.6 0 0 1 8.9-16A.3.3 0 0 0 46 0 91.8 91.8 0 0 0 .3 12.1a.8.8 0 0 0-.4.7 93 93 0 0 0 36.5 73 .3.3 0 0 0 .4-.3 89.1 89.1 0 0 1-6.6-29 .7.7 0 0 0 0-.3Z"/></svg>
```

2021-10-28 20:37 UTC, phallobst approved these changes

2021-11-08 20:09 UTC, ApCoder123 requested changes

2021-11-08 20:09 UTC, ApCoder123 commented on entries/f/fanduel.com.json
> +  "Fanduel": {
```suggestion
  "FanDuel": {
```

2021-11-08 21:21 UTC, ApCoder123 approved these changes

2021-11-08 21:21 UTC, merged