Add Zara
2factorauth/twofactorauth pull request #6246
Opened 2021-10-29 16:30 UTC by Lightning5trike

2021-10-30 14:05 UTC, ApCoder123 requested changes

2021-10-30 14:05 UTC, ApCoder123 commented on img/z/zara.com.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 132 55"><path d="m105.67.035 19.557 53.338 6.77.002v.383h-21.548v-.383h6.344l-6.431-17.54H97.308v.007l.07.204c.521 1.548.78 3.17.764 4.803v6.575c0
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 132 55"><path d="m105.67.035 19.557 53.338 6.77.002v.383h-21.548v-.383h6.344l-6.431-17.54H97.308v.007l.07.204c.521 1.548.78 3.17.764 4.803v6.575c0 3.382 1.494 6.81 4.347 6.81 1.675 0 3.012-.59 4.604-2.046l.227.211c-1.729 1.825-3.823 2.601-6.963 2.601-2.37 0-4.398-.57-6.03-1.693l-.309-.222c-2.148-1.624-3.542-4.278-4.142-7.89l-.096-.583-.1-.882-.01-.152-3.599 9.792h5.107v.384H80.493v-.384h5.162l3.951-10.753v-.023a34.924 34.924 0 0 1-.075-1.906v-4.693c0-5.77-4.29-9.08-11.771-9.08h-7.353v26.458h6.371v.383h-24.9v-.383h6.345l-6.431-17.54H33.945l-6.371 17.346.266-.044c8.366-1.442 12.213-7.827 12.265-14.55h.388v15.171H-.003l30.06-51.571H17.969c-10.018 0-14.552 7.737-14.622 15.45H2.96V1.8h36.488l-.222.385L9.393 53.373h15.695c.39 0 .778-.019 1.169-.05.26-.018.522-.044.788-.077l.095-.01L46.7 0h.387l.013.035 15.369 41.916V2.185h-6.328v-.39h21.778c10.467 0 17.774 5.372 17.774 13.068 0 5.612-5.005 10.27-12.45 11.595l-1.367.174 1.377.14c4.515.517 8.1 1.906 10.641 4.127l.017.016L105.27 0h.386zm-8.552 35.32.038.094h13.061l-8.773-23.928-7.221 19.67.039.037.367.364a11.876 11.876 0 0 1 2.489 3.762zM70.412 26.53V2.185h5.611c7.496 0 11.454 4.414 11.454 12.76 0 8.877-2.272 11.585-9.717 11.585zM42.879 11.521 34.087 35.45h17.565l-8.773-23.93z" fill-rule="evenodd" clip-rule="evenodd"/></svg>
```

2021-10-30 14:05 UTC, ApCoder123 commented on entries/z/zara.com.json
> +      "twitter": "ZARA"
```suggestion
      "twitter": "ZARA_Care"
```

2021-11-05 15:10 UTC, ApCoder123 approved these changes

2021-11-05 17:11 UTC, phallobst approved these changes

2021-11-05 23:54 UTC, merged

2021-11-05 23:58 UTC, Carlgo11 commented
The Zara website is improperly serving 404 status codes for 403 events resulting in the build failing. I've force-merged this PR but in the future we may need a way to exclude checks for certain websites :thinking: