Add Waterstones
2factorauth/twofactorauth pull request #6247
Opened 2021-10-29 16:48 UTC by Lightning5trike

2021-10-31 17:39 UTC, phallobst commented
Here is an SVG version of the logo:
![](https://raw.githubusercontent.com/phallobst/phallobst/main/resterampe/waterstones.com.svg)

2021-10-31 23:44 UTC, Carlgo11 requested changes

2021-10-31 23:44 UTC, Carlgo11 commented on entries/w/waterstones.com.json
> +      "twitter": "Waterstones"
```suggestion
      "twitter": "WstonesHelp"
```

2021-11-04 00:39 UTC, Carlgo11 approved these changes

2021-11-04 21:10 UTC, phallobst approved these changes

2021-11-04 21:10 UTC, merged