Add Matalan
2factorauth/twofactorauth pull request #6249
Opened 2021-10-29 17:07 UTC by Lightning5trike

2021-10-31 23:43 UTC, Carlgo11 requested changes

2021-10-31 23:43 UTC, Carlgo11 commented on img/m/matalan.co.uk.svg
> +</svg>
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 56 56"><path fill="#AD1E1F" d="M0 56h56V0H0z"/><path fill="#fff" d="M50.5 6.75h-5a.75.75 0 1 0 0 1.5h5a.75.75 0 1 0 0-1.5zm-10 0h-5a.75.75 0 1 0 0 1.5h5a.75.75 0 1 0 0-1.5zm-10 0h-5a.75.75 0 1 0 0 1.5h5a.75.75 0 1 0 0-1.5zm-10 0h-5a.75.75 0 1 0 0 1.5h5a.75.75 0 1 0 0-1.5zm-10 0h-5a.75.75 0 0 0 0 1.5h5a.75.75 0 1 0 0-1.5zM39.02 20.14h-2.8l-8.7 19.1-8.7-19.1h-2.79L13 42.63h2.4l2.53-18.83 8.54 18.83h2.12l8.54-18.83 2.52 18.83h2.4z"/></svg>
```

2021-11-04 00:41 UTC, Carlgo11 approved these changes

2021-11-04 21:08 UTC, phallobst approved these changes

2021-11-04 21:09 UTC, merged