Add holdem
2factorauth/twofactorauth pull request #6253
Opened 2021-11-02 09:41 UTC by 40504

2021-11-02 18:26 UTC, phallobst requested changes

2021-11-02 18:26 UTC, phallobst commented on entries/h/holded.com.json
> +    "url": "https://www.holded.com",
```suggestion
```

2021-11-02 18:26 UTC, phallobst commented on entries/h/holded.com.json
> +    "recovery": "https://www.holded.com/contact",
```suggestion
```

2021-11-03 08:26 UTC, phallobst approved these changes

2021-11-03 17:10 UTC, ApCoder123 requested changes

2021-11-03 17:10 UTC, ApCoder123 commented on entries/h/holded.com.json
> +  "holded": {
```suggestion
  "Holded": {
```

2021-11-03 17:30 UTC, ApCoder123 approved these changes

2021-11-03 17:30 UTC, merged