Updated Ubisoft
2factorauth/twofactorauth pull request #6257
Opened 2021-11-06 14:06 UTC by sn00py1310

2021-11-06 16:13 UTC, phallobst requested changes

2021-11-06 16:13 UTC, phallobst commented on entries/u/ubisoft.com.json
>      "documentation": "https://support.ubi.com/en-GB/Faqs/000039953",
```suggestion
    "documentation": "https://www.ubisoft.com/help?article=000065723",
    "recovery": "https://www.ubisoft.com/help?article=000063351",
```

2021-11-06 16:13 UTC, phallobst commented on entries/u/ubisoft.com.json
> +    "notes": "Software 2FA requires adding a phone number as a fallback.",
```suggestion
    "notes": "SMS and TOTP 2FA require adding a phone number as a fallback. SMS 2FA is not available in all regions.",
```

2021-11-06 18:45 UTC, phallobst approved these changes

2021-11-07 02:41 UTC, Carlgo11 approved these changes

2021-11-07 02:41 UTC, merged