Update Blizzard
2factorauth/twofactorauth pull request #6259
Opened 2021-11-07 13:22 UTC by sn00py1310

Unsure if "custom-hardware" should get removed because they don't sell it anymore ([Forum Post](https://us.forums.blizzard.com/en/wow/t/physical-blizzard-authenticator/237506/15)). And it isn't even mentioned in the [article](https://battle.net/support/article/24520).

2021-11-08 04:09 UTC, Carlgo11 commented
Yes please remove custom-hardware from the tfa array.

2021-11-13 10:55 UTC, phallobst requested changes

2021-11-13 10:55 UTC, phallobst commented on entries/b/blizzard.com.json
>      ],
```suggestion
      "custom-software"
    ],
    "custom-software": [
      "Battle.net Authenticator"
    ],
```

2021-11-13 13:03 UTC, phallobst approved these changes

2021-11-15 01:21 UTC, Carlgo11 approved these changes

2021-11-15 01:21 UTC, merged