Add Westpac site
2factorauth/twofactorauth pull request #6266
Opened 2021-11-10 11:43 UTC by jimmyvanau

Support authorisation according to https://www.westpac.com.au/faq/security-devices/ but not authentication

2021-11-10 14:31 UTC, Carlgo11 requested changes

2021-11-10 14:31 UTC, Carlgo11 commented on entries/w/westpac.com.au.json
> +            "twitter": "westpac"
```suggestion
            "twitter": "Westpac"
```

2021-11-11 01:00 UTC, Carlgo11 approved these changes

2021-11-11 09:58 UTC, phallobst approved these changes

2021-11-11 20:44 UTC, merged