Add TalkTalk
2factorauth/twofactorauth pull request #6280
Opened 2021-11-13 15:36 UTC by ApCoder123

2021-11-13 17:46 UTC, phallobst requested changes

2021-11-13 17:46 UTC, phallobst commented on img/t/talktalk.co.uk.svg
> +<svg xmlns="http://www.w3.org/2000/svg" fill="#394347" viewBox="0 0 113 22.701"><path d="M58.597 20.308c-.534-.394-1.933-2.03-3.017-3.387l-.399-.5-1.604-2.12c-.477-.669-.396-1.36.256-2.069a16.251 16.
I think a single "T" is more readable here, and sufficient as well.
![](https://raw.githubusercontent.com/phallobst/phallobst/main/resterampe/talktalk.co.uk.svg)
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" width="22.22" height="22.22" style="fill:#394347"><path d="M17.78 4.48c1.5-.01 2.64-.45 3.19-1.18.85-1.11.44-2.53.26-2.98a.5.5 0 0 0-.45-.32H4.44c-1.5.01-2.64.44-3.2 1.17C.4 2.3.82 3.71 1 4.16a.49.49 0 0 0 .45.32h6.4a.94.94 0 0 1 .86.67v14.9c0 .8.2 1.32.56 1.65.39.38.96.52 1.63.52h.5c1.22 0 2.1-.51 2.1-2.13V5.42c0-.51.4-.91.89-.94h3.4z"/></svg>
```

2021-11-13 17:51 UTC, phallobst approved these changes

2021-11-15 01:42 UTC, Carlgo11 approved these changes

2021-11-15 01:42 UTC, merged