Add Remind
2factorauth/twofactorauth pull request #6282
Opened 2021-11-13 16:06 UTC by ApCoder123

2021-11-14 22:07 UTC, phallobst requested changes

2021-11-14 22:07 UTC, phallobst commented on entries/r/remind.com.json
> +      "education"
```suggestion
      "education",
      "communication"
```

2021-11-17 20:29 UTC, phallobst approved these changes

2021-11-22 08:56 UTC, Carlgo11 approved these changes

2021-11-22 08:56 UTC, merged