Rename Netregistry to Webcentral, add 2FA support
2factorauth/twofactorauth pull request #6284
Opened 2021-11-13 20:43 UTC by phallobst

2021-11-14 11:38 UTC, ApCoder123 approved these changes

2021-11-15 01:26 UTC, Carlgo11 commented
No au region?

2021-11-17 20:32 UTC, phallobst commented
There was no `region` before, and I don't see a reason to add it here.

2021-11-22 08:51 UTC, Carlgo11 requested changes

2021-11-22 08:51 UTC, Carlgo11 commented on entries/w/webcentral.com.au.json
> +    ]
I'd still like a region tag here as they market themselves as **the** registrar/host for Australians.
```suggestion
    ],
    "regions": [
      "au"
    ]
```

2021-11-22 10:11 UTC, Carlgo11 approved these changes

2021-11-22 10:12 UTC, merged