Update Okta add custom-software
2factorauth/twofactorauth pull request #6285
Opened 2021-11-13 23:50 UTC by jimmyvanau

2021-11-13 23:51 UTC, jimmyvanau commented
https://help.okta.com/en/prod/Content/Topics/Mobile/okta-verify-overview.htm

2021-11-14 01:55 UTC, Carlgo11 requested changes

2021-11-14 01:55 UTC, Carlgo11 commented on entries/o/okta.com.json
> +    ],
```suggestion
    ],
    "custom-hardware": [
      "YubiKey OTP"
    ],
```

2021-11-14 14:38 UTC, phallobst approved these changes

2021-11-14 14:43 UTC, Carlgo11 approved these changes

2021-11-14 14:43 UTC, merged