Add auth0
2factorauth/twofactorauth pull request #6286
Opened 2021-11-14 00:00 UTC by jimmyvanau

2021-11-14 11:31 UTC, ApCoder123 requested changes

2021-11-14 11:31 UTC, ApCoder123 commented on img/a/auth0.com.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1000 1000" style="enable-background:new 0 0 1000 1000" xml:space="preserve"><path d="M753.3 794.5 656.6 500l253.3-182h-313L500.1 23.5h313.2L910.1
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 309.3 343.8"><path d="M266.31 0H154.65l34.51 107.54h111.66l-90.34 64.13L245 279.82c58.15-42.36 77.15-106.47 55.83-172.28zM8.48 107.54h111.66L154.65 0H43L8.48 107.54c-21.33 65.81-2.32 129.92 55.83 172.28l34.51-108.15zm55.83 172.28 90.34 64 90.34-64-90.34-65.06z"/></svg>
```
The [Auth0 Press Kit](https://auth0.com/press) uses the black version of the logo now

2021-11-15 01:45 UTC, Carlgo11 approved these changes

2021-11-15 15:23 UTC, ApCoder123 approved these changes

2021-11-15 15:23 UTC, merged