Add Codeberg (codeberg.org)
2factorauth/twofactorauth pull request #6313
Opened 2021-11-23 16:42 UTC by seabass-labrax

This commit adds [Codeberg](https://codeberg.org), a code hosting site intended for free software developers.

[SVGO](https://github.com/svg/svgo) was not able to minify the SVG logo effectively; it caused the left side of the logo to be cut off. However, I have used [Tidy](https://www.html-tidy.org/) to remove unnecessary whitespace, which did result in a significant reduction in file size as compared to the original.

2021-11-23 16:48 UTC, Carlgo11 commented
Try [svgomg](https://jakearchibald.github.io/svgomg/) and change the precision so that the image looks okay. Then enable all the *features* checkboxes and multipass.

2021-11-23 22:35 UTC, Carlgo11 requested changes

2021-11-23 22:35 UTC, Carlgo11 commented on img/c/codeberg.org.svg
> +</svg>
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 4.21 4.21"><defs><linearGradient xlink:href="#a" id="b" x1="42519.29" x2="42575.34" y1="-7078.79" y2="-6966.93" gradientTransform="translate(-1025.54 172.08) scale(.02417)" gradientUnits="userSpaceOnUse"/><linearGradient id="a"><stop offset="0" stop-color="#2185d0" stop-opacity="0"/><stop offset=".5" stop-color="#2185d0" stop-opacity=".49"/><stop offset="1" stop-color="#2185d0" stop-opacity=".63"/></linearGradient></defs><path fill="url(#b)" d="M2.15.98a.02.01 0 0 0-.02.02l.81 3.04a2.1 2.1 0 0 0 .95-.81L2.16.99a.02.01 0 0 0-.01 0z" opacity=".5"/><path fill="#2185d0" d="M2.1 0A2.1 2.1 0 0 0 0 2.1a2.1 2.1 0 0 0 .32 1.13L2.08.96a.03.02 0 0 1 .06 0l1.75 2.27a2.1 2.1 0 0 0 .32-1.12A2.1 2.1 0 0 0 2.11 0a2.1 2.1 0 0 0-.01 0z"/></svg>
```

2021-11-24 09:56 UTC, seabass-labrax commented
Say, thank you for the suggested changes @Carlgo11! I did try to use svgomg, but unfortunately it wouldn't run at all in my web browser.

2021-11-24 19:09 UTC, Carlgo11 approved these changes

2021-11-24 19:16 UTC, ApCoder123 approved these changes

2021-11-24 19:16 UTC, merged

2021-11-24 21:10 UTC, seabass-labrax commented
Thanks for merging! :)