Add kahoot
2factorauth/twofactorauth pull request #6317
Opened 2021-11-24 10:04 UTC by sn00py1310

2021-11-24 16:47 UTC, ApCoder123 requested changes

2021-11-24 16:47 UTC, ApCoder123 commented on entries/k/kahoot.it.json
> +    "domain": "kahoot.it",
```suggestion
    "domain": "kahoot.com",
    "additional-domains": [
      "kahoot.it"
    ],
```
While the quizzes are accessible from `kahoot.it`, the account login, management and other sensitive details (e..g private kahoots) are available at `kahoot.com`. Please also change the file name to `kahoot.com.json`.

I've also suggested adding `kahoot.it` as an additional domain, as there are some login pages that use subdomains of that (e.g. `create.kahoot.it`).

2021-11-24 19:16 UTC, Carlgo11 approved these changes
Thanks for the pull request @sn00py1310!

2021-11-24 19:58 UTC, sn00py1310 commented
@Carlgo11 I appreciate the project and like to do something useful. Otherwise, I would waste my time. And I learn more about Github and Git. 
All my entries are from a simple password manager script to compare the domains.
I need to thank all of you for helping me with my wrong entries and SVGs.

2021-11-25 14:50 UTC, Carlgo11 commented
@sn00py1310 thank you for the kind words! 😊

2021-11-25 19:43 UTC, ApCoder123 commented on entries/k/kahoot.com.json
> +      "twitter": "Kahoot"
```suggestion
      "twitter": "KahootSupport"
```

2021-11-25 19:50 UTC, ApCoder123 approved these changes

2021-11-25 19:51 UTC, merged