Add Aspiration
2factorauth/twofactorauth pull request #6321
Opened 2021-11-27 10:49 UTC by 40504

Based on this info: https://www.aspiration.com/security-policy/

2021-11-27 18:29 UTC, Carlgo11 requested changes

2021-11-27 18:29 UTC, Carlgo11 commented on entries/a/aspiration.com.json
> +    ]
```suggestion
    ],
    "regions": [
      "us"
    ]
```

2021-11-28 02:02 UTC, Carlgo11 approved these changes

2021-11-28 09:07 UTC, phallobst approved these changes

2021-11-28 09:07 UTC, merged