Update Hack The Box & Add Forums
2factorauth/twofactorauth pull request #6327
Opened 2021-11-29 16:29 UTC by sn00py1310

The Hack The Box domain changed from `hackthebox.eu` -> `hackthebox.com`
Hack the Box logins are possible from the `app` and `www` subdomain.

Hack The Box and Hack The Box _**Forums**_ have for some reason a different login system. 🤷

### Forums prove
![Forums 2FA](https://user-images.githubusercontent.com/61204194/143904494-89663f7d-8698-49bf-a7f9-0995c6a932dc.png)

2021-11-29 20:41 UTC, Carlgo11 requested changes

2021-11-29 20:41 UTC, Carlgo11 commented on entries/a/app.hackthebox.com.json
> +      "www.hackthebox.eu"
subdomains shouldn't be specified for domains.
```suggestion
      "hackthebox.eu"
```

2021-11-29 20:41 UTC, Carlgo11 commented on entries/a/app.hackthebox.com.json
> +    "domain": "app.hackthebox.com",
```suggestion
    "domain": "hackthebox.com",
```

2021-11-29 20:41 UTC, Carlgo11 commented on entries/f/forum.hackthebox.com.json
> +}
We don't list forums.
```suggestion
```

2021-11-29 21:19 UTC, sn00py1310 commented
@Carlgo11 is there a reason why forums aren't allowed. I didn't find anything in the exclusions.

2021-11-29 21:54 UTC, Carlgo11 commented
It's been a rule for as long as I've worked on the project.
Some of the problems with listing forums are:
* There's no good way of ranking the popularity as nearly all use subdomains and thus piggyback on the domain's Alexa rank.
* The impact of having your forum account stolen is for most people negligible.
* Most violate the self-hosting exception.

You're right that we should list that rule somewhere. I'm not sure why that hasn't been done already :thinking:

2021-11-29 21:54 UTC, Carlgo11 approved these changes

2021-11-30 14:44 UTC, ApCoder123 approved these changes

2021-11-30 14:45 UTC, merged