Add M1 Finance
2factorauth/twofactorauth pull request #6333
Opened 2021-12-01 02:55 UTC by Sid-Bezawada

2021-12-01 03:04 UTC, Carlgo11 requested changes

2021-12-01 03:04 UTC, Carlgo11 commented on img/m/m1finance.com.svg
> +</svg>
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024"><circle cx="512" cy="512" r="512" fill="#12123d"/><path fill="#fff" d="M390 695H276V385l114 114Zm203-187L394 309H276v46l235 235Zm-66-97 80 80 23-22v226h118V311H628Z"/></svg>
```

2021-12-01 03:04 UTC, Carlgo11 commented on entries/m/m1finance.com.json
> +      ]
```suggestion
      ],
      "regions": [
        "us"
      ]
```

2021-12-01 03:04 UTC, Carlgo11 commented on entries/m/m1finance.com.json
> +      "url": "https://www.m1finance.com",
The url tag isn't needed when the domain redirects to the same URL.
```suggestion
```

2021-12-01 03:04 UTC, Carlgo11 commented on entries/m/m1finance.com.json
> +      "documentation": "https://support.m1finance.com/hc/en-us/articles/221056367-Two-Factor-Authentication",
```suggestion
      "documentation": "https://support.m1finance.com/hc/en-us/articles/221056367",
```

2021-12-01 03:24 UTC, Sid-Bezawada commented
Thanks! @Carlgo11 , Updated the pr with your suggestions.

2021-12-01 03:25 UTC, Carlgo11 approved these changes

2021-12-01 03:25 UTC, Carlgo11 commented
Thanks for the PR @Sid-Bezawada! :clap:

2021-12-04 22:33 UTC, phallobst approved these changes

2021-12-04 22:33 UTC, merged