Created turhost.com json entry file
2factorauth/twofactorauth pull request #6334
Opened 2021-12-03 14:25 UTC by MesutErdemir

2021-12-04 22:41 UTC, phallobst requested changes
We still need a logo for this entry, preferably in SVG format.

Also, is there some sort of documentation publicly available? Otherwise, could you provide a screenshot of the 2FA setup process (with any personal information blurred or redacted)?

2021-12-04 22:42 UTC, phallobst requested changes

2021-12-04 22:42 UTC, phallobst commented on entries/t/turhost.com.json
> +    },
Once there is a `tfa` section, the `contact` section is not used anymore (which does not support `linkedin` or `instagram` anyway).
```suggestion
```

2021-12-04 22:42 UTC, phallobst commented on entries/t/turhost.com.json
> +      "server"
```suggestion
      "domains"
```

2021-12-06 22:18 UTC, Carlgo11 requested changes
The `doc` tag needs to be used or screenshots of the 2FA setup process would need to be provided in order for us to validate that 2FA is indeed supported.

Please fix the requested changes within a few days or we'll have to close the PR.

2021-12-06 22:18 UTC, Carlgo11 commented on entries/t/turhost.com.json
> +  "Hosting": {
```suggestion
  "Turhost": {
```

2021-12-06 22:18 UTC, Carlgo11 commented on entries/t/turhost.com.json
> +    "url": "https://www.turhost.com/hosting/",
```suggestion
```

2021-12-09 20:57 UTC, closed without merging