Add fedex.com
2factorauth/twofactorauth pull request #6347
Opened 2021-12-13 22:23 UTC by stephenjust

There does not appear to be any documentation for this feature, but it is accessible via the account settings page:
![image](https://user-images.githubusercontent.com/3144757/145898366-24f9af37-0030-4e5f-af15-f24f497ec121.png)

2021-12-14 23:14 UTC, Carlgo11 requested changes

2021-12-14 23:14 UTC, Carlgo11 commented on img/f/fedex.com.svg
> +<svg width="340.157" height="340.157" viewBox="0 0 90 90" xmlns="http://www.w3.org/2000/svg"><path style="display:inline;fill:#fd6500;stroke-width:.0190955" d="m51.93 31.889.044.01-.005 12.713-.005 1
I minified the SVG file for you:

```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 30.63"><path fill="#f60" d="m91.15 29.56-4.1-4.6-4.05 4.6h-8.54l8.35-9.38-8.35-9.38h8.8l4.14 4.55 3.98-4.55h8.5l-8.3 9.34 8.42 9.42h-8.85zm-33.1 0V0h16.4v6.6H65v4.2h9.46v6.35H65v5.82h9.46v6.6H58.05z"/><path fill="#412c91" d="M46.93 25.06c-2.56 0-4.14-2.38-4.14-4.86 0-2.65 1.38-5.2 4.14-5.2 2.86 0 4 2.55 4 5.2 0 2.52-1.21 4.86-4 4.86m-24.6-7.84c.44-1.87 1.9-3.1 3.71-3.1 2 0 3.39 1.19 3.75 3.1zM51.13 0v12.1h-.08c-1.53-1.76-3.45-2.38-5.67-2.38-4.55 0-7.98 3.1-9.18 7.19-1.37-4.5-4.91-7.27-10.16-7.27-4.26 0-7.62 1.91-9.38 5.03V10.8h-8.8V6.59h9.6V0H0v29.56h7.85V17.14h7.83c-.24.9-.36 1.89-.36 2.92 0 6.16 4.71 10.49 10.72 10.49 5.06 0 8.39-2.37 10.15-6.7h-6.73c-.9 1.3-1.6 1.69-3.42 1.69a4.04 4.04 0 0 1-3.93-4.03h13.7c.6 4.9 4.41 9.12 9.65 9.12a6.7 6.7 0 0 0 5.6-2.98h.07v1.91h6.92V0h-6.92Z"/></svg>
```

2021-12-15 00:44 UTC, stephenjust commented on img/f/fedex.com.svg
> +<svg width="340.157" height="340.157" viewBox="0 0 90 90" xmlns="http://www.w3.org/2000/svg"><path style="display:inline;fill:#fd6500;stroke-width:.0190955" d="m51.93 31.889.044.01-.005 12.713-.005 1
Interesting. I did run svgo on this file. Is there a specific way to run it for a better result?

2021-12-15 09:29 UTC, Carlgo11 approved these changes

2021-12-15 13:23 UTC, ApCoder123 approved these changes

2021-12-15 13:23 UTC, merged