Add Poli Systems
2factorauth/twofactorauth pull request #6350
Opened 2021-12-17 12:59 UTC by IIPoliII

Please add https://polisystems.ch.

The website is ranked also below 200k -> https://www.alexa.com/siteinfo/polisystems.ch

2021-12-17 13:08 UTC, IIPoliII commented
I don't understand why the first test fails directly at the start of "{"

2021-12-17 14:20 UTC, Carlgo11 commented
> Sites supporting TFA must not have a `contact` property.
- CONTRIBUTING.md

2021-12-18 22:14 UTC, Carlgo11 requested changes

2021-12-18 22:14 UTC, Carlgo11 commented on entries/p/polisystems.ch.json
> +}
```suggestion
{
   "Poli Systems":{
      "domain": "polisystems.ch",
      "tfa": [
         "totp"
      ],
      "documentation": "https://wiki.polisystems.ch/English/Tutorials/Two-factor-authentification-on-Poli-Systems-Portal/",
      "keywords": [
         "hosting",
         "cloud",
         "email"
      ]
   }
}
```

2021-12-18 23:44 UTC, IIPoliII commented
@Carlgo11 Thanks for the fix didn't see that!

2021-12-19 01:31 UTC, Carlgo11 requested changes
The logo is unnecessarily large. Ideally it would be between <2KiB.
Try and clean it up or use this one that I've cleaned up:
![](https://camo.githubusercontent.com/b918756dbc5617cc192ef6d3f2efacab4787593db6a70c089f34dfb33c9cc6c6/68747470733a2f2f642e74656d7066696c65732e646f776e6c6f61642f44363142463936384532363045302f3f703d73536f6d3133)

2021-12-20 07:02 UTC, IIPoliII commented
@Carlgo11 I tried to compress it a bit more than yours but I was only able to make it 0.1 Ko tiner.
It's now 1.36Ko could that work out?

2021-12-20 10:06 UTC, Carlgo11 commented on img/p/polisystems.ch.svg
> +</svg>
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" stroke="#000678" stroke-width="5.3" viewBox="0 0 100 100"><linearGradient id="a"><stop offset="0" stop-color="#00f2ff"/><stop offset="1" stop-color="#ff6b89"/></linearGradient><linearGradient xlink:href="#a" id="b" x1="100" x2="0" gradientUnits="userSpaceOnUse"/><path fill="url(#a)" d="M97.33 17.84V19a15.18 15.18 0 0 1-15.17 15.18H6.26a3.57 3.57 0 0 1-3.55-3.57V6.22a3.57 3.57 0 0 1 3.57-3.57h75.86a15.18 15.18 0 0 1 15.2 15.2ZM93.42 65.7a3.93 3.93 0 0 1 3.93 3.93v23.18a4.43 4.43 0 0 1-4.28 4.45H17.89A15.18 15.18 0 0 1 2.7 82.06V50.52A15.18 15.18 0 0 0 17.89 65.7Z"/><path fill="url(#b)" d="M97.3 18.99v31.53A15.18 15.18 0 0 1 82.1 65.7H17.6A15.18 15.18 0 0 1 2.65 50.52v-1.16a15.18 15.18 0 0 1 15.2-15.18h64.23a15.18 15.18 0 0 0 15.2-15.2Z"/><g stroke="none"><path fill="#00000026" d="M81.82 5.28a15.23 15.23 0 0 1 5.86 11.99v1.16a15.22 15.22 0 0 1-7.58 13.15h2.04c6.97 0 12.57-5.6 12.57-12.57v-1.16c0-6.97-5.6-12.57-12.58-12.57ZM18.09 36.87a15.23 15.23 0 0 0-5.86 11.99v1.16a15.22 15.22 0 0 0 7.57 13.15h-2.04c-6.97 0-12.56-5.6-12.56-12.57v-1.16c0-6.98 5.6-12.57 12.58-12.57Z"/><path fill="#00f2ff" d="M94.86 31.66a17.84 17.84 0 0 1-7.06 4.3v15.83a15.13 15.13 0 0 1-4.92 11.17 12.45 12.45 0 0 0 11.98-12.48z"/></g></svg>
```

2021-12-20 10:14 UTC, Carlgo11 approved these changes

2022-01-18 19:38 UTC, phallobst requested changes

2022-01-18 19:38 UTC, phallobst commented on entries/p/polisystems.ch.json
> +         "email"
> High-end mail hosting _included_ in your web hosting, ...

As long as they don't offer standalone mail hosting, we should not include `email` here, I think.
```suggestion
         "cloud"
```

2022-01-19 08:47 UTC, phallobst approved these changes

2022-01-19 08:47 UTC, merged

2022-01-19 11:46 UTC, Sethis11263 commented
Seth

On Fri, Dec 17, 2021, 7:59 AM Poli ***@***.***> wrote:

> Please add https://polisystems.ch.
>
> The website is ranked also below 200k ->
> https://www.alexa.com/siteinfo/polisystems.ch
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/2factorauth/twofactorauth/pull/6350
> Commit Summary
>
>    - f064536
>    <https://github.com/2factorauth/twofactorauth/pull/6350/commits/f0645360ae6cd05262ca3f413214cbbe624739c3>
>    Add Poli Systems
>    - b49a42f
>    <https://github.com/2factorauth/twofactorauth/pull/6350/commits/b49a42f063a1943b2df520d419c5110695d4325f>
>    Merge branch '2factorauth:master' into master
>
> File Changes
>
> (2 files <https://github.com/2factorauth/twofactorauth/pull/6350/files>)
>
>    - *A* entries/p/polisystems.ch.json
>    <https://github.com/2factorauth/twofactorauth/pull/6350/files#diff-5e453e4e6011c68752a6989f15f4113f9c771cfc45ca4866f9f25afaebb33bbd>
>    (23)
>    - *A* img/p/polisystems.ch.svg
>    <https://github.com/2factorauth/twofactorauth/pull/6350/files#diff-566c8755d882b2745a4f8cc378031088ffafc77e910552da9e6d394b8189635a>
>    (1)
>
> Patch Links:
>
>    - https://github.com/2factorauth/twofactorauth/pull/6350.patch
>    - https://github.com/2factorauth/twofactorauth/pull/6350.diff
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/2factorauth/twofactorauth/pull/6350>, or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AUAOV2SC45VJ5FDLGEXSKZLURMX2XANCNFSM5KIZIXRQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>