Add eufySecurity
2factorauth/twofactorauth pull request #6353
Opened 2021-12-19 17:13 UTC by ApCoder123

2021-12-19 20:39 UTC, Carlgo11 approved these changes

2021-12-21 17:37 UTC, phallobst requested changes

2021-12-21 17:37 UTC, phallobst commented on entries/e/eufylife.com.json
> +      "email"
The doc states
> Registering your mobile phone number to receive a code via text message is optional.
```suggestion
      "email",
      "sms"
```

2021-12-28 17:41 UTC, phallobst approved these changes

2021-12-28 17:41 UTC, merged