Add T. Rowe Price
2factorauth/twofactorauth pull request #6354
Opened 2021-12-19 17:25 UTC by ApCoder123

2021-12-20 22:06 UTC, Carlgo11 approved these changes

2021-12-20 22:07 UTC, Carlgo11 commented
Note: US VPN tunnel required to access the page.

2021-12-21 17:52 UTC, phallobst requested changes

2021-12-21 17:52 UTC, phallobst commented on img/t/troweprice.com.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="45" height="45" viewBox="0 0 640 640"><path d="M623.368 640v-8.412c3.637-70.817-23.976-116.338-104.582-143.257l85.546-46.702V20.469H15.156v504.807l123.8
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 640"><path fill="#fff" fill-rule="evenodd" d="M0 0h640v640H0z"/><path fill="#05c3de" d="M334.4 298.7c-3.6-.4-3.7-.6-3.7-9.5 0-7 3.7-7.2 10.3-5.3.8-4.4 3-17.4-2.4-17.4-4 0-7 3.1-12.3 3.1-6.1 0-18.1-4.1-22.2-4.1-7.8 0-3.8 13.6-3.8 19 15.5-2 22-4.3 22 3 0 12.1 2 10.2-17.6 12-10.1.8-16 1.3-22 1.5 0 0-5.7-22.9-2.7-27.5a189.7 189.7 0 0 1 17-22.2c3.7-4 3.7-4 1.9-9.7l-12.4-37.8a27.5 27.5 0 0 1 6.3-23.2c1.8-2.4.5-3.4-1.3-2.5-9.7 4.7-25.2 14.8-24.6 28.3.5 10.7-4.1 9-12.3 7.2a55.4 55.4 0 0 0-21.3-1.6c-10.8 1.8-17.4 9.7-16 17.2 1.3 6.7 7.2 12.7 24.2 12.7 16.5 0 18.3-10 25.6 3.2 6.3 11.3 11.6 14.7 2.7 23.5-22.1 22.2-22.9 15-22.9 37.4 0 23.7 25 42.3 38.7 38a207.4 207.4 0 0 0 33.5-10.5c.8-.6.6-2.4-.4-2.5-4.8 0-23.5 0-25-6.7l-2.5-11.7a164.2 164.2 0 0 1 33-2.8c6.1 0 12.3.4 18.4 1.1a33.6 33.6 0 0 0 1.7-10.6 82 82 0 0 0-9.9-1.6zm2.8-63.5a22.7 22.7 0 0 0 19.4 1c12.2-4.1 13.6-18.2.2-20.5-10.5-1.8-13.8 3.6-20.2-2.3l-10.4-10c-1.4-1.3-2.7-2.4-3.4-2.1-.7.2-1 1-.1 3.2a157.8 157.8 0 0 0 14.5 30.7zM0 0v640h184.5a97 97 0 0 0-14.6-39.5c-30.5-35-23.3-84.3-16.8-76.8a45.2 45.2 0 0 0 27.1 17.7 217.8 217.8 0 0 1-24.8-83.1C155.4 338 200 293 200 293s3.6-48.5-2.6-49.7c-14.3-2.8-32.5-15-32.5-30.9a49.5 49.5 0 0 0-51.6 56 18.8 18.8 0 0 0 18 19.3c11 0 15-7 15-16.9a10.9 10.9 0 0 1 12-11.7c3.8 0 10.9 1.6 10.9 22.8a47.7 47.7 0 0 1-13.2 38 47.7 47.7 0 0 1-37.5 14.3c-29.1 0-67.5-21.6-67.5-93.8a129.5 129.5 0 0 1 124.6-125.9 39.8 39.8 0 0 0-15.4 6.9 122.5 122.5 0 0 0-21.6 21 88.8 88.8 0 0 1 10 1 16 16 0 0 0 14.4-4.7 134.1 134.1 0 0 1 12.1-11.9A53.4 53.4 0 0 1 217 117c4.2.7 8.3 1.6 12.3 2.7a67.4 67.4 0 0 0-31 12 150 150 0 0 0-22.8 21s4.1 2.3 6.5 3.6a14.5 14.5 0 0 0 15.4-3.3 120.6 120.6 0 0 1 13.5-11.7 47.2 47.2 0 0 1 25.6-11.2 47.2 47.2 0 0 1 27.4 5.2l4 2.9a93.3 93.3 0 0 0-33.4 10.9 139.2 139.2 0 0 0-28.6 23.8l6 4.8a12.9 12.9 0 0 0 15.8-2.3 123.6 123.6 0 0 1 15.6-13 77.3 77.3 0 0 1 39-12.7c4.3 4.2 5.9 7.9 10 7.9 4.7 0 7.8-3.5 11.6-8.3a49.9 49.9 0 0 1 29 9.2 81.2 81.2 0 0 1 12.4 9c5.7 4.7 10 3.7 12.6 1.2 2-2 4.9-5.4 4.9-5.4a78 78 0 0 0-23-18.4 52 52 0 0 0-26.2-6.8 63.3 63.3 0 0 1 5.4-4.6 36.6 36.6 0 0 1 37.5 3.5 45.9 45.9 0 0 1 11.6 8.8 9.6 9.6 0 0 0 11.6 1.8 25 25 0 0 1 6.4-3.7 63 63 0 0 0-22-18.4 47.5 47.5 0 0 0-16.7-4.7 71.8 71.8 0 0 1 25.2-1.2c36.9 5 47.9 45.8 45.6 81.5-3.9 59.8-1.8 74.2 12.6 74.3a14 14 0 0 0 13.2-13.3c1.2-7.6 3.4-13.6 8.3-13.6 10 0 12.4 9.7 12.4 16 0 40-25.7 48-47.7 48-22 0-39-17.1-45-46.7-1.8-9.4-3.3-18.8-3.3-18.8a36.5 36.5 0 0 0-9.1 3.4c-5.7 2.9-11.5 6.6-11.5 6.6s6.3 14.6 7.6 18.8c.3 8-.2 16-1.6 23.8a237.7 237.7 0 0 1 36 129c0 74.5-27.7 142.7-46.7 168a43.4 43.4 0 0 0 15.7-6.9c17.7-17.4 22.2-20.7 41-22.4 11.8-31 16-69.4 4-156.4 68 47.6 70 87.5 60.4 131C507 520 483 477.2 483 477.2A199.4 199.4 0 0 0 516 495c79 32.4 107.5 75 107.5 136.7v8.4H640V0Z"/></svg>
```

2021-12-22 16:30 UTC, phallobst approved these changes

2021-12-22 16:30 UTC, merged