Add pandadoc
2factorauth/twofactorauth pull request #6370
Opened 2021-12-31 02:01 UTC by blimmer

I was surprised that PandaDoc doesn't support 2fa, so this PR adds it as an unsupported site.

In [this community thread](https://support.pandadoc.com/hc/en-us/community/posts/360051768714-Two-Factor-Authentication-login-to-PandaDoc), they recommend upvoting the [UserVoice request](https://pandadoc.uservoice.com/forums/926629-ideas-to-improve-pandadoc/suggestions/42446389-2fa-two-factor-authentication). I'd like to add a link to that, but the schema doesn't seem to support it. Is there a way I'm not aware of?

2021-12-31 13:45 UTC, phallobst requested changes

2021-12-31 13:45 UTC, phallobst commented on img/p/pandadoc.com.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="64" height="64"><path d="M62.125 0H1.875C.84 0 0 .84 0 1.875v60.25C0 63.16.84 64 1.875 64h60.25C63.16 64 64 63.16 64 62.125V1.875C64 .84 63.16 0 62.125
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 30 30"><path fill="#47b972" d="M0 0h30v30H0Z"/><path fill="#fff" d="M22 11a3.8 3.8 0 0 0-2.6-.9 4.4 4.4 0 0 0-3.4 1.5l1.2 1.4a3 3 0 0 1 2.2-1 2.8 2.8 0 0 1 2.7 3 2.8 2.8 0 0 1-2.7 3c-4.2 0-3-7.8-8.6-7.8A4.7 4.7 0 0 0 6 15v8.5h2V19a3.9 3.9 0 0 0 2.6.9 4.4 4.4 0 0 0 3.5-1.5L12.8 17a3 3 0 0 1-2.2 1 2.8 2.8 0 0 1-2.7-3 2.8 2.8 0 0 1 2.8-3c4.1 0 3 7.8 8.5 7.8a4.7 4.7 0 0 0 4.8-4.9V6.5h-2z"/></svg>
```

2021-12-31 13:45 UTC, phallobst commented on entries/p/pandadoc.com.json
> +    "url": "https://www.pandadoc.com/",
```suggestion
```

2021-12-31 16:47 UTC, blimmer commented
Hey @phallobst, thanks for your review! If you could explain the two changes you requested I'd be happy to try to update the test suite to identify these 😄

2021-12-31 19:43 UTC, phallobst commented
We usually leave out the `url` field if `https://<domain>` is pointing to the correct page (even if some kind of redirection is used).

The SVG logo is just an optimized version, courtesy of [svgo](https://github.com/svg/svgo), [SVGOMG](https://jakearchibald.github.io/svgomg/) and/or [nano](https://vecta.io/nano).

I'm not sure if it's feasible to adjust the test suite.

2021-12-31 19:43 UTC, phallobst approved these changes

2022-01-01 02:14 UTC, Carlgo11 approved these changes

2022-01-01 02:14 UTC, merged