Add MyAnimeList with TOTP support
2factorauth/twofactorauth pull request #6373
Opened 2022-01-01 17:37 UTC by ColinHebert

myanimelist.com [rank 1,049](https://www.alexa.com/siteinfo/myanimelist.net) supports TOTP, add details about it.

2022-01-01 20:50 UTC, Carlgo11 requested changes

2022-01-01 20:50 UTC, Carlgo11 commented on img/m/myanimelist.net.svg
> +<svg id="svg" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="400" height="400" viewBox="0, 0, 400,400"><g id="svgg"><path id="path0" d="M238.200 13
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" style="background:#2c54a4;fill:#fbfbfb" viewBox="0 0 400 400"><path d="M238.2 134.6c-57.8 3.7-80.3 33.7-66.8 89 3.4 13.7 14.3 41.5 15.9 40.5l22.6-14.7c-7.2-12-11.7-26-13.3-37.9l-.2-1.5h38.4v38.8h31.7l-.2-26.7-.3-42.8v-16.1h-31.1l-.3 12.3-.3 12.3-17.8-.2c-19.6-.2-18.7 0-18.3-2.8 1.6-9.9 8-19 16.3-23 6.7-3.3 5.5-3.2 32.4-3.3 8 .1 16-.1 23.9-.4 0-1.1-7.1-23-7.5-23-.7-.4-21.9-.7-25.1-.5m53 57v57.2l65-.2 2.8-11.8 2.8-11.8-17-.2-20.9-.3-3.9-.1v-89.1l-4.1-.3-14.4-.4-10.3-.1v57.1M37.6 248.8h28.8v-35.4c0-19.5.1-35.4.3-35.4.2 0 22.6 27.5 26.1 32 .7.9 1 .4 14.2-15.2l13.6-16 .1 35 .1 35h28.4V135.2h-29.1l-13.7 17.2a448 448 0 0 1-13.9 17l-12.7-17-12.5-17-14.8-.1-14.9-.1"/></svg>
```

2022-01-01 23:21 UTC, Carlgo11 approved these changes

2022-01-03 20:51 UTC, phallobst approved these changes

2022-01-03 20:51 UTC, merged