Add qantas.com with TOTP, SMS and email support
2factorauth/twofactorauth pull request #6375
Opened 2022-01-01 17:46 UTC by ColinHebert

qantas.com [rank 7,057](https://www.alexa.com/siteinfo/qantas.com) supports TOTP, SMS and email 2FA, add details about it.

2022-01-01 21:29 UTC, Carlgo11 requested changes

2022-01-01 21:29 UTC, Carlgo11 commented on img/q/qantas.com.svg
> +<svg viewBox="0 0 206 40" xmlns="http://www.w3.org/2000/svg"><title>qantas</title><defs><linearGradient x1="63.358%" y1="99.626%" x2="14.731%" y2="-.283%" id="a"><stop stop-color="#BE0000" offset="0%
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 34.52 24.53"><defs><linearGradient id="d" x1="0" x2="1" y1="0" y2="0" gradientTransform="translate(267.67 -370.39) scale(12.168)" gradientUnits="userSpaceOnUse" spreadMethod="pad"><stop offset="0" style="stop-color:#fff"/><stop offset=".43" style="stop-color:#fff"/><stop offset="1" style="stop-color:#a2a5a3"/></linearGradient><linearGradient id="c" x1="0" x2="1" y1="0" y2="0" gradientTransform="translate(281.26 -359.1) scale(10.885)" gradientUnits="userSpaceOnUse" spreadMethod="pad"><stop offset="0" style="stop-color:#fff"/><stop offset=".9" style="stop-color:#a2a5a3"/><stop offset="1" style="stop-color:#a2a5a3"/></linearGradient><linearGradient id="b" x1="0" x2="1" y1="0" y2="0" gradientTransform="rotate(-85 -57.37 -338.25) scale(2.59618)" gradientUnits="userSpaceOnUse" spreadMethod="pad"><stop offset="0" style="stop-color:#fff"/><stop offset=".65" style="stop-color:#fff"/><stop offset=".95" style="stop-color:#a2a5a3"/><stop offset="1" style="stop-color:#a2a5a3"/></linearGradient><linearGradient id="a" x1="0" x2="1" y1="0" y2="0" gradientTransform="rotate(-124.4 51.1 -253.65) scale(29.727)" gradientUnits="userSpaceOnUse" spreadMethod="pad"><stop offset="0" style="stop-opacity:.99607843;stop-color:#be0000"/><stop offset="1" style="stop-color:red"/></linearGradient></defs><path d="m267.36-379.3.32.82 1.4 3.67 7.64 20.04h25.16l-20.16-20.25a14.42 14.42 0 0 0-10.14-4.28h-4.21z" style="fill:url(#a)" transform="translate(-267.36 379.3)"/><path d="M269.07-374.81c2.75 4.7 9.98 5.2 10.77 12.51 0 .3.26.55.56.59 4.17.65 8.22 2.37 11.75 5.2h.2c.1-.1.1-.13 0-.18a25.07 25.07 0 0 0-8.77-5.96l-1.02-.41a1.38 1.38 0 0 1-.87-1.33c0-2.19 5.22-1.74 5.75-2.79l.1-.18a9.7 9.7 0 0 0-3.72-1.98c0 .1 0 .31.23.77.31.5-.33 1.3-1.27.44l-.1-.1c-6.99-6.4-12.22-3.08-14.99-10.27l1.4 3.67z" style="fill:#fff" transform="translate(-267.36 379.3)"/><path d="M283.53-367.76v1.74c.75-.21 1.61-.35 2.33-.5v-.97s-1.14.1-1.85-1.09c.21.34 0 .82-.48.82" style="fill:url(#b)" transform="translate(-267.36 379.3)"/><path d="M281.26-361.56c3.87.75 7.61 2.41 10.89 5.05-5.25-4.49-8.45-5.17-9.92-5.17-.58 0-.9.1-.97.12" style="fill:url(#c)" transform="translate(-267.36 379.3)"/><path d="m267.67-378.48 1.4 3.67c2.75 4.7 9.98 5.2 10.77 12.51-.8-9.33-4.9-7.94-9.3-12.19-1.14-.8-2.1-1.99-2.87-3.99z" style="fill:url(#d)" transform="translate(-267.36 379.3)"/></svg>
```

2022-01-01 23:22 UTC, Carlgo11 approved these changes

2022-01-02 20:50 UTC, ApCoder123 approved these changes

2022-01-02 20:50 UTC, merged