Add Stake with TOTP support
2factorauth/twofactorauth pull request #6376
Opened 2022-01-01 17:49 UTC by ColinHebert

[Stake](https://hellostake.com) [rank 26,135](https://www.alexa.com/siteinfo/hellostake.com) supports TOTP, add details about it.

2022-01-01 21:08 UTC, Carlgo11 requested changes

2022-01-01 21:08 UTC, Carlgo11 commented on img/h/hellostake.com.svg
> +<svg id="svg" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="400" height="400" viewBox="0, 0, 400,400"><g id="svgg"><path id="path0" d="M351.653 11
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 112 60"><path fill="#141414" d="M103.5 58.16.6 59.96 8.18 1.8 111.06 0l-7.57 58.16z"/><path fill="#fff" d="M27.48 13.34c-1.7-.28-3.42-.25-5.1.07-2.62.58-4.1 2.44-4.6 6.1l-.16 1.14c-.53 3.49.47 5.8 2.36 9.08l1.41 2.5c1.66 2.9 2.21 4.14 1.76 7.03a9.04 9.04 0 0 1-.7 2.76c-.36.68-.74.96-1.42 1.01-.99.08-1.72-.54-1.52-2.1l.9-6.63-4.99.09-.97 7.02c-.5 3.4.84 5.64 3.6 6.35.95.25 3.4.4 5.33-.16 2.72-.78 4.37-3.14 4.93-7.34l.16-1.2c.52-4.3-.67-6.25-2.8-10.52l-1.38-2.63c-1.36-2.63-1.75-3.54-1.56-5.38l.13-.87c.14-.7.47-1.88 1.61-1.9.8-.02 1.43.61 1.23 2.04l-.66 4.64 4.91-.1.77-5.55c.43-3.1-.7-4.97-3.24-5.45Zm21.8-.28-15.7.27-.68 5 5.38-.1-4.13 29.15 5.04-.08 4.11-29.15 5.29-.09.7-5Zm-5.62 34.16 4.62-.08 1.24-5.2 3.91-.07-.16 5.18 4.8-.08.46-34.07-6 .1-8.87 34.22Zm35.43-34.68-5.08.09-5.58 13.14 1.83-13.08-5.04.09-4.8 34.14 5.03-.08 2.08-14.69 2.09 14.62 5.17-.1-2.6-18.03 6.9-16.1Zm-2.22 34.1 11.67-.2.74-5.2-6.64.12 1.38-9.86 5-.09.73-5.19-5 .09 1.27-8.95 6.35-.1.7-4.97-11.4.2-4.8 34.15Zm19.94-25.18 3.07-.05.54-15.14-3.6 15.19Z"/></svg>
```

2022-01-01 23:23 UTC, Carlgo11 approved these changes

2022-01-03 21:26 UTC, phallobst approved these changes

2022-01-03 21:26 UTC, merged