Add Polywork
2factorauth/twofactorauth pull request #6383
Opened 2022-01-03 07:39 UTC by fletcherdodd

2022-01-03 23:43 UTC, Carlgo11 requested changes

2022-01-03 23:43 UTC, Carlgo11 commented on img/p/polywork.com.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="256" height="257" fill="none" stroke="#000" stroke-width="14.689" xmlns:v="https://vecta.io/nano"><path fill="#6775f8" d="M87.393 7.656h80.787v81.836H87
As the icon is just a 3x3 grid there's no need for a icon larger than 9 pixels.
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" stroke="#000" stroke-width=".153" viewBox="-.0765 -.0765 3.153 3.153"><path fill="#3fbe87" d="M.5 0C.25 0 0 .25 0 .5V1h1V0Z"/><path fill="#6775f8" d="M1 0h1v1H1z"/><path fill="#bd83cf" d="M1 1h1v1H1z"/><path fill="#f39a4a" d="M0 1h1v1H0z"/><path fill="#ff7575" d="M3 .5c0-.25-.25-.5-.5-.5H2v1h1z"/><path fill="#f2c94d" d="M2.5 2c.25 0 .5-.25.5-.5V1H2v1z"/><path fill="#88cfaf" d="M.5 3a.54.54 0 0 1-.5-.5V2h1v1z"/><path fill="#37c2e1" d="M1.5 3c.25 0 .5-.25.5-.5V2H1v1z"/></svg>
```

2022-01-03 23:45 UTC, Carlgo11 approved these changes

2022-01-05 12:45 UTC, phallobst approved these changes

2022-01-05 12:46 UTC, merged