Add AfterPay
2factorauth/twofactorauth pull request #6392
Opened 2022-01-05 02:13 UTC by fletcherdodd

There is no documentation on setting up 2FA on your account, when you first sign up you must verify your phone number and email, they then become the methods without you doing anything, see screenshot below for page that comes up after you input your username and password.

2022-01-05 02:14 UTC, fletcherdodd commented
![image](https://user-images.githubusercontent.com/7688583/148149883-05193001-d808-464f-a2d2-2d2119d078f2.jpeg)

2022-01-05 12:55 UTC, phallobst requested changes

2022-01-05 12:55 UTC, phallobst commented on img/a/afterpay.com.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="19.39" height="17.49"><path d="M18.05 3.543l-2.7-1.6-2.7-1.6c-1.8-1-4.1.3-4.1 2.4v.4a.55.55 0 0 0 .3.5l1.3.7c.4.2.8-.1.8-.5v-.8c0-.4.4-.7.8-.5l2.5 1.4 2
Slightly optimized - also, black is more visible on the green background.
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 22.8 20"><path fill="#000" d="M21.3 4.2 14.5.4c-2-1.1-4.4.3-4.4 2.5v.4c0 .3.2.7.5.8l1.3.8c.3.2.8 0 .8-.5v-1c0-.5.5-.8 1-.5l5.8 3.3c.4.2.4.8 0 1l-5.8 3.4c-.5.2-1-.1-1-.6v-.5c0-2.2-2.5-3.6-4.5-2.5l-6.7 3.8c-2 1-2 4 0 5l6.7 3.8c2 1.1 4.5-.3 4.5-2.5v-.4a1 1 0 0 0-.5-.8l-1.3-.8c-.4-.2-.8 0-.8.5v1c0 .5-.6.8-1 .5l-5.8-3.3a.6.6 0 0 1 0-1L9 9.3c.4-.2 1 .1 1 .6v.5c0 2.2 2.5 3.6 4.4 2.5l6.8-3.8c2-1 2-4 0-5z"/></svg>
```

2022-01-05 22:46 UTC, Carlgo11 approved these changes

2022-01-08 22:17 UTC, phallobst approved these changes

2022-01-08 22:17 UTC, merged