Add region tags to food entries
2factorauth/twofactorauth pull request #6400
Opened 2022-01-10 01:54 UTC by Carlgo11

* Removed Starbucks from Sweden as the Starbucks rewards program isn't available in Sweden.
* Added regions tag to Zamato.

2022-01-15 15:14 UTC, ApCoder123 requested changes

2022-01-15 15:14 UTC, ApCoder123 commented on entries/z/zomato.com.json
> +      "us"
```suggestion
      "ae",
      "au",
      "br",
      "ca",
      "cl",
      "cz",
      "gb",
      "in",
      "id",
      "ie",
      "it",
      "lb",
      "lk",
      "my",
      "nz",
      "ph",
      "pl",
      "pt",
      "qa",
      "sg",
      "sk",
      "sl",
      "za",
      "tr",
      "us",
      "za"
```
There were a few more regions on the country selector dropdown

2022-01-16 09:22 UTC, phallobst approved these changes

2022-01-16 10:51 UTC, ApCoder123 approved these changes

2022-01-16 10:52 UTC, merged