Add DCS
2factorauth/twofactorauth pull request #6414
Opened 2022-01-17 03:50 UTC by Carlgo11

Digital Combat Simulator / DCS World / DCS is a popular flight simulator for Windows. No 2FA documentation but I attached a screenshot of the 2FA setup process.
![screenshot](https://user-images.githubusercontent.com/3535780/149705035-e3c9a5c6-358b-492e-b68c-fd90350e755b.png)

2022-02-11 22:49 UTC, dsoegijono approved these changes

2022-02-13 17:06 UTC, phallobst requested changes

2022-02-13 17:06 UTC, phallobst commented on entries/d/digitalcombatsimulator.com.json
> +    ],
```suggestion
    ],
    "documentation": "https://www.digitalcombatsimulator.com/en/support/faq/User_profile/#3319486",
```

2022-02-13 19:43 UTC, phallobst approved these changes

2022-02-13 19:43 UTC, merged