Remove Bananatag
2factorauth/twofactorauth pull request #6419
Opened 2022-01-18 09:27 UTC by fletcherdodd

Bananatag has merged with and is now known as Staffbase (as per bananatag.com)

2022-01-18 09:50 UTC, phallobst requested changes

2022-01-18 09:50 UTC, phallobst commented on img/s/staffbase.com.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 279.38 281.66"><path fill="#03a4fc" d="m271.05 9.32-5.25 33.53-3.44 21.58a12 12 0 0 0 1 7.69 142.63 142.63 0 0 1 15.11 51.12c3 29.26-1.33 57.23-14
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" width="52.07" height="52.45" fill="#03a4fc"><path d="M26.08 0A26 26 0 0 0 7.32 8.2a26.15 26.15 0 0 0 .64 36.92 25.99 25.99 0 0 0 18.14 7.33 25.9 25.9 0 0 0 18.79-7.97c7.9-8.17 9.43-21.49 3.87-31.68l.73-4.63 1.02-6.5-6.47 1.22-4.66.88-.74-.35A25 25 0 0 0 26.08 0m0 4.64c3.56 0 7.12.95 10.38 2.88l2.3 1.1 6.14-1.17-.98 6.27c5.24 8.18 4.68 20.24-2.37 27.54A21.4 21.4 0 0 1 26.1 47.8a21.48 21.48 0 0 1-15.44-36.4 21.46 21.46 0 0 1 15.42-6.77m-.24 39.15a16.84 16.84 0 0 1-13.68-7.08l3.78-2.69c2.29 3.21 5.99 5.13 9.9 5.13s7.62-1.92 9.9-5.12l3.78 2.69a16.83 16.83 0 0 1-13.68 7.07"/></svg>
```

2022-01-18 11:51 UTC, phallobst commented
Is this a self-hosted service? I don't see a login on their website. In that case, we don't list it here according to our `EXCLUSION.md` policy.

2022-01-20 12:19 UTC, phallobst approved these changes

2022-01-20 13:56 UTC, Carlgo11 approved these changes

2022-01-20 13:56 UTC, merged