Add ALDImobile
2factorauth/twofactorauth pull request #6420
Opened 2022-01-20 13:00 UTC by fletcherdodd

Was unable to find a suitable SVG logo so had to go with a favicon PNG

2022-01-20 14:35 UTC, phallobst commented
There you go:
![](https://raw.githubusercontent.com/phallobst/phallobst/main/resterampe/aldimobile.com.au.svg)

2022-01-24 23:13 UTC, Carlgo11 requested changes
As requested by @phallobst, please replace the icon with the suggested SVG:
```SVG
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 26 26"><defs><radialGradient id="a" cx="13" cy="13" r="13" fx="12" fy="13" gradientUnits="userSpaceOnUse"><stop offset="0" stop-color="#000050"/><stop offset=".63" stop-color="#010151"/><stop offset=".78" stop-color="#040352a5"/><stop offset=".85" stop-color="#03025267"/><stop offset=".93" stop-color="#02025121"/><stop offset="1" stop-color="#01015100"/></radialGradient><filter id="b" width="1.3" height="1.3" x="-.15" y="-.15"><feGaussianBlur/></filter></defs><circle cx="13" cy="13" r="10" fill="none" stroke="url(#a)" stroke-width="6" filter="url(#b)"/></svg>
```
Thanks! 🙂

2022-01-24 23:13 UTC, Carlgo11 commented on entries/a/aldimobile.com.au.json
> +    "img": "aldimobile.com.au.png",
```suggestion
```

2022-01-26 10:17 UTC, phallobst approved these changes

2022-01-26 18:27 UTC, Carlgo11 approved these changes
Thanks for the pull request @fletcherdodd!
It will be public on 2fa.directory within a few minutes.

2022-01-26 18:28 UTC, merged