Update CommunityAmerica CU
2factorauth/twofactorauth pull request #6436
Opened 2022-01-25 23:29 UTC by Carlgo11

Resolves #6432.
Also changed the site name to the one they use on Twitter.

2022-01-26 10:35 UTC, phallobst requested changes

2022-01-26 10:35 UTC, phallobst commented on img/c/communityamerica.com.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 76.2 76.2"><path fill="#fff" d="M14.7 67.8a42 42 0 0 0-9 3L0 73.2 38.7 2.9l37.5 66.5a556 556 0 0 0-29-1.3c-9.9.2-27.6 2.5-27.9 2.5-1.6.1-3.1.3-3.1
The current logo has changed slightly.
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 84.8 75.6"><path fill="#fff" d="M42.5 0 0 75.5c9.3-2.1 17.6-4.1 19-4 1 0-2.2 3.4-.8 4.1 1.8 1 32-6.5 66.6-.3z" class="st0"/><path fill="#e81c2d" d="M25.6 61.9c.8.7 20.3-5.2 46.8-4l-4.8-8.7c-9.4 0-17.1.6-23.2 1.4-.8.1-2-1.1-2-1.1s-1.7 1.7-2.3 1.8c-7.4 1.2-13 2.5-13.5 2.1-2-1.2 2.1-4.3.4-4.4-1.4 0-6 1.9-11 3l-4.9 8.4c5.9-1.2 14-3.4 15.1-2.9 1.6.8-1.4 3.5-.6 4.4z" class="st1"/><path fill="#005eb8" d="M29.6 46.4c1.7.8-1.6 4.2-.5 4.7.7.3 16.3-4.4 36.8-4.6L42.5 4.8 17.4 49.4c6-1.5 11.2-3.4 12.2-3z" class="st2"/><path fill="#e81c2d" d="M23 64.4c-1.7-.8 2.2-4.3.5-4.4-1.2 0-8.7 2-13.8 3.1l-5.1 9c5-1 15.6-3.8 16.9-3.2 1.8.9-1.7 4-.5 4.4 2.3.6 25.2-5.8 59.4-1.1l-6.2-11.3c-29.3-2.3-49.5 4.3-51 3.5z" class="st1"/><path fill="#fff" d="m42.5 50.3-7.8 5.3c-.5.3-1 0-.8-.6l3-8.6-7.8-5.2c-.4-.3-.2-1 .3-1H39l3-8.7c.1-.4.8-.4 1 0l3 8.7h9.5c.6 0 .8.7.3 1l-7.6 5.2 3 8.6c.2.5-.4 1-.8.6z" class="st0"/></svg>
```

2022-01-26 18:35 UTC, phallobst approved these changes

2022-01-29 16:32 UTC, ApCoder123 approved these changes

2022-01-29 16:32 UTC, merged