Update StockX
2factorauth/twofactorauth pull request #6443
Opened 2022-01-28 07:05 UTC by fletcherdodd

2022-01-28 13:16 UTC, phallobst requested changes

2022-01-28 13:16 UTC, phallobst commented on img/s/stockx.com.svg
> +<svg viewBox="0 0 400 457.2"><path d="M283.234 99.8c-64.038 54.89-116.523 99.8-116.633 99.8-.111 0-.201-12.845-.201-28.545v-28.546L83.534 71.555C37.958 32.53.518.54.334.467.15.393 0 25.963 0 57.289v5
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 185 211"><path fill="#296143" fill-rule="evenodd" d="M185 0 77.2 92.2V65.9L0 0v52.8l61.7 52.7L0 158.3V211l107.8-92.2v26.3L185 211v-52.7l-61.7-52.8L185 52.8Z"/></svg>```

2022-01-29 02:54 UTC, Carlgo11 approved these changes

2022-01-29 08:36 UTC, phallobst approved these changes

2022-01-29 08:36 UTC, merged