Add Spaceship
2factorauth/twofactorauth pull request #6445
Opened 2022-01-29 08:42 UTC by fletcherdodd

2022-01-29 11:08 UTC, phallobst requested changes

2022-01-29 11:08 UTC, phallobst commented on img/s/spaceship.com.au.svg
> +<svg viewBox="0 0 24 18"><path fill="#12003B" d="M20.28 2.37s-.6 1.1-2.23 2.78a9 9 0 0 1 .89 3.91c0 4.5-3.28 8.23-7.58 8.94 2.52-.92 4.35-3.25 3.1-5.44-.9-1.58-3.28-1.42-5.75-.37C3.42 14.43.13 15.47.
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 18"><path fill="#12003B" d="M20.3 2.4s-.6 1-2.2 2.8a9 9 0 0 1 .8 3.9 9 9 0 0 1-7.5 8.9c2.5-1 4.3-3.3 3-5.4-.8-1.6-3.2-1.5-5.7-.4C3.4 14.4.1 15.5 0 15.5L20.3 2.4zM9.9 0a9 9 0 0 1 7 3.4C14.4 4.4 8 8.3 5.4 8.8c-2 .3-2.8-.6-3-1.4-.6-1.5 0-3.9 2-5.5A8.8 8.8 0 0 1 10 0zm11.5.9c1.3-.8 2.4-.7 2.4-.7s-.4 1-1.6 1.8l-.4 1.7A7.4 7.4 0 0 0 21 2 7.4 7.4 0 0 0 19.7.5l1.7.4z"/></svg>
```

2022-01-29 14:09 UTC, phallobst approved these changes

2022-01-31 00:26 UTC, Carlgo11 approved these changes

2022-01-31 00:26 UTC, merged