Update Image Validation
2factorauth/twofactorauth pull request #6450
Opened 2022-01-29 17:19 UTC by ApCoder123

Changed error function to take file as parameter, rather than setting a global variable. Fixes error message problem mentioned by @phallobst in https://github.com/2factorauth/twofactorauth/pull/6449#issuecomment-1024949352

2022-01-29 17:25 UTC, phallobst requested changes

2022-01-29 17:25 UTC, phallobst commented on tests/validate-images.rb
> +  error(file, "Unused image at #{file}") unless seen_sites.include? file
```suggestion
  error(file, "Unused image") unless seen_sites.include? file
```

2022-01-29 17:34 UTC, phallobst approved these changes

2022-02-11 22:54 UTC, dsoegijono approved these changes

2022-02-11 22:54 UTC, merged