Add Binge
2factorauth/twofactorauth pull request #6454
Opened 2022-01-30 13:16 UTC by fletcherdodd

2022-01-30 14:41 UTC, phallobst requested changes

2022-01-30 14:41 UTC, phallobst commented on img/b/binge.com.au.svg
> +<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 265 100"><defs><linearGradient xlink:href="#a" id="b" x1="-269.88" x2="-40.06" y1="86.56" y2="86.75" gr
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 242.1 53.1"><defs><linearGradient id="a" x1="2.49" x2="232.31" y1="25.59" y2="25.78" gradientUnits="userSpaceOnUse"><stop offset="0" stop-color="#2173fa"/><stop offset=".14" stop-color="#3241de"/><stop offset=".36" stop-color="#5117bf"/><stop offset=".43" stop-color="#6911ac"/><stop offset=".55" stop-color="#92078b"/><stop offset=".63" stop-color="#a90178"/><stop offset=".72" stop-color="#c00057"/><stop offset=".8" stop-color="#cf0541"/><stop offset=".89" stop-color="#db363a"/><stop offset="1" stop-color="#eb7531"/></linearGradient></defs><path fill="url(#a)" d="M0 53.08h26.2c5.93 0 12.04.37 17.46-2.5 8.32-4.42 13.43-21.02 1.06-23.96 2.25-1.05 4.37-1.83 5.87-3.97 3.5-5 2.95-15.28-1.9-19.21-2.8-2.26-6.36-2.72-9.8-3.06-7.13-.7-14.5-.22-21.69-.22H9.8L7.04.18 6.4 4.13 5 14.19l-5 38.9M61.66.16l-1.85 14.56h18.21l-14.25 7.34-5.2 3.08-1.2 8.1-2.33 19.84H73l.53-3.7 1.35-10.06 3.13-24.6L79.98.12l-6.42.04h-11.9m16.66 52.92 16.42.02 3.44-27.52 3.67 6.35 7.5 14.02 3.82 7.14h16.49l6.62-52.9-16.42-.03-3.44 27.79c-3.83-5.82-6.87-12.56-9.99-18.8A564.28 564.28 0 0 1 102.17.2l-4-.03H88.9l-3.8.05L84.36 6m105.35 16.66h-23.02c1.06 2.54 2.5 5.02 3.86 7.4.57 1.03 2.02 3.1 2.02 3.1s-2.04 2.94-2.97 3.7c-4.79 3.89-12.21.6-14.99-4.14-3.52-6.05-.54-14.5 6-17.08 3.39-1.33 7.28-.91 10.84-.91h19.32L192.62.16H169.6c-4.83 0-9.86-.4-14.55.99-18.74 5.56-24.61 30.6-11.35 44.52 6.74 7.08 15.21 7.4 24.31 7.4h13.23l4.45-.01 1.18-8.18c1.05-7.38 1.48-14.9 2.84-22.23m1.06 30.43h41.27l3.35-.02.7-3.95 1.24-10.32-28.04-.26.53-4.76h23.28l1.85-14.56h-23.28l.53-4.5 28.31-.26L242.1.43 209.29.16h-8.2l-3.57.02-.48 3.95-1.28 10.06-4.98 38.89M20.64 20.8c.23-1.5 1.44-7.63 1.44-7.63l3.06-.04c2.7 0 6.64-.52 8.83 1.45 2.68 2.4.53 5.66-2.21 6.1-1.4.23-2.84.12-4.24.12h-6.88m-2.52 19.86 1.25-8.88 4.78-.06c2.98 0 6.32-.38 8.96 1.3 4.15 2.53.8 6.8-2.41 7.42-1.57.3-3.17.22-4.76.22z"/></svg>
```

2022-01-31 09:31 UTC, phallobst approved these changes

2022-02-01 00:20 UTC, Carlgo11 requested changes

2022-02-01 00:20 UTC, Carlgo11 commented on entries/b/binge.com.au.json
> +			"twitter": "binge"
Support / Customer service accounts are generally preferred if available as the chances of the tweets being seen are greater. I think this is their official customer care twitter handle?
```suggestion
			"twitter": "binge_help"
```

2022-02-01 23:24 UTC, Carlgo11 approved these changes

2022-02-01 23:24 UTC, merged