Add two factor auth info to Foursquare.
2factorauth/twofactorauth pull request #6462
Opened 2022-02-03 14:22 UTC by timonus

As of yesterday Foursquare supports 2FA using email and SMS.

2022-02-03 19:51 UTC, Carlgo11 requested changes
Thanks for the pull request @timonus!

I see that you haven't add any documentation link. Could you maybe find one that describes how to enable 2FA on the site?

If no documentation is available or you can't find it, could you please add some screenshots of the 2FA setup process and/or login process?
__Remember to blur or crop out any personal information linked to you.__

You can attach the screenshots here in a comment, like this:
![screenshot](https://user-images.githubusercontent.com/3535780/62257740-32b4ef00-b407-11e9-8f35-fc7c47ad72fb.gif)

2022-02-13 18:29 UTC, phallobst requested changes

2022-02-13 18:29 UTC, phallobst commented on entries/f/foursquare.com.json
> +    ],
```suggestion
    ],
    "documentation": "https://foursquare.atlassian.net/servicedesk/customer/portal/20/article/3355476115",
```

2022-02-25 01:41 UTC, Carlgo11 approved these changes

2022-02-25 09:43 UTC, phallobst approved these changes

2022-02-25 09:43 UTC, merged