Update dashlane.com.json
2factorauth/twofactorauth pull request #6463
Opened 2022-02-03 16:25 UTC by louis-duncan

Dashlane does not currently support U2F for public use following the transition to using the webapp and removing their desktop app (the desktop app can be installed, but then refuses to run once the user logs in and instead directs them to the webapp). As such, it is no longer possible (despite advertising saying otherwise) to use U2F with dashlane.

2022-02-03 16:32 UTC, louis-duncan commented
I have left the `"u2f"` value as it may well still be supported for corporate customers and I cannot be sure it is not supported at least in _some_ way.

2022-02-03 19:48 UTC, Carlgo11 requested changes
According to https://support.dashlane.com/hc/en-us/articles/207051919 the U2F 2FA option is deprecated so I think it's better to just remove U2F completely from the listing.

2022-02-04 15:15 UTC, louis-duncan commented
According to https://support.dashlane.com/hc/en-us/articles/360021374760#h_01F5AZKY3QW2E9SPWZ1M98JR62
it does look like it is possible to still use a hardware token via WebAuthn by enabling the "Biometric unlock" option. Not sure how best to show this?

2022-02-04 15:16 UTC, Carlgo11 commented
That would be "passwordless" which we don't list as 2FA.

2022-02-25 01:40 UTC, Carlgo11 commented
As the requested changes haven't been resolved yet I'm going to label this PR as inactive.
Unless there's activity within the next week I'll close the PR.

2022-03-03 00:53 UTC, Carlgo11 approved these changes

2022-03-03 10:05 UTC, phallobst approved these changes

2022-03-03 10:06 UTC, merged