Add Ticketmaster
2factorauth/twofactorauth pull request #6472
Opened 2022-02-05 03:29 UTC by fletcherdodd

2022-02-05 14:23 UTC, Carlgo11 approved these changes

2022-02-05 14:35 UTC, Carlgo11 requested changes

2022-02-05 14:35 UTC, Carlgo11 commented on entries/t/ticketmaster.com.json
> +			"entertainment"
Like with #6474, retail is probably the better category.
```suggestion
			"retail"
```

2022-02-06 00:28 UTC, Carlgo11 approved these changes

2022-02-06 09:43 UTC, phallobst approved these changes

2022-02-06 09:43 UTC, merged