Add Ticketek
2factorauth/twofactorauth pull request #6473
Opened 2022-02-05 03:37 UTC by fletcherdodd

Headquarters/Company based out of Australia, hence why the social media channels are linked to the Aus ones.

Unsure whether or not premier.ticketek.com.au would have been the more appropriate main domain as ticketek.com is just a landing page.

2022-02-05 20:25 UTC, phallobst requested changes

2022-02-05 20:25 UTC, phallobst commented on entries/t/ticketek.com.au.json
> +			"premier.ticketek.com.my"
```suggestion
			"ticketek.com.au",
			"ticketek.co.nz",
			"ticketek.co.uk",
			"ticketek.com.sg",
			"ticketek.com.ph",
			"ticketek.com.my"
```

2022-02-05 20:25 UTC, phallobst commented on entries/t/ticketek.com.au.json
> +			"entertainment"
```suggestion
			"retail"
```

2022-02-06 00:28 UTC, Carlgo11 approved these changes

2022-02-06 09:48 UTC, phallobst approved these changes

2022-02-06 09:48 UTC, merged