Add SeatGeek
2factorauth/twofactorauth pull request #6474
Opened 2022-02-05 03:51 UTC by fletcherdodd

2022-02-05 12:12 UTC, phallobst requested changes

2022-02-05 12:12 UTC, phallobst commented on img/s/seatgeek.com.svg
> +<svg xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" fill="currentColor" stroke="none"  width="1.4083333333333334" viewBox="0 0 169 120" class="Icon__Svg-sc-1km1vmv-0 el
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 169 120"><path fill="#ff5b49" d="m23.3 94.74 8.5-.41v10.8c-12.75 1.16-18-3.07-18-15.68 0-11.7 9.48-14.62 18.2-14.62 7.7 0 11.78.85 11.78.85l-2.3-12.12c-2.04-.1-5.63-.22-11.74-.22C15.64 63.34 0 70.1 0 91.44c0 17.99 12.29 27.13 27.88 25.66a372.3 372.3 0 0 1 15.91-1.25V84.56l-18.33.41zm77.3-1.3 9.71.17v-9.3l-9.7-.11v-9.78l16.68.1-2.15-10.91-28.52-.01v51.05c9.68 0 20.24.32 30.62.85l2.25-11.08-18.88-.57V93.44zm-36.32.1 10.42-.12V84.1l-10.42.09v-9.85l16.6.06-2.17-10.8H50.29v51.9c6.55-.43 24.56-.84 30.68-.86l2.16-10.99-18.85.2v-10.3zM168.93 120 150.5 88.64l16.3-25.12h-15.72L136.8 85.9V63.54l-13.95-.02v52.28l13.95.93V92.57l13.78 25.31 18.34 2.12zM23.19 15.24c0-6.31 13.5-4.61 19.72-.95l.58-12.47A57.36 57.36 0 0 0 28.95.01C18.9 0 10.13 5.95 10.13 15.39c0 16.85 22.99 18 22.99 24.76 0 8.9-15.24 3.95-22.99-3.38v14.2s5.7 5.3 17.03 5.3c12.48 0 18.82-8.14 18.82-16.9C46 22.29 23.2 22.22 23.2 15.24zm109.57 39.62 13.94-.03.07-41.9 15.2-1.35L159.83 0a630.07 630.07 0 0 1-40.07 3.5l-2.17 11.22 15.18-.8zm-42.06.02 3.12-9.1 16.06-.11 3.15 9.16 14.03.04L108.5 4.02l-13.27.38-14.01 39.52c-5.74 0-11.12-.04-16.97-.1V33.6l10.46.12V24.5l-10.46-.15v-9.82l16.62.21L78.73 3.8l-28.46-.85v51.88l27.05.08 4.95.01h1.25l7.18-.03zm16-18.46-9.7.12 4.87-14.19z"/></svg>
```

2022-02-05 12:12 UTC, phallobst commented on entries/s/seatgeek.com.json
> +			"entertainment"
```suggestion
			"retail"
```

2022-02-05 12:12 UTC, phallobst commented on entries/s/seatgeek.com.json
> +	"Seat Geek": {
```suggestion
	"SeatGeek": {
```

2022-02-05 14:37 UTC, phallobst approved these changes

2022-02-05 14:41 UTC, Carlgo11 requested changes

2022-02-05 14:41 UTC, Carlgo11 commented on entries/s/seatgeek.com.json
> +		]
```suggestion
		],
		"regions": [
		"ca",
		"us",
		"gb"
		]
```

2022-02-08 01:34 UTC, Carlgo11 approved these changes

2022-02-08 01:34 UTC, merged