Add self-dox warning to social media buttons
2factorauth/twofactorauth pull request #6485
Opened 2022-02-05 22:00 UTC by Carlgo11

This PR adds a warning message when hovering over social media contact buttons in categories with the tag `sensitive`.
![](https://camo.githubusercontent.com/b7d88fabe557936f1a351f097c989628b49a9cdc3d61d0aa71629d8e6b2a13a7/68747470733a2f2f642e74656d7066696c65732e646f776e6c6f61642f44363146454632434344424546322f3f703d394d3435315572784c747633)

My IDE also cleaned up a bunch of white spaces in desktop-table.html so I apologize if the diff is hard to read :sweat_smile: 

* Resolves #1450
* Resolves #3812

2022-02-05 22:29 UTC, phallobst commented
Reading this diff on GitHub is easier if you hide whitespace-only changes:
![image](https://user-images.githubusercontent.com/520841/152661035-c61ef4c4-e117-4757-a13c-1201f6e63aa7.png)

2022-02-06 09:58 UTC, phallobst commented
I'm not quite sure if only certain categories should be considered "sensitive". Depending on your local laws and regulations, almost any category might contain a website that would qualify.

Similar to the region notice in #6484, a flag in the `localStorage` could indicate whether the user wants to keep this warning in. We wouldn't need cookies to do so.

2022-02-06 16:58 UTC, ApCoder123 commented
Are we planning to incorporate this into the mobile layout as well?

2022-03-13 03:41 UTC, Carlgo11 commented
I've addressed the requested changes the following ways:
* Made the tooltip a modal that's displayed on all device types
* Added a local storage variable to only display the warning once
* Switched from a custom Bootstrap v4 to vanilla Bootstrap v5 as the prev version didn't contain modals

2022-03-13 10:16 UTC, phallobst requested changes
I think that after clicking on "I accept the risk", the modal dialog should also be closed.

2022-03-13 10:16 UTC, phallobst commented on js/social-media.js
> +  const uri = `https://facebook.com/${(this).data('facebook')}`;
```suggestion
  const uri = `https://facebook.com/${$(this).data('facebook')}`;
```

2022-03-13 16:17 UTC, phallobst approved these changes

2022-04-15 13:23 UTC, dsoegijono approved these changes

2022-04-15 13:24 UTC, merged