Add HP
2factorauth/twofactorauth pull request #6490
Opened 2022-02-07 08:33 UTC by pitdicker

The category 'retail' doesn't feel like a great fit for HP, but it is the same as for Dell.
Their documentation page is only accessible when you are logged in.

2022-02-07 17:11 UTC, phallobst requested changes

2022-02-07 17:11 UTC, phallobst commented on img/h/hp.com.svg
> +<svg viewBox="0 0 36 36" xmlns="http://www.w3.org/2000/svg"><path d="m18 36c-0.179 0-0.3571-0.0033-0.5349-0.0084l3.678-10.11h5.062c0.8886 0 1.864-0.6831 2.168-1.518l3.991-10.96c0.6529-1.795-0.3751-3.
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 36 36"><path fill="#0096D6" d="M18 36h-.5L21 25.9h5.1c.9 0 1.9-.7 2.2-1.5l4-11c.6-1.8-.4-3.3-2.3-3.3h-7l-6 16.2-3.3 9.2A18 18 0 0 1 13.1.7L9.7 10 4 26h3.8l4.8-13.4h3l-5 13.4h3.9L19 13.4c.7-1.8-.4-3.3-2.3-3.3h-3.2l3.7-10L18 0a18 18 0 1 1 0 36Zm10.9-23.5H26l-4 11H25l4-11Z"/></svg>
```

2022-02-07 17:11 UTC, phallobst commented on entries/h/hp.com.json
> +    "documentation": "https://account.id.hp.com/webcomponents/static/mfa.html",
That link forwards to the login page after just one second (at least for me), so it's probably not useful to be used as a public documentation page. It does explain the TOTP setup process, however.
```suggestion
```

2022-02-08 16:52 UTC, pitdicker commented on img/h/hp.com.svg
> +<svg viewBox="0 0 36 36" xmlns="http://www.w3.org/2000/svg"><path d="m18 36c-0.179 0-0.3571-0.0033-0.5349-0.0084l3.678-10.11h5.062c0.8886 0 1.864-0.6831 2.168-1.518l3.991-10.96c0.6529-1.795-0.3751-3.
I ran the SVG through Inkscape with the save as optimized SVG. Is this the result of another tool? I notice it loses most of the decimals. (Not that I care all that much about the logo to be honest).

2022-02-08 19:50 UTC, phallobst commented on img/h/hp.com.svg
> +<svg viewBox="0 0 36 36" xmlns="http://www.w3.org/2000/svg"><path d="m18 36c-0.179 0-0.3571-0.0033-0.5349-0.0084l3.678-10.11h5.062c0.8886 0 1.864-0.6831 2.168-1.518l3.991-10.96c0.6529-1.795-0.3751-3.
You can play around with [SVGOMG](https://jakearchibald.github.io/svgomg/) and try the "Precision" slider. Usually 1 or 2 is sufficient and will show no distortion, even on full zoom.

2022-02-10 20:16 UTC, pitdicker commented on img/h/hp.com.svg
> +<svg viewBox="0 0 36 36" xmlns="http://www.w3.org/2000/svg"><path d="m18 36c-0.179 0-0.3571-0.0033-0.5349-0.0084l3.678-10.11h5.062c0.8886 0 1.864-0.6831 2.168-1.518l3.991-10.96c0.6529-1.795-0.3751-3.
Thank you, sorry for the slow reply.

2022-02-10 20:30 UTC, phallobst approved these changes

2022-02-15 21:32 UTC, Carlgo11 approved these changes

2022-02-15 21:32 UTC, merged