Add Sumitomo Mitsui Banking Corporation
2factorauth/twofactorauth pull request #6531
Opened 2022-02-17 19:35 UTC by phallobst

Closes #6526

2022-02-17 23:39 UTC, Carlgo11 requested changes

2022-02-17 23:39 UTC, Carlgo11 commented on entries/s/smbc.co.jp.json
> +    "domain": "smbc.co.jp",
A url tag seems to be needed as no website is being served on @
```suggestion
    "domain": "smbc.co.jp",
    "url:" "https://www.smbc.co.jp/",
```

2022-02-17 23:42 UTC, Carlgo11 requested changes

2022-02-17 23:42 UTC, Carlgo11 commented on img/s/smbc.co.jp.svg
> +<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" fill="none" viewBox="0 0 15.06 23"><defs><path id="a" fill="#c4d700" d="M0 11.5V23l4.61-2.01V9.49Zm10.44-9.49v11.5l4
The path seems to be drawn twice for some reason :thinking: 
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 15.06 23"><path fill="#c4d700" d="M0 11.5V23l4.61-2.01V9.49Zm10.44-9.49v11.5l4.62-2.01V0ZM5.22 9.23v11.5l4.62-6.96V2.27L5.22 9.23Z"/></svg>
```

2022-02-18 17:47 UTC, Carlgo11 approved these changes

2022-04-01 15:15 UTC, ApCoder123 approved these changes

2022-04-01 15:16 UTC, merged