Update Sailthru
2factorauth/twofactorauth pull request #6537
Opened 2022-02-18 23:32 UTC by phallobst

2022-02-18 23:44 UTC, Carlgo11 approved these changes

2022-02-19 13:49 UTC, ApCoder123 requested changes

2022-02-19 13:49 UTC, ApCoder123 commented on entries/s/sailthru.com.json
>      ],
```suggestion
    ],
    "notes": "You must contact Sailthru Support to enable 2FA",
```

> Contact Sailthru Support or your CSM to activate this feature on your account.

2022-02-19 15:07 UTC, ApCoder123 approved these changes

2022-02-19 15:08 UTC, merged