Add Profil zaufany
2factorauth/twofactorauth pull request #6543
Opened 2022-02-19 21:25 UTC by mimi89999

2022-02-19 23:09 UTC, Carlgo11 requested changes

2022-02-19 23:09 UTC, Carlgo11 commented on img/p/pz.gov.pl.svg
> +       d="m 0,0 h 8.784 c 0.72,-3.312 1.656,-7.632 1.8,-8.064 0.144,-0.576 0.072,-1.872 -1.8,-1.728 -1.872,0.144 -1.584,-1.44 -1.584,-1.8 0,-0.36 0.288,-1.872 0.288,-1.872 0,0 -0.864,-0.432 -0.936,-0
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" fill="#fff" viewBox="0 0 196.9 142.9"><rect width="196.9" height="142.9" y="0" fill="#00245e" ry="12.7"/><path d="M12.9 0A13 13 0 0 0 0 12.9v117.4c0 7 5.7 12.7 12.8 12.7h15.4c-3.1-15.8-4.1-26.2-.1-33.2 2.6-3.2 7.6-3.8 11.4-3.2 8.6.8 17 4 25.6 3.5 4.1-.2 8.4-3.3 8-7.7.3-4.2-3.5-7.9-1.5-11.9 1-2.4 2-4.3 3-6.4 0-.6-1.5-2-2-2.9-.5-.8-1-1.8-.3-2.8l4.5-2.8c-1-4.2-2.8-10.7-1-14.7 2.4-3.5 7-2.4 10.6-2.7 3.6 0 6.2-4.5 5-9L80.2 0Z"/><path fill="#8bc32e" d="M54.3 0H10.8C4.3.4-.7 7 .1 13.3V98c2.7-3.3 7.1-3.7 11-3 8.5.7 16.9 3.9 25.6 3.4 4-.2 8.3-3.3 8-7.7.3-4.2-3.6-7.8-1.6-12l3-6.3c0-.6-1.4-2-2-3-.5-.7-1-1.7-.3-2.7l4.5-2.8c-1-4.2-2.7-10.8-1-14.7 2.5-3.5 7-2.4 10.7-2.7 3.5 0 6-4.5 5-9L54.2 0Z"/><path d="M174.7 17a6 6 0 0 0-5.7 6.2 6 6 0 0 0 6 5.7 6 6 0 0 0 5.9-6v-.2a6 6 0 0 0-6.2-5.7Z"/><circle cx="158.8" cy="39" r="6"/><circle cx="142.7" cy="39" r="6"/><circle cx="110.5" cy="39" r="6"/><circle cx="110.5" cy="22.9" r="6"/><circle cx="126.5" cy="22.9" r="6"/><circle cx="142.7" cy="22.9" r="6"/><circle cx="174.9" cy="22.9" r="6"/><circle cx="126.5" cy="55.2" r="6"/><circle cx="158.8" cy="55.2" r="6"/><circle cx="175.1" cy="55.2" r="6"/><circle cx="174.9" cy="71.3" r="6"/><circle cx="158.8" cy="71.3" r="6"/><circle cx="142.7" cy="71.3" r="6"/><circle cx="126.5" cy="71.3" r="6"/><circle cx="110.5" cy="71.3" r="6"/><circle cx="126.5" cy="87.4" r="6"/><circle cx="142.7" cy="87.4" r="6"/><circle cx="174.9" cy="87.4" r="6"/><circle cx="174.9" cy="103.5" r="6"/><circle cx="158.8" cy="103.5" r="6"/><circle cx="142.7" cy="103.5" r="6"/><circle cx="126.5" cy="103.5" r="6"/><circle cx="110.5" cy="103.5" r="6"/><circle cx="110.5" cy="119.8" r="6"/><circle cx="142.7" cy="119.8" r="6"/><circle cx="158.8" cy="119.8" r="6"/></svg>
```

2022-02-20 10:55 UTC, phallobst commented
If I can trust deepl.com, there's also the possibility to log in using an ID card with a smartphone or card reader (i.e. `custom-hardware`). Can you check that?

2022-02-20 11:04 UTC, mimi89999 commented
> If I can trust deepl.com, there's also the possibility to log in using an ID card with a smartphone or card reader (i.e. `custom-hardware`). Can you check that?

A qualified digital certificate can also be used.

2022-02-25 01:29 UTC, Carlgo11 approved these changes

2022-05-29 00:31 UTC, merged