Add ING (NL)
2factorauth/twofactorauth pull request #6559
Opened 2022-02-24 13:42 UTC by pitdicker

The record for ING is mostly similar to their branches in other countries.
I also updated the logo the the one that is used as favicon and app logo.
The available SVG was already compressed a too far by a tool like svgomg, so I didn't run it again (not a fan anyway).

I am not sure about the current state of sms support. I believe it is necessary to have a verified number, among other things, but that it is no longer used for authentication.

2022-02-27 10:33 UTC, phallobst requested changes

2022-02-27 10:33 UTC, phallobst commented on entries/i/ing.nl.json
> +  "ING": {
This should include some country idenfication, e.g. `ING (NL)`, `ING (Netherlands)` or `ING (Nederland)`.

2022-02-27 23:19 UTC, Carlgo11 requested changes
The logo provided looks a bit too compressed.
I recommend one of these two:
Square ING logo (4.9KiB):
![square icon](https://user-images.githubusercontent.com/3535780/155904167-47458fd1-2beb-468c-a05b-41a30a46c31a.svg)

Rounded logo (3.3KiB):
![rounded icon](https://user-images.githubusercontent.com/3535780/155904199-362f3129-683e-4f08-bbd9-eb1983b28fde.svg)

2022-02-27 23:19 UTC, Carlgo11 commented on entries/i/ing.nl.json
> +  "ING": {
```suggestion
  "ING (NL)": {
```

2022-04-01 22:50 UTC, Carlgo11 commented
As the requested changes haven't been resolved yet I'm going to label this PR as inactive.
Unless there's activity within the next week I'll close the PR.

2022-04-12 19:06 UTC, Carlgo11 commented
Closing due to inactivity.

2022-04-12 19:06 UTC, closed without merging