Add sefcu.com (State Employees Federal Credit Union) to the directory
2factorauth/twofactorauth pull request #6560
Opened 2022-02-25 17:50 UTC by JPTeasdale

2022-02-25 18:19 UTC, phallobst requested changes

2022-02-25 18:19 UTC, phallobst commented on img/s/sefcu.com.svg
> +</svg>
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 51.48 51.16"><path fill="#a80230" d="M32.14 9.33a9.54 9.54 0 0 0-6.4-2.58 9.7 9.7 0 0 0-6.46 2.53l-.08.08 6.54 6.53 6.49-6.48-.09-.08"/><path fill="#211e1e" d="M38.2 12.44a2.3 2.3 0 0 0-3.27-.01l-11.2 11.12-2.02 2.02 3.27 3.27 2-2 11.2-11.14c.9-.9.91-2.36.01-3.26M10.97 36.35l3.26 3.27 6.02-6.02L17 30.34l-6.02 6.01M42.17 18a2.3 2.3 0 0 0-3.26 0l-5.78 5.77-.04.05-1.84 1.84 3.27 3.26 2.21-2.21 5.44-5.45c.9-.9.9-2.36 0-3.26M21.8 35.04l3.26 3.26 4.69-4.69-3.27-3.26-4.68 4.69m-6.06 6.06 3.28 3.26 1.38-1.4-3.28-3.25-1.38 1.4m27.49-14.82a2.3 2.3 0 0 0-3.26 0l-6.27 6.26-2.52 2.52 3.27 3.26 1.77-1.78.11-.1 6.9-6.9c.9-.9.9-2.36 0-3.26m-18.16-5.43L22.2 18l-5.92-5.9a2.3 2.3 0 1 0-3.26 3.26l6.71 6.72.05.04 2.02 2.02 3.27-3.27m1.41 7.95 4.77 4.76 3.26-3.27-4.76-4.76-3.27 3.27m9.39 9.38 1.4 1.4 3.26-3.27-1.4-1.4-3.26 3.27M21.72 26.97l-9.32-9.33a2.3 2.3 0 1 0-3.27 3.27l12.62 12.62 3.27-3.27-3.3-3.29m4.84 11.33 5.97 6.02 3.28-3.26-5.97-6-3.28 3.25m-12.84-9.96-2.29-2.3a2.3 2.3 0 1 0-3.27 3.25l1.93 1.95 2.3 2.3 3.26-3.27-1.93-1.93m3.36 9.9 4.75 4.74 3.27-3.27-4.75-4.74-3.27 3.27"/><path fill="#211e1e" d="M25.74 0A25.77 25.77 0 0 0 0 25.74c0 6.12 2.22 12.06 6.24 16.72a26 26 0 0 0 15.33 8.66l.03.02 8.14-8.13-3.27-3.27-6.33 6.33c-4-1.13-7.64-3.43-10.4-6.63a20.99 20.99 0 0 1-5.12-13.7A21.14 21.14 0 0 1 25.74 4.62a21.14 21.14 0 0 1 5.73 41.47l-1.76-1.75-3.26 3.26 3.42 3.44.02.12a25.53 25.53 0 0 0 15.41-8.63A25.77 25.77 0 0 0 25.74 0"/></svg>
```

2022-02-25 23:26 UTC, phallobst approved these changes

2022-03-04 02:57 UTC, Carlgo11 approved these changes

2022-03-04 02:57 UTC, merged