Rename BitBay to Zonda
2factorauth/twofactorauth pull request #6563
Opened 2022-02-26 15:34 UTC by phallobst

see https://zondaglobal.com/en/news/bitbay-becomes-zonda

2022-02-28 01:17 UTC, Carlgo11 requested changes

2022-02-28 01:17 UTC, Carlgo11 commented on img/z/zondaglobal.com.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100" fill="none" shape-rendering="crispEdges"><path d="m56.065 2.008 39.82 29.627c7.85 5.84 3.72 18.31-6.064 18.31H75.21c-2.76 0-3.923 3.51
The logo looks off with `shape-rendering="crispEdges"`
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><path d="m56 2 40 29.6A10.2 10.2 0 0 1 90 50H75.1c-2.8 0-4 3.6-1.7 5.2l7.8 5.8A6.9 6.9 0 0 1 77 73.3H23A6.9 6.9 0 0 1 19 61l7.7-5.8c2.2-1.6 1-5.2-1.7-5.2H10.2c-9.8 0-14-12.4-6-18.3L43.8 2A10.2 10.2 0 0 1 56 2zm10.4 91.5L52.2 82.9a3.6 3.6 0 0 0-4.4 0L33.6 93.5a3.6 3.6 0 0 0 2.2 6.5h28.4c3.5 0 5-4.5 2.2-6.5z"/></svg>
```

2022-02-28 12:24 UTC, Carlgo11 approved these changes

2022-03-10 20:46 UTC, ApCoder123 commented on entries/z/zondaglobal.com.json
> +    "documentation": "https://zondaglobal.com/en/helpdesk/zonda-exchange/my-account/how-to-use-two-factor-authentication-provided-by-google-authenticator",
```suggestion
    "documentation": "https://zondaglobal.com/en/helpdesk/zonda-exchange/my-account/how-to-use-two-factor-authentication-provided-by-google-authenticator",
    "recovery": "https://zondaglobal.com/en/helpdesk/zonda-exchange/my-account/what-can-be-done-if-google-authenticator-app-is-lost",
```

2022-03-10 21:01 UTC, ApCoder123 approved these changes

2022-03-10 21:01 UTC, merged