Add SolarWinds
2factorauth/twofactorauth pull request #6565
Opened 2022-02-27 23:43 UTC by Carlgo11

Not sure how FSB feels about this :fearful: 
Pingdom and papertrails are SolarWinds products and use the same SSO portal as all other SolarWinds products.

2022-02-28 18:16 UTC, phallobst requested changes

2022-02-28 18:16 UTC, phallobst commented on entries/s/solarwinds.com.json
> +      "papertrail.com"
Two more related domains, and "solarwinds.cloud" for the login service.
```suggestion
      "papertrail.com",
      "appoptics.com",
      "loggly.com",
      "solarwinds.cloud"
```

2022-02-28 19:50 UTC, phallobst approved these changes

2022-03-28 02:19 UTC, kmpoppe approved these changes

2022-03-28 02:20 UTC, merged