Add Independent Reserve
2factorauth/twofactorauth pull request #6614
Opened 2022-03-24 17:29 UTC by Carlgo11

Resolves #6613

2022-03-27 16:44 UTC, phallobst requested changes

2022-03-27 16:44 UTC, phallobst commented on entries/i/independentreserve.com.json
> +      "totp"
SMS ist not recommended, but it's available nonetheless.
```suggestion
      "totp",
      "sms"
```

2022-03-27 16:44 UTC, phallobst commented on img/i/independentreserve.com.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 63.78 34.44"><path fill="#fff" d="M30.96 21.8c-.35 0-4.02-5.04-5.32-5.73-1.3-.68-3.28-.82-4.95-2.06l-2.26-1.45-4.56-2.86-7.72-4.54-3.32-2.13C1.83
Maybe the logo with blue as the primary color is better?
https://www.independentreserve.com/_nuxt/img/symbol-blue.7294464.svg

2022-03-27 16:44 UTC, phallobst commented on entries/i/independentreserve.com.json
> +      "tw"
Missing regions according to https://www.independentreserve.com/help/getting-started: gl ie im ky nl pt 
```suggestion
      "at",
      "au",
      "be",
      "ca",
      "ch",
      "cz",
      "de",
      "dk",
      "fi",
      "fr",
      "gb",
      "gl",
      "hk",
      "hu",
      "ie",
      "im",
      "is",
      "it",
      "jp",
      "kr",
      "ky",
      "li",
      "lu",
      "mc",
      "mo",
      "nl",
      "no",
      "nz",
      "pl",
      "pt",
      "se",
      "sg",
      "si",
      "sk",
      "tw"
```

2022-03-27 17:56 UTC, phallobst approved these changes

2022-04-15 13:31 UTC, dsoegijono approved these changes

2022-04-15 13:31 UTC, merged