Adds SaxoTraderGo
2factorauth/twofactorauth pull request #6616
Opened 2022-03-26 12:51 UTC by chris-rutkowski

2022-03-26 17:45 UTC, Carlgo11 requested changes
Thanks for the pull request @chris-rutkowski,
There are a few problems with your PR:
* The url should point to the main page of a service, preferably not a login page. It seems that home.saxo is the main domain for the services of Saxo Bank. Please rename the file and change the domain value to reflect that.
* Subdomains should not be used in `additional-domains`.
* You've set `payments` as a category. This category is meant for payment services like Visa, Mastercard, Paypal, Google Pay, Western Union. Are you sure Saxo offers payment services?
* The documentation link you provided confirms that Saxo Bank uses 2FA but the documentation element is primarily meant to show users how to enable 2FA. I recommend you change it to this link instead `https://www.help.saxo/hc/en-us/articles/360038307372`

2022-03-26 18:23 UTC, chris-rutkowski commented
@Carlgo11 thank for the review. All your points are valid and has been addressed in the recent commit.

2022-03-26 18:31 UTC, chris-rutkowski commented
@Carlgo11 I've one question related to the subdomain "www." you mentioned before. 

It looks like you cannot open https://home.saxo/ but you can https://www.home.saxo/ . It really surprises me that such a big financial institution doesn't have a redirect, they use "fancy domains" but without www it doesn't work... The workflows also display warning about this.

2022-03-26 18:32 UTC, Carlgo11 requested changes

2022-03-26 18:32 UTC, Carlgo11 commented on entries/h/home.saxo.json
> +    "SaxoTraderGO": {
Saxo Bank or Saxo Group is probably a better name since the authentication system is for all Saxo platforms.
```suggestion
    "Saxo Bank": {
```

2022-03-26 18:32 UTC, Carlgo11 commented on entries/h/home.saxo.json
> +      "domain": "home.saxo",
It seems their web server isn't configured correctly for HTTPS redirections and therefore a `url` element is needed. 
```suggestion
      "domain": "home.saxo",
      "url": "https://www.home.saxo/",
```

2022-03-26 18:37 UTC, Carlgo11 commented
@chris-rutkowski I noticed the www subdomain thing as well. My latest review adds a url element which directs users of 2fa.directory to the proper web page.
I agree that it's unusual but at the same time it is part of the W3C spec.
Many Japanese sites only serve traffic on the www subdomain while most western sites serve on both or just on @
I guess it's a cultural thing :shrug:

2022-03-26 18:38 UTC, Carlgo11 approved these changes
Looks good! :+1:

2022-03-27 16:17 UTC, phallobst requested changes

2022-03-27 16:17 UTC, phallobst commented on entries/h/home.saxo.json
> +        "investing"
It seems to me that they only offer investment accounts, but neither savings accounts or checking accounts, nor loans or insurance. I'd suggest to leave just `investing` as a keyword then in order to keep it in line with other entries.
```suggestion
        "investing"
```

2022-03-28 21:28 UTC, phallobst approved these changes

2022-03-28 21:28 UTC, merged