Add Storyblocks
2factorauth/twofactorauth pull request #6623
Opened 2022-03-28 11:44 UTC by 40504

2022-03-28 13:51 UTC, Carlgo11 requested changes

2022-03-28 13:51 UTC, Carlgo11 commented on entries/s/storyblocks.com.json
> +    "domain": "storyblocks.com",
The website doesn't redirect HTTPS requests to @ properly. Better to specify the full URL then
```suggestion
    "domain": "storyblocks.com",
    "url": "https://www.storyblocks.com/",
```

2022-03-28 14:06 UTC, Carlgo11 approved these changes

2022-03-28 21:45 UTC, phallobst requested changes

2022-03-28 21:45 UTC, phallobst commented on entries/s/storyblocks.com.json
> +      "other"
```suggestion
      "creativity"
```

2022-03-29 20:34 UTC, phallobst approved these changes

2022-03-29 20:34 UTC, merged