Add LIHKG
2factorauth/twofactorauth pull request #6626
Opened 2022-03-30 08:20 UTC by JasonHK

This is one of the largest forums in Hong Kong, using in-house developed software. I think it should be eligible to add to the directory.

2022-03-30 16:12 UTC, Carlgo11 requested changes

2022-03-30 16:12 UTC, Carlgo11 commented on entries/l/lihkg.com.json
> +    ]
Since it's very region specific I think it would be a good idea to add the `hk` region (and possibly `cn` as well) 
```suggestion
    ],
    "regions": [
      "hk"
    ]
```

2022-03-30 16:12 UTC, Carlgo11 commented on img/l/lihkg.com.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024" xmlns:v="https://vecta.io/nano"><circle cx="512" cy="512" r="512"/><radialGradient id="A" cx="374.02" cy="1309.089" r="635.35" gradient
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024"><circle cx="512" cy="512" r="512"/><radialGradient id="a" cx="374" cy="1309.1" r="635.4" gradientTransform="translate(0 -951)" gradientUnits="userSpaceOnUse"><stop offset="0" stop-color="#fef000"/><stop offset=".3" stop-color="#fef000"/><stop offset=".5" stop-color="#fce701"/><stop offset=".7" stop-color="#f8cf02"/><stop offset=".9" stop-color="#f0a704"/><stop offset="1" stop-color="#ee9a05"/></radialGradient><circle cx="512" cy="512" r="430.7" fill="url(#a)"/><radialGradient id="b" cx="512" cy="1462.6" r="430.7" gradientTransform="translate(0 -951)" gradientUnits="userSpaceOnUse"><stop offset="0" stop-color="#fef000" stop-opacity="0"/><stop offset=".7" stop-color="#fef000" stop-opacity="0"/><stop offset="1" stop-color="#cc4300" stop-opacity=".2"/></radialGradient><circle cx="512" cy="512" r="430.7" fill="url(#b)"/><path d="M770 529c-22 0-41 18-41 41 0 94-85 171-190 171s-190-77-190-171a41 41 0 1 0-82 0c0 139 122 253 272 253s272-114 272-253c0-23-18-41-41-41zm-370-92c38 0 68-33 68-73s-30-72-69-72-68 33-68 72c0 41 31 73 69 73zm278 0c38 0 69-33 69-73s-31-72-69-72-69 33-69 72c1 41 31 73 69 73z"/></svg>
```

2022-04-06 07:11 UTC, JasonHK commented on entries/l/lihkg.com.json
> +    ]
Actually the site is banned in China 😄

2022-04-06 18:11 UTC, Carlgo11 approved these changes
Thanks for the pull request!

2022-05-09 05:16 UTC, dsoegijono approved these changes

2022-05-09 05:16 UTC, merged