Add Paramount+
2factorauth/twofactorauth pull request #6636
Opened 2022-04-03 12:20 UTC by fletcherdodd

2022-04-03 17:38 UTC, Carlgo11 requested changes
Are you using tabs? I don't think JSON allows tabs :thinking:

2022-04-03 17:38 UTC, Carlgo11 commented on entries/p/paramountplus.com.json
> +			"ve"
I only see that they support the following countries:
```suggestion
      "ar",
      "au",
      "bo",
      "br",
      "cl",
      "co",
      "cr",
      "de",
      "do",
      "ec",
      "fi",
      "gt",
      "hn",
      "ni",
      "no",
      "pa",
      "pe",
      "py",
      "se",
      "sv",
      "uy",
      "ve"
```
source: https://www.paramountplus.com/global/
![screenshot](https://user-images.githubusercontent.com/3535780/161440682-7eb73b1f-5ed4-450b-9064-2a5d8cc10ac4.png)

2022-04-04 20:27 UTC, Carlgo11 commented on entries/p/paramountplus.com.json
> +			"ve"
@fletcherdodd you marked this as resolved without updating any code :thinking:

2022-04-04 20:27 UTC, Carlgo11 commented on entries/p/paramountplus.com.json
> +			"ve"
@fletcherdodd you marked this as resolved without updating any code :thinking:

2022-04-12 17:20 UTC, Carlgo11 approved these changes

2022-04-16 14:22 UTC, phallobst approved these changes

2022-04-16 14:22 UTC, merged