Split Klarna
2factorauth/twofactorauth pull request #6671
Opened 2022-04-17 23:43 UTC by Carlgo11

Klarna offers:
* payment services internationally and authenticates through email/SMS/calls (except in NO & SE).
* banking and payment services to Norway and Sweden using software authentication called BankID.

_Note that "BankID" refers to different methods in the two different countries as it's run by completely unrelated companies. It thus can't be merged into the same entry._

To not make duplicate entries I had to use different domain names for all the entries resulting in Klarna SE and Klarna NO not receiving the appropriate SimilarWeb ranking as the domain which they 301 to. Should still be possible to merge though.

2022-04-18 11:36 UTC, phallobst commented on entries/k/klarna.com.json
> -      "se",
Shouldn't these be `"-no"` and `"-se"` instead?

2022-06-30 14:26 UTC, ApCoder123 commented on entries/k/klarna.com.json
>        "email",
> You will receive an email with a login link or a text with a 6-digit verification code 

Do we consider this to be 2FA? Sounds like passwordless

2022-06-30 15:13 UTC, Carlgo11 commented on entries/k/klarna.com.json
>        "email",
Yeah I guess that's just one factor :thinking:

2022-07-10 11:17 UTC, ApCoder123 requested changes

2022-07-10 11:17 UTC, ApCoder123 commented on entries/k/klarna.com.json
> -      "us"
Shouldn't these regions remain here as Klarna is only available in [these countries](https://www.klarna.com/international/)?

2022-07-12 10:50 UTC, ApCoder123 approved these changes

2022-07-12 10:50 UTC, merged