Add Wyre
2factorauth/twofactorauth pull request #6687
Opened 2022-04-29 11:59 UTC by afritz

I struggled to choose the folder bc the co name is "Wyre" but the URL is "sendwyre". I opted to use the s directory and base on url rather than corpname.

2022-04-29 23:38 UTC, Carlgo11 requested changes

2022-04-29 23:38 UTC, Carlgo11 commented on img/s/sendwyre.com.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="96" height="32"><g fill="none" fill-rule="evenodd"><path fill="#061027" d="M53.378 27.099c2.914.41 4.689-.124 6.063-1.497.863-.862 1.52-1.871 2.099-2.93
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><path d="M35.4 19.8h30.3v8L63 34h11v8l-3.3 8h10v6.3l-18.5 24H27.4v-7l3-7H19.2V59z"/><path fill="#fff" d="M71 37H45.4l-15 36.3h4.3l18-23.4h14.8l3.5-8.3ZM37.1 22.4 22.3 59h4.1l17.2-24.7H60l3-7v-4.8z"/></svg>
```

2022-04-29 23:38 UTC, Carlgo11 commented on entries/s/sendwyre.com.json
> +    "documentation": "https://support.sendwyre.com/hc/en-us/articles/360057063573-Enabling-your-Multi-Factor-Authenticator",
```suggestion
    "documentation": "https://support.sendwyre.com/hc/en-us/articles/360057063573",
```

2022-04-29 23:38 UTC, Carlgo11 commented on entries/s/sendwyre.com.json
> +    "recovery": "https://support.sendwyre.com/hc/en-us/articles/360055319134-I-can-t-access-my-account-with-MFA",
```suggestion
    "recovery": "https://support.sendwyre.com/hc/en-us/articles/360055319134",
```

2022-04-29 23:38 UTC, Carlgo11 commented on entries/s/sendwyre.com.json
> +    ],
The domain covers all subdomains so this part isn't needed.
```suggestion
```

2022-04-29 23:38 UTC, Carlgo11 commented on entries/s/sendwyre.com.json
> +      "custom-software"
Looks like TOTP is used.
```suggestion
      "totp"
```

2022-04-30 19:08 UTC, afritz commented
reviewed and committed changes, tx

2022-04-30 22:37 UTC, Carlgo11 commented
The pull request looks fine. The 403 warnings are just warnings and not errors so it can be ignored. Wyre probably uses some kind of proxy which blocks our [bots](https://2fa.directory/bot/) but as you mentioned, the pages display fine in web browsers.

2022-04-30 22:37 UTC, Carlgo11 approved these changes

2022-05-01 09:18 UTC, phallobst requested changes

2022-05-01 09:18 UTC, phallobst commented on img/s/sendwyre.com.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100"><path d="M35.4 19.8h30.3v8L63 34h11v8l-3.3 8h10v6.3l-18.5 24H27.4v-7l3-7H19.2V59z"/><path fill="#fff" d="M71 37H45.4l-15 36.3h4.3l18-23.4
Better leave out the empty padding:
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 61.5 60.5"><path d="M16.2 0h30.3v8l-2.7 6.2h11v8l-3.3 8h10v6.3L43 60.5H8.2v-7l3-7H0v-7.3z"/><path fill="#fff" d="M51.8 17.2H26.2l-15 36.3h4.3l18-23.4h14.8l3.5-8.3zM17.9 2.6 3.1 39.2h4.1l17.2-24.7h16.4l3-7V2.7Z"/></svg>
```

2022-05-01 19:29 UTC, phallobst approved these changes

2022-05-01 19:29 UTC, merged