Add NerdWallet
2factorauth/twofactorauth pull request #6696
Opened 2022-05-06 14:39 UTC by 40504

2022-05-10 23:13 UTC, Carlgo11 requested changes

2022-05-10 23:13 UTC, Carlgo11 commented on entries/n/nerdwallet.com.json
> +      "gb"
There doesn't seem to be any option for UK residents to log in. Probably due to PSD2?
```suggestion
      "ca"
```

2022-05-10 23:17 UTC, Carlgo11 commented
We use the military-banking-grade encryption technology MD5 :laughing: 
![](https://user-images.githubusercontent.com/3535780/167739875-318d58ce-1404-4640-a435-088fbec68ea5.png)

2022-05-18 02:58 UTC, Carlgo11 approved these changes

2022-05-18 20:30 UTC, phallobst requested changes

2022-05-18 20:30 UTC, phallobst commented on entries/n/nerdwallet.com.json
> +      "ca"
https://support.nerdwallet.com/hc/en-us/articles/115001681666
Accounts are available for US residents only.
```suggestion
      "us"
```

2022-05-19 10:54 UTC, phallobst approved these changes

2022-05-19 22:35 UTC, merged