Update GitLab
2factorauth/twofactorauth pull request #6705
Opened 2022-05-10 01:10 UTC by 40504

https://about.gitlab.com/press/press-kit/

2022-05-10 18:32 UTC, phallobst requested changes

2022-05-10 18:32 UTC, phallobst commented on img/g/gitlab.com.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 380 380"><defs><style>.cls-1{fill:#e24329;}.cls-2{fill:#fc6d26;}.cls-3{fill:#fca326;}</style></defs><g id="LOGO"><path class="cls-1" d="M282.83,17
It's propably better to leave out the massive padding.
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 192.1 185"><path fill="#e24329" d="m188.8 73.2-.2-.7-26.2-68.2a6.8 6.8 0 0 0-2.7-3.2 7 7 0 0 0-8 .4 7 7 0 0 0-2.3 3.5l-17.6 54H60.3L42.6 5a6.9 6.9 0 0 0-2.3-3.5 7 7 0 0 0-8-.4 6.9 6.9 0 0 0-2.7 3.2L3.4 72.5l-.2.7a48.5 48.5 0 0 0 16 56l.2.2.2.1 39.8 29.8 19.7 15 12 9a8 8 0 0 0 9.8 0l12-9 19.7-15 40-30h.1a48.6 48.6 0 0 0 16.1-56z"/><path fill="#fc6d26" d="m188.8 73.2-.2-.7a88.3 88.3 0 0 0-35.2 15.8L96 131.7a53007 53007 0 0 0 36.6 27.7l40-30h.1a48.6 48.6 0 0 0 16.1-56.2z" class="cls-2"/><path fill="#fca326" d="m59.4 159.4 19.7 14.9 12 9a8 8 0 0 0 9.8 0l12-9 19.7-15L96 131.7l-36.6 27.7z"/><path fill="#fc6d26" d="M38.6 88.3A88.2 88.2 0 0 0 3.4 72.5l-.2.7a48.5 48.5 0 0 0 16 56l.2.2.2.1 39.8 29.8L96 131.7z" class="cls-2"/></svg>
```

2022-05-11 01:10 UTC, Carlgo11 approved these changes

2022-05-14 11:20 UTC, phallobst approved these changes

2022-05-14 11:20 UTC, merged