added cloudamqp
2factorauth/twofactorauth pull request #6717
Opened 2022-05-12 17:52 UTC by person1234-ux

2022-05-13 15:09 UTC, Carlgo11 commented
@person1234-ux if you want to link an issue with a PR you can write any of the following messages in the PR description:
```
Closes #6712
```
```
Resolves #6712
```
```
Fixes #6712
```
Those are keywords letting GitHub know that the PR and issue are related.

Also, as all other PRs that add a site use the title format `Add <site name>` you might want to consider using that for future PRs. It makes going through multiple PRs easier for us :wink:

2022-05-13 18:23 UTC, Carlgo11 requested changes
I ran the logo through [TinyPNG](tinypng.com) and reduced the image quite a lot. I also suggest you rename it to `cloudamqp.com.png` to follow the naming scheme.
![cloudamqp.com.png](https://user-images.githubusercontent.com/3535780/168344096-abc586d9-0b42-42bd-89a7-33b4dc3cdc40.png)

2022-05-13 18:27 UTC, Carlgo11 requested changes

2022-05-13 18:27 UTC, Carlgo11 commented on entries/c/cloudamqp.com.json
> +    "notes": "Sms is required as a backup method",
As SMS is an abbreviation for Short Messaging Service, all letters should be capitalized.
```suggestion
    "notes": "SMS is required as a backup method",
```

2022-05-13 18:27 UTC, Carlgo11 commented on entries/c/cloudamqp.com.json
> +
```suggestion
```

2022-05-13 18:27 UTC, Carlgo11 commented on entries/c/cloudamqp.com.json
> +      "cloud",
From what I understand RabbitMQ is a message-broker and not cloud computing so the cloud category should be removed.
```suggestion
```

2022-05-13 19:44 UTC, person1234-ux reviewed
done

2022-05-13 19:44 UTC, person1234-ux commented on entries/c/cloudamqp.com.json
> +      "cloud",
ok

2022-05-14 11:59 UTC, phallobst commented
Here is an SVG version of the rabbit logo:
![cloudamqp com](https://user-images.githubusercontent.com/520841/168424685-d8cb9ef9-a7d6-4039-9f5d-55d2b78317a3.svg)

2022-05-18 04:19 UTC, person1234-ux commented
note to self update to use svg instead of png

2022-05-18 20:21 UTC, phallobst approved these changes

2022-05-19 22:36 UTC, Carlgo11 approved these changes

2022-05-19 22:36 UTC, merged