add practice better
2factorauth/twofactorauth pull request #6718
Opened 2022-05-12 21:50 UTC by person1234-ux

2022-05-13 16:22 UTC, person1234-ux commented
resolves #6711

2022-05-14 12:22 UTC, phallobst requested changes
For the logo, you could use one of these
![practicebetter io long](https://user-images.githubusercontent.com/520841/168425486-bc88cd15-4736-4e32-af6a-6f8cd63a5488.svg)

![practicebetter io short](https://user-images.githubusercontent.com/520841/168425487-9b797b7f-e356-4da8-8d53-bec05a647d56.svg)
:

2022-05-14 12:22 UTC, phallobst commented on entries/p/practicebetter.io.json
> +
```suggestion
```

2022-05-14 12:22 UTC, phallobst commented on entries/p/practicebetter.io.json
> +    "documentation": "https://help.practicebetter.io/hc/en-us/articles/360055519791-Using-Two-Factor-Authentication-with-Practice-Better",
```suggestion
    "documentation": "https://help.practicebetter.io/hc/en-us/articles/360055519791",
```

2022-05-14 12:22 UTC, phallobst commented on entries/p/practicebetter.io.json
> +      "food"
```suggestion
      "health"
```

2022-05-14 17:04 UTC, phallobst requested changes

2022-05-14 17:04 UTC, phallobst commented on entries/p/practicebetter.io.json
> +  "practice better": {
```suggestion
  "Practice Better": {
```

2022-05-15 13:42 UTC, phallobst approved these changes

2022-05-18 02:54 UTC, Carlgo11 approved these changes

2022-05-18 02:56 UTC, merged