Add arin.net
2factorauth/twofactorauth pull request #6720
Opened 2022-05-13 16:19 UTC by person1234-ux

resolves #6710 
I wasn't sure what category this website belong it so I just put in under the other category.

2022-05-14 12:39 UTC, phallobst commented
This SVG logo is a bit smaller in file size:
![arin net](https://user-images.githubusercontent.com/520841/168426096-8aed4f5a-0ba7-4500-b52a-8e9982c70dd9.svg)

2022-05-14 15:50 UTC, person1234-ux commented
> This SVG logo is a bit smaller in file size: ![arin net](https://user-images.githubusercontent.com/520841/168426096-8aed4f5a-0ba7-4500-b52a-8e9982c70dd9.svg)

That just includes one letter from the logo as apposed to the whole logo

2022-05-14 17:02 UTC, phallobst commented
It's what they use for their favicon as well, which is our go-to logo variant if the original is too wide to still look good when downscaled to a width of 32 pixels.

2022-05-14 17:04 UTC, person1234-ux commented
ok that makes a lot of sense

2022-05-14 17:23 UTC, phallobst requested changes

2022-05-14 17:23 UTC, phallobst commented on entries/a/arin.net.json
> +  "Arin": {
```suggestion
  "ARIN": {
```

2022-05-14 17:27 UTC, phallobst approved these changes

2022-05-16 02:19 UTC, Carlgo11 approved these changes

2022-05-16 02:19 UTC, merged