Add Deliverr
2factorauth/twofactorauth pull request #6728
Opened 2022-05-18 00:42 UTC by 40504

2022-05-18 02:50 UTC, Carlgo11 requested changes

2022-05-18 02:50 UTC, Carlgo11 commented on img/d/deliverr.com.svg
> +<svg viewBox="0 0 90 54" xmlns="http://www.w3.org/2000/svg"><path d="M89.015 2.972C87.836 1.077 85.705 0 83.478 0H0l10.223 11.046a17.118 17.118 0 0 0 12.568 5.5h48.755c3.866 0 7.329 2.01 9.258 5.381.
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 90 54"><path fill="#0D385E" d="M89.02 2.97A6.49 6.49 0 0 0 83.47 0H0l10.22 11.05a17.12 17.12 0 0 0 12.57 5.5h48.76a10.56 10.56 0 0 1 9.8 6.47l7.78-13.47a6.3 6.3 0 0 0-.11-6.58ZM71.55 20.93H24.22l9.32 10.08a17.12 17.12 0 0 0 12.57 5.5h13.82a10.56 10.56 0 0 1 9.84 6.55l7.18-12.43c1.15-2 1.24-4.48.1-6.49a6.27 6.27 0 0 0-5.5-3.2ZM59.8 40.12a6.94 6.94 0 0 1 6.52 7.32 6.93 6.93 0 0 1-7.29 6.55 6.94 6.94 0 0 1-6.52-7.32 6.92 6.92 0 0 1 7.28-6.55Z"/></svg>
```

2022-05-18 20:19 UTC, phallobst approved these changes

2022-05-19 22:41 UTC, Carlgo11 approved these changes

2022-05-19 22:41 UTC, merged