Add ShipStation
2factorauth/twofactorauth pull request #6729
Opened 2022-05-18 00:58 UTC by 40504

2022-05-18 02:44 UTC, Carlgo11 requested changes

2022-05-18 02:44 UTC, Carlgo11 commented on img/s/shipstation.com.svg
> +<svg viewBox="0 0 59 59" xmlns="http://www.w3.org/2000/svg"><path d="M29.5 0c1.643 0 3.251.14 4.821.398l.969 6.776h-.002a22.826 22.826 0 0 1 5.907 2.444l5.471-4.103a29.708 29.708 0 0 1 6.819 6.819l-4
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 59 59"><path fill="#6CBE45" d="M29.5 0c1.6 0 3.3.1 4.8.4l1 6.8a22.8 22.8 0 0 1 5.9 2.4l5.5-4a29.7 29.7 0 0 1 6.8 6.7l-4.1 5.5a22.8 22.8 0 0 1 2.4 6l6.8.9a29.7 29.7 0 0 1 0 9.6l-6.8 1a22.9 22.9 0 0 1-2.4 5.9l4 5.5a29.7 29.7 0 0 1-6.7 6.8l-5.5-4.1-.5.3a22.9 22.9 0 0 1-5.4 2.1l-1 6.8a29.7 29.7 0 0 1-4.8.4c-1.6 0-3.3-.1-4.8-.4l-1-6.8a22.9 22.9 0 0 1-5.4-2.1l-.5-.3-5.5 4a29.7 29.7 0 0 1-6.8-6.7l4.1-5.5a22.8 22.8 0 0 1-2.3-5.3l-.1-.6-6.8-1a29.7 29.7 0 0 1-.4-4.8c0-1.6.1-3.3.4-4.8l6.8-1a22.8 22.8 0 0 1 2.4-5.9l-4-5.5a29.7 29.7 0 0 1 6.7-6.8l5.5 4.1a22.8 22.8 0 0 1 5.3-2.3l.6-.1 1-6.8a29.7 29.7 0 0 1 4.8-.4Zm0 16.7a12.8 12.8 0 1 0 0 25.6 12.8 12.8 0 0 0 0-25.6Z"/></svg>
```

2022-05-18 14:56 UTC, Carlgo11 approved these changes

2022-05-18 20:17 UTC, phallobst requested changes

2022-05-18 20:17 UTC, phallobst commented on entries/s/shipstation.com.json
> +      "twitter": "ShipStation"
As given on their Twitter page:
```suggestion
      "twitter": "ShipStationHelp",
      "email": "support@shipstation.com"
```

2022-05-19 10:57 UTC, phallobst approved these changes

2022-05-19 10:58 UTC, merged