Add Warner Bros. Games
2factorauth/twofactorauth pull request #6751
Opened 2022-05-29 12:36 UTC by fletcherdodd

2022-05-29 17:02 UTC, Carlgo11 requested changes

2022-05-29 17:02 UTC, Carlgo11 commented on img/w/warnerbrosgames.com.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 285.72 358.3"><path fill="#004db4" d="M69.18 13.49a2 2 0 0 0-1.49 1.87L64.32 30l-27.67 7.43c-.75.19-.94.75-1.13 1.49l-3.74 15.34-26.92 7.1c-.75.19
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 285.7 358.3"><path fill="#004db4" d="M69.2 13.5a2 2 0 0 0-1.5 1.9L64.3 30l-27.7 7.4c-.7.2-.9.8-1 1.5l-3.8 15.4-27 7c-.7.3-1 .8-1.4 2.3A192.7 192.7 0 0 0 0 100c0 107.6 56 201 139.9 256.8a7.5 7.5 0 0 0 3 1.5 7.5 7.5 0 0 0 3-1.5c83.7-55.7 139.8-149.2 139.8-257a191.9 191.9 0 0 0-3.3-36.2c-.4-1.5-.8-2-1.5-2.2l-27-7.1-3.7-15.4c-.2-.7-.4-1.3-1.1-1.5L221.4 30 218 15.4a2 2 0 0 0-1.5-1.9L144.6.2a10.1 10.1 0 0 0-3.5 0Z"/><path fill="#fff" d="M154.8 307.6c70.3-65 91.6-113.3 91.6-142.4 0-16.5-6.3-28.8-22.8-33.3a50.8 50.8 0 0 0 13.1-34c0-30.3-32.1-51.2-82.3-54.6a1 1 0 0 0-1 .9 1.2 1.2 0 0 0 0 .2v262.9c0 .7.7 1 1.4.3Zm-22.4-.3V44.4a1 1 0 0 0-.9-1.1.8.8 0 0 0-.2 0 147.8 147.8 0 0 0-18.7 3.4c-1.5.3-1.9 1-1.9 2.6l.8 134.2c0 16.8 0 30.7.7 46.4 0 1-1.1 1.5-1.5.3-13.8-43-20.2-96.8-19-174.6 0-1.5-.4-1.8-2.3-1a130.1 130.1 0 0 0-18 9.3c-1.1.7-1.5 1.5-1.5 3.3a576 576 0 0 0 11.2 134.6l-4.1 2.6c-1.5 1.2-2.6 1.2-3.7-1C60.3 174.1 52 129.6 52 81.7c0-1.9-1.1-2.6-2.2-1.5a179.4 179.4 0 0 0-16.5 17.2 6.7 6.7 0 0 0-1.8 4.9c1 38.9 13.4 94.2 32.5 127.8 2.3 4.2 5.2 5.3 9 2.7l14.2-9a221.6 221.6 0 0 0 43.8 83.7c.7.8 1.5.4 1.5-.4ZM174.6 68c22.8 1.5 40 13.8 40 28.8 0 15.7-11.2 32.5-40 49.3Zm37 84.9c7.1 0 12 6 12 16.4 0 15-10.8 44.1-49 86.8v-84.5c22-15.7 29.2-18.7 37-18.7Z"/></svg>
```

2022-05-31 22:47 UTC, Carlgo11 requested changes
I see that you haven't add any documentation link. Could you maybe find one that describes how to enable 2FA on the site?

If no documentation is available or you can't find it, could you please add some screenshots of the 2FA setup process and/or login process?
__Remember to blur or crop out any personal information linked to you.__

You can attach the screenshots here in a comment, like this:
![screenshot](https://user-images.githubusercontent.com/3535780/62257740-32b4ef00-b407-11e9-8f35-fc7c47ad72fb.gif)

2022-06-03 11:46 UTC, fletcherdodd commented
This is the password & security area of the account settings. There doesn't seem to be any documentation on their website about setting up 2FA, the support site needs a bit of work done on it
![Password   Security — WB Games Account](https://user-images.githubusercontent.com/7688583/171847586-a47bc14d-e2f2-4264-9a62-46287fa1dd16.png)
.

2022-06-05 15:16 UTC, Carlgo11 approved these changes

2022-06-05 15:16 UTC, merged