add whimsical
2factorauth/twofactorauth pull request #6759
Opened 2022-06-02 03:04 UTC by person1234-ux

2022-06-02 16:36 UTC, Carlgo11 requested changes
I suggest you use this logo instead. Its file size is much more reasonable.
Please use the normal file naming scheme of `whimsical.com.png` for it.
![whimsical.com.png](https://user-images.githubusercontent.com/3535780/171679786-46799274-fc4c-4b62-bd55-caf57ac8d8e7.png)

2022-06-02 16:36 UTC, Carlgo11 commented on entries/w/whimsical.com.json
> +    "documentation": "https://help.whimsical.com/article/664-setting-up-two-factor-authentication-2fa",
```suggestion
    "documentation": "https://help.whimsical.com/article/664--",
```

2022-06-02 16:36 UTC, Carlgo11 commented on entries/w/whimsical.com.json
> +    "img" : "whimsical.png",
```suggestion
    "img" : "whimsical.com.png",
```

2022-06-07 18:58 UTC, phallobst commented
I found an SVG version of their logo in the end...
![whimsical com](https://user-images.githubusercontent.com/520841/172460919-45170642-a00d-41dc-b462-6f8466c2edd1.svg)

2022-06-08 03:56 UTC, person1234-ux commented
I am ready for this pull request to be review and hopefully murged but of course as alway let me know if I need to make any changes before merging

2022-06-08 19:50 UTC, Carlgo11 approved these changes
Thanks @person1234-ux! :+1:

2022-06-08 19:50 UTC, merged