Update int page
2factorauth/twofactorauth pull request #6762
Opened 2022-06-06 01:44 UTC by Carlgo11

I've reworked the regions.rb script to not display sites if:
* They have a regions element
* All of the regions in the regions-element have their own page on 2fa.directory (i.e. "[selectable](https://2fa.directory/api/v3/regions.json)")

That way, people from regions without a dedicated page on 2fa.directory don't see sites only relevant for another region.
i.e. if you're from Luxembourg the banking category isn't filled with U.S. credit unions.

I also replaced `2fa.directory/index.html` with a simple HTML-page linking to the international page. This page should never be displayed to users so if it is, we're more likely to be notified of it and bugs are caught quicker.

2022-06-06 09:32 UTC, phallobst commented
Unfortunately, this also means that a specific site may not come up in the search results if the user is not on a matching region. At least with `int`, this was guaranteed. I'm afraid this is a step in the wrong direction. (Handling regions like a search term would be way easier IMHO.)

2022-06-06 20:00 UTC, Carlgo11 commented
Alright I've reverted that change. Now all sites are displayed on the int page regardless of relevance.
I did however do some cleanup of the regions.rb script and the change to `2fa.directory/index.html` is still included.

2022-07-12 11:39 UTC, ApCoder123 requested changes

2022-07-12 11:39 UTC, ApCoder123 commented on scripts/regions.rb
> +regions = YAML.load_file("#{data_dir}/regions.yml").map { |r| [r['id'], r] }.to_h
```suggestion
regions = YAML.load_file("#{data_dir}/regions.yml").map { |r| [r['id'], { 'name' => r['name'] }] }.to_h
```
For consistency with 'int' key.

2022-07-12 11:39 UTC, ApCoder123 commented on scripts/regions.rb
> +    next unless website['regions']&.reject { |r| r.start_with?('-') }&.include?(key) || key.eql?('int')
```suggestion
    next if website['regions']&.select { |r| r.start_with?('-') }&.map! { |rc| rc.tr('-', '') }&.include?(key)
    # Ignore unless site includes current region, current region is int, site has no regions or site is not excluded in current region
    regions = website['regions']&.reject { |r| r.start_with?('-') }
    next unless regions&.include?(key) || key.eql?('int') || website['regions'].nil? || regions.empty?
```
Current code causes sites with no regions to not be displayed on regional sites and sites with excluded regions to not be displayed on any sites.

2022-07-12 11:39 UTC, ApCoder123 commented on scripts/regions.rb
>    puts `bundle exec jekyll build -s #{dest_dir} --config _config.yml,#{dest_dir}/_config_region.yml -d #{out_dir} --baseurl #{region['id']}`
```suggestion
  puts `bundle exec jekyll build -s #{dest_dir} --config _config.yml,#{dest_dir}/_config_region.yml -d #{out_dir} --baseurl #{key}`
```

2022-11-25 22:11 UTC, closed without merging