Add Coles
2factorauth/twofactorauth pull request #6766
Opened 2022-06-08 11:56 UTC by fletcherdodd

No documentation on how to set up 2FA see the screenshot below of the security and password preferences page.
![Coles 2FA](https://user-images.githubusercontent.com/7688583/172610459-60d8d6e7-2751-428c-974b-edef327a45f0.png)

2022-06-08 15:29 UTC, Carlgo11 requested changes

2022-06-08 15:29 UTC, Carlgo11 commented on entries/c/coles.com.au.json
> +    "notes": "A phone number and email are required for account setup.",
I don't think this is a restriction that needs to be pointed out.
```suggestion
```

2022-06-08 15:29 UTC, Carlgo11 commented on img/c/coles.com.au.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 400 125"><path fill="#E01A22" d="m371.202 67.945-11.36-2.552c-9.136-2.092-14.796-4.696-14.796-11.236 0-5.873 5.721-9.525 14.924-9.525 11.7 0 18.15
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 400 125"><path fill="#E01A22" d="m371 68-11-3c-9-2-15-4-15-11 0-6 6-9 15-9 12 0 18 4 19 13h18c0-9-3-16-9-21-7-5-16-8-27-8s-20 3-26 8-9 12-9 20c0 7 2 13 7 17 4 4 11 6 20 9l14 3c9 3 14 5 14 11 0 7-7 12-18 12-13 0-20-6-21-16v-1h-19v1c0 20 14 32 38 32 12 0 22-3 29-8s10-13 10-22c0-17-10-23-29-27Zm-72-3a26 26 0 0 0-50 0h50Zm20 11a57 57 0 0 1 0 5h-71c2 16 13 26 26 26 9 0 18-6 23-15h20c-6 21-24 33-43 33-24 0-46-19-46-49 0-35 27-47 46-47s45 12 45 47ZM201 0v123h21V0h-21Zm-25 77a29 29 0 1 0-58 0 29 29 0 0 0 58 0Zm19 0a48 48 0 1 1-96 0 48 48 0 0 1 96 0ZM19 77a29 29 0 0 0 55 12h21a48 48 0 1 1 0-24H74a29 29 0 0 0-55 12Z"/></svg>
```

2022-06-09 10:37 UTC, fletcherdodd commented on img/c/coles.com.au.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 400 125"><path fill="#E01A22" d="m371.202 67.945-11.36-2.552c-9.136-2.092-14.796-4.696-14.796-11.236 0-5.873 5.721-9.525 14.924-9.525 11.7 0 18.15
What are you using to improve the SVGs? I am using a combination of 2 websites (one that utilises SVGO) and sometimes Illustrator (which tends to add more unneeded data) but I still can't seem to trim them down as well.

2022-06-09 11:39 UTC, Carlgo11 approved these changes

2022-06-09 18:42 UTC, merged