Add vse.cz (Vysoká škola ekonomická v Praze)
2factorauth/twofactorauth pull request #6768
Opened 2022-06-08 15:51 UTC by lpavlicek

2022-06-08 19:54 UTC, Carlgo11 commented on entries/v/vse.cz.json
> +    "documentation": "https://ci.vse.cz/english/services/insis/multi-factor-authentication/",
The documentation page only mentions TOTP authentication

2022-06-10 17:42 UTC, Carlgo11 requested changes

2022-06-10 17:42 UTC, Carlgo11 commented on img/v/vse.cz.svg
> +<svg xmlns="http://www.w3.org/2000/svg" height="170.467" width="267.293" xml:space="preserve"><path style="fill:#00adef;fill-opacity:1;fill-rule:nonzero;stroke:none" d="M1200.39 1131.03h795.85V877.77
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 267.29 170.47"><path fill="#00adef" d="M160.05 19.68h106.1v33.76h-53.18v21.41h50.41v33.67h-50.41v23.98h54.32v34.82H160.05V19.68M88.07 57.85c0-12.64 7.88-22.82 19.39-26.55L91.43 71.03c-2.12-3.53-3.36-7.81-3.36-13.18zm11.25 21.27 19.86-49.34c8.68.33 15.95 3.12 29.24 11.2V28.45c-10.77-6.27-21.34-9.3-32.11-9.3-21.94 0-39.82 17.3-39.82 39.13 0 11.83 3.91 19.69 9.83 25.42l-24.47 60.64L11.11 19.61H0l60.17 148.94h3.15l31.6-78.48c19.53 11.36 47.61 13.06 47.61 40.41 0 16.64-12.81 29.4-29.27 29.4-10.77 0-19.5-3.89-34.95-15.78v13.4c12.2 8.65 24.18 12.97 35.56 12.97 22.55 0 40.25-17.73 40.25-40.42 0-38.12-35.95-37.88-54.8-50.93m42.57-68.69H90.67V.02h51.22v10.43"/></svg>
```

2022-06-15 22:00 UTC, lpavlicek commented on entries/v/vse.cz.json
> +    "documentation": "https://ci.vse.cz/english/services/insis/multi-factor-authentication/",
I have replaced the legacy documentation page with a new one describing all supported 2FA methods.

2022-06-16 00:05 UTC, Carlgo11 approved these changes

2022-06-16 00:05 UTC, Carlgo11 commented on entries/v/vse.cz.json
> +    "documentation": "https://ci.vse.cz/english/services/insis/multi-factor-authentication/",
Thanks!

2022-06-16 00:05 UTC, merged