Update Linktree
2factorauth/twofactorauth pull request #6786
Opened 2022-06-12 13:42 UTC by fletcherdodd

2022-06-12 18:37 UTC, phallobst requested changes

2022-06-12 18:37 UTC, phallobst commented on entries/l/linktr.ee.json
> +      "sms"
According to their docs, "voice call" is supported as well.
```suggestion
      "sms",
      "call"
```

2022-06-12 23:44 UTC, Carlgo11 approved these changes

2022-06-13 06:09 UTC, phallobst approved these changes

2022-06-13 06:09 UTC, merged