add Masaryk University
2factorauth/twofactorauth pull request #6808
Opened 2022-06-21 08:29 UTC by melanger

Add MUNI Unified Login which supports TOTP and WebAuthn.

2022-06-21 20:19 UTC, Carlgo11 requested changes

2022-06-21 20:19 UTC, Carlgo11 commented on entries/i/id.muni.cz.json
> +      "education",
higher education should be under universities only.
```suggestion
```

2022-06-21 20:19 UTC, Carlgo11 commented on entries/i/id.muni.cz.json
> +    ],
We don't use subdomains. Please rename the files to `muni.cz.json` and `muni.cz.svg`
```suggestion
    "domain": "muni.cz",
```

2022-06-21 20:19 UTC, Carlgo11 commented on img/i/id.muni.cz.svg
> +<svg xmlns="http://www.w3.org/2000/svg" xml:space="preserve" width="61.147" height="97.067"><path d="M344.238 728.012h114.395V0H344.238Zm-42.636 0h38.476L269.355 0h-38.476zm-184.082 0h38.476L226.719
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 36.6 36.6"><path fill="#0000dc" d="M9.92 5v26.6h4.14V5Zm4.29 0 2.59 26.6h1.4L15.62 5Zm6.73 0-2.58 26.6h1.4L22.35 5Zm1.56 0v26.6h4.18V5Z"/></svg>
```

2022-06-21 20:19 UTC, Carlgo11 commented on entries/i/id.muni.cz.json
> +  "MUNI Unified Login": {
Entries don't list the authentication systems but the websites using them. Here that would be Mazarykova univerzita or Masaryk University.
```suggestion
  "Mazarykova univerzita": {
```

2022-06-21 20:19 UTC, Carlgo11 commented on entries/i/id.muni.cz.json
> +    "recovery": "https://it.muni.cz/en/forms/report-a-problem-with-single-sign-on",
A region element would be appropriate here.
```suggestion
    "recovery": "https://it.muni.cz/en/forms/report-a-problem-with-single-sign-on",
    "regions": [
      "cz"
    ],
```

2022-06-21 21:00 UTC, melanger commented on entries/i/id.muni.cz.json
> +    ],
There are subdomain files, like [id.atlassian.com.json](https://github.com/2factorauth/twofactorauth/blob/master/entries/i/id.atlassian.com.json) and [id.nintendo.net.json](https://github.com/2factorauth/twofactorauth/blob/master/entries/i/id.nintendo.net.json). Should I change mine to `muni.cz` or leave it as it is?

2022-06-21 21:04 UTC, melanger commented on entries/i/id.muni.cz.json
> +    "recovery": "https://it.muni.cz/en/forms/report-a-problem-with-single-sign-on",
[CONTRIBUTING.md](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md) says:
```
If a site (with or without 2FA) is only available in certain countries - for example a government site - you can note this with the regions field
```
but the site is available to people world wide and provides access to services from many countries. Should I still add the region?

2022-06-21 21:38 UTC, Carlgo11 commented on entries/i/id.muni.cz.json
> +    "recovery": "https://it.muni.cz/en/forms/report-a-problem-with-single-sign-on",
Yes please.

2022-06-21 21:38 UTC, Carlgo11 commented on entries/i/id.muni.cz.json
> +    ],
I should have said, we don't use subdomains _any longer_. Apparently some have slipped through.

2022-06-22 08:30 UTC, melanger commented
@Carlgo11 I have applied all the suggestions.

2022-06-22 10:54 UTC, phallobst requested changes

2022-06-22 10:54 UTC, phallobst commented on img/m/muni.cz.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 36.6 36.6"><path fill="#0000dc" d="M9.92 5v26.6h4.14V5Zm4.29 0 2.59 26.6h1.4L15.62 5Zm6.73 0-2.58 26.6h1.4L22.35 5Zm1.56 0v26.6h4.18V5Z"/></svg>
Here's the logo without padding:
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 16.76 26.6"><path fill="#0000dc" d="M0 0v26.6h4.14V0Zm4.29 0 2.59 26.6h1.4L5.7 0Zm6.73 0L8.44 26.6h1.4L12.43 0Zm1.56 0v26.6h4.18V0Z"/></svg>
```

2022-06-22 10:58 UTC, phallobst approved these changes

2022-06-22 21:26 UTC, Carlgo11 approved these changes

2022-06-22 21:26 UTC, merged