Update Epic Games
2factorauth/twofactorauth pull request #6814
Opened 2022-06-23 12:37 UTC by fletcherdodd

2022-06-23 15:50 UTC, phallobst requested changes

2022-06-23 15:50 UTC, phallobst commented on entries/e/epicgames.com.json
> +      "fallyguys.com"
```suggestion
      "fallguys.com"
```

2022-06-24 07:09 UTC, fletcherdodd commented on entries/e/epicgames.com.json
> +      "fallyguys.com"
Oops, thanks

2022-06-24 11:35 UTC, phallobst approved these changes

2022-06-24 11:35 UTC, merged