Add Buyee
2factorauth/twofactorauth pull request #6822
Opened 2022-06-24 23:30 UTC by contextnerror

2022-06-25 02:20 UTC, Carlgo11 requested changes, later dismissed
Is the site only available in Japan? If so, please specify that using a _regions_ element.

2022-06-25 02:20 UTC, Carlgo11 commented on entries/b/buyee.jp.json
> +      "twitter": "buyee",
```suggestion
      "twitter": "Buyee",
```

2022-06-25 03:17 UTC, contextnerror commented
Nope, [several different regions.](https://buyee.jp/help/yahoo/guide/countries) They buy stuff from Japan and send it to you, hence the .jp domain.

2022-06-26 21:46 UTC, Carlgo11 commented
I'll let someone else review this site as I'm unable to view the site
![](https://d.tempfiles.download/D62B8D35A36960/?p=pGZVXlx9wsYQrm26Lu3)

2022-06-27 11:26 UTC, phallobst requested changes

2022-06-27 11:26 UTC, phallobst commented on entries/b/buyee.jp.json
> +      "other"
Even though they don't sell the goods themselves, the `retail` category is a better fit, I guess.
```suggestion
      "retail"
```

2022-06-27 18:20 UTC, phallobst approved these changes

2022-06-27 18:20 UTC, merged