Add missing custom-* data
2factorauth/twofactorauth pull request #6839
Opened 2022-07-03 15:56 UTC by ApCoder123

2022-07-04 23:29 UTC, Carlgo11 commented on entries/o/oracle.com.json
>        "custom-hardware",
I don't see any custom hardware?
```suggestion
```

2022-07-05 16:11 UTC, phallobst requested changes

2022-07-05 16:11 UTC, phallobst commented on entries/e/ebay.com.json
>      "documentation": "https://community.ebay.com/t5/Announcements/eBay-launches-a-new-2-step-verification-method-to-increase/ba-p/29818464",
```suggestion
    "documentation": "https://www.ebay.com/help/account/protecting-account/tips-keeping-ebay-account-secure?id=4872#section2",
```

2022-07-06 06:18 UTC, phallobst approved these changes

2022-07-06 06:18 UTC, merged