Add baloise.ch
2factorauth/twofactorauth pull request #6880
Opened 2022-07-29 07:49 UTC by kisst

2022-07-29 08:53 UTC, phallobst requested changes
Is there some publicly accessible documentation? If not, can you provide a screenshot of the setup process (with your personal information redacted)?

2022-07-29 08:53 UTC, phallobst commented on entries/b/baloise.ch.json
> +    "img": "baloise.ch.png",
This is the logo in SVG format, which we prefer:
![baloise ch](https://user-images.githubusercontent.com/520841/181715891-53c5eb83-ea6f-4197-92c3-6593980c8fc6.svg)

2022-07-29 08:53 UTC, phallobst commented on entries/b/baloise.ch.json
> +      "other"
```suggestion
      "finance"
```

2022-08-02 07:48 UTC, kisst commented
> Is there some publicly accessible documentation? If not, can you provide a screenshot of the setup process (with your personal information redacted)?

Not really, neither easy to produce screenshots at this point as it's part of the registration, it's not optional it's mandatory.

2022-08-03 23:53 UTC, Carlgo11 commented
We need some sort of screenshots to confirm. Either of the setup process, login process or settings page.
Also, when are SMS codes required? On login attempts or just for certain actions? Is a password also required?

__Remember to blur or crop out any personal information linked to you when uploading the screenshot(s).__

2022-08-04 13:38 UTC, kisst commented
SMS is sent out for each login and the sessions are short lived, the registration is already impossible without a phone number.

https://www.baloise.ch/en/private-customers/contact-services/customer-portal-mybaloise/registration/page/signup/step0

![screenshoot](https://user-images.githubusercontent.com/4265867/182860887-f8f8c657-48ba-4169-9edc-db6f8339ee5d.png)

2022-08-04 14:51 UTC, Carlgo11 commented
And a password is also required?

2022-08-05 11:25 UTC, kisst commented
![screenshoot_step1](https://user-images.githubusercontent.com/4265867/183067848-e6d25ade-d5cf-4da0-a0a3-64ac9035aff5.png)
Yes step 1 is U/P and step 2 is an SMS with a one time password

2022-08-05 17:52 UTC, Carlgo11 approved these changes

2022-08-07 12:27 UTC, phallobst approved these changes

2022-08-07 12:27 UTC, merged