Add University of Cambridge
2factorauth/twofactorauth pull request #6892
Opened 2022-08-06 01:52 UTC by christopherlam888

2022-08-06 11:04 UTC, phallobst commented
Although we prefer SVG logos, this one is quite chunky (57K). Even with some tweaks I was not able to get it under 20K. I'd suggest to use a PNG logo in this case:
![cam ac uk](https://user-images.githubusercontent.com/520841/183246084-40bb8ec4-0872-4665-8884-aeabb9738917.png)

2022-08-07 01:24 UTC, Carlgo11 requested changes

2022-08-07 01:24 UTC, Carlgo11 commented on entries/c/cam.ac.uk.json
> +      "Authy"
While Authy is mentioned, it's only used in the context of a TOTP RFC-6238 application and no methods specific to Authy are supported.
```suggestion
      "Microsoft Authenticator"
```

2022-08-07 02:02 UTC, Carlgo11 approved these changes

2022-08-07 02:02 UTC, merged