Add Belvo
2factorauth/twofactorauth pull request #6915
Opened 2022-08-24 17:40 UTC by manuel-belvo

Add Belvo.com

2022-08-24 18:26 UTC, phallobst commented
Currently this website has a Similarweb rank of over 200,000 - however, it's climbing rapidly. I'd suggest to re-vist this PR in a week or two and examine the progress then.

2022-08-24 20:51 UTC, Carlgo11 requested changes
Apart from the 200K rank issue, there's no linked image or regions array. Please add that so that the PR can be merged when/if the rank issue gets fixed.

2022-08-24 20:55 UTC, manuel-belvo commented
Thank you for the feedback, folks. I'll work on it.

2022-08-26 23:41 UTC, Carlgo11 requested changes

2022-08-26 23:41 UTC, Carlgo11 commented on img/b/belvo.com.svg
> +</svg>
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 110.3"><path fill="#00101e" d="M43.6 25.8a46 46 0 0 0-18.7 3.9V0H0v108.5h24.9v-3.7a46.2 46.2 0 0 0 18.7 3.7c24.9 0 43.2-17.7 43.2-41.4S69 25.8 43.6 25.8Zm.1 59.2A17.1 17.1 0 0 1 26 67.3c0-10.2 7.7-17.9 17.7-17.9 10.5 0 17.9 7.5 17.9 17.8A17.2 17.2 0 0 1 43.7 85Z"/><circle cx="110" cy="92.3" r="18" fill="#f9c806"/></svg>
```

2022-09-10 13:19 UTC, phallobst commented
The rank is over 500K now - there's hardly any use in pursuing this PR, I guess.

2022-09-10 16:59 UTC, closed without merging