Update ebay
2factorauth/twofactorauth pull request #6945
Opened 2022-09-03 16:25 UTC by alau740

Adds regions in which eBay is supported. To check the list, go to the bottom of [eBay website](https://www.ebay.co.uk) and click on the country button in the footer. 

<img width="155" alt="image" src="https://user-images.githubusercontent.com/77434904/188279284-e74a52dc-26ba-4470-a4ca-bc41d44d876e.png">

2022-09-03 19:07 UTC, phallobst commented
In this case, it would probably be useful  to add an `additional-domains` array as well (for those that are not subdomains of `ebay.com`).

2022-09-03 23:00 UTC, Carlgo11 requested changes

2022-09-03 23:00 UTC, Carlgo11 commented on entries/e/ebay.com.json
> +      "gittigidydor.com",
```suggestion
      "gittigidiyor.com",
```

2022-09-03 23:00 UTC, Carlgo11 commented on entries/e/ebay.com.json
> +      "global.gmarket.co.kr",
```suggestion
      "gmarket.co.kr",
```

2022-09-04 16:43 UTC, Carlgo11 approved these changes

2022-09-04 19:48 UTC, merged