Added BetterStack
2factorauth/twofactorauth pull request #7010
Opened 2022-10-25 12:46 UTC by Leigh-Ola

2022-10-25 13:27 UTC, Leigh-Ola commented
Issue may stem from the fact that I'm trying to add better-uptime, and better-uptime is available as a subdomain of betterstack.com

2022-11-24 00:49 UTC, Carlgo11 requested changes
Hello @Leigh-Ola,
apologies for the delay in reviewing your PR.

I see you attempted to fix a domain name error. The best way of doing this is to rename the file `betteruptime.com.json` and change the domain element to `betteruptime.com`. You can then use the url element to direct people to `https://betterstack.com/better-uptime`.

You entered the Developer tools and Domain Name registration categories in the keywords array. Is this correct?

Regarding the 2FA methods, as the documentation doesn't mention anything about which methods are supported we need some proof that TOTP in fact is supported. Please attach some screenshots of the 2FA setup process and/or login process.
> **Note** Remember to blur or crop out any personal information linked to you.

You can attach the screenshots here in a comment, like this:
![screenshot](https://user-images.githubusercontent.com/3535780/187552643-08eea7e8-e6c6-4873-b31c-0faf4347f69f.gif)

2022-11-24 00:49 UTC, Carlgo11 commented on img/b/betterstack.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="249" height="51" fill="none"><path fill="#fff" d="M53.055 36.106h8.762c4.534 0 7.66-2.328 7.66-6.403 0-2.819-1.655-4.534-3.616-5.3 1.256-.674 2.512-2.20
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 31.07 38.65"><defs><linearGradient id="a" x1="10.36" x2="25.05" y1="6.05" y2="33.68" gradientTransform="translate(-3.37 -5.56)" gradientUnits="userSpaceOnUse"><stop stop-color="#BCBECD"/><stop offset="1" stop-color="#BCBECD" stop-opacity="0"/></linearGradient></defs><path fill="url(#a)" d="M19.09 19.01V3.07a3.06 3.06 0 0 0-5.44-1.93L.69 17.08c-1.63 2-.2 5 2.38 5h12.95c1.7 0 3.07-1.37 3.07-3.07z"/><path fill="#fff" d="M27.82 16.9h-12.4a3.24 3.24 0 0 0-3.24 3.24V35.4a3.24 3.24 0 0 0 5.76 2.05l12.4-15.27a3.24 3.24 0 0 0-2.52-5.28z"/></svg>
```

2022-12-01 21:02 UTC, Carlgo11 commented
Closing due to inactivity.
> **Note**
> The PR author you can still commit the requested changes and re-open this PR.
> If someone else wants to commit the requested changes you can create a new PR and link to this PR.

2022-12-01 21:02 UTC, closed without merging