Added BetKing
2factorauth/twofactorauth pull request #7011
Opened 2022-10-25 12:51 UTC by Leigh-Ola

2022-12-26 03:03 UTC, hkamran80 requested changes

2022-12-26 03:03 UTC, hkamran80 commented on entries/b/betking.com.json
> +      "totp"
```suggestion
      "sms"
```

The two-factor authentication method described in the article is SMS, not TOTP

2022-12-26 03:03 UTC, hkamran80 commented on img/b/betking.com.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="120" height="44" fill="none"><path fill="#ffc400" d="m51.693 0 5.05 3.168L61.794 0l5.05 3.168L71.894 0v8.509H51.693V0z"/><path fill="#fff" d="M57.364 34
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 20.2 8.5"><path fill="#ffc400" d="m0 0 5.05 3.168L10.101 0l5.05 3.168L20.201 0v8.509H0Z"/></svg>
```

Here's a version with just the crown

2023-01-09 21:49 UTC, Carlgo11 commented
Closing due to inactivity.
> **Note**
> The PR author you can still commit the requested changes and re-open this PR.
> If someone else wants to commit the requested changes you can create a new PR and link to this PR.

2023-01-09 21:49 UTC, closed without merging