Add Gumroad
2factorauth/twofactorauth pull request #7063
Opened 2022-11-15 19:39 UTC by hkamran80

2022-11-15 21:41 UTC, Carlgo11 requested changes

2022-11-15 21:41 UTC, Carlgo11 commented on img/g/gumroad.com.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" fill="none"><circle cx="16" cy="16" r="16" fill="#FF90E8"/><path fill="#000" d="M14.61 24.064c-4.686 0-7.443-3.76-7.443-8.436 0-4.86 3.0
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32"><circle cx="16" cy="16" r="16" fill="#FF90E8"/><path d="M14.61 24.06c-4.69 0-7.44-3.76-7.44-8.43 0-4.86 3.03-8.8 8.82-8.8 5.97 0 8 4.03 8.09 6.32h-4.32c-.1-1.28-1.2-3.2-3.86-3.2-2.85 0-4.69 2.47-4.69 5.5s1.84 5.5 4.69 5.5c2.57 0 3.67-2.02 4.13-4.04H15.9v-1.65h8.68v8.44h-3.81v-5.32c-.28 1.92-1.47 5.68-6.16 5.68Z"/></svg>
```

2022-11-15 21:41 UTC, Carlgo11 commented on entries/g/gumroad.com.json
> +      "documentation": "https://help.gumroad.com/article/292-account-login-security",
```suggestion
      "documentation": "https://help.gumroad.com/article/292--",
```

2022-11-15 21:41 UTC, Carlgo11 commented on entries/g/gumroad.com.json
> +      "notes": "2FA is on by default for all users",
This information is not of much use for users as the documentation page already explains this.
```suggestion
```

2022-11-15 23:57 UTC, hkamran80 commented
Out of curiosity, what tool do you use to simplify the SVGs?

2022-11-16 00:32 UTC, Carlgo11 approved these changes

2022-11-16 00:34 UTC, Carlgo11 commented
@hkamran80 I first copy the code to [SVGO](https://jakearchibald.github.io/svgomg/) where I enable everything except `Remove xmlns` and fiddle with the number precision; Then I download the new XML code and make some final adjustments in Notepad and sometimes Inkscape.

2022-11-16 00:34 UTC, hkamran80 commented
> @hkamran80 I first copy the code to [SVGO](https://jakearchibald.github.io/svgomg/) where I enable everything except `Remove xmlns` and fiddle with the number precision; Then I download the new XML code and make some final adjustments in Notepad and sometimes Inkscape.

Thanks!

2022-11-16 00:35 UTC, merged