Add Cal Poly SLO
2factorauth/twofactorauth pull request #7128
Opened 2022-12-17 17:07 UTC by hkamran80

The high-quality/SVG logos are password-protected, requiring a staff or faculty member to access them ([source](https://universitymarketing.calpoly.edu/brand-guidelines/logo/)).

2022-12-17 18:48 UTC, Carlgo11 commented
:grin: 
![](https://user-images.githubusercontent.com/3535780/208256964-aa00363b-57ea-4a09-834f-c78f40b7d44b.svg)

2022-12-17 18:59 UTC, Carlgo11 requested changes

2022-12-17 18:59 UTC, Carlgo11 commented on entries/c/calpoly.edu.json
> +            "Duo token"
Most other uni sites seem to use this name for the token.
```suggestion
            "Duo D100 Token"
```

2022-12-18 00:08 UTC, hkamran80 commented
Thanks for the SVG!

2022-12-18 17:11 UTC, Carlgo11 approved these changes

2022-12-18 17:11 UTC, merged