Update Remotedesktopmanager
2factorauth/twofactorauth pull request #7145
Opened 2022-12-19 02:02 UTC by 40504

2022-12-19 02:14 UTC, Carlgo11 commented
@40504 if you're planning on submitting more pull requests please reset the master branch you're building from. The old and unrelated commits cause some problems when reviewing.
Thanks! 😊

2022-12-19 02:18 UTC, 40504 commented
ok 👍

2022-12-19 21:41 UTC, Carlgo11 requested changes

2022-12-19 21:41 UTC, Carlgo11 commented on entries/r/remotedesktopmanager.com.json
> +    "documentation": "https://helpmac.remotedesktopmanager.com/google_authenticator.html",
```suggestion
    "documentation": "https://helpmac.remotedesktopmanager.com/2-factor_authentication.html",
```

2022-12-19 21:41 UTC, Carlgo11 commented on entries/r/remotedesktopmanager.com.json
>      ],
Looks like multiple 2FA-methods are available:
```suggestion
      "totp",
      "custom-software",
      "custom-hardware"
    ],
    "custom-software": [
      "Duo"
    ],
    "custom-hardware": [
      "Yubico OTP"
    ],
```

2022-12-19 21:41 UTC, Carlgo11 commented on entries/r/remotedesktopmanager.com.json
>      "notes": "2FA is only available on the Enterprise Edition",
```suggestion
    "notes": "2FA is only supported on Devolutions Server, Microsoft Azure SQL, Microsoft SQL Server, SQLite & SQL Server",
```

2023-01-05 02:45 UTC, Carlgo11 commented
Closing due to inactivity.
> **Note**
> The PR author you can still commit the requested changes and re-open this PR.
> If someone else wants to commit the requested changes you can create a new PR and link to this PR.

2023-01-05 02:45 UTC, closed without merging