added datev.de entry and image
2factorauth/twofactorauth pull request #7146
Opened 2022-12-19 12:13 UTC by timreibe

2022-12-19 21:31 UTC, Carlgo11 commented on entries/d/datev.de.json
> +    "documentation": "https://apps.datev.de/help-center/documents/1022936",
Would this be a correct description?
```suggestion
    "documentation": "https://apps.datev.de/help-center/documents/1022936",
    "notes": "2FA only available for DATEV Arbeitnehmer online",
```

2022-12-27 18:57 UTC, Carlgo11 commented
As the requested changes haven't been resolved yet I'm going to label this PR as inactive.
:warning: Unless there's activity within the next 7 days I'll close the PR.

2022-12-29 14:19 UTC, phallobst requested changes, later dismissed

2022-12-29 14:19 UTC, phallobst commented on entries/d/datev.de.json
> +    "documentation": "https://apps.datev.de/help-center/documents/1022936",
There are other methods available as well:
```suggestion
      "totp",
      "sms",
      "custom-hardware"
    ],
    "custom-hardware": [
      "National identity card"
    ],
    "documentation": "https://apps.datev.de/help-center/documents/1022726",
    "notes": "2FA only available for DATEV Arbeitnehmer online",
```

2023-01-02 15:02 UTC, timreibe commented
thanks @Carlgo11 for editing, the changes were correct! Is it ready to merge now?

2023-01-02 22:32 UTC, Carlgo11 approved these changes
Thank you! 🙂
Your contribution will be visible in around 10 minutes. Sometimes it takes longer due to server and browser cache.

2023-01-02 22:33 UTC, merged