Update uber.com.json
2factorauth/twofactorauth pull request #7198
Opened 2022-12-31 00:16 UTC by leggomyinfo

I was using TOTP for Uber. I disabled it and re-enabled it in order to set up TOTP on a different authenticator app. Once re-enabled, SMS was the only option.

2022-12-31 00:24 UTC, hkamran80 requested changes

2022-12-31 00:24 UTC, hkamran80 commented on entries/u/uber.com.json
>      "url": "https://www.uber.com/",
```suggestion
```

The `url` key is only needed if going to the domain (e.g. `https://uber.com`) fails

2022-12-31 00:25 UTC, hkamran80 commented
Interesting that they haven't updated their docs yet

2022-12-31 00:26 UTC, Carlgo11 commented
@leggomyinfo Have you reached out to Uber Support?
Their [help article](https://help.uber.com/riders/article/turn-on-2-step-verification?nodeId=b8bb9152-8c91-4f49-83c4-35cf2e1dcf72) on the matter still states TOTP is supported.

2022-12-31 13:40 UTC, leggomyinfo commented
I just contacted support. I’ll let you know their reply.

On Fri, Dec 30, 2022 at 7:26 PM, Carlgo11 - notifications at github.com ***@***.***> wrote:

> ***@***.***(https://github.com/leggomyinfo) Have you reached out to Uber Support?
> Their [help article](https://help.uber.com/riders/article/turn-on-2-step-verification?nodeId=b8bb9152-8c91-4f49-83c4-35cf2e1dcf72) on the matter still states TOTP is supported.
>
> —
> Reply to this email directly, [view it on GitHub](https://github.com/2factorauth/twofactorauth/pull/7198#issuecomment-1368133605), or [unsubscribe](https://github.com/notifications/unsubscribe-auth/AN25TSZSWOHSZUAI2NJRQD3WP54SZANCNFSM6AAAAAATNHTPHM).
> You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-01-05 21:19 UTC, kmpoppe commented
Pre-Pandemic I wasn't even able to log into my Uber account that I created for a tour in the UK, which nowadays seems to work.
I had set up TOTP in the account in 2019 and it is still working so I wouldn't remove TOTP as of now.

2023-01-05 21:33 UTC, leggomyinfo commented
After a lot of back and forth, Uber support was totally unhelpful. They agreed to escalate the ticket a few days ago — still waiting on a reply.

The primary audience for 2fa.directory is people looking up a site/service to see if a 2FA method is available, not people who already have that 2FA method enabled for the site/service. If you accept that premise, and if TOTP is in fact only available to Uber users who already have it enabled, it makes more sense to remove it and explain the weird situation with the tooltip note. At a minimum, if TOTP remains checked off for Uber, there should be a tooltip note – I'm guessing everyone can agree on that.

If there is someone who is willing to risk losing TOTP for Uber or doesn't already have it, please test it by disabling/re-enabling or trying to enable TOTP for the first time.

2023-01-05 21:40 UTC, kmpoppe commented
> After a lot of back and forth, Uber support was totally unhelpful.

Which was exactly my experience with them after debating why I wasn't able to access my account from Germany when I created it in the UK...

> At a minimum, if TOTP remains checked off for Uber, there should be a tooltip note – I'm guessing everyone can agree on that.

Indeed. With `notes` in the file, an exclamation mark is shown with could be used for warning users that TOTP seems to be unavailable for new setup as of a right now.

2023-01-07 02:02 UTC, Carlgo11 commented
I took it upon myself to verify and yes, it is indeed not an option after resetting it.
I think the note is redundant (and misspelled?) but support removing TOTP from the list.

2023-01-11 17:24 UTC, Carlgo11 requested changes

2023-01-11 17:24 UTC, Carlgo11 commented on entries/u/uber.com.json
> +    "notes": "2FA can only be enabled via the app. TOTP is no longer an option but grandathered in if previously set up.",
```suggestion
    "notes": "2FA can only be enabled via the app",
```

2023-01-12 20:08 UTC, Carlgo11 approved these changes

2023-01-12 20:54 UTC, hkamran80 approved these changes

2023-01-12 20:54 UTC, merged