Add BookBeat
2factorauth/twofactorauth pull request #7218
Opened 2023-01-03 19:01 UTC by slothtown

2023-01-03 19:05 UTC, slothtown commented
I'm still pretty unfamiliar with Github and PR's, so please let me know if there's something here I can do.

2023-01-04 01:43 UTC, hkamran80 requested changes

2023-01-04 01:43 UTC, hkamran80 commented on entries/b/bookbeat.fi.json
> +    "url": "https://www.bookbeat.fi/",
```suggestion
```

The `url` attribute is only needed if going to the domain (e.g. `https://bookbeat.fi`) fails

2023-01-04 01:43 UTC, hkamran80 commented on entries/b/bookbeat.fi.json
> +      "facebook": "bookbeatfi",
```suggestion
      "facebook": "BookBeatFI",
```

2023-01-04 01:43 UTC, hkamran80 commented on img/b/bookbeat.fi.svg
> +<style xmlns="" data-source="base" class="dblt-ykjmwcnxmi"/><style xmlns="" data-source="stylesheet-processor" class="dblt-ykjmwcnxmi"/></svg>
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32.6 38.2"><g fill="none" fill-rule="evenodd"><mask id="a" fill="#fff"><path d="M.015 38.315H250V.074H.015z"/></mask><path fill="#0b0b0a" d="M14.194 36.951h-1.348V15.97c1.72 0 9.75.46 9.75 9.864 0 10.44-6.176 11.118-8.402 11.118zM12.842 1.664c.242 0 .78.002 1.027.022 2.798.228 5.681 1.976 5.681 6.138 0 4.807-3.679 6.622-6.708 6.622zm6.794 13.065c2.727-.082 7.34-1.803 7.34-7.02 0-5.691-6.441-7.635-13.216-7.635H.79a.79.79 0 00-.79.79v.019c0 .36.253.645.594.764 1.374.479 1.997.025 1.997 2.035v31.035c0 2.01-.623 1.556-1.997 2.034-.341.12-.594.404-.594.765v.019c0 .436.353.789.79.789h14.667c11.513 0 17.14-3.709 17.14-12.485 0-7.9-6.315-11.11-12.961-11.11z" mask="url(#a)"/></g></svg>
```

Here's a minified SVG

2023-01-04 01:43 UTC, hkamran80 commented on entries/b/bookbeat.fi.json
> +    "contact": {
```suggestion
    "additional-domains": [
      "bookbeat.at",
      "bookbeat.be",
      "bookbeat.com",
      "bookbeat.dk",
      "bookbeat.fr",
      "bookbeat.de",
      "bookbeat.it",
      "bookbeat.nl",
      "bookbeat.no",
      "bookbeat.pl",
      "bookbeat.es",
      "bookbeat.se",
      "bookbeat.ch",
      "bookbeat.co.uk"
    ],
    "contact": {
```

BookBeat has regional sites as well

2023-01-04 01:43 UTC, hkamran80 commented on entries/b/bookbeat.fi.json
> +      "fi"
```suggestion
      "fi",
      "at",
      "be",
      "bg",
      "hr",
      "cy",
      "cz",
      "dk",
      "ee",
      "fr",
      "de",
      "gr",
      "hu",
      "ie",
      "it",
      "lv",
      "lt",
      "lu",
      "mt",
      "nl",
      "no",
      "pl",
      "pt",
      "ro",
      "sk",
      "si",
      "es",
      "se",
      "ch",
      "gb"
```

BookBeat has regional sites as well

2023-01-04 03:24 UTC, Carlgo11 requested changes

2023-01-04 03:24 UTC, Carlgo11 commented on entries/b/bookbeat.fi.json
> +    "domain": "bookbeat.fi",
As BookBeat operates internationally, an international TLD is preferred over a local one.
```suggestion
    "domain": "bookbeat.com",
```

2023-01-04 03:24 UTC, Carlgo11 commented on entries/b/bookbeat.fi.json
> +      "language": "fi"
```suggestion
      "email": "help@bookbeat.com",
      "facebook": "BookBeatApp"
```

2023-01-04 11:14 UTC, slothtown commented
Sorry for the commit mess, I'm still not that used to Github workflow and made some mistakes

2023-01-04 16:26 UTC, Carlgo11 commented
I see that.
If you're using Git:
```sh
git reset --hard 7115fc6f84b50982a8be1797bc1ada715e3c6947
git push -f
```

If you're using the web browser, let me know and I'll try and reset the branch for you.

2023-01-04 17:29 UTC, slothtown commented
Thank you, I just did that.

2023-01-04 19:24 UTC, Carlgo11 approved these changes
Thank you! 🙂
Your contribution will be visible in around 10 minutes. Sometimes it takes longer due to server and browser cache.

2023-01-04 19:24 UTC, merged

2023-01-04 19:38 UTC, slothtown commented
No problem! And thanks for the help!