Specify net-http instead of httpclient in header
2factorauth/twofactorauth pull request #7276
Opened 2023-01-14 20:18 UTC by phallobst

2023-01-14 21:04 UTC, Carlgo11 commented
Gem.loaded_specs['net-http'].version just returns nil for me

2023-01-14 21:18 UTC, Carlgo11 requested changes

2023-01-14 21:18 UTC, Carlgo11 commented on tests/language-codes.rb
> +    "(Net::HTTP/#{Gem.loaded_specs['net-http'].version} on Ruby/#{RUBY_VERSION}; +https://2fa.directory/bot)",
```suggestion
    "(Ruby/#{RUBY_VERSION}; +https://2fa.directory/bot)",
```

2023-01-14 21:18 UTC, Carlgo11 commented on tests/region-codes.rb
> +    "(Net::HTTP/#{Gem.loaded_specs['net-http'].version} on Ruby/#{RUBY_VERSION}; +https://2fa.directory/bot)",
```suggestion
    "(Ruby/#{RUBY_VERSION}; +https://2fa.directory/bot)",
```

2023-01-14 22:48 UTC, phallobst commented
> `Gem.loaded_specs['net-http']` just returns nil for me

That's basically how I stumbled upon this problem - the `httpclient` gem was not installed and the script gave me an error message. Does the test work for you at all, @Carlgo11? (Without the cached file in `/tmp`, that is.)

2023-01-14 22:56 UTC, Carlgo11 commented
Script works fine without `Gem.loaded_specs['net-http']`.
httpclient is also in the tests group so running `bundle install --with tests` should install it for you.

2023-01-15 10:04 UTC, phallobst commented
Since these tests use Net::HTTP instead of HTTPClient, I figured it would be useless to specify the `httpclient` version, but leaving it out altogether is okay for me as well. :man_shrugging:

2023-01-15 12:53 UTC, Carlgo11 approved these changes

2023-01-15 12:55 UTC, Carlgo11 commented
Net is part of the core Ruby methods so it makes sense leaving it out.

2023-01-15 12:55 UTC, merged