Add Yle
2factorauth/twofactorauth pull request #7278
Opened 2023-01-15 14:22 UTC by slothtown

2023-01-15 23:16 UTC, Carlgo11 commented
I don't see any places to log in :thinking:

2023-01-16 02:33 UTC, slothtown commented
There should be a login icon on the top right of the page. Maybe it's easier to find on the English page: https://yle.fi/news

2023-01-16 21:56 UTC, Carlgo11 requested changes

2023-01-16 21:56 UTC, Carlgo11 commented on entries/y/yle.fi.json
> +      "form": "https://asiakaspalvelu.yle.fi/csp",
```suggestion
      "email": "yleinfo@yle.fi",
```

2023-01-16 21:57 UTC, Carlgo11 requested changes

2023-01-16 21:57 UTC, Carlgo11 commented on entries/y/yle.fi.json
> +      "twitter": "yleuutiset",
```suggestion
      "twitter": "Yleisradio",
```

2023-01-17 22:39 UTC, Carlgo11 approved these changes

2023-01-17 22:39 UTC, merged