Add Tiketti
2factorauth/twofactorauth pull request #7283
Opened 2023-01-17 10:41 UTC by slothtown

Feel free to crop the svg to only have the icon, I had problems trying to do that as I have no experience with svg editing.

2023-01-17 12:00 UTC, slothtown commented
I finally understood how to crop the svg. Hope it's good now.

2023-01-17 21:53 UTC, phallobst requested changes

2023-01-17 21:53 UTC, phallobst commented on img/t/tiketti.fi.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="194.872" height="194.871" viewBox="0 0 146.154 146.153"><defs><clipPath id="a"><path d="M0 0h841.89v595.276H0Z"/></clipPath><clipPath id="b" clipPathUni
There is still a bit of  superfluous stuff in there, so here's an optimized version:
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 146.154 146.153"><path fill="#dfa726" d="M97.359 146.153c26.948 0 48.795-21.846 48.795-48.795 0-26.948-21.847-48.794-48.795-48.794S48.564 70.41 48.564 97.358c0 26.949 21.847 48.795 48.795 48.795M0 97.358c0-26.87 21.722-48.667 48.564-48.792v97.584C21.722 146.025.001 124.23.001 97.358m48.563-48.794V.001C21.799.126.127 21.798.004 48.564ZM97.362 0c26.87 0 48.667 21.721 48.792 48.563H48.57C48.695 21.721 70.49 0 97.362 0"/></svg>
```

2023-01-18 10:41 UTC, Carlgo11 approved these changes

2023-01-18 11:31 UTC, phallobst approved these changes

2023-01-18 11:31 UTC, merged