Add CMG (Checkmate Gaming)
2factorauth/twofactorauth pull request #7432
Opened 2023-02-22 20:56 UTC by coreystone

About: Site used to host gaming tournaments and competitions.
Similarweb ranking: [#60,455](https://www.similarweb.com/website/checkmategaming.com/#overview)

2023-02-22 20:59 UTC, hkamran80 requested changes

2023-02-22 20:59 UTC, hkamran80 commented on entries/c/checkmategaming.com.json
> +    "domain": "checkmategaming.com",
```suggestion
    "domain": "checkmategaming.com",
    "img": "checkmategaming.com.png",
```

2023-02-22 21:01 UTC, coreystone commented
I apologize, I didn't resize the .png. What should I do?

2023-02-22 21:03 UTC, hkamran80 commented
You need to add an `img` tag to the JSON entry. You can click "Commit suggestion" on the requested changes above to add it automatically.

2023-02-22 21:24 UTC, coreystone commented
> You need to add an `img` tag to the JSON entry. You can click "Commit suggestion" on the requested changes above to add it automatically.

Thanks for the quick and helpful response. I've committed the suggestion. This was my first pull request so still figuring out what I'm doing. Also forgot to resize the .png:  `Error:  PNGs must be one of the following sizes: 32x32, 64x64, 128x128.` Do I need to re-submit the image.

Resized to 128x128, tests are passing now.

2023-02-22 21:30 UTC, hkamran80 commented
Perfect, thanks! Glad to help! I'll finish reviewing it in a little while.

2023-02-22 22:32 UTC, Carlgo11 requested changes
It looks like you squished the PNG when resizing it.
Keeping the aspect ratio and simply adding padding makes the content more legible.

I suggest you use this image instead:
![checkmategaming.com.png](https://user-images.githubusercontent.com/3535780/220775037-0e61a9a7-e532-4b49-8ec0-ebe7f0abc873.png)

2023-02-22 23:19 UTC, Carlgo11 approved these changes

2023-02-23 00:33 UTC, hkamran80 approved these changes

2023-02-23 00:33 UTC, merged

2023-02-23 00:36 UTC, coreystone commented
Thank you both for your help and for bearing with me. I'm excited to contribute more in the future 😄

2023-02-23 00:37 UTC, hkamran80 commented
Of course! Thanks for contributing!