Add omg.lol
2factorauth/twofactorauth pull request #7434
Opened 2023-02-23 02:00 UTC by coreystone

Home page: [omg.lol](https://home.omg.lol/)
Similarweb.com ranking: [#157,093](https://www.similarweb.com/website/omg.lol/#overview)

Credit belongs to @newbold for the .svg file.

2023-02-23 03:20 UTC, Carlgo11 requested changes
As @newbold doesn't believe in international law, please exclude the EEA/EU/UK regions using a regions array.

2023-02-23 03:20 UTC, Carlgo11 commented on img/o/omg.lol.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 50 500 400"><g transform="matrix(1.88679 0 0 -1.88679 250 450)"><path d="M0 0c-20.346 0-40.691 7.762-56.215 23.285l-53 53c-31.047 31.047-31.047 81.3
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 50 500 400"><g id="a"><path fill="#ff69ad" d="M153.06 50.03a149.56 149.56 0 0 0-109.13 43.9c-58.58 58.58-58.58 153.56 0 212.14l100 100A149.53 149.53 0 0 0 250 450V88.2a149.47 149.47 0 0 0-96.94-38.17Z"/><path fill="#461036" d="M209.1 214.39a9.43 9.43 0 0 0-8.4 14.36c11.18 18.23 30.24 27.35 49.3 27.35v-18.36c-12.75 0-25.5-6.28-33.2-18.85a9.44 9.44 0 0 0-7.7-4.5z"/><path fill="#e34198" d="M179.25 212.01a58.97 58.97 0 1 0-117.93 0 58.97 58.97 0 0 0 117.93 0"/><circle cx="208.73" cy="176.64" r="17.45" fill="#461036"/></g><use href="#a" transform="matrix(-1 0 0 1 500 0)"/></svg>
```

2023-02-23 03:31 UTC, Carlgo11 requested changes

2023-02-23 03:31 UTC, Carlgo11 commented on entries/o/omg.lol.json
> +    ]
```suggestion
    ],
    "regions": [
    "-at",
    "-be",
    "-bg",
    "-ch",
    "-cy",
    "-cz",
    "-de",
    "-dk",
    "-ee",
    "-es",
    "-fi",
    "-fr",
    "-gb",
    "-gr",
    "-hr",
    "-hu",
    "-ie",
    "-it",
    "-lt",
    "-lu",
    "-lv",
    "-mt",
    "-nl",
    "-no",
    "-pl",
    "-pt",
    "-ro",
    "-se",
    "-si",
    "-sk"
  ]
```

2023-02-23 06:05 UTC, newbold commented
> As @newbold doesn't believe in international law, please exclude the EEA/EU/UK regions using a regions array.

I’d be happy to dig into this if you’re willing to clarify what the specific issue is. Thanks!

2023-02-23 06:10 UTC, Carlgo11 commented
@newbold  I read the legal page and the part about GDPR was just plain wrong. As long as EU/EEA/UK residents are allowed to use the site, GDPR applies.
You need to rewrite that part and specify a DPA.

2023-02-23 06:16 UTC, Carlgo11 approved these changes

2023-02-23 06:16 UTC, merged

2023-02-23 06:26 UTC, newbold commented
> @newbold I read the legal page and the part about GDPR was just plain wrong. As long as EU/EEA/UK residents are allowed to use the site, GDPR applies. It doesn’t matter if the party is a business, nonprofit or person. Origin of the site also doesn’t matter.
> You need to rewrite that part and specify a DPA.

Thanks for the info! That content was written by an attorney, so I’ll get back with them to have it corrected. I’ll also work on providing a DPA. Thanks again!

2023-02-24 00:57 UTC, Carlgo11 commented
That's great news. Feel free to post an update when your new privacy policy is posted and I'll remove the exclusion.

Small correction: __DPA__ was a typo and should really be __DPO__ as in _Data Protection Officer_ which is a point of contact for consumers and authorities. Although a DPA might also be useful in your case as you're sending/storing data in a ["third country"](https://en.wikipedia.org/wiki/General_Data_Protection_Regulation#Third_countries).