Added Shockbyte
2factorauth/twofactorauth pull request #7446
Opened 2023-03-02 22:44 UTC by TnrR

- Domain: https://shockbyte.com
- Methods: TOTP Only
- Notes: The control panel and client area use separate accounts. So, 2FA will need to be enabled separately for each site
- Image: https://shockbyte.com/branding/logomarks/shockbyte_logomark.svg
- Docs: https://shockbyte.com/billing/knowledgebase/23/How-to-Enable-2-Factor-Authentication-in-Your-Shockbyte-Account.html
- Categories: Hosting, Gaming

2023-03-03 01:14 UTC, hkamran80 requested changes
Please reformat the JSON using normal quotes, not smart quotes. Additionally, please separate the control panel and client entries if they use separate authentication systems.

2023-03-03 01:14 UTC, hkamran80 commented on entries/s/shockbyte.com.json
> +    "img": "https://shockbyte.com/branding/logomarks/shockbyte_logomark.svg”,
Please download the SVG and place it in the `img` directory

2023-03-08 22:30 UTC, Carlgo11 requested changes

2023-03-08 22:30 UTC, Carlgo11 commented on entries/s/shockbyte.com.json
> +    "documentation": "https://shockbyte.com/billing/knowledgebase/23/How-to-Enable-2-Factor-Authentication-in-Your-Shockbyte-Account.html",
```suggestion
    "documentation": "https://shockbyte.com/billing/knowledgebase/23",
```

2023-03-08 22:30 UTC, Carlgo11 commented on entries/s/shockbyte.com.json
> +    "domain": “https://shockbyte.com”,
```suggestion
    "domain": "shockbyte.com",
```

2023-03-08 22:30 UTC, Carlgo11 commented on entries/s/shockbyte.com.json
> +      “Gaming”
```suggestion
      "hosting"
```

2023-03-08 22:31 UTC, Carlgo11 commented
As the requested changes haven't been resolved yet I'm going to label this PR as inactive.
> **Warning**
> Unless there's activity within the next 7 days I'll close the PR.

2023-03-15 00:02 UTC, Carlgo11 commented
Closing due to inactivity.
> **Note**
> The PR author you can still commit the requested changes and re-open this PR.
> If someone else wants to commit the requested changes you can create a new PR and link to this PR.

2023-03-15 00:02 UTC, closed without merging