Add Theta.tv
2factorauth/twofactorauth pull request #7480
Opened 2023-03-17 12:23 UTC by DevBaddy

Unfortunately, I couldn't find an SVG for this website.

2023-03-17 17:40 UTC, hkamran80 requested changes
All PNGs should be a max of 128x128 and run through an optimizing utility like [TinyPNG](https://tinypng.com). Please read [the guidelines](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#guidelines) for more information.

2023-03-17 17:40 UTC, hkamran80 commented on entries/t/theta.tv.json
> +    "domain": "theta.tv",
```suggestion
    "domain": "theta.tv",
    "img": "theta.tv.png",
```

The `img` key is required if the image is not an SVG

2023-03-17 21:56 UTC, DevBaddy commented
Updated the image.

2023-03-17 22:49 UTC, Carlgo11 requested changes
There's a lot of padding around that image which will make it look smaller than all the other sites listed on 2FA Directory. Try and get it to 128x128 without the padding.

2023-03-17 23:18 UTC, DevBaddy commented
Is the new image good?

2023-03-18 20:48 UTC, Carlgo11 approved these changes

2023-03-19 00:01 UTC, hkamran80 approved these changes

2023-03-19 00:02 UTC, merged