Add Magnet.me
2factorauth/twofactorauth pull request #7483
Opened 2023-03-20 23:52 UTC by rogierslag

<img width="1175" alt="Screenshot 2023-03-21 at 00 52 11" src="https://user-images.githubusercontent.com/2778689/226489877-70f4ac26-6a9a-4439-9c43-ee18241b8052.png">

Refs https://github.com/2factorauth/twofactorauth/pull/6706

2023-03-20 23:58 UTC, hkamran80 requested changes
Can you provide evidence of 2FA?

2023-03-20 23:58 UTC, hkamran80 commented on entries/m/magnet.me.json
> +    "keywords": [
```suggestion
    "categories": [
```

2023-03-20 23:58 UTC, hkamran80 commented on img/m/magnet.me.svg
> +<svg height="37" viewBox="0 0 37 37" width="37" xmlns="http://www.w3.org/2000/svg"><path d="m4 4h29v29h-29z" fill="#fff"/><path d="m34 0h-31c-3 0-3 3-3 3v31c0 2.9 3 3 3 3h31c2.9 0 3-3 3-3v-31c0-3-3-3
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 37 37"><path fill="#fff" d="M4 4h29v29H4z"/><path fill="#ff5c51" fill-rule="evenodd" d="M34 0H3C0 0 0 3 0 3v31c0 2.9 3 3 3 3h31c2.9 0 3-3 3-3V3c0-3-3-3-3-3zM11 29H6v-4h5zm10 0h-5v-4h5zm10 0h-5v-4h5zm0-7h-5v-6s0-2.5-2.4-2.5C21 13.5 21 16 21 16v6h-5v-6s0-2.5-2.5-2.5S11 16 11 16v6H6V9s.1-1 1-1h6.5s3.8 0 5 2.5c1.2-2.5 5-2.5 5-2.5C31 8 31 16 31 16z"/></svg>
```

2023-03-21 07:54 UTC, rogierslag commented
Hopefully this GIF of logging in with 2FA support suffices. If not, please let me know and I'd be happy to provide what's needed

![2023-03-21 08 51 14](https://user-images.githubusercontent.com/2778689/226546036-e99ea89d-80b9-4341-a5b9-72669d58aa17.gif)

2023-03-21 08:21 UTC, hkamran80 commented
Could you sign in to CircleCI again? Sometimes when a PR author has used CircleCI previously, CircleCI tries to use the author's credentials instead of 2factorauth's. If the PR author's authentication token has expired the build can't run and so the auth token needs to be regenerated by signing in to CircleCI.

2023-03-21 09:25 UTC, rogierslag commented
Done! Amended the commit twice to force a re-run of CircleCI

2023-03-21 09:27 UTC, hkamran80 approved these changes

2023-03-21 09:27 UTC, merged