Add Abine DeleteMe
2factorauth/twofactorauth pull request #7485
Opened 2023-03-21 04:55 UTC by coreystone

Similarweb ranking: [#109,514](https://www.similarweb.com/website/joindeleteme.com/#overview)

DeleteMe is a service that acts as an authorized agent for users in filing data deletion requests with popular data brokers and people search sites.

2023-03-21 05:40 UTC, hkamran80 requested changes
Please remove omg.lol from your PR. In addition, here's an SVG you can use. 
![DeleteMe](https://user-images.githubusercontent.com/16967687/226526971-f6b7d31b-67d7-4946-8d4c-af07d7e1ad43.svg)

2023-03-24 22:44 UTC, Carlgo11 commented
As the requested changes haven't been resolved yet I'm going to label this PR as inactive.
> **Warning**
> Unless there's activity within the next 7 days I'll close the PR.

2023-03-30 04:22 UTC, coreystone commented
Sorry I keep adding unrelated commits, I'm dumb and struggling to learn how to remove them from this PR. Could I close and open another?

2023-03-30 04:23 UTC, hkamran80 requested changes
Please remove `omg.lol` and the PNG

2023-03-30 04:23 UTC, hkamran80 commented on entries/j/joindeleteme.com.json
> +    "img": "joindeleteme.com.png",
```suggestion
```

2023-03-30 04:37 UTC, hkamran80 commented
> Sorry I keep adding unrelated commits, I'm dumb and struggling to learn how to remove them from this PR. Could I close and open another?

Sure, go ahead

2023-03-31 19:54 UTC, closed without merging