Add CoSpaces
2factorauth/twofactorauth pull request #7535
Opened 2023-04-21 10:18 UTC by DevBaddy

2023-04-21 11:32 UTC, phallobst requested changes

2023-04-21 11:32 UTC, phallobst commented on img/c/cospaces.io.svg
> +<svg xmlns="http://www.w3.org/2000/svg" xml:space="preserve" id="Layer_1" x="0" y="0" style="enable-background:new 0 0 246.3 74.4" version="1.1" viewBox="0 0 246.3 74.4"><style>.st0{fill:#50256b}</st
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 116.6 84.6"><path fill="#4e28a1" fill-rule="evenodd" d="M2.8 2.8c-.4 0-.8.3-1.1.5l-1 1L.3 6 0 7.6V77c0 .6 0 1.2.2 1.7.1.6.3 1 .6 1.5.2.4.5.8.9 1 .3.3.7.5 1 .5l17.6 2.8a4.6 4.6 0 0 0 2.1-.1 4.6 4.6 0 0 0 1.7-1.1c.5-.5.9-1.1 1.2-1.8.3-.7.4-1.5.4-2.3V5.4c0-.8-.1-1.6-.4-2.3-.3-.7-.7-1.3-1.2-1.8a4.5 4.5 0 0 0-1.7-1 4.6 4.6 0 0 0-2.1-.3L2.8 2.8m105.6 47.4a23 23 0 0 1-2.6 6.2 15.4 15.4 0 0 1-4 4.4 10 10 0 0 1-5.1 2 9.3 9.3 0 0 1-.7 0 9 9 0 0 1-4.7-1.3 14 14 0 0 1-4.5-4.1c-1.3-1.9-2.4-4-3.1-6.5a28.5 28.5 0 0 1 3-22.8 15 15 0 0 1 4.6-4.2 9.5 9.5 0 0 1 10.5.9c1.5 1 2.9 2.6 4 4.4 1.1 1.8 2 4 2.6 6.2a28.9 28.9 0 0 1 1 7.4 28.8 28.8 0 0 1-1 7.4M74.3 35.4a4.2 4.2 0 0 1-.5 1.2 3 3 0 0 1-.9 1 2.2 2.2 0 0 1-.3.2 2.2 2.2 0 0 1-1 .2 2.2 2.2 0 0 1-.8-.2 2.7 2.7 0 0 1-.7-.4 3.2 3.2 0 0 1-.6-.6 4.1 4.1 0 0 1-.5-.9 16 16 0 0 0-1.7-3.3 13 13 0 0 0-2.2-2.5 10.5 10.5 0 0 0-2.7-1.7 9 9 0 0 0-3.5-.7c-1.4 0-2.7.3-4 1-1.3.6-2.6 1.6-3.7 3s-2 3-2.6 4.8a18.8 18.8 0 0 0-1 6 17.4 17.4 0 0 0 3.6 11c1.1 1.3 2.4 2.4 3.8 3a8.9 8.9 0 0 0 4.4 1 8.9 8.9 0 0 0 3-.7 10.4 10.4 0 0 0 2.5-1.5 12.8 12.8 0 0 0 2.3-2.4l1.7-3.1.4-.9.6-.6.7-.4.8-.1a2.2 2.2 0 0 1 1 .3c.2 0 .3 0 .4.2.4.2.6.5.9 1l.4 1.2a5 5 0 0 1-.2 2.8 23.7 23.7 0 0 1-2.6 4.6 19.8 19.8 0 0 1-3.3 3.7 16.3 16.3 0 0 1-4 2.6 14 14 0 0 1-4.6 1.1 13.3 13.3 0 0 1-7-1.3c-2.1-1-4.1-2.6-5.9-4.7a23.6 23.6 0 0 1-4.1-7.4 28.4 28.4 0 0 1 4.1-26c1.8-2.1 3.8-3.7 6-4.7a13 13 0 0 1 5.8-1.3 14.1 14.1 0 0 1 5.8 1.2 16.4 16.4 0 0 1 4.1 2.7 20.2 20.2 0 0 1 3.4 4 24.5 24.5 0 0 1 2.5 4.8 4.9 4.9 0 0 1 .2 2.8m41.9-20.9-.7-1.5a4 4 0 0 0-1-1 2.3 2.3 0 0 0-1-.5L33.4 0a4.4 4.4 0 0 0-2 .2 4.5 4.5 0 0 0-1.7 1.1 5 5 0 0 0-1 1.8c-.3.7-.3 1.5-.3 2.3v73.8c0 .8 0 1.6.3 2.3a5 5 0 0 0 1 1.8 5 5 0 0 0 1.7 1 4.3 4.3 0 0 0 2 .2l80-11.4c.3 0 .7-.2 1-.5l.9-1 .8-1.5c.1-.6.4-1.1.4-1.7V16.2c0-.6-.3-1.2-.4-1.7"/><path fill="#4e28a1" fill-rule="evenodd" d="M104.4 48.7a18.8 18.8 0 0 0-1.7-14 9.9 9.9 0 0 0-2.7-2.9 6.3 6.3 0 0 0-3.6-1.2c-1 0-2 .3-3 .9a9 9 0 0 0-2.8 2.7c-.9 1.2-1.5 2.6-2 4.2a18.6 18.6 0 0 0 2 14.8c.8 1.2 1.8 2 2.8 2.7a6 6 0 0 0 3.4.8c1 0 2.2-.4 3.2-1.1a12 12 0 0 0 2.7-2.8c.7-1.2 1.3-2.6 1.7-4.1"/></svg>
```

2023-04-21 12:59 UTC, DevBaddy commented
Changes made.

2023-04-21 23:18 UTC, Carlgo11 approved these changes

2023-04-22 10:11 UTC, phallobst approved these changes

2023-04-22 10:11 UTC, merged