cohost.org supports 2fa via TOTP now
2factorauth/twofactorauth pull request #7536
Opened 2023-04-21 18:28 UTC by jkap

SOURCE: I merged it this morning.

2023-04-21 23:14 UTC, Carlgo11 requested changes
I see that you haven't add any documentation link. Could you maybe find one that describes how to enable 2FA on the site?

If no documentation is available or you can't find it, please attach some screenshots of the 2FA setup process and/or login process.
> **Note** Remember to blur or crop out any personal information linked to you.

You can attach the screenshots here in a comment, like this:
![screenshot](https://user-images.githubusercontent.com/3535780/187552643-08eea7e8-e6c6-4873-b31c-0faf4347f69f.gif)

2023-04-21 23:14 UTC, Carlgo11 commented on entries/c/cohost.org.json
> +    "categories": ["social"]
Please include one array value per line as this is the code style used for all the other files in the repo.

2023-04-24 22:36 UTC, hkamran80 commented
![cohost - 2FA](https://user-images.githubusercontent.com/16967687/234131098-9f619e54-7470-42cf-a2f8-bc482f4b0638.png)

2023-04-25 18:24 UTC, Carlgo11 commented
As the requested changes haven't been resolved yet I'm going to label this PR as inactive.
> **Warning**
> Unless there's activity within the next 7 days I'll close the PR.

2023-05-06 16:30 UTC, Carlgo11 commented
/
Closing due to inactivity.
> **Note**
> The PR author you can still commit the requested changes and re-open this PR.
> If someone else wants to commit the requested changes you can create a new PR and link to this PR.

2023-05-06 16:30 UTC, closed without merging