Add myRMV
2factorauth/twofactorauth pull request #7543
Opened 2023-04-23 17:06 UTC by lazytownfan

Add myRMV for the RMV of the state of Massachusetts

## Note on image

[This](https://atlas-myrmv.massdot.state.ma.us/myrmv/Image/ENG/MR.RMV_logo_small_white.png) was the best PNG I could find from the myRMV site (after making the image square, resizing it down to 128x128 in GIMP, and running it through the TinyPNG site).

However, I prefer this [one](https://i2.wp.com/www.mass.gov/files/2017-08/rmv%20logo.png), as the logo colors have white text on darker backgrounds and has much better background contrast, but "Registry of Motor Vehicles" is spelled out on the bottom.

(I also haven't figured out how to convert PNG images into SVG yet.)

2023-04-23 17:15 UTC, hkamran80 commented
If you want to use the second image, you could crop it to be just "RMV" then resize it.

2023-04-23 18:03 UTC, lazytownfan commented
I reuploaded the image and [this](https://imgur.com/a/QTu5c9l) is the largest PNG I have (before shrinking the image) of the RMV logo without the words.

2023-04-23 19:01 UTC, Carlgo11 requested changes
I think the letters need to be white.
![myRMV logo](https://user-images.githubusercontent.com/3535780/233859623-4d915faa-ed9a-47ea-b293-d2f8608e1d74.png)

2023-05-01 01:04 UTC, Carlgo11 approved these changes

2023-05-01 01:04 UTC, merged