New weltsparen.de logo
2factorauth/twofactorauth pull request #7562
Opened 2023-05-01 18:21 UTC by BaumiCoder

1. I got svg from website with logo and writing. Link to the file: https://cdn.weltsparen.de/app/themes/sg-core-theme/assets/lib/img/Logo_Raisin.svg
2. I cuted the logo out with Inkscape.
3. I optimized it with SVGOMG (default settings).

issue: #7561

Here at github the new logo looks smaller. I hope that isn't a problem. (As far as I know svg files have not a real size in pixel, aren't?)

2023-05-01 18:40 UTC, hkamran80 requested changes

2023-05-01 18:40 UTC, hkamran80 commented on img/w/weltsparen.de.svg
> +<svg xmlns="http://www.w3.org/2000/svg" xml:space="preserve" id="Ebene_1" width="22.67" height="21.03" x="0" y="0" version="1.1"><defs id="defs48"><clipPath id="clipPath154" clipPathUnits="userSpaceO
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 22.67 21.03"><defs><clipPath id="a" clipPathUnits="userSpaceOnUse"><ellipse cx="9.88" cy="10.57" fill="red" fill-rule="evenodd" rx="12.9" ry="12.84"/></clipPath></defs><g clip-path="url(#a)" transform="translate(-.1 -.2)"><path d="M40.88 13.74a3.86 3.86 0 0 0 3.92 3.99 3.86 3.86 0 0 0 3.93-4 3.83 3.83 0 0 0-3.93-3.95 3.83 3.83 0 0 0-3.92 3.96m7.45-7.01h4v14.05h-4v-1.82A5.09 5.09 0 0 1 44 21.23c-4.35 0-7.23-3.37-7.23-7.5 0-4.14 2.84-7.45 7.03-7.45 1.08 0 3.2.2 4.54 2.27V6.73ZM57.52.2a2.4 2.4 0 0 1 2.39 2.37 2.4 2.4 0 0 1-4.77 0c0-1.3 1.07-2.37 2.38-2.37m-1.99 6.53h3.99v14.05h-3.99zm14.6 3.34a3.33 3.33 0 0 0-2.32-.94c-.95 0-1.53.45-1.53 1.14 0 .35.16.9 1.27 1.26l.95.3c1.11.35 2.78.9 3.6 2a4.63 4.63 0 0 1-.86 5.91 5.97 5.97 0 0 1-4.24 1.5 7.2 7.2 0 0 1-5.5-2.34l2.1-2.4a4.4 4.4 0 0 0 3.13 1.62c1.11 0 1.96-.55 1.96-1.53 0-.87-.71-1.23-1.24-1.42l-.91-.33a7.66 7.66 0 0 1-3.04-1.69 3.75 3.75 0 0 1-1.08-2.69c0-1.36.65-2.5 1.47-3.18 1.11-.87 2.55-1 3.7-1a7.1 7.1 0 0 1 4.5 1.49zM76.94.2a2.4 2.4 0 0 1 2.4 2.37 2.4 2.4 0 0 1-4.78 0c0-1.3 1.08-2.37 2.38-2.37m-1.99 6.53h3.99v14.05h-3.99zm7.15 0h4v1.82a5.2 5.2 0 0 1 4.38-2.27c1.24 0 3.07.35 4.18 1.72.98 1.2 1.11 2.6 1.11 3.95v8.83h-3.99v-7.66c0-.78-.03-2-.75-2.75a2.56 2.56 0 0 0-1.86-.72c-1.05 0-1.86.36-2.45 1.23a4.8 4.8 0 0 0-.62 2.73v7.17h-4V6.73Zm-50.99 7.3v6.75h-3.99V6.73h3.99zm2.72-7.76a2.4 2.4 0 0 1 2.4 2.37 2.4 2.4 0 0 1-4.78 0 2.4 2.4 0 0 1 2.38-2.37" class="st0"/><linearGradient id="b" x1="3.32" x2="18.06" y1="18.02" y2="3.28" gradientUnits="userSpaceOnUse"><stop offset="0" stop-color="#156cc4"/><stop offset=".16" stop-color="#1368bb"/><stop offset=".41" stop-color="#0f5ca3"/><stop offset=".73" stop-color="#07487b"/><stop offset="1" stop-color="#003554"/></linearGradient><path fill="url(#b)" d="M10.62.2a10.52 10.52 0 0 0-8.7 16.4l5.88-5.88H2.9v-4h11.73v11.71h-4v-4.9L8.17 16l-3.44 3.44A10.52 10.52 0 1 0 10.63.2z"/></g></svg>
```

2023-05-02 17:14 UTC, hkamran80 approved these changes

2023-05-02 17:14 UTC, merged

2023-05-02 17:14 UTC, hkamran80 commented
Thank you! Your contribution will be visible in around 10 minutes, although it may take longer due to server and browser caches.

2023-05-02 17:19 UTC, BaumiCoder commented
@hkamran80 Thank you for your help. I saw, that your suggestion removes the size in pixel of the svg image. 
Only out of own interest: How did you do that? Which tool to you use to make this changes?

2023-05-02 17:22 UTC, hkamran80 commented
@BaumiCoder You're welcome! I ran the logo through [SVGOMG](https://jakearchibald.github.io/svgomg/), with all the settings active, except for "Remove xmlns". Then I lowered the two precision sliders until they were as low as possible without sacrificing too much quality.