Add octopus energy
2factorauth/twofactorauth pull request #7595
Opened 2023-05-17 13:19 UTC by kieronlanning

2023-05-17 13:25 UTC, kieronlanning commented
I'm not sure why this is failing with the following error:

```
Error:  'Format' error in entries/o/octopus.energy.json
- tag: url
  data: octopus.energy
  expected: uri
```

I did try adding `https://octopus.energy` which fails with a different error.

2023-05-17 13:29 UTC, phallobst requested changes

2023-05-17 13:29 UTC, phallobst commented on entries/o/octopus.energy.json
> +    "url": "octopus.energy",
If the `uri` field is given, it must contain a valid URI (e.g. start with `https://`). However, if the value is `https://`+domain, it should be left out.
```suggestion
```

2023-05-17 13:38 UTC, phallobst commented
Here's an SVG version of the logo, which we prefer.
![octopus energy](https://github.com/2factorauth/twofactorauth/assets/520841/510a9cfe-c4d1-4465-a8bf-8c44500160c3)

2023-05-17 14:15 UTC, kieronlanning commented
@phallobst didn't see you svg comment - sorted now, I did look but couldn't find one initially.

2023-05-17 19:17 UTC, phallobst requested changes

2023-05-17 19:17 UTC, phallobst commented on entries/o/octopus.energy.json
> +    "domain": "octopus.energy",
```suggestion
    "domain": "octopus.energy",
    "additional-domains": [
      "octopusenergy.de",
      "octopusenergy.es",
      "octopusenergy.fr",
      "octopusenergy.it",
      "octopusenergy.co.jp",
      "octopusenergy.nz",
      "octopusenergy.com"
    ],
```

2023-05-17 19:17 UTC, phallobst commented on entries/o/octopus.energy.json
> +    ]
```suggestion
    ],
    "regions": [
      "gb",
      "de",
      "es",
      "fr",
      "it",
      "jp",
      "nz",
      "us"
    ]
```

2023-05-18 09:00 UTC, phallobst approved these changes

2023-05-18 09:00 UTC, merged