Add skiff.com
2factorauth/twofactorauth pull request #7596
Opened 2023-05-17 20:18 UTC by nishils

2023-05-17 20:47 UTC, hkamran80 requested changes

2023-05-17 20:47 UTC, hkamran80 commented on img/s/skiff.com.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="513" height="516" fill="none"><g fill="#000" clip-path="url(#a)"><path d="M332.755 27.405c6.006 0 12.012.429 18.448.858l4.719.429 4.719.858c2.574.429 6.
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 513 516"><path d="M332.8 27.4c6 0 12 .4 18.4.9l4.7.4 4.7.9 9 1.7c2.6.4 5.2 1.3 7.8 2.1a94 94 0 0 1 14.1 5.2c2.6 1.2 6 2.5 8.6 3.8A259.1 259.1 0 0 0 67.6 85c-2.1 2.1-6.8 8.1-9 10.3a234.1 234.1 0 0 0-22.3 32.6l-6 10.7c-1.3 3-4.7 9.5-6 12L20 160.8l-3.9 10.8-4.2 12.8a163 163 0 0 0-3.5 13.3c-.4 1.7-2.1 9.5-2.6 11.2L4.1 220a242 242 0 0 0-2.5 61c.4 4.2 1.2 9.4 1.7 13.3l2.1 12.4 1.7 7.7.9 4.3c.8 3.4 2.1 8.6 3.4 12 .9 2.2 3 9.5 3.9 12 1.3 3 3 7.8 3.8 10.8 1.3 3 4.3 9.4 5.2 12.4l3.9 8.2.8 2 .4 1 .9.8 2.1 3.9c1.3 2.1 3 6 4.3 7.7L44 401l5.2 7.3c2.1 2.5 6 8.1 8.1 10.7 3.5 3.9 8.2 9.9 12 13.7l6.5 6.5 3.4 3L81 444a64 64 0 0 0 6 5.1c2.2 1.7 4.3 3.5 6 4.7.9.5 4.8 3.5 5.6 4 3 1.6 6.4 4.2 9.5 6 3 1.6 6.8 3.3 9.8 5a84 84 0 0 1 6 2.6c5.6 2.2 11.2 4.3 17.2 6 5.6 1.8 12 3 17.6 3.9 5.1.9 10.7 1.3 15.8 1.7h9.5c48-1.7 93-26.6 120.5-67.8.9-1.3 2.6-4.7 3.5-5.5 1.3-2.2 3-5.6 4.3-8.2l3-6c.8-2.6 2.5-6 3.4-8.2l1.7-4.2 1.3-4.3 1.3-4.3c2.1-7.3 3.4-14.6 4.3-22.3a146 146 0 0 0 1.3-19.3c-6 0-12.5-.9-18.5-1.8a147 147 0 0 1-73.8-31.3 152.5 152.5 0 0 1-54.9-148.4 153.3 153.3 0 0 1 151.5-124Zm-222.3 393c-3-2.2-6-5.2-8.6-7.7a244.7 244.7 0 0 1-54.4-82l-3.5-9c-.8-3.8-3-9-3.8-12.4l-2.6-9.5-1.3-6.4c-7.3-33.9-7.3-69.5.4-103.4C64.2 64.3 190-18 315.6 8.5A237.8 237.8 0 0 0 41.5 285.6a238 238 0 0 0 64.3 123.2 66 66 0 0 0 8.2 7.3c52.7 45.9 135.1 44.2 184-6.9-48 54.5-133.4 57.5-187.5 11.2Zm17.6-42.5c-2.1-2.1-5.6-6-7.7-8.6a99.2 99.2 0 0 1-7.3-9C11 227.3 90.4 33.8 256.4 11.5c22.7-2.5 46.3-1.7 69 2.6-30.4-4.7-61.3-3-90.9 5.2A214.7 214.7 0 0 0 122.1 93a214.5 214.5 0 0 0-4.3 263.5c1.7 2.5 5.2 6.4 7.3 9 2.2 2.5 5.2 6.4 7.7 8.6 43.8 50.1 124 56.2 172.5 8.1-47.6 52-130.9 46.3-177.2-4.3Zm47.2-15.9a90.4 90.4 0 0 1-9.9-8.1 193.3 193.3 0 0 1-48.9-74.7C73.6 162.2 150 33.8 274.5 18c20-2.6 40.7-1.7 60.8 2.1-13.3-1.7-27-2.6-40.3-1.7C144 27.8 60.3 196 145.3 321.3l3 4.3 3 3.8c3 3.9 6.4 8.2 9.4 11.6 36.5 43.3 102.1 55.8 148 20.2-37.3 32.6-94.4 30-133.4.8Zm26.6-40.7 3 3c2.6 2.1 5.6 4.7 8.2 6.4 1.2.9 4.2 2.6 5.1 3.5 2.6 1.2 4.7 3 7.3 4.2 1.3.5 4.3 2.6 5.6 3a103.6 103.6 0 0 0 77.6 4 99.9 99.9 0 0 1-29.6 7.2c-1.7 0-5.1.4-6.4.4h-6.4c-17.6-.8-34.8-6-50.2-15l-5.6-3.4-5.6-3.9c-2.1-1.3-4.3-3.4-6-4.7a174.2 174.2 0 0 1 73.8-298.2 171 171 0 0 1 69-2.5 177.2 177.2 0 0 0-100.3 18.4 172.3 172.3 0 0 0-39.5 277.6Z"/><path d="M200.2 184.9c-4.7-.9-9.9-1.3-15-1.8v.5a85 85 0 0 1 15 1.3c.4 0 .4 0 0 0Z"/><path d="M438.3 438.8c2.1-2.5 5.6-6 7.7-8.1 2.2-2.2 6.9-8.2 9-10.3a233.8 233.8 0 0 0 22.3-32.6c.9-1.7 5.2-9 6-10.7 1.3-3 4.8-9.5 6-12l4.3-10.4c.5-.8 3.5-9.4 3.9-10.7l4.3-12.9c1.3-4.2 2.6-9 3.4-13.3l2.6-11.1 1.7-11.2a264 264 0 0 0 1.7-60.9c-.4-4.3-1.3-9.4-1.7-13.3l-2.1-12.4-1.8-7.7-.8-4.3c-.9-3.5-2.2-8.6-3.4-12-.9-2.2-3-9.5-3.9-12-1.3-3-3-7.8-3.9-10.8-1.2-3-4.3-9.4-5.1-12.4l-3.9-8.2-.8-2.1-.5-.9-.4-.8-2.1-3.9c-1.3-2.1-3-6-4.3-7.7l-7.3-11.6-5.2-7.3c-2.1-2.6-6-8.1-8.1-10.7-3.4-3.9-8.2-9.9-12-13.8l-6.5-6.4-3.4-3-1.7-1.7a64 64 0 0 0-6-5.2l-6-4.7c-.9-.4-4.7-3.4-5.6-3.8-3-1.8-6.4-4.3-9.4-6-3-1.8-6.9-3.5-10-5.2a84 84 0 0 1-6-2.6 88.5 88.5 0 0 0-15-5.1c-2-.4-4.2-1.3-6.4-1.7-1.3-.5-5.1-1.3-6.4-1.3-2.1-1.3-4.7-1.7-6.4-2.2-5.2-.8-10.8-1.2-16-1.7h-9.3a150.3 150.3 0 0 0-120.2 67.8c-.8 1.3-2.5 4.7-3.4 5.6-1.3 2.1-3 5.6-4.3 8.1l-3 6c-.9 2.6-2.6 6-3.4 8.2l-1.7 4.3-1.3 4.3c-.5 1.3-.9 3-1.3 4.3-2.2 7.3-3.5 14.6-4.3 22.3-1.3 6.8-1.7 13.3-1.7 19.7 33.4 0 65.6 11.6 92.2 32.2a152.5 152.5 0 0 1 55 148.4 153.2 153.2 0 0 1-151.5 124.9c-6 0-12-.5-18.5-.9l-4.7-.4-4.7-.9-9-1.7c-2.6-.4-5.2-1.3-7.7-2.1A94 94 0 0 1 122 477c-2.6-1.3-6-2.6-8.6-3.8 0 0-.4-.5-.8-.5a259 259 0 0 0 325.6-33.9Zm-166.5 33a172.2 172.2 0 0 0 40.4-277.5l-3-3a91.5 91.5 0 0 0-8.2-6.4c-1.3-.9-4.3-2.6-5.1-3.5-2.6-1.3-4.8-3-7.3-4.3-1.3-.4-4.3-2.1-5.6-3a103.6 103.6 0 0 0-77.7-3.8A99.9 99.9 0 0 1 235 163c1.8 0 5.2-.5 6.5-.5h6.4c17.6.9 34.8 6 50.2 15 1.3 1 4.3 2.6 5.6 3.5l5.6 3.9c2.1 1.2 4.2 3.4 6 4.7a174.2 174.2 0 0 1-73.8 298.1 170.6 170.6 0 0 1-69.1 2.6c33.5 3.9 68.6-2.6 99.5-18.4Zm-52.7 25.4c150.6-9.5 234.2-177.6 149.3-303l-3-4.2-3-3.9a274 274 0 0 0-9.5-11.5c-36.4-43.4-102-55.8-148-20.2 37.3-32.6 94.4-30 133.4-.9a88 88 0 0 1 9.9 8.2 195.9 195.9 0 0 1-109 336 193.7 193.7 0 0 1-60.9-2.2c13.7 2.1 27.5 2.5 40.8 1.7Zm60.5-.9a215 215 0 0 0 116.3-337.2c-1.8-2.6-5.2-6.4-7.4-9-2.1-2.6-5.1-6.4-7.7-8.6-43.8-50.2-124-56.2-172.5-8.1 47.2-52 130.9-46.4 176.8 4.3 2.1 2.1 5.6 6 7.7 8.5 2.2 2.6 5.6 6.5 7.3 9 102.1 132.6 22.7 326.5-143.3 348.4a205 205 0 0 1-69-2.6 212 212 0 0 0 91.8-4.7ZM198 507c16.8 2.6 34 4 51.1 3a237.2 237.2 0 0 0 158.7-403.2 56.3 56.3 0 0 0-8.1-7.3c-52.8-46-135.2-44.2-184 6.8C263.6 52 349 49 403 95.2c3 2.1 6 5.1 8.6 7.7 23.6 23.2 42 51.5 54.5 82l3.4 9c1.3 3.4 3 9 3.9 12.4l2.5 9.4 1.3 6.5c7.3 33.9 7.3 69.5-.4 103.4C449.4 451.3 323.7 533.6 198 507Z"/></svg>
```

2023-05-17 21:15 UTC, hkamran80 commented on entries/s/skiff.com.json
> +      ],
Why do you have these domains as additional domains?

2023-05-17 22:29 UTC, nishils commented on entries/s/skiff.com.json
> +      ],
When a user with a crypto wallet links it to their skiff account, they gain access to a few additional domains that Skiff owns. An ethereum user gets access to ethereum.email for example.

Skiff owns these domains outright and can be confirmed via Whois records.

We can also remove if needed if this wasn't the intended use case of additional domains.

2023-05-17 22:59 UTC, hkamran80 commented on entries/s/skiff.com.json
> +      ],
Ah, gotcha. That's the intended use case of additional domains: to provide a list of alternate domains that are used by the service.

2023-05-17 23:01 UTC, hkamran80 commented on entries/s/skiff.com.json
> +      ],
Are you able to access those domains? I get 404s for all but Keplr, which redirects to the Keplr website.

2023-05-21 00:28 UTC, hkamran80 approved these changes

2023-05-21 00:28 UTC, merged

2023-05-21 00:28 UTC, hkamran80 commented
Thank you! Your contribution will be visible in around 10 minutes, although it may take longer due to server and browser caches.