Add Odoo
2factorauth/twofactorauth pull request #7601
Opened 2023-05-21 02:53 UTC by fhe-odoo

2023-05-21 17:22 UTC, Carlgo11 commented on entries/o/odoo.com.json
> +      "email",
I don't see any mention of email 2FA on the documentation page you linked to.

2023-05-21 17:27 UTC, Carlgo11 commented on img/o/odoo.com.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 919 495"><path d="M695 346a75 75 0 1 1 75-75 75 75 0 0 1-75 75Zm0-31a44 44 0 1 0-44-44 44 44 0 0 0 44 44Zm-157 31a75 75 0 1 1 75-75 75 75 0 0 1-75
As the image will be constrained to 32x32 pixels, the icon version containing just the "O" would be preferred here.

2023-05-22 03:10 UTC, fhe-odoo commented
@Carlgo11 Thank you for the review. I have fixed the issues.

2023-05-22 03:38 UTC, Carlgo11 requested changes

2023-05-22 03:38 UTC, Carlgo11 commented on img/o/odoo.com.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="150" height="150"><path fill="#714b67" d="M75 150a75 75 0 1 1 75-75 75 75 0 0 1-75 75zm0-31a44 44 0 1 0-44-44 44 44 0 0 0 44 44z"/></svg>
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="-7.5 -7.5 15 15"><circle r="6" fill="none" stroke="#714b67" stroke-width="3"/></svg>
```

2023-05-22 03:38 UTC, Carlgo11 commented on entries/o/odoo.com.json
> +    "notes": "Email 2FA is available if enabled by administrator.",
If email 2FA is available, I need proof of that. Either as a link to a documentation page or a screenshot of the setup/login process.
If it isn't available, please remove this element.

2023-05-22 18:38 UTC, Carlgo11 approved these changes
Thank you 🙂
Your contribution will be visible in around 10 minutes. Sometimes it takes longer due to server and browser cache.

2023-05-22 18:38 UTC, merged