Add Medal
2factorauth/twofactorauth pull request #7610
Opened 2023-05-26 10:22 UTC by DevBaddy

2023-05-26 22:57 UTC, Carlgo11 requested changes

2023-05-26 22:57 UTC, Carlgo11 commented on entries/m/medal.tv.json
> +      "twitter": "Medal_TV"
```suggestion
      "twitter": "Medal_TV",
      "email": "help@medal.tv"
```

2023-05-27 11:31 UTC, DevBaddy commented
Changes made.

2023-05-27 21:26 UTC, Carlgo11 approved these changes

2023-05-27 21:26 UTC, merged