Update Shadow
2factorauth/twofactorauth pull request #7632
Opened 2023-06-04 12:03 UTC by fletcherdodd

2023-06-04 12:29 UTC, phallobst requested changes

2023-06-04 12:29 UTC, phallobst commented on entries/s/shadow.tech.json
> +      "tfa",
```suggestion
      "totp",
```

2023-06-05 10:25 UTC, fletcherdodd commented on entries/s/shadow.tech.json
> +      "tfa",
Lol I don't know what I was thinking there 😂

2023-06-05 14:52 UTC, phallobst approved these changes

2023-06-05 14:52 UTC, merged