Add CNN
2factorauth/twofactorauth pull request #7656
Opened 2023-06-11 20:52 UTC by DevBaddy

2023-06-17 23:19 UTC, Carlgo11 commented
Which [site criteria](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#site-criteria) would it meet?

2023-06-18 13:01 UTC, DevBaddy commented
It would meet Personal Info, considering you can store your full name there.

2023-06-28 20:00 UTC, DevBaddy commented
Any reason why no comment has been left here by the twofactorauth team in weeks?

2023-07-12 10:35 UTC, DevBaddy commented
@hkamran80 @Carlgo11 Any updates on this PR?

2023-07-15 03:41 UTC, hkamran80 requested changes

2023-07-15 03:41 UTC, hkamran80 commented on img/c/cnn.com.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="800" viewBox="-1350 -1050 11700 6300"><path fill="#c00" d="M2800 1200h-700a900 900 0 0 0 0 1800h783a117 117 0 0 0 117-117V817a817 817 0 0
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 923.08 430.77"><path fill="#c00" d="M287.14 123.14h-71.79a92.3 92.36 0 0 0 0 184.72h80.3a12 12 0 0 0 12-12V83.83a83.79 83.84 0 0 1 156.5-41.56l89.64 156.9V83.84a83.79 83.84 0 0 1 156.5-41.56l89.63 156.9V0h51.28l10.25 10.26L871.71 0h51.28v347.16a83.79 83.84 0 0 1-156.5 41.56l-89.64-156.9v115.34a83.79 83.84 0 0 1-156.5 41.56l-89.63-156.9v115.34A83.79 83.84 0 0 1 346.93 431H215.35a215.37 215.5 0 0 1 0-431h71.8v51.31l-10.26 10.26 10.25 10.26z"/><path fill="none" stroke="#fff" stroke-width="20.52" d="M287.14 61.57h-71.79a153.83 153.93 0 0 0 0 307.86h131.58a22.25 22.27 0 0 0 22.26-22.27V83.84a22.25 22.27 0 0 1 41.53-11.08l163.06 285.48a22.25 22.27 0 0 0 41.54-11.08V83.84a22.25 22.27 0 0 1 41.53-11.08l163.07 285.48a22.25 22.27 0 0 0 41.53-11.08V0"/></svg>
```

2023-07-15 11:33 UTC, DevBaddy commented
Am wondering if there is need for a category concerning News.

2023-07-15 21:54 UTC, hkamran80 commented
At the moment, no, considering we have such few sites that are news sites.

2023-07-16 12:02 UTC, DevBaddy commented
Made the changes.

2023-07-17 01:36 UTC, hkamran80 approved these changes

2023-07-17 01:36 UTC, merged