Add Beeper
2factorauth/twofactorauth pull request #7667
Opened 2023-06-19 11:44 UTC by fletcherdodd

2023-06-19 22:01 UTC, hkamran80 requested changes

2023-06-19 22:01 UTC, hkamran80 commented on img/b/beeper.com.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 68.2 69.24"><defs><linearGradient id="a" x1="31.29" x2="29.65" y1="60.89" y2="16.52" gradientTransform="matrix(1 0 0 -1 0 92)" gradientUnits="user
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 68.2 69.24"><defs><linearGradient id="a" x1="31.29" x2="29.65" y1="60.89" y2="16.52" gradientTransform="matrix(1 0 0 -1 0 92)" gradientUnits="userSpaceOnUse"><stop offset="0" stop-color="#b547e9"/><stop offset="1" stop-color="#4958f5"/></linearGradient><linearGradient id="b" x1="38.14" x2="37.11" y1="96.74" y2="35.76" gradientTransform="matrix(1 0 0 -1 0 92)" gradientUnits="userSpaceOnUse"><stop offset="0" stop-color="#ff9b71"/><stop offset="1" stop-color="#db48f3"/></linearGradient></defs><path fill="url(#a)" d="M48.64 31.09H7.38L.22 61.54c-1.61 6.82 6 10.26 12 5.46l6.9-5.46h22.36c8.55 0 17.08-6.82 19.06-15.23s-3.35-15.22-11.9-15.22Z"/><path fill="url(#b)" d="M26.62 0C20 0 13.46 5.25 11.94 11.73L7.39 31.09h40.93c8.73 0 17.44-7 19.46-15.55S64.36 0 55.63 0Zm-7.23 36.55 6.9-5.46H7.38c-1.6 6.82 5.95 10.26 12.01 5.46Z"/></svg>
```

2023-06-20 22:05 UTC, Carlgo11 approved these changes

2023-06-21 02:23 UTC, hkamran80 approved these changes

2023-06-21 02:23 UTC, merged