Add Lemmy
2factorauth/twofactorauth pull request #7696
Opened 2023-08-01 11:19 UTC by slothtown

2023-08-02 01:35 UTC, Carlgo11 commented
I think this would be one of those [self hosted services](https://github.com/2factorauth/twofactorauth/blob/master/EXCLUSION.md#self-hosted-services) that are excluded.

2023-08-02 06:10 UTC, slothtown commented
I kind of disagree. Lemmy is part of the fediverse and works in a similar way to Mastodon, which isn't considered an excluded site. Both can be self hosted but it's definitely not mandatory, as one can also join a public instance. The reason I mentioned the version that an instance needs to be on is that 2fa is still a new feature in Lemmy and there might be some instances that haven't updated yet.

2023-08-04 22:39 UTC, Carlgo11 requested changes
Thank you for your comment.
I see that you haven't added any documentation link. Could you maybe find one that describes how to enable 2FA on the site?

If no documentation is available or you can't find it, please attach some screenshots of the 2FA setup process and/or login process.
> **Note** Remember to blur or crop out any personal information linked to you.

You can attach the screenshots here in a comment, like this:
![screenshot](https://user-images.githubusercontent.com/3535780/187552643-08eea7e8-e6c6-4873-b31c-0faf4347f69f.gif)

2023-08-04 22:39 UTC, Carlgo11 commented on img/j/join-lemmy.org.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="1024"><g style="display:inline"><path d="M167.04 270.787a132.894 132.894 0 0 0-15.65.867c-33.787 3.892-64.217 21.864-82.872 53.274-18.28 3
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" fill="#fff" stroke="#000" stroke-linecap="round" stroke-linejoin="round" stroke-width="28" viewBox="0 0 1024 1024"><path d="M716.9 336.9a190.3 190.3 0 0 1 56.5-53.3c66.6-38.5 137-33.2 170 22.4 33.1 55.7 15 117.5-47.6 159.9a248 248 0 0 1-97.2 35.5M307 337a190.3 190.3 0 0 0-56.5-53.3c-66.6-38.5-137-33.2-170 22.4-33.1 55.7-15 117.5 47.6 159.9 32 19.2 63 30.9 97.2 35.5Z"/><path d="M801.2 550.8C812.7 401 720.6 295.9 512 299.3 303.4 302.7 213.7 402 222.8 550.8c8.6 142 176.8 246.4 288 246.4 111.4 0 279.5-104.5 290.4-246.4z"/><path fill="#000" d="M610.5 618.2a41.8 41.8 0 1 0 83.6 0 41.8 41.8 0 0 0-83.6 0zm-280.6 0a42.2 42.2 0 1 0 84.4 0 42.2 42.2 0 0 0-84.4 0z"/><path stroke-width="32" d="m339.7 743.2-54.5 72.2m399-72.2 54.6 72.2M263.7 671.8l-87.8 35.8m579.9-35.8 87.7 35.8"/><path d="M512 687c-45.9 0-75.1 31.9-74.1 71.1 1 42.5 32.4 71.1 74.1 71.1a73 73 0 0 0 74.1-71c.1-39.3-28.2-71.2-74.1-71.2z"/></svg>
```

2023-08-05 17:57 UTC, slothtown commented
I couldn't find a documentation so here are some screenshots. 
![Screenshot from 2023-08-05 20-53-43](https://github.com/2factorauth/twofactorauth/assets/102730723/bf5c3573-66dc-4a20-97f6-095eb113d25a)
![Screenshot from 2023-08-05 20-55-36](https://github.com/2factorauth/twofactorauth/assets/102730723/d1bac952-cfbd-4260-830b-3300f8a6820b)
![Screenshot from 2023-08-05 20-55-49](https://github.com/2factorauth/twofactorauth/assets/102730723/dd4a8f7f-ba27-4d3e-88d9-146ba120ed98)

2023-08-05 18:00 UTC, slothtown commented
One thing that is perhaps important to mention is that atm Lemmy doesn't ask you to confirm succesfully enabling 2fa with a one-time code, so it's possible to enable 2fa, not save the secret and then log out locking yourself out.

2023-08-06 20:40 UTC, Carlgo11 approved these changes

2023-08-06 20:40 UTC, merged