Add Rest Super
2factorauth/twofactorauth pull request #7703
Opened 2023-08-05 00:12 UTC by Cautious-Software701

2023-08-05 01:51 UTC, Carlgo11 requested changes
I see that you haven't add any documentation link. Could you maybe find one that describes how to enable 2FA on the site?

If no documentation is available or you can't find it, please attach some screenshots of the 2FA setup process and/or login process.
> **Note** Remember to blur or crop out any personal information linked to you.

You can attach the screenshots here in a comment, like this:
![screenshot](https://user-images.githubusercontent.com/3535780/187552643-08eea7e8-e6c6-4873-b31c-0faf4347f69f.gif)

2023-08-05 01:51 UTC, Carlgo11 commented on img/r/rest.com.au.svg
> +<svg id="Layer_1" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 570.87 231.85"><defs><style>.cls-1{fill:#3fa946;}.cls-2{fill:#00a5ac;}.cls-3{fill:#0063af;}.cls-4{fill:#009fd9;}.
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 570.9 231.8"><path fill="#3fa946" d="M567.3 195.4a16.5 16.5 0 0 0-23.1-2.8 28.8 28.8 0 0 1-18 6.3 29.2 29.2 0 0 1-29.2-29.2v-63.5h36.5a16.5 16.5 0 0 0 0-33H497V61.3a61.2 61.2 0 1 0-121.3 11.9l47.1 13.4c-3.7-2.4-15.7-11.2-15.3-25.3a28.6 28.6 0 0 1 28.3-28.2A28.3 28.3 0 0 1 464 61.3v108.4a62.2 62.2 0 0 0 100.6 48.9 16.5 16.5 0 0 0 2.7-23.2Z"/><path fill="#00a5ac" d="M427 152c-10.5-10.6-26-16.3-45.8-16.8-13.5-.3-23.6-3.6-27.7-9a9.3 9.3 0 0 1-1.8-9c2-6.7 13.7-11.3 25-11 12.1.4 28.5 8.4 29.8 9-1-1.8-24.2-33.8-30.8-42-27.6.4-50.5 15-56 35.8a43.2 43.2 0 0 0 7.4 37c7.4 9.7 22.6 21.5 53.3 22.2 17 .4 26.6 6 26.6 15.5 0 12.8-15.4 15-24.7 15.2a79 79 0 0 1-62.3-31s-10.7 27.4-14 33.6a112.8 112.8 0 0 0 75.2 30.4c19.6 0 34.3-5.4 44.6-15A45.5 45.5 0 0 0 427 152Z"/><path fill="#0063af" d="M172.2 196.2c-24.8-4-45-13.4-62.2-26.9a75.7 75.7 0 0 1-25.5-30.2c37.9 0 68.7-31.2 68.7-69.5S122.4 0 84.5 0h-68A16.5 16.5 0 0 0 0 16.5v198.8a16.5 16.5 0 0 0 33 0V33h51.5c19.7 0 35.7 16.4 35.7 36.6s-16 36.5-35.7 36.5H64.2a16.5 16.5 0 0 0-12 5.1 16.3 16.3 0 0 0-4.5 12.1c1.6 29 16.8 52.3 42 72a169.9 169.9 0 0 0 89.9 35.1c10.4 1 20.2 1.5 29.2 1.5 22.6 0 41-3 55.9-7.7-7.4-2-83.4-25-92.5-28Z"/><path fill="#009fd9" d="M253 193.1a53.1 53.1 0 0 1-45-7.3 44.6 44.6 0 0 1-16.1-22.7c16.9 4.3 40.8 7.5 65 1.3 27.9-7 38-29.1 35.6-47.9A47 47 0 0 0 275 85.8a60.1 60.1 0 0 0-38.3-12.6 80 80 0 0 0-79.4 79.3c-.3 15.6 5.4 31 14.9 43.7 3.1 1 24.1 4 38.1 4 13 0 30-3 42.8-7Zm-16.4-87c14.7 0 22.3 7.5 23.2 14.5 1 7.6-6.6 10.7-11.1 11.8-19.4 5-39.6 1.3-52.6-2.4a46.4 46.4 0 0 1 40.5-23.8Z"/><path fill="#214491" d="M314.5 162a16.4 16.4 0 0 0-9.5-2.5c-5.2.3-9.6 2.7-13.2 7.8A65.5 65.5 0 0 1 253 193c-36.5 10.2-77.5 3.7-81 3.1a78.5 78.5 0 0 0 16.2 16 81 81 0 0 0 49 16 101 101 0 0 0 27.3-4c.8-.2 35.9-8.4 55.1-39.5a16.6 16.6 0 0 0-5.2-22.7Z"/><path fill="#00837a" d="M422.8 86.5a101 101 0 0 0-47.1-13.3c5.8 30 30.8 42 30.8 42 9.3 4.3 17.8 2.4 22.7-5.3s3-18-6.4-23.4Z"/></svg>
```

2023-08-05 02:47 UTC, Cautious-Software701 commented
Sorry about that, here is a screenshot of the MFA setup page. Doesn't look like there is any documentation for consumers/customers.

![image](https://github.com/2factorauth/twofactorauth/assets/85932242/22a0531c-7dd5-4624-974e-96cda0313bc7)

2023-08-06 20:39 UTC, Carlgo11 approved these changes

2023-08-06 20:39 UTC, merged