updated twitter logo
2factorauth/twofactorauth pull request #7705
Opened 2023-08-06 22:30 UTC by spellbind0127

2023-08-06 22:33 UTC, hkamran80 requested changes

2023-08-06 22:33 UTC, hkamran80 commented on img/t/twitter.com.svg
> +</svg>
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 1227"><path d="M714 519 1161 0h-106L667 451 357 0H0l468 682L0 1226h106l409-476 328 476h357L714 519ZM569 688l-47-68L144 80h163l304 436 48 68 396 566H892L569 688Z"/></svg>
```

2023-08-06 22:34 UTC, hkamran80 approved these changes

2023-08-06 22:34 UTC, merged

2023-08-06 22:35 UTC, hkamran80 commented
I like the name "Twitter" and the blue logo way better.

Thank you! Your contribution will be visible in around 10 minutes, although it may take longer due to server and browser caches.

2023-08-16 18:20 UTC, spellbind0127 commented
@hkamran80 for some reason it seems like the twitter logo isn't being updated on https://2fa.directory is this an issue or is it just me

2023-08-16 19:06 UTC, Carlgo11 commented
@spellbind0127 images are heavily cached so that the website loads faster for everyone. Clearing your browser cache will most likely update the logo.

2023-08-16 19:34 UTC, spellbind0127 commented
Yah seems like the page only updates when I complain it’s updated now.