anonaddy has moved to addy.io so I updated the domain and svg
2factorauth/twofactorauth pull request #7710
Opened 2023-08-11 17:06 UTC by spellbind0127

2023-08-11 17:08 UTC, spellbind0127 commented
I will need help making the .svg the right size.

2023-08-11 19:39 UTC, Carlgo11 requested changes

2023-08-11 19:39 UTC, Carlgo11 commented on img/a/addy.io.svg
> +</svg>
[SVGOMG](https://jakearchibald.github.io/svgomg/) is a good tool for minifying SVGs.
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 83.8 112"><defs><linearGradient id="a" x1="42.7" x2="130.7" y1="135.8" y2="47.8" gradientTransform="matrix(1 0 0 -1 0 206)" gradientUnits="userSpaceOnUse"><stop offset="0" stop-color="#3ae7e1"/><stop offset=".9" stop-color="#1993d2"/></linearGradient><linearGradient id="c" x1="42.7" x2="130.7" y1="135.7" y2="47.7" gradientTransform="matrix(1 0 0 -1 0 206)" gradientUnits="userSpaceOnUse"><stop offset="0" stop-color="#3ae7e1"/><stop offset=".9" stop-color="#1993d2"/></linearGradient><linearGradient id="b" x1="67.8" x2="155.7" y1="160.8" y2="72.8" gradientTransform="matrix(1 0 0 -1 0 206)" gradientUnits="userSpaceOnUse"><stop offset="0" stop-color="#3ae7e1"/><stop offset=".9" stop-color="#1993d2"/></linearGradient></defs><path fill="#2d7aae" d="M69.9 63c0 5.2-2.8 9.7-7 12.1V84a7 7 0 0 1-7 7 28 28 0 0 0 13.5-3.5c.3-1.1.5-2.3.5-3.5z"/><path fill="url(#a)" d="M102.9 95.5H75a7 7 0 0 0-7 7v28a7 7 0 0 0 7 7h28a7 7 0 0 0 7-7v-28c-.1-3.9-3.2-7-7.1-7zm-7 28H82v-14h14z" transform="translate(-47 -46.5)"/><path fill="url(#b)" d="M76.9 67.5c2.4-4.2 6.9-7 12.1-7 5.2 0 9.7 2.8 12.1 7h1.9c4.7 0 9.3 1 13.6 2.8a27.9 27.9 0 0 0-55.2 0c4.3-1.8 8.9-2.8 13.6-2.8Z" transform="translate(-47 -46.5)"/><path fill="#2d7aae" d="M14 31.8c4.1-2.4 8.9-3.8 14-3.8 0-2.5.7-4.9 1.9-7H28c-4.7 0-9.3 1-13.6 2.8l-.3 4.2v3.8zM54 21c1.2 2.1 1.9 4.4 1.9 7 5.1 0 9.9 1.4 14 3.8V28l-.3-4.2A35.2 35.2 0 0 0 56 21z"/><path fill="url(#c)" d="M116.9 130.5c0 1.2-.2 2.4-.5 3.5a28 28 0 0 0 14.4-24.5v-7a27.9 27.9 0 0 0-28-28H75c-5.1 0-9.9 1.4-14 3.8a27.7 27.7 0 0 0-14 24.2v28a28 28 0 0 0 28 28h28a14 14 0 0 0-14-14H75a14 14 0 0 1-14-14v-28a14 14 0 0 1 14-14h28a14 14 0 0 1 14 14v7z" transform="translate(-47 -46.5)"/></svg>
```

2023-08-11 19:46 UTC, Carlgo11 commented
It looks like neither addy.io nor anonaddy.com has a Similarweb ranking good enough to be listed on 2FA Directory. Since the domain `addy.io` is new that's understandable but for the last few months `anonaddy.com` have been well above the 200K limit.
Therefore, I recommend simply deleting the anonaddy.com entry in this PR. If `addy.io` becomes popular enough you can later on add another PR to include that domain.

2023-08-18 00:58 UTC, Carlgo11 commented
>Therefore, I recommend simply deleting the anonaddy.com entry in this PR. If addy.io becomes popular enough you can later on add another PR to include that domain.

2023-08-18 18:28 UTC, spellbind0127 reviewed
updated

2023-08-18 18:31 UTC, Carlgo11 commented
No?
The files are still there.

2023-08-18 23:03 UTC, Carlgo11 approved these changes

2023-08-18 23:03 UTC, merged