Add oikotie.fi and tori.fi to Schibsted. Remove Tori as a separate entry.
2factorauth/twofactorauth pull request #7735
Opened 2023-09-03 10:38 UTC by momentti

Both sites use Schibsted account to log in.

2023-09-03 13:05 UTC, phallobst commented
Since `Schibsted` has no documentation link, but `Tori` has (or had), I wonder if we should include that url here. It describes the common login backend, after all.

2023-09-03 16:38 UTC, momentti commented
I added FAQ page as documentation. It used to be behind login, but not anymore.

2023-09-03 21:29 UTC, Carlgo11 requested changes

2023-09-03 21:29 UTC, Carlgo11 commented on entries/s/schibsted.com.json
> +    "documentation": "https://login.schibsted.com/profile-pages/faq",
The entire page is rather long and it is primarily this part that's of interest.
```suggestion
    "documentation": "https://login.schibsted.com/profile-pages/faq#how-to-activate-and-deactivate-2fa",
```

2023-09-04 13:26 UTC, Carlgo11 approved these changes
Thank you! 🙂
Your contribution will be visible in around 10 minutes. Sometimes it takes longer due to server and browser cache.

2023-09-04 13:26 UTC, merged