add university website hva.nl
2factorauth/twofactorauth pull request #7741
Opened 2023-09-04 11:06 UTC by qtpies

2023-09-04 13:21 UTC, Carlgo11 requested changes

2023-09-04 13:21 UTC, Carlgo11 commented on entries/h/hva.nl.json
> +  "Site Name": {
You need to actually specify the name of the site

2023-09-04 13:21 UTC, Carlgo11 commented on img/h/hva.nl.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="64" height="64"><path d="M19 4.602c-3 .796-7.602 2.5-10.2 3.699L4 10.5 7.398 16c1.801 3 3.704 5.398 4.204 5.3.5-.1 3.597-1.198 6.898-2.402C28.898 15.102
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><path d="M19 4.6c-3 .8-7.6 2.5-10.2 3.7L4 10.5 7.4 16c1.8 3 3.7 5.4 4.2 5.3.5-.1 3.6-1.2 6.9-2.4C28.9 15.1 42 16 54 21.4c1.1.5 2.4-.9 4.8-5.3l3.2-5.9-6.2-2.6C52.3 6.2 47.5 4.6 45 4c-6.5-1.4-19.6-1.1-26 .6Z"/><path d="M16.5 21.7c-4.5 1.8-14.9 9.2-14.1 10 .3.3 1.6-.2 2.8-1.1 1.3-.9 3.4-2.4 4.8-3.3 2.3-1.8 2.4-1.7 1.6.2-1.8 4.5-2 5.9-.5 5.2 7.6-3.3 14.1-5.6 17.2-6.2 4.9-.8 4.2.6-1.8 3.6-6.2 3.1-8 5.2-6.6 7.7 1 1.8 1.3 1.9 4.8.6 4.4-1.5 11.3-1.8 11.3-.5 0 .5-2.3 3-5.1 5.5L25.8 48l3.7 6 3.7 6.1 3-3.8c5.6-6.9 10.8-15.6 10.8-18 0-3.1-3.3-4.3-12.1-4.3-9.2 0-8.8-1.7 1.3-5 8.6-2.8 9.9-3.7 7.8-5-3.5-2.3-16-.6-25.2 3.3-5 2.1-4.8.6.2-3 6.2-4.4 5-5.6-2.5-2.6Z"/></svg>
```

2023-09-04 13:21 UTC, Carlgo11 commented on entries/h/hva.nl.json
> +    ]
Since the site is only relevant in the Netherlands, I recommend a regions array.
```suggestion
    ],
    "regions": [
      "nl"
    ]
```

2023-09-05 01:15 UTC, Carlgo11 approved these changes
Thank you! 🙂
Your contribution will be visible in around 10 minutes. Sometimes it takes longer due to server and browser cache.

2023-09-05 01:16 UTC, merged

2023-09-05 07:39 UTC, qtpies commented
Thanks, sorry for all the inaccuracies.