Add Plutus
2factorauth/twofactorauth pull request #7791
Opened 2023-10-03 12:16 UTC by butterdawgs

Support for Plutus.it

2023-10-03 18:18 UTC, phallobst commented
You could use this SVG version of the logo:
![plutus it](https://github.com/2factorauth/twofactorauth/assets/520841/5684c86b-2860-45bf-829c-4145a97d3e15)

2023-10-03 22:32 UTC, Carlgo11 requested changes

2023-10-03 22:32 UTC, Carlgo11 commented on entries/p/plutus.it.json
> +   "Site Name":{
Please replace "Site Name" with the site's name.

2023-10-03 22:32 UTC, Carlgo11 commented on entries/p/plutus.it.json
> +      "documentation":"https://support.plutus.it/hc/en-us/articles/7203346943517-Account-creation-password-reset-2FA-and-account-block-suspension",
```suggestion
      "documentation":"https://support.plutus.it/hc/en-us/articles/7203346943517",
```

2023-10-03 22:32 UTC, Carlgo11 commented on entries/p/plutus.it.json
> +         "finance"
I think these categories are a better fit for the service.
```suggestion
         "cryptocurrencies",
         "banking"
```

2023-10-03 22:32 UTC, Carlgo11 commented on entries/p/plutus.it.json
> +      ]
According to [this article](https://support.plutus.it/hc/en-us/articles/4702798801949), only customers from the following countries are accepted.
```suggestion
      ],
      "regions": [
         "at",
         "be",
         "bg",
         "hr",
         "cz",
         "dk",
         "fi",
         "fr",
         "de",
         "gr",
         "hu",
         "is",
         "ie",
         "it",
         "lv",
         "li",
         "lt",
         "lu",
         "mt",
         "nl",
         "pl",
         "pt",
         "cy",
         "ro",
         "sk",
         "si",
         "es",
         "se"
      ]
```

2023-10-04 11:41 UTC, butterdawgs commented on entries/p/plutus.it.json
> +      ]
You're missing UK and more.

 

United Kingdom

England
Northern Ireland
Scotland
Wales
 

European Economic Area

Austria
Belgium
Bulgaria
Croatia
Czech Republic
Denmark
Finland
France
Germany
Greece
Hungary
Iceland
Ireland
Italy
Latvia
Liechtenstein
Lithuania
Luxembourg
Malta
Netherlands
Poland
Portugal
Republic of Cyprus
Romania
Slovakia
Slovenia
Spain
Sweden

2023-10-04 11:41 UTC, butterdawgs commented on entries/p/plutus.it.json
> +         "finance"
Agreed

2023-10-04 11:49 UTC, butterdawgs commented
I am new to GitHub so I have no clue on how to edit it but I am looking into it.

2023-10-04 12:02 UTC, butterdawgs reviewed
All should be good now :)

Edit: The delete button is greyed out, I cannot delete plutus.it.png

2023-10-04 23:33 UTC, Carlgo11 approved these changes
Thank you! 🙂
I removed the old PNG image and pushed it to your fork.
Your contribution will be visible in around 10 minutes. Sometimes, it takes longer due to server and browser cache.

2023-10-04 23:34 UTC, merged

2023-10-05 10:01 UTC, butterdawgs commented
Appreciate it. 

Also it appears Plutus is listed twice? 

I’m sorry if I messed anything up I’m new to all this

2023-10-05 15:06 UTC, Carlgo11 commented
It's listed in the banking and cryptocurrency categories, so everything is as it should be.