Add put.io
2factorauth/twofactorauth pull request #7796
Opened 2023-10-06 11:34 UTC by ozhanefemeral

2023-10-08 00:45 UTC, hkamran80 requested changes

2023-10-08 00:45 UTC, hkamran80 commented on img/p/put.io.svg
> +<svg width="256" height="256" viewBox="0 0 256 256" fill="none" xmlns="http://www.w3.org/2000/svg"><rect width="256" height="256" rx="20" fill="#323232"/><path fill-rule="evenodd" clip-rule="evenodd"
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 942 228"><defs><clipPath id="a"><path d="M0 567h822V0H0Z"/></clipPath></defs><g clip-path="url(#a)" transform="matrix(1.333 0 0 -1.333 -93 500)"><path fill-rule="evenodd" d="M594 375c-13 0-23-10-23-23 0-12 10-22 23-22s23 10 23 22c0 13-10 23-23 23m-82-25v7c0 9-7 16-17 16h-99c-9 0-16-7-16-16v-7c0-9 7-16 16-16h20c10 0 10-5 10-8v-74c0-9 7-16 16-16h7c9 0 16 7 16 16v74c0 3 0 8 11 8h19c10 0 17 7 17 16m9-69c-13 0-23-10-23-23s10-23 23-23c12 0 22 10 22 23s-10 23-22 23m76 30h-6c-10 0-17-7-17-16v-43c0-9 7-16 16-16h7c9 0 16 7 16 16v43c0 9-7 16-16 16m-252 63h-7c-4 0-8-2-11-5s-5-7-5-12v-52c0-16-12-30-26-30s-26 14-26 30v52c0 9-7 17-16 17h-6c-10 0-18-8-18-17v-53c0-39 28-69 65-69 38 0 67 30 67 69v53c0 9-8 17-17 17m-208-96a28 28 0 1 0 0 56 28 28 0 1 0 0-56m69 27c0 37-31 68-69 68s-68-30-68-69v-85c0-8 7-15 15-15h6c8 0 15 7 15 15v10c0 4 4 7 8 7h26c37 1 67 31 67 69m502-28a28 28 0 1 0 0 56c16 0 29-12 29-28 0-15-13-28-29-28m0 96c-38 0-68-30-68-69 0-38 29-68 67-68s69 31 69 69c0 37-31 68-68 68"/></g></svg>
```

2023-10-08 00:45 UTC, hkamran80 commented on entries/p/put.io.json
> +      "entertainment"
```suggestion
      "backup"
```

2023-10-08 04:21 UTC, hkamran80 approved these changes

2023-10-08 04:21 UTC, merged

2023-10-08 04:21 UTC, hkamran80 commented
Thank you! Your contribution will be visible in around 10 minutes, although it may take longer due to server and browser caches.

2023-10-09 07:13 UTC, altaywtf commented
@hkamran80 that is not the logo we want to use. can you please revert to the one we've sent in the original pull request?