Update concur.com.json
2factorauth/twofactorauth pull request #7818
Opened 2023-10-20 18:54 UTC by xotermic

Updated to include new 2FA for Concur, along with additional domain concursolutions.com.

2023-10-21 07:35 UTC, hkamran80 requested changes

2023-10-21 07:35 UTC, hkamran80 commented on entries/c/concur.com.json
> +      "u2f"
```suggestion
      "totp"
```

> **Will push notifications be supported?**
> At this point in time, push notifications and SMS are not supported. You will need to download an Authenticator app and copy the 6-digit code generated in the app into the Concur sign in screen.
> *— documentation, page six*

2023-10-21 07:35 UTC, hkamran80 commented on entries/c/concur.com.json
> +    "notes": "2FA is only enabled on specific Concur instances by the sysadmin.  2FA must be enabled on instance between 18OCT2023-15NOV2023 initially."
```suggestion
```

I don't think the notes are necessary.

I also don't see where the sysadmin can disable 2FA in the documentation you provided. On page two, it says "No, there is no option to disable the 2FA feature."

2023-10-23 19:22 UTC, xotermic reviewed
Submitting with recommended changes.

2023-10-23 22:48 UTC, hkamran80 approved these changes

2023-10-23 22:49 UTC, merged

2023-10-23 22:49 UTC, hkamran80 commented
Thank you! Your contribution will be visible in around 10 minutes, although it may take longer due to [server and browser caching](https://github.com/2factorauth/twofactorauth/wiki/FAQ-Caching).