Adding eduid.ch
2factorauth/twofactorauth pull request #7841
Opened 2023-11-19 10:09 UTC by tsager

eduid.ch is used for 2FA for universities in Switzerland

2023-11-19 19:23 UTC, Carlgo11 requested changes
Thanks for the pull request @up_the_irons,
I've attached some code suggestions I'd like you to merge.

2023-11-19 19:23 UTC, Carlgo11 commented on img/e/eduid.ch.svg
> +<svg id="Layer_1" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 250 250"><defs><style>.cls-1{fill:#00247d;}.cls-2{fill:#fff;}</style></defs><title>edu-id-logo-round-blue</title>
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 208.8 169.4"><path fill="#273375" d="M61.4 0h80.8c46.8 0 66.6 17 66.6 63v40c0 35.2-10 66.4-61.2 66.4H61.4Zm86.2 141.5c22 0 28.7-19.6 28.7-38.6V63c0-28.2-9.2-35.2-34-35.2H93.8v113.8Zm-115 27.8H0V0h32.5z"/></svg>
```

2023-11-19 19:23 UTC, Carlgo11 commented on entries/e/eduid.ch.json
> +    ]
```suggestion
    ],
    "regions": [
      "ch"
    ]
```

2023-11-20 13:19 UTC, tsager reviewed
Suggested changes look good.

2023-11-20 13:54 UTC, Carlgo11 commented on img/e/eduid.ch.svg
> +<svg id="Layer_1" data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 250 250"><defs><style>.cls-1{fill:#00247d;}.cls-2{fill:#fff;}</style></defs><title>edu-id-logo-round-blue</title>
I think you missed this one 😉

2023-11-20 14:11 UTC, Carlgo11 approved these changes
Thank you! 🙂
Your contribution will be visible in around 10 minutes. Sometimes, it takes longer to show up due to [server and browser caching](https://github.com/2factorauth/twofactorauth/wiki/FAQ-Caching).

2023-11-20 14:11 UTC, merged