Add Postype
2factorauth/twofactorauth pull request #7867
Opened 2023-12-16 20:28 UTC by contextnerror

2023-12-17 05:50 UTC, hkamran80 requested changes

2023-12-17 05:50 UTC, hkamran80 commented on entries/p/postype.com.json
> +    "documentation": "https://help.postype.com/hc/ko/articles/21876052282009-2%EB%8B%A8%EA%B3%84-%EC%9D%B8%EC%A6%9D-%EC%84%A4%EC%A0%95-%ED%95%B4%EC%A0%9C",
```suggestion
    "documentation": "https://help.postype.com/hc/ko/articles/21876052282009",
    "recovery": "https://help.postype.com/hc/ko/articles/21876052282009#01H8NMJNY1KWFB5H5YZ49HBC0J",
```

2023-12-17 05:50 UTC, hkamran80 commented on entries/p/postype.com.json
> +      "social"
```suggestion
      "retail"
```

From what I could glean from their [about page](https://www.postype.com/about), it seems to be more of a marketplace.

2023-12-17 05:50 UTC, hkamran80 commented on img/p/postype.com.svg
> +<svg viewBox="0 0 32 32" xmlns="http://www.w3.org/2000/svg"><path d="M32 0v32H0V0h32ZM18.744 7H7.34v2.689h2.094V25h2.404V9.689h2.093V25h2.403v-4.803l2.41-.004a6.596 6.596 0 0 0 6.596-6.596A6.596 6.59
```suggestion
<svg viewBox="0 0 32 32" xmlns="http://www.w3.org/2000/svg"><path d="M32 0v32H0V0h32ZM18.744 7H7.34v2.689h2.094V25h2.404V9.689h2.093V25h2.403v-4.803l2.41-.004a6.596 6.596 0 0 0 6.596-6.596A6.596 6.596 0 0 0 18.744 7Zm.246 2.7a3.87 3.87 0 1 1 0 7.74h-2.61V9.7Z" /></svg>
```

Thank you for minifying the SVG!

2023-12-17 06:09 UTC, contextnerror commented on entries/p/postype.com.json
> +      "social"
In a sense? It’s more like a patreon thing where you can pay creators to access content. There is a physical store but that’s a recent addition and still beta.

2023-12-18 04:52 UTC, hkamran80 commented on entries/p/postype.com.json
> +      "social"
In that case, let's go with `crowdfunding` and `retail` as the categories.

2023-12-18 09:36 UTC, hkamran80 approved these changes

2023-12-18 09:36 UTC, merged

2023-12-18 09:36 UTC, hkamran80 commented
Thank you! Your contribution will be visible in around 10 minutes, although it may take longer due to [server and browser caching](https://github.com/2factorauth/twofactorauth/wiki/FAQ-Caching).