Added Bank Australia
2factorauth/twofactorauth pull request #7918
Opened 2024-02-10 08:01 UTC by RedRubble

2024-02-10 08:47 UTC, RedRubble commented
It actually looks like that it only asks for authentication when doing transactions in the web app (or maybe logging in from unrecognised locations)
Either way I can't seem to get it to ask when logging in.
What would be the appropriate flags for this type of behaviour?

2024-02-10 08:48 UTC, hkamran80 commented
That sounds more like [authorization than authentication](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#authorization).

2024-02-10 08:50 UTC, RedRubble commented
> That sounds more like [authorization than authentication](https://github.com/2factorauth/twofactorauth/blob/master/CONTRIBUTING.md#authorization).

Alright, apologises. I'll change it so it says unsupported

2024-02-10 08:53 UTC, hkamran80 requested changes

2024-02-10 08:53 UTC, hkamran80 commented on entries/b/bankaust.com.au
> +    "domain": "bankaust.com.au.json",
```suggestion
    "domain": "bankaust.com.au",
```

2024-02-10 08:53 UTC, hkamran80 commented on entries/b/bankaust.com.au
> +    "url": "https://www.bankaust.com.au",
```suggestion
```

The `url` element is not needed because going to `https://[domain]` resolves correctly.

2024-02-10 08:53 UTC, hkamran80 commented on entries/b/bankaust.com.au
> +    "img": "bankaust.com.au.svg",
```suggestion
```

The `img` tag defaults to `[domain].svg`, so this isn't needed.

2024-02-10 08:53 UTC, hkamran80 commented on entries/b/bankaust.com.au
> +      "sms"
```suggestion
      "custom-software"
```

Does Bank Australia support SMS MFA? If so, please attach some screenshots of the 2FA setup process, login process, or management screen. Please blur or crop out any personal or sensitive information.

2024-02-10 08:53 UTC, hkamran80 commented on img/b/bankaust.com.au.svg
> +<svg xmlns="http://www.w3.org/2000/svg" xml:space="preserve" id="Layer_1" x="0" y="0" style="enable-background:new 0 0 63.9 63.9" version="1.1" viewBox="0 0 63.9 63.9"><style>.st2{fill:url(#SVGID_000
```suggestion
<svg viewBox="0 0 25.7 63.9" xmlns="http://www.w3.org/2000/svg"><linearGradient id="a" x1="569" x2="536.6" y1="802.5" y2="825.3" gradientTransform="matrix(0,1,-1,-0.141,822.316,-418.743)" gradientUnits="userSpaceOnUse"><stop offset="0" stop-color="#e9218e"/><stop offset=".5" stop-color="#e6007e"/><stop offset="1" stop-color="#c7017f"/></linearGradient><path fill="url(#a)" d="M25.7 16.1 0 0v36.4l25.6 16.8V16.1Z"/><path fill="#e30613" d="m12.1 44.3 13.5-9.8v18.7Z"/><linearGradient id="b" x1="37.9" x2="26.2" y1="16.3" y2="7.6" gradientTransform="matrix(1,0,0,-1,-19.1,66)" gradientUnits="userSpaceOnUse"><stop offset="0" stop-color="#ef7d00"/><stop offset="1" stop-color="#ea5153"/></linearGradient><path fill="url(#b)" d="M11.7 45.9v18l13-9.5z"/></svg>
```

2024-02-10 09:17 UTC, RedRubble commented
So just to confirm, if it is just authorization, we remove tfa and custom-software and replace with contact pages?

2024-02-10 21:30 UTC, Carlgo11 requested changes
>So just to confirm, if it is just authorization, we remove tfa and custom-software and replace with contact form and socials?

That's correct @RedRubble.

Right now, the test is failing because you forgot to add the file extension `.json` to the JSON file. It should be named `entries/b/bankaust.com.au.json` :wink:

2024-02-11 00:00 UTC, RedRubble commented
That was a clunky first pull request! Thanks for working through it with me

2024-02-11 00:01 UTC, hkamran80 approved these changes
Everything looks good to me!

2024-02-11 00:27 UTC, RedRubble commented
Urg this was meant to be outside of this pull request :/

2024-02-11 00:47 UTC, Carlgo11 approved these changes

2024-02-11 00:47 UTC, merged

2024-02-11 00:47 UTC, Carlgo11 commented
Thank you! 🙂
Your contribution will be visible in around 10 minutes. Sometimes, it takes longer to show up due to [server and browser caching](https://github.com/2factorauth/twofactorauth/wiki/FAQ-Caching).