Update Yammer
2factorauth/twofactorauth pull request #8014
Opened 2024-05-02 11:49 UTC by fletcherdodd

2024-05-02 23:29 UTC, Carlgo11 reviewed
I'm not sure if listing Viva Engage is the best thing. As it's a part of the Microsoft 365 suite it might be better to remove Yammer completely as Microsoft 365 is already listed here.

2024-05-03 00:29 UTC, fletcherdodd commented
> I'm not sure if listing Viva Engage is the best thing. As it's a part of the Microsoft 365 suite it might be better to remove Yammer completely as Microsoft 365 is already listed here.

I definitely agree, I thought about doing this but opted to updated it instead. Will remove it shortly.

2024-05-03 05:21 UTC, hkamran80 commented
Should `yammer.com` be added to the Microsoft 365 entry as an additional domain?

2024-05-04 11:36 UTC, fletcherdodd commented
> Should `yammer.com` be added to the Microsoft 365 entry as an additional domain?

Good thinking! Done.

2024-05-05 21:55 UTC, hkamran80 requested changes

2024-05-05 21:55 UTC, hkamran80 commented on entries/o/office.com.json
> +      "cloud.micrsoft",
```suggestion
      "cloud.microsoft",
```

2024-05-06 01:57 UTC, hkamran80 approved these changes

2024-05-06 02:09 UTC, merged