Update Starbucks
2factorauth/twofactorauth pull request #8032
Opened 2024-05-17 11:54 UTC by fletcherdodd

- Update the doco on the main Starbucks entry
- Add Starbucks Australia as it doesn't support 2FA
- Adjust SVG slightly

2024-05-17 15:47 UTC, Carlgo11 requested changes

2024-05-17 15:47 UTC, Carlgo11 commented on entries/s/starbucks.com.au.json
> +      "jp"
```suggestion
      "au"
```

2024-05-18 01:51 UTC, fletcherdodd commented
Just noticed it doesn't meet the 200k requirements so I might have to remove the AU listing

2024-05-18 05:32 UTC, Carlgo11 commented
I think it is close enough to be added.

2024-05-18 05:32 UTC, Carlgo11 approved these changes

2024-05-18 05:33 UTC, merged