Add realestate.com.au
2factorauth/twofactorauth pull request #8058
Opened 2024-05-31 07:44 UTC by fletcherdodd

2024-06-02 06:18 UTC, hkamran80 requested changes
Do you know if their other sites (REA Group, realcommercial.com.au, PropTrack, etc.) use the same authentication backend?

2024-06-02 06:18 UTC, hkamran80 commented on entries/r/realestate.com.au.json
> +    ]
```suggestion
    ],
    "regions": [
      "au"
    ]
```

2024-06-03 00:38 UTC, fletcherdodd commented
> Do you know if their other sites (REA Group, realcommercial.com.au, PropTrack, etc.) use the same authentication backend?

Just realcommercial.com.au & property.com.au do. They direct you to id.realestate.com.au to authenicate. Should I just add the others as additional domains. Or adjust the name also?

2024-06-03 05:56 UTC, hkamran80 commented
> > Do you know if their other sites (REA Group, realcommercial.com.au, PropTrack, etc.) use the same authentication backend?
> 
> Just realcommercial.com.au & property.com.au do. They direct you to id.realestate.com.au to authenicate. Should I just add the others as additional domains. Or adjust the name also?

Adding them as additional domains should suffice.

2024-06-03 20:30 UTC, Carlgo11 approved these changes

2024-06-03 21:54 UTC, hkamran80 approved these changes

2024-06-03 21:54 UTC, merged