Add Origin Energy
2factorauth/twofactorauth pull request #8059
Opened 2024-05-31 07:55 UTC by fletcherdodd

2024-06-02 06:12 UTC, hkamran80 requested changes

2024-06-02 06:12 UTC, hkamran80 commented on entries/o/originenergy.com.au.json
> +    ]
```suggestion
    ],
    "regions": [
      "au"
    ]
```

2024-06-02 10:15 UTC, fletcherdodd commented on entries/o/originenergy.com.au.json
> +    ]
Oops, forgot to add that 😬

2024-06-03 20:32 UTC, Carlgo11 approved these changes

2024-06-03 21:55 UTC, hkamran80 approved these changes

2024-06-03 21:55 UTC, merged