Add Energy Australia
2factorauth/twofactorauth pull request #8060
Opened 2024-05-31 08:18 UTC by fletcherdodd

2024-06-02 06:16 UTC, hkamran80 requested changes
I can't find an actual SVG of their logo, so maybe extract the PNG from the SVG and just add that?

2024-06-02 06:16 UTC, hkamran80 commented on entries/e/energyaustralia.com.au.json
> +    ]
```suggestion
    ],
    "regions": [
      "au"
    ]
```

2024-06-02 10:18 UTC, fletcherdodd commented
> I can't find an actual SVG of their logo, so maybe extract the PNG from the SVG and just add that?

I removed the reference image in Illustrator and created a new path same as the image it was referencing. Everytime I export the SVG add adds the image reference back. So I'll export it as a PNG

2024-06-03 20:33 UTC, Carlgo11 requested changes
6KiB is a bit much for an icon :grimacing:
Try this 64x64px icon instead:
![energyaustralia com au](https://github.com/2factorauth/twofactorauth/assets/3535780/edc6f74a-49f9-4ae9-9123-38c324891c64)

2024-06-04 07:03 UTC, hkamran80 approved these changes

2024-06-04 18:24 UTC, Carlgo11 approved these changes

2024-06-04 18:24 UTC, merged