Add Boost Mobile
2factorauth/twofactorauth pull request #8106
Opened 2024-06-18 11:48 UTC by fletcherdodd

2024-06-18 22:24 UTC, Carlgo11 commented
Closing due to website rank

2024-06-19 07:25 UTC, fletcherdodd commented
Similar to #8112 the workflow seems to be checking the additional domains rank also. The main one is at 70K ([see here](https://www.similarweb.com/website/superloop.com/)).

2024-06-19 09:20 UTC, hkamran80 requested changes

2024-06-19 09:20 UTC, hkamran80 commented on entries/b/boost.com.au.json
> +  "Boost Mobile": {
```suggestion
  "Boost Mobile [AU]": {
```

The U.S. version of Boost Mobile is entirely separate to my knowledge

2024-06-22 09:06 UTC, hkamran80 approved these changes

2024-06-22 09:11 UTC, merged