Updated of LabCorp Patient entry
2factorauth/twofactorauth pull request #8118
Opened 2024-07-08 01:35 UTC by andbenn

LabCorp's Patient entry now supports 2FA.

2024-07-08 01:40 UTC, Carlgo11 requested changes

2024-07-08 01:40 UTC, Carlgo11 commented on entries/p/patient.labcorp.com.json
> +    "documentation: "https://patient.labcorp.com/help-center/q-and-a/8000/2"
Thanks for the pull request @andbenn!

Just a small correction to fix the syntax errors :wink: 
```suggestion
    ],
    "custom-software": [
      "Okta Verify"
    ],
    "documentation: "https://patient.labcorp.com/help-center/q-and-a/8000/2",
```

2024-07-08 03:26 UTC, andbenn commented
Updated.  The example I  was looking at wasn't complete.  Apologies.  Appears Ruby tests passed, not JavaScript or external tests.  Are those a concern?

2024-07-08 04:30 UTC, fletcherdodd commented on entries/p/patient.labcorp.com.json
> +    "documentation: "https://patient.labcorp.com/help-center/q-and-a/8000/2"
```suggestion
    "documentation": "https://patient.labcorp.com/help-center/q-and-a/8000/2",
```
This should fix the errors you're getting

2024-07-08 04:32 UTC, fletcherdodd commented on entries/p/patient.labcorp.com.json
> +    "documentation: "https://patient.labcorp.com/help-center/q-and-a/8000/2",
```suggestion
    "documentation": "https://patient.labcorp.com/help-center/q-and-a/8000/2",
```
This should fix the error you're getting. :)

2024-07-09 05:27 UTC, andbenn commented
Hello.  I'm not sure what I can do about the external tests that are blocking/failing.  What would the recommendation be?  I'm perplexed.

2024-07-09 05:34 UTC, hkamran80 commented
Feel free to correct me if I'm wrong, but IIRC Similarweb doesn't rank subdomains. We'll need to update the PR validator to fix that.

@Carlgo11 might be able to merge it anyway.

2024-07-09 23:04 UTC, Carlgo11 reviewed
The documentation link doesn't mention anything about the supported 2FA methods.
Could you please attach screenshots of the 2FA setup and/or login process where the different 2FA methods are visible.
> **Note** Remember to blur or crop out any personal information linked to you.

You can attach the screenshots here in a comment like this:
![screenshot](https://user-images.githubusercontent.com/3535780/187552643-08eea7e8-e6c6-4873-b31c-0faf4347f69f.gif)

2024-07-09 23:04 UTC, Carlgo11 commented on entries/p/patient.labcorp.com.json
> +    "documentation: "https://patient.labcorp.com/help-center/q-and-a/8000/2",
Found another syntax error 
```suggestion
    "documentation": "https://patient.labcorp.com/help-center/q-and-a/8000/2",
```

2024-07-10 00:22 UTC, hkamran80 commented
> The documentation link doesn't mention anything about the supported 2FA methods.

This [page](https://patient.labcorp.com/help-center/q-and-a/8000/1) does list the methods. I recommend changing the documentation URL to this one.

2024-07-11 17:32 UTC, andbenn commented
Updated the URL to the one @hkamran80 recommended.  This should be ready now.  Thanks all.

2024-07-11 17:53 UTC, Carlgo11 approved these changes
Thank you! 🙂
Your contribution will be visible in around 10 minutes. Sometimes, it takes longer to show up due to [server and browser caching](https://github.com/2factorauth/twofactorauth/wiki/FAQ-Caching).

2024-07-11 17:53 UTC, merged

2024-07-12 07:32 UTC, andbenn commented
Thanks for the help making this change.  Hope I can do some more in the near future.  The site is a goldmine and bookmarked.