Add railway.app
2factorauth/twofactorauth pull request #8132
Opened 2024-07-18 11:38 UTC by xmok

The icon used in the nav is same as the svg logo just scaled down.

2024-07-18 17:07 UTC, Carlgo11 requested changes

2024-07-18 17:07 UTC, Carlgo11 commented on img/r/railway.app.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="1024" height="1024" fill="none"><path fill="#fff" d="M4.756 438.175A520.713 520.713 0 0 0 0 489.735h777.799c-2.716-5.306-6.365-10.09-10.045-14.772-132.9
Just a minor change to fix the warning.
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024"><path fill="#fff" d="M5 438a521 521 0 0 0-5 52h778l-10-15C635 303 563 318 461 314c-34-2-57-2-193-2H39c-10 27-19 53-24 74h399v52H5Zm779 104H0l4 41h724c32 0 50-19 56-41ZM45 724s120 295 466 300c208 0 386-123 466-300H45ZM511 0A512 512 0 0 0 65 261l203-1c158 0 164 1 195 2l19 1c67 2 149 9 214 58 35 27 85 85 115 127 28 38 36 83 17 125-17 39-55 62-100 62H17l10 38h971a510 510 0 0 0 26-161C1024 229 795 0 511 0"/></svg>
```

2024-07-18 17:12 UTC, xmok commented
That's pretty cool! How did you know which changes to apply? Did you use a tool or was it just experience? Interested to know for future icons I might submit.

2024-07-18 19:51 UTC, Carlgo11 commented
@xmok I usually upload the image to [SVGOMG](https://jakearchibald.github.io/svgomg/) with all options except "_Remove xmlns_" enabled and the "_Number precision_" set to 1-2.

2024-07-20 17:22 UTC, Carlgo11 approved these changes

2024-07-20 17:22 UTC, merged