Updated 123-Reg.co.uk to include TOTP Support
2factorauth/twofactorauth pull request #8182
Opened 2024-08-31 12:43 UTC by dalDevelo

Updated 123-Reg.co.uk to include TOTP Support + Support URL for 2FA setup

<img width="537" alt="Screenshot 2024-08-31 at 01 10 20" src="https://github.com/user-attachments/assets/421e40d8-3a4b-4eec-9694-763b4c7a972c">

Apologies for the dupes 🤦🏻‍♂️ - Was unable to re-open.
[#8180 ](https://github.com/2factorauth/twofactorauth/pull/8180)
[#8181 ](https://github.com/2factorauth/twofactorauth/pull/8181)

2024-08-31 23:35 UTC, hkamran80 commented
> Apologies for the dupes 🤦🏻‍♂️ - Was unable to re-open.

No worries. I think you may have been unable to re-open them because the branch was deleted.

2024-08-31 23:40 UTC, hkamran80 requested changes

2024-08-31 23:40 UTC, hkamran80 commented on entries/1/123-reg.co.uk.json
> +      "totp"
```suggestion
      "sms",
      "totp",
      "u2f"
```

According to the documentation page, they support SMS and FIDO2 security keys as well.

2024-08-31 23:53 UTC, dalDevelo commented
Thank you, I'll try to be more thorough next time. I appreciate the edit 🙏🏼

2024-09-01 00:18 UTC, hkamran80 approved these changes

2024-09-01 00:18 UTC, hkamran80 commented
Perfect, thank you! Happy to help!

2024-09-01 00:18 UTC, merged