Update fidelity.com.json
2factorauth/twofactorauth pull request #8204
Opened 2024-09-21 21:09 UTC by prelanguage

No mentions of Symantec VIP access in linked documentation.  custom-software entry conflicting with 1Password ability to use totp QR codes.  Other methods may be available with Fidelity Netbenefits, which has its own entry within the directory.

2024-09-21 21:19 UTC, prelanguage commented
429 - Too many requests from https://pr-validator.2fa.directory/twofactorauth/8204/

URL returns:
Similarweb: fidelity.com ranked 315
Blocklist: fidelity.com not found in any list

Will rerun test if possible.

2024-09-21 21:43 UTC, prelanguage commented
Retriggered tests.  Success.

2024-09-22 01:28 UTC, hkamran80 commented
> No mentions of Symantec VIP access in linked documentation.  

Symantec VIP Access was deprecated with the release of TOTP MFA. You can't register VIP Access with Fidelity now, but you can continue to use it if you already activated it.

> custom-software entry conflicting with 1Password ability to use totp QR codes.

That is very weird. I would raise an issue with 1Password support about that.

2024-09-22 01:32 UTC, hkamran80 requested changes
Since Fidelity supports using their app as MFA (push notifications), the `custom-software` array should contain just their app.

2024-10-06 08:01 UTC, closed without merging