Update Australian Retirement Trust
2factorauth/twofactorauth pull request #8222
Opened 2024-10-17 09:46 UTC by Jawshy

Australian Retirement Trust (ART) supports SMS and email multi-factor authentication (MFA). 
No public documentation is available. Here is a secondary source: [Multi-Factor Authentication (MFA) can be enabled for Australian Retirement Trust](https://www.reddit.com/r/AusFinance/comments/1dqa7q9/multifactor_authentication_mfa_can_be_enabled_for/)
Members must contact ART by phone to enable, disable, or change MFA.

2024-10-17 09:56 UTC, Jawshy commented
![art-mfa](https://github.com/user-attachments/assets/9ef45c1b-02ab-4829-88d0-1c3aee4c3256)

2024-10-17 18:49 UTC, hkamran80 requested changes

2024-10-17 18:49 UTC, hkamran80 commented on entries/a/australianretirementtrust.com.au.json
> +    ],
```suggestion
    ],
    "notes": "Requires contacting customer service to activate",
```

There should be a message like this. If you have a better way of phrasing it, use that instead.

2024-10-19 02:42 UTC, hkamran80 approved these changes

2024-10-19 02:43 UTC, merged

2024-10-19 03:35 UTC, hkamran80 commented
Thank you! Your contribution will be visible in around 10 minutes, although it may take longer due to [server and browser caching](https://github.com/2factorauth/twofactorauth/wiki/FAQ-Caching).