Update BA
2factorauth/twofactorauth pull request #8236
Opened 2024-10-25 23:46 UTC by Carlgo11

Resolves #8235

2024-10-25 23:50 UTC, hkamran80 requested changes

2024-10-25 23:50 UTC, hkamran80 commented on entries/b/britishairways.com.json
> +    "note": "Set-up requires linking one of the following services with your BA account: Qatar, Iberia, Uber",
```suggestion
    "notes": "Set-up requires linking one of the following services with your BA account: Qatar, Iberia, Uber",
```

2024-10-25 23:56 UTC, hkamran80 approved these changes

2024-10-25 23:56 UTC, merged

2024-10-26 09:00 UTC, freshgoods commented on entries/b/britishairways.com.json
> +    "notes": "Set-up requires linking one of the following services with your BA account: Qatar, Iberia, Uber",
I personally didn't encounter this and don't have any of these linked. If it happens for some then I'd suggest changing the wording from "requires" to "may require".