Add gyazo.com
2factorauth/twofactorauth pull request #8262
Opened 2024-11-21 09:05 UTC by Yang-Nankai

Gyazo is a screenshot and image sharing platform that allows users to capture, upload, and share images or GIFs instantly. The platform provides 2FA for the account login verification process. The website is ranked 7,255 on [Similarweb](https://pro.similarweb.com/#/digitalsuite/websiteanalysis/overview/website-performance/*/999/1m?webSource=Total&key=gyazo.com). The website provides documentation on how to turn on 2FA.

2024-11-22 05:22 UTC, Carlgo11 requested changes
Here's an SVG icon you could use:
![icon](https://github.com/user-attachments/assets/3f852b0b-1f56-4a43-9a48-1ffa240d9e2e)

2024-11-22 05:24 UTC, Carlgo11 requested changes

2024-11-22 05:24 UTC, Carlgo11 commented on entries/g/gyazo.com.json
> +    "documentation": "https://help.gyazo.com/Two-step%20login%20verification-5ed8969fc1eca80023e84383",
```suggestion
    "documentation": "https://help.gyazo.com/--5ed8969fc1eca80023e84383",
```

2024-11-22 11:47 UTC, Carlgo11 commented on entries/g/gyazo.com.json
> +      "creativity"
From what I understand, Gyazo is a file sharing service, akin to Dropbox. If that's the case, _Backup and Sync_ would be a better fit.
```suggestion
      "backup"
```

2024-11-23 03:48 UTC, Yang-Nankai commented on entries/g/gyazo.com.json
> +      "creativity"
@Carlgo11 I see. Please forgive me for not being familiar with website classification. I thought this website was a service for sharing creative inspiration. However, I took a closer look and you are right. We are currently researching websites about 2FA, so we have sorted out a lot of websites. I am not very familiar with Github submissions, so thank you for correcting me in time! I have committed it again, hope your review!

2024-11-23 03:51 UTC, Yang-Nankai commented
I would also like to ask why there are sometimes problems with the _Action_ part in _External Tests_, but I tested the _curl_ statement and there is no problem locally. When I submit, do I need to ensure that both _Actions_ pass before requesting a review?

2024-11-23 03:57 UTC, Carlgo11 commented
@Yang-Nankai Error status 429 means the API is throttling requests. It usually happens when a lot of commits are made within a short time period.

It doesn't affect the ability for the PR to be merged.

2024-11-23 03:57 UTC, Carlgo11 approved these changes

2024-11-23 03:59 UTC, merged