Add nitrotype.com
2factorauth/twofactorauth pull request #8266
Opened 2024-11-23 05:08 UTC by Yang-Nankai

Nitro Type is an online multiplayer typing game that helps users improve their typing skills through competitive and engaging races. The platform provides 2FA for the account login verification process. The website is ranked 6,508 on [Similarweb](https://pro.similarweb.com/#/digitalsuite/websiteanalysis/overview/website-performance/*/999/1m?webSource=Total&key=nitrotype.com). The website provides documentation on how to turn on 2FA.

2024-11-23 14:22 UTC, Carlgo11 requested changes
Here's an SVG icon you can use:
![icon](https://github.com/user-attachments/assets/2381a89b-7ea6-4845-b3a0-deb23781f36a)

2024-11-23 14:22 UTC, Carlgo11 commented on entries/n/nitrotype.com.json
> +    "documentation": "https://www.nitrotype.com/news/read/254/secure-your-nitro-account-with-two-factor-authentication-2fa",
```suggestion
    "documentation": "https://www.nitrotype.com/news/read/254/-",
```

2024-11-23 16:41 UTC, Yang-Nankai commented
Thanks! I have revised the question you asked and committed again. 
p.s. I would like to ask where you found the SVG you provided, I tried to use a search engine to find it but I failed. ✋

2024-11-25 18:42 UTC, Carlgo11 commented
@Yang-Nankai I just copied the N from the logo on their website.
![image](https://github.com/user-attachments/assets/7c3fac34-463a-498e-8b57-9fa308be751e)

2024-11-25 18:42 UTC, Carlgo11 approved these changes

2024-11-25 18:43 UTC, merged