Add MEXC
2factorauth/twofactorauth pull request #8296
Opened 2024-12-03 02:47 UTC by Yang-Nankai

MEXC is a global cryptocurrency exchange platform that offers trading services for a wide range of digital assets, including spot, futures, and margin trading. The platform provides features like trading tools, security measures, and a user-friendly interface for crypto enthusiasts and traders. MEXC offers 2FA for the account login verification process. The website is ranked 2,747 on [Similarweb](https://pro.similarweb.com/#/digitalsuite/websiteanalysis/overview/website-performance/*/999/1m?webSource=Total&key=mexc.com). The website provides documentation on how to turn on 2FA.

2024-12-03 04:20 UTC, hkamran80 requested changes, later dismissed

2024-12-03 04:20 UTC, hkamran80 commented on entries/m/mexc.com.json
> +    ]
```suggestion
    ],
    "regions": [
      "-ca",
      "-cu",
      "-kp",
      "-hk",
      "-ir",
      "-cn",
      "-sg",
      "-sd",
      "-sy",
      "-gb",
      "-us",
    ]
```

I was able to get this from [the terms](https://www.mexc.com/terms) before being geoblocked.

> You must ensure that you are not resident of Prohibited Countries. Currently, MEXC does not provide Services, nor do we accept registration of Users or trade applications, in the following countries: North Korea, Cuba, Sudan, Syria, Iran, Mainland China, Singapore, the United States, the United Kingdom, Hong Kong, Russian-controlled regions of Ukraine (currently including the Crimea, Donetsk, and Luhansk regions), Sevastopol, and Canada (altogether referred to as 'Prohibited Countries'). For the sake of clarification, the Prohibited Countries list is non-exclusive and is subject to change, at any time and from time to time, by MEXC in its absolute sole discretion may decide, taking into account legal and compliance considerations. You understand and acknowledge that if it is determined that you have given false representations of your location or place of residence, we reserve the right to take any appropriate actions in compliance with applicable laws and regulations, including termination of any Account immediately and liquidating any open positions. You undertake to inform MEXC at the earliest possible opportunity if you have become resident in any of the foregoing Prohibited Countries.

2024-12-06 00:33 UTC, fletcherdodd commented on img/m/mexc.com.svg
> +<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 140 90"><path fill="#003087" d="m137.6 62.6-30.2-52.4c-6.6-11-22.8-11-29.2.5L46.5 65a15 15 0 0 0 13.3 22.6h63.6a16.6 16.6 0 0 0 14.2-25.1Z"/><path
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 139.8 85.8"><defs><linearGradient id="a" x1="37.8" x2="111.3" y1="44.7" y2="71.9" gradientUnits="userSpaceOnUse"><stop offset="0" stop-color="#003087" stop-opacity="0"/><stop offset="1" stop-color="#003087"/></linearGradient></defs><path fill="#003087" d="M137.5 60.6 107.3 8.2c-6.6-11-22.8-11-29.2.5L46.5 63a15 15 0 0 0 13.2 22.6h63.7a16.6 16.6 0 0 0 14.1-25.1"/><path fill="#1877f2" d="m94 64.7-2-3.2-5.5-9.6L60.9 7.5A16.7 16.7 0 0 0 32 9.3L2.2 60.8a16.7 16.7 0 0 0 14.6 25H123c-16.4 0-21.6-8.5-29-21"/><path fill="url(#a)" d="m94 64.5-2-3.2-5.5-9.6-16.5-29L46.3 63a15 15 0 0 0 13.2 22.6H123c-16.5-.1-21.6-8.5-29-21.2z"/></svg>
```
Fixing padding

2024-12-06 07:08 UTC, fletcherdodd approved these changes

2024-12-06 07:10 UTC, merged