Add Sezzle
2factorauth/twofactorauth pull request #8339
Opened 2024-12-15 03:02 UTC by Yang-Nankai

Sezzle is a fintech platform that provides a "Buy Now, Pay Later" solution, enabling consumers to make purchases and split the payment into interest-free installments. It partners with merchants to offer flexible payment options that improve customer satisfaction and increase sales. Sezzle is widely used across e-commerce platforms, offering easy integration and user-friendly payment management tools. The platform offers 2FA for the account login verification process. The website is ranked 25,498 on [Similarweb](https://pro.similarweb.com/#/digitalsuite/websiteanalysis/overview/website-performance/*/999/1m?webSource=Total&key=sezzle.com). The website provides documentation on how to turn on 2FA.

2024-12-15 03:02 UTC, Yang-Nankai commented
![image](https://github.com/user-attachments/assets/50eaf4dc-3aaa-45a7-b6fa-9d5d46785d17)
![image](https://github.com/user-attachments/assets/4ceaa3cc-7bff-4537-a25b-224334c6062e)

2024-12-17 04:45 UTC, hkamran80 requested changes

2024-12-17 04:45 UTC, hkamran80 commented on entries/s/sezzle.com.json
> +    "documentation": "https://merchant-help.sezzle.com/hc/sections/16790628725780",
```suggestion
    "documentation": "https://merchant-help.sezzle.com/hc/en-us/articles/16960335317908",
```

This page seems to be better.

2024-12-17 04:45 UTC, hkamran80 commented on entries/s/sezzle.com.json
> +    "notes": "Only merchants can enable 2FA.",
```suggestion
    "notes": "MFA is available for merchants only.",
```

2024-12-17 04:46 UTC, hkamran80 commented
I recommend submitting this to the [Passkeys Directory](https://github.com/2factorauth/passkeys) based on [this help page](https://merchant-help.sezzle.com/hc/en-us/articles/22057128759700).

2024-12-19 01:10 UTC, hkamran80 approved these changes

2024-12-19 01:10 UTC, merged